var annotated =
[
    [ "pairinteraction", "namespacepairinteraction.html", "namespacepairinteraction" ],
    [ "sqlite", "namespacesqlite.html", "namespacesqlite" ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "utils", "namespaceutils.html", "namespaceutils" ],
    [ "Basisnames", "classBasisnames.html", "classBasisnames" ],
    [ "BasisnamesOne", "classBasisnamesOne.html", "classBasisnamesOne" ],
    [ "BasisnamesTwo", "classBasisnamesTwo.html", "classBasisnamesTwo" ],
    [ "Configuration", "classConfiguration.html", "classConfiguration" ],
    [ "ConstIter", "classConstIter.html", "classConstIter" ],
    [ "Fixture", "structFixture.html", "structFixture" ],
    [ "Hamiltonian", "classHamiltonian.html", "classHamiltonian" ],
    [ "Hamiltonianmatrix", "classHamiltonianmatrix.html", "classHamiltonianmatrix" ],
    [ "HamiltonianOne", "classHamiltonianOne.html", "classHamiltonianOne" ],
    [ "HamiltonianTwo", "classHamiltonianTwo.html", "classHamiltonianTwo" ],
    [ "MatrixElements", "classMatrixElements.html", "classMatrixElements" ],
    [ "metaclass", "classmetaclass.html", null ],
    [ "MutableMapping", "classMutableMapping.html", null ],
    [ "no_defect", "structno__defect.html", "structno__defect" ],
    [ "Numerov", "classNumerov.html", "classNumerov" ],
    [ "QuantumDefect", "classQuantumDefect.html", "classQuantumDefect" ],
    [ "Serializable", "classSerializable.html", "classSerializable" ],
    [ "Serializer", "classSerializer.html", "classSerializer" ],
    [ "State", "classState.html", "classState" ],
    [ "StateOne", "classStateOne.html", "classStateOne" ],
    [ "StateTwo", "classStateTwo.html", "classStateTwo" ],
    [ "Symmetry", "structSymmetry.html", "structSymmetry" ],
    [ "Triple", "classTriple.html", "classTriple" ],
    [ "Whittaker", "classWhittaker.html", "classWhittaker" ]
];