pairinteraction: Numerov Class Reference
Numerov Class Reference
Numerov's method
#include <Wavefunction.h>
Public Member Functions
Numerov (QuantumDefect const &qd)
Constructor.
std::vector< real_t > axis () const
x values
std::vector< real_t > integrate ()
Perform the integration.
Static Public Member Functions
static constexpr int power_kernel (int power)
Power kernel for matrix elements.
Data Fields
real_t const dx
Integration step size.
Detailed Description
Numerov's method
This class implements Numerov's method using a couple of helper functions. Numerov's method solves a differential equation of the form
\[ y''(x) + g(x)y(x) = 0 \]
The equation is solved by iteratively computing
\[ y_{n+1} = \frac{\left(2 + \frac{5 h^2}{6} g_n \right) y_n - \left(1 + \frac{h^2}{12} g_{n-1} \right) y_{n-1}}{\left(1 + \frac{h^2}{12} g_n \right)} \]
with \(y_n = y(x_n) \) and \(g_n = g(x_n) \). Clearly this equation needs two initial conditions \(y_0 \) and \(y_1 \). We integrate the equation from outside to inside. Since the wavefunction hs to decay to zero at infinity we choose \(y_0 = 0 \). Now depending on the number of knots of wavefunction we decide whether to set \(y_1 = \pm\varepsilon \).
Definition at line 82 of file Wavefunction.h.
Constructor & Destructor Documentation
Numerov::Numerov (QuantumDefect const & qd)
Constructor.
The constructor initializes the qd member and sets the initial condition for the integrator. It determines the outer and inner integration bounds by semiclassical and empirical arguments.
Parameters
[in] qd Quantum defect data (parameters for the potentials)
Definition at line 52 of file Wavefunction.cpp.
References dx, QuantumDefect::l, and QuantumDefect::n.
Member Function Documentation
std::vector< real_t > Numerov::axis () const
x values
Returns the domain on which the wavefunction was evaluated.
Returns
vector with radial points
Definition at line 73 of file Wavefunction.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE().
std::vector< real_t > Numerov::integrate ()
Perform the integration.
This performs the integration using Numerov's method.
Returns
vector with wavefunction amplitude
Definition at line 79 of file Wavefunction.cpp.
References pairinteraction.unitmanagement::C(), dx, model_potential::g(), QuantumDefect::l, and QuantumDefect::n.
Referenced by BOOST_FIXTURE_TEST_CASE().
static constexpr int Numerov::power_kernel (int power) inline static
Power kernel for matrix elements.
The power kernel accounts for the fact that in Numerov's method the domain is square root scaled. This is important for the calculation of matrix elements.
Parameters
[in] power exponent of r
Returns
power kernel
Definition at line 124 of file Wavefunction.h.
Field Documentation
real_t const Numerov::dx
Integration step size.
Definition at line 87 of file Wavefunction.h.
Referenced by integrate(), and Numerov().
The documentation for this class was generated from the following files:
/travis/calc/Wavefunction.h
/travis/calc/Wavefunction.cpp