pairinteraction: sqlite::result Class Reference
sqlite::result Class Reference
Result table.
#include <SQLite.h>
Data Structures
class iterator
Table iterator.
class row
Row of the table.
Public Member Functions
result (char **azResult, int nRow, int nColumn)
Constructor.
size_t size () const
Number of rows.
result::iterator begin () const
Iterator pointing to the first row.
result::iterator end () const
Iterator pointing to the last row.
result::row first () const
First row.
result::row header () const
Header row.
result::row getRow (int pos) const
Get a specific row.
Detailed Description
Result table.
This object wraps the result table. It is iterable and can be used in range-based for loops.
Definition at line 77 of file SQLite.h.
Constructor & Destructor Documentation
sqlite::result::result (char ** azResult, int nRow, int nColumn) inline explicit
Constructor.
Construct the result table of a query.
Definition at line 192 of file SQLite.h.
Member Function Documentation
result::iterator sqlite::result::begin () const inline
Iterator pointing to the first row.
Returns
Iterator pointing to the first row
Definition at line 211 of file SQLite.h.
Referenced by BOOST_AUTO_TEST_CASE().
result::iterator sqlite::result::end () const inline
Iterator pointing to the last row.
Returns
Iterator pointing to the last row
Definition at line 220 of file SQLite.h.
result::row sqlite::result::first () const inline
First row.
Returns
First row
Definition at line 229 of file SQLite.h.
References getRow().
Referenced by BOOST_AUTO_TEST_CASE(), HamiltonianOne::build(), HamiltonianTwo::calculate(), and QuantumDefect::QuantumDefect().
result::row sqlite::result::getRow (int pos) const inline
Get a specific row.
Parameters
[in] pos position of the row
Returns
Specified row
Exceptions
sqlite_error
Definition at line 249 of file SQLite.h.
Referenced by first(), header(), and sqlite::result::iterator::operator*().
result::row sqlite::result::header () const inline
Header row.
Returns
Header row
Definition at line 238 of file SQLite.h.
References getRow().
size_t sqlite::result::size () const inline
Number of rows.
Returns
Number of rows
Definition at line 202 of file SQLite.h.
Referenced by BOOST_AUTO_TEST_CASE(), HamiltonianOne::build(), HamiltonianTwo::calculate(), and QuantumDefect::QuantumDefect().
The documentation for this class was generated from the following file:
/travis/calc/SQLite.h