pairinteraction: BasisnamesOne Class Reference
BasisnamesOne Class Reference
#include <Basisnames.h>
Public Member Functions
const std::vector< StateOne > & initial () const
void removeUnnecessaryStates (const std::vector< bool > &is_necessary)
bool constructedFromFirst ()
void save (std::string path)
Public Member Functions inherited from Basisnames< StateOne >
Basisnames ()
void configure (const Configuration &config)
size_t size () const
size_t dim () const
StateOne & get (size_t idx)
const StateOne & get (size_t idx) const
void set (size_t i, const StateOne &v)
ConstIter< Basisnames, StateOne > begin () const
ConstIter< Basisnames, StateOne > end () const
const Configuration & getConf () const
Static Public Member Functions
static BasisnamesOne fromStates (std::vector< StateOne > names)
static BasisnamesOne fromFirst (const Configuration &config)
static BasisnamesOne fromFirst (std::shared_ptr< const BasisnamesTwo > basis_two)
static BasisnamesOne fromSecond (const Configuration &config)
static BasisnamesOne fromSecond (std::shared_ptr< const BasisnamesTwo > basis_two)
static BasisnamesOne fromBoth (const Configuration &config)
Additional Inherited Members
Protected Attributes inherited from Basisnames< StateOne >
int delta_n
int delta_l
int delta_j
int delta_m
Configuration conf
std::vector< StateOne > names_
size_t dim_
Detailed Description
Definition at line 84 of file Basisnames.h.
Member Function Documentation
bool BasisnamesOne::constructedFromFirst ()
Definition at line 252 of file Basisnames.cpp.
BasisnamesOne BasisnamesOne::fromBoth (const Configuration & config) static
Definition at line 81 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateTwo::j, StateTwo::l, StateTwo::m, StateTwo::n, and StateTwo::order().
Referenced by main().
BasisnamesOne BasisnamesOne::fromFirst (const Configuration & config) static
Definition at line 27 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
Referenced by HamiltonianTwo::calculate(), and main().
BasisnamesOne BasisnamesOne::fromFirst (std::shared_ptr< const BasisnamesTwo > basis_two) static
Definition at line 40 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
BasisnamesOne BasisnamesOne::fromSecond (const Configuration & config) static
Definition at line 54 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
Referenced by HamiltonianTwo::calculate(), and main().
BasisnamesOne BasisnamesOne::fromSecond (std::shared_ptr< const BasisnamesTwo > basis_two) static
Definition at line 67 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
BasisnamesOne BasisnamesOne::fromStates (std::vector< StateOne > names) static
Definition at line 21 of file Basisnames.cpp.
References Basisnames< T >::dim_, and Basisnames< T >::names_.
Referenced by main().
const std::vector< StateOne > & BasisnamesOne::initial () const
Definition at line 228 of file Basisnames.cpp.
void BasisnamesOne::removeUnnecessaryStates (const std::vector< bool > & is_necessary)
Definition at line 231 of file Basisnames.cpp.
References Basisnames< StateOne >::dim_, and Basisnames< StateOne >::names_.
void BasisnamesOne::save (std::string path)
Definition at line 256 of file Basisnames.cpp.
The documentation for this class was generated from the following files:
/home/travis/build/pairinteraction/pairinteraction/calc/Basisnames.h
/home/travis/build/pairinteraction/pairinteraction/calc/Basisnames.cpp