pairinteraction: Configuration Class Reference
Configuration Class Reference
#include <ConfParser.h>
Data Structures
class const_iterator
class iterator
class value
Public Member Functions
void load_from_json (std::string filename)
void save_to_json (std::string filename)
Configuration::value & operator[] (const std::string &key)
const Configuration::value & operator[] (const std::string &key) const
size_t size () const
Configuration::iterator find (const std::string &key)
Configuration::const_iterator find (const std::string &key) const
Configuration::iterator begin ()
Configuration::iterator end ()
Configuration::const_iterator begin () const
Configuration::const_iterator end () const
bool operator== (const Configuration &rhs) const
Configuration & operator+= (const Configuration &rhs)
size_t count (const std::string &key) const
Configuration ()
Detailed Description
Definition at line 25 of file ConfParser.h.
Constructor & Destructor Documentation
Configuration()
Configuration::Configuration ()
Definition at line 147 of file ConfParser.cpp.
Member Function Documentation
begin() [1/2]
Configuration::iterator Configuration::begin ()
Definition at line 115 of file ConfParser.cpp.
begin() [2/2]
Configuration::const_iterator Configuration::begin () const
Definition at line 121 of file ConfParser.cpp.
count()
size_t Configuration::count (const std::string & key) const
Definition at line 144 of file ConfParser.cpp.
Referenced by main().
end() [1/2]
Configuration::iterator Configuration::end ()
Definition at line 118 of file ConfParser.cpp.
Referenced by operator==().
end() [2/2]
Configuration::const_iterator Configuration::end () const
Definition at line 124 of file ConfParser.cpp.
find() [1/2]
Configuration::iterator Configuration::find (const std::string & key)
Definition at line 108 of file ConfParser.cpp.
Referenced by operator==().
find() [2/2]
Configuration::const_iterator Configuration::find (const std::string & key) const
Definition at line 112 of file ConfParser.cpp.
load_from_json()
void Configuration::load_from_json (std::string filename)
Definition at line 73 of file ConfParser.cpp.
Referenced by HamiltonianOne::build(), HamiltonianTwo::calculate(), and main().
operator+=()
Configuration & Configuration::operator+= (const Configuration & rhs)
Definition at line 138 of file ConfParser.cpp.
operator==()
bool Configuration::operator== (const Configuration & rhs) const
Definition at line 127 of file ConfParser.cpp.
References end(), find(), size(), and Configuration::value::str().
operator[]() [1/2]
Configuration::value & Configuration::operator[] (const std::string & key)
Definition at line 99 of file ConfParser.cpp.
operator[]() [2/2]
const Configuration::value & Configuration::operator[] (const std::string & key) const
Definition at line 102 of file ConfParser.cpp.
save_to_json()
void Configuration::save_to_json (std::string filename)
Definition at line 86 of file ConfParser.cpp.
size()
size_t Configuration::size () const
Definition at line 105 of file ConfParser.cpp.
Referenced by operator==().
The documentation for this class was generated from the following files:
/travis/calc/ConfParser.h
/travis/calc/ConfParser.cpp