pairinteraction: Serializer Class Reference
Serializer Class Reference
#include <Serializable.h>
Public Member Functions
Serializer ()
void load (const bytes_t &bytes)
void save (bytes_t &bytes)
size_t position ()
Friends
template<class T >
void operator<< (Serializer &s, const T &data)
template<class T >
void operator<< (Serializer &s, const std::vector< T > &data)
template<class T >
void operator>> (Serializer &s, T &data)
template<class T >
void operator>> (Serializer &s, std::vector< T > &data)
Detailed Description
Definition at line 37 of file Serializable.h.
Constructor & Destructor Documentation
Serializer::Serializer () inline
Definition at line 39 of file Serializable.h.
Member Function Documentation
void Serializer::load (const bytes_t & bytes) inline
Definition at line 54 of file Serializable.h.
Referenced by Hamiltonianmatrix::doDeserialization().
size_t Serializer::position () inline
Definition at line 88 of file Serializable.h.
void Serializer::save (bytes_t & bytes) inline
Definition at line 60 of file Serializable.h.
Referenced by pairinteraction.utils.Wignerd::__del__(), and Hamiltonianmatrix::doSerialization().
Friends And Related Function Documentation
template<class T > void operator<< (Serializer & s, const T & data) friend
Definition at line 98 of file Serializable.h.
template<class T > void operator<< (Serializer & s, const std::vector< T > & data) friend
Definition at line 107 of file Serializable.h.
template<class T > void operator>> (Serializer & s, T & data) friend
Definition at line 116 of file Serializable.h.
template<class T > void operator>> (Serializer & s, std::vector< T > & data) friend
Definition at line 121 of file Serializable.h.
The documentation for this class was generated from the following file:
/travis/calc/Serializable.h