pairinteraction: BasisnamesTwo Class Reference
BasisnamesTwo Class Reference
#include <Basisnames.h>
Public Member Functions
BasisnamesTwo (std::shared_ptr< const BasisnamesOne > basis_one1, std::shared_ptr< const BasisnamesOne > basis_one2)
BasisnamesTwo (std::shared_ptr< const BasisnamesOne > basis_one1)
const StateTwo & initial () const
void removeUnnecessaryStates (const std::vector< bool > &isNecessary)
void removeUnnecessaryStatesKeepIdx (const std::vector< bool > &isNecessary)
void save (std::string path)
Public Member Functions inherited from Basisnames< StateTwo >
Basisnames ()
void configure (const Configuration &config)
size_t size () const
size_t dim () const
StateTwo & get (size_t idx)
const StateTwo & get (size_t idx) const
void set (size_t i, const StateTwo &v)
ConstIter< Basisnames, StateTwo > begin () const
ConstIter< Basisnames, StateTwo > end () const
const Configuration & getConf () const
Protected Member Functions
void build (StateTwo startstate, std::array< std::string, 2 > species, std::shared_ptr< const BasisnamesOne > basis_one1, std::shared_ptr< const BasisnamesOne > basis_one2)
Additional Inherited Members
Protected Attributes inherited from Basisnames< StateTwo >
int delta_n
int delta_l
int delta_j
int delta_m
Configuration conf
std::vector< StateTwo > names_
size_t dim_
Detailed Description
Definition at line 110 of file Basisnames.h.
Constructor & Destructor Documentation
BasisnamesTwo::BasisnamesTwo (std::shared_ptr< const BasisnamesOne > basis_one1, std::shared_ptr< const BasisnamesOne > basis_one2)
Definition at line 290 of file Basisnames.cpp.
References build(), Basisnames< StateTwo >::conf, Basisnames< StateTwo >::configure(), StateTwo::j, StateTwo::l, StateTwo::m, and StateTwo::n.
BasisnamesTwo::BasisnamesTwo (std::shared_ptr< const BasisnamesOne > basis_one1)
Definition at line 265 of file Basisnames.cpp.
References build(), Basisnames< StateTwo >::conf, Basisnames< StateTwo >::configure(), StateTwo::j, StateTwo::l, StateTwo::m, and StateTwo::n.
Member Function Documentation
void BasisnamesTwo::build (StateTwo startstate, std::array< std::string, 2 > species, std::shared_ptr< const BasisnamesOne > basis_one1, std::shared_ptr< const BasisnamesOne > basis_one2) protected
Definition at line 360 of file Basisnames.cpp.
References Basisnames< StateTwo >::conf, Basisnames< StateTwo >::dim_, State::idx, StateTwo::j, StateTwo::l, StateTwo::m, StateTwo::n, and Basisnames< StateTwo >::size().
Referenced by BasisnamesTwo().
const StateTwo & BasisnamesTwo::initial () const
Definition at line 316 of file Basisnames.cpp.
void BasisnamesTwo::removeUnnecessaryStates (const std::vector< bool > & isNecessary)
Definition at line 320 of file Basisnames.cpp.
References Basisnames< StateTwo >::dim_, State::idx, and Basisnames< StateTwo >::names_.
void BasisnamesTwo::removeUnnecessaryStatesKeepIdx (const std::vector< bool > & isNecessary)
Definition at line 346 of file Basisnames.cpp.
References Basisnames< StateTwo >::names_.
void BasisnamesTwo::save (std::string path)
Definition at line 397 of file Basisnames.cpp.
Referenced by pairinteraction.utils.Wignerd::__del__().
The documentation for this class was generated from the following files:
/travis/calc/Basisnames.h
/travis/calc/Basisnames.cpp