pairinteraction: Whittaker Class Reference
Whittaker Class Reference
#include <Wavefunction.h>
Public Member Functions
Whittaker (QuantumDefect const &qd)
Constructor.
std::vector< real_t > axis () const
x values
std::vector< real_t > integrate ()
Evaluate the radial wavefunction.
Static Public Member Functions
static constexpr real_t power_kernel (int power)
Power kernel for matrix elements.
Data Fields
real_t const dx
Integration step size.
Detailed Description
Definition at line 178 of file Wavefunction.h.
Constructor & Destructor Documentation
Whittaker::Whittaker (QuantumDefect const & qd)
Constructor.
The constructor initializes the qd member and sets the initial condition for the integrator. It determines the outer integration bound by semiclassical and empirical arguments. The inner intergration boundary is set to 1.
Parameters
[in] qd Quantum defect data (parameters for the potentials)
Definition at line 143 of file Wavefunction.cpp.
References dx, and QuantumDefect::n.
Member Function Documentation
std::vector< real_t > Whittaker::axis () const
x values
Returns the domain on which the wavefunction was evaluated.
Returns
vector with radial points
Definition at line 158 of file Wavefunction.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE().
std::vector< real_t > Whittaker::integrate ()
Evaluate the radial wavefunction.
This does not perform an integration but merely evaluates the Whittaker functions over the domain.
Returns
vector with wavefunction amplitude
Definition at line 164 of file Wavefunction.cpp.
References QuantumDefect::l, QuantumDefect::n, QuantumDefect::nstar, and whittaker_functions::RadialWFWhittaker().
Referenced by BOOST_FIXTURE_TEST_CASE().
static constexpr real_t Whittaker::power_kernel (int power) inline static
Power kernel for matrix elements.
The power kernel accounts for the fact that for the Whittaker functions the domain is linear scaled. This is important for the calculation of matrix elements.
Parameters
[in] power exponent of r
Returns
power kernel
Definition at line 222 of file Wavefunction.h.
Field Documentation
real_t const Whittaker::dx
Integration step size.
Definition at line 183 of file Wavefunction.h.
Referenced by Whittaker().
The documentation for this class was generated from the following files:
/travis/calc/Wavefunction.h
/travis/calc/Wavefunction.cpp