pairinteraction: Configuration::value Class Reference
Configuration::value Class Reference
#include <ConfParser.h>
Public Member Functions
value ()
value (std::stringstream const &val)
value (const Configuration::value &obj)
std::string str () const
void str (std::string s)
template<typename T >
Configuration::value & operator<< (const T &rhs)
template<typename T >
Configuration::value & operator>> (T &rhs)
template<typename T >
const Configuration::value & operator>> (T &rhs) const
template<typename T >
Configuration::value & operator= (const T &rhs)
Configuration::value & operator= (const Configuration::value &rhs)
Detailed Description
Definition at line 27 of file ConfParser.h.
Constructor & Destructor Documentation
value() [1/3]
Configuration::value::value ()
Definition at line 24 of file ConfParser.cpp.
value() [2/3]
Configuration::value::value (std::stringstream const & val)
Definition at line 26 of file ConfParser.cpp.
value() [3/3]
Configuration::value::value (const Configuration::value & obj) inline
Definition at line 31 of file ConfParser.h.
References str().
Member Function Documentation
operator<<()
template<typename T > Configuration::value& Configuration::value::operator<< (const T & rhs) inline
Definition at line 37 of file ConfParser.h.
operator=() [1/2]
template<typename T > Configuration::value& Configuration::value::operator= (const T & rhs) inline
Definition at line 54 of file ConfParser.h.
References str().
operator=() [2/2]
Configuration::value & Configuration::value::operator= (const Configuration::value & rhs)
Definition at line 35 of file ConfParser.cpp.
References str().
operator>>() [1/2]
template<typename T > Configuration::value& Configuration::value::operator>> (T & rhs) inline
Definition at line 42 of file ConfParser.h.
operator>>() [2/2]
template<typename T > const Configuration::value& Configuration::value::operator>> (T & rhs) const inline
Definition at line 47 of file ConfParser.h.
References str().
str() [1/2]
std::string Configuration::value::str () const
Definition at line 29 of file ConfParser.cpp.
Referenced by HamiltonianOne::build(), HamiltonianTwo::calculate(), operator=(), Configuration::operator==(), operator>>(), and value().
str() [2/2]
void Configuration::value::str (std::string s)
Definition at line 32 of file ConfParser.cpp.
The documentation for this class was generated from the following files:
/travis/calc/ConfParser.h
/travis/calc/ConfParser.cpp