pairinteraction: sqlite::handle Class Reference
sqlite::handle Class Reference
SQLite Database handle.
#include <SQLite.h>
Public Member Functions
handle (std::string const &filename)
Constructor.
handle (std::string const &filename, int flags)
Extended Constructor.
result query (std::string const &sql)
Place an SQLite query.
result query (std::stringstream const &ss)
Place an SQLite query.
void exec (std::string const &sql)
Execute SQLite statements.
void exec (std::stringstream const &ss)
Execute SQLite statements.
Detailed Description
SQLite Database handle.
This object handles the connection to the underlying SQLite databse. It provides a high-level object oriented RAII interface to the C-bindings of SQLite3.
Definition at line 277 of file SQLite.h.
Constructor & Destructor Documentation
handle() [1/2]
sqlite::handle::handle (std::string const & filename) inline explicit
Constructor.
This is the canonical constructor. It takes a filename and opens a database connection with the default parameters.
Parameters
[in] filename fully-qualified filename of the database
Definition at line 287 of file SQLite.h.
References sqlite::sqlite_error::sqlite_error().
handle() [2/2]
sqlite::handle::handle (std::string const & filename, int flags) inline explicit
Extended Constructor.
This is the alternative constructor. It takes a filename and a bitmask of parameters to open the database connection. This is useful if you have to open the connection, e.g., read-only.
Parameters
[in] filename fully-qualified filename of the database
[in] flags options to open the database (bitmask)
Exceptions
sqlite_error
Definition at line 310 of file SQLite.h.
References sqlite::sqlite_error::sqlite_error().
Member Function Documentation
exec() [1/2]
void sqlite::handle::exec (std::string const & sql) inline
Execute SQLite statements.
The SQL statements are passed to this function as a string (or stringstream) and are executed in-place. The string has to be prepared before passing to this function. This function discards the result table.
Parameters
[in] sql SQL statements
Exceptions
sqlite_error
Definition at line 373 of file SQLite.h.
References sqlite::sqlite_error::sqlite_error().
Referenced by BOOST_AUTO_TEST_CASE(), and MatrixElements::getRadial().
exec() [2/2]
void sqlite::handle::exec (std::stringstream const & ss) inline
Execute SQLite statements.
Definition at line 391 of file SQLite.h.
query() [1/2]
result sqlite::handle::query (std::string const & sql) inline
Place an SQLite query.
The SQL statements are passed to this function as a string (or stringstream) and are executed in-place. The string has to be prepared before passing to this function. The table containing the result is returned in an sqlite::result object.
Parameters
[in] sql SQL statements
Returns
result of the query
Exceptions
sqlite_error
Definition at line 334 of file SQLite.h.
References sqlite::sqlite_error::sqlite_error().
Referenced by BOOST_AUTO_TEST_CASE(), MatrixElements::getRadial(), and QuantumDefect::QuantumDefect().
query() [2/2]
result sqlite::handle::query (std::stringstream const & ss) inline
Place an SQLite query.
Definition at line 359 of file SQLite.h.
The documentation for this class was generated from the following file:
/travis/calc/SQLite.h