pairinteraction: HamiltonianOne Class Reference
HamiltonianOne Class Reference
#include <HamiltonianOne.h>
Public Member Functions
HamiltonianOne (const Configuration &config, boost::filesystem::path &path_cache, std::shared_ptr< BasisnamesOne > basis_one)
const Configuration & getConf () const
Public Member Functions inherited from Hamiltonian< BasisnamesOne >
Hamiltonian ()
std::shared_ptr
< Hamiltonianmatrix > get (size_t idx)
std::shared_ptr< const
Hamiltonianmatrix > get (size_t idx) const
std::shared_ptr< const
Configuration > getParams (size_t idx) const
size_t size () const
std::shared_ptr< const
BasisnamesOne > names () const
void removeUnnecessaryStates (std::vector< bool > &necessary)
Protected Member Functions
void changeToSpherical (real_t val_x, real_t val_y, real_t val_z, real_t &val_p, real_t &val_m, real_t &val_0)
void changeToSpherical (real_t val_x, real_t val_y, real_t val_z, std::complex< real_t > &val_p, std::complex< real_t > &val_m, std::complex< real_t > &val_0)
void configure (const Configuration &config)
void build ()
Additional Inherited Members
Protected Attributes inherited from Hamiltonian< BasisnamesOne >
std::vector< std::shared_ptr
< Hamiltonianmatrix > > matrix_diag
std::vector< std::string > matrix_path
std::vector< std::shared_ptr
< Configuration > > params
std::shared_ptr< BasisnamesOne > basis
Detailed Description
Definition at line 35 of file HamiltonianOne.h.
Constructor & Destructor Documentation
HamiltonianOne::HamiltonianOne (const Configuration & config, boost::filesystem::path & path_cache, std::shared_ptr< BasisnamesOne > basis_one)
Definition at line 20 of file HamiltonianOne.cpp.
References Hamiltonian< BasisnamesOne >::basis, build(), and configure().
Member Function Documentation
void HamiltonianOne::build () protected
Definition at line 82 of file HamiltonianOne.cpp.
References Hamiltonianmatrix::addBasis(), Hamiltonianmatrix::addEntries(), Hamiltonian< BasisnamesOne >::basis, changeToSpherical(), Hamiltonianmatrix::compress(), Hamiltonianmatrix::diagonalize(), energy_level(), sqlite::result::first(), MatrixElements::getDiamagnetism(), MatrixElements::getElectricMomentum(), MatrixElements::getMagneticMomentum(), Hamiltonianmatrix::load(), Configuration::load_from_json(), Hamiltonian< BasisnamesOne >::matrix_diag, Hamiltonian< BasisnamesOne >::matrix_path, Hamiltonianmatrix::num_basisvectors(), Hamiltonian< BasisnamesOne >::params, MatrixElements::precalculateDiamagnetism(), MatrixElements::precalculateElectricMomentum(), MatrixElements::precalculateMagneticMomentum(), Hamiltonianmatrix::save(), selectionRulesMomentum(), selectionRulesMultipole(), sqlite::result::size(), and Configuration::value::str().
Referenced by HamiltonianOne().
void HamiltonianOne::changeToSpherical (real_t val_x, real_t val_y, real_t val_z, real_t & val_p, real_t & val_m, real_t & val_0) protected
Definition at line 30 of file HamiltonianOne.cpp.
Referenced by build().
void HamiltonianOne::changeToSpherical (real_t val_x, real_t val_y, real_t val_z, std::complex< real_t > & val_p, std::complex< real_t > & val_m, std::complex< real_t > & val_0) protected
Definition at line 41 of file HamiltonianOne.cpp.
void HamiltonianOne::configure (const Configuration & config) protected
Definition at line 47 of file HamiltonianOne.cpp.
References Hamiltonian< BasisnamesOne >::basis.
Referenced by HamiltonianOne().
const Configuration & HamiltonianOne::getConf () const
Definition at line 26 of file HamiltonianOne.cpp.
The documentation for this class was generated from the following files:
/travis/calc/HamiltonianOne.h
/travis/calc/HamiltonianOne.cpp