pairinteraction: /travis/calc/MatrixElements.h File Reference
MatrixElements.h File Reference
#include "dtypes.h"
#include "Basisnames.h"
#include "Wavefunction.h"
#include "wignerSymbols/include/wignerSymbols/wignerSymbols-cpp.h"
#include <string>
#include <unordered_map>
#include <memory>
#include <sstream>
Data Structures
class MatrixElements
Functions
bool selectionRulesMomentum (StateOne const &state1, StateOne const &state2, int q)
bool selectionRulesMomentum (StateOne const &state1, StateOne const &state2)
bool selectionRulesMultipole (StateOne const &state1, StateOne const &state2, int kappa, int q)
bool selectionRulesMultipole (StateOne const &state1, StateOne const &state2, int kappa)
Function Documentation
selectionRulesMomentum() [1/2]
bool selectionRulesMomentum (StateOne const & state1, StateOne const & state2, int q)
Definition at line 26 of file MatrixElements.cpp.
References StateOne::j, StateOne::l, and StateOne::m.
Referenced by HamiltonianOne::build(), and MatrixElements::getRadial().
selectionRulesMomentum() [2/2]
bool selectionRulesMomentum (StateOne const & state1, StateOne const & state2)
Definition at line 34 of file MatrixElements.cpp.
References StateOne::j, StateOne::l, and StateOne::m.
selectionRulesMultipole() [1/2]
bool selectionRulesMultipole (StateOne const & state1, StateOne const & state2, int kappa, int q)
Definition at line 41 of file MatrixElements.cpp.
References StateOne::j, StateOne::l, and StateOne::m.
Referenced by HamiltonianOne::build(), HamiltonianTwo::calculate(), and MatrixElements::getRadial().
selectionRulesMultipole() [2/2]
bool selectionRulesMultipole (StateOne const & state1, StateOne const & state2, int kappa)
Definition at line 50 of file MatrixElements.cpp.
References StateOne::j, StateOne::l, and StateOne::m.