pairinteraction: pairinteraction.unitmanagement Namespace Reference
pairinteraction.unitmanagement Namespace Reference
Data Structures
class Quantity
class Units
Functions
def U (u)
def C (s)
Variables
ureg = UnitRegistry()
Q = ureg.Quantity
Function Documentation
C()
def pairinteraction.unitmanagement.C (s)
Definition at line 29 of file unitmanagement.py.
References pairinteraction.unitmanagement.Q.
Referenced by Numerov.integrate().
U()
def pairinteraction.unitmanagement.U (u)
Definition at line 25 of file unitmanagement.py.
Referenced by pairinteraction.unitmanagement.Quantity.toAU(), and pairinteraction.unitmanagement.Quantity.toUU().
Variable Documentation
Q
pairinteraction.unitmanagement.Q = ureg.Quantity
Definition at line 22 of file unitmanagement.py.
Referenced by pairinteraction.unitmanagement.C(), pairinteraction.unitmanagement.Quantity.toAU(), and pairinteraction.unitmanagement.Quantity.toUU().
ureg
pairinteraction.unitmanagement.ureg = UnitRegistry()
Definition at line 21 of file unitmanagement.py.