pairinteraction: whittaker_functions Namespace Reference
whittaker_functions Namespace Reference
Functions
real_t HypergeometricU (real_t a, real_t b, real_t z)
Compute the confluent hypergeometric function.
real_t WhittakerW (real_t k, real_t m, real_t z)
Compute the Whittaker function.
real_t RadialWFWhittaker (real_t r, real_t nu, int l)
Radial wavefunctions from Whittaker's function.
Function Documentation
HypergeometricU()
real_t whittaker_functions::HypergeometricU (real_t a, real_t b, real_t z)
Compute the confluent hypergeometric function.
This is merely a wrapper around gsl_sf_hyperg_U
Parameters
[in] a see documentation for gsl_sf_hyperg_U
[in] b see documentation for gsl_sf_hyperg_U
[in] z see documentation for gsl_sf_hyperg_U
Returns
U(a,b,z)
Definition at line 121 of file Wavefunction.cpp.
Referenced by Numerov::power_kernel(), and WhittakerW().
RadialWFWhittaker()
real_t whittaker_functions::RadialWFWhittaker (real_t r, real_t nu, int l)
Radial wavefunctions from Whittaker's function.
The radial wavefunction of the Schrödinger equation with the Coulomb potential can be expressed in terms of the Whittaker function.
\[ R_{\nu,l}(r) = \frac{1}{\sqrt{\nu^2 \Gamma(\nu+l+1) \Gamma(\nu-l)}} W_{\nu, l+1/2}\left(\frac{2r}{\nu}\right) \]
Parameters
[in] nu effective principal quantum number \(\nu = n - \delta_{n,l} \)
[in] l angular quantum number
[in] r radial position
Returns
R(nu,l,r)
Definition at line 134 of file Wavefunction.cpp.
References WhittakerW().
Referenced by Whittaker::integrate(), and Numerov::power_kernel().
WhittakerW()
real_t whittaker_functions::WhittakerW (real_t k, real_t m, real_t z)
Compute the Whittaker function.
The Whittaker function is defined in terms of the confluent hypergeometric function.
\[ W_{k,m}(z) = \mathrm{e}^{-z/2} z^{m+1/2} U\left(m-k+\frac{1}{2}, 1+2m, z\right) \]
Parameters
[in] k parameter k from Whittaker's equation
[in] m parameter m from Whittaker's equation
[in] z radial position
Returns
W(k,m,z)
Definition at line 128 of file Wavefunction.cpp.
References HypergeometricU().
Referenced by Numerov::power_kernel(), and RadialWFWhittaker().