pairinteraction: /travis/calc/unit_test/wavefunction_test.cpp File Reference
wavefunction_test.cpp File Reference
#include "SQLite.h"
#include "QuantumDefect.h"
#include "Wavefunction.h"
#include <boost/test/unit_test.hpp>
#include <iostream>
Data Structures
struct Fixture
Macros
#define BOOST_TEST_MODULE Wavefunctions test
Functions
BOOST_FIXTURE_TEST_CASE (model_potentials, Fixture)
BOOST_FIXTURE_TEST_CASE (numerovs_method, Fixture)
BOOST_FIXTURE_TEST_CASE (coulomb_functions, Fixture)
BOOST_FIXTURE_TEST_CASE (method_comparison, Fixture)
Macro Definition Documentation
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE Wavefunctions test
Definition at line 20 of file wavefunction_test.cpp.
Function Documentation
BOOST_FIXTURE_TEST_CASE() [1/4]
BOOST_FIXTURE_TEST_CASE (model_potentials , Fixture)
Definition at line 33 of file wavefunction_test.cpp.
References model_potential::g(), Fixture::qd, and model_potential::V().
BOOST_FIXTURE_TEST_CASE() [2/4]
BOOST_FIXTURE_TEST_CASE (numerovs_method , Fixture)
Definition at line 41 of file wavefunction_test.cpp.
References Numerov::axis(), Numerov::integrate(), QuantumDefect::n, and Fixture::qd.
BOOST_FIXTURE_TEST_CASE() [3/4]
BOOST_FIXTURE_TEST_CASE (coulomb_functions , Fixture)
Definition at line 57 of file wavefunction_test.cpp.
References Whittaker::axis(), Whittaker::integrate(), QuantumDefect::n, and Fixture::qd.
BOOST_FIXTURE_TEST_CASE() [4/4]
BOOST_FIXTURE_TEST_CASE (method_comparison , Fixture)
Definition at line 73 of file wavefunction_test.cpp.
References Whittaker::axis(), Whittaker::integrate(), and Fixture::qd.