pairinteraction: /travis/libpairinteraction/eigen/test/adjoint.cpp File Reference
adjoint.cpp File Reference
#include "main.h"
Data Structures
struct adjoint_specific< IsInteger >
struct adjoint_specific< true >
struct adjoint_specific< false >
Macros
#define EIGEN_NO_STATIC_ASSERT
Functions
template<typename MatrixType >
void adjoint (const MatrixType &m)
void test_adjoint ()
Macro Definition Documentation
EIGEN_NO_STATIC_ASSERT
#define EIGEN_NO_STATIC_ASSERT
Definition at line 10 of file adjoint.cpp.
Function Documentation
adjoint()
template<typename MatrixType > void adjoint (const MatrixType & m)
Definition at line 67 of file adjoint.cpp.
References abs(), c, cols, conj(), i, j, m1, m2(), rows, Eigen::TensorSycl::run(), size, square(), v1(), v2(), VERIFY_IS_APPROX, and VERIFY_IS_MUCH_SMALLER_THAN.
Referenced by Eigen::PartialPivLU< Matrix< Scalar, Dynamic, Dynamic > >::_solve_impl_transposed(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::adjointInPlace(), Eigen::internal::apply_block_householder_on_the_left(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresCycle(), Eigen::internal::gmres(), if(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::inverse(), mixingtypes(), product_extra(), product_notemporary(), product_selfadjoint(), selfadjointeigensolver(), svd_min_norm(), symm(), trmm(), and trmv().
test_adjoint()
void test_adjoint ()
Definition at line 149 of file adjoint.cpp.
References i.