var annotated_dup =
[
    [ "boost", "namespaceboost.html", null ],
    [ "Eigen", "namespaceEigen.html", "namespaceEigen" ],
    [ "gdb", "namespacegdb.html", "namespacegdb" ],
    [ "internal", "namespaceinternal.html", "namespaceinternal" ],
    [ "mpfr", "namespacempfr.html", "namespacempfr" ],
    [ "numpy", "namespacenumpy.html", "namespacenumpy" ],
    [ "sqlite", "namespacesqlite.html", "namespacesqlite" ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "testing", "namespacetesting.html", "namespacetesting" ],
    [ "traits", "namespacetraits.html", "namespacetraits" ],
    [ "utility", "namespaceutility.html", "namespaceutility" ],
    [ "utils", "namespaceutils.html", "namespaceutils" ],
    [ "zmq", "namespacezmq.html", "namespacezmq" ],
    [ "_Functor", "class__Functor.html", null ],
    [ "Action_aat_product", "classAction__aat__product.html", "classAction__aat__product" ],
    [ "Action_ata_product", "classAction__ata__product.html", "classAction__ata__product" ],
    [ "Action_atv_product", "classAction__atv__product.html", "classAction__atv__product" ],
    [ "Action_axpby", "classAction__axpby.html", "classAction__axpby" ],
    [ "Action_axpy", "classAction__axpy.html", "classAction__axpy" ],
    [ "Action_cholesky", "classAction__cholesky.html", "classAction__cholesky" ],
    [ "Action_ger", "classAction__ger.html", "classAction__ger" ],
    [ "Action_hessenberg", "classAction__hessenberg.html", "classAction__hessenberg" ],
    [ "Action_lu_decomp", "classAction__lu__decomp.html", "classAction__lu__decomp" ],
    [ "Action_lu_solve", "classAction__lu__solve.html", null ],
    [ "Action_matrix_matrix_product", "classAction__matrix__matrix__product.html", "classAction__matrix__matrix__product" ],
    [ "Action_matrix_matrix_product_bis", "classAction__matrix__matrix__product__bis.html", null ],
    [ "Action_matrix_vector_product", "classAction__matrix__vector__product.html", "classAction__matrix__vector__product" ],
    [ "Action_partial_lu", "classAction__partial__lu.html", "classAction__partial__lu" ],
    [ "Action_rot", "classAction__rot.html", "classAction__rot" ],
    [ "Action_symv", "classAction__symv.html", "classAction__symv" ],
    [ "Action_syr2", "classAction__syr2.html", "classAction__syr2" ],
    [ "action_t", "structaction__t.html", "structaction__t" ],
    [ "Action_tridiagonalization", "classAction__tridiagonalization.html", "classAction__tridiagonalization" ],
    [ "Action_trisolve", "classAction__trisolve.html", "classAction__trisolve" ],
    [ "Action_trisolve_matrix", "classAction__trisolve__matrix.html", "classAction__trisolve__matrix" ],
    [ "Action_trmm", "classAction__trmm.html", "classAction__trmm" ],
    [ "adjoint_specific", "structadjoint__specific.html", null ],
    [ "adjoint_specific< false >", "structadjoint__specific_3_01false_01_4.html", null ],
    [ "adjoint_specific< true >", "structadjoint__specific_3_01true_01_4.html", null ],
    [ "alt_prod", "structalt__prod.html", "structalt__prod" ],
    [ "Ball", "structBall.html", "structBall" ],
    [ "BallPointStuff", "structBallPointStuff.html", "structBallPointStuff" ],
    [ "Basisnames", "classBasisnames.html", "classBasisnames" ],
    [ "BasisnamesOne", "classBasisnamesOne.html", "classBasisnamesOne" ],
    [ "BasisnamesTwo", "classBasisnamesTwo.html", "classBasisnamesTwo" ],
    [ "BatchMatMul", "structBatchMatMul.html", "structBatchMatMul" ],
    [ "bench_impl", "structbench__impl.html", null ],
    [ "bench_impl< Transformation, 0 >", "structbench__impl_3_01Transformation_00_010_01_4.html", null ],
    [ "benchmark_t", "structbenchmark__t.html", "structbenchmark__t" ],
    [ "BenchmarkSuite", "classBenchmarkSuite.html", "classBenchmarkSuite" ],
    [ "Bennett5_functor", "structBennett5__functor.html", "structBennett5__functor" ],
    [ "BinaryOp", "classBinaryOp.html", null ],
    [ "blas_interface", "classblas__interface.html", null ],
    [ "blas_interface< SCALAR >", "classblas__interface_3_01SCALAR_01_4.html", null ],
    [ "blaze_interface", "classblaze__interface.html", "classblaze__interface" ],
    [ "blitz_interface", "classblitz__interface.html", "classblitz__interface" ],
    [ "blitz_LU_solve_interface", "classblitz__LU__solve__interface.html", "classblitz__LU__solve__interface" ],
    [ "BoxBOD_functor", "structBoxBOD__functor.html", "structBoxBOD__functor" ],
    [ "BtlConfig", "classBtlConfig.html", "classBtlConfig" ],
    [ "BtlString", "classBtlString.html", "classBtlString" ],
    [ "c_interface_base", "classc__interface__base.html", "classc__interface__base" ],
    [ "C_Map_MatrixXd", "structC__Map__MatrixXd.html", null ],
    [ "C_MatrixXd", "structC__MatrixXd.html", null ],
    [ "Cache", "classCache.html", "classCache" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "CastXpr", "structCastXpr.html", "structCastXpr" ],
    [ "checkIdx", "structcheckIdx.html", null ],
    [ "chwirut2_functor", "structchwirut2__functor.html", "structchwirut2__functor" ],
    [ "circulant_functor", "classcirculant__functor.html", "classcirculant__functor" ],
    [ "circulant_helper", "structcirculant__helper.html", "structcirculant__helper" ],
    [ "complex", "structcomplex.html", "structcomplex" ],
    [ "Configuration", "classConfiguration.html", "classConfiguration" ],
    [ "ConstFixedBlockXpr", "structConstFixedBlockXpr.html", "structConstFixedBlockXpr" ],
    [ "ConstFixedSegmentReturnType", "structConstFixedSegmentReturnType.html", "structConstFixedSegmentReturnType" ],
    [ "ConstIter", "classConstIter.html", "classConstIter" ],
    [ "ConstNColsBlockXpr", "structConstNColsBlockXpr.html", "structConstNColsBlockXpr" ],
    [ "ConstNRowsBlockXpr", "structConstNRowsBlockXpr.html", "structConstNRowsBlockXpr" ],
    [ "contributor", "structcontributor.html", "structcontributor" ],
    [ "CwiseClampOp", "structCwiseClampOp.html", "structCwiseClampOp" ],
    [ "DenseLM", "structDenseLM.html", "structDenseLM" ],
    [ "Depends", "structDepends.html", "structDepends" ],
    [ "deque", "classdeque.html", null ],
    [ "doublecomplex", "structdoublecomplex.html", "structdoublecomplex" ],
    [ "dummy_a", "structdummy__a.html", null ],
    [ "dummy_b", "structdummy__b.html", null ],
    [ "dummy_c", "structdummy__c.html", null ],
    [ "dummy_d", "structdummy__d.html", null ],
    [ "dummy_e", "structdummy__e.html", null ],
    [ "dummy_inst", "structdummy__inst.html", "structdummy__inst" ],
    [ "dummy_op", "structdummy__op.html", null ],
    [ "dummy_op< dummy_a, dummy_a >", "structdummy__op_3_01dummy__a_00_01dummy__a_01_4.html", "structdummy__op_3_01dummy__a_00_01dummy__a_01_4" ],
    [ "dummy_op< dummy_a, dummy_b >", "structdummy__op_3_01dummy__a_00_01dummy__b_01_4.html", "structdummy__op_3_01dummy__a_00_01dummy__b_01_4" ],
    [ "dummy_op< dummy_a, dummy_c >", "structdummy__op_3_01dummy__a_00_01dummy__c_01_4.html", "structdummy__op_3_01dummy__a_00_01dummy__c_01_4" ],
    [ "dummy_op< dummy_b, dummy_a >", "structdummy__op_3_01dummy__b_00_01dummy__a_01_4.html", "structdummy__op_3_01dummy__b_00_01dummy__a_01_4" ],
    [ "dummy_op< dummy_b, dummy_b >", "structdummy__op_3_01dummy__b_00_01dummy__b_01_4.html", "structdummy__op_3_01dummy__b_00_01dummy__b_01_4" ],
    [ "dummy_op< dummy_b, dummy_c >", "structdummy__op_3_01dummy__b_00_01dummy__c_01_4.html", "structdummy__op_3_01dummy__b_00_01dummy__c_01_4" ],
    [ "dummy_op< dummy_c, dummy_a >", "structdummy__op_3_01dummy__c_00_01dummy__a_01_4.html", "structdummy__op_3_01dummy__c_00_01dummy__a_01_4" ],
    [ "dummy_op< dummy_c, dummy_b >", "structdummy__op_3_01dummy__c_00_01dummy__b_01_4.html", "structdummy__op_3_01dummy__c_00_01dummy__b_01_4" ],
    [ "dummy_op< dummy_c, dummy_c >", "structdummy__op_3_01dummy__c_00_01dummy__c_01_4.html", "structdummy__op_3_01dummy__c_00_01dummy__c_01_4" ],
    [ "dummy_test", "structdummy__test.html", null ],
    [ "dummy_test< dummy_a, dummy_a >", "structdummy__test_3_01dummy__a_00_01dummy__a_01_4.html", null ],
    [ "dummy_test< dummy_b, dummy_b >", "structdummy__test_3_01dummy__b_00_01dummy__b_01_4.html", null ],
    [ "dummy_test< dummy_c, dummy_c >", "structdummy__test_3_01dummy__c_00_01dummy__c_01_4.html", null ],
    [ "eckerle4_functor", "structeckerle4__functor.html", "structeckerle4__functor" ],
    [ "eigen2_interface", "classeigen2__interface.html", "classeigen2__interface" ],
    [ "eigen3_interface", "classeigen3__interface.html", "classeigen3__interface" ],
    [ "EIGEN_ALIGNED_ALLOCATOR", "classEIGEN__ALIGNED__ALLOCATOR.html", null ],
    [ "enumerated_state", "classenumerated__state.html", "classenumerated__state" ],
    [ "EulerAngles", "classEulerAngles.html", "classEulerAngles" ],
    [ "EvalIterator", "classEvalIterator.html", null ],
    [ "evaluate_defaults_action_t", "structevaluate__defaults__action__t.html", "structevaluate__defaults__action__t" ],
    [ "FancySpheres", "classFancySpheres.html", "classFancySpheres" ],
    [ "FixedBlockXpr", "structFixedBlockXpr.html", "structFixedBlockXpr" ],
    [ "FixedSegmentReturnType", "structFixedSegmentReturnType.html", "structFixedSegmentReturnType" ],
    [ "Fixture", "structFixture.html", "structFixture" ],
    [ "Foo", "structFoo.html", "structFoo" ],
    [ "Frame", "classFrame.html", "classFrame" ],
    [ "func", "structfunc.html", null ],
    [ "func< res, arg1, arg2, TMATV >", "structfunc_3_01res_00_01arg1_00_01arg2_00_01TMATV_01_4.html", null ],
    [ "func< res, arg1, arg2, TMATVMAT >", "structfunc_3_01res_00_01arg1_00_01arg2_00_01TMATVMAT_01_4.html", null ],
    [ "func< res, arg1, arg2, TV >", "structfunc_3_01res_00_01arg1_00_01arg2_00_01TV_01_4.html", null ],
    [ "Functor", "structFunctor.html", "structFunctor" ],
    [ "general_matrix_vector_product_wrapper", "structgeneral__matrix__vector__product__wrapper.html", null ],
    [ "generateTestMatrix", "structgenerateTestMatrix.html", null ],
    [ "generateTestMatrix< MatrixType, 0 >", "structgenerateTestMatrix_3_01MatrixType_00_010_01_4.html", null ],
    [ "generateTestMatrix< MatrixType, 1 >", "structgenerateTestMatrix_3_01MatrixType_00_011_01_4.html", null ],
    [ "Generator1D", "structGenerator1D.html", "structGenerator1D" ],
    [ "Generator2D", "structGenerator2D.html", "structGenerator2D" ],
    [ "get_dim", "structget__dim.html", "structget__dim" ],
    [ "get_dim< Matrix< S, R, C, O, MR, MC > >", "structget__dim_3_01Matrix_3_01S_00_01R_00_01C_00_01O_00_01MR_00_01MC_01_4_01_4.html", "structget__dim_3_01Matrix_3_01S_00_01R_00_01C_00_01O_00_01MR_00_01MC_01_4_01_4" ],
    [ "GetDifferentType", "structGetDifferentType.html", null ],
    [ "GetDifferentType< double >", "structGetDifferentType_3_01double_01_4.html", "structGetDifferentType_3_01double_01_4" ],
    [ "GetDifferentType< float >", "structGetDifferentType_3_01float_01_4.html", "structGetDifferentType_3_01float_01_4" ],
    [ "GetDifferentType< std::complex< T > >", "structGetDifferentType_3_01std_1_1complex_3_01T_01_4_01_4.html", "structGetDifferentType_3_01std_1_1complex_3_01T_01_4_01_4" ],
    [ "GlMatrixHelper", "structGlMatrixHelper.html", null ],
    [ "GlMatrixHelper< false, _Flags >", "structGlMatrixHelper_3_01false_00_01__Flags_01_4.html", null ],
    [ "GlMatrixHelper< true, _Flags >", "structGlMatrixHelper_3_01true_00_01__Flags_01_4.html", null ],
    [ "gmm_interface", "classgmm__interface.html", "classgmm__interface" ],
    [ "GpuHelper", "classGpuHelper.html", "classGpuHelper" ],
    [ "hahn1_functor", "structhahn1__functor.html", "structhahn1__functor" ],
    [ "Hamiltonian", "classHamiltonian.html", "classHamiltonian" ],
    [ "Hamiltonianmatrix", "classHamiltonianmatrix.html", "classHamiltonianmatrix" ],
    [ "HamiltonianOne", "classHamiltonianOne.html", "classHamiltonianOne" ],
    [ "HamiltonianTwo", "classHamiltonianTwo.html", "classHamiltonianTwo" ],
    [ "human_duration_t", "structhuman__duration__t.html", "structhuman__duration__t" ],
    [ "hybrd_functor", "structhybrd__functor.html", "structhybrd__functor" ],
    [ "hybrj_functor", "structhybrj__functor.html", "structhybrj__functor" ],
    [ "IcoSphere", "classIcoSphere.html", "classIcoSphere" ],
    [ "indexing_functor", "classindexing__functor.html", "classindexing__functor" ],
    [ "init", "structinit.html", "structinit" ],
    [ "inputfile_entry_t", "structinputfile__entry__t.html", "structinputfile__entry__t" ],
    [ "inputfile_t", "structinputfile__t.html", "structinputfile__t" ],
    [ "InsertZeros", "structInsertZeros.html", "structInsertZeros" ],
    [ "iters_before_test", "structiters__before__test.html", "structiters__before__test" ],
    [ "iters_before_test< double >", "structiters__before__test_3_01double_01_4.html", "structiters__before__test_3_01double_01_4" ],
    [ "lanczos1_functor", "structlanczos1__functor.html", "structlanczos1__functor" ],
    [ "LhsIterator", "classLhsIterator.html", null ],
    [ "Lib_Mean", "classLib__Mean.html", "classLib__Mean" ],
    [ "list", "classlist.html", null ],
    [ "lmder_functor", "structlmder__functor.html", "structlmder__functor" ],
    [ "lmdif_functor", "structlmdif__functor.html", "structlmdif__functor" ],
    [ "lmstr_functor", "structlmstr__functor.html", "structlmstr__functor" ],
    [ "loop_on_k", "structloop__on__k.html", null ],
    [ "loop_on_k< M, N, END >", "structloop__on__k_3_01M_00_01N_00_01END_01_4.html", null ],
    [ "loop_on_m", "structloop__on__m.html", null ],
    [ "loop_on_m< END, N, K >", "structloop__on__m_3_01END_00_01N_00_01K_01_4.html", null ],
    [ "loop_on_n", "structloop__on__n.html", null ],
    [ "loop_on_n< M, END, K, Scalar, Mode >", "structloop__on__n_3_01M_00_01END_00_01K_00_01Scalar_00_01Mode_01_4.html", null ],
    [ "MakeComplexOp", "structMakeComplexOp.html", "structMakeComplexOp" ],
    [ "MandelbrotThread", "classMandelbrotThread.html", "classMandelbrotThread" ],
    [ "MandelbrotWidget", "classMandelbrotWidget.html", "classMandelbrotWidget" ],
    [ "map_size", "structmap__size.html", "structmap__size" ],
    [ "map_size< 10 >", "structmap__size_3_0110_01_4.html", "structmap__size_3_0110_01_4" ],
    [ "map_size< 11 >", "structmap__size_3_0111_01_4.html", "structmap__size_3_0111_01_4" ],
    [ "map_size< 12 >", "structmap__size_3_0112_01_4.html", "structmap__size_3_0112_01_4" ],
    [ "map_size< 13 >", "structmap__size_3_0113_01_4.html", "structmap__size_3_0113_01_4" ],
    [ "mapstaticmethods_impl", "structmapstaticmethods__impl.html", null ],
    [ "mapstaticmethods_impl< PlainObjectType, false, IsVector >", "structmapstaticmethods__impl_3_01PlainObjectType_00_01false_00_01IsVector_01_4.html", null ],
    [ "mapstaticmethods_impl< PlainObjectType, true, false >", "structmapstaticmethods__impl_3_01PlainObjectType_00_01true_00_01false_01_4.html", null ],
    [ "mapstaticmethods_impl< PlainObjectType, true, true >", "structmapstaticmethods__impl_3_01PlainObjectType_00_01true_00_01true_01_4.html", null ],
    [ "MatrixElements", "classMatrixElements.html", "classMatrixElements" ],
    [ "MatrixReplacement", "classMatrixReplacement.html", "classMatrixReplacement" ],
    [ "measure_all_pot_sizes_action_t", "structmeasure__all__pot__sizes__action__t.html", "structmeasure__all__pot__sizes__action__t" ],
    [ "measure_default_sizes_action_t", "structmeasure__default__sizes__action__t.html", "structmeasure__default__sizes__action__t" ],
    [ "MGH09_functor", "structMGH09__functor.html", "structMGH09__functor" ],
    [ "MGH10_functor", "structMGH10__functor.html", "structMGH10__functor" ],
    [ "MGH17_functor", "structMGH17__functor.html", "structMGH17__functor" ],
    [ "misra1a_functor", "structmisra1a__functor.html", "structmisra1a__functor" ],
    [ "misra1d_functor", "structmisra1d__functor.html", "structmisra1d__functor" ],
    [ "Mixed_Perf_Analyzer", "classMixed__Perf__Analyzer.html", "classMixed__Perf__Analyzer" ],
    [ "mtl4_interface", "classmtl4__interface.html", "classmtl4__interface" ],
    [ "my_exception", "structmy__exception.html", "structmy__exception" ],
    [ "my_functor", "structmy__functor.html", "structmy__functor" ],
    [ "MyClassA", "classMyClassA.html", "classMyClassA" ],
    [ "MyGenerator", "structMyGenerator.html", "structMyGenerator" ],
    [ "MyStruct", "structMyStruct.html", "structMyStruct" ],
    [ "MyVectorType", "classMyVectorType.html", "classMyVectorType" ],
    [ "NColsBlockXpr", "structNColsBlockXpr.html", "structNColsBlockXpr" ],
    [ "no_defect", "structno__defect.html", "structno__defect" ],
    [ "NRowsBlockXpr", "structNRowsBlockXpr.html", "structNRowsBlockXpr" ],
    [ "Numerov", "classNumerov.html", "classNumerov" ],
    [ "other_matrix_type", "structother__matrix__type.html", "structother__matrix__type" ],
    [ "other_matrix_type< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >", "structother__matrix__type_3_01Matrix_3_01__Scalar_00_01__Rows_00_01__Cols_00_01__Options_00_01__a5698b8ba35a3adbe69de076e1ee484f.html", "structother__matrix__type_3_01Matrix_3_01__Scalar_00_01__Rows_00_01__Cols_00_01__Options_00_01__a5698b8ba35a3adbe69de076e1ee484f" ],
    [ "packet_helper", "structpacket__helper.html", "structpacket__helper" ],
    [ "packet_helper< false, Packet >", "structpacket__helper_3_01false_00_01Packet_01_4.html", "structpacket__helper_3_01false_00_01Packet_01_4" ],
    [ "partition_action_t", "structpartition__action__t.html", "structpartition__action__t" ],
    [ "PointPointMinimizer", "structPointPointMinimizer.html", "structPointPointMinimizer" ],
    [ "Portable_Perf_Analyzer", "classPortable__Perf__Analyzer.html", "classPortable__Perf__Analyzer" ],
    [ "Portable_Timer", "classPortable__Timer.html", "classPortable__Timer" ],
    [ "preprocessed_inputfile_entry_t", "structpreprocessed__inputfile__entry__t.html", "structpreprocessed__inputfile__entry__t" ],
    [ "preprocessed_inputfile_t", "structpreprocessed__inputfile__t.html", "structpreprocessed__inputfile__t" ],
    [ "print_n", "structprint__n.html", null ],
    [ "print_n< END >", "structprint__n_3_01END_01_4.html", null ],
    [ "processTriangularMatrix", "structprocessTriangularMatrix.html", null ],
    [ "processTriangularMatrix< MatrixType, 0 >", "structprocessTriangularMatrix_3_01MatrixType_00_010_01_4.html", null ],
    [ "ProductBase", "classProductBase.html", null ],
    [ "prune_column", "structprune__column.html", "structprune__column" ],
    [ "QGLWidget", "classQGLWidget.html", null ],
    [ "QMainWindow", "classQMainWindow.html", null ],
    [ "QThread", "classQThread.html", null ],
    [ "QuantumDefect", "classQuantumDefect.html", "classQuantumDefect" ],
    [ "QuaternionDemo", "classQuaternionDemo.html", "classQuaternionDemo" ],
    [ "QWidget", "classQWidget.html", null ],
    [ "randomMatrixWithImagEivals", "structrandomMatrixWithImagEivals.html", null ],
    [ "randomMatrixWithImagEivals< MatrixType, 0 >", "structrandomMatrixWithImagEivals_3_01MatrixType_00_010_01_4.html", null ],
    [ "randomMatrixWithImagEivals< MatrixType, 1 >", "structrandomMatrixWithImagEivals_3_01MatrixType_00_011_01_4.html", null ],
    [ "rat42_functor", "structrat42__functor.html", "structrat42__functor" ],
    [ "rat43_functor", "structrat43__functor.html", "structrat43__functor" ],
    [ "RenderingWidget", "classRenderingWidget.html", "classRenderingWidget" ],
    [ "root_type", "classinternal_1_1tensor__symmetry__pre__analysis_1_1root__type.html", null ],
    [ "scalar_norm1_op", "structscalar__norm1__op.html", "structscalar__norm1__op" ],
    [ "ScalarWithExceptions", "classScalarWithExceptions.html", "classScalarWithExceptions" ],
    [ "Scaling", "classScaling.html", null ],
    [ "Serializable", "classSerializable.html", "classSerializable" ],
    [ "Serializer", "classSerializer.html", "classSerializer" ],
    [ "size_triple_t", "structsize__triple__t.html", "structsize__triple__t" ],
    [ "some_non_vectorizable_type", "structsome__non__vectorizable__type.html", "structsome__non__vectorizable__type" ],
    [ "sparseGaussianTest", "structsparseGaussianTest.html", "structsparseGaussianTest" ],
    [ "SparseLUImpl", "classSparseLUImpl.html", null ],
    [ "SparseXprInnerIterator", "classSparseXprInnerIterator.html", null ],
    [ "State", "classState.html", "classState" ],
    [ "StateOne", "classStateOne.html", "classStateOne" ],
    [ "states_set", "structstates__set.html", "structstates__set" ],
    [ "StateTwo", "classStateTwo.html", "classStateTwo" ],
    [ "static_size_generator", "structstatic__size__generator.html", null ],
    [ "static_size_generator< 1, Perf_Analyzer, Action, Interface >", "structstatic__size__generator_3_011_00_01Perf__Analyzer_00_01Action_00_01Interface_01_4.html", null ],
    [ "STL_interface", "classSTL__interface.html", "classSTL__interface" ],
    [ "STL_Perf_Analyzer", "classSTL__Perf__Analyzer.html", "classSTL__Perf__Analyzer" ],
    [ "STL_Timer", "classSTL__Timer.html", "classSTL__Timer" ],
    [ "Symmetry", "structSymmetry.html", "structSymmetry" ],
    [ "SystemBase", "classSystemBase.html", "classSystemBase" ],
    [ "SystemOne", "classSystemOne.html", "classSystemOne" ],
    [ "SystemTwo", "classSystemTwo.html", "classSystemTwo" ],
    [ "tensor_interface", "classtensor__interface.html", "classtensor__interface" ],
    [ "TensorAssign", "classTensorAssign.html", null ],
    [ "TensorBroadcasting", "classTensorBroadcasting.html", null ],
    [ "TensorContraction", "classTensorContraction.html", null ],
    [ "TensorConvolution", "classTensorConvolution.html", null ],
    [ "TensorExecutor", "classTensorExecutor.html", null ],
    [ "TensorExpr", "classTensorExpr.html", null ],
    [ "TensorForcedEval", "classTensorForcedEval.html", null ],
    [ "TensorForcedEval", "classTensorForcedEval.html", null ],
    [ "TensorGenerator", "classTensorGenerator.html", null ],
    [ "TensorImagePatch", "classTensorImagePatch.html", null ],
    [ "TensorIndexTuple", "classTensorIndexTuple.html", null ],
    [ "TensorInflation", "classTensorInflation.html", null ],
    [ "TensorKChippingReshaping", "classTensorKChippingReshaping.html", null ],
    [ "TensorLayoutSwap", "classTensorLayoutSwap.html", null ],
    [ "TensorPadding", "classTensorPadding.html", null ],
    [ "TensorPatch", "classTensorPatch.html", null ],
    [ "TensorReduction", "classTensorReduction.html", null ],
    [ "TensorReshaping", "classTensorReshaping.html", null ],
    [ "TensorReverse", "classTensorReverse.html", null ],
    [ "TensorScan", "classTensorScan.html", null ],
    [ "TensorShuffling", "classTensorShuffling.html", null ],
    [ "TensorSlicing", "classTensorSlicing.html", null ],
    [ "TensorStriding", "classTensorStriding.html", null ],
    [ "TensorTupleIndex", "classTensorTupleIndex.html", null ],
    [ "TensorVolumePatch", "classTensorVolumePatch.html", null ],
    [ "test_block_recursion", "structtest__block__recursion.html", null ],
    [ "test_block_recursion<-1 >", "structtest__block__recursion_3-1_01_4.html", null ],
    [ "test_transform", "structtest__transform.html", null ],
    [ "TestFunc1", "structTestFunc1.html", "structTestFunc1" ],
    [ "TestNew1", "structTestNew1.html", "structTestNew1" ],
    [ "TestNew2", "structTestNew2.html", "structTestNew2" ],
    [ "TestNew3", "structTestNew3.html", "structTestNew3" ],
    [ "TestNew4", "structTestNew4.html", "structTestNew4" ],
    [ "TestNew5", "structTestNew5.html", "structTestNew5" ],
    [ "TestNew6", "structTestNew6.html", "structTestNew6" ],
    [ "TestQueue", "structTestQueue.html", "structTestQueue" ],
    [ "thurber_functor", "structthurber__functor.html", "structthurber__functor" ],
    [ "times2_op", "structtimes2__op.html", null ],
    [ "tiny_blitz_interface", "classtiny__blitz__interface.html", "classtiny__blitz__interface" ],
    [ "ToRotationMatrixWrapper", "structToRotationMatrixWrapper.html", "structToRotationMatrixWrapper" ],
    [ "Trackball", "classTrackball.html", "classTrackball" ],
    [ "TreeTest", "structTreeTest.html", "structTreeTest" ],
    [ "Triple", "classTriple.html", "classTriple" ],
    [ "tvmet_interface", "classtvmet__interface.html", "classtvmet__interface" ],
    [ "type", "classinternal_1_1TransposeImpl__base_1_1type.html", null ],
    [ "ublas_interface", "classublas__interface.html", "classublas__interface" ],
    [ "UserReducer", "structUserReducer.html", "structUserReducer" ],
    [ "vector", "classvector.html", null ],
    [ "vectorization_logic", "structvectorization__logic.html", "structvectorization__logic" ],
    [ "vectorization_logic< Scalar, false >", "structvectorization__logic_3_01Scalar_00_01false_01_4.html", null ],
    [ "vectorization_logic_half", "structvectorization__logic__half.html", "structvectorization__logic__half" ],
    [ "vectorization_logic_half< Scalar, false >", "structvectorization__logic__half_3_01Scalar_00_01false_01_4.html", null ],
    [ "VectorType", "structVectorType.html", null ],
    [ "VectorType< EigenVectorContainer, Scalar >", "structVectorType_3_01EigenVectorContainer_00_01Scalar_01_4.html", "structVectorType_3_01EigenVectorContainer_00_01Scalar_01_4" ],
    [ "VectorType< StdVectorContainer, Scalar >", "structVectorType_3_01StdVectorContainer_00_01Scalar_01_4.html", "structVectorType_3_01StdVectorContainer_00_01Scalar_01_4" ],
    [ "Whittaker", "classWhittaker.html", "classWhittaker" ],
    [ "WignerD", "classWignerD.html", "classWignerD" ],
    [ "Wrapper", "structWrapper.html", "structWrapper" ],
    [ "X86_Perf_Analyzer", "classX86__Perf__Analyzer.html", "classX86__Perf__Analyzer" ],
    [ "X86_Timer", "classX86__Timer.html", "classX86__Timer" ]
];