pairinteraction: /travis/libpairinteraction/eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h File Reference
ArrayCwiseUnaryOps.h File Reference
Typedefs
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > AbsReturnType
typedef CwiseUnaryOp< internal::scalar_arg_op< Scalar >, const Derived > ArgReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > Abs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > SqrtReturnType
typedef CwiseUnaryOp< internal::scalar_rsqrt_op< Scalar >, const Derived > RsqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > SignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > InverseReturnType
typedef CwiseUnaryOp< internal::scalar_boolean_not_op< Scalar >, const Derived > BooleanNotReturnType
typedef CwiseUnaryOp< internal::scalar_exp_op< Scalar >, const Derived > ExpReturnType
typedef CwiseUnaryOp< internal::scalar_log_op< Scalar >, const Derived > LogReturnType
typedef CwiseUnaryOp< internal::scalar_log1p_op< Scalar >, const Derived > Log1pReturnType
typedef CwiseUnaryOp< internal::scalar_log10_op< Scalar >, const Derived > Log10ReturnType
typedef CwiseUnaryOp< internal::scalar_cos_op< Scalar >, const Derived > CosReturnType
typedef CwiseUnaryOp< internal::scalar_sin_op< Scalar >, const Derived > SinReturnType
typedef CwiseUnaryOp< internal::scalar_tan_op< Scalar >, const Derived > TanReturnType
typedef CwiseUnaryOp< internal::scalar_acos_op< Scalar >, const Derived > AcosReturnType
typedef CwiseUnaryOp< internal::scalar_asin_op< Scalar >, const Derived > AsinReturnType
typedef CwiseUnaryOp< internal::scalar_atan_op< Scalar >, const Derived > AtanReturnType
typedef CwiseUnaryOp< internal::scalar_tanh_op< Scalar >, const Derived > TanhReturnType
typedef CwiseUnaryOp< internal::scalar_sinh_op< Scalar >, const Derived > SinhReturnType
typedef CwiseUnaryOp< internal::scalar_cosh_op< Scalar >, const Derived > CoshReturnType
typedef CwiseUnaryOp< internal::scalar_square_op< Scalar >, const Derived > SquareReturnType
typedef CwiseUnaryOp< internal::scalar_cube_op< Scalar >, const Derived > CubeReturnType
typedef CwiseUnaryOp< internal::scalar_round_op< Scalar >, const Derived > RoundReturnType
typedef CwiseUnaryOp< internal::scalar_floor_op< Scalar >, const Derived > FloorReturnType
typedef CwiseUnaryOp< internal::scalar_ceil_op< Scalar >, const Derived > CeilReturnType
typedef CwiseUnaryOp< internal::scalar_isnan_op< Scalar >, const Derived > IsNaNReturnType
typedef CwiseUnaryOp< internal::scalar_isinf_op< Scalar >, const Derived > IsInfReturnType
typedef CwiseUnaryOp< internal::scalar_isfinite_op< Scalar >, const Derived > IsFiniteReturnType
typedef CwiseUnaryOp< internal::scalar_lgamma_op< Scalar >, const Derived > LgammaReturnType
typedef CwiseUnaryOp< internal::scalar_digamma_op< Scalar >, const Derived > DigammaReturnType
typedef CwiseUnaryOp< internal::scalar_erf_op< Scalar >, const Derived > ErfReturnType
typedef CwiseUnaryOp< internal::scalar_erfc_op< Scalar >, const Derived > ErfcReturnType
Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const AbsReturnType abs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArgReturnType arg () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Abs2ReturnType abs2 () const
EIGEN_DEVICE_FUNC const ExpReturnType exp () const
EIGEN_DEVICE_FUNC const LogReturnType log () const
EIGEN_DEVICE_FUNC const Log1pReturnType log1p () const
EIGEN_DEVICE_FUNC const Log10ReturnType log10 () const
EIGEN_DEVICE_FUNC const SqrtReturnType sqrt () const
EIGEN_DEVICE_FUNC const RsqrtReturnType rsqrt () const
EIGEN_DEVICE_FUNC const SignReturnType sign () const
EIGEN_DEVICE_FUNC const CosReturnType cos () const
EIGEN_DEVICE_FUNC const SinReturnType sin () const
EIGEN_DEVICE_FUNC const TanReturnType tan () const
EIGEN_DEVICE_FUNC const AtanReturnType atan () const
EIGEN_DEVICE_FUNC const AcosReturnType acos () const
EIGEN_DEVICE_FUNC const AsinReturnType asin () const
EIGEN_DEVICE_FUNC const TanhReturnType tanh () const
EIGEN_DEVICE_FUNC const SinhReturnType sinh () const
EIGEN_DEVICE_FUNC const CoshReturnType cosh () const
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const
EIGEN_DEVICE_FUNC const SquareReturnType square () const
EIGEN_DEVICE_FUNC const CubeReturnType cube () const
EIGEN_DEVICE_FUNC const RoundReturnType round () const
EIGEN_DEVICE_FUNC const FloorReturnType floor () const
EIGEN_DEVICE_FUNC const CeilReturnType ceil () const
EIGEN_DEVICE_FUNC const IsNaNReturnType isNaN () const
EIGEN_DEVICE_FUNC const IsInfReturnType isInf () const
EIGEN_DEVICE_FUNC const IsFiniteReturnType isFinite () const
EIGEN_DEVICE_FUNC const BooleanNotReturnType operator! () const
EIGEN_DEVICE_FUNC const LgammaReturnType lgamma () const
EIGEN_DEVICE_FUNC const DigammaReturnType digamma () const
EIGEN_DEVICE_FUNC const ErfReturnType erf () const
EIGEN_DEVICE_FUNC const ErfcReturnType erfc () const
Typedef Documentation
Abs2ReturnType
typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Abs2ReturnType
Definition at line 5 of file ArrayCwiseUnaryOps.h.
AbsReturnType
typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> AbsReturnType
Definition at line 3 of file ArrayCwiseUnaryOps.h.
AcosReturnType
typedef CwiseUnaryOp<internal::scalar_acos_op<Scalar>, const Derived> AcosReturnType
Definition at line 19 of file ArrayCwiseUnaryOps.h.
ArgReturnType
typedef CwiseUnaryOp<internal::scalar_arg_op<Scalar>, const Derived> ArgReturnType
Definition at line 4 of file ArrayCwiseUnaryOps.h.
AsinReturnType
typedef CwiseUnaryOp<internal::scalar_asin_op<Scalar>, const Derived> AsinReturnType
Definition at line 20 of file ArrayCwiseUnaryOps.h.
AtanReturnType
typedef CwiseUnaryOp<internal::scalar_atan_op<Scalar>, const Derived> AtanReturnType
Definition at line 21 of file ArrayCwiseUnaryOps.h.
BooleanNotReturnType
typedef CwiseUnaryOp<internal::scalar_boolean_not_op<Scalar>, const Derived> BooleanNotReturnType
Definition at line 10 of file ArrayCwiseUnaryOps.h.
CeilReturnType
typedef CwiseUnaryOp<internal::scalar_ceil_op<Scalar>, const Derived> CeilReturnType
Definition at line 29 of file ArrayCwiseUnaryOps.h.
CoshReturnType
typedef CwiseUnaryOp<internal::scalar_cosh_op<Scalar>, const Derived> CoshReturnType
Definition at line 24 of file ArrayCwiseUnaryOps.h.
CosReturnType
typedef CwiseUnaryOp<internal::scalar_cos_op<Scalar>, const Derived> CosReturnType
Definition at line 16 of file ArrayCwiseUnaryOps.h.
CubeReturnType
typedef CwiseUnaryOp<internal::scalar_cube_op<Scalar>, const Derived> CubeReturnType
Definition at line 26 of file ArrayCwiseUnaryOps.h.
DigammaReturnType
typedef CwiseUnaryOp<internal::scalar_digamma_op<Scalar>, const Derived> DigammaReturnType
Definition at line 471 of file ArrayCwiseUnaryOps.h.
ErfcReturnType
typedef CwiseUnaryOp<internal::scalar_erfc_op<Scalar>, const Derived> ErfcReturnType
Definition at line 473 of file ArrayCwiseUnaryOps.h.
ErfReturnType
typedef CwiseUnaryOp<internal::scalar_erf_op<Scalar>, const Derived> ErfReturnType
Definition at line 472 of file ArrayCwiseUnaryOps.h.
ExpReturnType
typedef CwiseUnaryOp<internal::scalar_exp_op<Scalar>, const Derived> ExpReturnType
Definition at line 12 of file ArrayCwiseUnaryOps.h.
FloorReturnType
typedef CwiseUnaryOp<internal::scalar_floor_op<Scalar>, const Derived> FloorReturnType
Definition at line 28 of file ArrayCwiseUnaryOps.h.
InverseReturnType
typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> InverseReturnType
Definition at line 9 of file ArrayCwiseUnaryOps.h.
IsFiniteReturnType
typedef CwiseUnaryOp<internal::scalar_isfinite_op<Scalar>, const Derived> IsFiniteReturnType
Definition at line 32 of file ArrayCwiseUnaryOps.h.
IsInfReturnType
typedef CwiseUnaryOp<internal::scalar_isinf_op<Scalar>, const Derived> IsInfReturnType
Definition at line 31 of file ArrayCwiseUnaryOps.h.
IsNaNReturnType
typedef CwiseUnaryOp<internal::scalar_isnan_op<Scalar>, const Derived> IsNaNReturnType
Definition at line 30 of file ArrayCwiseUnaryOps.h.
LgammaReturnType
typedef CwiseUnaryOp<internal::scalar_lgamma_op<Scalar>, const Derived> LgammaReturnType
Definition at line 470 of file ArrayCwiseUnaryOps.h.
Log10ReturnType
typedef CwiseUnaryOp<internal::scalar_log10_op<Scalar>, const Derived> Log10ReturnType
Definition at line 15 of file ArrayCwiseUnaryOps.h.
Log1pReturnType
typedef CwiseUnaryOp<internal::scalar_log1p_op<Scalar>, const Derived> Log1pReturnType
Definition at line 14 of file ArrayCwiseUnaryOps.h.
LogReturnType
typedef CwiseUnaryOp<internal::scalar_log_op<Scalar>, const Derived> LogReturnType
Definition at line 13 of file ArrayCwiseUnaryOps.h.
RoundReturnType
typedef CwiseUnaryOp<internal::scalar_round_op<Scalar>, const Derived> RoundReturnType
Definition at line 27 of file ArrayCwiseUnaryOps.h.
RsqrtReturnType
typedef CwiseUnaryOp<internal::scalar_rsqrt_op<Scalar>, const Derived> RsqrtReturnType
Definition at line 7 of file ArrayCwiseUnaryOps.h.
SignReturnType
typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> SignReturnType
Definition at line 8 of file ArrayCwiseUnaryOps.h.
SinhReturnType
typedef CwiseUnaryOp<internal::scalar_sinh_op<Scalar>, const Derived> SinhReturnType
Definition at line 23 of file ArrayCwiseUnaryOps.h.
SinReturnType
typedef CwiseUnaryOp<internal::scalar_sin_op<Scalar>, const Derived> SinReturnType
Definition at line 17 of file ArrayCwiseUnaryOps.h.
SqrtReturnType
typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> SqrtReturnType
Definition at line 6 of file ArrayCwiseUnaryOps.h.
SquareReturnType
typedef CwiseUnaryOp<internal::scalar_square_op<Scalar>, const Derived> SquareReturnType
Definition at line 25 of file ArrayCwiseUnaryOps.h.
TanhReturnType
typedef CwiseUnaryOp<internal::scalar_tanh_op<Scalar>, const Derived> TanhReturnType
Definition at line 22 of file ArrayCwiseUnaryOps.h.
TanReturnType
typedef CwiseUnaryOp<internal::scalar_tan_op<Scalar>, const Derived> TanReturnType
Definition at line 18 of file ArrayCwiseUnaryOps.h.
Function Documentation
abs()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const AbsReturnType abs () const
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
Math functions, abs2()
Definition at line 43 of file ArrayCwiseUnaryOps.h.
References EIGEN_STRONG_INLINE.
Referenced by Eigen::LDLT< _MatrixType, _UpLo >::_solve_impl(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::absDeterminant(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::absDeterminant(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::absDeterminant(), Eigen::SparseLU< _MatrixType, _OrderingType >::absDeterminant(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::absDistance(), Action_cholesky< Interface >::Action_cholesky(), SystemTwo::addInteraction(), SystemOne::addInteraction(), adjoint(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::angularDistance(), Hamiltonianmatrix::applyCutoff(), array(), array_complex(), array_real(), array_special_functions(), asum(), aux_evalSolver(), Eigen::internal::companion< _Scalar, _Deg >::balance(), Eigen::internal::bicgstab(), Eigen::internal::blueNorm_impl(), HamiltonianOne::build(), SystemBase< StateTwo >::buildRotator(), HamiltonianTwo::calculate(), Eigen::cauchy_max_bound(), Eigen::cauchy_min_bound(), check_abs(), check_accuracy(), check_accuracy_var(), check_extremity_accuracy(), check_slerp(), check_sparse_abs_determinant(), Eigen::internal::chkder(), combine(), comparisons(), Eigen::internal::MatrixFunctionAtomic< MatrixType >::compute(), Eigen::IterScaling< _MatrixType >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::compute(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::MatrixPower< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), Eigen::RealSchur< MatrixType >::computeFromHessenberg(), Eigen::internal::computeFromTridiagonal_impl(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::internal::conjugate_gradient(), Eigen::IterationController::converged(), Eigen::internal::covar(), Eigen::NumericalDiff< _Functor, mode >::df(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresComputeDeflationData(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresCycle(), Eigen::internal::dogleg(), drotmg_(), energycutoff(), evalSolverSugarFunction(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::image_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), boost::multiprecision::fabs(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::internal::fdjac1(), Hamiltonianmatrix::findUnnecessaryStates(), SystemBase< StateTwo >::forgetStatemixing(), generalized_eigensolver_real(), SystemBase< StateTwo >::getMainStates(), SystemBase< StateTwo >::getOverlap(), SystemBase< StateTwo >::getVectorindex(), Eigen::internal::gmres(), hyperplane(), SystemTwo::incorporate(), SystemTwo::initializeBasis(), SystemTwo::initializeInteraction(), SystemOne::initializeInteraction(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::intersection(), inverse(), inverse_general_4x4(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::isDiagonal(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::isLowerTriangular(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::isUpperTriangular(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::Iterator::Iterator(), lapackNorm(), Eigen::internal::least_square_conjugate_gradient(), linearStructure(), lines(), Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Eigen::internal::lmpar(), Eigen::internal::lmpar2(), Eigen::SparseLU< _MatrixType, _OrderingType >::logAbsDeterminant(), main(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::matrix_function_partition_eigenvalues(), Eigen::internal::matrix_log_compute_2x2(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorageOneStep(), mixingtypes(), nrm2(), WignerD::operator()(), Eigen::internal::scalar_abs_op< Scalar >::operator()(), Eigen::internal::abs_knowing_score< Scalar, typename >::operator()(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::Iterator::operator++(), Eigen::AngleAxis< _Scalar >::operator=(), Eigen::internal::pabs(), packetmath(), packetmath_notcomplex(), packetmath_real(), parametrizedline(), Eigen::PardisoImpl< PardisoLU< MatrixType > >::pardisoInit(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::pivotL(), planes(), qr(), qr_fixedsize(), qr_invertible(), qr_kahan_matrix(), quaternion(), Eigen::internal::QuickSplit(), Eigen::internal::RandomToTypeNormal(), Eigen::SVDBase< BDCSVD< _MatrixType > >::rank(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::rank(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::rank(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::internal::real_2x2_jacobi_svd(), real_qz(), Eigen::PolynomialSolverBase< _Scalar, 1 >::realRoots(), realRoots_to_monicPolynomial_test(), Hamiltonianmatrix::removeUnnecessaryBasisvectors(), rot(), rotg(), processTriangularMatrix< MatrixType, 0 >::run(), adjoint_specific< false >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::igammac_impl< Scalar >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::zeta_impl_series< float >::run(), Eigen::internal::zeta_impl_series< double >::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::internal::betainc_impl< Scalar >::run(), run_fixed_size_test(), run_test(), scal(), selectionRulesMomentum(), selectionRulesMultipole(), Eigen::PolynomialSolverBase< _Scalar, 1 >::selectRealRoot_withRespectToAbsRealPart(), Eigen::PolynomialSolverBase< _Scalar, 1 >::selectRealRoot_withRespectToRealPart(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::slerp(), slerp_legacy(), slerp_legacy_nlerp(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep(), stable_norm(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNorm(), test_basic_functions(), test_isApprox_abs(), testMatrixType(), Trackball::track(), transformations(), Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::unary_evaluator(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), vectorRedux(), verify_euler(), and verify_euler_ranged().
abs2()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Abs2ReturnType abs2 () const
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
Math functions, abs(), square()
Definition at line 71 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::atan2(), Eigen::internal::blueNorm_impl(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::SimplicialLLT< _MatrixType, _UpLo, _Ordering >::determinant(), Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::determinant(), dif_rmse(), Eigen::internal::dogleg(), eigen2support(), Eigen::EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), fft_rmse(), hyperplane(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::isOrthogonal(), lapackNorm(), Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorageOneStep(), Eigen::internal::scalar_abs2_op< Scalar >::operator()(), pblueNorm(), Eigen::poly_eval(), Eigen::internal::real_2x2_jacobi_svd(), rotg(), Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run(), Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::PolynomialSolverBase< _Scalar, 1 >::selectComplexRoot_withRespectToNorm(), Eigen::PolynomialSolverBase< _Scalar, 1 >::selectRealRoot_withRespectToAbsRealPart(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep(), stable_norm(), Eigen::internal::stable_norm_kernel(), boost::multiprecision::test_relative_error(), Eigen::test_relative_error(), triangular_square(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
acos()
EIGEN_DEVICE_FUNC const AcosReturnType acos () const inline
Returns
an expression of the coefficient-wise arc cosine of *this.
Example:
Output:
See also
Math functions, cos(), asin()
Definition at line 262 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), Eigen::atan2(), bounded_acos(), GpuHelper::drawVector(), GpuHelper::drawVectorBox(), fft_rmse(), main(), Eigen::internal::kiss_cpx_fft< _Scalar >::make_twiddles(), Eigen::internal::scalar_acos_op< Scalar >::operator()(), packetmath_real(), Eigen::internal::pacos(), Eigen::internal::kissfft_impl< _Scalar >::real_twiddles(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::slerp(), slerp_legacy(), slerp_legacy_nlerp(), and Trackball::track().
arg()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArgReturnType arg () const
Returns
an expression of the coefficient-wise phase angle of *this
Example:
Output:
See also
abs()
Definition at line 57 of file ArrayCwiseUnaryOps.h.
References EIGEN_STRONG_INLINE.
Referenced by array_complex(), array_real(), testing::Benchmark::Benchmark(), Eigen::internal::scalar_arg_op< Scalar >::operator()(), MandelbrotWidget::paintEvent(), Eigen::internal::parg(), and testing::Benchmark::Run().
asin()
EIGEN_DEVICE_FUNC const AsinReturnType asin () const inline
Returns
an expression of the coefficient-wise arc sine of *this.
Example:
Output:
See also
Math functions, sin(), acos()
Definition at line 276 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), Eigen::atan2(), Eigen::internal::scalar_asin_op< Scalar >::operator()(), EulerAngles< _Scalar >::operator=(), packetmath_real(), Eigen::internal::pasin(), slerp_gael(), and slerp_rw().
atan()
EIGEN_DEVICE_FUNC const AtanReturnType atan () const inline
Returns
an expression of the coefficient-wise arc tan of *this.
Example:
Output:
See also
Math functions, tan(), asin(), acos()
Definition at line 248 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), Eigen::internal::scalar_atan_op< Scalar >::operator()(), and Eigen::internal::patan().
ceil()
EIGEN_DEVICE_FUNC const CeilReturnType ceil () const inline
Returns
an expression of the coefficient-wise ceil of *this.
Example:
Output:
See also
Math functions, floor(), round()
Definition at line 402 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data(), mpfr::digits2bits(), Eigen::internal::matrix_log_compute_2x2(), Numerov::Numerov(), Eigen::internal::scalar_ceil_op< Scalar >::operator()(), packetmath_real(), Eigen::internal::pceil(), Eigen::internal::default_digits10_impl< T, false, false >::run(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::TensorEvaluator(), and Whittaker::Whittaker().
cos()
EIGEN_DEVICE_FUNC const CosReturnType cos () const inline
Returns
an expression of the coefficient-wise cosine of *this.
This function computes the coefficient-wise cosine. The function MatrixBase::cos() in the unsupported module MatrixFunctions computes the matrix cosine.
Example:
Output:
See also
Math functions, sin(), acos()
Definition at line 202 of file ArrayCwiseUnaryOps.h.
Referenced by angleToVec(), array_complex(), array_real(), Eigen::atan2(), check_atan2(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), eigen2support(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::eulerAngles(), foo(), main(), WignerD::operator()(), Eigen::internal::scalar_cos_op< Scalar >::operator()(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::operator=(), packetmath_real(), Eigen::internal::pcos(), SystemTwo::setAngle(), Eigen::internal::stem_function_cos(), Eigen::internal::stem_function_sin(), test2dRotation(), test_autodiff_hessian(), test_trigonometric_functions(), Eigen::Rotation2D< _Scalar >::toRotationMatrix(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), transformations(), and Eigen::Quaternion< _Scalar, _Options >::UnitRandom().
cosh()
EIGEN_DEVICE_FUNC const CoshReturnType cosh () const inline
Returns
an expression of the coefficient-wise hyperbolic cos of *this.
Example:
Output:
See also
Math functions, tan(), sinh(), cosh()
Definition at line 318 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::atan2(), check_hyperbolic_functions(), Eigen::internal::scalar_cosh_op< Scalar >::operator()(), Eigen::internal::pcosh(), Eigen::internal::stem_function_cosh(), Eigen::internal::stem_function_sinh(), and test2dHyperbolicRotation().
cube()
EIGEN_DEVICE_FUNC const CubeReturnType cube () const inline
Returns
an expression of the coefficient-wise cube of *this.
Example:
Output:
See also
Math functions, square(), pow()
Definition at line 360 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), and array_real().
digamma()
EIGEN_DEVICE_FUNC const DigammaReturnType digamma () const inline
Returns
an expression of the coefficient-wise digamma (psi, derivative of lgamma).
Note
This function supports only float and double scalar types. To support other scalar types, the user has to provide implementations of digamma(T) for any scalar type T to be supported.
See also
Math functions, Eigen::digamma(), Eigen::polygamma(), lgamma()
Definition at line 507 of file ArrayCwiseUnaryOps.h.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_digamma_op< Scalar >::operator()(), and Eigen::internal::pdigamma().
erf()
EIGEN_DEVICE_FUNC const ErfReturnType erf () const inline
Returns
an expression of the coefficient-wise Gauss error function of *this.
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of erf(T) for any scalar type T to be supported.
See also
Math functions, erfc()
Definition at line 528 of file ArrayCwiseUnaryOps.h.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_erf_op< Scalar >::operator()(), and Eigen::internal::perf().
erfc()
EIGEN_DEVICE_FUNC const ErfcReturnType erfc () const inline
Returns
an expression of the coefficient-wise Complementary error function of *this.
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of erfc(T) for any scalar type T to be supported.
See also
Math functions, erf()
Definition at line 549 of file ArrayCwiseUnaryOps.h.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_erfc_op< Scalar >::operator()(), and Eigen::internal::perfc().
exp()
EIGEN_DEVICE_FUNC const ExpReturnType exp () const inline
Returns
an expression of the coefficient-wise exponential of *this.
This function computes the coefficient-wise exponential. The function MatrixBase::exp() in the unsupported module MatrixFunctions computes the matrix exponential.
Example:
Output:
See also
Math functions, pow(), log(), sin(), cos()
Definition at line 88 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), array_special_functions(), check_atan2(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::determinant(), DenseLM< Scalar >::df(), chwirut2_functor::df(), misra1a_functor::df(), lanczos1_functor::df(), rat42_functor::df(), MGH10_functor::df(), BoxBOD_functor::df(), MGH17_functor::df(), rat43_functor::df(), eckerle4_functor::df(), Eigen::MatrixComplexPowerReturnValue< Derived >::evalTo(), expfn(), fft_rmse(), foo(), Eigen::internal::kiss_cpx_fft< _Scalar >::make_twiddles(), DenseLM< Scalar >::model(), DenseLM< Scalar >::operator()(), Eigen::internal::scalar_sigmoid_op< T >::operator()(), Eigen::internal::scalar_exp_op< Scalar >::operator()(), chwirut2_functor::operator()(), misra1a_functor::operator()(), Eigen::internal::GaussianGenerator< T, Index, NumDims >::operator()(), lanczos1_functor::operator()(), rat42_functor::operator()(), MGH10_functor::operator()(), BoxBOD_functor::operator()(), MGH17_functor::operator()(), rat43_functor::operator()(), eckerle4_functor::operator()(), packetmath_real(), Eigen::internal::pexp(), Eigen::internal::kissfft_impl< _Scalar >::real_twiddles(), Eigen::internal::igammac_impl< Scalar >::run(), Eigen::internal::igamma_impl< Scalar >::run(), Eigen::internal::polygamma_impl< Scalar >::run(), size_log(), Eigen::internal::stem_function_exp(), test2dRotation(), testGonioFunctions(), testHyperbolicFunctions(), model_potential::V(), and whittaker_functions::WhittakerW().
floor()
EIGEN_DEVICE_FUNC const FloorReturnType floor () const inline
Returns
an expression of the coefficient-wise floor of *this.
Example:
Output:
See also
Math functions, ceil(), round()
Definition at line 388 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), mpfr::bits2digits(), Eigen::MatrixPower< MatrixType >::compute(), main(), Numerov::Numerov(), Eigen::internal::scalar_floor_op< Scalar >::operator()(), packetmath_real(), Eigen::internal::pfloor(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::zeta_impl< Scalar >::run(), and Eigen::internal::polygamma_impl< Scalar >::run().
inverse()
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
operator/(), operator*()
Definition at line 332 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), cwiseSign(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), inverse_general_4x4(), Eigen::internal::kiss_cpx_fft< _Scalar >::make_twiddles(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*=(), and permutationmatrices().
isFinite()
EIGEN_DEVICE_FUNC const IsFiniteReturnType isFinite () const inline
Returns
an expression of the coefficient-wise isfinite of *this.
Example:
Output:
See also
isnan(), isinf()
Definition at line 444 of file ArrayCwiseUnaryOps.h.
isInf()
EIGEN_DEVICE_FUNC const IsInfReturnType isInf () const inline
Returns
an expression of the coefficient-wise isinf of *this.
Example:
Output:
See also
isnan(), isfinite()
Definition at line 430 of file ArrayCwiseUnaryOps.h.
isNaN()
EIGEN_DEVICE_FUNC const IsNaNReturnType isNaN () const inline
Returns
an expression of the coefficient-wise isnan of *this.
Example:
Output:
See also
isfinite(), isinf()
Definition at line 416 of file ArrayCwiseUnaryOps.h.
lgamma()
EIGEN_DEVICE_FUNC const LgammaReturnType lgamma () const inline
Returns
an expression of the coefficient-wise ln(|gamma(*this)|).
Example:
Output:
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of lgamma(T) for any scalar type T to be supported.
See also
Math functions, digamma()
Definition at line 490 of file ArrayCwiseUnaryOps.h.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_lgamma_op< Scalar >::operator()(), and Eigen::internal::plgamma().
log()
EIGEN_DEVICE_FUNC const LogReturnType log () const inline
Returns
an expression of the coefficient-wise logarithm of *this.
This function computes the coefficient-wise logarithm. The function MatrixBase::log() in the unsupported module MatrixFunctions computes the matrix logarithm.
Example:
Output:
See also
Math functions, exp()
Definition at line 105 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::internal::chkder(), Eigen::internal::MatrixLogarithmAtomic< MatrixType >::compute(), Bennett5_functor::df(), rat43_functor::df(), Eigen::SparseLU< _MatrixType, _OrderingType >::logAbsDeterminant(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::logDeterminant(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::scalar_log_op< Scalar >::operator()(), Eigen::internal::plog(), qr_invertible(), Eigen::internal::RandomToTypeNormal(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::igammac_impl< Scalar >::run(), Eigen::internal::igamma_impl< Scalar >::run(), and size_log().
log10()
EIGEN_DEVICE_FUNC const Log10ReturnType log10 () const inline
Returns
an expression of the coefficient-wise base-10 logarithm of *this.
This function computes the coefficient-wise base-10 logarithm.
Example:
Output:
See also
Math functions, log()
Definition at line 135 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::internal::scalar_log10_op< Scalar >::operator()(), Eigen::internal::plog10(), and Eigen::internal::default_digits10_impl< T, false, false >::run().
log1p()
EIGEN_DEVICE_FUNC const Log1pReturnType log1p () const inline
Returns
an expression of the coefficient-wise logarithm of 1 plus *this.
In exact arithmetic, x.log() is equivalent to (x+1).log(), however, with finite precision, this function is much more accurate when x is close to zero.
See also
Math functions, log()
Definition at line 119 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), Eigen::half_impl::log1p(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::scalar_log1p_op< Scalar >::operator()(), and Eigen::internal::plog1p().
operator!()
EIGEN_DEVICE_FUNC const BooleanNotReturnType operator! () const inline
Returns
an expression of the coefficient-wise ! operator of *this
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator!=()
Definition at line 460 of file ArrayCwiseUnaryOps.h.
References EIGEN_STATIC_ASSERT.
round()
EIGEN_DEVICE_FUNC const RoundReturnType round () const inline
Returns
an expression of the coefficient-wise round of *this.
Example:
Output:
See also
Math functions, ceil(), floor()
Definition at line 374 of file ArrayCwiseUnaryOps.h.
Referenced by array_real(), main(), Eigen::internal::scalar_round_op< Scalar >::operator()(), packetmath_real(), and Eigen::internal::pround().
rsqrt()
EIGEN_DEVICE_FUNC const RsqrtReturnType rsqrt () const inline
Returns
an expression of the coefficient-wise inverse square root of *this.
This function computes the coefficient-wise inverse square root.
Example:
Output:
See also
pow(), square()
Definition at line 168 of file ArrayCwiseUnaryOps.h.
Referenced by array_real().
sign()
EIGEN_DEVICE_FUNC const SignReturnType sign () const inline
Returns
an expression of the coefficient-wise signum of *this.
This function computes the coefficient-wise signum.
Example:
Output:
See also
pow(), square()
Definition at line 184 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), cholesky(), cholesky_cplx(), mpfr::const_infinity(), cwiseSqrt(), dlarfg(), mpfr::mpreal::get_default_prec(), Whittaker::integrate(), slarfg(), and zlarfg().
sin()
EIGEN_DEVICE_FUNC const SinReturnType sin () const inline
Returns
an expression of the coefficient-wise sine of *this.
This function computes the coefficient-wise sine. The function MatrixBase::sin() in the unsupported module MatrixFunctions computes the matrix sine.
Example:
Output:
See also
Math functions, cos(), asin()
Definition at line 220 of file ArrayCwiseUnaryOps.h.
Referenced by angleToVec(), array_complex(), array_real(), check_atan2(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::eulerAngles(), foo(), main(), Trackball::mapToSphere(), WignerD::operator()(), Eigen::internal::scalar_sin_op< Scalar >::operator()(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::operator=(), packetmath_real(), Eigen::internal::psin(), SystemTwo::setAngle(), sin_over_x(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::slerp(), slerp_gael(), slerp_legacy(), slerp_legacy_nlerp(), Eigen::internal::stem_function_cos(), Eigen::internal::stem_function_sin(), test2dRotation(), test_autodiff_hessian(), Eigen::Rotation2D< _Scalar >::toRotationMatrix(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), and Eigen::Quaternion< _Scalar, _Options >::UnitRandom().
sinh()
EIGEN_DEVICE_FUNC const SinhReturnType sinh () const inline
Returns
an expression of the coefficient-wise hyperbolic sin of *this.
Example:
Output:
See also
Math functions, sin(), tanh(), cosh()
Definition at line 304 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::atan2(), check_hyperbolic_functions(), Eigen::internal::scalar_sinh_op< Scalar >::operator()(), Eigen::internal::psinh(), Eigen::internal::stem_function_cosh(), Eigen::internal::stem_function_sinh(), and test2dHyperbolicRotation().
sqrt()
EIGEN_DEVICE_FUNC const SqrtReturnType sqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
This function computes the coefficient-wise square root. The function MatrixBase::sqrt() in the unsupported module MatrixFunctions computes the matrix square root.
Example:
Output:
See also
Math functions, pow(), square()
Definition at line 152 of file ArrayCwiseUnaryOps.h.
Referenced by __attribute__(), SystemOne::addInteraction(), array_complex(), array_real(), array_special_functions(), Eigen::atan2(), Eigen::internal::companion< _Scalar, _Deg >::balancedR(), Eigen::internal::bicgstab(), Eigen::internal::blueNorm_impl(), HamiltonianOne::build(), HamiltonianTwo::calculate(), HamiltonianOne::changeToSpherical(), check_accuracy(), Eigen::internal::chkder(), cholesky(), combine(), Eigen::IterScaling< _MatrixType >::compute(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::RealSchur< MatrixType >::computeFromHessenberg(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::internal::conjugate_gradient(), Eigen::NumericalDiff< _Functor, mode >::df(), dif_rmse(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::distance(), divacNorm(), dlapy2(), dlapy3(), dmmch(), dmvch(), Eigen::internal::dogleg(), RenderingWidget::drawScene(), evalSolverSugarFunction(), Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize_preordered(), Eigen::internal::fdjac1(), fft_rmse(), foo(), SystemBase< StateTwo >::forgetStatemixing(), SystemBase< StateTwo >::getConnections(), MatrixElements::getMagneticMomentum(), MatrixElements::getRadial(), Eigen::internal::gmres(), SystemOne::incorporate(), SystemTwo::initializeBasis(), SystemTwo::initializeInteraction(), Numerov::integrate(), lapackNorm(), Eigen::internal::least_square_conjugate_gradient(), Eigen::LevenbergMarquardt< _FunctorType >::LevenbergMarquardt(), Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Eigen::internal::lmpar(), Eigen::internal::lmpar2(), lpNorm(), main(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Trackball::mapToSphere(), Eigen::internal::matrix_sqrt_quasi_triangular_diagonal(), Eigen::matrix_sqrt_triangular(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorageOneStep(), Eigen::internal::minimum_degree_ordering(), Eigen::internal::minres(), mixingtypes(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::norm(), Numerov::Numerov(), WignerD::operator()(), Eigen::internal::scalar_hypot_op< Scalar, Scalar >::operator()(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operatorNorm(), pblueNorm(), MatrixElements::precalculateDiamagnetism(), Eigen::internal::psqrt(), qr(), qr_fixedsize(), qr_kahan_matrix(), whittaker_functions::RadialWFWhittaker(), Eigen::internal::real_2x2_jacobi_svd(), relerr(), Eigen::LevenbergMarquardt< _FunctorType >::resetParameters(), rotg(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run(), SystemTwo::setAngle(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::setFromTwoVectors(), slapy2(), slapy3(), smmch(), smvch(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), stable_norm(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNorm(), svd_least_square(), test_array(), boost::multiprecision::test_relative_error(), Eigen::test_relative_error(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), Eigen::Quaternion< _Scalar, _Options >::UnitRandom(), Whittaker::Whittaker(), zmmch(), and zmvch().
square()
EIGEN_DEVICE_FUNC const SquareReturnType square () const inline
Returns
an expression of the coefficient-wise square of *this.
Example:
Output:
See also
Math functions, abs2(), cube(), pow()
Definition at line 346 of file ArrayCwiseUnaryOps.h.
Referenced by adjoint(), array_complex(), array_real(), basicStuff(), cwiseAbs2(), dontalign(), inplace(), integer_type_tests(), miscMatrices(), product(), and product_extra().
tan()
EIGEN_DEVICE_FUNC const TanReturnType tan () const inline
Returns
an expression of the coefficient-wise tan of *this.
Example:
Output:
See also
Math functions, cos(), sin()
Definition at line 234 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::atan2(), Eigen::internal::scalar_tan_op< Scalar >::operator()(), packetmath_real(), Eigen::internal::ptan(), Eigen::internal::digamma_impl< Scalar >::run(), and Camera::updateProjectionMatrix().
tanh()
EIGEN_DEVICE_FUNC const TanhReturnType tanh () const inline
Returns
an expression of the coefficient-wise hyperbolic tan of *this.
Example:
Output:
See also
Math functions, tan(), sinh(), cosh()
Definition at line 290 of file ArrayCwiseUnaryOps.h.
Referenced by array_complex(), array_real(), Eigen::atan2(), check_hyperbolic_functions(), Eigen::internal::scalar_tanh_op< Scalar >::operator()(), packetmath_real(), and Eigen::internal::ptanh().