pairinteraction: /travis/libpairinteraction/eigen/test/array.cpp File Reference
array.cpp File Reference
#include "main.h"
Functions
template<typename ArrayType >
void array (const ArrayType &m)
template<typename ArrayType >
void comparisons (const ArrayType &m)
template<typename ArrayType >
void array_real (const ArrayType &m)
template<typename ArrayType >
void array_complex (const ArrayType &m)
template<typename ArrayType >
void min_max (const ArrayType &m)
void test_array ()
Function Documentation
array()
template<typename ArrayType > void array (const ArrayType & m)
Definition at line 12 of file array.cpp.
References abs(), cols, Eigen::Dynamic, m1, m2(), Eigen::ArrayBase< Derived >::pow(), Eigen::half_impl::pow(), rows, mpfr::mpreal::sum, mpfr::sum(), VERIFY, VERIFY_IS_APPROX, VERIFY_IS_MUCH_SMALLER_THAN, and VERIFY_IS_NOT_APPROX.
array_complex()
template<typename ArrayType > void array_complex (const ArrayType & m)
Definition at line 320 of file array.cpp.
References abs(), abs2(), arg(), Eigen::atan2(), cols, conj(), cos(), cosh(), cube(), eval(), exp(), i, imag(), inverse(), isfinite, isinf, isnan, j, log(), log10(), m1, m2(), rows, sign(), sin(), sinh(), sqrt(), square(), tan(), tanh(), VERIFY, VERIFY_IS_APPROX, and zero().
array_real()
template<typename ArrayType > void array_real (const ArrayType & m)
Definition at line 207 of file array.cpp.
References abs(), abs2(), acos(), arg(), asin(), atan(), ceil(), cols, cos(), cosh(), cube(), eval(), exp(), floor(), imag(), inverse(), isfinite, isinf, isnan, log(), log10(), log1p(), m1, m2(), Eigen::ArrayBase< Derived >::pow(), round(), rows, rsqrt(), sign(), sin(), sinh(), sqrt(), square(), tan(), tanh(), VERIFY, and VERIFY_IS_APPROX.
comparisons()
template<typename ArrayType > void comparisons (const ArrayType & m)
Definition at line 130 of file array.cpp.
References a, abs(), c, cols, i, j, m1, m2(), rows, VERIFY, and VERIFY_IS_APPROX.
min_max()
template<typename ArrayType > void min_max (const ArrayType & m)
Definition at line 425 of file array.cpp.
References cols, m1, rows, and VERIFY_IS_APPROX.
test_array()
void test_array ()
Definition at line 454 of file array.cpp.
References i.