pairinteraction: /travis/libpairinteraction/eigen/bench/basicbenchmark.h File Reference
basicbenchmark.h File Reference
Enumerations
enum { LazyEval, EarlyEval, OmpEval }
Functions
template<int Mode, typename MatrixType >
void benchBasic_loop (const MatrixType &I, MatrixType &m, int iterations) __attribute__((noinline))
template<int Mode, typename MatrixType >
double benchBasic (const MatrixType &mat, int size, int tries) __attribute__((noinline))
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LazyEval
EarlyEval
OmpEval
Definition at line 5 of file basicbenchmark.h.
Function Documentation
benchBasic()
template<int Mode, typename MatrixType > double benchBasic (const MatrixType & mat, int size, int tries)
Definition at line 41 of file basicbenchmark.h.
References cols, initMatrix_identity(), m, and rows.
Referenced by benchBasic_loop().
benchBasic_loop()
template<int Mode, typename MatrixType > void benchBasic_loop (const MatrixType & I, MatrixType & m, int iterations)
Definition at line 11 of file basicbenchmark.h.
References __attribute__(), a, benchBasic(), Eigen::Dynamic, LazyEval, m, mat, OmpEval, and size.