pairinteraction: /travis/libpairinteraction/eigen/test/bdcsvd.cpp File Reference
bdcsvd.cpp File Reference
#include "main.h"
#include <Eigen/SVD>
#include <iostream>
#include <Eigen/LU>
#include "svd_common.h"
Macros
#define EIGEN_STACK_ALLOCATION_LIMIT 0
#define EIGEN_RUNTIME_NO_MALLOC
#define SVD_DEFAULT(M) BDCSVD<M>
#define SVD_FOR_MIN_NORM(M) BDCSVD<M>
Functions
template<typename MatrixType >
void bdcsvd (const MatrixType &a=MatrixType(), bool pickrandom=true)
template<typename MatrixType >
void bdcsvd_method ()
template<typename MatrixType >
void compare_bdc_jacobi (const MatrixType &a=MatrixType(), unsigned int computationOptions=0)
void test_bdcsvd ()
Macro Definition Documentation
EIGEN_RUNTIME_NO_MALLOC
#define EIGEN_RUNTIME_NO_MALLOC
Definition at line 15 of file bdcsvd.cpp.
EIGEN_STACK_ALLOCATION_LIMIT
#define EIGEN_STACK_ALLOCATION_LIMIT 0
Definition at line 14 of file bdcsvd.cpp.
SVD_DEFAULT
#define SVD_DEFAULT (M) BDCSVD<M>
Definition at line 23 of file bdcsvd.cpp.
Referenced by svd_underoverflow(), and svd_verify_assert().
SVD_FOR_MIN_NORM
#define SVD_FOR_MIN_NORM (M) BDCSVD<M>
Definition at line 24 of file bdcsvd.cpp.
Referenced by svd_min_norm(), and svd_verify_assert().
Function Documentation
bdcsvd()
template<typename MatrixType > void bdcsvd (const MatrixType & a = MatrixType(), bool pickrandom = true)
Definition at line 29 of file bdcsvd.cpp.
References a, CALL_SUBTEST, m, svd_fill_random(), and svd_test_all_computation_options().
Referenced by bench(), and test_boostmultiprec().
bdcsvd_method()
template<typename MatrixType > void bdcsvd_method ()
Definition at line 39 of file bdcsvd.cpp.
References Eigen::ComputeFullU, Eigen::ComputeFullV, m, VERIFY_IS_APPROX, and VERIFY_RAISES_ASSERT.
compare_bdc_jacobi()
template<typename MatrixType > void compare_bdc_jacobi (const MatrixType & a = MatrixType(), unsigned int computationOptions = 0)
Definition at line 53 of file bdcsvd.cpp.
References a, Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, m, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixU(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::singularValues(), and VERIFY_IS_APPROX.
test_bdcsvd()
void test_bdcsvd ()
Definition at line 65 of file bdcsvd.cpp.
References i, svd_all_trivial_2x2(), and svd_verify_assert().