pairinteraction: /travis/libpairinteraction/eigen/test/bicgstab.cpp File Reference
bicgstab.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/IterativeLinearSolvers>
Functions
template<typename T , typename I >
void test_bicgstab_T ()
void test_bicgstab ()
Function Documentation
test_bicgstab()
void test_bicgstab ()
Definition at line 29 of file bicgstab.cpp.
References test_bicgstab_T().
test_bicgstab_T()
template<typename T , typename I > void test_bicgstab_T ()
Definition at line 13 of file bicgstab.cpp.
References CALL_SUBTEST, check_sparse_square_solving(), and Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::setTolerance().
Referenced by test_bicgstab().