pairinteraction: /travis/libpairinteraction/eigen/demos/mix_eigen_and_c/binary_library.cpp File Reference
binary_library.cpp File Reference
#include "binary_library.h"
#include <Eigen/Core>
Functions
MatrixXd & c_to_eigen (C_MatrixXd *ptr)
const MatrixXd & c_to_eigen (const C_MatrixXd *ptr)
C_MatrixXd * eigen_to_c (MatrixXd &ref)
const C_MatrixXd * eigen_to_c (const MatrixXd &ref)
Map< MatrixXd > & c_to_eigen (C_Map_MatrixXd *ptr)
const Map< MatrixXd > & c_to_eigen (const C_Map_MatrixXd *ptr)
C_Map_MatrixXd * eigen_to_c (Map< MatrixXd > &ref)
const C_Map_MatrixXd * eigen_to_c (const Map< MatrixXd > &ref)
C_MatrixXd * MatrixXd_new (int rows, int cols)
void MatrixXd_delete (C_MatrixXd *m)
double * MatrixXd_data (C_MatrixXd *m)
void MatrixXd_set_zero (C_MatrixXd *m)
void MatrixXd_resize (C_MatrixXd *m, int rows, int cols)
void MatrixXd_copy (C_MatrixXd *dst, const C_MatrixXd *src)
void MatrixXd_copy_map (C_MatrixXd *dst, const C_Map_MatrixXd *src)
void MatrixXd_set_coeff (C_MatrixXd *m, int i, int j, double coeff)
double MatrixXd_get_coeff (const C_MatrixXd *m, int i, int j)
void MatrixXd_print (const C_MatrixXd *m)
void MatrixXd_multiply (const C_MatrixXd *m1, const C_MatrixXd *m2, C_MatrixXd *result)
void MatrixXd_add (const C_MatrixXd *m1, const C_MatrixXd *m2, C_MatrixXd *result)
C_Map_MatrixXd * Map_MatrixXd_new (double *array, int rows, int cols)
void Map_MatrixXd_delete (C_Map_MatrixXd *m)
void Map_MatrixXd_set_zero (C_Map_MatrixXd *m)
void Map_MatrixXd_copy (C_Map_MatrixXd *dst, const C_Map_MatrixXd *src)
void Map_MatrixXd_copy_matrix (C_Map_MatrixXd *dst, const C_MatrixXd *src)
void Map_MatrixXd_set_coeff (C_Map_MatrixXd *m, int i, int j, double coeff)
double Map_MatrixXd_get_coeff (const C_Map_MatrixXd *m, int i, int j)
void Map_MatrixXd_print (const C_Map_MatrixXd *m)
void Map_MatrixXd_multiply (const C_Map_MatrixXd *m1, const C_Map_MatrixXd *m2, C_Map_MatrixXd *result)
void Map_MatrixXd_add (const C_Map_MatrixXd *m1, const C_Map_MatrixXd *m2, C_Map_MatrixXd *result)
Function Documentation
c_to_eigen() [1/4]
MatrixXd& c_to_eigen (C_MatrixXd * ptr) inline
Definition at line 23 of file binary_library.cpp.
References ptr.
Referenced by Map_MatrixXd_add(), Map_MatrixXd_copy(), Map_MatrixXd_copy_matrix(), Map_MatrixXd_delete(), Map_MatrixXd_get_coeff(), Map_MatrixXd_multiply(), Map_MatrixXd_print(), Map_MatrixXd_set_coeff(), Map_MatrixXd_set_zero(), MatrixXd_add(), MatrixXd_copy(), MatrixXd_copy_map(), MatrixXd_data(), MatrixXd_delete(), MatrixXd_get_coeff(), MatrixXd_multiply(), MatrixXd_print(), MatrixXd_resize(), MatrixXd_set_coeff(), and MatrixXd_set_zero().
c_to_eigen() [2/4]
const MatrixXd& c_to_eigen (const C_MatrixXd * ptr) inline
Definition at line 28 of file binary_library.cpp.
References ptr.
c_to_eigen() [3/4]
Map<MatrixXd>& c_to_eigen (C_Map_MatrixXd * ptr) inline
Definition at line 45 of file binary_library.cpp.
References ptr.
c_to_eigen() [4/4]
const Map<MatrixXd>& c_to_eigen (const C_Map_MatrixXd * ptr) inline
Definition at line 50 of file binary_library.cpp.
References ptr.
eigen_to_c() [1/4]
C_MatrixXd* eigen_to_c (MatrixXd & ref) inline
Definition at line 33 of file binary_library.cpp.
Referenced by Map_MatrixXd_new(), and MatrixXd_new().
eigen_to_c() [2/4]
const C_MatrixXd* eigen_to_c (const MatrixXd & ref) inline
Definition at line 38 of file binary_library.cpp.
eigen_to_c() [3/4]
C_Map_MatrixXd* eigen_to_c (Map< MatrixXd > & ref) inline
Definition at line 55 of file binary_library.cpp.
eigen_to_c() [4/4]
const C_Map_MatrixXd* eigen_to_c (const Map< MatrixXd > & ref) inline
Definition at line 60 of file binary_library.cpp.
Map_MatrixXd_add()
void Map_MatrixXd_add (const C_Map_MatrixXd * m1, const C_Map_MatrixXd * m2, C_Map_MatrixXd * result)
Definition at line 182 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_Map_MatrixXd().
Map_MatrixXd_copy()
void Map_MatrixXd_copy (C_Map_MatrixXd * dst, const C_Map_MatrixXd * src)
Definition at line 152 of file binary_library.cpp.
References c_to_eigen().
Map_MatrixXd_copy_matrix()
void Map_MatrixXd_copy_matrix (C_Map_MatrixXd * dst, const C_MatrixXd * src)
Definition at line 157 of file binary_library.cpp.
References c_to_eigen().
Map_MatrixXd_delete()
void Map_MatrixXd_delete (C_Map_MatrixXd * m)
Definition at line 142 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_Map_MatrixXd(), and print_array().
Map_MatrixXd_get_coeff()
double Map_MatrixXd_get_coeff (const C_Map_MatrixXd * m, int i, int j)
Definition at line 167 of file binary_library.cpp.
References c_to_eigen(), i, and j.
Map_MatrixXd_multiply()
void Map_MatrixXd_multiply (const C_Map_MatrixXd * m1, const C_Map_MatrixXd * m2, C_Map_MatrixXd * result)
Definition at line 177 of file binary_library.cpp.
References c_to_eigen().
Map_MatrixXd_new()
C_Map_MatrixXd* Map_MatrixXd_new (double * array, int rows, int cols)
Definition at line 137 of file binary_library.cpp.
References eigen_to_c().
Referenced by demo_Map_MatrixXd(), and print_array().
Map_MatrixXd_print()
void Map_MatrixXd_print (const C_Map_MatrixXd * m)
Definition at line 172 of file binary_library.cpp.
References c_to_eigen().
Referenced by print_array().
Map_MatrixXd_set_coeff()
void Map_MatrixXd_set_coeff (C_Map_MatrixXd * m, int i, int j, double coeff)
Definition at line 162 of file binary_library.cpp.
References c_to_eigen(), i, and j.
Map_MatrixXd_set_zero()
void Map_MatrixXd_set_zero (C_Map_MatrixXd * m)
Definition at line 147 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_add()
void MatrixXd_add (const C_MatrixXd * m1, const C_MatrixXd * m2, C_MatrixXd * result)
Definition at line 127 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_copy()
void MatrixXd_copy (C_MatrixXd * dst, const C_MatrixXd * src)
Definition at line 97 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_copy_map()
void MatrixXd_copy_map (C_MatrixXd * dst, const C_Map_MatrixXd * src)
Definition at line 102 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_data()
double* MatrixXd_data (C_MatrixXd * m)
Definition at line 82 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_delete()
void MatrixXd_delete (C_MatrixXd * m)
Definition at line 77 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_MatrixXd().
MatrixXd_get_coeff()
double MatrixXd_get_coeff (const C_MatrixXd * m, int i, int j)
Definition at line 112 of file binary_library.cpp.
References c_to_eigen(), i, and j.
MatrixXd_multiply()
void MatrixXd_multiply (const C_MatrixXd * m1, const C_MatrixXd * m2, C_MatrixXd * result)
Definition at line 122 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_MatrixXd().
MatrixXd_new()
C_MatrixXd* MatrixXd_new (int rows, int cols)
Definition at line 72 of file binary_library.cpp.
References eigen_to_c().
Referenced by demo_MatrixXd().
MatrixXd_print()
void MatrixXd_print (const C_MatrixXd * m)
Definition at line 117 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_MatrixXd().
MatrixXd_resize()
void MatrixXd_resize (C_MatrixXd * m, int rows, int cols)
Definition at line 92 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_set_coeff()
void MatrixXd_set_coeff (C_MatrixXd * m, int i, int j, double coeff)
Definition at line 107 of file binary_library.cpp.
References c_to_eigen(), i, and j.
Referenced by demo_MatrixXd().
MatrixXd_set_zero()
void MatrixXd_set_zero (C_MatrixXd * m)
Definition at line 87 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_MatrixXd().