pairinteraction: /travis/libpairinteraction/eigen/demos/mix_eigen_and_c/binary_library.h File Reference
binary_library.h File Reference
Data Structures
struct C_MatrixXd
struct C_Map_MatrixXd
Functions
struct C_MatrixXd * MatrixXd_new (int rows, int cols)
void MatrixXd_delete (struct C_MatrixXd *m)
double * MatrixXd_data (struct C_MatrixXd *m)
void MatrixXd_set_zero (struct C_MatrixXd *m)
void MatrixXd_resize (struct C_MatrixXd *m, int rows, int cols)
void MatrixXd_copy (struct C_MatrixXd *dst, const struct C_MatrixXd *src)
void MatrixXd_copy_map (struct C_MatrixXd *dst, const struct C_Map_MatrixXd *src)
void MatrixXd_set_coeff (struct C_MatrixXd *m, int i, int j, double coeff)
double MatrixXd_get_coeff (const struct C_MatrixXd *m, int i, int j)
void MatrixXd_print (const struct C_MatrixXd *m)
void MatrixXd_add (const struct C_MatrixXd *m1, const struct C_MatrixXd *m2, struct C_MatrixXd *result)
void MatrixXd_multiply (const struct C_MatrixXd *m1, const struct C_MatrixXd *m2, struct C_MatrixXd *result)
struct C_Map_MatrixXd * Map_MatrixXd_new (double *array, int rows, int cols)
void Map_MatrixXd_delete (struct C_Map_MatrixXd *m)
void Map_MatrixXd_set_zero (struct C_Map_MatrixXd *m)
void Map_MatrixXd_copy (struct C_Map_MatrixXd *dst, const struct C_Map_MatrixXd *src)
void Map_MatrixXd_copy_matrix (struct C_Map_MatrixXd *dst, const struct C_MatrixXd *src)
void Map_MatrixXd_set_coeff (struct C_Map_MatrixXd *m, int i, int j, double coeff)
double Map_MatrixXd_get_coeff (const struct C_Map_MatrixXd *m, int i, int j)
void Map_MatrixXd_print (const struct C_Map_MatrixXd *m)
void Map_MatrixXd_add (const struct C_Map_MatrixXd *m1, const struct C_Map_MatrixXd *m2, struct C_Map_MatrixXd *result)
void Map_MatrixXd_multiply (const struct C_Map_MatrixXd *m1, const struct C_Map_MatrixXd *m2, struct C_Map_MatrixXd *result)
Function Documentation
Map_MatrixXd_add()
void Map_MatrixXd_add (const struct C_Map_MatrixXd * m1, const struct C_Map_MatrixXd * m2, struct C_Map_MatrixXd * result)
Map_MatrixXd_copy()
void Map_MatrixXd_copy (struct C_Map_MatrixXd * dst, const struct C_Map_MatrixXd * src)
Map_MatrixXd_copy_matrix()
void Map_MatrixXd_copy_matrix (struct C_Map_MatrixXd * dst, const struct C_MatrixXd * src)
Map_MatrixXd_delete()
void Map_MatrixXd_delete (struct C_Map_MatrixXd * m)
Definition at line 142 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_Map_MatrixXd(), and print_array().
Map_MatrixXd_get_coeff()
double Map_MatrixXd_get_coeff (const struct C_Map_MatrixXd * m, int i, int j)
Map_MatrixXd_multiply()
void Map_MatrixXd_multiply (const struct C_Map_MatrixXd * m1, const struct C_Map_MatrixXd * m2, struct C_Map_MatrixXd * result)
Map_MatrixXd_new()
struct C_Map_MatrixXd* Map_MatrixXd_new (double * array, int rows, int cols)
Definition at line 137 of file binary_library.cpp.
References eigen_to_c().
Referenced by demo_Map_MatrixXd(), and print_array().
Map_MatrixXd_print()
void Map_MatrixXd_print (const struct C_Map_MatrixXd * m)
Map_MatrixXd_set_coeff()
void Map_MatrixXd_set_coeff (struct C_Map_MatrixXd * m, int i, int j, double coeff)
Definition at line 162 of file binary_library.cpp.
References c_to_eigen(), i, and j.
Map_MatrixXd_set_zero()
void Map_MatrixXd_set_zero (struct C_Map_MatrixXd * m)
Definition at line 147 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_add()
void MatrixXd_add (const struct C_MatrixXd * m1, const struct C_MatrixXd * m2, struct C_MatrixXd * result)
MatrixXd_copy()
void MatrixXd_copy (struct C_MatrixXd * dst, const struct C_MatrixXd * src)
MatrixXd_copy_map()
void MatrixXd_copy_map (struct C_MatrixXd * dst, const struct C_Map_MatrixXd * src)
MatrixXd_data()
double* MatrixXd_data (struct C_MatrixXd * m)
Definition at line 82 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_delete()
void MatrixXd_delete (struct C_MatrixXd * m)
Definition at line 77 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_MatrixXd().
MatrixXd_get_coeff()
double MatrixXd_get_coeff (const struct C_MatrixXd * m, int i, int j)
MatrixXd_multiply()
void MatrixXd_multiply (const struct C_MatrixXd * m1, const struct C_MatrixXd * m2, struct C_MatrixXd * result)
MatrixXd_new()
struct C_MatrixXd* MatrixXd_new (int rows, int cols)
Definition at line 72 of file binary_library.cpp.
References eigen_to_c().
Referenced by demo_MatrixXd().
MatrixXd_print()
void MatrixXd_print (const struct C_MatrixXd * m)
MatrixXd_resize()
void MatrixXd_resize (struct C_MatrixXd * m, int rows, int cols)
Definition at line 92 of file binary_library.cpp.
References c_to_eigen().
MatrixXd_set_coeff()
void MatrixXd_set_coeff (struct C_MatrixXd * m, int i, int j, double coeff)
Definition at line 107 of file binary_library.cpp.
References c_to_eigen(), i, and j.
Referenced by demo_MatrixXd().
MatrixXd_set_zero()
void MatrixXd_set_zero (struct C_MatrixXd * m)
Definition at line 87 of file binary_library.cpp.
References c_to_eigen().
Referenced by demo_MatrixXd().