pairinteraction: /travis/libpairinteraction/eigen/blas/double.cpp File Reference
double.cpp File Reference
#include "level1_impl.h"
#include "level1_real_impl.h"
#include "level2_impl.h"
#include "level2_real_impl.h"
#include "level3_impl.h"
Macros
#define SCALAR double
#define SCALAR_SUFFIX d
#define SCALAR_SUFFIX_UP "D"
#define ISCOMPLEX 0
Functions
double BLASFUNC() dsdot (int *n, float *x, int *incx, float *y, int *incy)
Macro Definition Documentation
ISCOMPLEX
#define ISCOMPLEX 0
Definition at line 14 of file double.cpp.
SCALAR
#define SCALAR double
Definition at line 11 of file double.cpp.
SCALAR_SUFFIX
#define SCALAR_SUFFIX d
Definition at line 12 of file double.cpp.
SCALAR_SUFFIX_UP
#define SCALAR_SUFFIX_UP "D"
Definition at line 13 of file double.cpp.
Function Documentation
dsdot()
double BLASFUNC() dsdot (int * n, float * x, int * incx, float * y, int * incy)
Definition at line 22 of file double.cpp.
References incx, incy, make_vector(), n, mpfr::sum(), x, and y.
Referenced by sdsdot().