pairinteraction: /travis/libpairinteraction/eigen/test/block.cpp File Reference
block.cpp File Reference
#include "main.h"
Macros
#define EIGEN_NO_STATIC_ASSERT
Functions
template<typename MatrixType , typename Index , typename Scalar >
Eigen::internal::enable_if<!NumTraits< typename MatrixType::Scalar >::IsComplex, typename MatrixType::Scalar >::type block_real_only (const MatrixType &m1, Index r1, Index r2, Index c1, Index c2, const Scalar &s1)
template<typename MatrixType , typename Index , typename Scalar >
Eigen::internal::enable_if< NumTraits< typename MatrixType::Scalar >::IsComplex, typename MatrixType::Scalar >::type block_real_only (const MatrixType &, Index, Index, Index, Index, const Scalar &)
template<typename MatrixType >
void block (const MatrixType &m)
template<typename MatrixType >
void compare_using_data_and_stride (const MatrixType &m)
template<typename MatrixType >
void data_and_stride (const MatrixType &m)
void test_block ()
Macro Definition Documentation
EIGEN_NO_STATIC_ASSERT
#define EIGEN_NO_STATIC_ASSERT
Definition at line 10 of file block.cpp.
Function Documentation
block()
template<typename MatrixType > void block (const MatrixType & m)
Definition at line 33 of file block.cpp.
References b, block_real_only(), col(), cols, head< 2 >(), i, m1, m2(), ones, row(), Eigen::RowMajorBit, rows, segment(), tail< 2 >(), v1(), VERIFY, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, and VERIFY_RAISES_ASSERT.
block_real_only() [1/2]
template<typename MatrixType , typename Index , typename Scalar > Eigen::internal::enable_if<!NumTraits<typename MatrixType::Scalar>::IsComplex,typename MatrixType::Scalar>::type block_real_only (const MatrixType & m1, Index r1, Index r2, Index c1, Index c2, const Scalar & s1)
Definition at line 15 of file block.cpp.
References VERIFY_IS_APPROX.
Referenced by block().
block_real_only() [2/2]
template<typename MatrixType , typename Index , typename Scalar > Eigen::internal::enable_if<NumTraits<typename MatrixType::Scalar>::IsComplex,typename MatrixType::Scalar>::type block_real_only (const MatrixType & , Index , Index , Index , Index , const Scalar &)
Definition at line 28 of file block.cpp.
compare_using_data_and_stride()
template<typename MatrixType > void compare_using_data_and_stride (const MatrixType & m)
Definition at line 201 of file block.cpp.
References cols, data, i, j, Eigen::RowMajorBit, rows, size, and VERIFY.
Referenced by data_and_stride().
data_and_stride()
template<typename MatrixType > void data_and_stride (const MatrixType & m)
Definition at line 235 of file block.cpp.
References cols, compare_using_data_and_stride(), m1, and rows.
test_block()
void test_block ()
Definition at line 255 of file block.cpp.
References i.