pairinteraction: /travis/libpairinteraction/eigen/Eigen/src/plugins/BlockMethods.h File Reference
BlockMethods.h File Reference
Data Structures
struct NColsBlockXpr< N >
struct ConstNColsBlockXpr< N >
struct NRowsBlockXpr< N >
struct ConstNRowsBlockXpr< N >
struct FixedBlockXpr< Rows, Cols >
struct ConstFixedBlockXpr< Rows, Cols >
struct FixedSegmentReturnType< Size >
struct ConstFixedSegmentReturnType< Size >
Typedefs
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Functions
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block(Index,Index,Index,Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
EIGEN_DEVICE_FUNC RowsBlockXpr topRows (Index n) const
This is the const version of topRows(Index).
EIGEN_DEVICE_FUNC RowsBlockXpr bottomRows (Index n) const
This is the const version of bottomRows(Index).
EIGEN_DEVICE_FUNC RowsBlockXpr middleRows (Index startRow, Index n) const
This is the const version of middleRows(Index,Index).
EIGEN_DEVICE_FUNC ColsBlockXpr leftCols (Index n) const
This is the const version of leftCols(Index).
EIGEN_DEVICE_FUNC ColsBlockXpr rightCols (Index n) const
This is the const version of rightCols(Index).
EIGEN_DEVICE_FUNC ColsBlockXpr middleCols (Index startCol, Index numCols) const
This is the const version of middleCols(Index,Index).
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
EIGEN_DEVICE_FUNC ColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i) const
This is the const version of row(). */.
EIGEN_DEVICE_FUNC SegmentReturnType segment (Index start, Index n) const
This is the const version of segment(Index,Index).
EIGEN_DEVICE_FUNC SegmentReturnType head (Index n) const
This is the const version of head(Index).
EIGEN_DEVICE_FUNC SegmentReturnType tail (Index n) const
This is the const version of tail(Index).
Typedef Documentation
BlockXpr
typedef Block<Derived> BlockXpr
Definition at line 32 of file BlockMethods.h.
ColsBlockXpr
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ColsBlockXpr
Definition at line 20 of file BlockMethods.h.
ColXpr
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ColXpr
Definition at line 14 of file BlockMethods.h.
ConstBlockXpr
typedef const Block<const Derived> ConstBlockXpr
Definition at line 33 of file BlockMethods.h.
ConstColsBlockXpr
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ConstColsBlockXpr
Definition at line 21 of file BlockMethods.h.
ConstColXpr
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ConstColXpr
Definition at line 15 of file BlockMethods.h.
ConstRowsBlockXpr
typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowsBlockXpr
Definition at line 24 of file BlockMethods.h.
ConstRowXpr
typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowXpr
Definition at line 18 of file BlockMethods.h.
ConstSegmentReturnType
typedef const VectorBlock<const Derived> ConstSegmentReturnType
Definition at line 39 of file BlockMethods.h.
RowsBlockXpr
typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowsBlockXpr
Definition at line 23 of file BlockMethods.h.
RowXpr
typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowXpr
Definition at line 17 of file BlockMethods.h.
SegmentReturnType
typedef VectorBlock<Derived> SegmentReturnType
Definition at line 38 of file BlockMethods.h.
Function Documentation
block() [1/3]
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
This is the const version of block(Index,Index,Index,Index). */.
This is the const version of block<>(Index, Index, Index, Index).
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Returns
an expression of a block in *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 64 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
Referenced by block().
block() [2/3]
template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<NRows,NCols>::Type block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
class Block, block(Index,Index,Index,Index)
Definition at line 780 of file BlockMethods.h.
block() [3/3]
template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<NRows,NCols>::Type block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). */.
Definition at line 788 of file BlockMethods.h.
References block(), EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, and EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
bottomLeftCorner() [1/3]
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) inline
This is the const version of bottomLeftCorner(Index, Index).
This is the const version of bottomLeftCorner<int, int>(Index, Index).
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 348 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and rows.
Referenced by bottomLeftCorner().
bottomLeftCorner() [2/3]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 373 of file BlockMethods.h.
References rows.
bottomLeftCorner() [3/3]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
Definition at line 381 of file BlockMethods.h.
References bottomLeftCorner(), EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, row(), and rows.
bottomRightCorner() [1/3]
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) inline
This is the const version of bottomRightCorner(Index, Index).
This is the const version of bottomRightCorner<int, int>(Index, Index).
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 263 of file BlockMethods.h.
References cols, EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and rows.
Referenced by bottomRightCorner().
bottomRightCorner() [2/3]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 288 of file BlockMethods.h.
References cols, and rows.
bottomRightCorner() [3/3]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
Definition at line 296 of file BlockMethods.h.
References bottomRightCorner(), cols, EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and rows.
bottomRows()
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n = N) inline
This is the const version of bottomRows(Index).
This is the const version of bottomRows<int>().
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 488 of file BlockMethods.h.
References cols, EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, n, row(), and rows.
Referenced by corners(), and Eigen::DenseBase< Derived >::reverseInPlace().
col()
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) inline
This is the const version of col().
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
Definition at line 838 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, i, and row().
head()
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n = N) inline
This is the const version of head(Index).
This is the const version of head<int>().
Returns
a dynamic-size expression of the first coefficients of *this.
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Returns
a fixed-size expression of the first coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 919 of file BlockMethods.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and n.
Referenced by internal::colamd_r(), and Eigen::internal::minimum_degree_ordering().
leftCols()
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n = N) inline
This is the const version of leftCols(Index).
This is the const version of leftCols<int>().
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 602 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, n, and rows.
Referenced by corners(), Eigen::DenseBase< Derived >::reverseInPlace(), and sparse_product().
middleCols()
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n = N) inline
This is the const version of middleCols(Index,Index).
This is the const version of middleCols<int>().
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 715 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, n, and rows.
Referenced by corners().
middleRows()
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n = N) inline
This is the const version of middleRows(Index,Index).
This is the const version of middleRows<int>().
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 545 of file BlockMethods.h.
References cols, EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, n, and row().
Referenced by corners().
rightCols()
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n = N) inline
This is the const version of rightCols(Index).
This is the const version of rightCols<int>().
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 658 of file BlockMethods.h.
References cols, EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, n, and rows.
Referenced by corners(), and Eigen::DenseBase< Derived >::reverseInPlace().
row()
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) inline
This is the const version of row(). */.
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
Definition at line 859 of file BlockMethods.h.
References i.
Referenced by bottomLeftCorner(), bottomRows(), col(), middleRows(), and topRows().
segment()
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n = N) inline
This is the const version of segment(Index,Index).
This is the const version of segment<int>(Index).
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, segment(Index)
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 888 of file BlockMethods.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and n.
Referenced by block(), and tail().
tail()
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n = N) inline
This is the const version of tail(Index).
This is the const version of tail<int>.
Returns
a dynamic-size expression of the last coefficients of *this.
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Returns
a fixed-size expression of the last coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 949 of file BlockMethods.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, n, segment(), and size.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::makeHouseholder(), and Eigen::DenseBase< Derived >::reverseInPlace().
topLeftCorner() [1/3]
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) inline
This is the const version of topLeftCorner(Index, Index).
This is the const version of topLeftCorner<int, int>(Index, Index).
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 178 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
Referenced by topLeftCorner().
topLeftCorner() [2/3]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 203 of file BlockMethods.h.
topLeftCorner() [3/3]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
Definition at line 211 of file BlockMethods.h.
References EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and topLeftCorner().
topRightCorner() [1/3]
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) inline
This is the const version of topRightCorner(Index, Index).
This is the const version of topRightCorner<int, int>(Index, Index).
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 92 of file BlockMethods.h.
References cols, and EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL.
Referenced by topRightCorner().
topRightCorner() [2/3]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
See also
class Block, block<int,int>(Index,Index)
Definition at line 118 of file BlockMethods.h.
References cols.
topRightCorner() [3/3]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
Definition at line 126 of file BlockMethods.h.
References cols, EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL, and topRightCorner().
topRows()
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n = N) inline
This is the const version of topRows(Index).
This is the const version of topRows<int>().
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 432 of file BlockMethods.h.
References cols, EIGEN_DOC_BLOCK_ADDONS_INNER_PANEL_IF, n, and row().
Referenced by corners(), and Eigen::DenseBase< Derived >::reverseInPlace().