pairinteraction: /travis/libpairinteraction/eigen/test/bug1213.h File Reference
bug1213.h File Reference
#include <Eigen/Core>
Functions
template<typename T , int dim>
bool bug1213_2 (const Eigen::Matrix< T, dim, 1 > &x)
bool bug1213_1 (const Eigen::Vector3f &x)
Function Documentation
bug1213_1()
bool bug1213_1 (const Eigen::Vector3f & x)
Definition at line 9 of file bug1213.cpp.
References bug1213_2().
bug1213_2()
template<typename T , int dim> bool bug1213_2 (const Eigen::Matrix< T, dim, 1 > & x)
Definition at line 13 of file bug1213_main.cpp.
References bug1213_2< float, 3 >().
Referenced by bug1213_1().