pairinteraction: /travis/libpairinteraction/eigen/blas/testing/cblat1.f File Reference
cblat1.f File Reference
Functions/Subroutines
program cblat1
CBLAT1
subroutine header
subroutine check1 (SFAC)
subroutine check2 (SFAC)
subroutine stest (LEN, SCOMP, STRUE, SSIZE, SFAC)
subroutine stest1 (SCOMP1, STRUE1, SSIZE, SFAC)
real function sdiff (SA, SB)
subroutine ctest (LEN, CCOMP, CTRUE, CSIZE, SFAC)
subroutine itest1 (ICOMP, ITRUE)
Function/Subroutine Documentation
cblat1()
program cblat1 ()
CBLAT1
Purpose:
    Test program for the COMPLEX Level 1 BLAS.
    Based upon the original BLAS test routine together with:
    F06GAF Example Program Text
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 38 of file cblat1.f.
References check1(), check2(), e(), header(), and x.
check1()
subroutine check1 (real SFAC)
Definition at line 119 of file cblat1.f.
References cscal(), csscal(), ctest(), itest1(), max, and stest1().
Referenced by cblat1(), dblat1(), sblat1(), and zblat1().
check2()
subroutine check2 (real SFAC)
Definition at line 320 of file cblat1.f.
References abs, caxpy(), ccopy(), cswap(), ctest(), and min.
Referenced by cblat1(), dblat1(), sblat1(), and zblat1().
ctest()
subroutine ctest (integer LEN, complex, dimension(len) CCOMP, complex, dimension(len) CTRUE, complex, dimension(len) CSIZE, real SFAC)
Definition at line 655 of file cblat1.f.
References stest().
Referenced by check1(), and check2().
header()
subroutine header ()
Definition at line 91 of file cblat1.f.
References x.
Referenced by cblat1(), dblat1(), Eigen::saveMarket(), sblat1(), and zblat1().
itest1()
subroutine itest1 (integer ICOMP, integer ITRUE)
Definition at line 686 of file cblat1.f.
References x.
Referenced by check1().
sdiff()
real function sdiff (real SA, real SB)
Definition at line 645 of file cblat1.f.
Referenced by sdiff().
stest()
subroutine stest (integer LEN, real, dimension(len) SCOMP, real, dimension(len) STRUE, real, dimension(len) SSIZE, real SFAC)
Definition at line 564 of file cblat1.f.
References abs, and x.
Referenced by check0(), check1(), check2(), check3(), ctest(), and stest1().
stest1()
subroutine stest1 (real SCOMP1, real STRUE1, real, dimension(*) SSIZE, real SFAC)
Definition at line 620 of file cblat1.f.
References stest().
Referenced by check0(), check1(), and check2().