pairinteraction: /travis/libpairinteraction/eigen/blas/testing/cblat3.f File Reference
cblat3.f File Reference
Functions/Subroutines
program cblat3
CBLAT3
subroutine cchk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine cchk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine cchk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NMAX, A, AA, AS, B, BB, BS, CT, G, C)
subroutine cchk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine cchk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, AB, AA, AS, BB, BS, C, CC, CS, CT, G, W)
subroutine cchke (ISNUM, SRNAMT, NOUT)
subroutine cmake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, RESET, TRANSL)
subroutine cmmch (TRANSA, TRANSB, M, N, KK, ALPHA, A, LDA, B, LDB, BETA, C, LDC, CT, G, CC, LDCC, EPS, ERR, FATAL, NOUT, MV)
logical function lce (RI, RJ, LR)
logical function lceres (TYPE, UPLO, M, N, AA, AS, LDA)
complex function cbeg (RESET)
real function sdiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
cbeg()
complex function cbeg (logical RESET)
Definition at line 3335 of file cblat3.f.
References cbeg().
cblat3()
program cblat3 ()
CBLAT3
Purpose:
 Test program for the COMPLEX          Level 3 Blas.
 The program must be driven by a short data file. The first 14 records
 of the file are read using list-directed input, the last 9 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 23 lines:
 'cblat3.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'CBLAT3.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 3                 NUMBER OF VALUES OF ALPHA
 (0.0,0.0) (1.0,0.0) (0.7,-0.9)       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 (0.0,0.0) (1.0,0.0) (1.3,-1.1)       VALUES OF BETA
 CGEMM  T PUT F FOR NO TEST. SAME COLUMNS.
 CHEMM  T PUT F FOR NO TEST. SAME COLUMNS.
 CSYMM  T PUT F FOR NO TEST. SAME COLUMNS.
 CTRMM  T PUT F FOR NO TEST. SAME COLUMNS.
 CTRSM  T PUT F FOR NO TEST. SAME COLUMNS.
 CHERK  T PUT F FOR NO TEST. SAME COLUMNS.
 CSYRK  T PUT F FOR NO TEST. SAME COLUMNS.
 CHER2K T PUT F FOR NO TEST. SAME COLUMNS.
 CSYR2K T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
 See:
    Dongarra J. J., Du Croz J. J., Duff I. S. and Hammarling S.
    A Set of Level 3 Basic Linear Algebra Subprograms.
    Technical Memorandum No.88 (Revision 1), Mathematics and
    Computer Science Division, Argonne National Laboratory, 9700
    South Cass Avenue, Argonne, Illinois 60439, US.
 -- Written on 8-February-1989.
    Jack Dongarra, Argonne National Laboratory.
    Iain Duff, AERE Harwell.
    Jeremy Du Croz, Numerical Algorithms Group Ltd.
    Sven Hammarling, Numerical Algorithms Group Ltd.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 86 of file cblat3.f.
References a, c, cchk1(), cchk2(), cchk3(), cchk4(), cchk5(), cchke(), cmmch(), max, min, p, w, and x.
cchk1()
subroutine cchk1 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NBET, complex, dimension(nbet) BET, integer NMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax, nmax) B, complex, dimension(nmax*nmax) BB, complex, dimension(nmax*nmax) BS, complex, dimension(nmax, nmax) C, complex, dimension(nmax*nmax) CC, complex, dimension(nmax*nmax) CS, complex, dimension(nmax) CT, real, dimension(nmax) G)
Definition at line 408 of file cblat3.f.
References b, c, cgemm(), cmake(), cmmch(), lda, m, max, n, and x.
cchk2()
subroutine cchk2 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NBET, complex, dimension(nbet) BET, integer NMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax, nmax) B, complex, dimension(nmax*nmax) BB, complex, dimension(nmax*nmax) BS, complex, dimension(nmax, nmax) C, complex, dimension(nmax*nmax) CC, complex, dimension(nmax*nmax) CS, complex, dimension(nmax) CT, real, dimension(nmax) G)
Definition at line 693 of file cblat3.f.
References b, c, chemm(), cmake(), cmmch(), csymm(), lda, m, max, n, and x.
cchk3()
subroutine cchk3 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax, nmax) B, complex, dimension(nmax*nmax) BB, complex, dimension(nmax*nmax) BS, complex, dimension(nmax) CT, real, dimension(nmax) G, complex, dimension(nmax, nmax) C)
Definition at line 972 of file cblat3.f.
References b, c, cmake(), cmmch(), ctrmm(), ctrsm(), lda, m, max, n, and x.
cchk4()
subroutine cchk4 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NBET, complex, dimension(nbet) BET, integer NMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax, nmax) B, complex, dimension(nmax*nmax) BB, complex, dimension(nmax*nmax) BS, complex, dimension(nmax, nmax) C, complex, dimension(nmax*nmax) CC, complex, dimension(nmax*nmax) CS, complex, dimension(nmax) CT, real, dimension(nmax) G)
Definition at line 1282 of file cblat3.f.
References b, c, cherk(), cmake(), cmmch(), csyrk(), lda, max, n, and x.
cchk5()
subroutine cchk5 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NBET, complex, dimension(nbet) BET, integer NMAX, complex, dimension(2*nmax*nmax) AB, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax*nmax) BB, complex, dimension(nmax*nmax) BS, complex, dimension(nmax, nmax) C, complex, dimension(nmax*nmax) CC, complex, dimension(nmax*nmax) CS, complex, dimension(nmax) CT, real, dimension(nmax) G, complex, dimension(2*nmax) W)
Definition at line 1614 of file cblat3.f.
References c, cher2k(), cmake(), cmmch(), csyr2k(), lda, max, n, w, and x.
cchke()
subroutine cchke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 1985 of file cblat3.f.
References cgemm(), chemm(), cher2k(), cherk(), chkxer(), csymm(), csyr2k(), csyrk(), ctrmm(), and ctrsm().
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 3408 of file cblat3.f.
cmake()
subroutine cmake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, complex, dimension(nmax, *) A, integer NMAX, complex, dimension(*) AA, integer LDA, logical RESET, complex TRANSL)
Definition at line 2927 of file cblat3.f.
cmmch()
subroutine cmmch (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer KK, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB, complex BETA, complex, dimension(ldc, *) C, integer LDC, complex, dimension(*) CT, real, dimension(*) G, complex, dimension(ldcc, *) CC, integer LDCC, real EPS, real ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 3056 of file cblat3.f.
References abs, max, and x.
Referenced by cblat3(), cchk1(), cchk2(), cchk3(), cchk4(), and cchk5().
lce()
logical function lce (complex, dimension(*) RI, complex, dimension(*) RJ, integer LR)
Definition at line 3242 of file cblat3.f.
References lce().
lceres()
logical function lceres (character*2 TYPE, character*1 UPLO, integer M, integer N, complex, dimension(lda, *) AA, complex, dimension(lda, *) AS, integer LDA)
Definition at line 3274 of file cblat3.f.
References lceres().
sdiff()
real function sdiff (real X, real Y)
Definition at line 3389 of file cblat3.f.
References sdiff().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 3438 of file cblat3.f.