pairinteraction: /travis/libpairinteraction/eigen/blas/testing/cblat2.f File Reference
cblat2.f File Reference
Functions/Subroutines
program cblat2
CBLAT2
subroutine cchk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine cchk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine cchk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, XT, G, Z)
subroutine cchk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine cchk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine cchk6 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine cchke (ISNUM, SRNAMT, NOUT)
subroutine cmake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, KL, KU, RESET, TRANSL)
subroutine cmvch (TRANS, M, N, ALPHA, A, NMAX, X, INCX, BETA, Y, INCY, YT, G, YY, EPS, ERR, FATAL, NOUT, MV)
logical function lce (RI, RJ, LR)
logical function lceres (TYPE, UPLO, M, N, AA, AS, LDA)
complex function cbeg (RESET)
real function sdiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
cbeg()
complex function cbeg (logical RESET)
Definition at line 3131 of file cblat2.f.
Referenced by cbeg().
cblat2()
program cblat2 ()
CBLAT2
Purpose:
 Test program for the COMPLEX          Level 2 Blas.
 The program must be driven by a short data file. The first 18 records
 of the file are read using list-directed input, the last 17 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 35 lines:
 'cblat2.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'CBLA2T.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 4                 NUMBER OF VALUES OF K
 0 1 2 4           VALUES OF K
 4                 NUMBER OF VALUES OF INCX AND INCY
 1 2 -1 -2         VALUES OF INCX AND INCY
 3                 NUMBER OF VALUES OF ALPHA
 (0.0,0.0) (1.0,0.0) (0.7,-0.9)       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 (0.0,0.0) (1.0,0.0) (1.3,-1.1)       VALUES OF BETA
 CGEMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CGBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CHEMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CHBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CHPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CTRMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CTBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CTPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 CTRSV  T PUT F FOR NO TEST. SAME COLUMNS.
 CTBSV  T PUT F FOR NO TEST. SAME COLUMNS.
 CTPSV  T PUT F FOR NO TEST. SAME COLUMNS.
 CGERC  T PUT F FOR NO TEST. SAME COLUMNS.
 CGERU  T PUT F FOR NO TEST. SAME COLUMNS.
 CHER   T PUT F FOR NO TEST. SAME COLUMNS.
 CHPR   T PUT F FOR NO TEST. SAME COLUMNS.
 CHER2  T PUT F FOR NO TEST. SAME COLUMNS.
 CHPR2  T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
    See:
       Dongarra J. J., Du Croz J. J., Hammarling S.  and Hanson R. J..
       An  extended  set of Fortran  Basic Linear Algebra Subprograms.
       Technical  Memoranda  Nos. 41 (revision 3) and 81,  Mathematics
       and  Computer Science  Division,  Argonne  National Laboratory,
       9700 South Cass Avenue, Argonne, Illinois 60439, US.
       Or
       NAG  Technical Reports TR3/87 and TR4/87,  Numerical Algorithms
       Group  Ltd.,  NAG  Central  Office,  256  Banbury  Road, Oxford
       OX2 7DE, UK,  and  Numerical Algorithms Group Inc.,  1101  31st
       Street,  Suite 100,  Downers Grove,  Illinois 60515-1263,  USA.
 -- Written on 10-August-1987.
    Richard Hanson, Sandia National Labs.
    Jeremy Du Croz, NAG Central Office.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 104 of file cblat2.f.
References abs, cchk1(), cchk2(), cchk3(), cchk4(), cchk5(), cchk6(), cchke(), cmvch(), max, min, p, x, and y.
cchk1()
subroutine cchk1 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, complex, dimension(nalf) ALF, integer NBET, complex, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax) X, complex, dimension(nmax*incmax) XX, complex, dimension(nmax*incmax) XS, complex, dimension(nmax) Y, complex, dimension(nmax*incmax) YY, complex, dimension(nmax*incmax) YS, complex, dimension(nmax) YT, real, dimension(nmax) G)
Definition at line 441 of file cblat2.f.
References abs, cgbmv(), cgemv(), cmake(), cmvch(), lda, m, max, min, n, x, and y.
Referenced by cblat2(), and cblat3().
cchk2()
subroutine cchk2 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, complex, dimension(nalf) ALF, integer NBET, complex, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax) X, complex, dimension(nmax*incmax) XX, complex, dimension(nmax*incmax) XS, complex, dimension(nmax) Y, complex, dimension(nmax*incmax) YY, complex, dimension(nmax*incmax) YS, complex, dimension(nmax) YT, real, dimension(nmax) G)
Definition at line 786 of file cblat2.f.
References abs, chbmv(), chemv(), chpmv(), cmake(), cmvch(), lda, max, n, x, and y.
Referenced by cblat2(), and cblat3().
cchk3()
subroutine cchk3 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax) X, complex, dimension(nmax*incmax) XX, complex, dimension(nmax*incmax) XS, complex, dimension(nmax) XT, real, dimension(nmax) G, complex, dimension(nmax) Z)
Definition at line 1133 of file cblat2.f.
References abs, cmake(), cmvch(), ctbmv(), ctbsv(), ctpmv(), ctpsv(), ctrmv(), ctrsv(), lda, max, n, and x.
Referenced by cblat2(), and cblat3().
cchk4()
subroutine cchk4 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax) X, complex, dimension(nmax*incmax) XX, complex, dimension(nmax*incmax) XS, complex, dimension(nmax) Y, complex, dimension(nmax*incmax) YY, complex, dimension(nmax*incmax) YS, complex, dimension(nmax) YT, real, dimension(nmax) G, complex, dimension(nmax) Z)
Definition at line 1495 of file cblat2.f.
References abs, cgerc(), cgeru(), cmake(), cmvch(), j, lda, m, max, min, n, x, and y.
Referenced by cblat2(), and cblat3().
cchk5()
subroutine cchk5 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax) X, complex, dimension(nmax*incmax) XX, complex, dimension(nmax*incmax) XS, complex, dimension(nmax) Y, complex, dimension(nmax*incmax) YY, complex, dimension(nmax*incmax) YS, complex, dimension(nmax) YT, real, dimension(nmax) G, complex, dimension(nmax) Z)
Definition at line 1772 of file cblat2.f.
References abs, cher(), chpr(), cmake(), cmvch(), lda, max, n, x, and y.
Referenced by cblat2(), and cblat3().
cchk6()
subroutine cchk6 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex, dimension(nmax, nmax) A, complex, dimension(nmax*nmax) AA, complex, dimension(nmax*nmax) AS, complex, dimension(nmax) X, complex, dimension(nmax*incmax) XX, complex, dimension(nmax*incmax) XS, complex, dimension(nmax) Y, complex, dimension(nmax*incmax) YY, complex, dimension(nmax*incmax) YS, complex, dimension(nmax) YT, real, dimension(nmax) G, complex, dimension(nmax, 2) Z)
Definition at line 2056 of file cblat2.f.
References abs, cher2(), chpr2(), cmake(), cmvch(), j, lda, max, n, x, and y.
Referenced by cblat2().
cchke()
subroutine cchke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 2375 of file cblat2.f.
References cgbmv(), cgemv(), cgerc(), cgeru(), chbmv(), chemv(), cher(), cher2(), chkxer(), chpmv(), chpr(), chpr2(), ctbmv(), ctbsv(), ctpmv(), ctpsv(), ctrmv(), and ctrsv().
Referenced by cblat2(), and cblat3().
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 3199 of file cblat2.f.
Referenced by cchke(), dchke(), schke(), and zchke().
cmake()
subroutine cmake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, complex, dimension(nmax, *) A, integer NMAX, complex, dimension(*) AA, integer LDA, integer KL, integer KU, logical RESET, complex TRANSL)
Definition at line 2719 of file cblat2.f.
References max, and min.
Referenced by cchk1(), cchk2(), cchk3(), cchk4(), cchk5(), and cchk6().
cmvch()
subroutine cmvch (character*1 TRANS, integer M, integer N, complex ALPHA, complex, dimension(nmax, *) A, integer NMAX, complex, dimension(*) X, integer INCX, complex BETA, complex, dimension(*) Y, integer INCY, complex, dimension(*) YT, real, dimension(*) G, complex, dimension(*) YY, real EPS, real ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 2911 of file cblat2.f.
References abs, and max.
Referenced by cblat2(), cchk1(), cchk2(), cchk3(), cchk4(), cchk5(), and cchk6().
lce()
logical function lce (complex, dimension(*) RI, complex, dimension(*) RJ, integer LR)
Definition at line 3042 of file cblat2.f.
Referenced by lce().
lceres()
logical function lceres (character*2 TYPE, character*1 UPLO, integer M, integer N, complex, dimension(lda, *) AA, complex, dimension(lda, *) AS, integer LDA)
Definition at line 3072 of file cblat2.f.
Referenced by lceres().
sdiff()
real function sdiff (real X, real Y)
Definition at line 3183 of file cblat2.f.
References sdiff().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 3227 of file cblat2.f.