pairinteraction: Eigen::internal::scoped_array< T > Class Template Reference
Eigen::internal::scoped_array< T > Class Template Reference
#include <Memory.h>
Public Member Functions
scoped_array (std::ptrdiff_t size)
~scoped_array ()
T & operator[] (std::ptrdiff_t i)
const T & operator[] (std::ptrdiff_t i) const
T *& ptr ()
const T * ptr () const
operator const T * () const
Detailed Description
template<typename T>
class Eigen::internal::scoped_array< T >
Definition at line 583 of file Memory.h.
Constructor & Destructor Documentation
scoped_array()
template<typename T> Eigen::internal::scoped_array< T >::scoped_array (std::ptrdiff_t size) inline explicit
Definition at line 587 of file Memory.h.
References size.
~scoped_array()
template<typename T> Eigen::internal::scoped_array< T >::~scoped_array () inline
Definition at line 591 of file Memory.h.
Member Function Documentation
operator const T *()
template<typename T> Eigen::internal::scoped_array< T >::operator const T * () const inline
Definition at line 599 of file Memory.h.
operator[]() [1/2]
template<typename T> T& Eigen::internal::scoped_array< T >::operator[] (std::ptrdiff_t i) inline
Definition at line 595 of file Memory.h.
References i.
operator[]() [2/2]
template<typename T> const T& Eigen::internal::scoped_array< T >::operator[] (std::ptrdiff_t i) const inline
Definition at line 596 of file Memory.h.
References i.
ptr() [1/2]
template<typename T> T* & Eigen::internal::scoped_array< T >::ptr () inline
Definition at line 597 of file Memory.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), and Eigen::internal::swap().
ptr() [2/2]
template<typename T> const T* Eigen::internal::scoped_array< T >::ptr () const inline
Definition at line 598 of file Memory.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/Memory.h