pairinteraction: Action_matrix_matrix_product< Interface > Class Template Reference
Action_matrix_matrix_product< Interface > Class Template Reference
#include <action_matrix_matrix_product.hh>
Public Member Functions
Action_matrix_matrix_product (int size)
Action_matrix_matrix_product (const Action_matrix_matrix_product &)
~Action_matrix_matrix_product (void)
double nb_op_base (void)
void initialize (void)
void calculate (void)
void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_matrix_matrix_product< Interface >
Definition at line 32 of file action_matrix_matrix_product.hh.
Constructor & Destructor Documentation
Action_matrix_matrix_product() [1/2]
template<class Interface > Action_matrix_matrix_product< Interface >::Action_matrix_matrix_product (int size) inline
Definition at line 38 of file action_matrix_matrix_product.hh.
References MESSAGE, and X.
Action_matrix_matrix_product() [2/2]
template<class Interface > Action_matrix_matrix_product< Interface >::Action_matrix_matrix_product (const Action_matrix_matrix_product< Interface > &) inline
Definition at line 63 of file action_matrix_matrix_product.hh.
References INFOS.
~Action_matrix_matrix_product()
template<class Interface > Action_matrix_matrix_product< Interface >::~Action_matrix_matrix_product (void) inline
Definition at line 71 of file action_matrix_matrix_product.hh.
References MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > void Action_matrix_matrix_product< Interface >::calculate (void) inline
Definition at line 106 of file action_matrix_matrix_product.hh.
References X.
check_result()
template<class Interface > void Action_matrix_matrix_product< Interface >::check_result (void) inline
Definition at line 110 of file action_matrix_matrix_product.hh.
References e(), INFOS, STL_interface< real >::matrix_matrix_product(), STL_interface< real >::norm_diff(), and X.
initialize()
template<class Interface > void Action_matrix_matrix_product< Interface >::initialize (void) inline
Definition at line 98 of file action_matrix_matrix_product.hh.
References X.
name()
template<class Interface > static std::string Action_matrix_matrix_product< Interface >::name (void) inline static
Definition at line 89 of file action_matrix_matrix_product.hh.
nb_op_base()
template<class Interface > double Action_matrix_matrix_product< Interface >::nb_op_base (void) inline
Definition at line 94 of file action_matrix_matrix_product.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_matrix_matrix_product.hh