pairinteraction: MandelbrotWidget Class Reference
MandelbrotWidget Class Reference
#include <mandelbrot.h>
Public Member Functions
MandelbrotWidget ()
~MandelbrotWidget ()
Protected Member Functions
void resizeEvent (QResizeEvent *)
void paintEvent (QPaintEvent *)
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Friends
class MandelbrotThread
Detailed Description
Definition at line 34 of file mandelbrot.h.
Constructor & Destructor Documentation
MandelbrotWidget()
MandelbrotWidget::MandelbrotWidget () inline
Definition at line 55 of file mandelbrot.h.
References MandelbrotThread::MandelbrotThread().
~MandelbrotWidget()
MandelbrotWidget::~MandelbrotWidget () inline
Definition at line 63 of file mandelbrot.h.
Member Function Documentation
mouseMoveEvent()
void MandelbrotWidget::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 188 of file mandelbrot.cpp.
References relicense::update().
mousePressEvent()
void MandelbrotWidget::mousePressEvent (QMouseEvent * event) protected
Definition at line 173 of file mandelbrot.cpp.
References relicense::update().
paintEvent()
void MandelbrotWidget::paintEvent (QPaintEvent *) protected
Definition at line 127 of file mandelbrot.cpp.
References arg(), int(), max, and relicense::update().
resizeEvent()
void MandelbrotWidget::resizeEvent (QResizeEvent *) protected
Definition at line 17 of file mandelbrot.cpp.
Friends And Related Function Documentation
MandelbrotThread
friend class MandelbrotThread friend
Definition at line 38 of file mandelbrot.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/demos/mandelbrot/mandelbrot.h
/travis/libpairinteraction/eigen/demos/mandelbrot/mandelbrot.cpp