pairinteraction: Action_lu_solve< Interface > Class Template Reference
Action_lu_solve< Interface > Class Template Reference
#include <action_lu_solve.hh>
Static Public Member Functions
static std::string name (void)
static double nb_op_base (int size)
static double calculate (int nb_calc, int size)
Detailed Description
template<class Interface>
class Action_lu_solve< Interface >
Definition at line 32 of file action_lu_solve.hh.
Member Function Documentation
calculate()
template<class Interface > static double Action_lu_solve< Interface >::calculate (int nb_calc, int size) inline static
Definition at line 47 of file action_lu_solve.hh.
References STL_interface< real >::display_vector(), e(), INFOS, STL_interface< real >::matrix_vector_product(), STL_interface< real >::norm_diff(), size, Portable_Timer::start(), Portable_Timer::stop(), Portable_Timer::user_time(), and X.
name()
template<class Interface > static std::string Action_lu_solve< Interface >::name (void) inline static
Definition at line 37 of file action_lu_solve.hh.
nb_op_base()
template<class Interface > static double Action_lu_solve< Interface >::nb_op_base (int size) inline static
Definition at line 42 of file action_lu_solve.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_lu_solve.hh