pairinteraction: Eigen::RunQueue< Work, kSize > Class Template Reference
Eigen::RunQueue< Work, kSize > Class Template Reference
#include <RunQueue.h>
Public Member Functions
RunQueue ()
~RunQueue ()
Work PushFront (Work w)
Work PopFront ()
Work PushBack (Work w)
Work PopBack ()
unsigned PopBackHalf (std::vector< Work > *result)
unsigned Size () const
bool Empty () const
Detailed Description
template<typename Work, unsigned kSize>
class Eigen::RunQueue< Work, kSize >
Definition at line 39 of file RunQueue.h.
Constructor & Destructor Documentation
RunQueue()
template<typename Work, unsigned kSize> Eigen::RunQueue< Work, kSize >::RunQueue () inline
Definition at line 41 of file RunQueue.h.
References eigen_assert, and i.
Referenced by Eigen::RunQueue< Work, kSize >::Empty().
~RunQueue()
template<typename Work, unsigned kSize> Eigen::RunQueue< Work, kSize >::~RunQueue () inline
Definition at line 50 of file RunQueue.h.
References eigen_assert, and Eigen::RunQueue< Work, kSize >::Size().
Member Function Documentation
Empty()
template<typename Work, unsigned kSize> bool Eigen::RunQueue< Work, kSize >::Empty () const inline
Definition at line 178 of file RunQueue.h.
References Eigen::RunQueue< Work, kSize >::RunQueue(), Eigen::RunQueue< Work, kSize >::Size(), and w.
Referenced by Eigen::RunQueue< Work, kSize >::PopBack(), Eigen::RunQueue< Work, kSize >::PopBackHalf(), test_basic_runqueue(), test_empty_runqueue(), and test_stress_runqueue().
PopBack()
template<typename Work, unsigned kSize> Work Eigen::RunQueue< Work, kSize >::PopBack () inline
Definition at line 102 of file RunQueue.h.
References e(), Eigen::RunQueue< Work, kSize >::Empty(), s, and w.
Referenced by test_basic_runqueue().
PopBackHalf()
template<typename Work, unsigned kSize> unsigned Eigen::RunQueue< Work, kSize >::PopBackHalf (std::vector< Work > * result) inline
Definition at line 120 of file RunQueue.h.
References e(), eigen_assert, Eigen::RunQueue< Work, kSize >::Empty(), n, s, size, and Eigen::RunQueue< Work, kSize >::Size().
Referenced by test_basic_runqueue(), test_empty_runqueue(), and test_stress_runqueue().
PopFront()
template<typename Work, unsigned kSize> Work Eigen::RunQueue< Work, kSize >::PopFront () inline
Definition at line 69 of file RunQueue.h.
References e(), s, and w.
Referenced by Eigen::NonBlockingThreadPoolTempl< Environment >::CurrentThreadId(), test_basic_runqueue(), test_empty_runqueue(), and test_stress_runqueue().
PushBack()
template<typename Work, unsigned kSize> Work Eigen::RunQueue< Work, kSize >::PushBack (Work w) inline
Definition at line 85 of file RunQueue.h.
References e(), and s.
Referenced by Eigen::NonBlockingThreadPoolTempl< Environment >::Schedule(), test_basic_runqueue(), test_empty_runqueue(), and test_stress_runqueue().
PushFront()
template<typename Work, unsigned kSize> Work Eigen::RunQueue< Work, kSize >::PushFront (Work w) inline
Definition at line 54 of file RunQueue.h.
References e(), and s.
Referenced by Eigen::NonBlockingThreadPoolTempl< Environment >::Schedule(), test_basic_runqueue(), test_empty_runqueue(), and test_stress_runqueue().
Size()
template<typename Work, unsigned kSize> unsigned Eigen::RunQueue< Work, kSize >::Size () const inline
Definition at line 155 of file RunQueue.h.
References size.
Referenced by Eigen::RunQueue< Work, kSize >::Empty(), Eigen::RunQueue< Work, kSize >::PopBackHalf(), test_basic_runqueue(), test_empty_runqueue(), and Eigen::RunQueue< Work, kSize >::~RunQueue().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/ThreadPool/RunQueue.h