pairinteraction: Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options > Class Template Reference
Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC DenseStorage ()
DenseStorage (internal::constructor_without_unaligned_array_assert)
EIGEN_DEVICE_FUNC DenseStorage (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC DenseStorage (const DenseStorage &other)
EIGEN_DEVICE_FUNC DenseStorage & operator= (const DenseStorage &other)
EIGEN_DEVICE_FUNC ~DenseStorage ()
EIGEN_DEVICE_FUNC void swap (DenseStorage &other)
EIGEN_DEVICE_FUNC Index cols (void) const
EIGEN_DEVICE_FUNC void conservativeResize (Index size, Index, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize (Index size, Index, Index cols)
EIGEN_DEVICE_FUNC const T * data () const
EIGEN_DEVICE_FUNC T * data ()
Static Public Member Functions
static EIGEN_DEVICE_FUNC Index rows (void)
Detailed Description
template<typename T, int _Rows, int _Options>
class Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >
Definition at line 421 of file DenseStorage.h.
Constructor & Destructor Documentation
DenseStorage() [1/4]
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage () inline
Definition at line 426 of file DenseStorage.h.
DenseStorage() [2/4]
template<typename T , int _Rows, int _Options> Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage (internal::constructor_without_unaligned_array_assert) inline explicit
Definition at line 427 of file DenseStorage.h.
DenseStorage() [3/4]
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage (Index size, Index rows, Index cols) inline
Definition at line 428 of file DenseStorage.h.
References eigen_internal_assert, EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, and EIGEN_UNUSED_VARIABLE.
DenseStorage() [4/4]
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::DenseStorage (const DenseStorage< T, Dynamic, _Rows, Dynamic, _Options > & other) inline
Definition at line 434 of file DenseStorage.h.
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, size, and Eigen::internal::smart_copy().
~DenseStorage()
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::~DenseStorage () inline
Definition at line 468 of file DenseStorage.h.
Member Function Documentation
cols()
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC Index Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::cols (void) const inline
Definition at line 471 of file DenseStorage.h.
conservativeResize()
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC void Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::conservativeResize (Index size, Index , Index cols) inline
Definition at line 472 of file DenseStorage.h.
References cols, and size.
data() [1/2]
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC const T* Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::data () const inline
Definition at line 490 of file DenseStorage.h.
data() [2/2]
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC T* Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::data () inline
Definition at line 491 of file DenseStorage.h.
operator=()
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC DenseStorage& Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::operator= (const DenseStorage< T, Dynamic, _Rows, Dynamic, _Options > & other) inline
Definition at line 441 of file DenseStorage.h.
References EIGEN_NOEXCEPT, Eigen::internal::swap(), and std::swap().
resize()
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::resize (Index size, Index , Index cols) inline
Definition at line 477 of file DenseStorage.h.
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, and size.
rows()
template<typename T , int _Rows, int _Options> static EIGEN_DEVICE_FUNC Index Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::rows (void) inline static
Definition at line 470 of file DenseStorage.h.
swap()
template<typename T , int _Rows, int _Options> EIGEN_DEVICE_FUNC void Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::swap (DenseStorage< T, Dynamic, _Rows, Dynamic, _Options > & other) inline
Definition at line 469 of file DenseStorage.h.
References std::swap().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/DenseStorage.h