pairinteraction: Action_aat_product< Interface > Class Template Reference
Action_aat_product< Interface > Class Template Reference
#include <action_aat_product.hh>
Public Member Functions
Action_aat_product (int size)
Action_aat_product (const Action_aat_product &)
~Action_aat_product (void)
double nb_op_base (void)
void initialize (void)
void calculate (void)
void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_aat_product< Interface >
Definition at line 32 of file action_aat_product.hh.
Constructor & Destructor Documentation
Action_aat_product() [1/2]
template<class Interface > Action_aat_product< Interface >::Action_aat_product (int size) inline
Definition at line 38 of file action_aat_product.hh.
References MESSAGE, and X.
Action_aat_product() [2/2]
template<class Interface > Action_aat_product< Interface >::Action_aat_product (const Action_aat_product< Interface > &) inline
Definition at line 60 of file action_aat_product.hh.
References INFOS.
~Action_aat_product()
template<class Interface > Action_aat_product< Interface >::~Action_aat_product (void) inline
Definition at line 68 of file action_aat_product.hh.
References MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > void Action_aat_product< Interface >::calculate (void) inline
Definition at line 100 of file action_aat_product.hh.
References X.
check_result()
template<class Interface > void Action_aat_product< Interface >::check_result (void) inline
Definition at line 106 of file action_aat_product.hh.
References STL_interface< real >::aat_product(), e(), INFOS, STL_interface< real >::norm_diff(), and X.
initialize()
template<class Interface > void Action_aat_product< Interface >::initialize (void) inline
Definition at line 93 of file action_aat_product.hh.
References X.
name()
template<class Interface > static std::string Action_aat_product< Interface >::name (void) inline static
Definition at line 84 of file action_aat_product.hh.
nb_op_base()
template<class Interface > double Action_aat_product< Interface >::nb_op_base (void) inline
Definition at line 89 of file action_aat_product.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_aat_product.hh