pairinteraction: Eigen::array< T, n > Class Template Reference
Eigen::array< T, n > Class Template Reference
#include <EmulateArray.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & operator[] (size_t index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & operator[] (size_t index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & front ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & front () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & back ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & back () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2, const T &v3)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2, const T &v3, const T &v4)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2, const T &v3, const T &v4, const T &v5)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2, const T &v3, const T &v4, const T &v5, const T &v6)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2, const T &v3, const T &v4, const T &v5, const T &v6, const T &v7)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE array (const T &v1, const T &v2, const T &v3, const T &v4, const T &v5, const T &v6, const T &v7, const T &v8)
Static Public Member Functions
EIGEN_DEVICE_FUNC static EIGEN_ALWAYS_INLINE std::size_t size ()
Data Fields
T values [n]
Detailed Description
template<typename T, size_t n>
class Eigen::array< T, n >
Definition at line 21 of file EmulateArray.h.
Constructor & Destructor Documentation
array() [1/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array () inline
Definition at line 44 of file EmulateArray.h.
Referenced by Eigen::array< Index, ContractDims >::array(), and Eigen::array< T, 0 >::array().
array() [2/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v) inline
Definition at line 46 of file EmulateArray.h.
array() [3/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2) inline
Definition at line 51 of file EmulateArray.h.
array() [4/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2, const T & v3) inline
Definition at line 57 of file EmulateArray.h.
array() [5/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2, const T & v3, const T & v4) inline
Definition at line 64 of file EmulateArray.h.
array() [6/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2, const T & v3, const T & v4, const T & v5) inline
Definition at line 73 of file EmulateArray.h.
array() [7/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2, const T & v3, const T & v4, const T & v5, const T & v6) inline
Definition at line 83 of file EmulateArray.h.
array() [8/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2, const T & v3, const T & v4, const T & v5, const T & v6, const T & v7) inline
Definition at line 94 of file EmulateArray.h.
array() [9/9]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::array< T, n >::array (const T & v1, const T & v2, const T & v3, const T & v4, const T & v5, const T & v6, const T & v7, const T & v8) inline
Definition at line 106 of file EmulateArray.h.
Member Function Documentation
back() [1/2]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::array< T, n >::back () inline
Definition at line 34 of file EmulateArray.h.
Referenced by Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::TensorEvaluator().
back() [2/2]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::array< T, n >::back () const inline
Definition at line 36 of file EmulateArray.h.
front() [1/2]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::array< T, n >::front () inline
Definition at line 29 of file EmulateArray.h.
front() [2/2]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::array< T, n >::front () const inline
Definition at line 31 of file EmulateArray.h.
operator[]() [1/2]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::array< T, n >::operator[] (size_t index) inline
Definition at line 24 of file EmulateArray.h.
operator[]() [2/2]
template<typename T, size_t n> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::array< T, n >::operator[] (size_t index) const inline
Definition at line 26 of file EmulateArray.h.
size()
template<typename T, size_t n> EIGEN_DEVICE_FUNC static EIGEN_ALWAYS_INLINE std::size_t Eigen::array< T, n >::size () inline static
Definition at line 39 of file EmulateArray.h.
Field Documentation
values
template<typename T, size_t n> T Eigen::array< T, n >::values[n]
Definition at line 41 of file EmulateArray.h.
Referenced by Eigen::array< Index, ContractDims >::array(), Eigen::array< Index, ContractDims >::back(), Eigen::array< Index, ContractDims >::front(), and Eigen::array< Index, ContractDims >::operator[]().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/util/EmulateArray.h