pairinteraction: X86_Timer Class Reference
X86_Timer Class Reference
#include <x86_timer.hh>
Public Member Functions
X86_Timer (void)
void start (void)
void stop (void)
double frequency (void)
double get_elapsed_time_in_second (void)
unsigned long long get_click (void)
void find_frequency (void)
void add_get_click (void)
void dump_statistics (string filemane)
void dump_history (string filemane)
double get_mean_clicks (void)
double get_shortest_clicks (void)
void fill_history_clicks (void)
double get_most_occured_clicks (void)
void clear (void)
Detailed Description
Definition at line 44 of file x86_timer.hh.
Constructor & Destructor Documentation
X86_Timer()
X86_Timer::X86_Timer (void) inline
Definition at line 48 of file x86_timer.hh.
References MESSAGE.
Member Function Documentation
add_get_click()
void X86_Timer::add_get_click (void) inline
Definition at line 111 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::eval_mflops().
clear()
void X86_Timer::clear (void) inline
Definition at line 204 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::eval_mflops().
dump_history()
void X86_Timer::dump_history (string filemane) inline
Definition at line 133 of file x86_timer.hh.
References i.
dump_statistics()
void X86_Timer::dump_statistics (string filemane) inline
Definition at line 119 of file x86_timer.hh.
fill_history_clicks()
void X86_Timer::fill_history_clicks (void) inline
Definition at line 175 of file x86_timer.hh.
find_frequency()
void X86_Timer::find_frequency (void) inline
INFOS("CPU frequency : "<< _frequency);
Definition at line 84 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::X86_Perf_Analyzer().
frequency()
double X86_Timer::frequency (void) inline
Definition at line 67 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::eval_mflops().
get_click()
unsigned long long X86_Timer::get_click (void) inline
Definition at line 78 of file x86_timer.hh.
get_elapsed_time_in_second()
double X86_Timer::get_elapsed_time_in_second (void) inline
Definition at line 71 of file x86_timer.hh.
References FREQUENCY.
get_mean_clicks()
double X86_Timer::get_mean_clicks (void) inline
Definition at line 153 of file x86_timer.hh.
get_most_occured_clicks()
double X86_Timer::get_most_occured_clicks (void) inline
Definition at line 184 of file x86_timer.hh.
get_shortest_clicks()
double X86_Timer::get_shortest_clicks (void) inline
Definition at line 169 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::eval_mflops().
start()
void X86_Timer::start (void) inline
Definition at line 53 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::eval_mflops().
stop()
void X86_Timer::stop (void) inline
Definition at line 60 of file x86_timer.hh.
Referenced by X86_Perf_Analyzer< Action >::eval_mflops().
Field Documentation
n32
unsigned long int X86_Timer::n32[2]
Definition at line 221 of file x86_timer.hh.
n64
unsigned long long X86_Timer::n64
Definition at line 222 of file x86_timer.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/timers/x86_timer.hh