pairinteraction: Action_symv< Interface > Class Template Reference
Action_symv< Interface > Class Template Reference
#include <action_symv.hh>
Public Member Functions
BTL_DONT_INLINE Action_symv (int size)
Action_symv (const Action_symv &)
BTL_DONT_INLINE ~Action_symv (void)
double nb_op_base (void)
BTL_DONT_INLINE void initialize (void)
BTL_DONT_INLINE void calculate (void)
BTL_DONT_INLINE void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_symv< Interface >
Definition at line 32 of file action_symv.hh.
Constructor & Destructor Documentation
Action_symv() [1/2]
template<class Interface > BTL_DONT_INLINE Action_symv< Interface >::Action_symv (int size) inline
Definition at line 38 of file action_symv.hh.
References MESSAGE, and X.
Action_symv() [2/2]
template<class Interface > Action_symv< Interface >::Action_symv (const Action_symv< Interface > &) inline
Definition at line 60 of file action_symv.hh.
References INFOS.
~Action_symv()
template<class Interface > BTL_DONT_INLINE Action_symv< Interface >::~Action_symv (void) inline
Definition at line 67 of file action_symv.hh.
References X.
Member Function Documentation
calculate()
template<class Interface > BTL_DONT_INLINE void Action_symv< Interface >::calculate (void) inline
Definition at line 95 of file action_symv.hh.
References BTL_ASM_COMMENT, symv(), and X.
check_result()
template<class Interface > BTL_DONT_INLINE void Action_symv< Interface >::check_result (void) inline
Definition at line 101 of file action_symv.hh.
References e(), INFOS, STL_interface< real >::norm_diff(), STL_interface< real >::symv(), and X.
initialize()
template<class Interface > BTL_DONT_INLINE void Action_symv< Interface >::initialize (void) inline
Definition at line 87 of file action_symv.hh.
References X.
name()
template<class Interface > static std::string Action_symv< Interface >::name (void) inline static
Definition at line 78 of file action_symv.hh.
nb_op_base()
template<class Interface > double Action_symv< Interface >::nb_op_base (void) inline
Definition at line 83 of file action_symv.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_symv.hh