pairinteraction: Eigen::Transpose< MatrixType > Class Template Reference
Eigen::Transpose< MatrixType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of the transpose of a matrix.
#include <Transpose.h>
Public Types
typedef internal::ref_selector< MatrixType >::non_const_type MatrixTypeNested
typedef TransposeImpl< MatrixType, typename internal::traits< MatrixType >::StorageKind >::Base Base
typedef internal::remove_all< MatrixType >::type NestedExpression
Public Types inherited from Eigen::TransposeImpl< MatrixType, internal::traits< MatrixType >::StorageKind >
typedef internal::generic_xpr_base< Transpose< MatrixType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC Transpose (MatrixType &matrix)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const internal::remove_all< MatrixTypeNested >::type & nestedExpression () const
EIGEN_DEVICE_FUNC internal::remove_reference< MatrixTypeNested >::type & nestedExpression ()
void resize (Index nrows, Index ncols)
Protected Attributes
internal::ref_selector< MatrixType >::non_const_type m_matrix
Detailed Description
template<typename MatrixType>
class Eigen::Transpose< MatrixType >
Expression of the transpose of a matrix.
Template Parameters
MatrixType the type of the object of which we are taking the transpose
This class represents an expression of the transpose of a matrix. It is the return type of MatrixBase::transpose() and MatrixBase::adjoint() and most of the time this is the only way it is used.
See also
MatrixBase::transpose(), MatrixBase::adjoint()
Definition at line 52 of file Transpose.h.
Member Typedef Documentation
Base
template<typename MatrixType> typedef TransposeImpl<MatrixType,typename internal::traits<MatrixType>::StorageKind>::Base Eigen::Transpose< MatrixType >::Base
Definition at line 59 of file Transpose.h.
MatrixTypeNested
template<typename MatrixType> typedef internal::ref_selector<MatrixType>::non_const_type Eigen::Transpose< MatrixType >::MatrixTypeNested
Definition at line 57 of file Transpose.h.
NestedExpression
template<typename MatrixType> typedef internal::remove_all<MatrixType>::type Eigen::Transpose< MatrixType >::NestedExpression
Definition at line 61 of file Transpose.h.
Constructor & Destructor Documentation
Transpose()
template<typename MatrixType> EIGEN_DEVICE_FUNC Eigen::Transpose< MatrixType >::Transpose (MatrixType & matrix) inline explicit
Definition at line 64 of file Transpose.h.
References EIGEN_INHERIT_ASSIGNMENT_OPERATORS.
Member Function Documentation
cols()
template<typename MatrixType> EIGEN_DEVICE_FUNC Index Eigen::Transpose< MatrixType >::cols (void) const inline
Definition at line 69 of file Transpose.h.
nestedExpression() [1/2]
template<typename MatrixType> EIGEN_DEVICE_FUNC const internal::remove_all<MatrixTypeNested>::type& Eigen::Transpose< MatrixType >::nestedExpression () const inline
Returns
the nested expression
Definition at line 74 of file Transpose.h.
Referenced by Eigen::internal::generic_product_impl< Transpose< Lhs >, Rhs, TranspositionsShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Transpose< Rhs >, MatrixShape, TranspositionsShape, ProductTag >::evalTo(), Eigen::internal::blas_traits< Transpose< NestedXpr > >::extract(), and Eigen::internal::blas_traits< Transpose< NestedXpr > >::extractScalarFactor().
nestedExpression() [2/2]
template<typename MatrixType> EIGEN_DEVICE_FUNC internal::remove_reference<MatrixTypeNested>::type& Eigen::Transpose< MatrixType >::nestedExpression () inline
Returns
the nested expression
Definition at line 79 of file Transpose.h.
resize()
template<typename MatrixType> void Eigen::Transpose< MatrixType >::resize (Index nrows, Index ncols) inline
Definition at line 82 of file Transpose.h.
rows()
template<typename MatrixType> EIGEN_DEVICE_FUNC Index Eigen::Transpose< MatrixType >::rows (void) const inline
Definition at line 68 of file Transpose.h.
Field Documentation
m_matrix
template<typename MatrixType> internal::ref_selector<MatrixType>::non_const_type Eigen::Transpose< MatrixType >::m_matrix protected
Definition at line 87 of file Transpose.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/Transpose.h