pairinteraction: Eigen::internal::AmbiVector< _Scalar, _StorageIndex > Class Template Reference
Eigen::internal::AmbiVector< _Scalar, _StorageIndex > Class Template Reference
#include <AmbiVector.h>
Data Structures
class Iterator
struct ListEl
Public Types
typedef _Scalar Scalar
typedef _StorageIndex StorageIndex
typedef NumTraits< Scalar >::Real RealScalar
Public Member Functions
AmbiVector (Index size)
void init (double estimatedDensity)
void init (int mode)
Index nonZeros () const
void setBounds (Index start, Index end)
void setZero ()
void restart ()
Scalar & coeffRef (Index i)
Scalar & coeff (Index i)
~AmbiVector ()
void resize (Index size)
StorageIndex size () const
Protected Member Functions
StorageIndex convert_index (Index idx)
void reallocate (Index size)
void reallocateSparse ()
Protected Attributes
Scalar * m_buffer
Scalar m_zero
StorageIndex m_size
StorageIndex m_start
StorageIndex m_end
StorageIndex m_allocatedSize
StorageIndex m_allocatedElements
StorageIndex m_mode
StorageIndex m_llStart
StorageIndex m_llCurrent
StorageIndex m_llSize
Detailed Description
template<typename _Scalar, typename _StorageIndex>
class Eigen::internal::AmbiVector< _Scalar, _StorageIndex >
Definition at line 23 of file AmbiVector.h.
Member Typedef Documentation
RealScalar
template<typename _Scalar , typename _StorageIndex > typedef NumTraits<Scalar>::Real Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::RealScalar
Definition at line 28 of file AmbiVector.h.
Scalar
template<typename _Scalar , typename _StorageIndex > typedef _Scalar Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::Scalar
Definition at line 26 of file AmbiVector.h.
StorageIndex
template<typename _Scalar , typename _StorageIndex > typedef _StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::StorageIndex
Definition at line 27 of file AmbiVector.h.
Constructor & Destructor Documentation
AmbiVector()
template<typename _Scalar , typename _StorageIndex > Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::AmbiVector (Index size) inline explicit
Definition at line 30 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::nonZeros(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::resize().
~AmbiVector()
template<typename _Scalar , typename _StorageIndex > Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::~AmbiVector () inline
Definition at line 52 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer.
Member Function Documentation
coeff()
template<typename _Scalar , typename _StorageIndex > _Scalar & Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff (Index i)
Definition at line 255 of file AmbiVector.h.
References eigen_assert, EIGEN_RESTRICT, i, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::ListEl::index, Eigen::IsDense, Eigen::IsSparse, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llCurrent, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llSize, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llStart, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_mode, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_zero.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds().
coeffRef()
template<typename _Scalar , typename _StorageIndex > _Scalar & Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef (Index i)
Definition at line 186 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::convert_index(), eigen_assert, eigen_internal_assert, EIGEN_RESTRICT, i, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::ListEl::index, Eigen::IsDense, Eigen::IsSparse, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_allocatedElements, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llCurrent, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llSize, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llStart, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_mode, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::ListEl::next, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocateSparse(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::ListEl::value.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds().
convert_index()
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::convert_index (Index idx) inline protected
Definition at line 64 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::resize(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds().
init() [1/2]
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init (double estimatedDensity)
Definition at line 138 of file AmbiVector.h.
References Eigen::IsDense, and Eigen::IsSparse.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::AmbiVector().
init() [2/2]
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init (int mode)
Definition at line 147 of file AmbiVector.h.
References Eigen::IsSparse, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llSize, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llStart, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_mode.
nonZeros()
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::nonZeros () const
Returns
the number of non zeros in the current sub vector
Definition at line 129 of file AmbiVector.h.
References Eigen::IsSparse, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_end, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llSize, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_mode, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_start.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::AmbiVector().
reallocate()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate (Index size) inline protected
Definition at line 69 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::convert_index(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_allocatedElements, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_end, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_size, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_start, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::size().
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::resize().
reallocateSparse()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocateSparse () inline protected
Definition at line 90 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_allocatedElements, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_size, and min.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef().
resize()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::resize (Index size) inline
Definition at line 54 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::convert_index(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_size, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate().
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::AmbiVector().
restart()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::restart ()
Must be called whenever we might perform a write access with an index smaller than the previous one.
Don't worry, this function is extremely cheap.
Definition at line 163 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llCurrent, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llStart.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds().
setBounds()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds (Index start, Index end) inline
Specifies a sub-vector to work on
Definition at line 42 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::convert_index(), i, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_end, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_start, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::restart(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero().
Referenced by Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run().
setZero()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero ()
Set all coefficients of current subvector to zero
Definition at line 170 of file AmbiVector.h.
References eigen_assert, i, Eigen::IsDense, Eigen::IsSparse, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_end, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llSize, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llStart, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_mode, and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_start.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds().
size()
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::size () const inline
Definition at line 61 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_size.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate().
Field Documentation
m_allocatedElements
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_allocatedElements protected
Definition at line 118 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocateSparse().
m_allocatedSize
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_allocatedSize protected
Definition at line 117 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::resize().
m_buffer
template<typename _Scalar , typename _StorageIndex > Scalar* Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_buffer protected
Definition at line 112 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocateSparse(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::~AmbiVector().
m_end
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_end protected
Definition at line 116 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::nonZeros(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero().
m_llCurrent
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llCurrent protected
Definition at line 123 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::restart().
m_llSize
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llSize protected
Definition at line 124 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::nonZeros(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero().
m_llStart
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_llStart protected
Definition at line 122 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::restart(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero().
m_mode
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_mode protected
Definition at line 119 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::nonZeros(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero().
m_size
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_size protected
Definition at line 114 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocateSparse(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::resize(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::size().
m_start
template<typename _Scalar , typename _StorageIndex > StorageIndex Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_start protected
Definition at line 115 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::nonZeros(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds(), and Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero().
m_zero
template<typename _Scalar , typename _StorageIndex > Scalar Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::m_zero protected
Definition at line 113 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeff().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/AmbiVector.h