pairinteraction: Eigen::SparseVector< _Scalar, _Options, _StorageIndex > Class Template Reference
Eigen::SparseVector< _Scalar, _Options, _StorageIndex > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
a sparse vector class
#include <SparseUtil.h>
Public Types
enum { IsColVector = internal::traits<SparseVector>::IsColVector }
enum { Options = _Options }
typedef internal::CompressedStorage< Scalar, StorageIndex > Storage
typedef Base::InnerIterator InnerIterator
typedef Base::ReverseInnerIterator ReverseInnerIterator
Public Types inherited from Eigen::SparseCompressedBase< SparseVector< _Scalar, _Options, _StorageIndex > >
typedef SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > > Base
Public Types inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >
enum
typedef internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::StorageKind StorageKind
typedef internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const SparseVector< _Scalar, _Options, _StorageIndex > > >, Transpose< const SparseVector< _Scalar, _Options, _StorageIndex > > >::type AdjointReturnType
typedef Transpose< SparseVector< _Scalar, _Options, _StorageIndex > > TransposeReturnType
typedef internal::add_const< Transpose< const SparseVector< _Scalar, _Options, _StorageIndex > > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, const Scalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< SparseVector< _Scalar, _Options, _StorageIndex > > Base
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > >, const SparseVector< _Scalar, _Options, _StorageIndex > & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > >, const SparseVector< _Scalar, _Options, _StorageIndex > & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, SparseVector< _Scalar, _Options, _StorageIndex > >, SparseVector< _Scalar, _Options, _StorageIndex > & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, SparseVector< _Scalar, _Options, _StorageIndex > > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > NegativeReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex > > CwiseInverseReturnType
typedef CwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const SparseVector< _Scalar, _Options, _StorageIndex >, const ConstantReturnType > CwiseScalarEqualReturnType
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex >, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, 1, !IsRowMajor > ColXpr
typedef const Block< const SparseVector< _Scalar, _Options, _StorageIndex >, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, 1, !IsRowMajor > ConstColXpr
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex >, 1, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const SparseVector< _Scalar, _Options, _StorageIndex >, 1, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex >, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, Dynamic, !IsRowMajor > ColsBlockXpr
typedef const Block< const SparseVector< _Scalar, _Options, _StorageIndex >, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::RowsAtCompileTime, Dynamic, !IsRowMajor > ConstColsBlockXpr
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex >, Dynamic, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const SparseVector< _Scalar, _Options, _StorageIndex >, Dynamic, internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex > > BlockXpr
typedef const Block< const SparseVector< _Scalar, _Options, _StorageIndex > > ConstBlockXpr
typedef VectorBlock< SparseVector< _Scalar, _Options, _StorageIndex > > SegmentReturnType
typedef const VectorBlock< const SparseVector< _Scalar, _Options, _StorageIndex > > ConstSegmentReturnType
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const SparseVector< _Scalar, _Options, _StorageIndex >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< SparseVector< _Scalar, _Options, _StorageIndex >, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const SparseVector< _Scalar, _Options, _StorageIndex >, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_STRONG_INLINE Index rows () const
EIGEN_STRONG_INLINE Index cols () const
EIGEN_STRONG_INLINE Index innerSize () const
EIGEN_STRONG_INLINE Index outerSize () const
EIGEN_STRONG_INLINE const Scalar * valuePtr () const
EIGEN_STRONG_INLINE Scalar * valuePtr ()
EIGEN_STRONG_INLINE const StorageIndex * innerIndexPtr () const
EIGEN_STRONG_INLINE StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
Storage & data ()
const Storage & data () const
Scalar coeff (Index row, Index col) const
Scalar coeff (Index i) const
Scalar & coeffRef (Index row, Index col)
Scalar & coeffRef (Index i)
void setZero ()
Index nonZeros () const
void startVec (Index outer)
Scalar & insertBackByOuterInner (Index outer, Index inner)
Scalar & insertBack (Index i)
Scalar & insertBackByOuterInnerUnordered (Index outer, Index inner)
Scalar & insertBackUnordered (Index i)
Scalar & insert (Index row, Index col)
Scalar & insert (Index i)
void reserve (Index reserveSize)
void finalize ()
void prune (const Scalar &reference, const RealScalar &epsilon=NumTraits< RealScalar >::dummy_precision())
void resize (Index rows, Index cols)
void resize (Index newSize)
void conservativeResize (Index newSize)
void resizeNonZeros (Index size)
SparseVector ()
SparseVector (Index size)
SparseVector (Index rows, Index cols)
template<typename OtherDerived >
SparseVector (const SparseMatrixBase< OtherDerived > &other)
SparseVector (const SparseVector &other)
void swap (SparseVector &other)
template<int OtherOptions>
void swap (SparseMatrix< Scalar, OtherOptions, StorageIndex > &other)
SparseVector & operator= (const SparseVector &other)
template<typename OtherDerived >
SparseVector & operator= (const SparseMatrixBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
SparseVector & operator= (const SparseSparseProduct< Lhs, Rhs > &product)
~SparseVector ()
Scalar sum () const
EIGEN_DEPRECATED void startFill (Index reserve)
EIGEN_DEPRECATED Scalar & fill (Index r, Index c)
EIGEN_DEPRECATED Scalar & fill (Index i)
EIGEN_DEPRECATED Scalar & fillrand (Index r, Index c)
EIGEN_DEPRECATED Scalar & fillrand (Index i)
EIGEN_DEPRECATED void endFill ()
EIGEN_DEPRECATED Storage & _data ()
EIGEN_DEPRECATED const Storage & _data () const
Public Member Functions inherited from Eigen::SparseCompressedBase< SparseVector< _Scalar, _Options, _StorageIndex > >
Index nonZeros () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
Public Member Functions inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >
SparseVector< _Scalar, _Options, _StorageIndex > & operator= (const EigenBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator= (const ReturnByValue< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator= (const SparseVector< _Scalar, _Options, _StorageIndex > &other)
const SparseVector< _Scalar, _Options, _StorageIndex > & derived () const
SparseVector< _Scalar, _Options, _StorageIndex > & derived ()
SparseVector< _Scalar, _Options, _StorageIndex > & const_cast_derived () const
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const SparseVector< _Scalar, _Options, _StorageIndex > > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const SparseVector< _Scalar, _Options, _StorageIndex > > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (SparseVector< _Scalar, _Options, _StorageIndex >, OtherDerived, product) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::equal_to< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType cwiseEqual (const Scalar &s) const
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::not_equal_to< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const ConstantReturnType > cwiseMin (const Scalar &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const ConstantReturnType > cwiseMax (const Scalar &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const SparseVector< _Scalar, _Options, _StorageIndex >, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block(Index,Index,Index,Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
EIGEN_DEVICE_FUNC RowsBlockXpr topRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr topRows (Index n) const
This is the const version of topRows(Index).
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr bottomRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr bottomRows (Index n) const
This is the const version of bottomRows(Index).
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr middleRows (Index startRow, Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr middleRows (Index startRow, Index n) const
This is the const version of middleRows(Index,Index).
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr leftCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr leftCols (Index n) const
This is the const version of leftCols(Index).
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr rightCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr rightCols (Index n) const
This is the const version of rightCols(Index).
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr middleCols (Index startCol, Index numCols)
EIGEN_DEVICE_FUNC ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
This is the const version of middleCols(Index,Index).
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
EIGEN_DEVICE_FUNC SegmentReturnType segment (Index start, Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType segment (Index start, Index n) const
This is the const version of segment(Index,Index).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
EIGEN_DEVICE_FUNC SegmentReturnType head (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType head (Index n) const
This is the const version of head(Index).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
EIGEN_DEVICE_FUNC SegmentReturnType tail (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType tail (Index n) const
This is the const version of tail(Index).
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
SparseVector< _Scalar, _Options, _StorageIndex > & markAsRValue ()
SparseMatrixBase ()
SparseVector< _Scalar, _Options, _StorageIndex > & operator+= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator+= (const DiagonalBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE SparseVector< _Scalar, _Options, _StorageIndex > & operator+= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator-= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator-= (const DiagonalBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE SparseVector< _Scalar, _Options, _StorageIndex > & operator-= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator*= (const Scalar &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator*= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar, _Options, _StorageIndex > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< SparseVector< _Scalar, _Options, _StorageIndex >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< SparseVector< _Scalar, _Options, _StorageIndex >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< SparseVector< _Scalar, _Options, _StorageIndex >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< SparseVector< _Scalar, _Options, _StorageIndex >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const SparseVector< _Scalar, _Options, _StorageIndex >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< SparseVector< _Scalar, _Options, _StorageIndex > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< SparseVector< _Scalar, _Options, _StorageIndex > >::type eval () const
Scalar sum () const
const SparseView< SparseVector< _Scalar, _Options, _StorageIndex > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Static Protected Member Functions
static void check_template_parameters ()
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >
static StorageIndex convert_index (const Index idx)
Protected Attributes
Storage m_data
Index m_size
Protected Attributes inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >
bool m_isRValue
Friends
std::ostream & operator<< (std::ostream &s, const SparseVector &m)
Additional Inherited Members
Protected Types inherited from Eigen::SparseCompressedBase< SparseVector< _Scalar, _Options, _StorageIndex > >
typedef Base::IndexVector IndexVector
Protected Member Functions inherited from Eigen::SparseCompressedBase< SparseVector< _Scalar, _Options, _StorageIndex > >
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
SparseCompressedBase ()
Protected Member Functions inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >
SparseVector< _Scalar, _Options, _StorageIndex > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Detailed Description
template<typename _Scalar, int _Options, typename _StorageIndex>
class Eigen::SparseVector< _Scalar, _Options, _StorageIndex >
a sparse vector class
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
See http://www.netlib.org/linalg/html_templates/node91.html for details on the storage scheme.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_SPARSEVECTOR_PLUGIN.
Definition at line 54 of file SparseUtil.h.
Member Typedef Documentation
InnerIterator
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Base::InnerIterator Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::InnerIterator
Definition at line 134 of file SparseVector.h.
ReverseInnerIterator
template<typename _Scalar, int _Options, typename _StorageIndex> typedef Base::ReverseInnerIterator Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::ReverseInnerIterator
Definition at line 135 of file SparseVector.h.
Storage
template<typename _Scalar, int _Options, typename _StorageIndex> typedef internal::CompressedStorage<Scalar,StorageIndex> Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::Storage
Definition at line 74 of file SparseVector.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int _Options, typename _StorageIndex> anonymous enum
Enumerator
IsColVector
Definition at line 75 of file SparseVector.h.
anonymous enum
template<typename _Scalar, int _Options, typename _StorageIndex> anonymous enum
Enumerator
Options
Definition at line 77 of file SparseVector.h.
Constructor & Destructor Documentation
SparseVector() [1/5]
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector () inline
Definition at line 259 of file SparseVector.h.
References resize().
SparseVector() [2/5]
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector (Index size) inline explicit
Definition at line 261 of file SparseVector.h.
References resize().
SparseVector() [3/5]
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector (Index rows, Index cols) inline
Definition at line 263 of file SparseVector.h.
References resize().
SparseVector() [4/5]
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector (const SparseMatrixBase< OtherDerived > & other) inline
Definition at line 266 of file SparseVector.h.
References Eigen::SparseMatrixBase< Derived >::derived(), and EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN.
SparseVector() [5/5]
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector (const SparseVector< _Scalar, _Options, _StorageIndex > & other) inline
Definition at line 276 of file SparseVector.h.
References Eigen::SparseMatrixBase< Derived >::derived().
~SparseVector()
template<typename _Scalar, int _Options, typename _StorageIndex> Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::~SparseVector () inline
Destructor
Definition at line 341 of file SparseVector.h.
References mpfr::sum().
Member Function Documentation
_data() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED Storage& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::_data () inline
Definition at line 387 of file SparseVector.h.
_data() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED const Storage& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::_data () const inline
Definition at line 389 of file SparseVector.h.
check_template_parameters()
template<typename _Scalar, int _Options, typename _StorageIndex> static void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::check_template_parameters () inline static protected
Definition at line 397 of file SparseVector.h.
References Eigen::ColMajor, EIGEN_STATIC_ASSERT, and Eigen::RowMajor.
coeff() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeff (Index row, Index col) const inline
Definition at line 102 of file SparseVector.h.
References eigen_assert.
coeff() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeff (Index i) const inline
Definition at line 107 of file SparseVector.h.
References eigen_assert.
coeffRef() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeffRef (Index row, Index col) inline
Definition at line 113 of file SparseVector.h.
References eigen_assert.
coeffRef() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeffRef (Index i) inline
Returns
a reference to the coefficient value at given index i This operation involes a log(rho*size) binary search. If the coefficient does not exist yet, then a sorted insertion into a sequential buffer is performed.
This insertion might be very costly if the number of nonzeros above i is large.
Definition at line 125 of file SparseVector.h.
References eigen_assert.
cols()
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::cols (void) const inline
Definition at line 82 of file SparseVector.h.
conservativeResize()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::conservativeResize (Index newSize) inline
Resizes the sparse vector to newSize, while leaving old values untouched.
If the size of the vector is decreased, then the storage of the out-of bounds coefficients is kept and reserved. Call .data().squeeze() to free extra memory.
See also
reserve(), setZero()
Definition at line 246 of file SparseVector.h.
References i.
data() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Storage& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::data () inline
Definition at line 98 of file SparseVector.h.
data() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> const Storage& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::data () const inline
Definition at line 100 of file SparseVector.h.
endFill()
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::endFill () inline
Definition at line 383 of file SparseVector.h.
fill() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::fill (Index r, Index c) inline
Definition at line 356 of file SparseVector.h.
References eigen_assert.
fill() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::fill (Index i) inline
Definition at line 363 of file SparseVector.h.
fillrand() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::fillrand (Index r, Index c) inline
Definition at line 370 of file SparseVector.h.
References eigen_assert.
fillrand() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::fillrand (Index i) inline
Definition at line 377 of file SparseVector.h.
References insert().
finalize()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::finalize () inline
Definition at line 207 of file SparseVector.h.
innerIndexPtr() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE const StorageIndex* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::innerIndexPtr () const inline
Definition at line 89 of file SparseVector.h.
innerIndexPtr() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE StorageIndex* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::innerIndexPtr () inline
Definition at line 90 of file SparseVector.h.
innerNonZeroPtr() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> const StorageIndex* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr () const inline
Definition at line 94 of file SparseVector.h.
innerNonZeroPtr() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr () inline
Definition at line 95 of file SparseVector.h.
innerSize()
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::innerSize () const inline
Definition at line 83 of file SparseVector.h.
insert() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert (Index row, Index col) inline
Definition at line 172 of file SparseVector.h.
References col(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, insert(), and row().
insert() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert (Index i) inline
Definition at line 182 of file SparseVector.h.
References Eigen::internal::convert_index(), eigen_assert, i, and p.
insertBack()
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insertBack (Index i) inline
Definition at line 154 of file SparseVector.h.
Referenced by initSparse().
insertBackByOuterInner()
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner (Index outer, Index inner) inline
Definition at line 148 of file SparseVector.h.
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
insertBackByOuterInnerUnordered()
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered (Index outer, Index inner) inline
Definition at line 160 of file SparseVector.h.
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
insertBackUnordered()
template<typename _Scalar, int _Options, typename _StorageIndex> Scalar& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insertBackUnordered (Index i) inline
Definition at line 166 of file SparseVector.h.
nonZeros()
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::nonZeros () const inline
Returns
the number of non zero coefficients
Definition at line 140 of file SparseVector.h.
operator=() [1/3]
template<typename _Scalar, int _Options, typename _StorageIndex> SparseVector& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator= (const SparseVector< _Scalar, _Options, _StorageIndex > & other) inline
Definition at line 301 of file SparseVector.h.
References Eigen::SparseMatrixBase< Derived >::const_cast_derived(), Eigen::SparseMatrixBase< Derived >::isRValue(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::m_data, resize(), Eigen::SparseMatrixBase< Derived >::size(), and Eigen::internal::swap().
operator=() [2/3]
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename OtherDerived > SparseVector& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
Definition at line 316 of file SparseVector.h.
References Eigen::SparseMatrixBase< Derived >::derived(), Eigen::TensorSycl::run(), Eigen::SparseMatrixBase< Derived >::size(), and Eigen::internal::swap().
operator=() [3/3]
template<typename _Scalar, int _Options, typename _StorageIndex> template<typename Lhs , typename Rhs > SparseVector& Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator= (const SparseSparseProduct< Lhs, Rhs > & product) inline
Definition at line 326 of file SparseVector.h.
outerIndexPtr() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> const StorageIndex* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::outerIndexPtr () const inline
Definition at line 92 of file SparseVector.h.
outerIndexPtr() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> StorageIndex* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::outerIndexPtr () inline
Definition at line 93 of file SparseVector.h.
outerSize()
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::outerSize () const inline
Definition at line 84 of file SparseVector.h.
prune()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::prune (const Scalar & reference, const RealScalar & epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Suppresses all nonzeros which are much smaller than reference under the tolerence epsilon
Definition at line 210 of file SparseVector.h.
reserve()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::reserve (Index reserveSize) inline
Definition at line 204 of file SparseVector.h.
Referenced by initSparse().
resize() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::resize (Index rows, Index cols) inline
Resizes the sparse vector to rows x cols
This method is provided for compatibility with matrices. For a column vector, cols must be equal to 1. For a row vector, rows must be equal to 1.
See also
resize(Index)
Definition at line 223 of file SparseVector.h.
References eigen_assert, and resize().
resize() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::resize (Index newSize) inline
Resizes the sparse vector to newSize This method deletes all entries, thus leaving an empty sparse vector
See also
conservativeResize(), setZero()
Definition at line 233 of file SparseVector.h.
resizeNonZeros()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::resizeNonZeros (Index size) inline
Definition at line 257 of file SparseVector.h.
rows()
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::rows (void) const inline
Definition at line 81 of file SparseVector.h.
setZero()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::setZero () inline
Definition at line 137 of file SparseVector.h.
Referenced by initSparse().
startFill()
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_DEPRECATED void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::startFill (Index reserve) inline
Definition at line 349 of file SparseVector.h.
References setZero().
startVec()
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::startVec (Index outer) inline
Definition at line 142 of file SparseVector.h.
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
sum()
template<typename _Scalar , int _Options, typename _Index > internal::traits< SparseVector< _Scalar, _Options, _Index > >::Scalar Eigen::SparseVector< _Scalar, _Options, _Index >::sum () const
Overloaded for performance
Definition at line 41 of file SparseRedux.h.
References cols, eigen_assert, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map(), rows, and mpfr::sum().
swap() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap (SparseVector< _Scalar, _Options, _StorageIndex > & other) inline
Swaps the values of *this and other. Overloaded for performance: this version performs a shallow swap by swaping pointers and attributes only.
See also
SparseMatrixBase::swap()
Definition at line 287 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::m_size, and std::swap().
swap() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> template<int OtherOptions> void Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap (SparseMatrix< Scalar, OtherOptions, StorageIndex > & other) inline
Definition at line 294 of file SparseVector.h.
References eigen_assert, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), and std::swap().
valuePtr() [1/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE const Scalar* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::valuePtr () const inline
Definition at line 86 of file SparseVector.h.
valuePtr() [2/2]
template<typename _Scalar, int _Options, typename _StorageIndex> EIGEN_STRONG_INLINE Scalar* Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::valuePtr () inline
Definition at line 87 of file SparseVector.h.
Friends And Related Function Documentation
operator<<
template<typename _Scalar, int _Options, typename _StorageIndex> std::ostream& operator<< (std::ostream & s, const SparseVector< _Scalar, _Options, _StorageIndex > & m) friend
Definition at line 332 of file SparseVector.h.
Field Documentation
m_data
template<typename _Scalar, int _Options, typename _StorageIndex> Storage Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::m_data protected
Definition at line 403 of file SparseVector.h.
Referenced by Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap().
m_size
template<typename _Scalar, int _Options, typename _StorageIndex> Index Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::m_size protected
Definition at line 404 of file SparseVector.h.
Referenced by Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseUtil.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseVector.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseRedux.h