pairinteraction: Eigen::NonBlockingThreadPoolTempl< Environment > Class Template Reference
Eigen::NonBlockingThreadPoolTempl< Environment > Class Template Reference
#include <NonBlockingThreadPool.h>
Public Types
typedef Environment::Task Task
typedef RunQueue< Task, 1024 > Queue
Public Member Functions
NonBlockingThreadPoolTempl (int num_threads, Environment env=Environment())
~NonBlockingThreadPoolTempl ()
void Schedule (std::function< void()> fn)
int NumThreads () const final
int CurrentThreadId () const final
Public Member Functions inherited from Eigen::ThreadPoolInterface
virtual ~ThreadPoolInterface ()
Detailed Description
template<typename Environment>
class Eigen::NonBlockingThreadPoolTempl< Environment >
Definition at line 17 of file NonBlockingThreadPool.h.
Member Typedef Documentation
Queue
template<typename Environment > typedef RunQueue<Task, 1024> Eigen::NonBlockingThreadPoolTempl< Environment >::Queue
Definition at line 20 of file NonBlockingThreadPool.h.
Task
template<typename Environment > typedef Environment::Task Eigen::NonBlockingThreadPoolTempl< Environment >::Task
Definition at line 19 of file NonBlockingThreadPool.h.
Constructor & Destructor Documentation
NonBlockingThreadPoolTempl()
template<typename Environment > Eigen::NonBlockingThreadPoolTempl< Environment >::NonBlockingThreadPoolTempl (int num_threads, Environment env = Environment()) inline
Definition at line 22 of file NonBlockingThreadPool.h.
References a, b, i, and Eigen::MaxSizeVector< T >::push_back().
~NonBlockingThreadPoolTempl()
template<typename Environment > Eigen::NonBlockingThreadPoolTempl< Environment >::~NonBlockingThreadPoolTempl () inline
Definition at line 62 of file NonBlockingThreadPool.h.
References i, Eigen::EventCount::Notify(), and Eigen::MaxSizeVector< T >::size().
Member Function Documentation
CurrentThreadId()
template<typename Environment > int Eigen::NonBlockingThreadPoolTempl< Environment >::CurrentThreadId () const inline final virtual
Implements Eigen::ThreadPoolInterface.
Definition at line 104 of file NonBlockingThreadPool.h.
References Eigen::EventCount::CancelWait(), Eigen::EventCount::CommitWait(), eigen_assert, EIGEN_STRONG_INLINE, EIGEN_THREAD_LOCAL, i, Eigen::EventCount::Notify(), Eigen::RunQueue< Work, kSize >::PopFront(), Eigen::EventCount::Prewait(), Eigen::numext::q, size, and Eigen::MaxSizeVector< T >::size().
NumThreads()
template<typename Environment > int Eigen::NonBlockingThreadPoolTempl< Environment >::NumThreads () const inline final virtual
Implements Eigen::ThreadPoolInterface.
Definition at line 100 of file NonBlockingThreadPool.h.
References Eigen::MaxSizeVector< T >::size().
Schedule()
template<typename Environment > void Eigen::NonBlockingThreadPoolTempl< Environment >::Schedule (std::function< void()> fn) inline virtual
Implements Eigen::ThreadPoolInterface.
Definition at line 74 of file NonBlockingThreadPool.h.
References Eigen::EventCount::Notify(), Eigen::RunQueue< Work, kSize >::PushBack(), Eigen::RunQueue< Work, kSize >::PushFront(), and Eigen::numext::q.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/ThreadPool/NonBlockingThreadPool.h