pairinteraction: eigen2_interface< real, SIZE > Class Template Reference
eigen2_interface< real, SIZE > Class Template Reference
#include <eigen2_interface.hh>
Public Types
enum { IsFixedSize = (SIZE!=Dynamic) }
typedef real real_type
typedef std::vector< real > stl_vector
typedef std::vector< stl_vector > stl_matrix
typedef Eigen::Matrix< real, SIZE, SIZE > gene_matrix
typedef Eigen::Matrix< real, SIZE, 1 > gene_vector
Static Public Member Functions
static std::string name (void)
static void free_matrix (gene_matrix &A, int N)
static void free_vector (gene_vector &B)
static BTL_DONT_INLINE void matrix_from_stl (gene_matrix &A, stl_matrix &A_stl)
static BTL_DONT_INLINE void vector_from_stl (gene_vector &B, stl_vector &B_stl)
static BTL_DONT_INLINE void vector_to_stl (gene_vector &B, stl_vector &B_stl)
static BTL_DONT_INLINE void matrix_to_stl (gene_matrix &A, stl_matrix &A_stl)
static void matrix_matrix_product (const gene_matrix &A, const gene_matrix &B, gene_matrix &X, int N)
static void transposed_matrix_matrix_product (const gene_matrix &A, const gene_matrix &B, gene_matrix &X, int N)
static void ata_product (const gene_matrix &A, gene_matrix &X, int N)
static void aat_product (const gene_matrix &A, gene_matrix &X, int N)
static void matrix_vector_product (const gene_matrix &A, const gene_vector &B, gene_vector &X, int N)
static void atv_product (gene_matrix &A, gene_vector &B, gene_vector &X, int N)
static void axpy (real coef, const gene_vector &X, gene_vector &Y, int N)
static void axpby (real a, const gene_vector &X, real b, gene_vector &Y, int N)
static void copy_matrix (const gene_matrix &source, gene_matrix &cible, int N)
static void copy_vector (const gene_vector &source, gene_vector &cible, int N)
static void trisolve_lower (const gene_matrix &L, const gene_vector &B, gene_vector &X, int N)
static void trisolve_lower_matrix (const gene_matrix &L, const gene_matrix &B, gene_matrix &X, int N)
static void cholesky (const gene_matrix &X, gene_matrix &C, int N)
static void lu_decomp (const gene_matrix &X, gene_matrix &C, int N)
static void tridiagonalization (const gene_matrix &X, gene_matrix &C, int N)
static void hessenberg (const gene_matrix &X, gene_matrix &C, int N)
Detailed Description
template<class real, int SIZE = Dynamic>
class eigen2_interface< real, SIZE >
Definition at line 31 of file eigen2_interface.hh.
Member Typedef Documentation
gene_matrix
template<class real , int SIZE = Dynamic> typedef Eigen::Matrix<real,SIZE,SIZE> eigen2_interface< real, SIZE >::gene_matrix
Definition at line 43 of file eigen2_interface.hh.
gene_vector
template<class real , int SIZE = Dynamic> typedef Eigen::Matrix<real,SIZE,1> eigen2_interface< real, SIZE >::gene_vector
Definition at line 44 of file eigen2_interface.hh.
real_type
template<class real , int SIZE = Dynamic> typedef real eigen2_interface< real, SIZE >::real_type
Definition at line 38 of file eigen2_interface.hh.
stl_matrix
template<class real , int SIZE = Dynamic> typedef std::vector<stl_vector> eigen2_interface< real, SIZE >::stl_matrix
Definition at line 41 of file eigen2_interface.hh.
stl_vector
template<class real , int SIZE = Dynamic> typedef std::vector<real> eigen2_interface< real, SIZE >::stl_vector
Definition at line 40 of file eigen2_interface.hh.
Member Enumeration Documentation
anonymous enum
template<class real , int SIZE = Dynamic> anonymous enum
Enumerator
IsFixedSize
Definition at line 36 of file eigen2_interface.hh.
Member Function Documentation
aat_product()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::aat_product (const gene_matrix & A, gene_matrix & X, int N) inline static
Definition at line 108 of file eigen2_interface.hh.
ata_product()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::ata_product (const gene_matrix & A, gene_matrix & X, int N) inline static
Definition at line 104 of file eigen2_interface.hh.
atv_product()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::atv_product (gene_matrix & A, gene_vector & B, gene_vector & X, int N) inline static
Definition at line 116 of file eigen2_interface.hh.
axpby()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::axpby (real a, const gene_vector & X, real b, gene_vector & Y, int N) inline static
Definition at line 124 of file eigen2_interface.hh.
axpy()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::axpy (real coef, const gene_vector & X, gene_vector & Y, int N) inline static
Definition at line 120 of file eigen2_interface.hh.
cholesky()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::cholesky (const gene_matrix & X, gene_matrix & C, int N) inline static
Definition at line 144 of file eigen2_interface.hh.
copy_matrix()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::copy_matrix (const gene_matrix & source, gene_matrix & cible, int N) inline static
Definition at line 128 of file eigen2_interface.hh.
copy_vector()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::copy_vector (const gene_vector & source, gene_vector & cible, int N) inline static
Definition at line 132 of file eigen2_interface.hh.
free_matrix()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::free_matrix (gene_matrix & A, int N) inline static
Definition at line 57 of file eigen2_interface.hh.
free_vector()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::free_vector (gene_vector & B) inline static
Definition at line 59 of file eigen2_interface.hh.
hessenberg()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::hessenberg (const gene_matrix & X, gene_matrix & C, int N) inline static
Definition at line 160 of file eigen2_interface.hh.
lu_decomp()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::lu_decomp (const gene_matrix & X, gene_matrix & C, int N) inline static
Definition at line 151 of file eigen2_interface.hh.
matrix_from_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen2_interface< real, SIZE >::matrix_from_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 61 of file eigen2_interface.hh.
References Eigen::PlainObjectBase< Derived >::coeffRef(), i, j, Eigen::PlainObjectBase< Derived >::resize(), and size.
matrix_matrix_product()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::matrix_matrix_product (const gene_matrix & A, const gene_matrix & B, gene_matrix & X, int N) inline static
Definition at line 96 of file eigen2_interface.hh.
matrix_to_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen2_interface< real, SIZE >::matrix_to_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 85 of file eigen2_interface.hh.
matrix_vector_product()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::matrix_vector_product (const gene_matrix & A, const gene_vector & B, gene_vector & X, int N) inline static
Definition at line 112 of file eigen2_interface.hh.
name()
template<class real , int SIZE = Dynamic> static std::string eigen2_interface< real, SIZE >::name (void) inline static
Definition at line 46 of file eigen2_interface.hh.
References Eigen::Dynamic, and SIZE.
transposed_matrix_matrix_product()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::transposed_matrix_matrix_product (const gene_matrix & A, const gene_matrix & B, gene_matrix & X, int N) inline static
Definition at line 100 of file eigen2_interface.hh.
tridiagonalization()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::tridiagonalization (const gene_matrix & X, gene_matrix & C, int N) inline static
Definition at line 156 of file eigen2_interface.hh.
trisolve_lower()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::trisolve_lower (const gene_matrix & L, const gene_vector & B, gene_vector & X, int N) inline static
Definition at line 136 of file eigen2_interface.hh.
trisolve_lower_matrix()
template<class real , int SIZE = Dynamic> static void eigen2_interface< real, SIZE >::trisolve_lower_matrix (const gene_matrix & L, const gene_matrix & B, gene_matrix & X, int N) inline static
Definition at line 140 of file eigen2_interface.hh.
vector_from_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen2_interface< real, SIZE >::vector_from_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 71 of file eigen2_interface.hh.
References Eigen::PlainObjectBase< Derived >::coeffRef(), i, and Eigen::PlainObjectBase< Derived >::resize().
vector_to_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen2_interface< real, SIZE >::vector_to_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 79 of file eigen2_interface.hh.
References Eigen::PlainObjectBase< Derived >::coeff(), and i.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/libs/eigen2/eigen2_interface.hh