pairinteraction: Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs, ConjRhs = false, Vectorizable = packet_traits<LhsScalar>::Vectorizable && packet_traits<RhsScalar>::Vectorizable, LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1,
RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1, ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1, NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS, nr = 4,
mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*LhsPacketSize, LhsProgress = LhsPacketSize, RhsProgress = 1
}
typedef std::complex< RealScalar > LhsScalar
typedef RealScalar RhsScalar
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef packet_traits< LhsScalar >::type _LhsPacket
typedef packet_traits< RhsScalar >::type _RhsPacket
typedef packet_traits< ResScalar >::type _ResPacket
typedef conditional< Vectorizable, _LhsPacket, LhsScalar >::type LhsPacket
typedef conditional< Vectorizable, _RhsPacket, RhsScalar >::type RhsPacket
typedef conditional< Vectorizable, _ResPacket, ResScalar >::type ResPacket
typedef ResPacket AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (AccPacket &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp) const
EIGEN_STRONG_INLINE void madd_impl (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp, const true_type &) const
EIGEN_STRONG_INLINE void madd_impl (const LhsScalar &a, const RhsScalar &b, ResScalar &c, RhsScalar &, const false_type &) const
EIGEN_STRONG_INLINE void acc (const AccPacket &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< ResPacket, ResPacket, ConjLhs, false > cj
Detailed Description
template<typename RealScalar, bool _ConjLhs>
class Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >
Definition at line 464 of file GeneralBlockPanelKernel.h.
Member Typedef Documentation
_LhsPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<LhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_LhsPacket
Definition at line 492 of file GeneralBlockPanelKernel.h.
_ResPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<ResScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_ResPacket
Definition at line 494 of file GeneralBlockPanelKernel.h.
_RhsPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<RhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_RhsPacket
Definition at line 493 of file GeneralBlockPanelKernel.h.
AccPacket
template<typename RealScalar , bool _ConjLhs> typedef ResPacket Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::AccPacket
Definition at line 500 of file GeneralBlockPanelKernel.h.
LhsPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_LhsPacket,LhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::LhsPacket
Definition at line 496 of file GeneralBlockPanelKernel.h.
LhsScalar
template<typename RealScalar , bool _ConjLhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::LhsScalar
Definition at line 467 of file GeneralBlockPanelKernel.h.
ResPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_ResPacket,ResScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::ResPacket
Definition at line 498 of file GeneralBlockPanelKernel.h.
ResScalar
template<typename RealScalar , bool _ConjLhs> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::ResScalar
Definition at line 469 of file GeneralBlockPanelKernel.h.
RhsPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_RhsPacket,RhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::RhsPacket
Definition at line 497 of file GeneralBlockPanelKernel.h.
RhsScalar
template<typename RealScalar , bool _ConjLhs> typedef RealScalar Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::RhsScalar
Definition at line 468 of file GeneralBlockPanelKernel.h.
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool _ConjLhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
NumberOfRegisters
nr
mr
LhsProgress
RhsProgress
Definition at line 471 of file GeneralBlockPanelKernel.h.
Member Function Documentation
acc()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::acc (const AccPacket & c, const ResPacket & alpha, ResPacket & r) const inline
Definition at line 557 of file GeneralBlockPanelKernel.h.
broadcastRhs()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
Definition at line 527 of file GeneralBlockPanelKernel.h.
References Eigen::internal::pbroadcast4().
initAcc()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::initAcc (AccPacket & p) inline
Definition at line 502 of file GeneralBlockPanelKernel.h.
loadLhs()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
Definition at line 517 of file GeneralBlockPanelKernel.h.
References a.
loadLhsUnaligned()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
Definition at line 522 of file GeneralBlockPanelKernel.h.
References a.
loadRhs()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadRhs (const RhsScalar * b, RhsPacket & dest) const inline
Definition at line 507 of file GeneralBlockPanelKernel.h.
loadRhsQuad()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadRhsQuad (const RhsScalar * b, RhsPacket & dest) const inline
Definition at line 512 of file GeneralBlockPanelKernel.h.
madd()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp) const inline
Definition at line 537 of file GeneralBlockPanelKernel.h.
madd_impl() [1/2]
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp, const true_type &) const inline
Definition at line 542 of file GeneralBlockPanelKernel.h.
References b, EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmadd(), and Eigen::internal::pmul().
madd_impl() [2/2]
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl (const LhsScalar & a, const RhsScalar & b, ResScalar & c, RhsScalar & , const false_type &) const inline
Definition at line 552 of file GeneralBlockPanelKernel.h.
References b.
Field Documentation
cj
template<typename RealScalar , bool _ConjLhs> conj_helper<ResPacket,ResPacket,ConjLhs,false> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::cj protected
Definition at line 563 of file GeneralBlockPanelKernel.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h