pairinteraction: Eigen::SkylineStorage< Scalar > Class Template Reference
Eigen::SkylineStorage< Scalar > Class Template Reference
#include <SkylineStorage.h>
Public Member Functions
SkylineStorage ()
SkylineStorage (const SkylineStorage &other)
SkylineStorage & operator= (const SkylineStorage &other)
void swap (SkylineStorage &other)
~SkylineStorage ()
void reserve (Index size, Index upperProfileSize, Index lowerProfileSize, Index upperSize, Index lowerSize)
void squeeze ()
void resize (Index diagSize, Index upperProfileSize, Index lowerProfileSize, Index upperSize, Index lowerSize, float reserveSizeFactor=0)
Index diagSize () const
Index upperSize () const
Index lowerSize () const
Index upperProfileSize () const
Index lowerProfileSize () const
Index allocatedSize () const
void clear ()
Scalar & diag (Index i)
const Scalar & diag (Index i) const
Scalar & upper (Index i)
const Scalar & upper (Index i) const
Scalar & lower (Index i)
const Scalar & lower (Index i) const
Index & upperProfile (Index i)
const Index & upperProfile (Index i) const
Index & lowerProfile (Index i)
const Index & lowerProfile (Index i) const
void reset ()
void prune (Scalar reference, RealScalar epsilon=dummy_precision< RealScalar >())
Static Public Member Functions
static SkylineStorage Map (Index *upperProfile, Index *lowerProfile, Scalar *diag, Scalar *upper, Scalar *lower, Index size, Index upperSize, Index lowerSize)
Data Fields
Scalar * m_diag
Scalar * m_upper
Scalar * m_lower
Index * m_upperProfile
Index * m_lowerProfile
Index m_diagSize
Index m_upperSize
Index m_lowerSize
Index m_upperProfileSize
Index m_lowerProfileSize
Index m_allocatedSize
Protected Member Functions
void reallocate (Index diagSize, Index upperProfileSize, Index lowerProfileSize, Index upperSize, Index lowerSize)
Detailed Description
template<typename Scalar>
class Eigen::SkylineStorage< Scalar >
Stores a skyline set of values in three structures : The diagonal elements The upper elements The lower elements
Definition at line 22 of file SkylineStorage.h.
Constructor & Destructor Documentation
SkylineStorage() [1/2]
template<typename Scalar> Eigen::SkylineStorage< Scalar >::SkylineStorage () inline
Definition at line 27 of file SkylineStorage.h.
SkylineStorage() [2/2]
template<typename Scalar> Eigen::SkylineStorage< Scalar >::SkylineStorage (const SkylineStorage< Scalar > & other) inline
Definition at line 41 of file SkylineStorage.h.
~SkylineStorage()
template<typename Scalar> Eigen::SkylineStorage< Scalar >::~SkylineStorage () inline
Definition at line 78 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_diag, Eigen::SkylineStorage< Scalar >::m_lower, Eigen::SkylineStorage< Scalar >::m_lowerProfile, Eigen::SkylineStorage< Scalar >::m_upper, and Eigen::SkylineStorage< Scalar >::m_upperProfile.
Member Function Documentation
allocatedSize()
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::allocatedSize () const inline
Definition at line 128 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_allocatedSize.
clear()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::clear (void) inline
Definition at line 132 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_diagSize.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::resize(), and Eigen::SkylineMatrix< _Scalar, _Options >::setZero().
diag() [1/2]
template<typename Scalar> Scalar& Eigen::SkylineStorage< Scalar >::diag (Index i) inline
Definition at line 136 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_diag.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::_diagPtr(), Eigen::SkylineMatrix< _Scalar, _Options >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffDiag(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefDiag(), Eigen::SkylineMatrix< _Scalar, _Options >::insert(), Eigen::SkylineStorage< Scalar >::Map(), and Eigen::SkylineStorage< Scalar >::reallocate().
diag() [2/2]
template<typename Scalar> const Scalar& Eigen::SkylineStorage< Scalar >::diag (Index i) const inline
Definition at line 140 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_diag.
diagSize()
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::diagSize () const inline
Definition at line 108 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_diagSize.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::nonZeros(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), and Eigen::SkylineStorage< Scalar >::resize().
lower() [1/2]
template<typename Scalar> Scalar& Eigen::SkylineStorage< Scalar >::lower (Index i) inline
Definition at line 152 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_lower.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::_lowerPtr(), Eigen::SkylineMatrix< _Scalar, _Options >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffLower(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefLower(), Eigen::SkylineMatrix< _Scalar, _Options >::insert(), Eigen::SkylineStorage< Scalar >::Map(), and Eigen::SkylineStorage< Scalar >::reallocate().
lower() [2/2]
template<typename Scalar> const Scalar& Eigen::SkylineStorage< Scalar >::lower (Index i) const inline
Definition at line 156 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_lower.
lowerProfile() [1/2]
template<typename Scalar> Index& Eigen::SkylineStorage< Scalar >::lowerProfile (Index i) inline
Definition at line 168 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_lowerProfile.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::_lowerProfilePtr(), Eigen::SkylineMatrix< _Scalar, _Options >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffExistLower(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffLower(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefLower(), Eigen::SkylineMatrix< _Scalar, _Options >::insert(), Eigen::SkylineStorage< Scalar >::Map(), and Eigen::SkylineStorage< Scalar >::reallocate().
lowerProfile() [2/2]
template<typename Scalar> const Index& Eigen::SkylineStorage< Scalar >::lowerProfile (Index i) const inline
Definition at line 172 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_lowerProfile.
lowerProfileSize()
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::lowerProfileSize () const inline
Definition at line 124 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_lowerProfileSize.
Referenced by Eigen::SkylineStorage< Scalar >::reallocate(), and Eigen::SkylineStorage< Scalar >::resize().
lowerSize()
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::lowerSize () const inline
Definition at line 116 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_lowerSize.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::lowerNonZeros(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineMatrix< _Scalar, _Options >::nonZeros(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reserve(), and Eigen::SkylineStorage< Scalar >::resize().
Map()
template<typename Scalar> static SkylineStorage Eigen::SkylineStorage< Scalar >::Map (Index * upperProfile, Index * lowerProfile, Scalar * diag, Scalar * upper, Scalar * lower, Index size, Index upperSize, Index lowerSize) inline static
Definition at line 176 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::diag(), Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), Eigen::SkylineStorage< Scalar >::lowerSize(), Eigen::SkylineStorage< Scalar >::m_allocatedSize, Eigen::SkylineStorage< Scalar >::m_diag, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lower, Eigen::SkylineStorage< Scalar >::m_lowerProfile, Eigen::SkylineStorage< Scalar >::m_lowerSize, Eigen::SkylineStorage< Scalar >::m_upper, Eigen::SkylineStorage< Scalar >::m_upperProfile, Eigen::SkylineStorage< Scalar >::m_upperSize, res, size, Eigen::SkylineStorage< Scalar >::upper(), Eigen::SkylineStorage< Scalar >::upperProfile(), and Eigen::SkylineStorage< Scalar >::upperSize().
operator=()
template<typename Scalar> SkylineStorage& Eigen::SkylineStorage< Scalar >::operator= (const SkylineStorage< Scalar > & other) inline
Definition at line 56 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::diagSize(), Eigen::SkylineStorage< Scalar >::lowerSize(), Eigen::SkylineStorage< Scalar >::m_diag, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lower, Eigen::SkylineStorage< Scalar >::m_lowerProfile, Eigen::SkylineStorage< Scalar >::m_lowerProfileSize, Eigen::SkylineStorage< Scalar >::m_upper, Eigen::SkylineStorage< Scalar >::m_upperProfile, Eigen::SkylineStorage< Scalar >::m_upperProfileSize, Eigen::SkylineStorage< Scalar >::resize(), and Eigen::SkylineStorage< Scalar >::upperSize().
prune()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::prune (Scalar reference, RealScalar epsilon = dummy_precision<RealScalar>()) inline
Definition at line 197 of file SkylineStorage.h.
reallocate()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::reallocate (Index diagSize, Index upperProfileSize, Index lowerProfileSize, Index upperSize, Index lowerSize) inline protected
Definition at line 203 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::diag(), Eigen::SkylineStorage< Scalar >::diagSize(), Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), Eigen::SkylineStorage< Scalar >::lowerProfileSize(), Eigen::SkylineStorage< Scalar >::lowerSize(), Eigen::SkylineStorage< Scalar >::m_allocatedSize, Eigen::SkylineStorage< Scalar >::m_diag, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lower, Eigen::SkylineStorage< Scalar >::m_lowerProfile, Eigen::SkylineStorage< Scalar >::m_lowerProfileSize, Eigen::SkylineStorage< Scalar >::m_lowerSize, Eigen::SkylineStorage< Scalar >::m_upper, Eigen::SkylineStorage< Scalar >::m_upperProfile, Eigen::SkylineStorage< Scalar >::m_upperProfileSize, Eigen::SkylineStorage< Scalar >::m_upperSize, min, Eigen::SkylineStorage< Scalar >::upper(), Eigen::SkylineStorage< Scalar >::upperProfile(), Eigen::SkylineStorage< Scalar >::upperProfileSize(), and Eigen::SkylineStorage< Scalar >::upperSize().
Referenced by Eigen::SkylineStorage< Scalar >::reserve(), Eigen::SkylineStorage< Scalar >::resize(), and Eigen::SkylineStorage< Scalar >::squeeze().
reserve()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::reserve (Index size, Index upperProfileSize, Index lowerProfileSize, Index upperSize, Index lowerSize) inline
Definition at line 87 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::lowerSize(), Eigen::SkylineStorage< Scalar >::m_allocatedSize, and Eigen::SkylineStorage< Scalar >::reallocate().
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::reserve().
reset()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::reset () inline
Definition at line 189 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_diag, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lower, Eigen::SkylineStorage< Scalar >::m_lowerProfile, Eigen::SkylineStorage< Scalar >::m_lowerSize, Eigen::SkylineStorage< Scalar >::m_upper, Eigen::SkylineStorage< Scalar >::m_upperProfile, and Eigen::SkylineStorage< Scalar >::m_upperSize.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::resize().
resize()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::resize (Index diagSize, Index upperProfileSize, Index lowerProfileSize, Index upperSize, Index lowerSize, float reserveSizeFactor = 0) inline
Definition at line 98 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::diagSize(), Eigen::SkylineStorage< Scalar >::lowerProfileSize(), Eigen::SkylineStorage< Scalar >::lowerSize(), Eigen::SkylineStorage< Scalar >::m_allocatedSize, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lowerProfileSize, Eigen::SkylineStorage< Scalar >::m_lowerSize, Eigen::SkylineStorage< Scalar >::m_upperProfileSize, Eigen::SkylineStorage< Scalar >::m_upperSize, Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::upperProfileSize(), and Eigen::SkylineStorage< Scalar >::upperSize().
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::finalize(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineMatrix< _Scalar, _Options >::resize(), and Eigen::SkylineMatrix< _Scalar, _Options >::resizeNonZeros().
squeeze()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::squeeze () inline
Definition at line 93 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_allocatedSize, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lowerProfileSize, Eigen::SkylineStorage< Scalar >::m_lowerSize, Eigen::SkylineStorage< Scalar >::m_upperProfileSize, Eigen::SkylineStorage< Scalar >::m_upperSize, and Eigen::SkylineStorage< Scalar >::reallocate().
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::squeeze().
swap()
template<typename Scalar> void Eigen::SkylineStorage< Scalar >::swap (SkylineStorage< Scalar > & other) inline
Definition at line 66 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_allocatedSize, Eigen::SkylineStorage< Scalar >::m_diag, Eigen::SkylineStorage< Scalar >::m_diagSize, Eigen::SkylineStorage< Scalar >::m_lower, Eigen::SkylineStorage< Scalar >::m_lowerProfile, Eigen::SkylineStorage< Scalar >::m_lowerSize, Eigen::SkylineStorage< Scalar >::m_upper, Eigen::SkylineStorage< Scalar >::m_upperProfile, Eigen::SkylineStorage< Scalar >::m_upperSize, and std::swap().
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::swap().
upper() [1/2]
template<typename Scalar> Scalar& Eigen::SkylineStorage< Scalar >::upper (Index i) inline
Definition at line 144 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_upper.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::_upperPtr(), Eigen::SkylineMatrix< _Scalar, _Options >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::insert(), Eigen::SkylineStorage< Scalar >::Map(), and Eigen::SkylineStorage< Scalar >::reallocate().
upper() [2/2]
template<typename Scalar> const Scalar& Eigen::SkylineStorage< Scalar >::upper (Index i) const inline
Definition at line 148 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_upper.
upperProfile() [1/2]
template<typename Scalar> Index& Eigen::SkylineStorage< Scalar >::upperProfile (Index i) inline
Definition at line 160 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_upperProfile.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::_upperProfilePtr(), Eigen::SkylineMatrix< _Scalar, _Options >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffExistUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::insert(), Eigen::SkylineStorage< Scalar >::Map(), and Eigen::SkylineStorage< Scalar >::reallocate().
upperProfile() [2/2]
template<typename Scalar> const Index& Eigen::SkylineStorage< Scalar >::upperProfile (Index i) const inline
Definition at line 164 of file SkylineStorage.h.
References i, and Eigen::SkylineStorage< Scalar >::m_upperProfile.
upperProfileSize()
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::upperProfileSize () const inline
Definition at line 120 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_upperProfileSize.
Referenced by Eigen::SkylineStorage< Scalar >::reallocate(), and Eigen::SkylineStorage< Scalar >::resize().
upperSize()
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::upperSize () const inline
Definition at line 112 of file SkylineStorage.h.
References Eigen::SkylineStorage< Scalar >::m_upperSize.
Referenced by Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineMatrix< _Scalar, _Options >::nonZeros(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::resize(), and Eigen::SkylineMatrix< _Scalar, _Options >::upperNonZeros().
Field Documentation
m_allocatedSize
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::m_allocatedSize
Definition at line 253 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::allocatedSize(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reserve(), Eigen::SkylineStorage< Scalar >::resize(), Eigen::SkylineStorage< Scalar >::squeeze(), and Eigen::SkylineStorage< Scalar >::swap().
m_diag
template<typename Scalar> Scalar* Eigen::SkylineStorage< Scalar >::m_diag
Definition at line 243 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::diag(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::swap(), and Eigen::SkylineStorage< Scalar >::~SkylineStorage().
m_diagSize
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::m_diagSize
Definition at line 248 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::clear(), Eigen::SkylineStorage< Scalar >::diagSize(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::resize(), Eigen::SkylineStorage< Scalar >::squeeze(), and Eigen::SkylineStorage< Scalar >::swap().
m_lower
template<typename Scalar> Scalar* Eigen::SkylineStorage< Scalar >::m_lower
Definition at line 245 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::swap(), and Eigen::SkylineStorage< Scalar >::~SkylineStorage().
m_lowerProfile
template<typename Scalar> Index* Eigen::SkylineStorage< Scalar >::m_lowerProfile
Definition at line 247 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::lowerProfile(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::swap(), and Eigen::SkylineStorage< Scalar >::~SkylineStorage().
m_lowerProfileSize
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::m_lowerProfileSize
Definition at line 252 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::lowerProfileSize(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::resize(), and Eigen::SkylineStorage< Scalar >::squeeze().
m_lowerSize
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::m_lowerSize
Definition at line 250 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::lowerSize(), Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::resize(), Eigen::SkylineStorage< Scalar >::squeeze(), and Eigen::SkylineStorage< Scalar >::swap().
m_upper
template<typename Scalar> Scalar* Eigen::SkylineStorage< Scalar >::m_upper
Definition at line 244 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::swap(), Eigen::SkylineStorage< Scalar >::upper(), and Eigen::SkylineStorage< Scalar >::~SkylineStorage().
m_upperProfile
template<typename Scalar> Index* Eigen::SkylineStorage< Scalar >::m_upperProfile
Definition at line 246 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::swap(), Eigen::SkylineStorage< Scalar >::upperProfile(), and Eigen::SkylineStorage< Scalar >::~SkylineStorage().
m_upperProfileSize
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::m_upperProfileSize
Definition at line 251 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::operator=(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::resize(), Eigen::SkylineStorage< Scalar >::squeeze(), and Eigen::SkylineStorage< Scalar >::upperProfileSize().
m_upperSize
template<typename Scalar> Index Eigen::SkylineStorage< Scalar >::m_upperSize
Definition at line 249 of file SkylineStorage.h.
Referenced by Eigen::SkylineStorage< Scalar >::Map(), Eigen::SkylineStorage< Scalar >::reallocate(), Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::resize(), Eigen::SkylineStorage< Scalar >::squeeze(), Eigen::SkylineStorage< Scalar >::swap(), and Eigen::SkylineStorage< Scalar >::upperSize().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/Skyline/SkylineStorage.h