pairinteraction: Eigen::JacobiSVD< _MatrixType, QRPreconditioner > Class Template Reference
Eigen::JacobiSVD< _MatrixType, QRPreconditioner > Class Template Reference
Dense linear problems and decompositions » Reference » SVD_Module
Two-sided Jacobi SVD decomposition of a rectangular matrix.
#include <ForwardDeclarations.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime), MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime, MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime), MatrixOptions = MatrixType::Options
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename MatrixType::Scalar >::Real RealScalar
typedef Base::MatrixUType MatrixUType
typedef Base::MatrixVType MatrixVType
typedef Base::SingularValuesType SingularValuesType
typedef internal::plain_row_type< MatrixType >::type RowType
typedef internal::plain_col_type< MatrixType >::type ColType
typedef Matrix< Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime > WorkMatrixType
Public Types inherited from Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >
enum
typedef internal::traits< JacobiSVD< _MatrixType, QRPreconditioner > >::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename MatrixType::Scalar >::Real RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Eigen::Index Index
typedef Matrix< Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime > MatrixUType
typedef Matrix< Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime > MatrixVType
typedef internal::plain_diag_type< MatrixType, RealScalar >::type SingularValuesType
Public Member Functions
JacobiSVD ()
Default Constructor.
JacobiSVD (Index rows, Index cols, unsigned int computationOptions=0)
Default Constructor with memory preallocation.
JacobiSVD (const MatrixType &matrix, unsigned int computationOptions=0)
Constructor performing the decomposition of given matrix.
JacobiSVD & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
JacobiSVD & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix using current options.
Public Member Functions inherited from Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >
JacobiSVD< _MatrixType, QRPreconditioner > & derived ()
const JacobiSVD< _MatrixType, QRPreconditioner > & derived () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
Index nonzeroSingularValues () const
Index rank () const
JacobiSVD< _MatrixType, QRPreconditioner > & setThreshold (const RealScalar &threshold)
JacobiSVD< _MatrixType, QRPreconditioner > & setThreshold (Default_t)
RealScalar threshold () const
bool computeU () const
bool computeV () const
Index rows () const
Index cols () const
const Solve< JacobiSVD< _MatrixType, QRPreconditioner >, Rhs > solve (const MatrixBase< Rhs > &b) const
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Attributes
WorkMatrixType m_workMatrix
internal::qr_preconditioner_impl< MatrixType, QRPreconditioner, internal::PreconditionIfMoreColsThanRows > m_qr_precond_morecols
internal::qr_preconditioner_impl< MatrixType, QRPreconditioner, internal::PreconditionIfMoreRowsThanCols > m_qr_precond_morerows
MatrixType m_scaledMatrix
Protected Attributes inherited from Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
bool m_isInitialized
bool m_isAllocated
bool m_usePrescribedThreshold
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
Index m_rows
Index m_cols
Index m_diagSize
RealScalar m_prescribedThreshold
Friends
template<typename __MatrixType , int _QRPreconditioner, bool _IsComplex>
struct internal::svd_precondition_2x2_block_to_be_real
template<typename __MatrixType , int _QRPreconditioner, int _Case, bool _DoAnything>
struct internal::qr_preconditioner_impl
Additional Inherited Members
Protected Member Functions inherited from Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >
bool allocate (Index rows, Index cols, unsigned int computationOptions)
SVDBase ()
Default Constructor.
Static Protected Member Functions inherited from Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >
static void check_template_parameters ()
Detailed Description
template<typename _MatrixType, int QRPreconditioner>
class Eigen::JacobiSVD< _MatrixType, QRPreconditioner >
Two-sided Jacobi SVD decomposition of a rectangular matrix.
Template Parameters
_MatrixType the type of the matrix of which we are computing the SVD decomposition
QRPreconditioner this optional parameter allows to specify the type of QR decomposition that will be used internally for the R-SVD step for non-square matrices. See discussion of possible values below.
SVD decomposition consists in decomposing any n-by-p matrix A as a product
\[ A = U S V^* \]
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
This JacobiSVD decomposition computes only the singular values by default. If you want U or V, you need to ask for them explicitly.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
Here's an example demonstrating basic usage:
Output:
This JacobiSVD class is a two-sided Jacobi R-SVD decomposition, ensuring optimal reliability and accuracy. The downside is that it's slower than bidiagonalizing SVD algorithms for large square matrices; however its complexity is still \(O(n^2p) \) where n is the smaller dimension and p is the greater dimension, meaning that it is still of the same order of complexity as the faster bidiagonalizing R-SVD algorithms. In particular, like any R-SVD, it takes advantage of non-squareness in that its complexity is only linear in the greater dimension.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
The possible values for QRPreconditioner are:
ColPivHouseholderQRPreconditioner is the default. In practice it's very safe. It uses column-pivoting QR.
FullPivHouseholderQRPreconditioner, is the safest and slowest. It uses full-pivoting QR. Contrary to other QRs, it doesn't allow computing thin unitaries.
HouseholderQRPreconditioner is the fastest, and less safe and accurate than the pivoting variants. It uses non-pivoting QR. This is very similar in safety and accuracy to the bidiagonalization process used by bidiagonalizing SVD algorithms (since bidiagonalization is inherently non-pivoting). However the resulting SVD is still more reliable than bidiagonalizing SVDs because the Jacobi-based iterarive process is more reliable than the optimized bidiagonal SVD iterations.
NoQRPreconditioner allows not to use a QR preconditioner at all. This is useful if you know that you will only be computing JacobiSVD decompositions of square matrices. Non-square matrices require a QR preconditioner. Using this option will result in faster compilation and smaller executable code. It won't significantly speed up computation, since JacobiSVD is always checking if QR preconditioning is needed before applying it anyway.
See also
MatrixBase::jacobiSvd()
Definition at line 258 of file ForwardDeclarations.h.
Member Typedef Documentation
ColType
template<typename _MatrixType, int QRPreconditioner> typedef internal::plain_col_type<MatrixType>::type Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::ColType
Definition at line 511 of file JacobiSVD.h.
MatrixType
template<typename _MatrixType, int QRPreconditioner> typedef _MatrixType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::MatrixType
Definition at line 493 of file JacobiSVD.h.
MatrixUType
template<typename _MatrixType, int QRPreconditioner> typedef Base::MatrixUType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::MatrixUType
Definition at line 506 of file JacobiSVD.h.
MatrixVType
template<typename _MatrixType, int QRPreconditioner> typedef Base::MatrixVType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::MatrixVType
Definition at line 507 of file JacobiSVD.h.
RealScalar
template<typename _MatrixType, int QRPreconditioner> typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::RealScalar
Definition at line 495 of file JacobiSVD.h.
RowType
template<typename _MatrixType, int QRPreconditioner> typedef internal::plain_row_type<MatrixType>::type Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::RowType
Definition at line 510 of file JacobiSVD.h.
Scalar
template<typename _MatrixType, int QRPreconditioner> typedef MatrixType::Scalar Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::Scalar
Definition at line 494 of file JacobiSVD.h.
SingularValuesType
template<typename _MatrixType, int QRPreconditioner> typedef Base::SingularValuesType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::SingularValuesType
Definition at line 508 of file JacobiSVD.h.
WorkMatrixType
template<typename _MatrixType, int QRPreconditioner> typedef Matrix<Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::WorkMatrixType
Definition at line 514 of file JacobiSVD.h.
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType, int QRPreconditioner> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
DiagSizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxDiagSizeAtCompileTime
MatrixOptions
Definition at line 496 of file JacobiSVD.h.
Constructor & Destructor Documentation
JacobiSVD() [1/3]
template<typename _MatrixType, int QRPreconditioner> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via JacobiSVD::compute(const MatrixType&).
Definition at line 521 of file JacobiSVD.h.
JacobiSVD() [2/3]
template<typename _MatrixType, int QRPreconditioner> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD (Index rows, Index cols, unsigned int computationOptions = 0) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
JacobiSVD()
Definition at line 531 of file JacobiSVD.h.
JacobiSVD() [3/3]
template<typename _MatrixType, int QRPreconditioner> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD (const MatrixType & matrix, unsigned int computationOptions = 0) inline explicit
Constructor performing the decomposition of given matrix.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are ComputeFullU, ComputeThinU, ComputeFullV, ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
Definition at line 546 of file JacobiSVD.h.
References compute(), and matrix().
Member Function Documentation
compute() [1/2]
template<typename MatrixType , int QRPreconditioner> JacobiSVD< MatrixType, QRPreconditioner > & Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute (const MatrixType & matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are ComputeFullU, ComputeThinU, ComputeFullV, ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
Definition at line 663 of file JacobiSVD.h.
References a, abs(), i, imag(), min, p, Eigen::numext::q, Eigen::internal::real_2x2_jacobi_svd(), scale, std::swap(), and Eigen::JacobiRotation< Scalar >::transpose().
Referenced by ctms_decompositions(), and jacobisvd_verify_assert().
compute() [2/2]
template<typename _MatrixType, int QRPreconditioner> JacobiSVD& Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute (const MatrixType & matrix) inline
Method performing the decomposition of given matrix using current options.
Parameters
matrix the matrix to decompose
This method uses the current computationOptions, as already passed to the constructor or to compute(const MatrixType&, unsigned int).
Definition at line 569 of file JacobiSVD.h.
References cols, compute(), and rows.
Friends And Related Function Documentation
internal::qr_preconditioner_impl
template<typename _MatrixType, int QRPreconditioner> template<typename __MatrixType , int _QRPreconditioner, int _Case, bool _DoAnything> friend struct internal::qr_preconditioner_impl friend
Definition at line 605 of file JacobiSVD.h.
internal::svd_precondition_2x2_block_to_be_real
template<typename _MatrixType, int QRPreconditioner> template<typename __MatrixType , int _QRPreconditioner, bool _IsComplex> friend struct internal::svd_precondition_2x2_block_to_be_real friend
Definition at line 603 of file JacobiSVD.h.
Field Documentation
m_qr_precond_morecols
template<typename _MatrixType, int QRPreconditioner> internal::qr_preconditioner_impl<MatrixType, QRPreconditioner, internal::PreconditionIfMoreColsThanRows> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_qr_precond_morecols protected
Definition at line 607 of file JacobiSVD.h.
m_qr_precond_morerows
template<typename _MatrixType, int QRPreconditioner> internal::qr_preconditioner_impl<MatrixType, QRPreconditioner, internal::PreconditionIfMoreRowsThanCols> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_qr_precond_morerows protected
Definition at line 608 of file JacobiSVD.h.
m_scaledMatrix
template<typename _MatrixType, int QRPreconditioner> MatrixType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_scaledMatrix protected
Definition at line 609 of file JacobiSVD.h.
m_workMatrix
template<typename _MatrixType, int QRPreconditioner> WorkMatrixType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix protected
Definition at line 600 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/SVD/JacobiSVD.h