pairinteraction: Eigen::GMRES< _MatrixType, _Preconditioner > Class Template Reference
Eigen::GMRES< _MatrixType, _Preconditioner > Class Template Reference
Sparse linear algebra » Reference » IterativeLinearSolvers_Module
A GMRES solver for sparse square problems.
#include <GMRES.h>
Public Types
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef _Preconditioner Preconditioner
Public Types inherited from Eigen::IterativeSolverBase< GMRES< _MatrixType, _Preconditioner > >
enum
typedef internal::traits< GMRES< _MatrixType, _Preconditioner > >::MatrixType MatrixType
typedef internal::traits< GMRES< _MatrixType, _Preconditioner > >::Preconditioner Preconditioner
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef MatrixType::RealScalar RealScalar
Public Member Functions
GMRES ()
template<typename MatrixDerived >
GMRES (const EigenBase< MatrixDerived > &A)
~GMRES ()
Index get_restart ()
void set_restart (const Index restart)
template<typename Rhs , typename Dest >
void _solve_with_guess_impl (const Rhs &b, Dest &x) const
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, MatrixBase< Dest > &x) const
Public Member Functions inherited from Eigen::IterativeSolverBase< GMRES< _MatrixType, _Preconditioner > >
IterativeSolverBase ()
IterativeSolverBase (const EigenBase< MatrixDerived > &A)
~IterativeSolverBase ()
GMRES< _MatrixType, _Preconditioner > & analyzePattern (const EigenBase< MatrixDerived > &A)
GMRES< _MatrixType, _Preconditioner > & factorize (const EigenBase< MatrixDerived > &A)
GMRES< _MatrixType, _Preconditioner > & compute (const EigenBase< MatrixDerived > &A)
Index rows () const
Index cols () const
RealScalar tolerance () const
GMRES< _MatrixType, _Preconditioner > & setTolerance (const RealScalar &tolerance)
Preconditioner & preconditioner ()
const Preconditioner & preconditioner () const
Index maxIterations () const
GMRES< _MatrixType, _Preconditioner > & setMaxIterations (Index maxIters)
Index iterations () const
RealScalar error () const
const SolveWithGuess< GMRES< _MatrixType, _Preconditioner >, Rhs, Guess > solveWithGuess (const MatrixBase< Rhs > &b, const Guess &x0) const
ComputationInfo info () const
void _solve_impl (const Rhs &b, SparseMatrixBase< DestDerived > &aDest) const
Public Member Functions inherited from Eigen::SparseSolverBase< GMRES< _MatrixType, _Preconditioner > >
SparseSolverBase ()
~SparseSolverBase ()
GMRES< _MatrixType, _Preconditioner > & derived ()
const GMRES< _MatrixType, _Preconditioner > & derived () const
const Solve< GMRES< _MatrixType, _Preconditioner >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< GMRES< _MatrixType, _Preconditioner >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Additional Inherited Members
Protected Types inherited from Eigen::IterativeSolverBase< GMRES< _MatrixType, _Preconditioner > >
typedef SparseSolverBase< GMRES< _MatrixType, _Preconditioner > > Base
typedef internal::generic_matrix_wrapper< MatrixType > MatrixWrapper
typedef MatrixWrapper::ActualMatrixType ActualMatrixType
Protected Member Functions inherited from Eigen::IterativeSolverBase< GMRES< _MatrixType, _Preconditioner > >
void init ()
const ActualMatrixType & matrix () const
void grab (const InputType &A)
Protected Attributes inherited from Eigen::IterativeSolverBase< GMRES< _MatrixType, _Preconditioner > >
MatrixWrapper m_matrixWrapper
Preconditioner m_preconditioner
Index m_maxIterations
RealScalar m_tolerance
RealScalar m_error
Index m_iterations
ComputationInfo m_info
bool m_analysisIsOk
bool m_factorizationIsOk
Protected Attributes inherited from Eigen::SparseSolverBase< GMRES< _MatrixType, _Preconditioner > >
bool m_isInitialized
Detailed Description
template<typename _MatrixType, typename _Preconditioner>
class Eigen::GMRES< _MatrixType, _Preconditioner >
A GMRES solver for sparse square problems.
This class allows to solve for A.x = b sparse linear problems using a generalized minimal residual method. The vectors x and b can be either dense or sparse.
Template Parameters
_MatrixType the type of the sparse matrix A, can be a dense or a sparse matrix.
_Preconditioner the type of the preconditioner. Default is DiagonalPreconditioner
The maximal number of iterations and tolerance value can be controlled via the setMaxIterations() and setTolerance() methods. The defaults are the size of the problem for the maximal number of iterations and NumTraits<Scalar>::epsilon() for the tolerance.
This class can be used as the direct solver classes. Here is a typical usage example:
int n = 10000;
VectorXd x(n), b(n);
SparseMatrix<double> A(n,n);
// fill A and b
GMRES<SparseMatrix<double> > solver(A);
x = solver.solve(b);
std::cout << "#iterations:     " << solver.iterations() << std::endl;
std::cout << "estimated error: " << solver.error()      << std::endl;
// update b, and solve again
x = solver.solve(b);
By default the iterations start with x=0 as an initial guess of the solution. One can control the start using the solveWithGuess() method.
GMRES can also be used in a matrix-free context, see the following example .
See also
class SimplicialCholesky, DiagonalPreconditioner, IdentityPreconditioner
Definition at line 212 of file GMRES.h.
Member Typedef Documentation
MatrixType
template<typename _MatrixType, typename _Preconditioner> typedef _MatrixType Eigen::GMRES< _MatrixType, _Preconditioner >::MatrixType
Definition at line 274 of file GMRES.h.
Preconditioner
template<typename _MatrixType, typename _Preconditioner> typedef _Preconditioner Eigen::GMRES< _MatrixType, _Preconditioner >::Preconditioner
Definition at line 277 of file GMRES.h.
RealScalar
template<typename _MatrixType, typename _Preconditioner> typedef MatrixType::RealScalar Eigen::GMRES< _MatrixType, _Preconditioner >::RealScalar
Definition at line 276 of file GMRES.h.
Scalar
template<typename _MatrixType, typename _Preconditioner> typedef MatrixType::Scalar Eigen::GMRES< _MatrixType, _Preconditioner >::Scalar
Definition at line 275 of file GMRES.h.
Constructor & Destructor Documentation
GMRES() [1/2]
template<typename _MatrixType, typename _Preconditioner> Eigen::GMRES< _MatrixType, _Preconditioner >::GMRES () inline
Default constructor.
Definition at line 282 of file GMRES.h.
GMRES() [2/2]
template<typename _MatrixType, typename _Preconditioner> template<typename MatrixDerived > Eigen::GMRES< _MatrixType, _Preconditioner >::GMRES (const EigenBase< MatrixDerived > & A) inline explicit
Initialize the solver with matrix A for further Ax=b solving.
This constructor is a shortcut for the default constructor followed by a call to compute().
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
Definition at line 295 of file GMRES.h.
~GMRES()
template<typename _MatrixType, typename _Preconditioner> Eigen::GMRES< _MatrixType, _Preconditioner >::~GMRES () inline
Definition at line 297 of file GMRES.h.
Member Function Documentation
_solve_impl()
template<typename _MatrixType, typename _Preconditioner> template<typename Rhs , typename Dest > void Eigen::GMRES< _MatrixType, _Preconditioner >::_solve_impl (const Rhs & b, MatrixBase< Dest > & x) const inline
Definition at line 330 of file GMRES.h.
References b, and Eigen::MatrixBase< Derived >::squaredNorm().
_solve_with_guess_impl()
template<typename _MatrixType, typename _Preconditioner> template<typename Rhs , typename Dest > void Eigen::GMRES< _MatrixType, _Preconditioner >::_solve_with_guess_impl (const Rhs & b, Dest & x) const inline
Definition at line 310 of file GMRES.h.
References Eigen::internal::gmres(), j, matrix(), Eigen::NoConvergence, Eigen::NumericalIssue, and Eigen::Success.
get_restart()
template<typename _MatrixType, typename _Preconditioner> Index Eigen::GMRES< _MatrixType, _Preconditioner >::get_restart () inline
Get the number of iterations after that a restart is performed.
Definition at line 301 of file GMRES.h.
set_restart()
template<typename _MatrixType, typename _Preconditioner> void Eigen::GMRES< _MatrixType, _Preconditioner >::set_restart (const Index restart) inline
Set the number of iterations after that a restart is performed.
Parameters
restart number of iterations for a restarti, default is 30.
Definition at line 306 of file GMRES.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/IterativeSolvers/GMRES.h