pairinteraction: BtlConfig Class Reference
BtlConfig Class Reference
#include <btl.hh>
Public Member Functions
BtlConfig ()
Static Public Member Functions
static BTL_DONT_INLINE bool skipAction (const std::string &_name)
Data Fields
bool overwriteResults
bool checkResults
bool realclock
int tries
Static Public Attributes
static BtlConfig Instance
Protected Attributes
std::vector< BtlString > m_selectedActionNames
Detailed Description
Definition at line 163 of file btl.hh.
Constructor & Destructor Documentation
BtlConfig()
BtlConfig::BtlConfig () inline
Definition at line 166 of file btl.hh.
References BtlString::beginsWith(), BTL_DISABLE_SSE_EXCEPTIONS, BtlString::BtlString(), and i.
Member Function Documentation
skipAction()
static BTL_DONT_INLINE bool BtlConfig::skipAction (const std::string & _name) inline static
Definition at line 216 of file btl.hh.
References BtlString::contains(), and i.
Referenced by bench(), and bench_static().
Field Documentation
checkResults
bool BtlConfig::checkResults
Definition at line 231 of file btl.hh.
Instance
BtlConfig BtlConfig::Instance static
Definition at line 229 of file btl.hh.
Referenced by bench(), Portable_Perf_Analyzer< Action >::eval_mflops(), and Portable_Timer::Portable_Timer().
m_selectedActionNames
std::vector<BtlString> BtlConfig::m_selectedActionNames protected
Definition at line 236 of file btl.hh.
overwriteResults
bool BtlConfig::overwriteResults
Definition at line 230 of file btl.hh.
realclock
bool BtlConfig::realclock
Definition at line 232 of file btl.hh.
Referenced by Portable_Timer::Portable_Timer().
tries
int BtlConfig::tries
Definition at line 233 of file btl.hh.
Referenced by Portable_Perf_Analyzer< Action >::eval_mflops().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/btl.hh