pairinteraction: STL_Timer Class Reference
STL_Timer Class Reference
#include <STL_timer.hh>
Public Member Functions
STL_Timer ()
void start (unsigned int r)
void start_baseline (unsigned int r)
bool check ()
double get_time (void)
Detailed Description
Definition at line 30 of file STL_timer.hh.
Constructor & Destructor Documentation
STL_Timer()
STL_Timer::STL_Timer () inline
Definition at line 32 of file STL_timer.hh.
Member Function Documentation
check()
bool STL_Timer::check () inline
Definition at line 48 of file STL_timer.hh.
Referenced by STL_Perf_Analyzer< ACTION >::eval_mflops().
get_time()
double STL_Timer::get_time (void) inline
Definition at line 60 of file STL_timer.hh.
Referenced by STL_Perf_Analyzer< ACTION >::eval_mflops().
start()
void STL_Timer::start (unsigned int r) inline
Definition at line 34 of file STL_timer.hh.
Referenced by STL_Perf_Analyzer< ACTION >::eval_mflops().
start_baseline()
void STL_Timer::start_baseline (unsigned int r) inline
Definition at line 42 of file STL_timer.hh.
Referenced by STL_Perf_Analyzer< ACTION >::eval_mflops().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/timers/STL_timer.hh