pairinteraction: Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs, ConjRhs = _ConjRhs, Vectorizable, RealPacketSize = Vectorizable ? packet_traits<RealScalar>::size : 1,
ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1, LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1, RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1, nr = 4,
mr = ResPacketSize, LhsProgress = ResPacketSize, RhsProgress = 1
}
typedef std::complex< RealScalar > Scalar
typedef std::complex< RealScalar > LhsScalar
typedef std::complex< RealScalar > RhsScalar
typedef std::complex< RealScalar > ResScalar
typedef packet_traits< RealScalar >::type RealPacket
typedef packet_traits< Scalar >::type ScalarPacket
typedef DoublePacket< RealPacket > DoublePacketType
typedef conditional< Vectorizable, RealPacket, Scalar >::type LhsPacket
typedef conditional< Vectorizable, DoublePacketType, Scalar >::type RhsPacket
typedef conditional< Vectorizable, ScalarPacket, Scalar >::type ResPacket
typedef conditional< Vectorizable, DoublePacketType, Scalar >::type AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (Scalar &p)
EIGEN_STRONG_INLINE void initAcc (DoublePacketType &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, DoublePacketType &b0, DoublePacketType &b1)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsScalar &b0, RhsScalar &b1)
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, DoublePacketType &c, RhsPacket &) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, ResPacket &c, RhsPacket &) const
EIGEN_STRONG_INLINE void acc (const Scalar &c, const Scalar &alpha, Scalar &r) const
EIGEN_STRONG_INLINE void acc (const DoublePacketType &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > cj
Detailed Description
template<typename RealScalar, bool _ConjLhs, bool _ConjRhs>
class Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >
Definition at line 599 of file GeneralBlockPanelKernel.h.
Member Typedef Documentation
AccPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacketType,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::AccPacket
Definition at line 632 of file GeneralBlockPanelKernel.h.
DoublePacketType
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef DoublePacket<RealPacket> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::DoublePacketType
Definition at line 627 of file GeneralBlockPanelKernel.h.
LhsPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,RealPacket, Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsPacket
Definition at line 629 of file GeneralBlockPanelKernel.h.
LhsScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsScalar
Definition at line 603 of file GeneralBlockPanelKernel.h.
RealPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<RealScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RealPacket
Definition at line 625 of file GeneralBlockPanelKernel.h.
ResPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,ScalarPacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResPacket
Definition at line 631 of file GeneralBlockPanelKernel.h.
ResScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResScalar
Definition at line 605 of file GeneralBlockPanelKernel.h.
RhsPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacketType,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsPacket
Definition at line 630 of file GeneralBlockPanelKernel.h.
RhsScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsScalar
Definition at line 604 of file GeneralBlockPanelKernel.h.
Scalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::Scalar
Definition at line 602 of file GeneralBlockPanelKernel.h.
ScalarPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ScalarPacket
Definition at line 626 of file GeneralBlockPanelKernel.h.
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
RealPacketSize
ResPacketSize
LhsPacketSize
RhsPacketSize
nr
mr
LhsProgress
RhsProgress
Definition at line 607 of file GeneralBlockPanelKernel.h.
Member Function Documentation
acc() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const Scalar & c, const Scalar & alpha, Scalar & r) const inline
Definition at line 712 of file GeneralBlockPanelKernel.h.
References c.
acc() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const DoublePacketType & c, const ResPacket & alpha, ResPacket & r) const inline
Definition at line 714 of file GeneralBlockPanelKernel.h.
References Eigen::internal::DoublePacket< Packet >::first, Eigen::internal::padd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pmadd(), Eigen::internal::psub(), and Eigen::internal::DoublePacket< Packet >::second.
broadcastRhs() [1/3]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
Definition at line 665 of file GeneralBlockPanelKernel.h.
broadcastRhs() [2/3]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, DoublePacketType & b0, DoublePacketType & b1) inline
Definition at line 675 of file GeneralBlockPanelKernel.h.
broadcastRhs() [3/3]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsScalar & b0, RhsScalar & b1) inline
Definition at line 683 of file GeneralBlockPanelKernel.h.
initAcc() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (Scalar & p) inline
Definition at line 634 of file GeneralBlockPanelKernel.h.
initAcc() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (DoublePacketType & p) inline
Definition at line 636 of file GeneralBlockPanelKernel.h.
References Eigen::internal::DoublePacket< Packet >::first, and Eigen::internal::DoublePacket< Packet >::second.
loadLhs()
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
Definition at line 691 of file GeneralBlockPanelKernel.h.
loadLhsUnaligned()
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
Definition at line 696 of file GeneralBlockPanelKernel.h.
loadRhs() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, ResPacket & dest) const inline
Definition at line 643 of file GeneralBlockPanelKernel.h.
loadRhs() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, DoublePacketType & dest) const inline
Definition at line 649 of file GeneralBlockPanelKernel.h.
References Eigen::internal::DoublePacket< Packet >::first, Eigen::imag(), Eigen::real(), and Eigen::internal::DoublePacket< Packet >::second.
loadRhsQuad() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, ResPacket & dest) const inline
Definition at line 655 of file GeneralBlockPanelKernel.h.
loadRhsQuad() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, DoublePacketType & dest) const inline
Definition at line 659 of file GeneralBlockPanelKernel.h.
References eigen_internal_assert.
madd() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, DoublePacketType & c, RhsPacket &) const inline
Definition at line 701 of file GeneralBlockPanelKernel.h.
References Eigen::internal::DoublePacket< Packet >::first, Eigen::internal::padd(), Eigen::internal::pmul(), and Eigen::internal::DoublePacket< Packet >::second.
madd() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, ResPacket & c, RhsPacket &) const inline
Definition at line 707 of file GeneralBlockPanelKernel.h.
Field Documentation
cj
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> conj_helper<LhsScalar,RhsScalar,ConjLhs,ConjRhs> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::cj protected
Definition at line 743 of file GeneralBlockPanelKernel.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h