pairinteraction: Eigen::SkylineMatrix< _Scalar, _Options > Class Template Reference
Eigen::SkylineMatrix< _Scalar, _Options > Class Template Reference
The main skyline matrix class.
#include <SkylineMatrix.h>
Data Structures
class InnerLowerIterator
class InnerUpperIterator
Public Member Functions
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
Index upperNonZeros () const
Index lowerNonZeros () const
Index upperNonZeros (Index j) const
Index lowerNonZeros (Index j) const
const Scalar * _diagPtr () const
Scalar * _diagPtr ()
const Scalar * _upperPtr () const
Scalar * _upperPtr ()
const Scalar * _lowerPtr () const
Scalar * _lowerPtr ()
const Index * _upperProfilePtr () const
Index * _upperProfilePtr ()
const Index * _lowerProfilePtr () const
Index * _lowerProfilePtr ()
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Scalar coeffDiag (Index idx) const
Scalar coeffLower (Index row, Index col) const
Scalar coeffUpper (Index row, Index col) const
Scalar & coeffRefDiag (Index idx)
Scalar & coeffRefLower (Index row, Index col)
bool coeffExistLower (Index row, Index col)
Scalar & coeffRefUpper (Index row, Index col)
bool coeffExistUpper (Index row, Index col)
void setZero ()
Index nonZeros () const
void reserve (Index reserveSize, Index reserveUpperSize, Index reserveLowerSize)
EIGEN_DONT_INLINE Scalar & insert (Index row, Index col)
void finalize ()
void squeeze ()
void prune (Scalar reference, RealScalar epsilon=dummy_precision< RealScalar >())
void resize (size_t rows, size_t cols)
void resizeNonZeros (Index size)
SkylineMatrix ()
SkylineMatrix (size_t rows, size_t cols)
template<typename OtherDerived >
SkylineMatrix (const SkylineMatrixBase< OtherDerived > &other)
SkylineMatrix (const SkylineMatrix &other)
void swap (SkylineMatrix &other)
SkylineMatrix & operator= (const SkylineMatrix &other)
template<typename OtherDerived >
SkylineMatrix & operator= (const SkylineMatrixBase< OtherDerived > &other)
~SkylineMatrix ()
Scalar sum () const
Public Member Functions inherited from Eigen::SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >
const SkylineMatrix< _Scalar, _Options > & derived () const
SkylineMatrix< _Scalar, _Options > & derived ()
SkylineMatrix< _Scalar, _Options > & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
Index nonZeros () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
SkylineMatrix< _Scalar, _Options > & markAsRValue ()
SkylineMatrixBase ()
SkylineMatrix< _Scalar, _Options > & operator= (const SkylineMatrix< _Scalar, _Options > &other)
SkylineMatrix< _Scalar, _Options > & operator= (const SkylineMatrixBase< OtherDerived > &other)
SkylineMatrix< _Scalar, _Options > & operator= (const SkylineProduct< Lhs, Rhs, SkylineTimeSkylineProduct > &product)
void assignGeneric (const OtherDerived &other)
const SkylineProductReturnType< SkylineMatrix< _Scalar, _Options >, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SkylineProductReturnType< SkylineMatrix< _Scalar, _Options >, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
void evalTo (MatrixBase< DenseDerived > &dst) const
Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > toDense () const
EIGEN_STRONG_INLINE const internal::eval< SkylineMatrix< _Scalar, _Options >, IsSkyline >::type eval () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Data Fields
Index * m_colStartIndex
Index * m_rowStartIndex
SkylineStorage< Scalar > m_data
Protected Types
typedef SkylineMatrix< Scalar,(Flags &~RowMajorBit)|(IsRowMajor ? RowMajorBit :0) > TransposedSkylineMatrix
Protected Attributes
Index m_outerSize
Index m_innerSize
Protected Attributes inherited from Eigen::SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >
bool m_isRValue
Friends
std::ostream & operator<< (std::ostream &s, const SkylineMatrix &m)
Additional Inherited Members
Public Types inherited from Eigen::SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >
enum
typedef internal::traits< SkylineMatrix< _Scalar, _Options > >::Scalar Scalar
typedef internal::traits< SkylineMatrix< _Scalar, _Options > >::StorageKind StorageKind
typedef internal::index< StorageKind >::type Index
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime) > SquareMatrixType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Detailed Description
template<typename _Scalar, int _Options>
class Eigen::SkylineMatrix< _Scalar, _Options >
The main skyline matrix class.
This class implements a skyline matrix using the very uncommon storage scheme.
Parameters
_Scalar the scalar type, i.e. the type of the coefficients
_Options Union of bit flags controlling the storage scheme. Currently the only possibility is RowMajor. The default is 0 which means column-major.
Definition at line 51 of file SkylineMatrix.h.
Member Typedef Documentation
TransposedSkylineMatrix
template<typename _Scalar , int _Options> typedef SkylineMatrix<Scalar, (Flags&~RowMajorBit) | (IsRowMajor ? RowMajorBit : 0) > Eigen::SkylineMatrix< _Scalar, _Options >::TransposedSkylineMatrix protected
Definition at line 62 of file SkylineMatrix.h.
Constructor & Destructor Documentation
SkylineMatrix() [1/4]
template<typename _Scalar , int _Options> Eigen::SkylineMatrix< _Scalar, _Options >::SkylineMatrix () inline
Definition at line 630 of file SkylineMatrix.h.
References resize().
SkylineMatrix() [2/4]
template<typename _Scalar , int _Options> Eigen::SkylineMatrix< _Scalar, _Options >::SkylineMatrix (size_t rows, size_t cols) inline
Definition at line 635 of file SkylineMatrix.h.
References resize().
SkylineMatrix() [3/4]
template<typename _Scalar , int _Options> template<typename OtherDerived > Eigen::SkylineMatrix< _Scalar, _Options >::SkylineMatrix (const SkylineMatrixBase< OtherDerived > & other) inline
Definition at line 641 of file SkylineMatrix.h.
References Eigen::SkylineMatrixBase< Derived >::derived().
SkylineMatrix() [4/4]
template<typename _Scalar , int _Options> Eigen::SkylineMatrix< _Scalar, _Options >::SkylineMatrix (const SkylineMatrix< _Scalar, _Options > & other) inline
Definition at line 646 of file SkylineMatrix.h.
References Eigen::SkylineMatrixBase< Derived >::derived().
~SkylineMatrix()
template<typename _Scalar , int _Options> Eigen::SkylineMatrix< _Scalar, _Options >::~SkylineMatrix () inline
Destructor
Definition at line 725 of file SkylineMatrix.h.
References mpfr::sum().
Member Function Documentation
_diagPtr() [1/2]
template<typename _Scalar , int _Options> const Scalar* Eigen::SkylineMatrix< _Scalar, _Options >::_diagPtr () const inline
Definition at line 106 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::diag().
_diagPtr() [2/2]
template<typename _Scalar , int _Options> Scalar* Eigen::SkylineMatrix< _Scalar, _Options >::_diagPtr () inline
Definition at line 110 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::diag().
_lowerProfilePtr() [1/2]
template<typename _Scalar , int _Options> const Index* Eigen::SkylineMatrix< _Scalar, _Options >::_lowerProfilePtr () const inline
Definition at line 138 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::lowerProfile().
_lowerProfilePtr() [2/2]
template<typename _Scalar , int _Options> Index* Eigen::SkylineMatrix< _Scalar, _Options >::_lowerProfilePtr () inline
Definition at line 142 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::lowerProfile().
_lowerPtr() [1/2]
template<typename _Scalar , int _Options> const Scalar* Eigen::SkylineMatrix< _Scalar, _Options >::_lowerPtr () const inline
Definition at line 122 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::lower().
_lowerPtr() [2/2]
template<typename _Scalar , int _Options> Scalar* Eigen::SkylineMatrix< _Scalar, _Options >::_lowerPtr () inline
Definition at line 126 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::lower().
_upperProfilePtr() [1/2]
template<typename _Scalar , int _Options> const Index* Eigen::SkylineMatrix< _Scalar, _Options >::_upperProfilePtr () const inline
Definition at line 130 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::upperProfile().
_upperProfilePtr() [2/2]
template<typename _Scalar , int _Options> Index* Eigen::SkylineMatrix< _Scalar, _Options >::_upperProfilePtr () inline
Definition at line 134 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::upperProfile().
_upperPtr() [1/2]
template<typename _Scalar , int _Options> const Scalar* Eigen::SkylineMatrix< _Scalar, _Options >::_upperPtr () const inline
Definition at line 114 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::upper().
_upperPtr() [2/2]
template<typename _Scalar , int _Options> Scalar* Eigen::SkylineMatrix< _Scalar, _Options >::_upperPtr () inline
Definition at line 118 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::upper().
coeff()
template<typename _Scalar , int _Options> Scalar Eigen::SkylineMatrix< _Scalar, _Options >::coeff (Index row, Index col) const inline
Definition at line 146 of file SkylineMatrix.h.
References col(), Eigen::SkylineStorage< Scalar >::diag(), eigen_assert, Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), row(), Eigen::SkylineStorage< Scalar >::upper(), and Eigen::SkylineStorage< Scalar >::upperProfile().
coeffDiag()
template<typename _Scalar , int _Options> Scalar Eigen::SkylineMatrix< _Scalar, _Options >::coeffDiag (Index idx) const inline
Definition at line 234 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::diag(), and eigen_assert.
coeffExistLower()
template<typename _Scalar , int _Options> bool Eigen::SkylineMatrix< _Scalar, _Options >::coeffExistLower (Index row, Index col) inline
Definition at line 312 of file SkylineMatrix.h.
References col(), eigen_assert, Eigen::SkylineStorage< Scalar >::lowerProfile(), and row().
coeffExistUpper()
template<typename _Scalar , int _Options> bool Eigen::SkylineMatrix< _Scalar, _Options >::coeffExistUpper (Index row, Index col) inline
Definition at line 348 of file SkylineMatrix.h.
References col(), eigen_assert, row(), and Eigen::SkylineStorage< Scalar >::upperProfile().
coeffLower()
template<typename _Scalar , int _Options> Scalar Eigen::SkylineMatrix< _Scalar, _Options >::coeffLower (Index row, Index col) const inline
Definition at line 240 of file SkylineMatrix.h.
References col(), eigen_assert, Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), and row().
coeffRef()
template<typename _Scalar , int _Options> Scalar& Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef (Index row, Index col) inline
Definition at line 195 of file SkylineMatrix.h.
References col(), Eigen::SkylineStorage< Scalar >::diag(), eigen_assert, Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), row(), Eigen::SkylineStorage< Scalar >::upper(), and Eigen::SkylineStorage< Scalar >::upperProfile().
coeffRefDiag()
template<typename _Scalar , int _Options> Scalar& Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefDiag (Index idx) inline
Definition at line 287 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::diag(), and eigen_assert.
coeffRefLower()
template<typename _Scalar , int _Options> Scalar& Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefLower (Index row, Index col) inline
Definition at line 293 of file SkylineMatrix.h.
References col(), eigen_assert, Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), and row().
coeffRefUpper()
template<typename _Scalar , int _Options> Scalar& Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefUpper (Index row, Index col) inline
Definition at line 329 of file SkylineMatrix.h.
References col(), eigen_assert, row(), Eigen::SkylineStorage< Scalar >::upper(), and Eigen::SkylineStorage< Scalar >::upperProfile().
coeffUpper()
template<typename _Scalar , int _Options> Scalar Eigen::SkylineMatrix< _Scalar, _Options >::coeffUpper (Index row, Index col) const inline
Definition at line 264 of file SkylineMatrix.h.
References col(), eigen_assert, row(), Eigen::SkylineStorage< Scalar >::upper(), and Eigen::SkylineStorage< Scalar >::upperProfile().
cols()
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::cols (void) const inline
Definition at line 78 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::operator=().
finalize()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::finalize () inline
Must be called after inserting a set of non zero entries.
Definition at line 534 of file SkylineMatrix.h.
References cols, Eigen::SkylineStorage< Scalar >::resize(), and rows.
innerSize()
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::innerSize () const inline
Definition at line 82 of file SkylineMatrix.h.
insert()
template<typename _Scalar , int _Options> EIGEN_DONT_INLINE Scalar& Eigen::SkylineMatrix< _Scalar, _Options >::insert (Index row, Index col) inline
Returns
a reference to a novel non zero coefficient with coordinates row x col.
Warning
This function can be extremely slow if the non zero coefficients are not inserted in a coherent order.
After an insertion session, you should call the finalize() function.
Definition at line 400 of file SkylineMatrix.h.
References col(), cols, Eigen::SkylineStorage< Scalar >::diag(), eigen_assert, Eigen::SkylineStorage< Scalar >::lower(), Eigen::SkylineStorage< Scalar >::lowerProfile(), row(), rows, Eigen::SkylineStorage< Scalar >::upper(), and Eigen::SkylineStorage< Scalar >::upperProfile().
lowerNonZeros() [1/2]
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::lowerNonZeros () const inline
Definition at line 94 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::lowerSize().
lowerNonZeros() [2/2]
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::lowerNonZeros (Index j) const inline
Definition at line 102 of file SkylineMatrix.h.
References j.
nonZeros()
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::nonZeros () const inline
Returns
the number of non zero coefficients
Definition at line 383 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::diagSize(), Eigen::SkylineStorage< Scalar >::lowerSize(), and Eigen::SkylineStorage< Scalar >::upperSize().
operator=() [1/2]
template<typename _Scalar , int _Options> SkylineMatrix& Eigen::SkylineMatrix< _Scalar, _Options >::operator= (const SkylineMatrix< _Scalar, _Options > & other) inline
Definition at line 660 of file SkylineMatrix.h.
References Eigen::SkylineMatrix< _Scalar, _Options >::cols(), Eigen::SkylineMatrixBase< Derived >::const_cast_derived(), Eigen::SkylineMatrixBase< Derived >::isRValue(), Eigen::SkylineMatrix< _Scalar, _Options >::m_colStartIndex, Eigen::SkylineMatrix< _Scalar, _Options >::m_data, Eigen::SkylineMatrix< _Scalar, _Options >::m_rowStartIndex, resize(), Eigen::SkylineMatrix< _Scalar, _Options >::rows(), and Eigen::internal::swap().
operator=() [2/2]
template<typename _Scalar , int _Options> template<typename OtherDerived > SkylineMatrix& Eigen::SkylineMatrix< _Scalar, _Options >::operator= (const SkylineMatrixBase< OtherDerived > & other) inline
Definition at line 674 of file SkylineMatrix.h.
References Eigen::SkylineMatrixBase< Derived >::derived(), Eigen::SkylineMatrixBase< Derived >::operator=(), and Eigen::RowMajorBit.
outerSize()
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::outerSize () const inline
Definition at line 86 of file SkylineMatrix.h.
prune()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::prune (Scalar reference, RealScalar epsilon = dummy_precision<RealScalar > ()) inline
Definition at line 582 of file SkylineMatrix.h.
reserve()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::reserve (Index reserveSize, Index reserveUpperSize, Index reserveLowerSize) inline
Preallocates reserveSize non zeros
Definition at line 388 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::reserve().
resize()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::resize (size_t rows, size_t cols) inline
Resizes the matrix to a rows x cols matrix and initializes it to zero
See also
resizeNonZeros(Index), reserve(), setZero()
Definition at line 589 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::clear(), cols, eigen_assert, Eigen::SkylineStorage< Scalar >::reset(), Eigen::SkylineStorage< Scalar >::resize(), and rows.
resizeNonZeros()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::resizeNonZeros (Index size) inline
Definition at line 626 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::resize().
rows()
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::rows (void) const inline
Definition at line 74 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::operator=().
setZero()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::setZero () inline
Removes all non zeros
Definition at line 376 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::clear().
squeeze()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::squeeze () inline
Definition at line 577 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::squeeze().
sum()
template<typename _Scalar , int _Options> Scalar Eigen::SkylineMatrix< _Scalar, _Options >::sum () const
Overloaded for performance
swap()
template<typename _Scalar , int _Options> void Eigen::SkylineMatrix< _Scalar, _Options >::swap (SkylineMatrix< _Scalar, _Options > & other) inline
Definition at line 651 of file SkylineMatrix.h.
References Eigen::SkylineMatrix< _Scalar, _Options >::m_colStartIndex, Eigen::SkylineMatrix< _Scalar, _Options >::m_data, Eigen::SkylineMatrix< _Scalar, _Options >::m_innerSize, Eigen::SkylineMatrix< _Scalar, _Options >::m_outerSize, Eigen::SkylineMatrix< _Scalar, _Options >::m_rowStartIndex, Eigen::SkylineStorage< Scalar >::swap(), and std::swap().
upperNonZeros() [1/2]
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::upperNonZeros () const inline
Definition at line 90 of file SkylineMatrix.h.
References Eigen::SkylineStorage< Scalar >::upperSize().
upperNonZeros() [2/2]
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::upperNonZeros (Index j) const inline
Definition at line 98 of file SkylineMatrix.h.
References j.
Friends And Related Function Documentation
operator<<
template<typename _Scalar , int _Options> std::ostream& operator<< (std::ostream & s, const SkylineMatrix< _Scalar, _Options > & m) friend
Definition at line 685 of file SkylineMatrix.h.
Field Documentation
m_colStartIndex
template<typename _Scalar , int _Options> Index* Eigen::SkylineMatrix< _Scalar, _Options >::m_colStartIndex
Definition at line 68 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::operator=(), and Eigen::SkylineMatrix< _Scalar, _Options >::swap().
m_data
template<typename _Scalar , int _Options> SkylineStorage<Scalar> Eigen::SkylineMatrix< _Scalar, _Options >::m_data
Definition at line 70 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::operator=(), and Eigen::SkylineMatrix< _Scalar, _Options >::swap().
m_innerSize
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::m_innerSize protected
Definition at line 65 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::swap().
m_outerSize
template<typename _Scalar , int _Options> Index Eigen::SkylineMatrix< _Scalar, _Options >::m_outerSize protected
Definition at line 64 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::swap().
m_rowStartIndex
template<typename _Scalar , int _Options> Index* Eigen::SkylineMatrix< _Scalar, _Options >::m_rowStartIndex
Definition at line 69 of file SkylineMatrix.h.
Referenced by Eigen::SkylineMatrix< _Scalar, _Options >::operator=(), and Eigen::SkylineMatrix< _Scalar, _Options >::swap().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/Skyline/SkylineMatrix.h