pairinteraction: std::numeric_limits< mpfr::mpreal > Class Template Reference
std::numeric_limits< mpfr::mpreal > Class Template Reference
#include <mpreal.h>
Static Public Member Functions
static mpfr::mpreal() min (mp_prec_t precision=mpfr::mpreal::get_default_prec())
static mpfr::mpreal() max (mp_prec_t precision=mpfr::mpreal::get_default_prec())
static mpfr::mpreal lowest (mp_prec_t precision=mpfr::mpreal::get_default_prec())
static mpfr::mpreal epsilon (mp_prec_t precision=mpfr::mpreal::get_default_prec())
static mpfr::mpreal epsilon (const mpfr::mpreal &x)
static mpfr::mpreal round_error (mp_prec_t precision=mpfr::mpreal::get_default_prec())
static const mpfr::mpreal infinity ()
static const mpfr::mpreal quiet_NaN ()
static const mpfr::mpreal signaling_NaN ()
static const mpfr::mpreal denorm_min ()
static float_round_style round_style ()
static int digits ()
static int digits (const mpfr::mpreal &x)
static int digits10 (mp_prec_t precision=mpfr::mpreal::get_default_prec())
static int digits10 (const mpfr::mpreal &x)
static int max_digits10 (mp_prec_t precision=mpfr::mpreal::get_default_prec())
Static Public Attributes
static const bool is_specialized = true
static const bool is_signed = true
static const bool is_integer = false
static const bool is_exact = false
static const int radix = 2
static const bool has_infinity = true
static const bool has_quiet_NaN = true
static const bool has_signaling_NaN = true
static const bool is_iec559 = true
static const bool is_bounded = true
static const bool is_modulo = false
static const bool traps = true
static const bool tinyness_before = true
static const float_denorm_style has_denorm = denorm_absent
static const int min_exponent = MPFR_EMIN_DEFAULT
static const int max_exponent = MPFR_EMAX_DEFAULT
static MPREAL_PERMISSIVE_EXPR const int min_exponent10 = (int) (MPFR_EMIN_DEFAULT * 0.3010299956639811)
static MPREAL_PERMISSIVE_EXPR const int max_exponent10 = (int) (MPFR_EMAX_DEFAULT * 0.3010299956639811)
Detailed Description
template<>
class std::numeric_limits< mpfr::mpreal >
Definition at line 2992 of file mpreal.h.
Member Function Documentation
denorm_min()
static const mpfr::mpreal std::numeric_limits< mpfr::mpreal >::denorm_min () inline static
Definition at line 3034 of file mpreal.h.
References mpfr::min().
digits() [1/2]
static int std::numeric_limits< mpfr::mpreal >::digits () inline static
Definition at line 3064 of file mpreal.h.
References mpfr::mpreal::get_default_prec(), and int().
digits() [2/2]
static int std::numeric_limits< mpfr::mpreal >::digits (const mpfr::mpreal & x) inline static
Definition at line 3065 of file mpreal.h.
References mpfr::mpreal::getPrecision().
digits10() [1/2]
static int std::numeric_limits< mpfr::mpreal >::digits10 (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3067 of file mpreal.h.
References mpfr::bits2digits().
digits10() [2/2]
static int std::numeric_limits< mpfr::mpreal >::digits10 (const mpfr::mpreal & x) inline static
Definition at line 3072 of file mpreal.h.
References mpfr::bits2digits(), and mpfr::mpreal::getPrecision().
epsilon() [1/2]
static mpfr::mpreal std::numeric_limits< mpfr::mpreal >::epsilon (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3018 of file mpreal.h.
References mpfr::machine_epsilon().
epsilon() [2/2]
static mpfr::mpreal std::numeric_limits< mpfr::mpreal >::epsilon (const mpfr::mpreal & x) inline static
Definition at line 3021 of file mpreal.h.
References mpfr::machine_epsilon().
infinity()
static const mpfr::mpreal std::numeric_limits< mpfr::mpreal >::infinity () inline static
Definition at line 3031 of file mpreal.h.
References mpfr::const_infinity().
lowest()
static mpfr::mpreal std::numeric_limits< mpfr::mpreal >::lowest (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3015 of file mpreal.h.
References mpfr::maxval().
max()
static mpfr::mpreal() std::numeric_limits< mpfr::mpreal >::max (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3014 of file mpreal.h.
References mpfr::maxval().
max_digits10()
static int std::numeric_limits< mpfr::mpreal >::max_digits10 (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3077 of file mpreal.h.
min()
static mpfr::mpreal() std::numeric_limits< mpfr::mpreal >::min (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3013 of file mpreal.h.
References mpfr::minval().
quiet_NaN()
static const mpfr::mpreal std::numeric_limits< mpfr::mpreal >::quiet_NaN () inline static
Definition at line 3032 of file mpreal.h.
References mpfr::mpreal::setNan().
round_error()
static mpfr::mpreal std::numeric_limits< mpfr::mpreal >::round_error (mp_prec_t precision = mpfr::mpreal::get_default_prec()) inline static
Definition at line 3023 of file mpreal.h.
References mpfr::mpreal::get_default_rnd().
round_style()
static float_round_style std::numeric_limits< mpfr::mpreal >::round_style () inline static
Definition at line 3050 of file mpreal.h.
References mpfr::mpreal::get_default_rnd().
signaling_NaN()
static const mpfr::mpreal std::numeric_limits< mpfr::mpreal >::signaling_NaN () inline static
Definition at line 3033 of file mpreal.h.
References mpfr::mpreal::setNan().
Field Documentation
has_denorm
const float_denorm_style std::numeric_limits< mpfr::mpreal >::has_denorm = denorm_absent static
Definition at line 3011 of file mpreal.h.
has_infinity
const bool std::numeric_limits< mpfr::mpreal >::has_infinity = true static
Definition at line 3001 of file mpreal.h.
has_quiet_NaN
const bool std::numeric_limits< mpfr::mpreal >::has_quiet_NaN = true static
Definition at line 3002 of file mpreal.h.
has_signaling_NaN
const bool std::numeric_limits< mpfr::mpreal >::has_signaling_NaN = true static
Definition at line 3003 of file mpreal.h.
is_bounded
const bool std::numeric_limits< mpfr::mpreal >::is_bounded = true static
Definition at line 3006 of file mpreal.h.
is_exact
const bool std::numeric_limits< mpfr::mpreal >::is_exact = false static
Definition at line 2998 of file mpreal.h.
is_iec559
const bool std::numeric_limits< mpfr::mpreal >::is_iec559 = true static
Definition at line 3005 of file mpreal.h.
is_integer
const bool std::numeric_limits< mpfr::mpreal >::is_integer = false static
Definition at line 2997 of file mpreal.h.
is_modulo
const bool std::numeric_limits< mpfr::mpreal >::is_modulo = false static
Definition at line 3007 of file mpreal.h.
is_signed
const bool std::numeric_limits< mpfr::mpreal >::is_signed = true static
Definition at line 2996 of file mpreal.h.
is_specialized
const bool std::numeric_limits< mpfr::mpreal >::is_specialized = true static
Definition at line 2995 of file mpreal.h.
max_exponent
const int std::numeric_limits< mpfr::mpreal >::max_exponent = MPFR_EMAX_DEFAULT static
Definition at line 3038 of file mpreal.h.
max_exponent10
MPREAL_PERMISSIVE_EXPR const int std::numeric_limits< mpfr::mpreal >::max_exponent10 = (int) (MPFR_EMAX_DEFAULT * 0.3010299956639811) static
Definition at line 3040 of file mpreal.h.
min_exponent
const int std::numeric_limits< mpfr::mpreal >::min_exponent = MPFR_EMIN_DEFAULT static
Definition at line 3037 of file mpreal.h.
min_exponent10
MPREAL_PERMISSIVE_EXPR const int std::numeric_limits< mpfr::mpreal >::min_exponent10 = (int) (MPFR_EMIN_DEFAULT * 0.3010299956639811) static
Definition at line 3039 of file mpreal.h.
radix
const int std::numeric_limits< mpfr::mpreal >::radix = 2 static
Definition at line 2999 of file mpreal.h.
tinyness_before
const bool std::numeric_limits< mpfr::mpreal >::tinyness_before = true static
Definition at line 3009 of file mpreal.h.
traps
const bool std::numeric_limits< mpfr::mpreal >::traps = true static
Definition at line 3008 of file mpreal.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/test/mpreal/mpreal.h