pairinteraction: Action_atv_product< Interface > Class Template Reference
Action_atv_product< Interface > Class Template Reference
#include <action_atv_product.hh>
Public Member Functions
Action_atv_product (int size)
Action_atv_product (const Action_atv_product &)
~Action_atv_product (void)
double nb_op_base (void)
void initialize (void)
BTL_DONT_INLINE void calculate (void)
void check_result (void)
Static Public Member Functions
static std::string name ()
Detailed Description
template<class Interface>
class Action_atv_product< Interface >
Definition at line 32 of file action_atv_product.hh.
Constructor & Destructor Documentation
Action_atv_product() [1/2]
template<class Interface > Action_atv_product< Interface >::Action_atv_product (int size) inline
Definition at line 36 of file action_atv_product.hh.
References MESSAGE, and X.
Action_atv_product() [2/2]
template<class Interface > Action_atv_product< Interface >::Action_atv_product (const Action_atv_product< Interface > &) inline
Definition at line 59 of file action_atv_product.hh.
References INFOS.
~Action_atv_product()
template<class Interface > Action_atv_product< Interface >::~Action_atv_product (void) inline
Definition at line 65 of file action_atv_product.hh.
References MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > BTL_DONT_INLINE void Action_atv_product< Interface >::calculate (void) inline
Definition at line 88 of file action_atv_product.hh.
References BTL_ASM_COMMENT, and X.
check_result()
template<class Interface > void Action_atv_product< Interface >::check_result (void) inline
Definition at line 94 of file action_atv_product.hh.
References STL_interface< real >::atv_product(), e(), INFOS, STL_interface< real >::norm_diff(), and X.
initialize()
template<class Interface > void Action_atv_product< Interface >::initialize (void) inline
Definition at line 82 of file action_atv_product.hh.
References X.
name()
template<class Interface > static std::string Action_atv_product< Interface >::name (void) inline static
Definition at line 78 of file action_atv_product.hh.
nb_op_base()
template<class Interface > double Action_atv_product< Interface >::nb_op_base (void) inline
Definition at line 80 of file action_atv_product.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_atv_product.hh