pairinteraction: Action_trisolve< Interface > Class Template Reference
Action_trisolve< Interface > Class Template Reference
#include <action_trisolve.hh>
Public Member Functions
Action_trisolve (int size)
Action_trisolve (const Action_trisolve &)
~Action_trisolve (void)
double nb_op_base (void)
void initialize (void)
void calculate (void)
void check_result ()
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_trisolve< Interface >
Definition at line 31 of file action_trisolve.hh.
Constructor & Destructor Documentation
Action_trisolve() [1/2]
template<class Interface > Action_trisolve< Interface >::Action_trisolve (int size) inline
Definition at line 37 of file action_trisolve.hh.
References i, j, L, MESSAGE, and X.
Action_trisolve() [2/2]
template<class Interface > Action_trisolve< Interface >::Action_trisolve (const Action_trisolve< Interface > &) inline
Definition at line 68 of file action_trisolve.hh.
References INFOS.
~Action_trisolve()
template<class Interface > Action_trisolve< Interface >::~Action_trisolve (void) inline
Definition at line 76 of file action_trisolve.hh.
References L, MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > void Action_trisolve< Interface >::calculate (void) inline
Definition at line 101 of file action_trisolve.hh.
References L, and X.
check_result()
template<class Interface > void Action_trisolve< Interface >::check_result () inline
Definition at line 105 of file action_trisolve.hh.
References e(), INFOS, L, STL_interface< real >::norm_diff(), STL_interface< real >::trisolve_lower(), and X.
initialize()
template<class Interface > void Action_trisolve< Interface >::initialize (void) inline
Definition at line 97 of file action_trisolve.hh.
name()
template<class Interface > static std::string Action_trisolve< Interface >::name (void) inline static
Definition at line 88 of file action_trisolve.hh.
nb_op_base()
template<class Interface > double Action_trisolve< Interface >::nb_op_base (void) inline
Definition at line 93 of file action_trisolve.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_trisolve.hh