pairinteraction: Eigen::internal::variable_if_dynamic< T, Value > Class Template Reference
Eigen::internal::variable_if_dynamic< T, Value > Class Template Reference
#include <XprHelper.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE variable_if_dynamic (T v)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void setValue (T)
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T value ()
Detailed Description
template<typename T, int Value>
class Eigen::internal::variable_if_dynamic< T, Value >
Definition at line 106 of file XprHelper.h.
Constructor & Destructor Documentation
variable_if_dynamic()
template<typename T, int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::variable_if_dynamic< T, Value >::variable_if_dynamic (T v) inline explicit
Definition at line 110 of file XprHelper.h.
Member Function Documentation
setValue()
template<typename T, int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::variable_if_dynamic< T, Value >::setValue (T) inline
Definition at line 112 of file XprHelper.h.
value()
template<typename T, int Value> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::variable_if_dynamic< T, Value >::value () inline static
Definition at line 111 of file XprHelper.h.
Referenced by Eigen::Stride< 0, Value >::inner(), Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=(), and Eigen::Stride< 0, Value >::outer().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/XprHelper.h