pairinteraction: Eigen::MatrixBase< Derived > Class Template Reference
Eigen::MatrixBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for all dense matrices, vectors, and expressions.
#include <MatrixBase.h>
Data Structures
struct CastXpr
struct ConstDiagonalIndexReturnType
struct ConstSelfAdjointViewReturnType
struct ConstTriangularViewReturnType
struct cross_product_return_type
struct DiagonalIndexReturnType
struct SelfAdjointViewReturnType
struct TriangularViewReturnType
Public Types
enum { HomogeneousReturnTypeDirection }
enum { SizeMinusOne = SizeAtCompileTime==Dynamic ? Dynamic : SizeAtCompileTime-1 }
typedef MatrixBase StorageBaseType
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::ConstTransposeReturnType ConstTransposeReturnType
typedef Base::RowXpr RowXpr
typedef Base::ColXpr ColXpr
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType >::type AdjointReturnType
typedef Matrix< std::complex< RealScalar >, internal::traits< Derived >::ColsAtCompileTime, 1, ColMajor > EigenvaluesReturnType
typedef CwiseNullaryOp< internal::scalar_identity_op< Scalar >, PlainObject > IdentityReturnType
typedef Block< const CwiseNullaryOp< internal::scalar_identity_op< Scalar >, SquareMatrixType >, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime > BasisReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived &>::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived &>::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived &>::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > CwiseInverseReturnType
typedef CwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const Derived, const ConstantReturnType > CwiseScalarEqualReturnType
typedef Diagonal< Derived > DiagonalReturnType
typedef internal::add_const< Diagonal< const Derived > >::type ConstDiagonalReturnType
typedef Diagonal< Derived, DynamicIndex > DiagonalDynamicIndexReturnType
typedef internal::add_const< Diagonal< const Derived, DynamicIndex > >::type ConstDiagonalDynamicIndexReturnType
typedef Homogeneous< Derived, HomogeneousReturnTypeDirection > HomogeneousReturnType
typedef Block< const Derived, internal::traits< Derived >::ColsAtCompileTime==1 ? SizeMinusOne :1, internal::traits< Derived >::ColsAtCompileTime==1 ? 1 :SizeMinusOne > ConstStartMinusOne
typedef internal::stem_function< Scalar >::type StemFunction
Public Types inherited from Eigen::DenseBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime, Flags = internal::traits<Derived>::Flags,
IsRowMajor = int(Flags) & RowMajorBit, InnerSizeAtCompileTime, InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret, OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef internal::conditional< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray >::type PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > SequentialLinSpacedReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< const Derived > >::type ConstTransposeReturnType
typedef internal::add_const_on_value_type< typename internal::eval< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Public Member Functions
EIGEN_DEVICE_FUNC Index diagonalSize () const
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
template<typename CustomBinaryOp , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const Derived, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const Derived, const OtherDerived > operator && (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const Derived, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (Derived, OtherDerived, product) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::equal_to< Scalar >, const Derived, const OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::not_equal_to< Scalar >, const Derived, const OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const Derived, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType cwiseEqual (const Scalar &s) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const MatrixBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< Derived, OtherDerived, LazyProduct > lazyProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Derived & operator*= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
void applyOnTheLeft (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
void applyOnTheRight (const EigenBase< OtherDerived > &other)
template<typename DiagonalDerived >
EIGEN_DEVICE_FUNC const Product< Derived, DiagonalDerived, LazyProduct > operator* (const DiagonalBase< DiagonalDerived > &diagonal) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC ScalarBinaryOpTraits< typename internal::traits< Derived >::Scalar, typename internal::traits< OtherDerived >::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC RealScalar squaredNorm () const
EIGEN_DEVICE_FUNC RealScalar norm () const
RealScalar stableNorm () const
RealScalar blueNorm () const
RealScalar hypotNorm () const
EIGEN_DEVICE_FUNC const PlainObject normalized () const
EIGEN_DEVICE_FUNC const PlainObject stableNormalized () const
EIGEN_DEVICE_FUNC void normalize ()
EIGEN_DEVICE_FUNC void stableNormalize ()
EIGEN_DEVICE_FUNC const AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC void adjointInPlace ()
EIGEN_DEVICE_FUNC DiagonalReturnType diagonal ()
EIGEN_DEVICE_FUNC ConstDiagonalReturnType diagonal () const
template<int Index>
EIGEN_DEVICE_FUNC DiagonalIndexReturnType< Index >::Type diagonal ()
template<int Index>
EIGEN_DEVICE_FUNC ConstDiagonalIndexReturnType< Index >::Type diagonal () const
EIGEN_DEVICE_FUNC DiagonalDynamicIndexReturnType diagonal (Index index)
EIGEN_DEVICE_FUNC ConstDiagonalDynamicIndexReturnType diagonal (Index index) const
template<unsigned int Mode>
EIGEN_DEVICE_FUNC TriangularViewReturnType< Mode >::Type triangularView ()
template<unsigned int Mode>
EIGEN_DEVICE_FUNC ConstTriangularViewReturnType< Mode >::Type triangularView () const
template<unsigned int UpLo>
EIGEN_DEVICE_FUNC SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<unsigned int UpLo>
EIGEN_DEVICE_FUNC ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
const SparseView< Derived > sparseView (const Scalar &m_reference=Scalar(0), const typename NumTraits< Scalar >::Real &m_epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const DiagonalWrapper< const Derived > asDiagonal () const
const PermutationWrapper< const Derived > asPermutation () const
EIGEN_DEVICE_FUNC Derived & setIdentity ()
EIGEN_DEVICE_FUNC Derived & setIdentity (Index rows, Index cols)
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
bool isIdentity (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isDiagonal (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUpperTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isLowerTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isOrthogonal (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUnitary (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool operator== (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool operator!= (const MatrixBase< OtherDerived > &other) const
NoAlias< Derived, Eigen::MatrixBase > noalias ()
const Derived & forceAlignedAccess () const
Derived & forceAlignedAccess ()
template<bool Enable>
const Derived & forceAlignedAccessIf () const
template<bool Enable>
Derived & forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar trace () const
template<int p>
EIGEN_DEVICE_FUNC RealScalar lpNorm () const
EIGEN_DEVICE_FUNC MatrixBase< Derived > & matrix ()
EIGEN_DEVICE_FUNC const MatrixBase< Derived > & matrix () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< Derived > array ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArrayWrapper< const Derived > array () const
const FullPivLU< PlainObject > fullPivLu () const
const PartialPivLU< PlainObject > partialPivLu () const
const PartialPivLU< PlainObject > lu () const
const Inverse< Derived > inverse () const
template<typename ResultType >
void computeInverseAndDetWithCheck (ResultType &inverse, typename ResultType::Scalar &determinant, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
template<typename ResultType >
void computeInverseWithCheck (ResultType &inverse, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
Scalar determinant () const
const LLT< PlainObject > llt () const
const LDLT< PlainObject > ldlt () const
const HouseholderQR< PlainObject > householderQr () const
const ColPivHouseholderQR< PlainObject > colPivHouseholderQr () const
const FullPivHouseholderQR< PlainObject > fullPivHouseholderQr () const
const CompleteOrthogonalDecomposition< PlainObject > completeOrthogonalDecomposition () const
EigenvaluesReturnType eigenvalues () const
Computes the eigenvalues of a matrix.
RealScalar operatorNorm () const
Computes the L2 operator norm.
JacobiSVD< PlainObject > jacobiSvd (unsigned int computationOptions=0) const
BDCSVD< PlainObject > bdcSvd (unsigned int computationOptions=0) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC cross_product_return_type< OtherDerived >::type cross (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC PlainObject cross3 (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC PlainObject unitOrthogonal (void) const
EIGEN_DEVICE_FUNC Matrix< Scalar, 3, 1 > eulerAngles (Index a0, Index a1, Index a2) const
EIGEN_DEVICE_FUNC HomogeneousReturnType homogeneous () const
typedef EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (ConstStartMinusOne, Scalar, quotient) HNormalizedReturnType
EIGEN_DEVICE_FUNC const HNormalizedReturnType hnormalized () const
homogeneous normalization
void makeHouseholderInPlace (Scalar &tau, RealScalar &beta)
template<typename EssentialPart >
void makeHouseholder (EssentialPart &essential, Scalar &tau, RealScalar &beta) const
template<typename EssentialPart >
void applyHouseholderOnTheLeft (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
template<typename EssentialPart >
void applyHouseholderOnTheRight (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
template<typename OtherScalar >
void applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > &j)
template<typename OtherScalar >
void applyOnTheRight (Index p, Index q, const JacobiRotation< OtherScalar > &j)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< OtherDerived >::template CwiseProductDenseReturnType< Derived >::Type cwiseProduct (const SparseMatrixBase< OtherDerived > &other) const
const MatrixExponentialReturnValue< Derived > exp () const
const MatrixFunctionReturnValue< Derived > matrixFunction (StemFunction f) const
const MatrixFunctionReturnValue< Derived > cosh () const
const MatrixFunctionReturnValue< Derived > sinh () const
const MatrixFunctionReturnValue< Derived > cos () const
const MatrixFunctionReturnValue< Derived > sin () const
const MatrixSquareRootReturnValue< Derived > sqrt () const
const MatrixLogarithmReturnValue< Derived > log () const
const MatrixPowerReturnValue< Derived > pow (const RealScalar &p) const
const MatrixComplexPowerReturnValue< Derived > pow (const std::complex< RealScalar > &p) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const MatrixBase< OtherDerived > &other)
template<typename DiagonalDerived >
const Product< Derived, DiagonalDerived, LazyProduct > operator* (const DiagonalBase< DiagonalDerived > &a_diagonal) const
template<int p>
NumTraits< typename internal::traits< Derived >::Scalar >::Real lpNorm () const
template<bool Enable>
internal::add_const_on_value_type< typename internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type >::type forceAlignedAccessIf () const
template<bool Enable>
internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf ()
template<typename OtherDerived >
const Product< Derived, OtherDerived, LazyProduct > lazyProduct (const MatrixBase< OtherDerived > &other) const
template<unsigned int UpLo>
MatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
MatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<unsigned int Mode>
MatrixBase< Derived >::template TriangularViewReturnType< Mode >::Type triangularView ()
template<unsigned int Mode>
MatrixBase< Derived >::template ConstTriangularViewReturnType< Mode >::Type triangularView () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC MatrixBase< Derived >::template cross_product_return_type< OtherDerived >::type cross (const MatrixBase< OtherDerived > &other) const
Public Member Functions inherited from Eigen::DenseBase< Derived >
EIGEN_DEVICE_FUNC Index nonZeros () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool hasNaN () const
bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block(Index,Index,Index,Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
EIGEN_DEVICE_FUNC RowsBlockXpr topRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr topRows (Index n) const
This is the const version of topRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr bottomRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr bottomRows (Index n) const
This is the const version of bottomRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr middleRows (Index startRow, Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr middleRows (Index startRow, Index n) const
This is the const version of middleRows(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr leftCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr leftCols (Index n) const
This is the const version of leftCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr rightCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr rightCols (Index n) const
This is the const version of rightCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr middleCols (Index startCol, Index numCols)
EIGEN_DEVICE_FUNC ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
This is the const version of middleCols(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
EIGEN_DEVICE_FUNC SegmentReturnType segment (Index start, Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType segment (Index start, Index n) const
This is the const version of segment(Index,Index).
EIGEN_DEVICE_FUNC SegmentReturnType head (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType head (Index n) const
This is the const version of head(Index).
EIGEN_DEVICE_FUNC SegmentReturnType tail (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType tail (Index n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
template<typename Func >
internal::traits< Derived >::Scalar redux (const Func &func) const
template<int RowFactor, int ColFactor>
const Replicate< Derived, RowFactor, ColFactor > replicate () const
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
Static Public Member Functions
static EIGEN_DEVICE_FUNC const IdentityReturnType Identity ()
static EIGEN_DEVICE_FUNC const IdentityReturnType Identity (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const BasisReturnType Unit (Index size, Index i)
static EIGEN_DEVICE_FUNC const BasisReturnType Unit (Index i)
static EIGEN_DEVICE_FUNC const BasisReturnType UnitX ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitY ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitZ ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitW ()
Static Public Member Functions inherited from Eigen::DenseBase< Derived >
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Member Functions
EIGEN_DEVICE_FUNC MatrixBase ()
template<typename OtherDerived >
Derived & operator+= (const ArrayBase< OtherDerived > &)
template<typename OtherDerived >
Derived & operator-= (const ArrayBase< OtherDerived > &)
Protected Member Functions inherited from Eigen::DenseBase< Derived >
EIGEN_DEVICE_FUNC DenseBase ()
Additional Inherited Members
Related Functions inherited from Eigen::DenseBase< Derived >
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::MatrixBase< Derived >
Base class for all dense matrices, vectors, and expressions.
This class is the base that is inherited by all matrix, vector, and related expression types. Most of the Eigen API is contained in this class, and its base classes. Other important classes for the Eigen API are Matrix, and VectorwiseOp.
Note that some methods are defined in other modules such as the LU_Module LU module for all functions related to matrix inversions.
Template Parameters
Derived is the derived type, e.g. a matrix type, or an expression, etc.
When writing a function taking Eigen objects as argument, if you want your function to take as argument any matrix, vector, or expression, just let it take a MatrixBase argument. As an example, here is a function printFirstRow which, given a matrix, vector, or expression x, prints the first row of x.
template<typename Derived>
void printFirstRow(const Eigen::MatrixBase<Derived>& x)
{
  cout << x.row(0) << endl;
}
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_MATRIXBASE_PLUGIN.
See also
The class hierarchy
Definition at line 48 of file MatrixBase.h.
Member Typedef Documentation
AdjointReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, ConstTransposeReturnType>, ConstTransposeReturnType >::type Eigen::MatrixBase< Derived >::AdjointReturnType
Definition at line 112 of file MatrixBase.h.
Base
template<typename Derived> typedef DenseBase<Derived> Eigen::MatrixBase< Derived >::Base
Definition at line 60 of file MatrixBase.h.
BasisReturnType
template<typename Derived> typedef Block<const CwiseNullaryOp<internal::scalar_identity_op<Scalar>, SquareMatrixType>, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime> Eigen::MatrixBase< Derived >::BasisReturnType
Definition at line 120 of file MatrixBase.h.
CoeffReturnType
template<typename Derived> typedef Base::CoeffReturnType Eigen::MatrixBase< Derived >::CoeffReturnType
Definition at line 84 of file MatrixBase.h.
ColXpr
template<typename Derived> typedef Base::ColXpr Eigen::MatrixBase< Derived >::ColXpr
Definition at line 87 of file MatrixBase.h.
ConjugateReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type Eigen::MatrixBase< Derived >::ConjugateReturnType
Definition at line 20 of file MatrixBase.h.
ConstantReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,PlainObject> Eigen::MatrixBase< Derived >::ConstantReturnType
Definition at line 107 of file MatrixBase.h.
ConstDiagonalDynamicIndexReturnType
template<typename Derived> typedef internal::add_const<Diagonal<const Derived,DynamicIndex> >::type Eigen::MatrixBase< Derived >::ConstDiagonalDynamicIndexReturnType
Definition at line 234 of file MatrixBase.h.
ConstDiagonalReturnType
template<typename Derived> typedef internal::add_const<Diagonal<const Derived> >::type Eigen::MatrixBase< Derived >::ConstDiagonalReturnType
Definition at line 218 of file MatrixBase.h.
ConstStartMinusOne
template<typename Derived> typedef Block<const Derived, internal::traits<Derived>::ColsAtCompileTime==1 ? SizeMinusOne : 1, internal::traits<Derived>::ColsAtCompileTime==1 ? 1 : SizeMinusOne> Eigen::MatrixBase< Derived >::ConstStartMinusOne
Definition at line 417 of file MatrixBase.h.
ConstTransposeReturnType
template<typename Derived> typedef Base::ConstTransposeReturnType Eigen::MatrixBase< Derived >::ConstTransposeReturnType
Definition at line 85 of file MatrixBase.h.
CwiseAbs2ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::CwiseAbs2ReturnType
Definition at line 17 of file MatrixBase.h.
CwiseAbsReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::CwiseAbsReturnType
Definition at line 16 of file MatrixBase.h.
CwiseInverseReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::CwiseInverseReturnType
Definition at line 20 of file MatrixBase.h.
CwiseScalarEqualReturnType
template<typename Derived> typedef CwiseBinaryOp<internal::scalar_cmp_op<Scalar,Scalar,internal::cmp_EQ>, const Derived, const ConstantReturnType> Eigen::MatrixBase< Derived >::CwiseScalarEqualReturnType
Definition at line 137 of file MatrixBase.h.
CwiseSignReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::CwiseSignReturnType
Definition at line 19 of file MatrixBase.h.
CwiseSqrtReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::CwiseSqrtReturnType
Definition at line 18 of file MatrixBase.h.
DiagonalDynamicIndexReturnType
template<typename Derived> typedef Diagonal<Derived,DynamicIndex> Eigen::MatrixBase< Derived >::DiagonalDynamicIndexReturnType
Definition at line 233 of file MatrixBase.h.
DiagonalReturnType
template<typename Derived> typedef Diagonal<Derived> Eigen::MatrixBase< Derived >::DiagonalReturnType
Definition at line 214 of file MatrixBase.h.
EigenvaluesReturnType
template<typename Derived> typedef Matrix<std::complex<RealScalar>, internal::traits<Derived>::ColsAtCompileTime, 1, ColMajor> Eigen::MatrixBase< Derived >::EigenvaluesReturnType
Definition at line 114 of file MatrixBase.h.
HomogeneousReturnType
template<typename Derived> typedef Homogeneous<Derived, HomogeneousReturnTypeDirection> Eigen::MatrixBase< Derived >::HomogeneousReturnType
Definition at line 408 of file MatrixBase.h.
IdentityReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_identity_op<Scalar>,PlainObject> Eigen::MatrixBase< Derived >::IdentityReturnType
Definition at line 116 of file MatrixBase.h.
ImagReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::ImagReturnType
Definition at line 32 of file MatrixBase.h.
NegativeReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> Eigen::MatrixBase< Derived >::NegativeReturnType
Definition at line 36 of file MatrixBase.h.
NonConstImagReturnType
template<typename Derived> typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> Eigen::MatrixBase< Derived >::NonConstImagReturnType
Definition at line 34 of file MatrixBase.h.
NonConstRealReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type Eigen::MatrixBase< Derived >::NonConstRealReturnType
Definition at line 30 of file MatrixBase.h.
PacketScalar
template<typename Derived> typedef internal::packet_traits<Scalar>::type Eigen::MatrixBase< Derived >::PacketScalar
Definition at line 57 of file MatrixBase.h.
PlainObject
template<typename Derived> typedef Base::PlainObject Eigen::MatrixBase< Derived >::PlainObject
Definition at line 103 of file MatrixBase.h.
RealReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type Eigen::MatrixBase< Derived >::RealReturnType
Definition at line 25 of file MatrixBase.h.
RealScalar
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::MatrixBase< Derived >::RealScalar
Definition at line 58 of file MatrixBase.h.
RowXpr
template<typename Derived> typedef Base::RowXpr Eigen::MatrixBase< Derived >::RowXpr
Definition at line 86 of file MatrixBase.h.
Scalar
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::MatrixBase< Derived >::Scalar
Definition at line 56 of file MatrixBase.h.
SquareMatrixType
template<typename Derived> typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::MatrixBase< Derived >::SquareMatrixType
type of the equivalent square matrix
Definition at line 95 of file MatrixBase.h.
StemFunction
template<typename Derived> typedef internal::stem_function<Scalar>::type Eigen::MatrixBase< Derived >::StemFunction
Definition at line 455 of file MatrixBase.h.
StorageBaseType
template<typename Derived> typedef MatrixBase Eigen::MatrixBase< Derived >::StorageBaseType
Definition at line 53 of file MatrixBase.h.
StorageIndex
template<typename Derived> typedef internal::traits<Derived>::StorageIndex Eigen::MatrixBase< Derived >::StorageIndex
Definition at line 55 of file MatrixBase.h.
StorageKind
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::MatrixBase< Derived >::StorageKind
Definition at line 54 of file MatrixBase.h.
Member Enumeration Documentation
anonymous enum
template<typename Derived> anonymous enum
Enumerator
HomogeneousReturnTypeDirection
Definition at line 406 of file MatrixBase.h.
anonymous enum
template<typename Derived> anonymous enum
Enumerator
SizeMinusOne
Definition at line 412 of file MatrixBase.h.
Constructor & Destructor Documentation
MatrixBase()
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::MatrixBase< Derived >::MatrixBase () inline protected
Definition at line 468 of file MatrixBase.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::MatrixBase().
Member Function Documentation
adjoint()
template<typename Derived > const MatrixBase< Derived >::AdjointReturnType Eigen::MatrixBase< Derived >::adjoint () const inline
Returns
an expression of the adjoint (i.e. conjugate transpose) of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own adjoint, do NOT do this:
m = m.adjoint(); // bug!!! caused by aliasing effect
Instead, use the adjointInPlace() method:
m.adjointInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.adjoint().eval();
See also
adjointInPlace(), transpose(), conjugate(), class Transpose, class internal::scalar_conjugate_op
Definition at line 210 of file Transpose.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
adjointInPlace()
template<typename Derived > void Eigen::MatrixBase< Derived >::adjointInPlace () inline
This is the "in place" version of adjoint(): it replaces *this by its own transpose. Thus, doing
m.adjointInPlace();
has the same effect on m as doing
m = m.adjoint().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own adjoint. If you just need the adjoint of a matrix, use adjoint().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), transposeInPlace()
Definition at line 315 of file Transpose.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
applyHouseholderOnTheLeft()
template<typename Derived > template<typename EssentialPart > void Eigen::MatrixBase< Derived >::applyHouseholderOnTheLeft (const EssentialPart & essential, const Scalar & tau, Scalar * workspace)
Apply the elementary reflector H given by \(H = I - tau v v^*\) with \(v^T = [1 essential^T] \) from the left to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() * essential.size() entries
See also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheRight()
Definition at line 113 of file Householder.h.
applyHouseholderOnTheRight()
template<typename Derived > template<typename EssentialPart > void Eigen::MatrixBase< Derived >::applyHouseholderOnTheRight (const EssentialPart & essential, const Scalar & tau, Scalar * workspace)
Apply the elementary reflector H given by \(H = I - tau v v^*\) with \(v^T = [1 essential^T] \) from the right to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() * essential.size() entries
See also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft()
Definition at line 150 of file Householder.h.
applyOnTheLeft() [1/2]
template<typename Derived > template<typename OtherDerived > void Eigen::MatrixBase< Derived >::applyOnTheLeft (const EigenBase< OtherDerived > & other) inline
replaces *this by other * *this.
Example:
Output:
Definition at line 523 of file MatrixBase.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
applyOnTheLeft() [2/2]
template<typename Derived > template<typename OtherScalar > void Eigen::MatrixBase< Derived >::applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > & j) inline
Applies the rotation in the plane j to the rows p and q of *this, i.e., it computes B = J * B, with \(B = \left (\begin{array}{cc} \text{*this.row}(p) \\ \text{*this.row}(q) \end{array} \right) \).
See also
class JacobiRotation, MatrixBase::applyOnTheRight(), internal::apply_rotation_in_the_plane()
Definition at line 278 of file Jacobi.h.
applyOnTheRight()
template<typename Derived > template<typename OtherDerived > void Eigen::MatrixBase< Derived >::applyOnTheRight (const EigenBase< OtherDerived > & other) inline
replaces *this by *this * other. It is equivalent to MatrixBase::operator*=().
Example:
Output:
Definition at line 511 of file MatrixBase.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
array() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper<Derived> Eigen::MatrixBase< Derived >::array () inline
Returns
an Array expression of this matrix
See also
ArrayBase::matrix()
Definition at line 326 of file MatrixBase.h.
array() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArrayWrapper<const Derived> Eigen::MatrixBase< Derived >::array () const inline
Returns
a const Array expression of this matrix
See also
ArrayBase::matrix()
Definition at line 329 of file MatrixBase.h.
asDiagonal()
template<typename Derived > const DiagonalWrapper< const Derived > Eigen::MatrixBase< Derived >::asDiagonal () const inline
Returns
a pseudo-expression of a diagonal matrix with *this as vector of diagonal coefficients
Example:
Output:
See also
class DiagonalWrapper, class DiagonalMatrix, diagonal(), isDiagonal()
Definition at line 277 of file DiagonalMatrix.h.
Referenced by Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::_solve_impl(), Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::_solve_impl(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::prescale(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale(), and Eigen::Scaling().
asPermutation()
template<typename Derived > const PermutationWrapper< const Derived > Eigen::MatrixBase< Derived >::asPermutation () const
Definition at line 620 of file PermutationMatrix.h.
bdcSvd()
template<typename Derived > BDCSVD< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::bdcSvd (unsigned int computationOptions = 0) const inline
Returns
the singular value decomposition of *this computed by Divide & Conquer algorithm
See also
class BDCSVD
Definition at line 1223 of file BDCSVD.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
binaryExpr()
template<typename Derived> template<typename CustomBinaryOp , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
Output:
See also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
Definition at line 44 of file MatrixBase.h.
blueNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::blueNorm () const inline
Returns
the l2 norm of *this using the Blue's algorithm. A Portable Fortran Program to Find the Euclidean Norm of a Vector, ACM TOMS, Vol 4, Issue 1, 1978.
For architecture/scalar types without vectorization, this version is much faster than stableNorm(). Otherwise the stableNorm() is faster.
See also
norm(), stableNorm(), hypotNorm()
Definition at line 202 of file StableNorm.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
cast()
template<typename Derived> template<typename NewType > EIGEN_DEVICE_FUNC CastXpr<NewType>::Type Eigen::MatrixBase< Derived >::cast () const inline
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
Definition at line 63 of file MatrixBase.h.
colPivHouseholderQr()
template<typename Derived > const ColPivHouseholderQR< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::colPivHouseholderQr () const inline
Returns
the column-pivoting Householder QR decomposition of *this.
See also
class ColPivHouseholderQR
Definition at line 646 of file ColPivHouseholderQR.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
completeOrthogonalDecomposition()
template<typename Derived > const CompleteOrthogonalDecomposition< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::completeOrthogonalDecomposition () const inline
Returns
the complete orthogonal decomposition of *this.
See also
class CompleteOrthogonalDecomposition
Definition at line 556 of file CompleteOrthogonalDecomposition.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
computeInverseAndDetWithCheck()
template<typename Derived > template<typename ResultType > void Eigen::MatrixBase< Derived >::computeInverseAndDetWithCheck (ResultType & inverse, typename ResultType::Scalar & determinant, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline
Computation of matrix inverse and determinant, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Parameters
inverse Reference to the matrix in which to store the inverse.
determinant Reference to the variable in which to store the determinant.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Output:
See also
inverse(), computeInverseWithCheck()
Definition at line 362 of file InverseImpl.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
computeInverseWithCheck()
template<typename Derived > template<typename ResultType > void Eigen::MatrixBase< Derived >::computeInverseWithCheck (ResultType & inverse, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline
Computation of matrix inverse, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Parameters
inverse Reference to the matrix in which to store the inverse.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Output:
See also
inverse(), computeInverseAndDetWithCheck()
Definition at line 401 of file InverseImpl.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
conjugate()
template<typename Derived> EIGEN_DEVICE_FUNC ConjugateReturnType Eigen::MatrixBase< Derived >::conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
Definition at line 75 of file MatrixBase.h.
cos()
template<typename Derived > const MatrixFunctionReturnValue< Derived > Eigen::MatrixBase< Derived >::cos () const
Definition at line 555 of file MatrixFunction.h.
cosh()
template<typename Derived > const MatrixFunctionReturnValue< Derived > Eigen::MatrixBase< Derived >::cosh () const
Definition at line 571 of file MatrixFunction.h.
cross()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC cross_product_return_type<OtherDerived>::type Eigen::MatrixBase< Derived >::cross (const MatrixBase< OtherDerived > & other) const inline
cwiseAbs()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType Eigen::MatrixBase< Derived >::cwiseAbs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
cwiseAbs2()
Definition at line 33 of file MatrixBase.h.
Referenced by Eigen::internal::lpNorm_selector< Derived, p >::run(), Eigen::internal::lpNorm_selector< Derived, 1 >::run(), and Eigen::internal::lpNorm_selector< Derived, Infinity >::run().
cwiseAbs2()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType Eigen::MatrixBase< Derived >::cwiseAbs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
cwiseAbs()
Definition at line 46 of file MatrixBase.h.
Referenced by areNotApprox(), and relerr().
cwiseEqual() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::equal_to<Scalar>, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
Definition at line 44 of file MatrixBase.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator==().
cwiseEqual() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType Eigen::MatrixBase< Derived >::cwiseEqual (const Scalar & s) const inline
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See also
cwiseEqual(const MatrixBase<OtherDerived> &) const
Definition at line 150 of file MatrixBase.h.
cwiseInverse()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseInverseReturnType Eigen::MatrixBase< Derived >::cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
cwiseProduct()
Definition at line 84 of file MatrixBase.h.
cwiseMax() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Output:
See also
class CwiseBinaryOp, min()
Definition at line 105 of file MatrixBase.h.
cwiseMax() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::MatrixBase< Derived >::cwiseMax (const Scalar & other) const inline
Returns
an expression of the coefficient-wise max of *this and scalar other
See also
class CwiseBinaryOp, min()
Definition at line 116 of file MatrixBase.h.
cwiseMin() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Output:
See also
class CwiseBinaryOp, max()
Definition at line 79 of file MatrixBase.h.
cwiseMin() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::MatrixBase< Derived >::cwiseMin (const Scalar & other) const inline
Returns
an expression of the coefficient-wise min of *this and scalar other
See also
class CwiseBinaryOp, min()
Definition at line 90 of file MatrixBase.h.
cwiseNotEqual()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseEqual(), isApprox(), isMuchSmallerThan()
Definition at line 64 of file MatrixBase.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator!=().
cwiseProduct()
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase<OtherDerived>::template CwiseProductDenseReturnType<Derived>::Type Eigen::MatrixBase< Derived >::cwiseProduct (const SparseMatrixBase< OtherDerived > & other) const inline
Definition at line 448 of file MatrixBase.h.
cwiseQuotient()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
Definition at line 132 of file MatrixBase.h.
cwiseSign()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSignReturnType Eigen::MatrixBase< Derived >::cwiseSign () const inline
Returns
an expression of the coefficient-wise signum of *this.
Example:
Output:
Definition at line 70 of file MatrixBase.h.
cwiseSqrt()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSqrtReturnType Eigen::MatrixBase< Derived >::cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See also
cwisePow(), cwiseSquare()
Definition at line 59 of file MatrixBase.h.
determinant()
template<typename Derived > internal::traits< Derived >::Scalar Eigen::MatrixBase< Derived >::determinant () const inline
Returns
the determinant of this matrix
Definition at line 92 of file Determinant.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
diagonal() [1/6]
template<typename Derived > MatrixBase< Derived >::template DiagonalIndexReturnType< Index_ >::Type Eigen::MatrixBase< Derived >::diagonal () inline
Returns
an expression of the main diagonal of the matrix *this
*this is not required to be square.
Example:
Output:
See also
class Diagonal
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Output:
See also
MatrixBase::diagonal(), class Diagonal
Definition at line 188 of file Diagonal.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::diagonal(), and Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
diagonal() [2/6]
template<typename Derived > MatrixBase< Derived >::template ConstDiagonalIndexReturnType< Index_ >::Type Eigen::MatrixBase< Derived >::diagonal () const inline
This is the const version of diagonal().
This is the const version of diagonal<int>().
Definition at line 196 of file Diagonal.h.
diagonal() [3/6]
template<typename Derived> template<int Index> EIGEN_DEVICE_FUNC DiagonalIndexReturnType<Index>::Type Eigen::MatrixBase< Derived >::diagonal ()
diagonal() [4/6]
template<typename Derived> template<int Index> EIGEN_DEVICE_FUNC ConstDiagonalIndexReturnType<Index>::Type Eigen::MatrixBase< Derived >::diagonal () const
diagonal() [5/6]
template<typename Derived > MatrixBase< Derived >::DiagonalDynamicIndexReturnType Eigen::MatrixBase< Derived >::diagonal (Index index) inline
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Output:
See also
MatrixBase::diagonal(), class Diagonal
Definition at line 214 of file Diagonal.h.
diagonal() [6/6]
template<typename Derived > MatrixBase< Derived >::ConstDiagonalDynamicIndexReturnType Eigen::MatrixBase< Derived >::diagonal (Index index) const inline
This is the const version of diagonal(Index).
Definition at line 222 of file Diagonal.h.
diagonalSize()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::MatrixBase< Derived >::diagonalSize () const inline
Returns
the size of the main diagonal, which is min(rows(),cols()).
See also
rows(), cols(), SizeAtCompileTime.
Definition at line 101 of file MatrixBase.h.
dot()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC ScalarBinaryOpTraits< typename internal::traits< Derived >::Scalar, typename internal::traits< OtherDerived >::Scalar >::ReturnType Eigen::MatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
Returns
the dot product of *this with other.
Note
If the scalar type is complex numbers, then this function returns the hermitian (sesquilinear) dot product, conjugate-linear in the first variable and linear in the second variable.
See also
squaredNorm(), norm()
Definition at line 69 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
EIGEN_CWISE_BINARY_RETURN_TYPE()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::MatrixBase< Derived >::EIGEN_CWISE_BINARY_RETURN_TYPE (Derived , OtherDerived , product) const & inline
Returns
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseAbs2
Definition at line 23 of file MatrixBase.h.
EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE()
template<typename Derived> typedef Eigen::MatrixBase< Derived >::EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (ConstStartMinusOne , Scalar , quotient)
eigenvalues()
template<typename Derived > MatrixBase< Derived >::EigenvaluesReturnType Eigen::MatrixBase< Derived >::eigenvalues () const inline
Computes the eigenvalues of a matrix.
Returns
Column vector containing the eigenvalues.
This function computes the eigenvalues with the help of the EigenSolver class (for real matrices) or the ComplexEigenSolver class (for complex matrices).
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix.
The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
Output:
See also
EigenSolver::eigenvalues(), ComplexEigenSolver::eigenvalues(), SelfAdjointView::eigenvalues()
Definition at line 67 of file MatrixBaseEigenvalues.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
exp()
template<typename Derived > const MatrixExponentialReturnValue< Derived > Eigen::MatrixBase< Derived >::exp () const
Definition at line 424 of file MatrixExponential.h.
forceAlignedAccess() [1/2]
template<typename Derived > const ForceAlignedAccess< Derived > Eigen::MatrixBase< Derived >::forceAlignedAccess () const inline
Returns
an expression of *this with forced aligned access
See also
forceAlignedAccessIf(),class ForceAlignedAccess
Definition at line 312 of file MatrixBase.h.
forceAlignedAccess() [2/2]
template<typename Derived > ForceAlignedAccess< Derived > Eigen::MatrixBase< Derived >::forceAlignedAccess () inline
Returns
an expression of *this with forced aligned access
See also
forceAlignedAccessIf(), class ForceAlignedAccess
Definition at line 313 of file MatrixBase.h.
forceAlignedAccessIf() [1/4]
template<typename Derived> template<bool Enable> internal::add_const_on_value_type<typename internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type>::type Eigen::MatrixBase< Derived >::forceAlignedAccessIf () const inline
Returns
an expression of *this with forced aligned access if Enable is true.
See also
forceAlignedAccess(), class ForceAlignedAccess
Definition at line 128 of file ForceAlignedAccess.h.
forceAlignedAccessIf() [2/4]
template<typename Derived> template<bool Enable> internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::MatrixBase< Derived >::forceAlignedAccessIf () inline
Returns
an expression of *this with forced aligned access if Enable is true.
See also
forceAlignedAccess(), class ForceAlignedAccess
Definition at line 139 of file ForceAlignedAccess.h.
forceAlignedAccessIf() [3/4]
template<typename Derived> template<bool Enable> const Derived& Eigen::MatrixBase< Derived >::forceAlignedAccessIf () const inline
Definition at line 314 of file MatrixBase.h.
forceAlignedAccessIf() [4/4]
template<typename Derived> template<bool Enable> Derived& Eigen::MatrixBase< Derived >::forceAlignedAccessIf () inline
Definition at line 315 of file MatrixBase.h.
fullPivHouseholderQr()
template<typename Derived > const FullPivHouseholderQR< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::fullPivHouseholderQr () const inline
Returns
the full-pivoting Householder QR decomposition of *this.
See also
class FullPivHouseholderQR
Definition at line 669 of file FullPivHouseholderQR.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
fullPivLu()
template<typename Derived > const FullPivLU< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::fullPivLu () const inline
Returns
the full-pivoting LU decomposition of *this.
See also
class FullPivLU
Definition at line 884 of file FullPivLU.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
householderQr()
template<typename Derived > const HouseholderQR< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::householderQr () const inline
Returns
the Householder QR decomposition of *this.
See also
class HouseholderQR
Definition at line 402 of file HouseholderQR.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
hypotNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::hypotNorm () const inline
Returns
the l2 norm of *this avoiding undeflow and overflow. This version use a concatenation of hypot() calls, and it is very slow.
See also
norm(), stableNorm()
Definition at line 214 of file StableNorm.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
Identity() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::IdentityReturnType Eigen::MatrixBase< Derived >::Identity () static
Returns
an expression of the identity matrix (not necessarily square).
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variant taking size arguments.
Example:
Output:
See also
Identity(Index,Index), setIdentity(), isIdentity()
Definition at line 700 of file CwiseNullaryOp.h.
Identity() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::IdentityReturnType Eigen::MatrixBase< Derived >::Identity (Index rows, Index cols) static
Returns
an expression of the identity matrix (not necessarily square).
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Identity() should be used instead.
Example:
Output:
See also
Identity(), setIdentity(), isIdentity()
Definition at line 683 of file CwiseNullaryOp.h.
imag() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC const ImagReturnType Eigen::MatrixBase< Derived >::imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
Definition at line 96 of file MatrixBase.h.
imag() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC NonConstImagReturnType Eigen::MatrixBase< Derived >::imag () inline
Returns
a non const expression of the imaginary part of *this.
See also
real()
Definition at line 164 of file MatrixBase.h.
inverse()
template<typename Derived > const Inverse< Derived > Eigen::MatrixBase< Derived >::inverse () const inline
Returns
the matrix inverse of this matrix.
For small fixed sizes up to 4x4, this method uses cofactors. In the general case, this method uses class PartialPivLU.
Note
This matrix must be invertible, otherwise the result is undefined. If you need an invertibility check, do the following:
for fixed sizes up to 4x4, use computeInverseAndDetWithCheck().
for the general case, use class FullPivLU.
Example:
Output:
See also
computeInverseAndDetWithCheck()
Definition at line 335 of file InverseImpl.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array(), and Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform().
isDiagonal()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isDiagonal (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a diagonal matrix, within the precision given by prec.
Example:
Output:
See also
asDiagonal()
Definition at line 291 of file DiagonalMatrix.h.
isIdentity()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isIdentity (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the identity matrix (not necessarily square), within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Identity(), Identity(Index,Index), setIdentity()
Definition at line 717 of file CwiseNullaryOp.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::Identity().
isLowerTriangular()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isLowerTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a lower triangular matrix, within the precision given by prec.
See also
isUpperTriangular()
Definition at line 673 of file TriangularMatrix.h.
isOrthogonal()
template<typename Derived > template<typename OtherDerived > bool Eigen::MatrixBase< Derived >::isOrthogonal (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately orthogonal to other, within the precision given by prec.
Example:
Output:
Definition at line 280 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::lpNorm().
isUnitary()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isUnitary (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately an unitary matrix, within the precision given by prec. In the case where the Scalar type is real numbers, a unitary matrix is an orthogonal matrix, whence the name.
Note
This can be used to check whether a family of vectors forms an orthonormal basis. Indeed, m.isUnitary() returns true if and only if the columns (equivalently, the rows) of m form an orthonormal basis.
Example:
Output:
Definition at line 299 of file Dot.h.
Referenced by Eigen::test_isUnitary().
isUpperTriangular()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isUpperTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to an upper triangular matrix, within the precision given by prec.
See also
isLowerTriangular()
Definition at line 648 of file TriangularMatrix.h.
jacobiSvd()
template<typename Derived > JacobiSVD< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::jacobiSvd (unsigned int computationOptions = 0) const inline
Returns
the singular value decomposition of *this computed by two-sided Jacobi transformations.
See also
class JacobiSVD
Definition at line 797 of file JacobiSVD.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
lazyProduct() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<Derived,OtherDerived,LazyProduct> Eigen::MatrixBase< Derived >::lazyProduct (const MatrixBase< OtherDerived > & other) const
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
lazyProduct() [2/2]
template<typename Derived> template<typename OtherDerived > const Product<Derived,OtherDerived,LazyProduct> Eigen::MatrixBase< Derived >::lazyProduct (const MatrixBase< OtherDerived > & other) const
Returns
an expression of the matrix product of *this and other without implicit evaluation.
The returned product will behave like any other expressions: the coefficients of the product will be computed once at a time as requested. This might be useful in some extremely rare cases when only a small and no coherent fraction of the result's coefficients have to be computed.
Warning
This version of the matrix product can be much much slower. So use it only if you know what you are doing and that you measured a true speed improvement.
See also
operator*(const MatrixBase&)
Definition at line 431 of file GeneralProduct.h.
ldlt()
template<typename Derived > const LDLT< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::ldlt () const inline
Returns
the Cholesky decomposition with full pivoting without square root of *this
See also
SelfAdjointView::ldlt()
Definition at line 662 of file LDLT.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
llt()
template<typename Derived > const LLT< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::llt () const inline
Returns
the LLT decomposition of *this
See also
SelfAdjointView::llt()
Definition at line 516 of file LLT.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
log()
template<typename Derived > const MatrixLogarithmReturnValue< Derived > Eigen::MatrixBase< Derived >::log () const
Definition at line 365 of file MatrixLogarithm.h.
lpNorm() [1/2]
template<typename Derived> template<int p> NumTraits<typename internal::traits<Derived>::Scalar>::Real Eigen::MatrixBase< Derived >::lpNorm () const inline
Returns
the coefficient-wise \(\ell^p \) norm of *this, that is, returns the p-th root of the sum of the p-th powers of the absolute values of the coefficients of *this. If p is the special value Eigen::Infinity, this function returns the \(\ell^\infty \) norm, that is the maximum of the absolute values of the coefficients of *this.
In all cases, if *this is empty, then the value 0 is returned.
Note
For matrices, this function does not compute the operator-norm. That is, if *this is a matrix, then its coefficients are interpreted as a 1D vector. Nonetheless, you can easily compute the 1-norm and \(\infty\)-norm matrix operator norms using partial reductions .
See also
norm()
Definition at line 264 of file Dot.h.
lpNorm() [2/2]
template<typename Derived> template<int p> EIGEN_DEVICE_FUNC RealScalar Eigen::MatrixBase< Derived >::lpNorm () const
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::forceAlignedAccessIf().
lu()
template<typename Derived > const PartialPivLU< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::lu () const inline
Synonym of partialPivLu().
Returns
the partial-pivoting LU decomposition of *this.
See also
class PartialPivLU
Definition at line 604 of file PartialPivLU.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
makeHouseholder()
template<typename Derived > template<typename EssentialPart > void Eigen::MatrixBase< Derived >::makeHouseholder (EssentialPart & essential, Scalar & tau, RealScalar & beta) const
Computes the elementary reflector H such that: \(H *this = [ beta 0 ... 0]^T \) where the transformation H is: \(H = I - tau v v^*\) and the vector v is: \(v^T = [1 essential^T] \)
On output:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
beta the result of H * *this
See also
MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
Definition at line 65 of file Householder.h.
makeHouseholderInPlace()
template<typename Derived > void Eigen::MatrixBase< Derived >::makeHouseholderInPlace (Scalar & tau, RealScalar & beta)
Computes the elementary reflector H such that: \(H *this = [ beta 0 ... 0]^T \) where the transformation H is: \(H = I - tau v v^*\) and the vector v is: \(v^T = [1 essential^T] \)
The essential part of the vector v is stored in *this.
On output:
Parameters
tau the scaling factor of the Householder transformation
beta the result of H * *this
See also
MatrixBase::makeHouseholder(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
Definition at line 42 of file Householder.h.
matrix() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC MatrixBase<Derived>& Eigen::MatrixBase< Derived >::matrix () inline
Definition at line 321 of file MatrixBase.h.
Referenced by regrrssion_bug_1410().
matrix() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC const MatrixBase<Derived>& Eigen::MatrixBase< Derived >::matrix () const inline
Definition at line 322 of file MatrixBase.h.
matrixFunction()
template<typename Derived> const MatrixFunctionReturnValue< Derived > Eigen::MatrixBase< Derived >::matrixFunction (StemFunction f) const
Definition at line 540 of file MatrixFunction.h.
noalias()
template<typename Derived > NoAlias< Derived, MatrixBase > Eigen::MatrixBase< Derived >::noalias ()
Returns
a pseudo expression of *this with an operator= assuming no aliasing between *this and the source expression.
More precisely, noalias() allows to bypass the EvalBeforeAssignBit flag. Currently, even though several expressions may alias, only product expressions have this flag. Therefore, noalias() is only usefull when the source expression contains a matrix product.
Here are some examples where noalias is usefull:
D.noalias()  = A * B;
D.noalias() += A.transpose() * B;
D.noalias() -= 2 * A * B.adjoint();
On the other hand the following example will lead to a wrong result:
A.noalias() = A * B;
because the result matrix A is also an operand of the matrix product. Therefore, there is no alternative than evaluating A * B in a temporary, that is the default behavior when you write:
A = A * B;
See also
class NoAlias
Definition at line 101 of file NoAlias.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator!=().
norm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::norm () const inline
Returns
, for vectors, the l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the square root of the sum of the square of all the matrix entries. For vectors, this is also equals to the square root of the dot product of *this with itself.
See also
lpNorm(), dot(), squaredNorm()
Definition at line 105 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag(), and Eigen::internal::lpNorm_selector< Derived, 2 >::run().
normalize()
template<typename Derived > void Eigen::MatrixBase< Derived >::normalize () inline
Normalizes the vector, i.e. divides it by its own norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then *this is left unchanged.
See also
norm(), normalized()
Definition at line 142 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
normalized()
template<typename Derived > const MatrixBase< Derived >::PlainObject Eigen::MatrixBase< Derived >::normalized () const inline
Returns
an expression of the quotient of *this by its own norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then this function returns a copy of the input.
See also
norm(), normalize()
Definition at line 121 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag(), and Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::setFromTwoVectors().
operator &&()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_and_op, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean and operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator||(), select()
Definition at line 92 of file MatrixBase.h.
operator!=()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::MatrixBase< Derived >::operator!= (const MatrixBase< OtherDerived > & other) const inline
Returns
true if at least one pair of coefficients of *this and other are not exactly equal to each other.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See also
isApprox(), operator==
Definition at line 305 of file MatrixBase.h.
operator*() [1/3]
template<typename Derived> template<typename DiagonalDerived > const Product<Derived, DiagonalDerived, LazyProduct> Eigen::MatrixBase< Derived >::operator* (const DiagonalBase< DiagonalDerived > & a_diagonal) const inline
Returns
the diagonal matrix product of *this by the diagonal matrix diagonal.
Definition at line 21 of file DiagonalProduct.h.
operator*() [2/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived > Eigen::MatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const inline
Returns
the matrix product of *this and other.
Note
If instead of the matrix product you want the coefficient-wise product, see Cwise::operator*().
See also
lazyProduct(), operator*=(const MatrixBase&), Cwise::operator*()
Definition at line 387 of file GeneralProduct.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
operator*() [3/3]
template<typename Derived> template<typename DiagonalDerived > EIGEN_DEVICE_FUNC const Product<Derived, DiagonalDerived, LazyProduct> Eigen::MatrixBase< Derived >::operator* (const DiagonalBase< DiagonalDerived > & diagonal) const
operator*=()
template<typename Derived > template<typename OtherDerived > Derived & Eigen::MatrixBase< Derived >::operator*= (const EigenBase< OtherDerived > & other) inline
replaces *this by *this * other.
Returns
a reference to *this
Example:
Output:
Definition at line 498 of file MatrixBase.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
operator+=() [1/3]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator+= (const MatrixBase< OtherDerived > & other)
operator+=() [2/3]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator+= (const MatrixBase< OtherDerived > & other)
replaces *this by *this + other.
Returns
a reference to *this
Definition at line 175 of file CwiseBinaryOp.h.
operator+=() [3/3]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::MatrixBase< Derived >::operator+= (const ArrayBase< OtherDerived > &) inline protected
Definition at line 476 of file MatrixBase.h.
operator-()
template<typename Derived> EIGEN_DEVICE_FUNC const NegativeReturnType Eigen::MatrixBase< Derived >::operator- () const inline
Returns
an expression of the opposite of *this
Definition at line 46 of file MatrixBase.h.
operator-=() [1/3]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator-= (const MatrixBase< OtherDerived > & other)
operator-=() [2/3]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator-= (const MatrixBase< OtherDerived > & other)
replaces *this by *this - other.
Returns
a reference to *this
Definition at line 162 of file CwiseBinaryOp.h.
operator-=() [3/3]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::MatrixBase< Derived >::operator-= (const ArrayBase< OtherDerived > &) inline protected
Definition at line 479 of file MatrixBase.h.
operator=() [1/6]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Definition at line 73 of file Assign.h.
operator=() [2/6]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
Definition at line 82 of file Assign.h.
operator=() [3/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::operator= (const MatrixBase< Derived > & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
Definition at line 55 of file Assign.h.
operator=() [4/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Definition at line 64 of file Assign.h.
operator=() [5/6]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::MatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
operator=() [6/6]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::MatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
operator==()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::MatrixBase< Derived >::operator== (const MatrixBase< OtherDerived > & other) const inline
Returns
true if each coefficients of *this and other are all exactly equal.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See also
isApprox(), operator!=
Definition at line 297 of file MatrixBase.h.
operatorNorm()
template<typename Derived > MatrixBase< Derived >::RealScalar Eigen::MatrixBase< Derived >::operatorNorm () const inline
Computes the L2 operator norm.
Returns
Operator norm of the matrix.
This function computes the L2 operator norm of a matrix, which is also known as the spectral norm. The norm of a matrix \(A \) is defined to be
\[ \|A\|_2 = \max_x \frac{\|Ax\|_2}{\|x\|_2} \]
where the maximum is over all vectors and the norm on the right is the Euclidean vector norm. The norm equals the largest singular value, which is the square root of the largest eigenvalue of the positive semi-definite matrix \(A^*A \).
The current implementation uses the eigenvalues of \(A^*A \), as computed by SelfAdjointView::eigenvalues(), to compute the operator norm of a matrix. The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
Output:
See also
SelfAdjointView::eigenvalues(), SelfAdjointView::operatorNorm()
Definition at line 122 of file MatrixBaseEigenvalues.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
operator||()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_or_op, const Derived, const OtherDerived> Eigen::MatrixBase< Derived >::operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean or operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator&&(), select()
Definition at line 111 of file MatrixBase.h.
partialPivLu()
template<typename Derived > const PartialPivLU< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::partialPivLu () const inline
Returns
the partial-pivoting LU decomposition of *this.
See also
class PartialPivLU
Definition at line 589 of file PartialPivLU.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::array().
pow() [1/2]
template<typename Derived > const MatrixPowerReturnValue< Derived > Eigen::MatrixBase< Derived >::pow (const RealScalar & p) const
Definition at line 700 of file MatrixPower.h.
pow() [2/2]
template<typename Derived > const MatrixComplexPowerReturnValue< Derived > Eigen::MatrixBase< Derived >::pow (const std::complex< RealScalar > & p) const
Definition at line 704 of file MatrixPower.h.
real() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC RealReturnType Eigen::MatrixBase< Derived >::real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
Definition at line 87 of file MatrixBase.h.
real() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC NonConstRealReturnType Eigen::MatrixBase< Derived >::real () inline
Returns
a non const expression of the real part of *this.
See also
imag()
Definition at line 155 of file MatrixBase.h.
selfadjointView() [1/4]
template<typename Derived> template<unsigned int UpLo> EIGEN_DEVICE_FUNC SelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView ()
selfadjointView() [2/4]
template<typename Derived> template<unsigned int UpLo> EIGEN_DEVICE_FUNC ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView () const
selfadjointView() [3/4]
template<typename Derived> template<unsigned int UpLo> MatrixBase<Derived>::template ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView () const
This is the const version of MatrixBase::selfadjointView()
Definition at line 326 of file SelfAdjointView.h.
selfadjointView() [4/4]
template<typename Derived> template<unsigned int UpLo> MatrixBase<Derived>::template SelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView ()
Returns
an expression of a symmetric/self-adjoint view extracted from the upper or lower triangular part of the current matrix
The parameter UpLo can be either Upper or Lower
Example:
Output:
See also
class SelfAdjointView
Definition at line 343 of file SelfAdjointView.h.
setIdentity() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::setIdentity ()
Writes the identity expression (not necessarily square) into *this.
Example:
Output:
See also
class CwiseNullaryOp, Identity(), Identity(Index,Index), isIdentity()
Definition at line 774 of file CwiseNullaryOp.h.
setIdentity() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::setIdentity (Index rows, Index cols)
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
MatrixBase::setIdentity(), class CwiseNullaryOp, MatrixBase::Identity()
Definition at line 790 of file CwiseNullaryOp.h.
sin()
template<typename Derived > const MatrixFunctionReturnValue< Derived > Eigen::MatrixBase< Derived >::sin () const
Definition at line 547 of file MatrixFunction.h.
sinh()
template<typename Derived > const MatrixFunctionReturnValue< Derived > Eigen::MatrixBase< Derived >::sinh () const
Definition at line 563 of file MatrixFunction.h.
sqrt()
template<typename Derived > const MatrixSquareRootReturnValue< Derived > Eigen::MatrixBase< Derived >::sqrt () const
Definition at line 362 of file MatrixSquareRoot.h.
squaredNorm()
template<typename Derived > EIGEN_STRONG_INLINE NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::squaredNorm () const
Returns
, for vectors, the squared l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the sum of the square of all the matrix entries. For vectors, this is also equals to the dot product of *this with itself.
See also
dot(), norm(), lpNorm()
Definition at line 93 of file Dot.h.
Referenced by Eigen::GMRES< _MatrixType, _Preconditioner >::_solve_impl(), Eigen::IterationController::finished(), and Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
stableNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::stableNorm () const inline
Returns
the l2 norm of *this avoiding underflow and overflow. This version use a blockwise two passes algorithm: 1 - find the absolute largest coefficient s 2 - compute \(s \Vert \frac{*this}{s} \Vert \) in a standard way
For architecture/scalar types supporting vectorization, this version is faster than blueNorm(). Otherwise the blueNorm() is much faster.
See also
norm(), blueNorm(), hypotNorm()
Definition at line 157 of file StableNorm.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
stableNormalize()
template<typename Derived > void Eigen::MatrixBase< Derived >::stableNormalize () inline
Normalizes the vector while avoid underflow and overflow
This method is analogue to the normalize() method, but it reduces the risk of underflow and overflow when computing the norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then *this is left unchanged.
See also
stableNorm(), stableNormalized(), normalize()
Definition at line 188 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
stableNormalized()
template<typename Derived > const MatrixBase< Derived >::PlainObject Eigen::MatrixBase< Derived >::stableNormalized () const inline
Returns
an expression of the quotient of *this by its own norm while avoiding underflow and overflow.
This method is analogue to the normalized() method, but it reduces the risk of underflow and overflow when computing the norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then this function returns a copy of the input.
See also
stableNorm(), stableNormalize(), normalized()
Definition at line 164 of file Dot.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::imag().
trace()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::MatrixBase< Derived >::trace () const
Returns
the trace of *this, i.e. the sum of the coefficients on the main diagonal.
*this can be any matrix, not necessarily square.
See also
diagonal(), sum()
Definition at line 498 of file Redux.h.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::forceAlignedAccessIf().
triangularView() [1/4]
template<typename Derived> template<unsigned int Mode> EIGEN_DEVICE_FUNC TriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView ()
triangularView() [2/4]
template<typename Derived> template<unsigned int Mode> EIGEN_DEVICE_FUNC ConstTriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView () const
triangularView() [3/4]
template<typename Derived> template<unsigned int Mode> MatrixBase<Derived>::template TriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView ()
Returns
an expression of a triangular view extracted from the current matrix
The parameter Mode can have the following values: Upper, StrictlyUpper, UnitUpper, Lower, StrictlyLower, UnitLower.
Example:
Output:
See also
class TriangularView
Definition at line 628 of file TriangularMatrix.h.
triangularView() [4/4]
template<typename Derived> template<unsigned int Mode> MatrixBase<Derived>::template ConstTriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView () const
This is the const version of MatrixBase::triangularView()
Definition at line 637 of file TriangularMatrix.h.
unaryExpr()
template<typename Derived> template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp<CustomUnaryOp, const Derived> Eigen::MatrixBase< Derived >::unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
Definition at line 122 of file MatrixBase.h.
unaryViewExpr()
template<typename Derived> template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView<CustomViewOp, const Derived> Eigen::MatrixBase< Derived >::unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See also
unaryExpr, binaryExpr class CwiseUnaryOp
Definition at line 143 of file MatrixBase.h.
Unit() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::Unit (Index newSize, Index i) static
Returns
an expression of the i-th unit (basis) vector.
See also
MatrixBase::Unit(Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
Definition at line 803 of file CwiseNullaryOp.h.
Unit() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::Unit (Index i) static
Returns
an expression of the i-th unit (basis) vector.
This variant is for fixed-size vector only.
See also
MatrixBase::Unit(Index,Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
Definition at line 818 of file CwiseNullaryOp.h.
UnitW()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitW () static
Returns
an expression of the W axis unit vector (0,0,0,1)
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
Definition at line 861 of file CwiseNullaryOp.h.
UnitX()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitX () static
Returns
an expression of the X axis unit vector (1{,0}^*)
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
Definition at line 831 of file CwiseNullaryOp.h.
UnitY()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitY () static
Returns
an expression of the Y axis unit vector (0,1{,0}^*)
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
Definition at line 841 of file CwiseNullaryOp.h.
UnitZ()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitZ () static
Returns
an expression of the Z axis unit vector (0,0,1{,0}^*)
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
Definition at line 851 of file CwiseNullaryOp.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/MatrixBase.h
/travis/libpairinteraction/eigen/Eigen/src/Cholesky/LDLT.h
/travis/libpairinteraction/eigen/Eigen/src/Cholesky/LLT.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Assign.h
/travis/libpairinteraction/eigen/Eigen/src/Core/CwiseBinaryOp.h
/travis/libpairinteraction/eigen/Eigen/src/Core/CwiseNullaryOp.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Diagonal.h
/travis/libpairinteraction/eigen/Eigen/src/Core/DiagonalMatrix.h
/travis/libpairinteraction/eigen/Eigen/src/Core/DiagonalProduct.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Dot.h
/travis/libpairinteraction/eigen/Eigen/src/Core/ForceAlignedAccess.h
/travis/libpairinteraction/eigen/Eigen/src/Core/GeneralProduct.h
/travis/libpairinteraction/eigen/Eigen/src/Core/NoAlias.h
/travis/libpairinteraction/eigen/Eigen/src/Core/PermutationMatrix.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Redux.h
/travis/libpairinteraction/eigen/Eigen/src/Core/SelfAdjointView.h
/travis/libpairinteraction/eigen/Eigen/src/Core/StableNorm.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Transpose.h
/travis/libpairinteraction/eigen/Eigen/src/Core/TriangularMatrix.h
/travis/libpairinteraction/eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h
/travis/libpairinteraction/eigen/Eigen/src/Geometry/EulerAngles.h
/travis/libpairinteraction/eigen/Eigen/src/Geometry/Homogeneous.h
/travis/libpairinteraction/eigen/Eigen/src/Geometry/OrthoMethods.h
/travis/libpairinteraction/eigen/Eigen/src/Householder/Householder.h
/travis/libpairinteraction/eigen/Eigen/src/Jacobi/Jacobi.h
/travis/libpairinteraction/eigen/Eigen/src/LU/Determinant.h
/travis/libpairinteraction/eigen/Eigen/src/LU/FullPivLU.h
/travis/libpairinteraction/eigen/Eigen/src/LU/InverseImpl.h
/travis/libpairinteraction/eigen/Eigen/src/LU/PartialPivLU.h
/travis/libpairinteraction/eigen/Eigen/src/QR/ColPivHouseholderQR.h
/travis/libpairinteraction/eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h
/travis/libpairinteraction/eigen/Eigen/src/QR/FullPivHouseholderQR.h
/travis/libpairinteraction/eigen/Eigen/src/QR/HouseholderQR.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseView.h
/travis/libpairinteraction/eigen/Eigen/src/SVD/BDCSVD.h
/travis/libpairinteraction/eigen/Eigen/src/SVD/JacobiSVD.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixExponential.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixFunction.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixLogarithm.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixPower.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixSquareRoot.h