pairinteraction: tensor_interface< real > Class Template Reference
tensor_interface< real > Class Template Reference
#include <tensor_interface.hh>
Public Types
typedef real real_type
typedef Eigen::Tensor< real, 2 >::Index Index
typedef std::vector< real > stl_vector
typedef std::vector< stl_vector > stl_matrix
typedef Eigen::Tensor< real, 2 > gene_matrix
typedef Eigen::Tensor< real, 1 > gene_vector
Static Public Member Functions
static std::string name (void)
static void free_matrix (gene_matrix &, int)
static void free_vector (gene_vector &)
static BTL_DONT_INLINE void matrix_from_stl (gene_matrix &A, stl_matrix &A_stl)
static BTL_DONT_INLINE void vector_from_stl (gene_vector &B, stl_vector &B_stl)
static BTL_DONT_INLINE void vector_to_stl (gene_vector &B, stl_vector &B_stl)
static BTL_DONT_INLINE void matrix_to_stl (gene_matrix &A, stl_matrix &A_stl)
static void matrix_matrix_product (const gene_matrix &A, const gene_matrix &B, gene_matrix &X, int)
static void matrix_vector_product (const gene_matrix &A, const gene_vector &B, gene_vector &X, int)
static void axpy (real coef, const gene_vector &X, gene_vector &Y, int)
static void axpby (real a, const gene_vector &X, real b, gene_vector &Y, int)
static EIGEN_DONT_INLINE void copy_matrix (const gene_matrix &source, gene_matrix &cible, int)
static EIGEN_DONT_INLINE void copy_vector (const gene_vector &source, gene_vector &cible, int)
Detailed Description
template<class real>
class tensor_interface< real >
Definition at line 19 of file tensor_interface.hh.
Member Typedef Documentation
gene_matrix
template<class real > typedef Eigen::Tensor<real,2> tensor_interface< real >::gene_matrix
Definition at line 28 of file tensor_interface.hh.
gene_vector
template<class real > typedef Eigen::Tensor<real,1> tensor_interface< real >::gene_vector
Definition at line 29 of file tensor_interface.hh.
Index
template<class real > typedef Eigen::Tensor<real,2>::Index tensor_interface< real >::Index
Definition at line 23 of file tensor_interface.hh.
real_type
template<class real > typedef real tensor_interface< real >::real_type
Definition at line 22 of file tensor_interface.hh.
stl_matrix
template<class real > typedef std::vector<stl_vector> tensor_interface< real >::stl_matrix
Definition at line 26 of file tensor_interface.hh.
stl_vector
template<class real > typedef std::vector<real> tensor_interface< real >::stl_vector
Definition at line 25 of file tensor_interface.hh.
Member Function Documentation
axpby()
template<class real > static void tensor_interface< real >::axpby (real a, const gene_vector & X, real b, gene_vector & Y, int) inline static
Definition at line 92 of file tensor_interface.hh.
axpy()
template<class real > static void tensor_interface< real >::axpy (real coef, const gene_vector & X, gene_vector & Y, int) inline static
Definition at line 88 of file tensor_interface.hh.
References X.
copy_matrix()
template<class real > static EIGEN_DONT_INLINE void tensor_interface< real >::copy_matrix (const gene_matrix & source, gene_matrix & cible, int) inline static
Definition at line 96 of file tensor_interface.hh.
copy_vector()
template<class real > static EIGEN_DONT_INLINE void tensor_interface< real >::copy_vector (const gene_vector & source, gene_vector & cible, int) inline static
Definition at line 100 of file tensor_interface.hh.
free_matrix()
template<class real > static void tensor_interface< real >::free_matrix (gene_matrix & , int) inline static
Definition at line 37 of file tensor_interface.hh.
free_vector()
template<class real > static void tensor_interface< real >::free_vector (gene_vector &) inline static
Definition at line 39 of file tensor_interface.hh.
matrix_from_stl()
template<class real > static BTL_DONT_INLINE void tensor_interface< real >::matrix_from_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 41 of file tensor_interface.hh.
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeffRef(), i, j, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::resize(), and size.
matrix_matrix_product()
template<class real > static void tensor_interface< real >::matrix_matrix_product (const gene_matrix & A, const gene_matrix & B, gene_matrix & X, int) inline static
Definition at line 76 of file tensor_interface.hh.
matrix_to_stl()
template<class real > static BTL_DONT_INLINE void tensor_interface< real >::matrix_to_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 65 of file tensor_interface.hh.
matrix_vector_product()
template<class real > static void tensor_interface< real >::matrix_vector_product (const gene_matrix & A, const gene_vector & B, gene_vector & X, int) inline static
Definition at line 82 of file tensor_interface.hh.
name()
template<class real > static std::string tensor_interface< real >::name (void) inline static
Definition at line 32 of file tensor_interface.hh.
References EIGEN_MAKESTRING.
vector_from_stl()
template<class real > static BTL_DONT_INLINE void tensor_interface< real >::vector_from_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 51 of file tensor_interface.hh.
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeffRef(), i, and Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::resize().
vector_to_stl()
template<class real > static BTL_DONT_INLINE void tensor_interface< real >::vector_to_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 59 of file tensor_interface.hh.
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeff(), and i.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/libs/tensors/tensor_interface.hh