pairinteraction: Eigen::KroneckerProductSparse< Lhs, Rhs > Class Template Reference
Eigen::KroneckerProductSparse< Lhs, Rhs > Class Template Reference
Kronecker tensor product helper class for sparse matrices.
#include <KroneckerTensorProduct.h>
Public Member Functions
KroneckerProductSparse (const Lhs &A, const Rhs &B)
Constructor.
template<typename Dest >
void evalTo (Dest &dst) const
Evaluate the Kronecker tensor product.
Public Member Functions inherited from Eigen::KroneckerProductBase< KroneckerProductSparse< Lhs, Rhs > >
KroneckerProductBase (const Lhs &A, const Rhs &B)
Constructor.
Index rows () const
Index cols () const
Scalar coeff (Index row, Index col) const
Scalar coeff (Index i) const
Public Member Functions inherited from Eigen::ReturnByValue< KroneckerProductSparse< Lhs, Rhs > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Additional Inherited Members
Public Types inherited from Eigen::ReturnByValue< KroneckerProductSparse< Lhs, Rhs > >
typedef internal::traits< KroneckerProductSparse< Lhs, Rhs > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Protected Types inherited from Eigen::KroneckerProductBase< KroneckerProductSparse< Lhs, Rhs > >
typedef Traits::Lhs Lhs
typedef Traits::Rhs Rhs
Protected Attributes inherited from Eigen::KroneckerProductBase< KroneckerProductSparse< Lhs, Rhs > >
Lhs::Nested m_A
Rhs::Nested m_B
Detailed Description
template<typename Lhs, typename Rhs>
class Eigen::KroneckerProductSparse< Lhs, Rhs >
Kronecker tensor product helper class for sparse matrices.
If at least one of the operands is a sparse matrix expression, then this class is returned and evaluates into a sparse matrix.
This class is the return value of kroneckerProduct(EigenBase, EigenBase). Use the function rather than construct this class directly to avoid specifying template prarameters.
Template Parameters
Lhs Type of the left-hand side, a matrix expression.
Rhs Type of the rignt-hand side, a matrix expression.
Definition at line 115 of file KroneckerTensorProduct.h.
Constructor & Destructor Documentation
KroneckerProductSparse()
template<typename Lhs , typename Rhs > Eigen::KroneckerProductSparse< Lhs, Rhs >::KroneckerProductSparse (const Lhs & A, const Rhs & B) inline
Constructor.
Definition at line 124 of file KroneckerTensorProduct.h.
References Eigen::ReturnByValue< Derived >::evalTo().
Member Function Documentation
evalTo()
template<typename Lhs , typename Rhs > template<typename Dest > void Eigen::KroneckerProductSparse< Lhs, Rhs >::evalTo (Dest & dst) const
Evaluate the Kronecker tensor product.
Definition at line 147 of file KroneckerTensorProduct.h.
References Eigen::KroneckerProductBase< Derived >::cols(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), i, j, Eigen::KroneckerProductBase< Derived >::m_A, Eigen::KroneckerProductBase< Derived >::m_B, and Eigen::KroneckerProductBase< Derived >::rows().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/KroneckerProduct/KroneckerTensorProduct.h