pairinteraction: Eigen::SparseMatrixBase< Derived > Class Template Reference
Eigen::SparseMatrixBase< Derived > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
Base class of any sparse matrices or sparse expressions.
#include <ForwardDeclarations.h>
Data Structures
struct CastXpr
struct ConstFixedBlockXpr
struct ConstFixedSegmentReturnType
struct ConstNColsBlockXpr
struct ConstNRowsBlockXpr
struct ConstSelfAdjointViewReturnType
struct CwiseProductDenseReturnType
struct FixedBlockXpr
struct FixedSegmentReturnType
struct NColsBlockXpr
struct NRowsBlockXpr
struct SelfAdjointViewReturnType
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = RowsAtCompileTime,
MaxColsAtCompileTime = ColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1, Flags = internal::traits<Derived>::Flags,
IsRowMajor = Flags&RowMajorBit ? 1 : 0, InnerSizeAtCompileTime, _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Derived > >, Transpose< const Derived > >::type AdjointReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< const Derived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, const Scalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Derived > Base
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived &>::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived &>::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived &>::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > CwiseInverseReturnType
typedef CwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const Derived, const ConstantReturnType > CwiseScalarEqualReturnType
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
typedef Block< Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< Derived, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const Derived, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
const Derived & derived () const
Derived & derived ()
Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_DEVICE_FUNC NonConstRealReturnType real ()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag ()
template<typename CustomBinaryOp , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const Derived, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const Derived, const OtherDerived > operator && (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const Derived, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const EIGEN_CWISE_BINARY_RETURN_TYPE (Derived, OtherDerived, product) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::equal_to< Scalar >, const Derived, const OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< std::not_equal_to< Scalar >, const Derived, const OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar >, const Derived, const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const Derived, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType cwiseEqual (const Scalar &s) const
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block(Index,Index,Index,Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
EIGEN_DEVICE_FUNC RowsBlockXpr topRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr topRows (Index n) const
This is the const version of topRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr bottomRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr bottomRows (Index n) const
This is the const version of bottomRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr middleRows (Index startRow, Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr middleRows (Index startRow, Index n) const
This is the const version of middleRows(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr leftCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr leftCols (Index n) const
This is the const version of leftCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr rightCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr rightCols (Index n) const
This is the const version of rightCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr middleCols (Index startCol, Index numCols)
EIGEN_DEVICE_FUNC ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
This is the const version of middleCols(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
EIGEN_DEVICE_FUNC SegmentReturnType segment (Index start, Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType segment (Index start, Index n) const
This is the const version of segment(Index,Index).
EIGEN_DEVICE_FUNC SegmentReturnType head (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType head (Index n) const
This is the const version of head(Index).
EIGEN_DEVICE_FUNC SegmentReturnType tail (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType tail (Index n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Derived & markAsRValue ()
SparseMatrixBase ()
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
template<typename OtherDerived >
Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
Derived & operator*= (const Scalar &other)
Derived & operator/= (const Scalar &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<typename OtherDerived >
Derived & operator*= (const SparseMatrixBase< OtherDerived > &other)
template<int Mode>
const TriangularView< const Derived, Mode > triangularView () const
template<unsigned int UpLo>
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<typename OtherDerived >
Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
template<typename OtherDerived >
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Derived >::type eval () const
Scalar sum () const
const SparseView< Derived > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
template<typename OtherDerived >
Derived & assign (const OtherDerived &other)
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Protected Attributes
bool m_isRValue
Friends
std::ostream & operator<< (std::ostream &s, const SparseMatrixBase &m)
template<typename OtherDerived >
const Product< OtherDerived, Derived > operator* (const DiagonalBase< OtherDerived > &lhs, const SparseMatrixBase &rhs)
template<typename OtherDerived >
const Product< OtherDerived, Derived > operator* (const MatrixBase< OtherDerived > &lhs, const SparseMatrixBase &rhs)
Detailed Description
template<typename Derived>
class Eigen::SparseMatrixBase< Derived >
Base class of any sparse matrices or sparse expressions.
Template Parameters
Derived is the derived type, e.g. a sparse matrix type, or an expression, etc.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_SPARSEMATRIXBASE_PLUGIN.
Definition at line 281 of file ForwardDeclarations.h.
Member Typedef Documentation
AdjointReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, Eigen::Transpose<const Derived> >, Transpose<const Derived> >::type Eigen::SparseMatrixBase< Derived >::AdjointReturnType
Definition at line 109 of file SparseMatrixBase.h.
Base
template<typename Derived> typedef EigenBase<Derived> Eigen::SparseMatrixBase< Derived >::Base
Definition at line 143 of file SparseMatrixBase.h.
BlockXpr
template<typename Derived> typedef Block<Derived> Eigen::SparseMatrixBase< Derived >::BlockXpr
Definition at line 33 of file SparseMatrixBase.h.
CoeffReturnType
template<typename Derived> typedef internal::conditional<_HasDirectAccess, const Scalar&, Scalar>::type Eigen::SparseMatrixBase< Derived >::CoeffReturnType
Definition at line 127 of file SparseMatrixBase.h.
ColsBlockXpr
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ColsBlockXpr
Definition at line 21 of file SparseMatrixBase.h.
ColXpr
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ColXpr
Definition at line 15 of file SparseMatrixBase.h.
ConjugateReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type Eigen::SparseMatrixBase< Derived >::ConjugateReturnType
Definition at line 20 of file SparseMatrixBase.h.
ConstantReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< Derived >::ConstantReturnType
Definition at line 130 of file SparseMatrixBase.h.
ConstBlockXpr
template<typename Derived> typedef const Block<const Derived> Eigen::SparseMatrixBase< Derived >::ConstBlockXpr
Definition at line 34 of file SparseMatrixBase.h.
ConstColsBlockXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstColsBlockXpr
Definition at line 22 of file SparseMatrixBase.h.
ConstColXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstColXpr
Definition at line 16 of file SparseMatrixBase.h.
ConstInnerVectorReturnType
template<typename Derived> typedef Block<const Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorReturnType
Definition at line 355 of file SparseMatrixBase.h.
ConstInnerVectorsReturnType
template<typename Derived> typedef Block<const Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorsReturnType
Definition at line 361 of file SparseMatrixBase.h.
ConstRowsBlockXpr
template<typename Derived> typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstRowsBlockXpr
Definition at line 25 of file SparseMatrixBase.h.
ConstRowXpr
template<typename Derived> typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::ConstRowXpr
Definition at line 19 of file SparseMatrixBase.h.
ConstSegmentReturnType
template<typename Derived> typedef const VectorBlock<const Derived> Eigen::SparseMatrixBase< Derived >::ConstSegmentReturnType
Definition at line 40 of file SparseMatrixBase.h.
ConstTransposeReturnType
template<typename Derived> typedef internal::add_const<Transpose<const Derived> >::type Eigen::SparseMatrixBase< Derived >::ConstTransposeReturnType
Definition at line 111 of file SparseMatrixBase.h.
CwiseAbs2ReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseAbs2ReturnType
Definition at line 17 of file SparseMatrixBase.h.
CwiseAbsReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseAbsReturnType
Definition at line 16 of file SparseMatrixBase.h.
CwiseInverseReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseInverseReturnType
Definition at line 20 of file SparseMatrixBase.h.
CwiseScalarEqualReturnType
template<typename Derived> typedef CwiseBinaryOp<internal::scalar_cmp_op<Scalar,Scalar,internal::cmp_EQ>, const Derived, const ConstantReturnType> Eigen::SparseMatrixBase< Derived >::CwiseScalarEqualReturnType
Definition at line 137 of file SparseMatrixBase.h.
CwiseSignReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseSignReturnType
Definition at line 19 of file SparseMatrixBase.h.
CwiseSqrtReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::CwiseSqrtReturnType
Definition at line 18 of file SparseMatrixBase.h.
DenseMatrixType
template<typename Derived> typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< Derived >::DenseMatrixType
type of the equivalent dense matrix
Definition at line 133 of file SparseMatrixBase.h.
ImagReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::ImagReturnType
Definition at line 32 of file SparseMatrixBase.h.
IndexVector
template<typename Derived> typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseMatrixBase< Derived >::IndexVector
Definition at line 51 of file SparseMatrixBase.h.
InnerVectorReturnType
template<typename Derived> typedef Block<Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::InnerVectorReturnType
Definition at line 354 of file SparseMatrixBase.h.
InnerVectorsReturnType
template<typename Derived> typedef Block<Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::InnerVectorsReturnType
Definition at line 360 of file SparseMatrixBase.h.
NegativeReturnType
template<typename Derived> typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> Eigen::SparseMatrixBase< Derived >::NegativeReturnType
Definition at line 36 of file SparseMatrixBase.h.
NonConstImagReturnType
template<typename Derived> typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> Eigen::SparseMatrixBase< Derived >::NonConstImagReturnType
Definition at line 34 of file SparseMatrixBase.h.
NonConstRealReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type Eigen::SparseMatrixBase< Derived >::NonConstRealReturnType
Definition at line 30 of file SparseMatrixBase.h.
PacketReturnType
template<typename Derived> typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits<Scalar>::type >::type Eigen::SparseMatrixBase< Derived >::PacketReturnType
Definition at line 47 of file SparseMatrixBase.h.
PacketScalar
template<typename Derived> typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Derived >::PacketScalar
Definition at line 38 of file SparseMatrixBase.h.
PlainObject
template<typename Derived> typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Derived >::PlainObject
Definition at line 114 of file SparseMatrixBase.h.
RealReturnType
template<typename Derived> typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type Eigen::SparseMatrixBase< Derived >::RealReturnType
Definition at line 25 of file SparseMatrixBase.h.
RealScalar
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Derived >::RealScalar
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
Definition at line 123 of file SparseMatrixBase.h.
RowsBlockXpr
template<typename Derived> typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::RowsBlockXpr
Definition at line 24 of file SparseMatrixBase.h.
RowXpr
template<typename Derived> typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::SparseMatrixBase< Derived >::RowXpr
Definition at line 18 of file SparseMatrixBase.h.
Scalar
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::Scalar
Definition at line 31 of file SparseMatrixBase.h.
ScalarVector
template<typename Derived> typedef Matrix<Scalar,Dynamic,1> Eigen::SparseMatrixBase< Derived >::ScalarVector
Definition at line 52 of file SparseMatrixBase.h.
SegmentReturnType
template<typename Derived> typedef VectorBlock<Derived> Eigen::SparseMatrixBase< Derived >::SegmentReturnType
Definition at line 39 of file SparseMatrixBase.h.
SquareMatrixType
template<typename Derived> typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< Derived >::SquareMatrixType
type of the equivalent square matrix
Definition at line 136 of file SparseMatrixBase.h.
StorageBaseType
template<typename Derived> typedef SparseMatrixBase Eigen::SparseMatrixBase< Derived >::StorageBaseType
Definition at line 49 of file SparseMatrixBase.h.
StorageIndex
template<typename Derived> typedef internal::traits<Derived>::StorageIndex Eigen::SparseMatrixBase< Derived >::StorageIndex
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
Definition at line 43 of file SparseMatrixBase.h.
StorageKind
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::SparseMatrixBase< Derived >::StorageKind
Definition at line 39 of file SparseMatrixBase.h.
TransposeReturnType
template<typename Derived> typedef Transpose<Derived> Eigen::SparseMatrixBase< Derived >::TransposeReturnType
Definition at line 110 of file SparseMatrixBase.h.
value_type
template<typename Derived> typedef Scalar Eigen::SparseMatrixBase< Derived >::value_type
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Definition at line 36 of file SparseMatrixBase.h.
Member Enumeration Documentation
anonymous enum
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxSizeAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
InnerSizeAtCompileTime
_HasDirectAccess
Definition at line 57 of file SparseMatrixBase.h.
Constructor & Destructor Documentation
SparseMatrixBase()
template<typename Derived> Eigen::SparseMatrixBase< Derived >::SparseMatrixBase () inline
Definition at line 192 of file SparseMatrixBase.h.
Member Function Documentation
adjoint()
template<typename Derived> const AdjointReturnType Eigen::SparseMatrixBase< Derived >::adjoint () const inline
Definition at line 351 of file SparseMatrixBase.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), Hamiltonianmatrix::applyCutoff(), SystemBase< StateTwo >::applyRightsideTransformator(), Hamiltonianmatrix::changeBasis(), Hamiltonianmatrix::getBlock(), SystemBase< StateTwo >::getHamiltonianentry(), SystemTwo::initializeInteraction(), SystemOne::initializeInteraction(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate(), Hamiltonianmatrix::removeUnnecessaryBasisvectors(), SystemBase< StateTwo >::setHamiltonianentry(), SystemTwo::transformInteraction(), and SystemOne::transformInteraction().
assign()
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::assign (const OtherDerived & other) inline protected
assignGeneric()
template<typename Derived> template<typename OtherDerived > void Eigen::SparseMatrixBase< Derived >::assignGeneric (const OtherDerived & other) inline protected
binaryExpr()
template<typename Derived> template<typename CustomBinaryOp , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
Output:
See also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
Definition at line 44 of file SparseMatrixBase.h.
block() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Definition at line 65 of file SparseMatrixBase.h.
block() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block(Index,Index,Index,Index). */.
Definition at line 72 of file SparseMatrixBase.h.
block() [3/6]
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
class Block, block(Index,Index,Index,Index)
Definition at line 781 of file SparseMatrixBase.h.
block() [4/6]
template<typename Derived> template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). */.
Definition at line 789 of file SparseMatrixBase.h.
block() [5/6]
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block in *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 816 of file SparseMatrixBase.h.
block() [6/6]
template<typename Derived> template<int NRows, int NCols> const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::SparseMatrixBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
Definition at line 824 of file SparseMatrixBase.h.
blueNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::blueNorm () const inline
Definition at line 92 of file SparseDot.h.
bottomLeftCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 349 of file SparseMatrixBase.h.
bottomLeftCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner(Index, Index).
Definition at line 356 of file SparseMatrixBase.h.
bottomLeftCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 374 of file SparseMatrixBase.h.
bottomLeftCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
Definition at line 382 of file SparseMatrixBase.h.
bottomLeftCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 407 of file SparseMatrixBase.h.
bottomLeftCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
Definition at line 414 of file SparseMatrixBase.h.
bottomRightCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::SparseMatrixBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 264 of file SparseMatrixBase.h.
bottomRightCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::SparseMatrixBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner(Index, Index).
Definition at line 271 of file SparseMatrixBase.h.
bottomRightCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 289 of file SparseMatrixBase.h.
bottomRightCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
Definition at line 297 of file SparseMatrixBase.h.
bottomRightCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 322 of file SparseMatrixBase.h.
bottomRightCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
Definition at line 329 of file SparseMatrixBase.h.
bottomRows() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC RowsBlockXpr Eigen::SparseMatrixBase< Derived >::bottomRows (Index n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 489 of file SparseMatrixBase.h.
bottomRows() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowsBlockXpr Eigen::SparseMatrixBase< Derived >::bottomRows (Index n) const inline
This is the const version of bottomRows(Index).
Definition at line 496 of file SparseMatrixBase.h.
bottomRows() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 518 of file SparseMatrixBase.h.
bottomRows() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
Definition at line 526 of file SparseMatrixBase.h.
cast()
template<typename Derived> template<typename NewType > EIGEN_DEVICE_FUNC CastXpr<NewType>::Type Eigen::SparseMatrixBase< Derived >::cast () const inline
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
Definition at line 63 of file SparseMatrixBase.h.
col() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC ColXpr Eigen::SparseMatrixBase< Derived >::col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
Definition at line 839 of file SparseMatrixBase.h.
Referenced by Eigen::SPQR< _MatrixType >::compute(), and Eigen::internal::generic_product_impl< MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct >::scaleAndAddTo().
col() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColXpr Eigen::SparseMatrixBase< Derived >::col (Index i) const inline
This is the const version of col().
Definition at line 846 of file SparseMatrixBase.h.
cols()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::cols (void) const inline
Returns
the number of columns.
See also
rows()
Definition at line 173 of file SparseMatrixBase.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isVector(), Eigen::SparseMatrix< scalar_t >::operator=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::outerSize(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner().
conjugate()
template<typename Derived> EIGEN_DEVICE_FUNC ConjugateReturnType Eigen::SparseMatrixBase< Derived >::conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
Definition at line 75 of file SparseMatrixBase.h.
const_cast_derived()
template<typename Derived> Derived& Eigen::SparseMatrixBase< Derived >::const_cast_derived () const inline
Definition at line 140 of file SparseMatrixBase.h.
Referenced by Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< scalar_t >::operator=(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), and Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref().
convert_index()
template<typename Derived> static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static protected
Definition at line 396 of file SparseMatrixBase.h.
cwiseAbs()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType Eigen::SparseMatrixBase< Derived >::cwiseAbs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
cwiseAbs2()
Definition at line 33 of file SparseMatrixBase.h.
Referenced by Hamiltonianmatrix::abs().
cwiseAbs2()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType Eigen::SparseMatrixBase< Derived >::cwiseAbs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
cwiseAbs()
Definition at line 46 of file SparseMatrixBase.h.
cwiseEqual() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::equal_to<Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
Definition at line 44 of file SparseMatrixBase.h.
cwiseEqual() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseScalarEqualReturnType Eigen::SparseMatrixBase< Derived >::cwiseEqual (const Scalar & s) const inline
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See also
cwiseEqual(const MatrixBase<OtherDerived> &) const
Definition at line 150 of file SparseMatrixBase.h.
cwiseInverse()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseInverseReturnType Eigen::SparseMatrixBase< Derived >::cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
cwiseProduct()
Definition at line 84 of file SparseMatrixBase.h.
cwiseMax() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Output:
See also
class CwiseBinaryOp, min()
Definition at line 105 of file SparseMatrixBase.h.
cwiseMax() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::SparseMatrixBase< Derived >::cwiseMax (const Scalar & other) const inline
Returns
an expression of the coefficient-wise max of *this and scalar other
See also
class CwiseBinaryOp, min()
Definition at line 116 of file SparseMatrixBase.h.
cwiseMin() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Output:
See also
class CwiseBinaryOp, max()
Definition at line 79 of file SparseMatrixBase.h.
Referenced by BOOST_AUTO_TEST_CASE().
cwiseMin() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar>, const Derived, const ConstantReturnType> Eigen::SparseMatrixBase< Derived >::cwiseMin (const Scalar & other) const inline
Returns
an expression of the coefficient-wise min of *this and scalar other
See also
class CwiseBinaryOp, min()
Definition at line 90 of file SparseMatrixBase.h.
cwiseNotEqual()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
Output:
See also
cwiseEqual(), isApprox(), isMuchSmallerThan()
Definition at line 64 of file SparseMatrixBase.h.
cwiseProduct() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE const CwiseProductDenseReturnType<OtherDerived>::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::cwiseProduct().
cwiseProduct() [2/2]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase<Derived>::template CwiseProductDenseReturnType<OtherDerived>::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const
Definition at line 691 of file SparseCwiseBinaryOp.h.
cwiseQuotient()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
Definition at line 132 of file SparseMatrixBase.h.
cwiseSign()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSignReturnType Eigen::SparseMatrixBase< Derived >::cwiseSign () const inline
Returns
an expression of the coefficient-wise signum of *this.
Example:
Output:
Definition at line 70 of file SparseMatrixBase.h.
cwiseSqrt()
template<typename Derived> EIGEN_DEVICE_FUNC const CwiseSqrtReturnType Eigen::SparseMatrixBase< Derived >::cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See also
cwisePow(), cwiseSquare()
Definition at line 59 of file SparseMatrixBase.h.
derived() [1/2]
template<typename Derived> const Derived& Eigen::SparseMatrixBase< Derived >::derived () const inline
Definition at line 138 of file SparseMatrixBase.h.
Referenced by Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::_solve_impl(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::_solve_impl(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::dot(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), eiToDense(), eiToGmm(), eiToMtl(), eiToUblas(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isApprox(), main(), Eigen::SluMatrix::Map(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::markAsRValue(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), Eigen::operator+(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator+=(), Eigen::operator-(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator-=(), Eigen::internal::sparse_matrix_block_impl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols >::operator=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< scalar_t >::operator=(), Eigen::Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), Eigen::SparseQR< _MatrixType, _OrderingType >::solve(), Eigen::SparseMatrix< scalar_t >::SparseMatrix(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::toDense(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::transpose(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
derived() [2/2]
template<typename Derived> Derived& Eigen::SparseMatrixBase< Derived >::derived () inline
Definition at line 139 of file SparseMatrixBase.h.
dot() [1/4]
template<typename Derived> template<typename OtherDerived > internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
Definition at line 18 of file SparseDot.h.
dot() [2/4]
template<typename Derived> template<typename OtherDerived > internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const
Definition at line 43 of file SparseDot.h.
dot() [3/4]
template<typename Derived> template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
dot() [4/4]
template<typename Derived> template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const
EIGEN_CWISE_BINARY_RETURN_TYPE()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::SparseMatrixBase< Derived >::EIGEN_CWISE_BINARY_RETURN_TYPE (Derived , OtherDerived , product) const & inline
Returns
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Output:
See also
class CwiseBinaryOp, cwiseAbs2
Definition at line 23 of file SparseMatrixBase.h.
eval()
template<typename Derived> const internal::eval<Derived>::type Eigen::SparseMatrixBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Definition at line 384 of file SparseMatrixBase.h.
head() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC SegmentReturnType Eigen::SparseMatrixBase< Derived >::head (Index n) inline
Returns
a dynamic-size expression of the first coefficients of *this.
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Definition at line 920 of file SparseMatrixBase.h.
head() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstSegmentReturnType Eigen::SparseMatrixBase< Derived >::head (Index n) const inline
This is the const version of head(Index).
Definition at line 928 of file SparseMatrixBase.h.
head() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 1014 of file SparseMatrixBase.h.
head() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::head (Index n = N) const inline
This is the const version of head<int>().
Definition at line 1023 of file SparseMatrixBase.h.
imag() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC const ImagReturnType Eigen::SparseMatrixBase< Derived >::imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
Definition at line 96 of file SparseMatrixBase.h.
imag() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC NonConstImagReturnType Eigen::SparseMatrixBase< Derived >::imag () inline
Returns
a non const expression of the imaginary part of *this.
See also
real()
Definition at line 164 of file SparseMatrixBase.h.
innerSize()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::innerSize () const inline
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
Definition at line 187 of file SparseMatrixBase.h.
innerVector() [1/2]
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer)
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
Definition at line 333 of file SparseBlock.h.
innerVector() [2/2]
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer) const
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
Definition at line 340 of file SparseBlock.h.
innerVectors() [1/2]
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize)
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
Definition at line 348 of file SparseBlock.h.
innerVectors() [2/2]
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize) const
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
Definition at line 361 of file SparseBlock.h.
isApprox() [1/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Definition at line 17 of file SparseFuzzy.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::toDense().
isApprox() [2/2]
template<typename Derived> template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline
Definition at line 375 of file SparseMatrixBase.h.
isRValue()
template<typename Derived> bool Eigen::SparseMatrixBase< Derived >::isRValue () const inline
Definition at line 189 of file SparseMatrixBase.h.
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseMatrix< scalar_t >::operator=().
isVector()
template<typename Derived> bool Eigen::SparseMatrixBase< Derived >::isVector () const inline
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
Definition at line 181 of file SparseMatrixBase.h.
leftCols() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC ColsBlockXpr Eigen::SparseMatrixBase< Derived >::leftCols (Index n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 603 of file SparseMatrixBase.h.
leftCols() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColsBlockXpr Eigen::SparseMatrixBase< Derived >::leftCols (Index n) const inline
This is the const version of leftCols(Index).
Definition at line 610 of file SparseMatrixBase.h.
leftCols() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 632 of file SparseMatrixBase.h.
leftCols() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
Definition at line 640 of file SparseMatrixBase.h.
markAsRValue()
template<typename Derived> Derived& Eigen::SparseMatrixBase< Derived >::markAsRValue () inline
Definition at line 190 of file SparseMatrixBase.h.
Referenced by Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >::run().
middleCols() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC ColsBlockXpr Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, Index numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 716 of file SparseMatrixBase.h.
middleCols() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColsBlockXpr Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, Index numCols) const inline
This is the const version of middleCols(Index,Index).
Definition at line 723 of file SparseMatrixBase.h.
middleCols() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 746 of file SparseMatrixBase.h.
middleCols() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
Definition at line 754 of file SparseMatrixBase.h.
middleRows() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC RowsBlockXpr Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, Index n) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 546 of file SparseMatrixBase.h.
middleRows() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowsBlockXpr Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, Index n) const inline
This is the const version of middleRows(Index,Index).
Definition at line 553 of file SparseMatrixBase.h.
middleRows() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 576 of file SparseMatrixBase.h.
middleRows() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
Definition at line 584 of file SparseMatrixBase.h.
norm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::norm () const inline
Definition at line 84 of file SparseDot.h.
operator &&()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_and_op, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean and operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator||(), select()
Definition at line 92 of file SparseMatrixBase.h.
operator*() [1/3]
template<typename Derived> template<typename OtherDerived > const Product<Derived,OtherDerived> Eigen::SparseMatrixBase< Derived >::operator* (const DiagonalBase< OtherDerived > & other) const inline
Definition at line 297 of file SparseMatrixBase.h.
operator*() [2/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Derived >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
Definition at line 29 of file SparseProduct.h.
operator*() [3/3]
template<typename Derived> template<typename OtherDerived > const Product<Derived,OtherDerived> Eigen::SparseMatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const inline
Definition at line 314 of file SparseMatrixBase.h.
operator*=() [1/2]
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const Scalar & other)
Definition at line 124 of file SparseCwiseUnaryOp.h.
operator*=() [2/2]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator*= (const SparseMatrixBase< OtherDerived > & other)
operator+=() [1/4]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other)
operator+=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const DiagonalBase< OtherDerived > & other)
Definition at line 674 of file SparseCwiseBinaryOp.h.
operator+=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
Definition at line 642 of file SparseCwiseBinaryOp.h.
operator+=() [4/4]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other)
Definition at line 667 of file SparseCwiseBinaryOp.h.
operator-()
template<typename Derived> EIGEN_DEVICE_FUNC const NegativeReturnType Eigen::SparseMatrixBase< Derived >::operator- () const inline
Returns
an expression of the opposite of *this
Definition at line 46 of file SparseMatrixBase.h.
operator-=() [1/4]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other)
operator-=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const DiagonalBase< OtherDerived > & other)
Definition at line 682 of file SparseCwiseBinaryOp.h.
operator-=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
Definition at line 650 of file SparseCwiseBinaryOp.h.
operator-=() [4/4]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other)
Definition at line 659 of file SparseCwiseBinaryOp.h.
operator/=()
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator/= (const Scalar & other)
Definition at line 136 of file SparseCwiseUnaryOp.h.
operator=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Definition at line 17 of file SparseAssign.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::SparseMatrixBase().
operator=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
Definition at line 25 of file SparseAssign.h.
operator=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
Definition at line 34 of file SparseAssign.h.
operator=() [4/4]
template<typename Derived> Derived & Eigen::SparseMatrixBase< Derived >::operator= (const Derived & other) inline
Definition at line 43 of file SparseAssign.h.
operator||()
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_or_op, const Derived, const OtherDerived> Eigen::SparseMatrixBase< Derived >::operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean or operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator&&(), select()
Definition at line 111 of file SparseMatrixBase.h.
outerSize()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::outerSize () const inline
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
Definition at line 184 of file SparseMatrixBase.h.
pruned()
template<typename Derived > const SparseView< Derived > Eigen::SparseMatrixBase< Derived >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
Definition at line 245 of file SparseView.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval().
real() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC RealReturnType Eigen::SparseMatrixBase< Derived >::real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
Definition at line 87 of file SparseMatrixBase.h.
real() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC NonConstRealReturnType Eigen::SparseMatrixBase< Derived >::real () inline
Returns
a non const expression of the real part of *this.
See also
imag()
Definition at line 155 of file SparseMatrixBase.h.
rightCols() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC ColsBlockXpr Eigen::SparseMatrixBase< Derived >::rightCols (Index n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 659 of file SparseMatrixBase.h.
rightCols() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColsBlockXpr Eigen::SparseMatrixBase< Derived >::rightCols (Index n) const inline
This is the const version of rightCols(Index).
Definition at line 666 of file SparseMatrixBase.h.
rightCols() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 688 of file SparseMatrixBase.h.
rightCols() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
Definition at line 696 of file SparseMatrixBase.h.
row() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC RowXpr Eigen::SparseMatrixBase< Derived >::row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
Definition at line 860 of file SparseMatrixBase.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner().
row() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowXpr Eigen::SparseMatrixBase< Derived >::row (Index i) const inline
This is the const version of row(). */.
Definition at line 867 of file SparseMatrixBase.h.
rows()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::rows (void) const inline
Returns
the number of rows.
See also
cols()
Definition at line 171 of file SparseMatrixBase.h.
Referenced by Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isVector(), Eigen::SparseMatrix< scalar_t >::operator=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::outerSize(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size(), Eigen::SparseSolverBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), Eigen::SparseQR< _MatrixType, _OrderingType >::solve(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner().
segment() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC SegmentReturnType Eigen::SparseMatrixBase< Derived >::segment (Index start, Index n) inline
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, segment(Index)
Definition at line 889 of file SparseMatrixBase.h.
Referenced by Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), and Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >::run().
segment() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstSegmentReturnType Eigen::SparseMatrixBase< Derived >::segment (Index start, Index n) const inline
This is the const version of segment(Index,Index).
Definition at line 898 of file SparseMatrixBase.h.
segment() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 982 of file SparseMatrixBase.h.
segment() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
Definition at line 991 of file SparseMatrixBase.h.
selfadjointView() [1/4]
template<typename Derived> template<unsigned int UpLo> SparseMatrixBase<Derived>::template ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const
Definition at line 175 of file SparseSelfAdjointView.h.
selfadjointView() [2/4]
template<typename Derived> template<unsigned int UpLo> SparseMatrixBase<Derived>::template SelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView ()
Definition at line 182 of file SparseSelfAdjointView.h.
selfadjointView() [3/4]
template<typename Derived> template<unsigned int UpLo> ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inline
selfadjointView() [4/4]
template<typename Derived> template<unsigned int UpLo> SelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inline
size()
template<typename Derived> Index Eigen::SparseMatrixBase< Derived >::size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
Definition at line 176 of file SparseMatrixBase.h.
Referenced by SystemBase< StateTwo >::add(), SystemBase< StateTwo >::applyLeftsideTransformator(), SystemBase< StateTwo >::applyRightsideTransformator(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::dot(), SystemBase< StateTwo >::onParameterChange(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=().
squaredNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::squaredNorm () const inline
Definition at line 77 of file SparseDot.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isApprox().
sum()
template<typename Derived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::sum () const
Definition at line 17 of file SparseRedux.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval().
tail() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC SegmentReturnType Eigen::SparseMatrixBase< Derived >::tail (Index n) inline
Returns
a dynamic-size expression of the last coefficients of *this.
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Definition at line 950 of file SparseMatrixBase.h.
tail() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstSegmentReturnType Eigen::SparseMatrixBase< Derived >::tail (Index n) const inline
This is the const version of tail(Index).
Definition at line 958 of file SparseMatrixBase.h.
tail() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 1046 of file SparseMatrixBase.h.
tail() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::SparseMatrixBase< Derived >::tail (Index n = N) const inline
This is the const version of tail<int>.
Definition at line 1055 of file SparseMatrixBase.h.
toDense()
template<typename Derived> DenseMatrixType Eigen::SparseMatrixBase< Derived >::toDense () const inline
Definition at line 365 of file SparseMatrixBase.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isApprox(), and Eigen::test_relative_error().
topLeftCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::SparseMatrixBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 179 of file SparseMatrixBase.h.
topLeftCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::SparseMatrixBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner(Index, Index).
Definition at line 186 of file SparseMatrixBase.h.
topLeftCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 204 of file SparseMatrixBase.h.
topLeftCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
Definition at line 212 of file SparseMatrixBase.h.
topLeftCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 237 of file SparseMatrixBase.h.
topLeftCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
Definition at line 244 of file SparseMatrixBase.h.
topRightCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::SparseMatrixBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 93 of file SparseMatrixBase.h.
topRightCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::SparseMatrixBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner(Index, Index).
Definition at line 100 of file SparseMatrixBase.h.
topRightCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
See also
class Block, block<int,int>(Index,Index)
Definition at line 119 of file SparseMatrixBase.h.
topRightCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
Definition at line 127 of file SparseMatrixBase.h.
topRightCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 152 of file SparseMatrixBase.h.
topRightCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::SparseMatrixBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
Definition at line 159 of file SparseMatrixBase.h.
topRows() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC RowsBlockXpr Eigen::SparseMatrixBase< Derived >::topRows (Index n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 433 of file SparseMatrixBase.h.
topRows() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowsBlockXpr Eigen::SparseMatrixBase< Derived >::topRows (Index n) const inline
This is the const version of topRows(Index).
Definition at line 440 of file SparseMatrixBase.h.
topRows() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 462 of file SparseMatrixBase.h.
topRows() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::SparseMatrixBase< Derived >::topRows (Index n = N) const inline
This is the const version of topRows<int>().
Definition at line 470 of file SparseMatrixBase.h.
transpose() [1/2]
template<typename Derived> TransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () inline
Definition at line 349 of file SparseMatrixBase.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::adjoint(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::analyzePattern(), SystemBase< StateTwo >::getConnections(), and main().
transpose() [2/2]
template<typename Derived> const ConstTransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () const inline
Definition at line 350 of file SparseMatrixBase.h.
triangularView()
template<typename Derived > template<int Mode> const TriangularView< const Derived, Mode > Eigen::SparseMatrixBase< Derived >::triangularView () const inline
Definition at line 182 of file SparseTriangularView.h.
twistedBy()
template<typename Derived> SparseSymmetricPermutationProduct<Derived,Upper|Lower> Eigen::SparseMatrixBase< Derived >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline
Returns
an expression of P H P^-1 where H is the matrix represented by *this
Definition at line 324 of file SparseMatrixBase.h.
Referenced by Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), and Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::ordering().
unaryExpr()
template<typename Derived> template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp<CustomUnaryOp, const Derived> Eigen::SparseMatrixBase< Derived >::unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
Definition at line 122 of file SparseMatrixBase.h.
unaryViewExpr()
template<typename Derived> template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView<CustomViewOp, const Derived> Eigen::SparseMatrixBase< Derived >::unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See also
unaryExpr, binaryExpr class CwiseUnaryOp
Definition at line 143 of file SparseMatrixBase.h.
Friends And Related Function Documentation
operator* [1/2]
template<typename Derived> template<typename OtherDerived > const Product<OtherDerived,Derived> operator* (const DiagonalBase< OtherDerived > & lhs, const SparseMatrixBase< Derived > & rhs) friend
Definition at line 303 of file SparseMatrixBase.h.
operator* [2/2]
template<typename Derived> template<typename OtherDerived > const Product<OtherDerived,Derived> operator* (const MatrixBase< OtherDerived > & lhs, const SparseMatrixBase< Derived > & rhs) friend
Definition at line 320 of file SparseMatrixBase.h.
operator<<
template<typename Derived> std::ostream& operator<< (std::ostream & s, const SparseMatrixBase< Derived > & m) friend
Definition at line 213 of file SparseMatrixBase.h.
Field Documentation
m_isRValue
template<typename Derived> bool Eigen::SparseMatrixBase< Derived >::m_isRValue protected
Definition at line 394 of file SparseMatrixBase.h.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isRValue(), and Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::markAsRValue().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseMatrixBase.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseAssign.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseBlock.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseCwiseBinaryOp.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseCwiseUnaryOp.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseDot.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseFuzzy.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseProduct.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseRedux.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseTriangularView.h
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseView.h