pairinteraction: Eigen::IncompleteLU< _Scalar > Class Template Reference
Eigen::IncompleteLU< _Scalar > Class Template Reference
#include <IncompleteLU.h>
Public Types
typedef Matrix< Scalar, Dynamic, Dynamic > MatrixType
Public Member Functions
IncompleteLU ()
template<typename MatrixType >
IncompleteLU (const MatrixType &mat)
Index rows () const
Index cols () const
template<typename MatrixType >
IncompleteLU & compute (const MatrixType &mat)
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
Public Member Functions inherited from Eigen::SparseSolverBase< IncompleteLU< _Scalar > >
SparseSolverBase ()
~SparseSolverBase ()
IncompleteLU< _Scalar > & derived ()
const IncompleteLU< _Scalar > & derived () const
const Solve< IncompleteLU< _Scalar >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< IncompleteLU< _Scalar >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< IncompleteLU< _Scalar > > Base
typedef _Scalar Scalar
typedef Matrix< Scalar, Dynamic, 1 > Vector
typedef Vector::Index Index
typedef SparseMatrix< Scalar, RowMajor > FactorType
Protected Attributes
FactorType m_lu
Protected Attributes inherited from Eigen::SparseSolverBase< IncompleteLU< _Scalar > >
bool m_isInitialized
Detailed Description
template<typename _Scalar>
class Eigen::IncompleteLU< _Scalar >
Definition at line 16 of file IncompleteLU.h.
Member Typedef Documentation
Base
template<typename _Scalar > typedef SparseSolverBase<IncompleteLU<_Scalar> > Eigen::IncompleteLU< _Scalar >::Base protected
Definition at line 19 of file IncompleteLU.h.
FactorType
template<typename _Scalar > typedef SparseMatrix<Scalar,RowMajor> Eigen::IncompleteLU< _Scalar >::FactorType protected
Definition at line 25 of file IncompleteLU.h.
Index
template<typename _Scalar > typedef Vector::Index Eigen::IncompleteLU< _Scalar >::Index protected
Definition at line 24 of file IncompleteLU.h.
MatrixType
template<typename _Scalar > typedef Matrix<Scalar,Dynamic,Dynamic> Eigen::IncompleteLU< _Scalar >::MatrixType
Definition at line 28 of file IncompleteLU.h.
Scalar
template<typename _Scalar > typedef _Scalar Eigen::IncompleteLU< _Scalar >::Scalar protected
Definition at line 22 of file IncompleteLU.h.
Vector
template<typename _Scalar > typedef Matrix<Scalar,Dynamic,1> Eigen::IncompleteLU< _Scalar >::Vector protected
Definition at line 23 of file IncompleteLU.h.
Constructor & Destructor Documentation
IncompleteLU() [1/2]
template<typename _Scalar > Eigen::IncompleteLU< _Scalar >::IncompleteLU () inline
Definition at line 30 of file IncompleteLU.h.
IncompleteLU() [2/2]
template<typename _Scalar > template<typename MatrixType > Eigen::IncompleteLU< _Scalar >::IncompleteLU (const MatrixType & mat) inline
Definition at line 33 of file IncompleteLU.h.
References Eigen::IncompleteLU< _Scalar >::compute().
Member Function Documentation
_solve_impl()
template<typename _Scalar > template<typename Rhs , typename Dest > void Eigen::IncompleteLU< _Scalar >::_solve_impl (const Rhs & b, Dest & x) const inline
Definition at line 78 of file IncompleteLU.h.
References Eigen::IncompleteLU< _Scalar >::m_lu, and Eigen::SparseSolverBase< IncompleteLU< _Scalar > >::solve().
cols()
template<typename _Scalar > Index Eigen::IncompleteLU< _Scalar >::cols (void) const inline
Definition at line 39 of file IncompleteLU.h.
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), and Eigen::IncompleteLU< _Scalar >::m_lu.
compute()
template<typename _Scalar > template<typename MatrixType > IncompleteLU& Eigen::IncompleteLU< _Scalar >::compute (const MatrixType & mat) inline
Definition at line 42 of file IncompleteLU.h.
References Eigen::PlainObjectBase< Derived >::cols(), i, Eigen::SparseSolverBase< IncompleteLU< _Scalar > >::m_isInitialized, Eigen::IncompleteLU< _Scalar >::m_lu, mat, and size.
Referenced by Eigen::IncompleteLU< _Scalar >::IncompleteLU().
rows()
template<typename _Scalar > Index Eigen::IncompleteLU< _Scalar >::rows (void) const inline
Definition at line 38 of file IncompleteLU.h.
References Eigen::IncompleteLU< _Scalar >::m_lu, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
Field Documentation
m_lu
template<typename _Scalar > FactorType Eigen::IncompleteLU< _Scalar >::m_lu protected
Definition at line 85 of file IncompleteLU.h.
Referenced by Eigen::IncompleteLU< _Scalar >::_solve_impl(), Eigen::IncompleteLU< _Scalar >::cols(), Eigen::IncompleteLU< _Scalar >::compute(), and Eigen::IncompleteLU< _Scalar >::rows().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/IterativeSolvers/IncompleteLU.h