pairinteraction: MatrixElements Class Reference
MatrixElements Class Reference
#include <MatrixElements.h>
Public Member Functions
MatrixElements (std::string const &species, std::string const &dbname)
MatrixElements (const Configuration &config, std::string const &species, std::string const &dbname)
void precalculateElectricMomentum (std::shared_ptr< const BasisnamesOne > basis_one, int q)
void precalculateMagneticMomentum (std::shared_ptr< const BasisnamesOne > basis_one, int q)
void precalculateDiamagnetism (std::shared_ptr< const BasisnamesOne > basis_one, int k, int q)
void precalculateMultipole (std::shared_ptr< const BasisnamesOne > basis_one, int k)
void precalculateRadial (std::shared_ptr< const BasisnamesOne > basis_one, int k)
double getElectricMomentum (StateOne const &state_row, StateOne const &state_col)
double getMagneticMomentum (StateOne const &state_row, StateOne const &state_col)
double getDiamagnetism (StateOne const &state_row, StateOne const &state_col, int kappa)
double getMultipole (StateOne const &state_row, StateOne const &state_col, int kappa)
double getRadial (StateOne const &state_row, StateOne const &state_col, int kappa)
void precalculateElectricMomentum (const std::vector< StateOne > &basis_one, int q)
void precalculateMagneticMomentum (const std::vector< StateOne > &basis_one, int q)
void precalculateDiamagnetism (const std::vector< StateOne > &basis_one, int k, int q)
void precalculateMultipole (const std::vector< StateOne > &basis_one, int k)
void precalculateRadial (const std::vector< StateOne > &basis_one, int k)
Detailed Description
Definition at line 35 of file MatrixElements.h.
Constructor & Destructor Documentation
MatrixElements() [1/2]
MatrixElements::MatrixElements (std::string const & species, std::string const & dbname)
Definition at line 60 of file MatrixElements.cpp.
MatrixElements() [2/2]
MatrixElements::MatrixElements (const Configuration & config, std::string const & species, std::string const & dbname)
Definition at line 67 of file MatrixElements.cpp.
Member Function Documentation
getDiamagnetism()
double MatrixElements::getDiamagnetism (StateOne const & state_row, StateOne const & state_col, int kappa)
Definition at line 113 of file MatrixElements.cpp.
References inverse_electron_rest_mass, StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
Referenced by HamiltonianOne::build().
getElectricMomentum()
double MatrixElements::getElectricMomentum (StateOne const & state_row, StateOne const & state_col)
Definition at line 99 of file MatrixElements.cpp.
References getMultipole().
Referenced by HamiltonianOne::build().
getMagneticMomentum()
double MatrixElements::getMagneticMomentum (StateOne const & state_row, StateOne const & state_col)
Definition at line 103 of file MatrixElements.cpp.
References au2G, au2GHz, StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
Referenced by HamiltonianOne::build().
getMultipole()
double MatrixElements::getMultipole (StateOne const & state_row, StateOne const & state_col, int kappa)
Definition at line 121 of file MatrixElements.cpp.
References StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
Referenced by HamiltonianTwo::calculate(), getElectricMomentum(), and SystemTwo::initializeInteraction().
getRadial()
double MatrixElements::getRadial (StateOne const & state_row, StateOne const & state_col, int kappa)
Definition at line 129 of file MatrixElements.cpp.
References StateOne::j, StateTwo::j, StateOne::l, StateTwo::l, StateTwo::m, StateOne::n, StateTwo::n, sqlite::statement::prepare(), StateTwo::second(), selectionRulesMomentum(), and selectionRulesMultipole().
precalculateDiamagnetism() [1/2]
void MatrixElements::precalculateDiamagnetism (std::shared_ptr< const BasisnamesOne > basis_one, int k, int q)
Definition at line 95 of file MatrixElements.cpp.
Referenced by HamiltonianOne::build().
precalculateDiamagnetism() [2/2]
void MatrixElements::precalculateDiamagnetism (const std::vector< StateOne > & basis_one, int k, int q)
Definition at line 519 of file MatrixElements.cpp.
References sqlite::statement::bind(), sqlite::statement::exec(), sqlite::statement::get(), sqlite::statement::prepare(), sqlite::statement::reset(), selectionRulesMomentum(), selectionRulesMultipole(), sqlite::statement::set(), and sqlite::statement::step().
precalculateElectricMomentum() [1/2]
void MatrixElements::precalculateElectricMomentum (std::shared_ptr< const BasisnamesOne > basis_one, int q)
Definition at line 87 of file MatrixElements.cpp.
Referenced by HamiltonianOne::build().
precalculateElectricMomentum() [2/2]
void MatrixElements::precalculateElectricMomentum (const std::vector< StateOne > & basis_one, int q)
Definition at line 511 of file MatrixElements.cpp.
precalculateMagneticMomentum() [1/2]
void MatrixElements::precalculateMagneticMomentum (std::shared_ptr< const BasisnamesOne > basis_one, int q)
Definition at line 91 of file MatrixElements.cpp.
Referenced by HamiltonianOne::build().
precalculateMagneticMomentum() [2/2]
void MatrixElements::precalculateMagneticMomentum (const std::vector< StateOne > & basis_one, int q)
Definition at line 515 of file MatrixElements.cpp.
precalculateMultipole() [1/2]
void MatrixElements::precalculateMultipole (std::shared_ptr< const BasisnamesOne > basis_one, int k)
Definition at line 77 of file MatrixElements.cpp.
Referenced by HamiltonianTwo::calculate(), and SystemTwo::initializeInteraction().
precalculateMultipole() [2/2]
void MatrixElements::precalculateMultipole (const std::vector< StateOne > & basis_one, int k)
Definition at line 501 of file MatrixElements.cpp.
precalculateRadial() [1/2]
void MatrixElements::precalculateRadial (std::shared_ptr< const BasisnamesOne > basis_one, int k)
Definition at line 82 of file MatrixElements.cpp.
precalculateRadial() [2/2]
void MatrixElements::precalculateRadial (const std::vector< StateOne > & basis_one, int k)
Definition at line 506 of file MatrixElements.cpp.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/MatrixElements.h
/travis/libpairinteraction/MatrixElements.cpp