pairinteraction: Portable_Timer Class Reference
Portable_Timer Class Reference
#include <portable_timer.hh>
Public Member Functions
Portable_Timer ()
Portable_Timer (int clkid)
void start ()
void stop ()
double elapsed ()
double user_time ()
Detailed Description
Definition at line 139 of file portable_timer.hh.
Constructor & Destructor Documentation
Portable_Timer() [1/2]
Portable_Timer::Portable_Timer () inline
Definition at line 143 of file portable_timer.hh.
References BtlConfig::Instance, and BtlConfig::realclock.
Portable_Timer() [2/2]
Portable_Timer::Portable_Timer (int clkid) inline
Definition at line 148 of file portable_timer.hh.
Member Function Documentation
elapsed()
double Portable_Timer::elapsed () inline
Definition at line 167 of file portable_timer.hh.
References user_time().
start()
void Portable_Timer::start () inline
Definition at line 151 of file portable_timer.hh.
References e().
Referenced by Action_lu_solve< Interface >::calculate(), Portable_Perf_Analyzer< Action >::time_calculate(), and Portable_Perf_Analyzer< Action >::time_init().
stop()
void Portable_Timer::stop () inline
Definition at line 159 of file portable_timer.hh.
References e().
Referenced by Action_lu_solve< Interface >::calculate(), Portable_Perf_Analyzer< Action >::time_calculate(), and Portable_Perf_Analyzer< Action >::time_init().
user_time()
double Portable_Timer::user_time () inline
Definition at line 172 of file portable_timer.hh.
Referenced by Action_lu_solve< Interface >::calculate(), elapsed(), Portable_Perf_Analyzer< Action >::time_calculate(), and Portable_Perf_Analyzer< Action >::time_init().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/timers/portable_timer.hh