pairinteraction: Action_axpy< Interface > Class Template Reference
Action_axpy< Interface > Class Template Reference
#include <action_axpy.hh>
Public Member Functions
Action_axpy (int size)
Action_axpy (const Action_axpy &)
~Action_axpy (void)
double nb_op_base (void)
void initialize (void)
void calculate (void)
void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_axpy< Interface >
Definition at line 32 of file action_axpy.hh.
Constructor & Destructor Documentation
Action_axpy() [1/2]
template<class Interface > Action_axpy< Interface >::Action_axpy (int size) inline
Definition at line 38 of file action_axpy.hh.
References MESSAGE, and X.
Action_axpy() [2/2]
template<class Interface > Action_axpy< Interface >::Action_axpy (const Action_axpy< Interface > &) inline
Definition at line 61 of file action_axpy.hh.
References INFOS.
~Action_axpy()
template<class Interface > Action_axpy< Interface >::~Action_axpy (void) inline
Definition at line 69 of file action_axpy.hh.
References MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > void Action_axpy< Interface >::calculate (void) inline
Definition at line 98 of file action_axpy.hh.
References axpy(), BTL_ASM_COMMENT, and X.
check_result()
template<class Interface > void Action_axpy< Interface >::check_result (void) inline
Definition at line 104 of file action_axpy.hh.
References STL_interface< real >::axpy(), e(), INFOS, STL_interface< real >::norm_diff(), and X.
initialize()
template<class Interface > void Action_axpy< Interface >::initialize (void) inline
Definition at line 93 of file action_axpy.hh.
References X.
name()
template<class Interface > static std::string Action_axpy< Interface >::name (void) inline static
Definition at line 84 of file action_axpy.hh.
nb_op_base()
template<class Interface > double Action_axpy< Interface >::nb_op_base (void) inline
Definition at line 89 of file action_axpy.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_axpy.hh