pairinteraction: Eigen::Translation< _Scalar, _Dim > Class Template Reference
Eigen::Translation< _Scalar, _Dim > Class Template Reference
Geometry » Reference » Geometry_Module
Represents a translation transformation.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = _Dim }
typedef _Scalar Scalar
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Matrix< Scalar, Dim, Dim > LinearMatrixType
typedef Transform< Scalar, Dim, Affine > AffineTransformType
typedef Transform< Scalar, Dim, Isometry > IsometryTransformType
Public Member Functions
EIGEN_DEVICE_FUNC Translation ()
EIGEN_DEVICE_FUNC Translation (const Scalar &sx, const Scalar &sy)
EIGEN_DEVICE_FUNC Translation (const Scalar &sx, const Scalar &sy, const Scalar &sz)
EIGEN_DEVICE_FUNC Translation (const VectorType &vector)
EIGEN_DEVICE_FUNC Scalar x () const
Retruns the x-translation by value.
EIGEN_DEVICE_FUNC Scalar y () const
Retruns the y-translation by value.
EIGEN_DEVICE_FUNC Scalar z () const
Retruns the z-translation by value.
EIGEN_DEVICE_FUNC Scalar & x ()
Retruns the x-translation as a reference.
EIGEN_DEVICE_FUNC Scalar & y ()
Retruns the y-translation as a reference.
EIGEN_DEVICE_FUNC Scalar & z ()
Retruns the z-translation as a reference.
EIGEN_DEVICE_FUNC const VectorType & vector () const
EIGEN_DEVICE_FUNC VectorType & vector ()
EIGEN_DEVICE_FUNC const VectorType & translation () const
EIGEN_DEVICE_FUNC VectorType & translation ()
EIGEN_DEVICE_FUNC Translation operator* (const Translation &other) const
EIGEN_DEVICE_FUNC AffineTransformType operator* (const UniformScaling< Scalar > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC AffineTransformType operator* (const EigenBase< OtherDerived > &linear) const
template<typename Derived >
EIGEN_DEVICE_FUNC IsometryTransformType operator* (const RotationBase< Derived, Dim > &r) const
template<int Mode, int Options>
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename Derived >
internal::enable_if< Derived::IsVectorAtCompileTime, VectorType >::type operator* (const MatrixBase< Derived > &vec) const
Translation inverse () const
Translation & operator= (const Translation &other)
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< Translation, Translation< NewScalarType, Dim > >::type cast () const
template<typename OtherScalarType >
EIGEN_DEVICE_FUNC Translation (const Translation< OtherScalarType, Dim > &other)
EIGEN_DEVICE_FUNC bool isApprox (const Translation &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
Static Public Member Functions
static const Translation Identity ()
Protected Attributes
VectorType m_coeffs
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC AffineTransformType operator* (const EigenBase< OtherDerived > &linear, const Translation &t)
Detailed Description
template<typename _Scalar, int _Dim>
class Eigen::Translation< _Scalar, _Dim >
Represents a translation transformation.
Template Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
_Dim the dimension of the space, can be a compile time value or Dynamic
Note
This class is not aimed to be used to store a translation transformation, but rather to make easier the constructions and updates of Transform objects.
See also
class Scaling, class Transform
Definition at line 271 of file ForwardDeclarations.h.
Member Typedef Documentation
AffineTransformType
template<typename _Scalar, int _Dim> typedef Transform<Scalar,Dim,Affine> Eigen::Translation< _Scalar, _Dim >::AffineTransformType
corresponding affine transformation type
Definition at line 43 of file Translation.h.
IsometryTransformType
template<typename _Scalar, int _Dim> typedef Transform<Scalar,Dim,Isometry> Eigen::Translation< _Scalar, _Dim >::IsometryTransformType
corresponding isometric transformation type
Definition at line 45 of file Translation.h.
LinearMatrixType
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,Dim,Dim> Eigen::Translation< _Scalar, _Dim >::LinearMatrixType
corresponding linear transformation matrix type
Definition at line 41 of file Translation.h.
Scalar
template<typename _Scalar, int _Dim> typedef _Scalar Eigen::Translation< _Scalar, _Dim >::Scalar
the scalar type of the coefficients
Definition at line 37 of file Translation.h.
VectorType
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,Dim,1> Eigen::Translation< _Scalar, _Dim >::VectorType
corresponding vector type
Definition at line 39 of file Translation.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int _Dim> anonymous enum
dimension of the space
Enumerator
Dim
Definition at line 35 of file Translation.h.
Constructor & Destructor Documentation
Translation() [1/5]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Eigen::Translation< _Scalar, _Dim >::Translation () inline
Default constructor without initialization.
Definition at line 54 of file Translation.h.
Referenced by Eigen::Translation< _Scalar, _Dim >::Identity(), Eigen::Translation< _Scalar, _Dim >::inverse(), and Eigen::Translation< _Scalar, _Dim >::operator*().
Translation() [2/5]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Eigen::Translation< _Scalar, _Dim >::Translation (const Scalar & sx, const Scalar & sy) inline
Definition at line 56 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::Dim, and eigen_assert.
Translation() [3/5]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Eigen::Translation< _Scalar, _Dim >::Translation (const Scalar & sx, const Scalar & sy, const Scalar & sz) inline
Definition at line 63 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::Dim, and eigen_assert.
Translation() [4/5]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Eigen::Translation< _Scalar, _Dim >::Translation (const VectorType & vector) inline explicit
Constructs and initialize the translation transformation from a vector of translation coefficients
Definition at line 71 of file Translation.h.
Translation() [5/5]
template<typename _Scalar, int _Dim> template<typename OtherScalarType > EIGEN_DEVICE_FUNC Eigen::Translation< _Scalar, _Dim >::Translation (const Translation< OtherScalarType, Dim > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 160 of file Translation.h.
Member Function Documentation
cast()
template<typename _Scalar, int _Dim> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<Translation,Translation<NewScalarType,Dim> >::type Eigen::Translation< _Scalar, _Dim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 155 of file Translation.h.
Identity()
template<typename _Scalar, int _Dim> static const Translation Eigen::Translation< _Scalar, _Dim >::Identity () inline static
Definition at line 147 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::Translation().
inverse()
template<typename _Scalar, int _Dim> Translation Eigen::Translation< _Scalar, _Dim >::inverse () const inline
Returns
the inverse translation (opposite)
Definition at line 139 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::Translation().
isApprox()
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC bool Eigen::Translation< _Scalar, _Dim >::isApprox (const Translation< _Scalar, _Dim > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
Definition at line 167 of file Translation.h.
operator*() [1/6]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Translation Eigen::Translation< _Scalar, _Dim >::operator* (const Translation< _Scalar, _Dim > & other) const inline
Concatenates two translation
Definition at line 94 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::Translation().
operator*() [2/6]
template<typename Scalar , int Dim> EIGEN_DEVICE_FUNC Translation< Scalar, Dim >::AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const UniformScaling< Scalar > & other) const inline
Concatenates a translation and a uniform scaling
Definition at line 182 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::Dim, Eigen::UniformScaling< _Scalar >::factor(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Eigen::Translation< _Scalar, _Dim >::m_coeffs, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), res, Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
operator*() [3/6]
template<typename Scalar , int Dim> template<typename OtherDerived > EIGEN_DEVICE_FUNC Translation< Scalar, Dim >::AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const EigenBase< OtherDerived > & linear) const inline
Concatenates a translation and a linear transformation
Definition at line 195 of file Translation.h.
References Eigen::EigenBase< Derived >::derived(), Eigen::Translation< _Scalar, _Dim >::Dim, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Eigen::Translation< _Scalar, _Dim >::m_coeffs, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), res, Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
operator*() [4/6]
template<typename _Scalar, int _Dim> template<typename Derived > EIGEN_DEVICE_FUNC IsometryTransformType Eigen::Translation< _Scalar, _Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
Concatenates a translation and a rotation
Definition at line 106 of file Translation.h.
operator*() [5/6]
template<typename _Scalar, int _Dim> template<int Mode, int Options> EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode> Eigen::Translation< _Scalar, _Dim >::operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Concatenates a translation and a transformation
Definition at line 125 of file Translation.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::pretranslate(), and res.
operator*() [6/6]
template<typename _Scalar, int _Dim> template<typename Derived > internal::enable_if<Derived::IsVectorAtCompileTime,VectorType>::type Eigen::Translation< _Scalar, _Dim >::operator* (const MatrixBase< Derived > & vec) const inline
Applies translation to vector
Definition at line 135 of file Translation.h.
operator=()
template<typename _Scalar, int _Dim> Translation& Eigen::Translation< _Scalar, _Dim >::operator= (const Translation< _Scalar, _Dim > & other) inline
Definition at line 141 of file Translation.h.
translation() [1/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC const VectorType& Eigen::Translation< _Scalar, _Dim >::translation () const inline
Definition at line 90 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::m_coeffs.
translation() [2/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC VectorType& Eigen::Translation< _Scalar, _Dim >::translation () inline
Definition at line 91 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::m_coeffs.
vector() [1/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC const VectorType& Eigen::Translation< _Scalar, _Dim >::vector () const inline
Definition at line 87 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::m_coeffs.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*=(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), test_openglsupport(), and Eigen::test_relative_error().
vector() [2/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC VectorType& Eigen::Translation< _Scalar, _Dim >::vector () inline
Definition at line 88 of file Translation.h.
References Eigen::Translation< _Scalar, _Dim >::m_coeffs.
x() [1/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Scalar Eigen::Translation< _Scalar, _Dim >::x () const inline
Retruns the x-translation by value.
Definition at line 74 of file Translation.h.
x() [2/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Scalar& Eigen::Translation< _Scalar, _Dim >::x () inline
Retruns the x-translation as a reference.
Definition at line 81 of file Translation.h.
y() [1/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Scalar Eigen::Translation< _Scalar, _Dim >::y () const inline
Retruns the y-translation by value.
Definition at line 76 of file Translation.h.
y() [2/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Scalar& Eigen::Translation< _Scalar, _Dim >::y () inline
Retruns the y-translation as a reference.
Definition at line 83 of file Translation.h.
z() [1/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Scalar Eigen::Translation< _Scalar, _Dim >::z () const inline
Retruns the z-translation by value.
Definition at line 78 of file Translation.h.
z() [2/2]
template<typename _Scalar, int _Dim> EIGEN_DEVICE_FUNC Scalar& Eigen::Translation< _Scalar, _Dim >::z () inline
Retruns the z-translation as a reference.
Definition at line 85 of file Translation.h.
Friends And Related Function Documentation
operator*
template<typename _Scalar, int _Dim> template<typename OtherDerived > EIGEN_DEVICE_FUNC AffineTransformType operator* (const EigenBase< OtherDerived > & linear, const Translation< _Scalar, _Dim > & t) friend
Returns
the concatenation of a linear transformation l with the translation t
Definition at line 112 of file Translation.h.
Field Documentation
m_coeffs
template<typename _Scalar, int _Dim> VectorType Eigen::Translation< _Scalar, _Dim >::m_coeffs protected
Definition at line 49 of file Translation.h.
Referenced by Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::Translation< _Scalar, _Dim >::translation(), and Eigen::Translation< _Scalar, _Dim >::vector().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/Geometry/Translation.h