pairinteraction: Eigen::DGMRES< _MatrixType, _Preconditioner > Class Template Reference
Eigen::DGMRES< _MatrixType, _Preconditioner > Class Template Reference
A Restarted GMRES with deflation. This class implements a modification of the GMRES solver for sparse linear systems. The basis is built with modified Gram-Schmidt. At each restart, a few approximated eigenvectors corresponding to the smallest eigenvalues are used to build a preconditioner for the next cycle. This preconditioner for deflation can be combined with any other preconditioner, the IncompleteLUT for instance. The preconditioner is applied at right of the matrix and the combination is multiplicative.
#include <DGMRES.h>
Public Types
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef MatrixType::StorageIndex StorageIndex
typedef MatrixType::RealScalar RealScalar
typedef _Preconditioner Preconditioner
typedef Matrix< Scalar, Dynamic, Dynamic > DenseMatrix
typedef Matrix< RealScalar, Dynamic, Dynamic > DenseRealMatrix
typedef Matrix< Scalar, Dynamic, 1 > DenseVector
typedef Matrix< RealScalar, Dynamic, 1 > DenseRealVector
typedef Matrix< std::complex< RealScalar >, Dynamic, 1 > ComplexVector
Public Types inherited from Eigen::IterativeSolverBase< DGMRES< _MatrixType, _Preconditioner > >
enum
typedef internal::traits< DGMRES< _MatrixType, _Preconditioner > >::MatrixType MatrixType
typedef internal::traits< DGMRES< _MatrixType, _Preconditioner > >::Preconditioner Preconditioner
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef MatrixType::RealScalar RealScalar
Public Member Functions
DGMRES ()
template<typename MatrixDerived >
DGMRES (const EigenBase< MatrixDerived > &A)
~DGMRES ()
template<typename Rhs , typename Dest >
void _solve_with_guess_impl (const Rhs &b, Dest &x) const
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, MatrixBase< Dest > &x) const
int restart ()
void set_restart (const int restart)
void setEigenv (const int neig)
int deflSize ()
void setMaxEigenv (const int maxNeig)
Public Member Functions inherited from Eigen::IterativeSolverBase< DGMRES< _MatrixType, _Preconditioner > >
IterativeSolverBase ()
IterativeSolverBase (const EigenBase< MatrixDerived > &A)
~IterativeSolverBase ()
DGMRES< _MatrixType, _Preconditioner > & analyzePattern (const EigenBase< MatrixDerived > &A)
DGMRES< _MatrixType, _Preconditioner > & factorize (const EigenBase< MatrixDerived > &A)
DGMRES< _MatrixType, _Preconditioner > & compute (const EigenBase< MatrixDerived > &A)
Index rows () const
Index cols () const
RealScalar tolerance () const
DGMRES< _MatrixType, _Preconditioner > & setTolerance (const RealScalar &tolerance)
Preconditioner & preconditioner ()
const Preconditioner & preconditioner () const
Index maxIterations () const
DGMRES< _MatrixType, _Preconditioner > & setMaxIterations (Index maxIters)
Index iterations () const
RealScalar error () const
const SolveWithGuess< DGMRES< _MatrixType, _Preconditioner >, Rhs, Guess > solveWithGuess (const MatrixBase< Rhs > &b, const Guess &x0) const
ComputationInfo info () const
void _solve_impl (const Rhs &b, SparseMatrixBase< DestDerived > &aDest) const
Public Member Functions inherited from Eigen::SparseSolverBase< DGMRES< _MatrixType, _Preconditioner > >
SparseSolverBase ()
~SparseSolverBase ()
DGMRES< _MatrixType, _Preconditioner > & derived ()
const DGMRES< _MatrixType, _Preconditioner > & derived () const
const Solve< DGMRES< _MatrixType, _Preconditioner >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< DGMRES< _MatrixType, _Preconditioner >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Member Functions
template<typename Rhs , typename Dest >
void dgmres (const MatrixType &mat, const Rhs &rhs, Dest &x, const Preconditioner &precond) const
Perform several cycles of restarted GMRES with modified Gram Schmidt,.
template<typename Dest >
int dgmresCycle (const MatrixType &mat, const Preconditioner &precond, Dest &x, DenseVector &r0, RealScalar &beta, const RealScalar &normRhs, int &nbIts) const
Perform one restart cycle of DGMRES.
int dgmresComputeDeflationData (const MatrixType &mat, const Preconditioner &precond, const Index &it, StorageIndex &neig) const
template<typename RhsType , typename DestType >
int dgmresApplyDeflation (const RhsType &In, DestType &Out) const
ComplexVector schurValues (const ComplexSchur< DenseMatrix > &schurofH) const
ComplexVector schurValues (const RealSchur< DenseMatrix > &schurofH) const
void dgmresInitDeflation (Index &rows) const
Protected Member Functions inherited from Eigen::IterativeSolverBase< DGMRES< _MatrixType, _Preconditioner > >
void init ()
const ActualMatrixType & matrix () const
void grab (const InputType &A)
Protected Attributes
DenseMatrix m_V
DenseMatrix m_H
DenseMatrix m_Hes
Index m_restart
DenseMatrix m_U
DenseMatrix m_MU
DenseMatrix m_T
PartialPivLU< DenseMatrix > m_luT
StorageIndex m_neig
int m_r
int m_maxNeig
RealScalar m_lambdaN
bool m_isDeflAllocated
bool m_isDeflInitialized
RealScalar m_smv
bool m_force
Protected Attributes inherited from Eigen::IterativeSolverBase< DGMRES< _MatrixType, _Preconditioner > >
MatrixWrapper m_matrixWrapper
Preconditioner m_preconditioner
Index m_maxIterations
RealScalar m_tolerance
RealScalar m_error
Index m_iterations
ComputationInfo m_info
bool m_analysisIsOk
bool m_factorizationIsOk
Protected Attributes inherited from Eigen::SparseSolverBase< DGMRES< _MatrixType, _Preconditioner > >
bool m_isInitialized
Additional Inherited Members
Protected Types inherited from Eigen::IterativeSolverBase< DGMRES< _MatrixType, _Preconditioner > >
typedef SparseSolverBase< DGMRES< _MatrixType, _Preconditioner > > Base
typedef internal::generic_matrix_wrapper< MatrixType > MatrixWrapper
typedef MatrixWrapper::ActualMatrixType ActualMatrixType
Detailed Description
template<typename _MatrixType, typename _Preconditioner>
class Eigen::DGMRES< _MatrixType, _Preconditioner >
A Restarted GMRES with deflation. This class implements a modification of the GMRES solver for sparse linear systems. The basis is built with modified Gram-Schmidt. At each restart, a few approximated eigenvectors corresponding to the smallest eigenvalues are used to build a preconditioner for the next cycle. This preconditioner for deflation can be combined with any other preconditioner, the IncompleteLUT for instance. The preconditioner is applied at right of the matrix and the combination is multiplicative.
Template Parameters
_MatrixType the type of the sparse matrix A, can be a dense or a sparse matrix.
_Preconditioner the type of the preconditioner. Default is DiagonalPreconditioner Typical usage :
SparseMatrix<double> A;
VectorXd x, b;
//Fill A and b ...
DGMRES<SparseMatrix<double> > solver;
solver.set_restart(30); // Set restarting value
solver.setEigenv(1); // Set the number of eigenvalues to deflate
solver.compute(A);
x = solver.solve(b);
DGMRES can also be used in a matrix-free context, see the following example .
References : [1] D. NUENTSA WAKAM and F. PACULL, Memory Efficient Hybrid Algebraic Solvers for Linear Systems Arising from Compressible Flows, Computers and Fluids, In Press, http://dx.doi.org/10.1016/j.compfluid.2012.03.023 [2] K. Burrage and J. Erhel, On the performance of various adaptive preconditioned GMRES strategies, 5(1998), 101-121. [3] J. Erhel, K. Burrage and B. Pohl, Restarted GMRES preconditioned by deflation,J. Computational and Applied Mathematics, 69(1996), 303-318.
Definition at line 19 of file DGMRES.h.
Member Typedef Documentation
ComplexVector
template<typename _MatrixType, typename _Preconditioner> typedef Matrix<std::complex<RealScalar>, Dynamic, 1> Eigen::DGMRES< _MatrixType, _Preconditioner >::ComplexVector
Definition at line 123 of file DGMRES.h.
DenseMatrix
template<typename _MatrixType, typename _Preconditioner> typedef Matrix<Scalar,Dynamic,Dynamic> Eigen::DGMRES< _MatrixType, _Preconditioner >::DenseMatrix
Definition at line 119 of file DGMRES.h.
DenseRealMatrix
template<typename _MatrixType, typename _Preconditioner> typedef Matrix<RealScalar,Dynamic,Dynamic> Eigen::DGMRES< _MatrixType, _Preconditioner >::DenseRealMatrix
Definition at line 120 of file DGMRES.h.
DenseRealVector
template<typename _MatrixType, typename _Preconditioner> typedef Matrix<RealScalar,Dynamic,1> Eigen::DGMRES< _MatrixType, _Preconditioner >::DenseRealVector
Definition at line 122 of file DGMRES.h.
DenseVector
template<typename _MatrixType, typename _Preconditioner> typedef Matrix<Scalar,Dynamic,1> Eigen::DGMRES< _MatrixType, _Preconditioner >::DenseVector
Definition at line 121 of file DGMRES.h.
Index
template<typename _MatrixType, typename _Preconditioner> typedef MatrixType::Index Eigen::DGMRES< _MatrixType, _Preconditioner >::Index
Definition at line 115 of file DGMRES.h.
MatrixType
template<typename _MatrixType, typename _Preconditioner> typedef _MatrixType Eigen::DGMRES< _MatrixType, _Preconditioner >::MatrixType
Definition at line 113 of file DGMRES.h.
Preconditioner
template<typename _MatrixType, typename _Preconditioner> typedef _Preconditioner Eigen::DGMRES< _MatrixType, _Preconditioner >::Preconditioner
Definition at line 118 of file DGMRES.h.
RealScalar
template<typename _MatrixType, typename _Preconditioner> typedef MatrixType::RealScalar Eigen::DGMRES< _MatrixType, _Preconditioner >::RealScalar
Definition at line 117 of file DGMRES.h.
Scalar
template<typename _MatrixType, typename _Preconditioner> typedef MatrixType::Scalar Eigen::DGMRES< _MatrixType, _Preconditioner >::Scalar
Definition at line 114 of file DGMRES.h.
StorageIndex
template<typename _MatrixType, typename _Preconditioner> typedef MatrixType::StorageIndex Eigen::DGMRES< _MatrixType, _Preconditioner >::StorageIndex
Definition at line 116 of file DGMRES.h.
Constructor & Destructor Documentation
DGMRES() [1/2]
template<typename _MatrixType, typename _Preconditioner> Eigen::DGMRES< _MatrixType, _Preconditioner >::DGMRES () inline
Default constructor.
Definition at line 127 of file DGMRES.h.
DGMRES() [2/2]
template<typename _MatrixType, typename _Preconditioner> template<typename MatrixDerived > Eigen::DGMRES< _MatrixType, _Preconditioner >::DGMRES (const EigenBase< MatrixDerived > & A) inline explicit
Initialize the solver with matrix A for further Ax=b solving.
This constructor is a shortcut for the default constructor followed by a call to compute().
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
Definition at line 140 of file DGMRES.h.
~DGMRES()
template<typename _MatrixType, typename _Preconditioner> Eigen::DGMRES< _MatrixType, _Preconditioner >::~DGMRES () inline
Definition at line 142 of file DGMRES.h.
Member Function Documentation
_solve_impl()
template<typename _MatrixType, typename _Preconditioner> template<typename Rhs , typename Dest > void Eigen::DGMRES< _MatrixType, _Preconditioner >::_solve_impl (const Rhs & b, MatrixBase< Dest > & x) const inline
Definition at line 165 of file DGMRES.h.
References b.
_solve_with_guess_impl()
template<typename _MatrixType, typename _Preconditioner> template<typename Rhs , typename Dest > void Eigen::DGMRES< _MatrixType, _Preconditioner >::_solve_with_guess_impl (const Rhs & b, Dest & x) const inline
Definition at line 146 of file DGMRES.h.
References j, matrix(), Eigen::NoConvergence, Eigen::NumericalIssue, and Eigen::Success.
deflSize()
template<typename _MatrixType, typename _Preconditioner> int Eigen::DGMRES< _MatrixType, _Preconditioner >::deflSize () inline
Get the size of the deflation subspace size
Definition at line 192 of file DGMRES.h.
dgmres()
template<typename _MatrixType , typename _Preconditioner > template<typename Rhs , typename Dest > void Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmres (const MatrixType & mat, const Rhs & rhs, Dest & x, const Preconditioner & precond) const protected
Perform several cycles of restarted GMRES with modified Gram Schmidt,.
A right preconditioner is used combined with deflation.
Definition at line 243 of file DGMRES.h.
References n, Eigen::NoConvergence, Eigen::Success, and x.
dgmresApplyDeflation()
template<typename _MatrixType , typename _Preconditioner > template<typename RhsType , typename DestType > int Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresApplyDeflation (const RhsType & In, DestType & Out) const protected
Definition at line 505 of file DGMRES.h.
References x.
dgmresComputeDeflationData()
template<typename _MatrixType , typename _Preconditioner > int Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresComputeDeflationData (const MatrixType & mat, const Preconditioner & precond, const Index & it, StorageIndex & neig) const protected
Definition at line 421 of file DGMRES.h.
References abs(), eig, j, m, max, Eigen::PlainObjectBase< Derived >::setZero(), Eigen::internal::sortWithPermutation(), and X.
dgmresCycle()
template<typename _MatrixType , typename _Preconditioner > template<typename Dest > int Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresCycle (const MatrixType & mat, const Preconditioner & precond, Dest & x, DenseVector & r0, RealScalar & beta, const RealScalar & normRhs, int & nbIts) const protected
Perform one restart cycle of DGMRES.
Parameters
mat The coefficient matrix
precond The preconditioner
x the new approximated solution
r0 The initial residual vector
beta The norm of the residual computed so far
normRhs The norm of the right hand side vector
nbIts The number of iterations
Definition at line 287 of file DGMRES.h.
References abs(), adjoint(), model_potential::g(), i, n, Eigen::NoConvergence, Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Success.
dgmresInitDeflation()
template<typename _MatrixType , typename _Preconditioner > void Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresInitDeflation (Index & rows) const protected
Definition at line 379 of file DGMRES.h.
restart()
template<typename _MatrixType, typename _Preconditioner> int Eigen::DGMRES< _MatrixType, _Preconditioner >::restart () inline
Get the restart value
Definition at line 173 of file DGMRES.h.
schurValues() [1/2]
template<typename _MatrixType , typename _Preconditioner > DGMRES< _MatrixType, _Preconditioner >::ComplexVector Eigen::DGMRES< _MatrixType, _Preconditioner >::schurValues (const ComplexSchur< DenseMatrix > & schurofH) const inline protected
Definition at line 389 of file DGMRES.h.
References Eigen::ComplexSchur< _MatrixType >::matrixT().
schurValues() [2/2]
template<typename _MatrixType , typename _Preconditioner > DGMRES< _MatrixType, _Preconditioner >::ComplexVector Eigen::DGMRES< _MatrixType, _Preconditioner >::schurValues (const RealSchur< DenseMatrix > & schurofH) const inline protected
Definition at line 395 of file DGMRES.h.
References eig, j, Eigen::RealSchur< _MatrixType >::matrixT(), and Eigen::PlainObjectBase< Derived >::rows().
set_restart()
template<typename _MatrixType, typename _Preconditioner> void Eigen::DGMRES< _MatrixType, _Preconditioner >::set_restart (const int restart) inline
Set the restart value (default is 30)
Definition at line 178 of file DGMRES.h.
setEigenv()
template<typename _MatrixType, typename _Preconditioner> void Eigen::DGMRES< _MatrixType, _Preconditioner >::setEigenv (const int neig) inline
Set the number of eigenvalues to deflate at each restart
Definition at line 183 of file DGMRES.h.
setMaxEigenv()
template<typename _MatrixType, typename _Preconditioner> void Eigen::DGMRES< _MatrixType, _Preconditioner >::setMaxEigenv (const int maxNeig) inline
Set the maximum size of the deflation subspace
Definition at line 197 of file DGMRES.h.
References mat, Eigen::internal::Rhs, rows, and x.
Field Documentation
m_force
template<typename _MatrixType, typename _Preconditioner> bool Eigen::DGMRES< _MatrixType, _Preconditioner >::m_force mutable protected
Definition at line 232 of file DGMRES.h.
m_H
template<typename _MatrixType, typename _Preconditioner> DenseMatrix Eigen::DGMRES< _MatrixType, _Preconditioner >::m_H mutable protected
Definition at line 216 of file DGMRES.h.
m_Hes
template<typename _MatrixType, typename _Preconditioner> DenseMatrix Eigen::DGMRES< _MatrixType, _Preconditioner >::m_Hes mutable protected
Definition at line 217 of file DGMRES.h.
m_isDeflAllocated
template<typename _MatrixType, typename _Preconditioner> bool Eigen::DGMRES< _MatrixType, _Preconditioner >::m_isDeflAllocated mutable protected
Definition at line 227 of file DGMRES.h.
m_isDeflInitialized
template<typename _MatrixType, typename _Preconditioner> bool Eigen::DGMRES< _MatrixType, _Preconditioner >::m_isDeflInitialized mutable protected
Definition at line 228 of file DGMRES.h.
m_lambdaN
template<typename _MatrixType, typename _Preconditioner> RealScalar Eigen::DGMRES< _MatrixType, _Preconditioner >::m_lambdaN mutable protected
Definition at line 226 of file DGMRES.h.
m_luT
template<typename _MatrixType, typename _Preconditioner> PartialPivLU<DenseMatrix> Eigen::DGMRES< _MatrixType, _Preconditioner >::m_luT mutable protected
Definition at line 222 of file DGMRES.h.
m_maxNeig
template<typename _MatrixType, typename _Preconditioner> int Eigen::DGMRES< _MatrixType, _Preconditioner >::m_maxNeig mutable protected
Definition at line 225 of file DGMRES.h.
m_MU
template<typename _MatrixType, typename _Preconditioner> DenseMatrix Eigen::DGMRES< _MatrixType, _Preconditioner >::m_MU mutable protected
Definition at line 220 of file DGMRES.h.
m_neig
template<typename _MatrixType, typename _Preconditioner> StorageIndex Eigen::DGMRES< _MatrixType, _Preconditioner >::m_neig mutable protected
Definition at line 223 of file DGMRES.h.
m_r
template<typename _MatrixType, typename _Preconditioner> int Eigen::DGMRES< _MatrixType, _Preconditioner >::m_r mutable protected
Definition at line 224 of file DGMRES.h.
m_restart
template<typename _MatrixType, typename _Preconditioner> Index Eigen::DGMRES< _MatrixType, _Preconditioner >::m_restart mutable protected
Definition at line 218 of file DGMRES.h.
m_smv
template<typename _MatrixType, typename _Preconditioner> RealScalar Eigen::DGMRES< _MatrixType, _Preconditioner >::m_smv mutable protected
Definition at line 231 of file DGMRES.h.
m_T
template<typename _MatrixType, typename _Preconditioner> DenseMatrix Eigen::DGMRES< _MatrixType, _Preconditioner >::m_T mutable protected
Definition at line 221 of file DGMRES.h.
m_U
template<typename _MatrixType, typename _Preconditioner> DenseMatrix Eigen::DGMRES< _MatrixType, _Preconditioner >::m_U mutable protected
Definition at line 219 of file DGMRES.h.
m_V
template<typename _MatrixType, typename _Preconditioner> DenseMatrix Eigen::DGMRES< _MatrixType, _Preconditioner >::m_V mutable protected
Definition at line 215 of file DGMRES.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/IterativeSolvers/DGMRES.h