pairinteraction: Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options > Class Template Reference
Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options > Class Template Reference
Geometry » Reference » Geometry_Module
A parametrized line.
#include <ForwardDeclarations.h>
Public Types
enum { AmbientDimAtCompileTime = _AmbientDim, Options = _Options }
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, AmbientDimAtCompileTime, 1, Options > VectorType
Public Member Functions
EIGEN_DEVICE_FUNC ParametrizedLine ()
template<int OtherOptions>
EIGEN_DEVICE_FUNC ParametrizedLine (const ParametrizedLine< Scalar, AmbientDimAtCompileTime, OtherOptions > &other)
EIGEN_DEVICE_FUNC ParametrizedLine (Index _dim)
EIGEN_DEVICE_FUNC ParametrizedLine (const VectorType &origin, const VectorType &direction)
template<int OtherOptions>
EIGEN_DEVICE_FUNC ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane)
EIGEN_DEVICE_FUNC ~ParametrizedLine ()
EIGEN_DEVICE_FUNC Index dim () const
EIGEN_DEVICE_FUNC const VectorType & origin () const
EIGEN_DEVICE_FUNC VectorType & origin ()
EIGEN_DEVICE_FUNC const VectorType & direction () const
EIGEN_DEVICE_FUNC VectorType & direction ()
EIGEN_DEVICE_FUNC RealScalar squaredDistance (const VectorType &p) const
EIGEN_DEVICE_FUNC RealScalar distance (const VectorType &p) const
EIGEN_DEVICE_FUNC VectorType projection (const VectorType &p) const
EIGEN_DEVICE_FUNC VectorType pointAt (const Scalar &t) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< ParametrizedLine, ParametrizedLine< NewScalarType, AmbientDimAtCompileTime, Options > >::type cast () const
template<typename OtherScalarType , int OtherOptions>
EIGEN_DEVICE_FUNC ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
EIGEN_DEVICE_FUNC bool isApprox (const ParametrizedLine &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC _Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC _Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC ParametrizedLine Through (const VectorType &p0, const VectorType &p1)
Protected Attributes
VectorType m_origin
VectorType m_direction
Detailed Description
template<typename _Scalar, int _AmbientDim, int _Options>
class Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >
A parametrized line.
A parametrized line is defined by an origin point \(\mathbf{o} \) and a unit direction vector \(\mathbf{d} \) such that the line corresponds to the set \(l(t) = \mathbf{o} + t \mathbf{d} \), \(t \in \mathbf{R} \).
Template Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
Definition at line 275 of file ForwardDeclarations.h.
Member Typedef Documentation
Index
template<typename _Scalar, int _AmbientDim, int _Options> typedef Eigen::Index Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::Index
Deprecated:
since Eigen 3.3
Definition at line 40 of file ParametrizedLine.h.
RealScalar
template<typename _Scalar, int _AmbientDim, int _Options> typedef NumTraits<Scalar>::Real Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::RealScalar
Definition at line 39 of file ParametrizedLine.h.
Scalar
template<typename _Scalar, int _AmbientDim, int _Options> typedef _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::Scalar
Definition at line 38 of file ParametrizedLine.h.
VectorType
template<typename _Scalar, int _AmbientDim, int _Options> typedef Matrix<Scalar,AmbientDimAtCompileTime,1,Options> Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType
Definition at line 41 of file ParametrizedLine.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int _AmbientDim, int _Options> anonymous enum
Enumerator
AmbientDimAtCompileTime
Options
Definition at line 34 of file ParametrizedLine.h.
Constructor & Destructor Documentation
ParametrizedLine() [1/6]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine () inline
Default constructor without initialization
Definition at line 44 of file ParametrizedLine.h.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::cast(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::Through().
ParametrizedLine() [2/6]
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine (const ParametrizedLine< Scalar, AmbientDimAtCompileTime, OtherOptions > & other) inline
Definition at line 47 of file ParametrizedLine.h.
ParametrizedLine() [3/6]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine (Index _dim) inline explicit
Constructs a dynamic-size line with _dim the dimension of the ambient space
Definition at line 53 of file ParametrizedLine.h.
ParametrizedLine() [4/6]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine (const VectorType & origin, const VectorType & direction) inline
Initializes a parametrized line of direction direction and origin origin.
Warning
the vector direction is assumed to be normalized.
Definition at line 58 of file ParametrizedLine.h.
References hyperplane(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
ParametrizedLine() [5/6]
template<typename _Scalar , int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) inline explicit
Constructs a parametrized line from a 2D hyperplane
Warning
the ambient space must have dimension 2 such that the hyperplane actually describes a line
Definition at line 146 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin().
~ParametrizedLine()
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::~ParametrizedLine () inline
Definition at line 68 of file ParametrizedLine.h.
ParametrizedLine() [6/6]
template<typename _Scalar, int _AmbientDim, int _Options> template<typename OtherScalarType , int OtherOptions> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 122 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_direction, and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_origin.
Member Function Documentation
cast()
template<typename _Scalar, int _AmbientDim, int _Options> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<ParametrizedLine, ParametrizedLine<NewScalarType,AmbientDimAtCompileTime,Options> >::type Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 114 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
dim()
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC Index Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::dim () const inline
Returns
the dimension in which the line holds
Definition at line 71 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_direction.
direction() [1/2]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC const VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction (void) const inline
Definition at line 76 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_direction.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::squaredDistance().
direction() [2/2]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction (void) inline
Definition at line 77 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_direction.
distance()
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC RealScalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::distance (const VectorType & p) const inline
Returns
the distance of a point p to its projection onto the line *this.
See also
squaredDistance()
Definition at line 90 of file ParametrizedLine.h.
References sqrt(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::squaredDistance().
intersection() [1/2]
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection().
intersection() [2/2]
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Deprecated:
use intersectionParameter()
Returns
the parameter value of the intersection between *this and the given hyperplane
Definition at line 178 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter().
intersectionParameter() [1/2]
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersection(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionPoint(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection().
intersectionParameter() [2/2]
template<typename _Scalar, int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the parameter value of the intersection between *this and the given hyperplane
Definition at line 166 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin().
intersectionPoint()
template<typename _Scalar , int _AmbientDim, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the point of the intersection between *this and the given hyperplane
Definition at line 188 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt().
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection().
isApprox()
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC bool Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::isApprox (const ParametrizedLine< _Scalar, _AmbientDim, _Options > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
Definition at line 132 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_direction, and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_origin.
origin() [1/2]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC const VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin () const inline
Definition at line 73 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_origin.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::squaredDistance(), and Eigen::test_relative_error().
origin() [2/2]
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin () inline
Definition at line 74 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_origin.
pointAt()
template<typename _Scalar , int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt (const Scalar & t) const inline
Returns
the point at t along this line
Definition at line 157 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin().
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionPoint(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection().
projection()
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the line *this.
Definition at line 93 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersection(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionParameter(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionPoint(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt().
squaredDistance()
template<typename _Scalar, int _AmbientDim, int _Options> EIGEN_DEVICE_FUNC RealScalar Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::squaredDistance (const VectorType & p) const inline
Returns
the squared distance of a point p to its projection onto the line *this.
See also
distance()
Definition at line 82 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), dot(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin().
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::distance().
Through()
template<typename _Scalar, int _AmbientDim, int _Options> static EIGEN_DEVICE_FUNC ParametrizedLine Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a parametrized line going from p0 to p1.
Definition at line 65 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
Field Documentation
m_direction
template<typename _Scalar, int _AmbientDim, int _Options> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_direction protected
Definition at line 137 of file ParametrizedLine.h.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::dim(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::direction(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::isApprox(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
m_origin
template<typename _Scalar, int _AmbientDim, int _Options> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::m_origin protected
Definition at line 137 of file ParametrizedLine.h.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::isApprox(), Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/Geometry/ParametrizedLine.h