pairinteraction: Eigen::ReturnByValue< Derived > Class Template Reference
Eigen::ReturnByValue< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
#include <ReturnByValue.h>
Data Structures
class Unusable
Public Types
typedef internal::traits< Derived >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Detailed Description
template<typename Derived>
class Eigen::ReturnByValue< Derived >
Definition at line 50 of file ReturnByValue.h.
Member Typedef Documentation
Base
template<typename Derived> typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< Derived >::Base
Definition at line 56 of file ReturnByValue.h.
ReturnType
template<typename Derived> typedef internal::traits<Derived>::ReturnType Eigen::ReturnByValue< Derived >::ReturnType
Definition at line 54 of file ReturnByValue.h.
Member Function Documentation
coeff() [1/2]
template<typename Derived> const Unusable& Eigen::ReturnByValue< Derived >::coeff (Index) const inline
Definition at line 72 of file ReturnByValue.h.
coeff() [2/2]
template<typename Derived> const Unusable& Eigen::ReturnByValue< Derived >::coeff (Index , Index) const inline
Definition at line 73 of file ReturnByValue.h.
coeffRef() [1/2]
template<typename Derived> Unusable& Eigen::ReturnByValue< Derived >::coeffRef (Index) inline
Definition at line 74 of file ReturnByValue.h.
coeffRef() [2/2]
template<typename Derived> Unusable& Eigen::ReturnByValue< Derived >::coeffRef (Index , Index) inline
Definition at line 75 of file ReturnByValue.h.
cols()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::ReturnByValue< Derived >::cols (void) const inline
Definition at line 64 of file ReturnByValue.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1(), Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::cols(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase().
evalTo()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::ReturnByValue< Derived >::evalTo (Dest & dst) const inline
Definition at line 61 of file ReturnByValue.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1(), Eigen::internal::evaluator< ReturnByValue< Derived > >::evaluator(), Eigen::KroneckerProduct< Lhs, Rhs >::KroneckerProduct(), Eigen::KroneckerProductSparse< Lhs, Rhs >::KroneckerProductSparse(), Eigen::DenseBase< Derived >::operator=(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::SparseMatrix< scalar_t >::SparseMatrix(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
rows()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::ReturnByValue< Derived >::rows (void) const inline
Definition at line 63 of file ReturnByValue.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), and Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::rows().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ReturnByValue.h