pairinteraction: Eigen::EulerAngles< _Scalar, _System > Class Template Reference
Eigen::EulerAngles< _Scalar, _System > Class Template Reference
Represents a rotation in a 3 dimensional space as three Euler angles.
#include <EulerAngles.h>
Public Types
typedef _Scalar Scalar
typedef _System System
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Quaternion< Scalar > QuaternionType
typedef AngleAxis< Scalar > AngleAxisType
Public Types inherited from Eigen::RotationBase< EulerAngles< _Scalar, _System >, 3 >
enum
typedef internal::traits< EulerAngles< _Scalar, _System > >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
EulerAngles ()
EulerAngles (const Scalar &alpha, const Scalar &beta, const Scalar &gamma)
template<typename Derived >
EulerAngles (const MatrixBase< Derived > &m)
template<typename Derived >
EulerAngles (const MatrixBase< Derived > &m, bool positiveRangeAlpha, bool positiveRangeBeta, bool positiveRangeGamma)
template<typename Derived >
EulerAngles (const RotationBase< Derived, 3 > &rot)
template<typename Derived >
EulerAngles (const RotationBase< Derived, 3 > &rot, bool positiveRangeAlpha, bool positiveRangeBeta, bool positiveRangeGamma)
const Vector3 & angles () const
Vector3 & angles ()
Scalar alpha () const
Scalar & alpha ()
Scalar beta () const
Scalar & beta ()
Scalar gamma () const
Scalar & gamma ()
EulerAngles inverse () const
EulerAngles operator- () const
template<typename Derived >
EulerAngles & operator= (const MatrixBase< Derived > &m)
template<typename Derived >
EulerAngles & operator= (const RotationBase< Derived, 3 > &rot)
Matrix3 toRotationMatrix () const
operator QuaternionType () const
Public Member Functions inherited from Eigen::RotationBase< EulerAngles< _Scalar, _System >, 3 >
EIGEN_DEVICE_FUNC const EulerAngles< _Scalar, _System > & derived () const
EIGEN_DEVICE_FUNC EulerAngles< _Scalar, _System > & derived ()
EIGEN_DEVICE_FUNC RotationMatrixType toRotationMatrix () const
EIGEN_DEVICE_FUNC RotationMatrixType matrix () const
EIGEN_DEVICE_FUNC EulerAngles< _Scalar, _System > inverse () const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
EIGEN_DEVICE_FUNC RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector< EulerAngles< _Scalar, _System >, OtherDerived, OtherDerived::IsVectorAtCompileTime >::ReturnType operator* (const EigenBase< OtherDerived > &e) const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
EIGEN_DEVICE_FUNC VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static Vector3 AlphaAxisVector ()
static Vector3 BetaAxisVector ()
static Vector3 GammaAxisVector ()
template<bool PositiveRangeAlpha, bool PositiveRangeBeta, bool PositiveRangeGamma, typename Derived >
static EulerAngles FromRotation (const MatrixBase< Derived > &m)
template<bool PositiveRangeAlpha, bool PositiveRangeBeta, bool PositiveRangeGamma, typename Derived >
static EulerAngles FromRotation (const RotationBase< Derived, 3 > &rot)
Friends
std::ostream & operator<< (std::ostream &s, const EulerAngles< Scalar, System > &eulerAngles)
Detailed Description
template<typename _Scalar, class _System>
class Eigen::EulerAngles< _Scalar, _System >
Represents a rotation in a 3 dimensional space as three Euler angles.
Euler rotation is a set of three rotation of three angles over three fixed axes, defined by the EulerSystem given as a template parameter.
Here is how intrinsic Euler angles works:
first, rotate the axes system over the alpha axis in angle alpha
then, rotate the axes system over the beta axis(which was rotated in the first stage) in angle beta
then, rotate the axes system over the gamma axis(which was rotated in the two stages above) in angle gamma
Note
This class support only intrinsic Euler angles for simplicity, see EulerSystem how to easily overcome this for extrinsic systems.
Rotation representation and conversions
It has been proved(see Wikipedia link below) that every rotation can be represented by Euler angles, but there is no singular representation (e.g. unlike rotation matrices). Therefore, you can convert from Eigen rotation and to them (including rotation matrices, which is not called "rotations" by Eigen design).
Euler angles usually used for:
convenient human representation of rotation, especially in interactive GUI.
gimbal systems and robotics
efficient encoding(i.e. 3 floats only) of rotation for network protocols.
However, Euler angles are slow comparing to quaternion or matrices, because their unnatural math definition, although it's simple for human. To overcome this, this class provide easy movement from the math friendly representation to the human friendly representation, and vise-versa.
All the user need to do is a safe simple C++ type conversion, and this class take care for the math. Additionally, some axes related computation is done in compile time.
Euler angles ranges in conversions
When converting some rotation to Euler angles, there are some ways you can guarantee the Euler angles ranges.
implicit ranges
When using implicit ranges, all angles are guarantee to be in the range [-PI, +PI], unless you convert from some other Euler angles. In this case, the range is undefined (might be even less than -PI or greater than +2*PI).
See also
EulerAngles(const MatrixBase<Derived>&)
EulerAngles(const RotationBase<Derived, 3>&)
explicit ranges
When using explicit ranges, all angles are guarantee to be in the range you choose. In the range Boolean parameter, you're been ask whether you prefer the positive range or not:
true - force the range between [0, +2*PI]
false - force the range between [-PI, +PI]
compile time ranges
This is when you have compile time ranges and you prefer to use template parameter. (e.g. for performance)
See also
FromRotation()
run-time time ranges
Run-time ranges are also supported.
See also
EulerAngles(const MatrixBase<Derived>&, bool, bool, bool)
EulerAngles(const RotationBase<Derived, 3>&, bool, bool, bool)
Convenient user typedefs
Convenient typedefs for EulerAngles exist for float and double scalar, in a form of EulerAngles{A}{B}{C}{scalar}, e.g. EulerAnglesXYZd, EulerAnglesZYZf.
Only for positive axes{+x,+y,+z} Euler systems are have convenient typedef. If you need negative axes{-x,-y,-z}, it is recommended to create you own typedef with a word that represent what you need.
Example
Output:
Additional reading
If you're want to get more idea about how Euler system work in Eigen see EulerSystem.
More information about Euler angles: https://en.wikipedia.org/wiki/Euler_angles
Template Parameters
_Scalar the scalar type, i.e., the type of the angles.
_System the EulerSystem to use, which represents the axes of rotation.
Definition at line 111 of file EulerAngles.h.
Member Typedef Documentation
AngleAxisType
template<typename _Scalar, class _System> typedef AngleAxis<Scalar> Eigen::EulerAngles< _Scalar, _System >::AngleAxisType
the equivalent angle-axis type
Definition at line 123 of file EulerAngles.h.
Matrix3
template<typename _Scalar, class _System> typedef Matrix<Scalar,3,3> Eigen::EulerAngles< _Scalar, _System >::Matrix3
the equivalent rotation matrix type
Definition at line 120 of file EulerAngles.h.
QuaternionType
template<typename _Scalar, class _System> typedef Quaternion<Scalar> Eigen::EulerAngles< _Scalar, _System >::QuaternionType
the equivalent quaternion type
Definition at line 122 of file EulerAngles.h.
Scalar
template<typename _Scalar, class _System> typedef _Scalar Eigen::EulerAngles< _Scalar, _System >::Scalar
the scalar type of the angles
Definition at line 115 of file EulerAngles.h.
System
template<typename _Scalar, class _System> typedef _System Eigen::EulerAngles< _Scalar, _System >::System
the EulerSystem to use, which represents the axes of rotation.
Definition at line 118 of file EulerAngles.h.
Vector3
template<typename _Scalar, class _System> typedef Matrix<Scalar,3,1> Eigen::EulerAngles< _Scalar, _System >::Vector3
the equivalent 3 dimension vector type
Definition at line 121 of file EulerAngles.h.
Constructor & Destructor Documentation
EulerAngles() [1/6]
template<typename _Scalar, class _System> Eigen::EulerAngles< _Scalar, _System >::EulerAngles () inline
Default constructor without initialization.
Definition at line 148 of file EulerAngles.h.
EulerAngles() [2/6]
template<typename _Scalar, class _System> Eigen::EulerAngles< _Scalar, _System >::EulerAngles (const Scalar & alpha, const Scalar & beta, const Scalar & gamma) inline
Constructs and initialize Euler angles(alpha, beta, gamma).
Definition at line 150 of file EulerAngles.h.
EulerAngles() [3/6]
template<typename _Scalar, class _System> template<typename Derived > Eigen::EulerAngles< _Scalar, _System >::EulerAngles (const MatrixBase< Derived > & m) inline
Constructs and initialize Euler angles from a 3x3 rotation matrix m.
Note
All angles will be in the range [-PI, PI].
Definition at line 158 of file EulerAngles.h.
References m.
EulerAngles() [4/6]
template<typename _Scalar, class _System> template<typename Derived > Eigen::EulerAngles< _Scalar, _System >::EulerAngles (const MatrixBase< Derived > & m, bool positiveRangeAlpha, bool positiveRangeBeta, bool positiveRangeGamma) inline
Constructs and initialize Euler angles from a 3x3 rotation matrix m, with options to choose for each angle the requested range.
If positive range is true, then the specified angle will be in the range [0, +2*PI]. Otherwise, the specified angle will be in the range [-PI, +PI].
Parameters
m The 3x3 rotation matrix to convert
positiveRangeAlpha If true, alpha will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeBeta If true, beta will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeGamma If true, gamma will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
Definition at line 172 of file EulerAngles.h.
EulerAngles() [5/6]
template<typename _Scalar, class _System> template<typename Derived > Eigen::EulerAngles< _Scalar, _System >::EulerAngles (const RotationBase< Derived, 3 > & rot) inline
Constructs and initialize Euler angles from a rotation rot.
Note
All angles will be in the range [-PI, PI], unless rot is an EulerAngles. If rot is an EulerAngles, expected EulerAngles range is undefined. (Use other functions here for enforcing range if this effect is desired)
Definition at line 188 of file EulerAngles.h.
References rot().
EulerAngles() [6/6]
template<typename _Scalar, class _System> template<typename Derived > Eigen::EulerAngles< _Scalar, _System >::EulerAngles (const RotationBase< Derived, 3 > & rot, bool positiveRangeAlpha, bool positiveRangeBeta, bool positiveRangeGamma) inline
Constructs and initialize Euler angles from a rotation rot, with options to choose for each angle the requested range.
If positive range is true, then the specified angle will be in the range [0, +2*PI]. Otherwise, the specified angle will be in the range [-PI, +PI].
Parameters
rot The 3x3 rotation matrix to convert
positiveRangeAlpha If true, alpha will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeBeta If true, beta will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeGamma If true, gamma will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
Definition at line 202 of file EulerAngles.h.
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
Member Function Documentation
alpha() [1/2]
template<typename _Scalar, class _System> Scalar Eigen::EulerAngles< _Scalar, _System >::alpha () const inline
Returns
The value of the first angle.
Definition at line 217 of file EulerAngles.h.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType().
alpha() [2/2]
template<typename _Scalar, class _System> Scalar& Eigen::EulerAngles< _Scalar, _System >::alpha () inline
Returns
A read-write reference to the angle of the first angle.
Definition at line 219 of file EulerAngles.h.
AlphaAxisVector()
template<typename _Scalar, class _System> static Vector3 Eigen::EulerAngles< _Scalar, _System >::AlphaAxisVector () inline static
Returns
the axis vector of the first (alpha) rotation
Definition at line 126 of file EulerAngles.h.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType().
angles() [1/2]
template<typename _Scalar, class _System> const Vector3& Eigen::EulerAngles< _Scalar, _System >::angles () const inline
Returns
The angle values stored in a vector (alpha, beta, gamma).
Definition at line 212 of file EulerAngles.h.
angles() [2/2]
template<typename _Scalar, class _System> Vector3& Eigen::EulerAngles< _Scalar, _System >::angles () inline
Returns
A read-write reference to the angle values stored in a vector (alpha, beta, gamma).
Definition at line 214 of file EulerAngles.h.
beta() [1/2]
template<typename _Scalar, class _System> Scalar Eigen::EulerAngles< _Scalar, _System >::beta () const inline
Returns
The value of the second angle.
Definition at line 222 of file EulerAngles.h.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType().
beta() [2/2]
template<typename _Scalar, class _System> Scalar& Eigen::EulerAngles< _Scalar, _System >::beta () inline
Returns
A read-write reference to the angle of the second angle.
Definition at line 224 of file EulerAngles.h.
BetaAxisVector()
template<typename _Scalar, class _System> static Vector3 Eigen::EulerAngles< _Scalar, _System >::BetaAxisVector () inline static
Returns
the axis vector of the second (beta) rotation
Definition at line 132 of file EulerAngles.h.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType().
FromRotation() [1/2]
template<typename _Scalar, class _System> template<bool PositiveRangeAlpha, bool PositiveRangeBeta, bool PositiveRangeGamma, typename Derived > static EulerAngles Eigen::EulerAngles< _Scalar, _System >::FromRotation (const MatrixBase< Derived > & m) inline static
Constructs and initialize Euler angles from a 3x3 rotation matrix m, with options to choose for each angle the requested range (only in compile time).
If positive range is true, then the specified angle will be in the range [0, +2*PI]. Otherwise, the specified angle will be in the range [-PI, +PI].
Parameters
m The 3x3 rotation matrix to convert
Template Parameters
positiveRangeAlpha If true, alpha will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeBeta If true, beta will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeGamma If true, gamma will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
Definition at line 265 of file EulerAngles.h.
References e(), EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_SIZE, and m.
FromRotation() [2/2]
template<typename _Scalar, class _System> template<bool PositiveRangeAlpha, bool PositiveRangeBeta, bool PositiveRangeGamma, typename Derived > static EulerAngles Eigen::EulerAngles< _Scalar, _System >::FromRotation (const RotationBase< Derived, 3 > & rot) inline static
Constructs and initialize Euler angles from a rotation rot, with options to choose for each angle the requested range (only in compile time).
If positive range is true, then the specified angle will be in the range [0, +2*PI]. Otherwise, the specified angle will be in the range [-PI, +PI].
Parameters
rot The 3x3 rotation matrix to convert
Template Parameters
positiveRangeAlpha If true, alpha will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeBeta If true, beta will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
positiveRangeGamma If true, gamma will be in [0, 2*PI]. Otherwise, in [-PI, +PI].
Definition at line 291 of file EulerAngles.h.
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
gamma() [1/2]
template<typename _Scalar, class _System> Scalar Eigen::EulerAngles< _Scalar, _System >::gamma () const inline
Returns
The value of the third angle.
Definition at line 227 of file EulerAngles.h.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType().
gamma() [2/2]
template<typename _Scalar, class _System> Scalar& Eigen::EulerAngles< _Scalar, _System >::gamma () inline
Returns
A read-write reference to the angle of the third angle.
Definition at line 229 of file EulerAngles.h.
GammaAxisVector()
template<typename _Scalar, class _System> static Vector3 Eigen::EulerAngles< _Scalar, _System >::GammaAxisVector () inline static
Returns
the axis vector of the third (gamma) rotation
Definition at line 138 of file EulerAngles.h.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType().
inverse()
template<typename _Scalar, class _System> EulerAngles Eigen::EulerAngles< _Scalar, _System >::inverse () const inline
Returns
The Euler angles rotation inverse (which is as same as the negative), (-alpha, -beta, -gamma).
Definition at line 234 of file EulerAngles.h.
References res.
Referenced by Eigen::EulerAngles< _Scalar, _System >::operator-().
operator QuaternionType()
template<typename _Scalar, class _System> Eigen::EulerAngles< _Scalar, _System >::operator QuaternionType () const inline
Convert the Euler angles to quaternion.
Definition at line 337 of file EulerAngles.h.
References Eigen::EulerAngles< _Scalar, _System >::alpha(), Eigen::EulerAngles< _Scalar, _System >::AlphaAxisVector(), Eigen::EulerAngles< _Scalar, _System >::beta(), Eigen::EulerAngles< _Scalar, _System >::BetaAxisVector(), Eigen::EulerAngles< _Scalar, _System >::gamma(), and Eigen::EulerAngles< _Scalar, _System >::GammaAxisVector().
operator-()
template<typename _Scalar, class _System> EulerAngles Eigen::EulerAngles< _Scalar, _System >::operator- () const inline
Returns
The Euler angles rotation negative (which is as same as the inverse), (-alpha, -beta, -gamma).
Definition at line 244 of file EulerAngles.h.
References Eigen::EulerAngles< _Scalar, _System >::inverse().
operator=() [1/2]
template<typename _Scalar, class _System> template<typename Derived > EulerAngles& Eigen::EulerAngles< _Scalar, _System >::operator= (const MatrixBase< Derived > & m) inline
Set *this from a rotation matrix(i.e. pure orthogonal matrix with determinant of +1).
Definition at line 312 of file EulerAngles.h.
References EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_SIZE.
operator=() [2/2]
template<typename _Scalar, class _System> template<typename Derived > EulerAngles& Eigen::EulerAngles< _Scalar, _System >::operator= (const RotationBase< Derived, 3 > & rot) inline
Set *this from a rotation.
Definition at line 323 of file EulerAngles.h.
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
toRotationMatrix()
template<typename _Scalar, class _System> Matrix3 Eigen::EulerAngles< _Scalar, _System >::toRotationMatrix (void) const inline
Returns
an equivalent 3x3 rotation matrix.
Definition at line 331 of file EulerAngles.h.
Friends And Related Function Documentation
operator<<
template<typename _Scalar, class _System> std::ostream& operator<< (std::ostream & s, const EulerAngles< Scalar, System > & eulerAngles) friend
Definition at line 345 of file EulerAngles.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/EulerAngles/EulerAngles.h