pairinteraction: testing::Benchmark Class Reference
testing::Benchmark Class Reference
#include <benchmark.h>
Public Member Functions
Benchmark (const char *name, void(*fn)(int))
Benchmark (const char *name, void(*fn_range)(int, int))
Benchmark * Arg (int x)
Benchmark * Range (int lo, int hi)
const char * Name ()
bool ShouldRun (int argc, char *argv[])
void Run ()
Detailed Description
Definition at line 21 of file benchmark.h.
Constructor & Destructor Documentation
Benchmark() [1/2]
testing::Benchmark::Benchmark (const char * name, void(*)(int) fn) inline
Definition at line 23 of file benchmark.h.
Benchmark() [2/2]
testing::Benchmark::Benchmark (const char * name, void(*)(int, int) fn_range) inline
Definition at line 26 of file benchmark.h.
References Arg(), arg(), int(), Name(), Range(), Run(), SetBenchmarkFlopsProcessed(), ShouldRun(), StartBenchmarkTiming(), StopBenchmarkTiming(), and x.
Member Function Documentation
Arg()
Benchmark * testing::Benchmark::Arg (int x)
Definition at line 74 of file benchmark_main.cc.
Referenced by Benchmark().
Name()
const char * testing::Benchmark::Name ()
Definition at line 95 of file benchmark_main.cc.
Referenced by Benchmark().
Range()
Benchmark * testing::Benchmark::Range (int lo, int hi)
Definition at line 79 of file benchmark_main.cc.
Referenced by Benchmark().
Run()
void testing::Benchmark::Run ()
Definition at line 128 of file benchmark_main.cc.
References arg(), and i.
Referenced by Benchmark().
ShouldRun()
bool testing::Benchmark::ShouldRun (int argc, char * argv[])
Definition at line 98 of file benchmark_main.cc.
References gBenchmarks(), and i.
Referenced by Benchmark().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/bench/tensors/benchmark.h
/travis/libpairinteraction/eigen/bench/tensors/benchmark_main.cc