pairinteraction: BtlString Class Reference
BtlString Class Reference
#include <btl.hh>
Public Member Functions
BtlString ()
BtlString (const BtlString &str)
BtlString (const std::string &str)
BtlString (const char *str)
operator const char * () const
void trim (bool left=true, bool right=true)
std::vector< BtlString > split (const BtlString &delims="\ ") const
bool endsWith (const BtlString &str) const
bool contains (const BtlString &str) const
bool beginsWith (const BtlString &str) const
BtlString toLowerCase (void)
BtlString toUpperCase (void)
bool isEquiv (const BtlString &str) const
void decomposePathAndFile (BtlString &path, BtlString &filename) const
Detailed Description
Enhanced std::string
Definition at line 57 of file btl.hh.
Constructor & Destructor Documentation
BtlString() [1/4]
BtlString::BtlString () inline
Definition at line 60 of file btl.hh.
Referenced by BtlConfig::BtlConfig().
BtlString() [2/4]
BtlString::BtlString (const BtlString & str) inline
Definition at line 61 of file btl.hh.
BtlString() [3/4]
BtlString::BtlString (const std::string & str) inline
Definition at line 62 of file btl.hh.
BtlString() [4/4]
BtlString::BtlString (const char * str) inline
Definition at line 63 of file btl.hh.
Member Function Documentation
beginsWith()
bool BtlString::beginsWith (const BtlString & str) const inline
Definition at line 118 of file btl.hh.
References size.
Referenced by BtlConfig::BtlConfig().
contains()
bool BtlString::contains (const BtlString & str) const inline
Definition at line 114 of file btl.hh.
References size.
Referenced by BtlConfig::skipAction().
decomposePathAndFile()
void BtlString::decomposePathAndFile (BtlString & path, BtlString & filename) const inline
Decompose the current string as a path and a file. For instance: "dir1/dir2/file.ext" leads to path="dir1/dir2/" and filename="file.ext"
Definition at line 150 of file btl.hh.
References i, and split().
endsWith()
bool BtlString::endsWith (const BtlString & str) const inline
Definition at line 108 of file btl.hh.
References size.
isEquiv()
bool BtlString::isEquiv (const BtlString & str) const inline
Case insensitive comparison.
Definition at line 138 of file btl.hh.
References toLowerCase().
operator const char *()
BtlString::operator const char * () const inline
Definition at line 65 of file btl.hh.
split()
std::vector<BtlString> BtlString::split (const BtlString & delims = "\t\n ") const inline
Definition at line 81 of file btl.hh.
References ret.
Referenced by decomposePathAndFile().
toLowerCase()
BtlString BtlString::toLowerCase (void) inline
Definition at line 125 of file btl.hh.
References transform().
Referenced by isEquiv().
toUpperCase()
BtlString BtlString::toUpperCase (void) inline
Definition at line 130 of file btl.hh.
References transform().
trim()
void BtlString::trim (bool left = true, bool right = true) inline
Definition at line 67 of file btl.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/btl.hh