pairinteraction: Eigen::SimpleThreadPoolTempl< Environment > Class Template Reference
Eigen::SimpleThreadPoolTempl< Environment > Class Template Reference
#include <SimpleThreadPool.h>
Public Member Functions
SimpleThreadPoolTempl (int num_threads, Environment env=Environment())
~SimpleThreadPoolTempl ()
void Schedule (std::function< void()> fn) final
int NumThreads () const final
int CurrentThreadId () const final
Public Member Functions inherited from Eigen::ThreadPoolInterface
virtual ~ThreadPoolInterface ()
Protected Member Functions
void WorkerLoop (int thread_id)
Detailed Description
template<typename Environment>
class Eigen::SimpleThreadPoolTempl< Environment >
Definition at line 21 of file SimpleThreadPool.h.
Constructor & Destructor Documentation
SimpleThreadPoolTempl()
template<typename Environment > Eigen::SimpleThreadPoolTempl< Environment >::SimpleThreadPoolTempl (int num_threads, Environment env = Environment()) inline explicit
Definition at line 24 of file SimpleThreadPool.h.
References i, and Eigen::MaxSizeVector< T >::push_back().
~SimpleThreadPoolTempl()
template<typename Environment > Eigen::SimpleThreadPoolTempl< Environment >::~SimpleThreadPoolTempl () inline
Definition at line 33 of file SimpleThreadPool.h.
References w.
Member Function Documentation
CurrentThreadId()
template<typename Environment > int Eigen::SimpleThreadPoolTempl< Environment >::CurrentThreadId () const inline final virtual
Implements Eigen::ThreadPoolInterface.
Definition at line 76 of file SimpleThreadPool.h.
NumThreads()
template<typename Environment > int Eigen::SimpleThreadPoolTempl< Environment >::NumThreads () const inline final virtual
Implements Eigen::ThreadPoolInterface.
Definition at line 72 of file SimpleThreadPool.h.
References Eigen::MaxSizeVector< T >::size().
Schedule()
template<typename Environment > void Eigen::SimpleThreadPoolTempl< Environment >::Schedule (std::function< void()> fn) inline final virtual
Implements Eigen::ThreadPoolInterface.
Definition at line 58 of file SimpleThreadPool.h.
References Eigen::MaxSizeVector< T >::back(), Eigen::MaxSizeVector< T >::empty(), Eigen::MaxSizeVector< T >::pop_back(), and w.
WorkerLoop()
template<typename Environment > void Eigen::SimpleThreadPoolTempl< Environment >::WorkerLoop (int thread_id) inline protected
Definition at line 86 of file SimpleThreadPool.h.
References EIGEN_THREAD_LOCAL, Eigen::MaxSizeVector< T >::push_back(), and w.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/ThreadPool/SimpleThreadPool.h