pairinteraction: Eigen::DenseBase< Derived > Class Template Reference
Eigen::DenseBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for all dense matrices, vectors, and arrays.
#include <DenseBase.h>
Data Structures
struct ConstFixedBlockXpr
struct ConstFixedSegmentReturnType
struct ConstNColsBlockXpr
struct ConstNRowsBlockXpr
struct FixedBlockXpr
struct FixedSegmentReturnType
struct NColsBlockXpr
struct NRowsBlockXpr
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime, Flags = internal::traits<Derived>::Flags,
IsRowMajor = int(Flags) & RowMajorBit, InnerSizeAtCompileTime, InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret, OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef internal::conditional< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray >::type PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > SequentialLinSpacedReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< const Derived > >::type ConstTransposeReturnType
typedef internal::add_const_on_value_type< typename internal::eval< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Public Member Functions
EIGEN_DEVICE_FUNC Index nonZeros () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool hasNaN () const
bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block(Index,Index,Index,Index). */.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomRightCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomLeftCorner (Index cRows, Index cCols)
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
EIGEN_DEVICE_FUNC RowsBlockXpr topRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr topRows (Index n) const
This is the const version of topRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr bottomRows (Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr bottomRows (Index n) const
This is the const version of bottomRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr middleRows (Index startRow, Index n)
EIGEN_DEVICE_FUNC ConstRowsBlockXpr middleRows (Index startRow, Index n) const
This is the const version of middleRows(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr leftCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr leftCols (Index n) const
This is the const version of leftCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr rightCols (Index n)
EIGEN_DEVICE_FUNC ConstColsBlockXpr rightCols (Index n) const
This is the const version of rightCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr middleCols (Index startCol, Index numCols)
EIGEN_DEVICE_FUNC ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
This is the const version of middleCols(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). */.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i)
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i)
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) const
This is the const version of row(). */.
EIGEN_DEVICE_FUNC SegmentReturnType segment (Index start, Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType segment (Index start, Index n) const
This is the const version of segment(Index,Index).
EIGEN_DEVICE_FUNC SegmentReturnType head (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType head (Index n) const
This is the const version of head(Index).
EIGEN_DEVICE_FUNC SegmentReturnType tail (Index n)
EIGEN_DEVICE_FUNC ConstSegmentReturnType tail (Index n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
template<typename Func >
internal::traits< Derived >::Scalar redux (const Func &func) const
template<int RowFactor, int ColFactor>
const Replicate< Derived, RowFactor, ColFactor > replicate () const
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
Static Public Member Functions
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Member Functions
EIGEN_DEVICE_FUNC DenseBase ()
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::DenseBase< Derived >
Base class for all dense matrices, vectors, and arrays.
This class is the base that is inherited by all dense objects (matrix, vector, arrays, and related expression types). The common Eigen API for dense objects is contained in this class.
Template Parameters
Derived is the derived type, e.g., a matrix type or an expression.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_DENSEBASE_PLUGIN.
See also
The class hierarchy
Definition at line 41 of file DenseBase.h.
Member Typedef Documentation
Base
template<typename Derived> typedef DenseCoeffsBase<Derived> Eigen::DenseBase< Derived >::Base
Definition at line 74 of file DenseBase.h.
BlockXpr
template<typename Derived> typedef Block<Derived> Eigen::DenseBase< Derived >::BlockXpr
Definition at line 33 of file DenseBase.h.
CoeffReturnType
template<typename Derived> typedef Base::CoeffReturnType Eigen::DenseBase< Derived >::CoeffReturnType
Definition at line 96 of file DenseBase.h.
ColsBlockXpr
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::DenseBase< Derived >::ColsBlockXpr
Definition at line 21 of file DenseBase.h.
ColwiseReturnType
template<typename Derived> typedef VectorwiseOp<Derived, Vertical> Eigen::DenseBase< Derived >::ColwiseReturnType
Definition at line 493 of file DenseBase.h.
ColXpr
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::DenseBase< Derived >::ColXpr
Definition at line 15 of file DenseBase.h.
ConstantReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,PlainObject> Eigen::DenseBase< Derived >::ConstantReturnType
Definition at line 262 of file DenseBase.h.
ConstBlockXpr
template<typename Derived> typedef const Block<const Derived> Eigen::DenseBase< Derived >::ConstBlockXpr
Definition at line 34 of file DenseBase.h.
ConstColsBlockXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::DenseBase< Derived >::ConstColsBlockXpr
Definition at line 22 of file DenseBase.h.
ConstColwiseReturnType
template<typename Derived> typedef const VectorwiseOp<const Derived, Vertical> Eigen::DenseBase< Derived >::ConstColwiseReturnType
Definition at line 494 of file DenseBase.h.
ConstColXpr
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::DenseBase< Derived >::ConstColXpr
Definition at line 16 of file DenseBase.h.
ConstReverseReturnType
template<typename Derived> typedef const Reverse<const Derived, BothDirections> Eigen::DenseBase< Derived >::ConstReverseReturnType
Definition at line 560 of file DenseBase.h.
ConstRowsBlockXpr
template<typename Derived> typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::ConstRowsBlockXpr
Definition at line 25 of file DenseBase.h.
ConstRowwiseReturnType
template<typename Derived> typedef const VectorwiseOp<const Derived, Horizontal> Eigen::DenseBase< Derived >::ConstRowwiseReturnType
Definition at line 492 of file DenseBase.h.
ConstRowXpr
template<typename Derived> typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::ConstRowXpr
Definition at line 19 of file DenseBase.h.
ConstSegmentReturnType
template<typename Derived> typedef const VectorBlock<const Derived> Eigen::DenseBase< Derived >::ConstSegmentReturnType
Definition at line 40 of file DenseBase.h.
ConstTransposeReturnType
template<typename Derived> typedef internal::add_const<Transpose<const Derived> >::type Eigen::DenseBase< Derived >::ConstTransposeReturnType
Definition at line 322 of file DenseBase.h.
EigenvaluesReturnType
template<typename Derived> typedef Matrix<typename NumTraits<typename internal::traits<Derived>::Scalar>::Real, internal::traits<Derived>::ColsAtCompileTime, 1> Eigen::DenseBase< Derived >::EigenvaluesReturnType
Definition at line 268 of file DenseBase.h.
EvalReturnType
template<typename Derived> typedef internal::add_const_on_value_type<typename internal::eval<Derived>::type>::type Eigen::DenseBase< Derived >::EvalReturnType
Definition at line 392 of file DenseBase.h.
InnerIterator
template<typename Derived> typedef Eigen::InnerIterator<Derived> Eigen::DenseBase< Derived >::InnerIterator
Inner iterator type to iterate over the coefficients of a row or column.
See also
class InnerIterator
Definition at line 53 of file DenseBase.h.
PacketScalar
template<typename Derived> typedef internal::find_best_packet<Scalar,SizeAtCompileTime>::type Eigen::DenseBase< Derived >::PacketScalar
Definition at line 174 of file DenseBase.h.
PlainArray
template<typename Derived> typedef Array<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainArray
The plain array type corresponding to this expression.
See also
PlainObject
Definition at line 196 of file DenseBase.h.
PlainMatrix
template<typename Derived> typedef Matrix<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainMatrix
The plain matrix type corresponding to this expression.
See also
PlainObject
Definition at line 186 of file DenseBase.h.
PlainObject
template<typename Derived> typedef internal::conditional<internal::is_same<typename internal::traits<Derived>::XprKind,MatrixXpr >::value, PlainMatrix, PlainArray>::type Eigen::DenseBase< Derived >::PlainObject
The plain matrix or array type corresponding to this expression.
This is not necessarily exactly the return type of eval(). In the case of plain matrices, the return type of eval() is a const reference to a matrix, not a matrix! It is however guaranteed that the return type of eval() is either PlainObject or const PlainObject&.
Definition at line 205 of file DenseBase.h.
RandomAccessLinSpacedReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::RandomAccessLinSpacedReturnType
Definition at line 266 of file DenseBase.h.
RandomReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_random_op<Scalar>,PlainObject> Eigen::DenseBase< Derived >::RandomReturnType
Definition at line 521 of file DenseBase.h.
RealScalar
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::DenseBase< Derived >::RealScalar
Definition at line 73 of file DenseBase.h.
ReverseReturnType
template<typename Derived> typedef Reverse<Derived, BothDirections> Eigen::DenseBase< Derived >::ReverseReturnType
Definition at line 559 of file DenseBase.h.
RowsBlockXpr
template<typename Derived> typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::RowsBlockXpr
Definition at line 24 of file DenseBase.h.
RowwiseReturnType
template<typename Derived> typedef VectorwiseOp<Derived, Horizontal> Eigen::DenseBase< Derived >::RowwiseReturnType
Definition at line 491 of file DenseBase.h.
RowXpr
template<typename Derived> typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::RowXpr
Definition at line 18 of file DenseBase.h.
Scalar
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::Scalar
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
Definition at line 66 of file DenseBase.h.
SegmentReturnType
template<typename Derived> typedef VectorBlock<Derived> Eigen::DenseBase< Derived >::SegmentReturnType
Definition at line 39 of file DenseBase.h.
SequentialLinSpacedReturnType
template<typename Derived> typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::SequentialLinSpacedReturnType
Definition at line 264 of file DenseBase.h.
StorageIndex
template<typename Derived> typedef internal::traits<Derived>::StorageIndex Eigen::DenseBase< Derived >::StorageIndex
The type used to store indices.
This typedef is relevant for types that store multiple indices such as PermutationMatrix or Transpositions, otherwise it defaults to Eigen::Index
See also
Preprocessor directives, Eigen::Index, SparseMatrixBase.
Definition at line 63 of file DenseBase.h.
StorageKind
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::DenseBase< Derived >::StorageKind
Definition at line 55 of file DenseBase.h.
TransposeReturnType
template<typename Derived> typedef Transpose<Derived> Eigen::DenseBase< Derived >::TransposeReturnType
Definition at line 319 of file DenseBase.h.
value_type
template<typename Derived> typedef Scalar Eigen::DenseBase< Derived >::value_type
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Definition at line 71 of file DenseBase.h.
Member Enumeration Documentation
anonymous enum
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
InnerSizeAtCompileTime
InnerStrideAtCompileTime
OuterStrideAtCompileTime
Definition at line 98 of file DenseBase.h.
anonymous enum
template<typename Derived> anonymous enum
Enumerator
IsPlainObjectBase
Definition at line 176 of file DenseBase.h.
Constructor & Destructor Documentation
DenseBase()
template<typename Derived> EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase () inline protected
Default constructor. Do nothing.
Definition at line 591 of file DenseBase.h.
References EIGEN_IMPLIES, and EIGEN_STATIC_ASSERT.
Member Function Documentation
all()
template<typename Derived > bool Eigen::DenseBase< Derived >::all () const inline
Returns
true if all coefficients are true
Example:
Output:
See also
any(), Cwise::operator<()
Definition at line 81 of file BooleanRedux.h.
References cols, Eigen::Dynamic, EIGEN_UNROLLING_LIMIT, i, j, and rows.
allFinite()
template<typename Derived > bool Eigen::DenseBase< Derived >::allFinite () const inline
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See also
hasNaN()
Definition at line 153 of file BooleanRedux.h.
any()
template<typename Derived > bool Eigen::DenseBase< Derived >::any () const inline
Returns
true if at least one coefficient is true
See also
all()
Definition at line 105 of file BooleanRedux.h.
References cols, Eigen::Dynamic, EIGEN_UNROLLING_LIMIT, i, j, and rows.
block() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Definition at line 65 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
block() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block(Index,Index,Index,Index). */.
Definition at line 72 of file DenseBase.h.
block() [3/6]
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
class Block, block(Index,Index,Index,Index)
Definition at line 781 of file DenseBase.h.
block() [4/6]
template<typename Derived> template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). */.
Definition at line 789 of file DenseBase.h.
block() [5/6]
template<typename Derived> template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block in *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 816 of file DenseBase.h.
block() [6/6]
template<typename Derived> template<int NRows, int NCols> const ConstFixedBlockXpr<NRows,NCols>::Type Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
Definition at line 824 of file DenseBase.h.
bottomLeftCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 349 of file DenseBase.h.
bottomLeftCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner(Index, Index).
Definition at line 356 of file DenseBase.h.
bottomLeftCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 374 of file DenseBase.h.
bottomLeftCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
Definition at line 382 of file DenseBase.h.
bottomLeftCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 407 of file DenseBase.h.
bottomLeftCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
Definition at line 414 of file DenseBase.h.
bottomRightCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 264 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
bottomRightCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner(Index, Index).
Definition at line 271 of file DenseBase.h.
bottomRightCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 289 of file DenseBase.h.
bottomRightCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
Definition at line 297 of file DenseBase.h.
bottomRightCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 322 of file DenseBase.h.
bottomRightCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
Definition at line 329 of file DenseBase.h.
bottomRows() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC RowsBlockXpr Eigen::DenseBase< Derived >::bottomRows (Index n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 489 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
bottomRows() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowsBlockXpr Eigen::DenseBase< Derived >::bottomRows (Index n) const inline
This is the const version of bottomRows(Index).
Definition at line 496 of file DenseBase.h.
bottomRows() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 518 of file DenseBase.h.
bottomRows() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
Definition at line 526 of file DenseBase.h.
col() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC ColXpr Eigen::DenseBase< Derived >::col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
Definition at line 839 of file DenseBase.h.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::_solve_impl(), and Eigen::UmfPackLU< _MatrixType >::_solve_impl().
col() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColXpr Eigen::DenseBase< Derived >::col (Index i) const inline
This is the const version of col().
Definition at line 846 of file DenseBase.h.
colwise() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColwiseReturnType Eigen::DenseBase< Derived >::colwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 516 of file DenseBase.h.
Referenced by Eigen::umeyama().
colwise() [2/2]
template<typename Derived > DenseBase< Derived >::ColwiseReturnType Eigen::DenseBase< Derived >::colwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 674 of file VectorwiseOp.h.
Constant() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index rows, Index cols, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Definition at line 174 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
Constant() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index size, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Definition at line 196 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
Constant() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (const Scalar & value) static
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Definition at line 212 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
count()
template<typename Derived > Eigen::Index Eigen::DenseBase< Derived >::count () const inline
Returns
the number of coefficients which evaluate to true
See also
all(), any()
Definition at line 129 of file BooleanRedux.h.
eval()
template<typename Derived> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType Eigen::DenseBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Warning
Be carefull with eval() and the auto C++ keyword, as detailed in this page .
Definition at line 401 of file DenseBase.h.
Referenced by Eigen::internal::generic_product_impl< Lhs, Homogeneous< RhsArg, Vertical >, TriangularShape, HomogeneousShape, ProductTag >::evalTo().
evalTo()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::evalTo (Dest &) const inline
Definition at line 584 of file DenseBase.h.
fill()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::fill (const Scalar & val)
Alias for setConstant(): sets all coefficients in this expression to val.
See also
setConstant(), Constant(), class CwiseNullaryOp
Definition at line 315 of file CwiseNullaryOp.h.
References setConstant().
flagged()
template<typename Derived> template<unsigned int Added, unsigned int Removed> EIGEN_DEPRECATED const Derived& Eigen::DenseBase< Derived >::flagged () const inline
Deprecated:
it now returns *this
Definition at line 312 of file DenseBase.h.
forceAlignedAccess() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC const ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () const inline
forceAlignedAccess() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () inline
forceAlignedAccessIf() [1/2]
template<typename Derived> template<bool Enable> EIGEN_DEVICE_FUNC const internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () const inline
forceAlignedAccessIf() [2/2]
template<typename Derived> template<bool Enable> EIGEN_DEVICE_FUNC internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () inline
format()
template<typename Derived> const WithFormat<Derived> Eigen::DenseBase< Derived >::format (const IOFormat & fmt) const inline
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See also
class IOFormat, class WithFormat
Definition at line 473 of file DenseBase.h.
hasNaN()
template<typename Derived > bool Eigen::DenseBase< Derived >::hasNaN () const inline
Returns
true is *this contains at least one Not A Number (NaN).
See also
allFinite()
Definition at line 139 of file BooleanRedux.h.
head() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC SegmentReturnType Eigen::DenseBase< Derived >::head (Index n) inline
Returns
a dynamic-size expression of the first coefficients of *this.
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Definition at line 920 of file DenseBase.h.
head() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstSegmentReturnType Eigen::DenseBase< Derived >::head (Index n) const inline
This is the const version of head(Index).
Definition at line 928 of file DenseBase.h.
head() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 1014 of file DenseBase.h.
head() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::head (Index n = N) const inline
This is the const version of head<int>().
Definition at line 1023 of file DenseBase.h.
innerSize()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::innerSize () const inline
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
Definition at line 230 of file DenseBase.h.
References cols, int(), rows, and size.
isApprox() [1/2]
template<typename Derived> template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec) const
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors \(v \) and \(w \) are considered to be approximately equal within precision \(p \) if
\[ \Vert v - w \Vert \leqslant p\,\min(\Vert v\Vert, \Vert w\Vert). \]
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
Definition at line 103 of file Fuzzy.h.
References Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run().
isApprox() [2/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const
isApproxToConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
Definition at line 290 of file CwiseNullaryOp.h.
References cols, i, Eigen::DenseBase< Derived >::isConstant(), j, and rows.
Referenced by Eigen::DenseBase< Derived >::LinSpaced().
isConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
Definition at line 305 of file CwiseNullaryOp.h.
Referenced by Eigen::DenseBase< Derived >::isApproxToConstant().
isMuchSmallerThan() [1/4]
template<typename Derived> template<typename Derived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector \(v \) is considered to be much smaller than \(x \) within precision \(p \) if
\[ \Vert v \Vert \leqslant p\,\vert x\vert. \]
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
Definition at line 125 of file Fuzzy.h.
References Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run().
isMuchSmallerThan() [2/4]
template<typename Derived> template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec) const
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector \(v \) is considered to be much smaller than a vector \(w \) within precision \(p \) if
\[ \Vert v \Vert \leqslant p\,\Vert w\Vert. \]
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
Definition at line 145 of file Fuzzy.h.
References Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run().
isMuchSmallerThan() [3/4]
template<typename Derived> EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const RealScalar & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const
Referenced by Eigen::test_isMuchSmallerThan().
isMuchSmallerThan() [4/4]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const
isOnes()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
Definition at line 612 of file CwiseNullaryOp.h.
Referenced by Eigen::DenseBase< Derived >::Ones().
isZero()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
Definition at line 481 of file CwiseNullaryOp.h.
References cols, i, j, and rows.
lazyAssign() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
Definition at line 20 of file Assign.h.
References Eigen::internal::call_assignment_no_alias(), cols, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_LVALUE, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, and rows.
lazyAssign() [2/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
leftCols() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC ColsBlockXpr Eigen::DenseBase< Derived >::leftCols (Index n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 603 of file DenseBase.h.
leftCols() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColsBlockXpr Eigen::DenseBase< Derived >::leftCols (Index n) const inline
This is the const version of leftCols(Index).
Definition at line 610 of file DenseBase.h.
leftCols() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 632 of file DenseBase.h.
leftCols() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
Definition at line 640 of file DenseBase.h.
LinSpaced() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) static
Deprecated:
because of accuracy loss. In Eigen 3.3, it is an alias for LinSpaced(Index,const Scalar&,const Scalar&)
See also
LinSpaced(Index,Scalar,Scalar), setLinSpaced(Index,const Scalar&,const Scalar&)
Definition at line 224 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Index size, const Scalar & low, const Scalar & high) static
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
Definition at line 268 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) static
Deprecated:
because of accuracy loss. In Eigen 3.3, it is an alias for LinSpaced(const Scalar&,const Scalar&)
See also
LinSpaced(Scalar,Scalar)
Definition at line 236 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (const Scalar & low, const Scalar & high) static
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
Definition at line 280 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::DenseBase< Derived >::isApproxToConstant(), and Eigen::DenseBase< Derived >::NullaryExpr().
lpNorm()
template<typename Derived> template<int p> RealScalar Eigen::DenseBase< Derived >::lpNorm () const
maxCoeff() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff () const
Returns
the maximum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
Definition at line 436 of file Redux.h.
References EIGEN_STRONG_INLINE.
maxCoeff() [2/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * rowId, IndexType * colId) const
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::maxCoeff()
Definition at line 244 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
maxCoeff() [3/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const
Returns
the maximum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
Definition at line 262 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
mean()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::mean () const
Returns
the mean of all coefficients of *this
See also
trace(), prod(), sum()
Definition at line 462 of file Redux.h.
References EIGEN_STRONG_INLINE, and size.
middleCols() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC ColsBlockXpr Eigen::DenseBase< Derived >::middleCols (Index startCol, Index numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 716 of file DenseBase.h.
middleCols() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColsBlockXpr Eigen::DenseBase< Derived >::middleCols (Index startCol, Index numCols) const inline
This is the const version of middleCols(Index,Index).
Definition at line 723 of file DenseBase.h.
middleCols() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 746 of file DenseBase.h.
middleCols() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
Definition at line 754 of file DenseBase.h.
middleRows() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC RowsBlockXpr Eigen::DenseBase< Derived >::middleRows (Index startRow, Index n) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 546 of file DenseBase.h.
middleRows() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowsBlockXpr Eigen::DenseBase< Derived >::middleRows (Index startRow, Index n) const inline
This is the const version of middleRows(Index,Index).
Definition at line 553 of file DenseBase.h.
middleRows() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 576 of file DenseBase.h.
middleRows() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
Definition at line 584 of file DenseBase.h.
References EIGEN_STATIC_ASSERT.
minCoeff() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff () const
Returns
the minimum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
Definition at line 426 of file Redux.h.
References EIGEN_STRONG_INLINE.
minCoeff() [2/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * rowId, IndexType * colId) const
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visit(), DenseBase::minCoeff()
Definition at line 207 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
minCoeff() [3/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const
Returns
the minimum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::minCoeff()
Definition at line 225 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
nestByValue()
template<typename Derived > const NestByValue< Derived > Eigen::DenseBase< Derived >::nestByValue () const inline
Returns
an expression of the temporary version of *this.
Definition at line 103 of file NestByValue.h.
nonZeros()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
Definition at line 210 of file DenseBase.h.
References size.
NullaryExpr() [1/6]
template<typename Derived> template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Definition at line 109 of file CwiseNullaryOp.h.
References cols, EIGEN_STRONG_INLINE, and rows.
NullaryExpr() [2/6]
template<typename Derived> template<typename CustomNullaryOp > EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
Here is an example with C++11 random generators:
Output:
See also
class CwiseNullaryOp
Definition at line 135 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, and size.
NullaryExpr() [3/6]
template<typename Derived> template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Definition at line 154 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE.
NullaryExpr() [4/6]
template<typename Derived> template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) static
Referenced by Eigen::DenseBase< Derived >::Constant(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::Identity(), and Eigen::DenseBase< Derived >::LinSpaced().
NullaryExpr() [5/6]
template<typename Derived> template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) static
NullaryExpr() [6/6]
template<typename Derived> template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) static
Ones() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index rows, Index cols) static
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index), isOnes(), class Ones
Definition at line 557 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE.
Ones() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index newSize) static
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index,Index), isOnes(), class Ones
Definition at line 580 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE.
Ones() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones () static
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
Definition at line 597 of file CwiseNullaryOp.h.
References Eigen::DenseBase< Derived >::isOnes().
operator*=()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator*= (const Scalar & other)
Definition at line 18 of file SelfCwiseBinaryOp.h.
References Eigen::internal::call_assignment(), cols, and rows.
operator+=()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
Definition at line 142 of file EigenBase.h.
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator-=()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
Definition at line 151 of file EigenBase.h.
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator/=()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator/= (const Scalar & other)
Definition at line 42 of file SelfCwiseBinaryOp.h.
References Eigen::internal::call_assignment(), cols, and rows.
operator<<() [1/3]
template<typename Derived> template<typename OtherDerived > CommaInitializer<Derived> Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inline
See also
operator<<(const Scalar&)
Definition at line 153 of file CommaInitializer.h.
operator<<() [2/3]
template<typename Derived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const Scalar & s) inline
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Output:
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See also
CommaInitializer::finished(), class CommaInitializer
Definition at line 144 of file CommaInitializer.h.
operator<<() [3/3]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC CommaInitializer<Derived> Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other)
operator=() [1/5]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
Definition at line 82 of file ReturnByValue.h.
References Eigen::ReturnByValue< Derived >::evalTo().
operator=() [2/5]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Copies other into *this.
Returns
a reference to *this.
Definition at line 39 of file Assign.h.
References Eigen::internal::call_assignment().
operator=() [3/5]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< Derived > & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
Definition at line 47 of file Assign.h.
References Eigen::internal::call_assignment().
operator=() [4/5]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
Definition at line 133 of file EigenBase.h.
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator=() [5/5]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & func)
outerSize()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::outerSize () const inline
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
Definition at line 218 of file DenseBase.h.
References cols, int(), and rows.
prod()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::prod () const
Returns
the product of all coefficients of *this
Example:
Output:
See also
sum(), mean(), trace()
Definition at line 483 of file Redux.h.
References Eigen::Dynamic, EIGEN_STRONG_INLINE, and size.
Random() [1/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index rows, Index cols) inline static
Returns
a random matrix expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See DenseBase::NullaryExpr(Index, const CustomNullaryOp&) for an example using C++11 random generators.
See also
DenseBase::setRandom(), DenseBase::Random(Index), DenseBase::Random()
Definition at line 56 of file Random.h.
Random() [2/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index size) inline static
Returns
a random vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random()
Definition at line 87 of file Random.h.
Random() [3/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random () inline static
Returns
a fixed-size random matrix or vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random(Index)
Definition at line 113 of file Random.h.
redux() [1/2]
template<typename Derived> template<typename Func > internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::redux (const Func & func) const
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current C++98 and C++11 functor styles are handled.
See also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
Definition at line 411 of file Redux.h.
References cols, eigen_assert, EIGEN_STRONG_INLINE, rows, and Eigen::TensorSycl::run().
redux() [2/2]
template<typename Derived> template<typename BinaryOp > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::redux (const BinaryOp & func) const
Referenced by Eigen::internal::member_redux< BinaryOp, Scalar >::operator()().
replicate() [1/3]
template<typename Derived> template<int RowFactor, int ColFactor> const Replicate<Derived,RowFactor,ColFactor> Eigen::DenseBase< Derived >::replicate () const
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
Definition at line 119 of file Replicate.h.
replicate() [2/3]
template<typename Derived> template<int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC const Replicate<Derived,RowFactor,ColFactor> Eigen::DenseBase< Derived >::replicate () const
replicate() [3/3]
template<typename Derived> EIGEN_DEVICE_FUNC const Replicate<Derived, Dynamic, Dynamic> Eigen::DenseBase< Derived >::replicate (Index rowFactor, Index colFactor) const inline
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
Definition at line 554 of file DenseBase.h.
resize() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index newSize) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
Definition at line 241 of file DenseBase.h.
References EIGEN_ONLY_USED_FOR_DEBUG.
Referenced by Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::evalToLazy().
resize() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index rows, Index cols) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
Definition at line 252 of file DenseBase.h.
References cols, eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and rows.
reverse() [1/2]
template<typename Derived > DenseBase< Derived >::ReverseReturnType Eigen::DenseBase< Derived >::reverse () inline
Returns
an expression of the reverse of *this.
Example:
Output:
Definition at line 118 of file Reverse.h.
reverse() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstReverseReturnType Eigen::DenseBase< Derived >::reverse () const inline
This is the const version of reverse().
Definition at line 564 of file DenseBase.h.
reverseInPlace()
template<typename Derived > void Eigen::DenseBase< Derived >::reverseInPlace () inline
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional benefits:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API enables reverse operations without the need for a temporary
it allows future optimizations (cache friendliness, etc.)
See also
VectorwiseOp::reverseInPlace(), reverse()
Definition at line 139 of file Reverse.h.
References bottomRows(), col(), cols, leftCols(), reverse(), rightCols(), row(), rows, tail(), and topRows().
rightCols() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC ColsBlockXpr Eigen::DenseBase< Derived >::rightCols (Index n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 659 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
rightCols() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstColsBlockXpr Eigen::DenseBase< Derived >::rightCols (Index n) const inline
This is the const version of rightCols(Index).
Definition at line 666 of file DenseBase.h.
rightCols() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 688 of file DenseBase.h.
rightCols() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
Definition at line 696 of file DenseBase.h.
row() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC RowXpr Eigen::DenseBase< Derived >::row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
Definition at line 860 of file DenseBase.h.
Referenced by Eigen::SPQR< _MatrixType >::_solve_impl(), and regrrssion_bug_1410().
row() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowXpr Eigen::DenseBase< Derived >::row (Index i) const inline
This is the const version of row(). */.
Definition at line 867 of file DenseBase.h.
rowwise() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowwiseReturnType Eigen::DenseBase< Derived >::rowwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 504 of file DenseBase.h.
Referenced by Eigen::umeyama().
rowwise() [2/2]
template<typename Derived > DenseBase< Derived >::RowwiseReturnType Eigen::DenseBase< Derived >::rowwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 688 of file VectorwiseOp.h.
segment() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC SegmentReturnType Eigen::DenseBase< Derived >::segment (Index start, Index n) inline
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, segment(Index)
Definition at line 889 of file DenseBase.h.
segment() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstSegmentReturnType Eigen::DenseBase< Derived >::segment (Index start, Index n) const inline
This is the const version of segment(Index,Index).
Definition at line 898 of file DenseBase.h.
segment() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 982 of file DenseBase.h.
segment() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
Definition at line 991 of file DenseBase.h.
select() [1/3]
template<typename Derived > template<typename ThenDerived , typename ElseDerived > const Select< Derived, ThenDerived, ElseDerived > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
Output:
See also
class Select
Definition at line 124 of file Select.h.
select() [2/3]
template<typename Derived > template<typename ThenDerived > const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const typename ThenDerived::Scalar & elseScalar) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
Definition at line 138 of file Select.h.
References cols, and rows.
select() [3/3]
template<typename Derived > template<typename ElseDerived > const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > Eigen::DenseBase< Derived >::select (const typename ElseDerived::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
Definition at line 153 of file Select.h.
References cols, and rows.
setConstant()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setConstant (const Scalar & val)
Sets all coefficients in this expression to value val.
See also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
Definition at line 325 of file CwiseNullaryOp.h.
References cols, EIGEN_STRONG_INLINE, and rows.
Referenced by Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::operator=().
setLinSpaced() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (Index newSize, const Scalar & low, const Scalar & high)
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
Definition at line 383 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setLinSpaced() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (const Scalar & low, const Scalar & high)
Sets a linearly spaced vector.
The function fills *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
Definition at line 403 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, EIGEN_STRONG_INLINE, setLinSpaced(), and size.
setOnes()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setOnes ()
Sets all coefficients in this expression to one.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
Definition at line 625 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE, and setConstant().
setRandom()
template<typename Derived > Derived & Eigen::DenseBase< Derived >::setRandom () inline
Sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
Example:
Output:
See also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
Definition at line 131 of file Random.h.
References cols, EIGEN_STRONG_INLINE, and rows.
setZero()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setZero ()
Sets all coefficients in this expression to zero.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
Definition at line 499 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE, and setConstant().
Referenced by Eigen::MINRES< _MatrixType, _UpLo, _Preconditioner >::_solve_impl(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::evalTo(), Eigen::SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::evalTo(), and Eigen::InverseImpl< PermutationType, PermutationStorage >::evalTo().
sum()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::sum () const
Returns
the sum of all coefficients of *this
If *this is empty, then the value 0 is returned.
See also
trace(), prod(), mean()
Definition at line 449 of file Redux.h.
References Eigen::Dynamic, EIGEN_STRONG_INLINE, and size.
swap() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (const DenseBase< OtherDerived > & other) inline
swaps *this with the expression other.
Definition at line 414 of file DenseBase.h.
References Eigen::internal::call_assignment(), cols, eigen_assert, EIGEN_STATIC_ASSERT, and rows.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, false >::run().
swap() [2/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (PlainObjectBase< OtherDerived > & other) inline
swaps *this with the matrix or array other.
Definition at line 426 of file DenseBase.h.
References Eigen::internal::call_assignment(), cols, Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, rows, and Eigen::PlainObjectBase< Derived >::rows().
tail() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC SegmentReturnType Eigen::DenseBase< Derived >::tail (Index n) inline
Returns
a dynamic-size expression of the last coefficients of *this.
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Definition at line 950 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, true >::run(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
tail() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstSegmentReturnType Eigen::DenseBase< Derived >::tail (Index n) const inline
This is the const version of tail(Index).
Definition at line 958 of file DenseBase.h.
tail() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
Definition at line 1046 of file DenseBase.h.
tail() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType<N>::Type Eigen::DenseBase< Derived >::tail (Index n = N) const inline
This is the const version of tail<int>.
Definition at line 1055 of file DenseBase.h.
topLeftCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 179 of file DenseBase.h.
topLeftCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner(Index, Index).
Definition at line 186 of file DenseBase.h.
topLeftCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 204 of file DenseBase.h.
topLeftCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
Definition at line 212 of file DenseBase.h.
topLeftCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 237 of file DenseBase.h.
topLeftCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
Definition at line 244 of file DenseBase.h.
topRightCorner() [1/6]
template<typename Derived> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 93 of file DenseBase.h.
topRightCorner() [2/6]
template<typename Derived> EIGEN_DEVICE_FUNC const ConstBlockXpr Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner(Index, Index).
Definition at line 100 of file DenseBase.h.
topRightCorner() [3/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
See also
class Block, block<int,int>(Index,Index)
Definition at line 119 of file DenseBase.h.
topRightCorner() [4/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
Definition at line 127 of file DenseBase.h.
topRightCorner() [5/6]
template<typename Derived> template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
See also
class Block
Definition at line 152 of file DenseBase.h.
topRightCorner() [6/6]
template<typename Derived> template<int CRows, int CCols> const ConstFixedBlockXpr<CRows,CCols>::Type Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
Definition at line 159 of file DenseBase.h.
topRows() [1/4]
template<typename Derived> EIGEN_DEVICE_FUNC RowsBlockXpr Eigen::DenseBase< Derived >::topRows (Index n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 433 of file DenseBase.h.
Referenced by Eigen::SparseQR< _MatrixType, _OrderingType >::_solve_impl().
topRows() [2/4]
template<typename Derived> EIGEN_DEVICE_FUNC ConstRowsBlockXpr Eigen::DenseBase< Derived >::topRows (Index n) const inline
This is the const version of topRows(Index).
Definition at line 440 of file DenseBase.h.
topRows() [3/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block, block(Index,Index,Index,Index)
Definition at line 462 of file DenseBase.h.
topRows() [4/4]
template<typename Derived> template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::topRows (Index n = N) const inline
This is the const version of topRows<int>().
Definition at line 470 of file DenseBase.h.
trace()
template<typename Derived> EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::trace () const
transpose() [1/2]
template<typename Derived > Transpose< Derived > Eigen::DenseBase< Derived >::transpose () inline
Returns
an expression of the transpose of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See also
transposeInPlace(), adjoint()
Definition at line 172 of file Transpose.h.
Referenced by Eigen::internal::dot_nocheck< T, U, true >::run().
transpose() [2/2]
template<typename Derived > DenseBase< Derived >::ConstTransposeReturnType Eigen::DenseBase< Derived >::transpose () const inline
This is the const version of transpose().
Make sure you read the warning for transpose() !
See also
transposeInPlace(), adjoint()
Definition at line 184 of file Transpose.h.
transposeInPlace()
template<typename Derived > void Eigen::DenseBase< Derived >::transposeInPlace () inline
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), adjointInPlace()
Definition at line 284 of file Transpose.h.
References cols, Eigen::Dynamic, eigen_assert, rows, and Eigen::TensorSycl::run().
value()
template<typename Derived> EIGEN_DEVICE_FUNC CoeffReturnType Eigen::DenseBase< Derived >::value () const inline
Returns
the unique coefficient of a 1x1 expression
Definition at line 480 of file DenseBase.h.
References cols, eigen_assert, EIGEN_STATIC_ASSERT_SIZE_1x1, and rows.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::solve().
visit()
template<typename Derived > template<typename Visitor > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::visit (Visitor & visitor) const
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
Definition at line 107 of file Visitor.h.
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
Zero() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index rows, Index cols) static
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index)
Definition at line 427 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE.
Zero() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index size) static
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index,Index)
Definition at line 450 of file CwiseNullaryOp.h.
References EIGEN_STRONG_INLINE.
Zero() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero () static
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Zero(Index), Zero(Index,Index)
Definition at line 467 of file CwiseNullaryOp.h.
Friends And Related Function Documentation
operator<<()
template<typename Derived > std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See also
DenseBase::format()
Definition at line 217 of file IO.h.
References EIGEN_DEFAULT_IO_FORMAT, m, and Eigen::internal::print_matrix().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/DenseBase.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Assign.h
/travis/libpairinteraction/eigen/Eigen/src/Core/BooleanRedux.h
/travis/libpairinteraction/eigen/Eigen/src/Core/CommaInitializer.h
/travis/libpairinteraction/eigen/Eigen/src/Core/CwiseNullaryOp.h
/travis/libpairinteraction/eigen/Eigen/src/Core/EigenBase.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Fuzzy.h
/travis/libpairinteraction/eigen/Eigen/src/Core/IO.h
/travis/libpairinteraction/eigen/Eigen/src/Core/NestByValue.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Random.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Redux.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Replicate.h
/travis/libpairinteraction/eigen/Eigen/src/Core/ReturnByValue.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Reverse.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Select.h
/travis/libpairinteraction/eigen/Eigen/src/Core/SelfCwiseBinaryOp.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Transpose.h
/travis/libpairinteraction/eigen/Eigen/src/Core/VectorwiseOp.h
/travis/libpairinteraction/eigen/Eigen/src/Core/Visitor.h