pairinteraction: Eigen::FullPivHouseholderQR< _MatrixType > Class Template Reference
Eigen::FullPivHouseholderQR< _MatrixType > Class Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Householder rank-revealing QR decomposition of a matrix with full pivoting.
#include <ForwardDeclarations.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > MatrixQReturnType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime, MaxRowsAtCompileTime)> IntDiagSizeVectorType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_col_type< MatrixType >::type ColVectorType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
FullPivHouseholderQR ()
Default Constructor.
FullPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
FullPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
FullPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename Rhs >
const Solve< FullPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
MatrixQReturnType matrixQ (void) const
const MatrixType & matrixQR () const
template<typename InputType >
FullPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
const IntDiagSizeVectorType & rowsTranspositions () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< FullPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
FullPivHouseholderQR & setThreshold (const RealScalar &threshold)
FullPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename InputType >
FullPivHouseholderQR< MatrixType > & compute (const EigenBase< InputType > &matrix)
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
IntDiagSizeVectorType m_rows_transpositions
IntDiagSizeVectorType m_cols_transpositions
PermutationType m_cols_permutation
RowVectorType m_temp
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
RealScalar m_precision
Index m_det_pq
Detailed Description
template<typename _MatrixType>
class Eigen::FullPivHouseholderQR< _MatrixType >
Householder rank-revealing QR decomposition of a matrix with full pivoting.
Template Parameters
_MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, P', Q and R such that
\[ \mathbf{P} \, \mathbf{A} \, \mathbf{P}' = \mathbf{Q} \, \mathbf{R} \]
by using Householder transformations. Here, P and P' are permutation matrices, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs a very prudent full pivoting in order to be rank-revealing and achieve optimal numerical stability. The trade-off is that it is slower than HouseholderQR and ColPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::fullPivHouseholderQr()
Definition at line 256 of file ForwardDeclarations.h.
Member Typedef Documentation
ColVectorType
template<typename _MatrixType> typedef internal::plain_col_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::ColVectorType
Definition at line 79 of file FullPivHouseholderQR.h.
HCoeffsType
template<typename _MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::HCoeffsType
Definition at line 73 of file FullPivHouseholderQR.h.
IntDiagSizeVectorType
template<typename _MatrixType> typedef Matrix<StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime,RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime,MaxRowsAtCompileTime)> Eigen::FullPivHouseholderQR< _MatrixType >::IntDiagSizeVectorType
Definition at line 76 of file FullPivHouseholderQR.h.
MatrixQReturnType
template<typename _MatrixType> typedef internal::FullPivHouseholderQRMatrixQReturnType<MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::MatrixQReturnType
Definition at line 72 of file FullPivHouseholderQR.h.
MatrixType
template<typename _MatrixType> typedef _MatrixType Eigen::FullPivHouseholderQR< _MatrixType >::MatrixType
Definition at line 61 of file FullPivHouseholderQR.h.
PermutationType
template<typename _MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::FullPivHouseholderQR< _MatrixType >::PermutationType
Definition at line 77 of file FullPivHouseholderQR.h.
PlainObject
template<typename _MatrixType> typedef MatrixType::PlainObject Eigen::FullPivHouseholderQR< _MatrixType >::PlainObject
Definition at line 80 of file FullPivHouseholderQR.h.
RealScalar
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::RealScalar
Definition at line 69 of file FullPivHouseholderQR.h.
RowVectorType
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::RowVectorType
Definition at line 78 of file FullPivHouseholderQR.h.
Scalar
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::FullPivHouseholderQR< _MatrixType >::Scalar
Definition at line 68 of file FullPivHouseholderQR.h.
StorageIndex
template<typename _MatrixType> typedef MatrixType::StorageIndex Eigen::FullPivHouseholderQR< _MatrixType >::StorageIndex
Definition at line 71 of file FullPivHouseholderQR.h.
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 62 of file FullPivHouseholderQR.h.
Constructor & Destructor Documentation
FullPivHouseholderQR() [1/4]
template<typename _MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via FullPivHouseholderQR::compute(const MatrixType&).
Definition at line 87 of file FullPivHouseholderQR.h.
FullPivHouseholderQR() [2/4]
template<typename _MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
FullPivHouseholderQR()
Definition at line 103 of file FullPivHouseholderQR.h.
FullPivHouseholderQR() [3/4]
template<typename _MatrixType> template<typename InputType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
FullPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
Definition at line 126 of file FullPivHouseholderQR.h.
FullPivHouseholderQR() [4/4]
template<typename _MatrixType> template<typename InputType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
FullPivHouseholderQR(const EigenBase&)
Definition at line 146 of file FullPivHouseholderQR.h.
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType> template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::FullPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename _MatrixType> template<typename RhsType , typename DstType > void Eigen::FullPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
Definition at line 542 of file FullPivHouseholderQR.h.
absDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
Definition at line 425 of file FullPivHouseholderQR.h.
Referenced by qr_invertible(), and qr_verify_assert().
check_template_parameters()
template<typename _MatrixType> static void Eigen::FullPivHouseholderQR< _MatrixType >::check_template_parameters () inline static protected
Definition at line 404 of file FullPivHouseholderQR.h.
cols()
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::cols (void) const inline
Definition at line 319 of file FullPivHouseholderQR.h.
colsPermutation()
template<typename _MatrixType> const PermutationType& Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
Definition at line 198 of file FullPivHouseholderQR.h.
Referenced by qr().
compute() [1/2]
template<typename _MatrixType> template<typename InputType > FullPivHouseholderQR& Eigen::FullPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Referenced by ctms_decompositions(), qr(), and qr_invertible().
compute() [2/2]
template<typename _MatrixType> template<typename InputType > FullPivHouseholderQR<MatrixType>& Eigen::FullPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class FullPivHouseholderQR, FullPivHouseholderQR(const MatrixType&)
Definition at line 449 of file FullPivHouseholderQR.h.
computeInPlace()
template<typename MatrixType > void Eigen::FullPivHouseholderQR< MatrixType >::computeInPlace () protected
Definition at line 457 of file FullPivHouseholderQR.h.
dimensionOfKernel()
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 263 of file FullPivHouseholderQR.h.
Referenced by qr(), and qr_verify_assert().
hCoeffs()
template<typename _MatrixType> const HCoeffsType& Eigen::FullPivHouseholderQR< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
Definition at line 325 of file FullPivHouseholderQR.h.
inverse()
template<typename _MatrixType> const Inverse<FullPivHouseholderQR> Eigen::FullPivHouseholderQR< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
Definition at line 312 of file FullPivHouseholderQR.h.
Referenced by qr(), and qr_verify_assert().
isInjective()
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 276 of file FullPivHouseholderQR.h.
Referenced by qr(), qr_invertible(), and qr_verify_assert().
isInvertible()
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 301 of file FullPivHouseholderQR.h.
Referenced by qr(), qr_invertible(), and qr_verify_assert().
isSurjective()
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 289 of file FullPivHouseholderQR.h.
Referenced by qr(), qr_invertible(), and qr_verify_assert().
logAbsDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
Definition at line 434 of file FullPivHouseholderQR.h.
Referenced by qr_invertible(), and qr_verify_assert().
matrixQ()
template<typename MatrixType > FullPivHouseholderQR< MatrixType >::MatrixQReturnType Eigen::FullPivHouseholderQR< MatrixType >::matrixQ (void) const inline
Returns
Expression object representing the matrix Q
Definition at line 657 of file FullPivHouseholderQR.h.
Referenced by qr(), qr_invertible(), and qr_verify_assert().
matrixQR()
template<typename _MatrixType> const MatrixType& Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
Definition at line 188 of file FullPivHouseholderQR.h.
Referenced by qr(), and qr_verify_assert().
maxPivot()
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
Definition at line 394 of file FullPivHouseholderQR.h.
nonzeroPivots()
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
Definition at line 385 of file FullPivHouseholderQR.h.
rank()
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 246 of file FullPivHouseholderQR.h.
Referenced by qr().
rows()
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::rows (void) const inline
Definition at line 318 of file FullPivHouseholderQR.h.
rowsTranspositions()
template<typename _MatrixType> const IntDiagSizeVectorType& Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions () const inline
Returns
a const reference to the vector of indices representing the rows transpositions
Definition at line 205 of file FullPivHouseholderQR.h.
setThreshold() [1/2]
template<typename _MatrixType> FullPivHouseholderQR& Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than \(\vert pivot \vert \leqslant threshold \times \vert maxpivot \vert \) where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
Definition at line 344 of file FullPivHouseholderQR.h.
setThreshold() [2/2]
template<typename _MatrixType> FullPivHouseholderQR& Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
Definition at line 359 of file FullPivHouseholderQR.h.
solve()
template<typename _MatrixType> template<typename Rhs > const Solve<FullPivHouseholderQR, Rhs> Eigen::FullPivHouseholderQR< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition.
Parameters
b the right-hand-side of the equation to solve.
Returns
the exact or least-square solution if the rank is greater or equal to the number of columns of A, and an arbitrary solution otherwise.
Example:
Output:
Definition at line 176 of file FullPivHouseholderQR.h.
Referenced by ctms_decompositions(), qr(), qr_invertible(), and qr_verify_assert().
threshold()
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Definition at line 369 of file FullPivHouseholderQR.h.
Field Documentation
m_cols_permutation
template<typename _MatrixType> PermutationType Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_permutation protected
Definition at line 415 of file FullPivHouseholderQR.h.
m_cols_transpositions
template<typename _MatrixType> IntDiagSizeVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_transpositions protected
Definition at line 414 of file FullPivHouseholderQR.h.
m_det_pq
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::m_det_pq protected
Definition at line 421 of file FullPivHouseholderQR.h.
m_hCoeffs
template<typename _MatrixType> HCoeffsType Eigen::FullPivHouseholderQR< _MatrixType >::m_hCoeffs protected
Definition at line 412 of file FullPivHouseholderQR.h.
m_isInitialized
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized protected
Definition at line 417 of file FullPivHouseholderQR.h.
m_maxpivot
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_maxpivot protected
Definition at line 418 of file FullPivHouseholderQR.h.
m_nonzero_pivots
template<typename _MatrixType> Index Eigen::FullPivHouseholderQR< _MatrixType >::m_nonzero_pivots protected
Definition at line 419 of file FullPivHouseholderQR.h.
m_precision
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_precision protected
Definition at line 420 of file FullPivHouseholderQR.h.
m_prescribedThreshold
template<typename _MatrixType> RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_prescribedThreshold protected
Definition at line 418 of file FullPivHouseholderQR.h.
m_qr
template<typename _MatrixType> MatrixType Eigen::FullPivHouseholderQR< _MatrixType >::m_qr protected
Definition at line 411 of file FullPivHouseholderQR.h.
m_rows_transpositions
template<typename _MatrixType> IntDiagSizeVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_rows_transpositions protected
Definition at line 413 of file FullPivHouseholderQR.h.
m_temp
template<typename _MatrixType> RowVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_temp protected
Definition at line 416 of file FullPivHouseholderQR.h.
m_usePrescribedThreshold
template<typename _MatrixType> bool Eigen::FullPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold protected
Definition at line 417 of file FullPivHouseholderQR.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/QR/FullPivHouseholderQR.h