pairinteraction: Eigen::IterScaling< _MatrixType > Class Template Reference
Eigen::IterScaling< _MatrixType > Class Template Reference
iterative scaling algorithm to equilibrate rows and column norms in matrices
#include <Scaling.h>
Public Types
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
Public Member Functions
IterScaling ()
IterScaling (const MatrixType &matrix)
~IterScaling ()
void compute (const MatrixType &mat)
void computeRef (MatrixType &mat)
VectorXd & LeftScaling ()
VectorXd & RightScaling ()
void setTolerance (double tol)
Protected Member Functions
void init ()
Protected Attributes
MatrixType m_matrix
ComputationInfo m_info
bool m_isInitialized
VectorXd m_left
VectorXd m_right
double m_tol
int m_maxits
Detailed Description
template<typename _MatrixType>
class Eigen::IterScaling< _MatrixType >
iterative scaling algorithm to equilibrate rows and column norms in matrices
This class can be used as a preprocessing tool to accelerate the convergence of iterative methods
This feature is useful to limit the pivoting amount during LU/ILU factorization The scaling strategy as presented here preserves the symmetry of the problem NOTE It is assumed that the matrix does not have empty row or column,
Example with key steps
VectorXd x(n), b(n);
SparseMatrix<double> A;
// fill A and b;
IterScaling<SparseMatrix<double> > scal;
// Compute the left and right scaling vectors. The matrix is equilibrated at output
scal.computeRef(A);
// Scale the right hand side
b = scal.LeftScaling().cwiseProduct(b);
// Now, solve the equilibrated linear system with any available solver
// Scale back the computed solution
x = scal.RightScaling().cwiseProduct(x);
Template Parameters
_MatrixType the type of the matrix. It should be a real square sparsematrix
References : D. Ruiz and B. Ucar, A Symmetry Preserving Algorithm for Matrix Scaling, INRIA Research report RR-7552
See also
IncompleteLUT
Definition at line 48 of file Scaling.h.
Member Typedef Documentation
Index
template<typename _MatrixType > typedef MatrixType::Index Eigen::IterScaling< _MatrixType >::Index
Definition at line 53 of file Scaling.h.
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::IterScaling< _MatrixType >::MatrixType
Definition at line 51 of file Scaling.h.
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::IterScaling< _MatrixType >::Scalar
Definition at line 52 of file Scaling.h.
Constructor & Destructor Documentation
IterScaling() [1/2]
template<typename _MatrixType > Eigen::IterScaling< _MatrixType >::IterScaling () inline
Definition at line 56 of file Scaling.h.
References Eigen::IterScaling< _MatrixType >::init().
IterScaling() [2/2]
template<typename _MatrixType > Eigen::IterScaling< _MatrixType >::IterScaling (const MatrixType & matrix) inline
Definition at line 58 of file Scaling.h.
References Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::init().
~IterScaling()
template<typename _MatrixType > Eigen::IterScaling< _MatrixType >::~IterScaling () inline
Definition at line 64 of file Scaling.h.
Member Function Documentation
compute()
template<typename _MatrixType > void Eigen::IterScaling< _MatrixType >::compute (const MatrixType & mat) inline
Compute the left and right diagonal matrices to scale the input matrix mat
FIXME This algorithm will be modified such that the diagonal elements are permuted on the diagonal.
See also
LeftScaling() RightScaling()
Definition at line 73 of file Scaling.h.
References abs(), eigen_assert, i, m, Eigen::IterScaling< _MatrixType >::m_isInitialized, Eigen::IterScaling< _MatrixType >::m_left, Eigen::IterScaling< _MatrixType >::m_matrix, Eigen::IterScaling< _MatrixType >::m_maxits, Eigen::IterScaling< _MatrixType >::m_right, Eigen::IterScaling< _MatrixType >::m_tol, mat, n, and sqrt().
Referenced by Eigen::IterScaling< _MatrixType >::computeRef(), and Eigen::IterScaling< _MatrixType >::IterScaling().
computeRef()
template<typename _MatrixType > void Eigen::IterScaling< _MatrixType >::computeRef (MatrixType & mat) inline
Compute the left and right vectors to scale the vectors the input matrix is scaled with the computed vectors at output
See also
compute()
Definition at line 143 of file Scaling.h.
References Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::m_matrix.
init()
template<typename _MatrixType > void Eigen::IterScaling< _MatrixType >::init () inline protected
Definition at line 171 of file Scaling.h.
References e(), Eigen::IterScaling< _MatrixType >::m_isInitialized, Eigen::IterScaling< _MatrixType >::m_maxits, and Eigen::IterScaling< _MatrixType >::m_tol.
Referenced by Eigen::IterScaling< _MatrixType >::IterScaling().
LeftScaling()
template<typename _MatrixType > VectorXd& Eigen::IterScaling< _MatrixType >::LeftScaling () inline
Get the vector to scale the rows of the matrix
Definition at line 150 of file Scaling.h.
References Eigen::IterScaling< _MatrixType >::m_left.
RightScaling()
template<typename _MatrixType > VectorXd& Eigen::IterScaling< _MatrixType >::RightScaling () inline
Get the vector to scale the columns of the matrix
Definition at line 157 of file Scaling.h.
References Eigen::IterScaling< _MatrixType >::m_right.
setTolerance()
template<typename _MatrixType > void Eigen::IterScaling< _MatrixType >::setTolerance (double tol) inline
Set the tolerance for the convergence of the iterative scaling algorithm
Definition at line 164 of file Scaling.h.
References Eigen::IterScaling< _MatrixType >::m_tol.
Field Documentation
m_info
template<typename _MatrixType > ComputationInfo Eigen::IterScaling< _MatrixType >::m_info mutable protected
Definition at line 179 of file Scaling.h.
m_isInitialized
template<typename _MatrixType > bool Eigen::IterScaling< _MatrixType >::m_isInitialized protected
Definition at line 180 of file Scaling.h.
Referenced by Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::init().
m_left
template<typename _MatrixType > VectorXd Eigen::IterScaling< _MatrixType >::m_left protected
Definition at line 181 of file Scaling.h.
Referenced by Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::LeftScaling().
m_matrix
template<typename _MatrixType > MatrixType Eigen::IterScaling< _MatrixType >::m_matrix protected
Definition at line 178 of file Scaling.h.
Referenced by Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::computeRef().
m_maxits
template<typename _MatrixType > int Eigen::IterScaling< _MatrixType >::m_maxits protected
Definition at line 184 of file Scaling.h.
Referenced by Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::init().
m_right
template<typename _MatrixType > VectorXd Eigen::IterScaling< _MatrixType >::m_right protected
Definition at line 182 of file Scaling.h.
Referenced by Eigen::IterScaling< _MatrixType >::compute(), and Eigen::IterScaling< _MatrixType >::RightScaling().
m_tol
template<typename _MatrixType > double Eigen::IterScaling< _MatrixType >::m_tol protected
Definition at line 183 of file Scaling.h.
Referenced by Eigen::IterScaling< _MatrixType >::compute(), Eigen::IterScaling< _MatrixType >::init(), and Eigen::IterScaling< _MatrixType >::setTolerance().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/IterativeSolvers/Scaling.h