pairinteraction: Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ > Class Template Reference
Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ > Class Template Reference
A tensor expression mapping an existing array of data.
#include <TensorForwardDeclarations.h>
Public Types
enum { IsAligned = ((int(Options_)&Aligned)==Aligned), Layout = PlainObjectType::Layout, CoordAccess = true, RawAccess = true }
typedef TensorMap< PlainObjectType, Options_, MakePointer_ > Self
typedef PlainObjectType::Base Base
typedef Eigen::internal::nested< Self >::type Nested
typedef internal::traits< PlainObjectType >::StorageKind StorageKind
typedef internal::traits< PlainObjectType >::Index Index
typedef internal::traits< PlainObjectType >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Base::CoeffReturnType CoeffReturnType
typedef MakePointer_< Scalar >::Type PointerType
typedef PointerType PointerArgType
typedef PlainObjectType::Dimensions Dimensions
Public Types inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
typedef internal::traits< TensorMap< PlainObjectType, Options_, MakePointer_ > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, Index firstDimension)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, Index dim1, Index dim2)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, Index dim1, Index dim2, Index dim3)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, Index dim1, Index dim2, Index dim3, Index dim4)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, Index dim1, Index dim2, Index dim3, Index dim4, Index dim5)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, const array< Index, NumIndices > &dimensions)
template<typename Dimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PointerArgType dataPtr, const Dimensions &dimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PlainObjectType &tensor)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rank () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index dimension (Index n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PointerType data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const PointerType data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (const array< Index, NumIndices > &indices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index i0, Index i1) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index i0, Index i1, Index i2) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index i0, Index i1, Index i2, Index i3) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index i0, Index i1, Index i2, Index i3, Index i4) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (const array< Index, NumIndices > &indices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index i0, Index i1)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index i0, Index i1, Index i2)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index i0, Index i1, Index i2, Index i3)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index i0, Index i1, Index i2, Index i3, Index i4)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Self & operator= (const Self &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Self & operator= (const OtherDerived &other)
Public Member Functions inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorMap< PlainObjectType, Options_, MakePointer_ > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorMap< PlainObjectType, Options_, MakePointer_ > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorMap< PlainObjectType, Options_, MakePointer_ >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorMap< PlainObjectType, Options_, MakePointer_ >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorMap< PlainObjectType, Options_, MakePointer_ > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorMap< PlainObjectType, Options_, MakePointer_ > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorMap< PlainObjectType, Options_, MakePointer_ > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorMap< PlainObjectType, Options_, MakePointer_ > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorMap< PlainObjectType, Options_, MakePointer_ > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorMap< PlainObjectType, Options_, MakePointer_ > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorMap< PlainObjectType, Options_, MakePointer_ > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorMap< PlainObjectType, Options_, MakePointer_ > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorMap< PlainObjectType, Options_, MakePointer_ > > shuffle (const Shuffle &shuffle) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorMap< PlainObjectType, Options_, MakePointer_ > > shuffle (const Shuffle &shuffle)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorMap< PlainObjectType, Options_, MakePointer_ > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorMap< PlainObjectType, Options_, MakePointer_ > > stride (const Strides &strides)
TensorDevice< TensorMap< PlainObjectType, Options_, MakePointer_ >, DeviceType > device (const DeviceType &device)
Static Public Attributes
static const int Options = Options_
static const Index NumIndices = PlainObjectType::NumIndices
Static Public Attributes inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
static const int NumDimensions
Additional Inherited Members
Protected Member Functions inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorMap< PlainObjectType, Options_, MakePointer_ > & derived () const
Detailed Description
template<typename PlainObjectType, int Options_, template< class > class MakePointer_>
class Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >
A tensor expression mapping an existing array of data.
template <class> class MakePointer_ is added to convert the host pointer to the device pointer. It is added due to the fact that for our device compiler T* is not allowed. If we wanted to use the same Evaluator functions we have to convert that type to our pointer T. This is done through our MakePointer_ class. By default the Type in the MakePointer_<T> is T* . Therefore, by adding the default value, we managed to convert the type and it does not break any existing code as its default value is T*.
Definition at line 25 of file TensorForwardDeclarations.h.
Member Typedef Documentation
Base
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef PlainObjectType::Base Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Base
Definition at line 31 of file TensorMap.h.
CoeffReturnType
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef Base::CoeffReturnType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::CoeffReturnType
Definition at line 37 of file TensorMap.h.
Dimensions
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef PlainObjectType::Dimensions Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Dimensions
Definition at line 50 of file TensorMap.h.
Index
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef internal::traits<PlainObjectType>::Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Index
Definition at line 34 of file TensorMap.h.
Nested
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef Eigen::internal::nested<Self>::type Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Nested
Definition at line 32 of file TensorMap.h.
PointerArgType
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef PointerType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::PointerArgType
Definition at line 45 of file TensorMap.h.
PointerType
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef MakePointer_<Scalar>::Type Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::PointerType
Definition at line 44 of file TensorMap.h.
RealScalar
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef NumTraits<Scalar>::Real Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::RealScalar
Definition at line 36 of file TensorMap.h.
Scalar
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef internal::traits<PlainObjectType>::Scalar Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Scalar
Definition at line 35 of file TensorMap.h.
Self
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef TensorMap<PlainObjectType, Options_, MakePointer_> Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Self
Definition at line 30 of file TensorMap.h.
StorageKind
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> typedef internal::traits<PlainObjectType>::StorageKind Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::StorageKind
Definition at line 33 of file TensorMap.h.
Member Enumeration Documentation
anonymous enum
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> anonymous enum
Enumerator
IsAligned
Layout
CoordAccess
RawAccess
Definition at line 52 of file TensorMap.h.
Constructor & Destructor Documentation
TensorMap() [1/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr) inline
Definition at line 60 of file TensorMap.h.
References Eigen::Dynamic, EIGEN_STATIC_ASSERT, and EIGEN_STRONG_INLINE.
TensorMap() [2/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, Index firstDimension) inline
Definition at line 73 of file TensorMap.h.
References Eigen::Dynamic, and EIGEN_STATIC_ASSERT.
TensorMap() [3/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, Index dim1, Index dim2) inline
Definition at line 78 of file TensorMap.h.
References Eigen::Dynamic, and EIGEN_STATIC_ASSERT.
TensorMap() [4/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, Index dim1, Index dim2, Index dim3) inline
Definition at line 82 of file TensorMap.h.
References Eigen::Dynamic, and EIGEN_STATIC_ASSERT.
TensorMap() [5/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, Index dim1, Index dim2, Index dim3, Index dim4) inline
Definition at line 86 of file TensorMap.h.
References Eigen::Dynamic, and EIGEN_STATIC_ASSERT.
TensorMap() [6/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, Index dim1, Index dim2, Index dim3, Index dim4, Index dim5) inline
Definition at line 90 of file TensorMap.h.
References Eigen::Dynamic, and EIGEN_STATIC_ASSERT.
TensorMap() [7/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, const array< Index, NumIndices > & dimensions) inline
Definition at line 95 of file TensorMap.h.
TensorMap() [8/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> template<typename Dimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PointerArgType dataPtr, const Dimensions & dimensions) inline
Definition at line 100 of file TensorMap.h.
TensorMap() [9/9]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PlainObjectType & tensor) inline
Definition at line 104 of file TensorMap.h.
Member Function Documentation
data() [1/2]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PointerType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::data () inline
Definition at line 117 of file TensorMap.h.
data() [2/2]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const PointerType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::data () const inline
Definition at line 119 of file TensorMap.h.
dimension()
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimension (Index n) const inline
Definition at line 111 of file TensorMap.h.
References n.
dimensions()
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimensions () const inline
Definition at line 113 of file TensorMap.h.
operator()() [1/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (const array< Index, NumIndices > & indices) const inline
Definition at line 122 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [2/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() () const inline
Definition at line 135 of file TensorMap.h.
References EIGEN_STATIC_ASSERT.
Referenced by Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()().
operator()() [3/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index index) const inline
Definition at line 142 of file TensorMap.h.
References eigen_internal_assert, EIGEN_STATIC_ASSERT, EIGEN_STRONG_INLINE, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()(), Eigen::RowMajor, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size().
operator()() [4/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1) const inline
Definition at line 163 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [5/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1, Index i2) const inline
Definition at line 174 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [6/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1, Index i2, Index i3) const inline
Definition at line 185 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [7/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1, Index i2, Index i3, Index i4) const inline
Definition at line 196 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [8/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (const array< Index, NumIndices > & indices) inline
Definition at line 209 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [9/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() () inline
Definition at line 222 of file TensorMap.h.
References EIGEN_STATIC_ASSERT.
operator()() [10/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index index) inline
Definition at line 229 of file TensorMap.h.
References Eigen::Dynamic, eigen_internal_assert, EIGEN_STRONG_INLINE, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()(), Eigen::RowMajor, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size().
operator()() [11/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1) inline
Definition at line 251 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [12/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1, Index i2) inline
Definition at line 262 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [13/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1, Index i2, Index i3) inline
Definition at line 273 of file TensorMap.h.
References Eigen::RowMajor.
operator()() [14/14]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index i0, Index i1, Index i2, Index i3, Index i4) inline
Definition at line 284 of file TensorMap.h.
References Eigen::RowMajor.
operator=() [1/2]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Self& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator= (const Self & other) inline
Definition at line 296 of file TensorMap.h.
References EIGEN_STRONG_INLINE, and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run().
operator=() [2/2]
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Self& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator= (const OtherDerived & other) inline
Definition at line 306 of file TensorMap.h.
References Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run().
rank()
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::rank () const inline
Definition at line 109 of file TensorMap.h.
size()
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size () const inline
Definition at line 115 of file TensorMap.h.
Referenced by Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()().
Field Documentation
NumIndices
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> const Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices = PlainObjectType::NumIndices static
Definition at line 49 of file TensorMap.h.
Options
template<typename PlainObjectType, int Options_, template< class > class MakePointer_> const int Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Options = Options_ static
Definition at line 47 of file TensorMap.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorForwardDeclarations.h
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorMap.h