pairinteraction: Eigen::MatrixPower< MatrixType > Class Template Reference
Eigen::MatrixPower< MatrixType > Class Template Reference
Class for computing matrix powers.
#include <MatrixPower.h>
Public Member Functions
MatrixPower (const MatrixType &A)
Constructor.
const MatrixPowerParenthesesReturnValue< MatrixType > operator() (RealScalar p)
Returns the matrix power.
template<typename ResultType >
void compute (ResultType &res, RealScalar p)
Compute the matrix power.
Index rows () const
Index cols () const
Detailed Description
template<typename MatrixType>
class Eigen::MatrixPower< MatrixType >
Class for computing matrix powers.
Template Parameters
MatrixType type of the base, expected to be an instantiation of the Matrix class template.
This class is capable of computing real/complex matrices raised to an arbitrary real power. Meanwhile, it saves the result of Schur decomposition if an non-integral power has even been calculated. Therefore, if you want to compute multiple (>= 2) matrix powers for the same matrix, using the class directly is more efficient than calling MatrixBase::pow().
Example:
Output:
Definition at line 15 of file MatrixPower.h.
Constructor & Destructor Documentation
MatrixPower()
template<typename MatrixType> Eigen::MatrixPower< MatrixType >::MatrixPower (const MatrixType & A) inline explicit
Constructor.
Parameters
[in] A the base of the matrix power.
The class stores a reference to A, so it should not be changed (or destroyed) before evaluation.
Definition at line 354 of file MatrixPower.h.
References eigen_assert.
Member Function Documentation
cols()
template<typename MatrixType> Index Eigen::MatrixPower< MatrixType >::cols (void) const inline
Definition at line 382 of file MatrixPower.h.
References Eigen::Dynamic.
compute()
template<typename MatrixType > template<typename ResultType > void Eigen::MatrixPower< MatrixType >::compute (ResultType & res, RealScalar p)
Compute the matrix power.
Parameters
[in] p exponent, a real scalar.
[out] res \(A^p \) where A is specified in the constructor.
Definition at line 450 of file MatrixPower.h.
References abs(), Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::PlainObjectBase< Derived >::coeff(), cols, Eigen::MatrixPowerAtomic< MatrixType >::compute(), eigen_assert, floor(), mpfr::fmod(), i, j, Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::ComplexSchur< _MatrixType >::matrixT(), Eigen::ComplexSchur< _MatrixType >::matrixU(), p, Eigen::half_impl::pow(), res, rot(), rows, and schurOfA().
operator()()
template<typename MatrixType> const MatrixPowerParenthesesReturnValue<MatrixType> Eigen::MatrixPower< MatrixType >::operator() (RealScalar p) inline
Returns the matrix power.
Parameters
[in] p exponent, a real scalar.
Returns
The expression \(A^p \), where A is specified in the constructor.
Definition at line 368 of file MatrixPower.h.
References Eigen::MatrixPowerAtomic< MatrixType >::compute(), and p.
rows()
template<typename MatrixType> Index Eigen::MatrixPower< MatrixType >::rows (void) const inline
Definition at line 381 of file MatrixPower.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixPower.h