pairinteraction: Action_matrix_vector_product< Interface > Class Template Reference
Action_matrix_vector_product< Interface > Class Template Reference
#include <action_matrix_vector_product.hh>
Public Member Functions
BTL_DONT_INLINE Action_matrix_vector_product (int size)
Action_matrix_vector_product (const Action_matrix_vector_product &)
BTL_DONT_INLINE ~Action_matrix_vector_product (void)
double nb_op_base (void)
BTL_DONT_INLINE void initialize (void)
BTL_DONT_INLINE void calculate (void)
BTL_DONT_INLINE void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_matrix_vector_product< Interface >
Definition at line 32 of file action_matrix_vector_product.hh.
Constructor & Destructor Documentation
Action_matrix_vector_product() [1/2]
template<class Interface > BTL_DONT_INLINE Action_matrix_vector_product< Interface >::Action_matrix_vector_product (int size) inline
Definition at line 38 of file action_matrix_vector_product.hh.
References MESSAGE, and X.
Action_matrix_vector_product() [2/2]
template<class Interface > Action_matrix_vector_product< Interface >::Action_matrix_vector_product (const Action_matrix_vector_product< Interface > &) inline
Definition at line 62 of file action_matrix_vector_product.hh.
References INFOS.
~Action_matrix_vector_product()
template<class Interface > BTL_DONT_INLINE Action_matrix_vector_product< Interface >::~Action_matrix_vector_product (void) inline
Definition at line 70 of file action_matrix_vector_product.hh.
References MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > BTL_DONT_INLINE void Action_matrix_vector_product< Interface >::calculate (void) inline
Definition at line 105 of file action_matrix_vector_product.hh.
References BTL_ASM_COMMENT, and X.
check_result()
template<class Interface > BTL_DONT_INLINE void Action_matrix_vector_product< Interface >::check_result (void) inline
Definition at line 111 of file action_matrix_vector_product.hh.
References e(), INFOS, STL_interface< real >::matrix_vector_product(), STL_interface< real >::norm_diff(), and X.
initialize()
template<class Interface > BTL_DONT_INLINE void Action_matrix_vector_product< Interface >::initialize (void) inline
Definition at line 97 of file action_matrix_vector_product.hh.
References X.
name()
template<class Interface > static std::string Action_matrix_vector_product< Interface >::name (void) inline static
Definition at line 88 of file action_matrix_vector_product.hh.
nb_op_base()
template<class Interface > double Action_matrix_vector_product< Interface >::nb_op_base (void) inline
Definition at line 93 of file action_matrix_vector_product.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_matrix_vector_product.hh