pairinteraction: Eigen::Product< _Lhs, _Rhs, Option > Class Template Reference
Eigen::Product< _Lhs, _Rhs, Option > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of the product of two arbitrary matrices or vectors.
#include <Product.h>
Public Types
typedef _Lhs Lhs
typedef _Rhs Rhs
typedef ProductImpl< Lhs, Rhs, Option, typename internal::product_promote_storage_type< typename internal::traits< Lhs >::StorageKind, typename internal::traits< Rhs >::StorageKind, internal::product_type< Lhs, Rhs >::ret >::ret >::Base Base
typedef internal::ref_selector< Lhs >::type LhsNested
typedef internal::ref_selector< Rhs >::type RhsNested
typedef internal::remove_all< LhsNested >::type LhsNestedCleaned
typedef internal::remove_all< RhsNested >::type RhsNestedCleaned
Public Types inherited from Eigen::ProductImpl< _Lhs, _Rhs, Option, internal::product_promote_storage_type< internal::traits< _Lhs >::StorageKind, internal::traits< _Rhs >::StorageKind, internal::product_type< _Lhs, _Rhs >::ret >::ret >
typedef internal::generic_xpr_base< Product< _Lhs, _Rhs, Option >, MatrixXpr, internal::product_promote_storage_type< internal::traits< _Lhs >::StorageKind, internal::traits< _Rhs >::StorageKind, internal::product_type< _Lhs, _Rhs >::ret >::ret >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC Product (const Lhs &lhs, const Rhs &rhs)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const LhsNestedCleaned & lhs () const
EIGEN_DEVICE_FUNC const RhsNestedCleaned & rhs () const
Protected Attributes
LhsNested m_lhs
RhsNested m_rhs
Detailed Description
template<typename _Lhs, typename _Rhs, int Option>
class Eigen::Product< _Lhs, _Rhs, Option >
Expression of the product of two arbitrary matrices or vectors.
Template Parameters
_Lhs the type of the left-hand side expression
_Rhs the type of the right-hand side expression
This class represents an expression of the product of two arbitrary matrices.
The other template parameters are:
Template Parameters
Option can be DefaultProduct, AliasFreeProduct, or LazyProduct
Definition at line 71 of file Product.h.
Member Typedef Documentation
Base
template<typename _Lhs, typename _Rhs, int Option> typedef ProductImpl< Lhs, Rhs, Option, typename internal::product_promote_storage_type<typename internal::traits<Lhs>::StorageKind, typename internal::traits<Rhs>::StorageKind, internal::product_type<Lhs,Rhs>::ret>::ret>::Base Eigen::Product< _Lhs, _Rhs, Option >::Base
Definition at line 85 of file Product.h.
Lhs
template<typename _Lhs, typename _Rhs, int Option> typedef _Lhs Eigen::Product< _Lhs, _Rhs, Option >::Lhs
Definition at line 78 of file Product.h.
LhsNested
template<typename _Lhs, typename _Rhs, int Option> typedef internal::ref_selector<Lhs>::type Eigen::Product< _Lhs, _Rhs, Option >::LhsNested
Definition at line 88 of file Product.h.
LhsNestedCleaned
template<typename _Lhs, typename _Rhs, int Option> typedef internal::remove_all<LhsNested>::type Eigen::Product< _Lhs, _Rhs, Option >::LhsNestedCleaned
Definition at line 90 of file Product.h.
Rhs
template<typename _Lhs, typename _Rhs, int Option> typedef _Rhs Eigen::Product< _Lhs, _Rhs, Option >::Rhs
Definition at line 79 of file Product.h.
RhsNested
template<typename _Lhs, typename _Rhs, int Option> typedef internal::ref_selector<Rhs>::type Eigen::Product< _Lhs, _Rhs, Option >::RhsNested
Definition at line 89 of file Product.h.
RhsNestedCleaned
template<typename _Lhs, typename _Rhs, int Option> typedef internal::remove_all<RhsNested>::type Eigen::Product< _Lhs, _Rhs, Option >::RhsNestedCleaned
Definition at line 91 of file Product.h.
Constructor & Destructor Documentation
Product()
template<typename _Lhs, typename _Rhs, int Option> EIGEN_DEVICE_FUNC Eigen::Product< _Lhs, _Rhs, Option >::Product (const Lhs & lhs, const Rhs & rhs) inline
Definition at line 93 of file Product.h.
Member Function Documentation
cols()
template<typename _Lhs, typename _Rhs, int Option> EIGEN_DEVICE_FUNC Index Eigen::Product< _Lhs, _Rhs, Option >::cols (void) const inline
Definition at line 101 of file Product.h.
Referenced by Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::add_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::sub_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), and Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, DefaultProduct >, internal::assign_op< Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, Dense2Triangular >::run().
lhs()
template<typename _Lhs, typename _Rhs, int Option> EIGEN_DEVICE_FUNC const LhsNestedCleaned& Eigen::Product< _Lhs, _Rhs, Option >::lhs () const inline
Definition at line 103 of file Product.h.
Referenced by Eigen::internal::product_evaluator< Product< Lhs, Rhs, Options >, ProductTag, LhsShape, RhsShape >::product_evaluator(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, AliasFreeProduct >, ProductTag, PermutationShape, SparseShape >::product_evaluator(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, AliasFreeProduct >, ProductTag, SparseShape, PermutationShape >::product_evaluator(), Eigen::internal::product_evaluator< Product< Lhs, RhsView, DefaultProduct >, ProductTag, SparseShape, SparseSelfAdjointShape >::product_evaluator(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::add_assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::sub_assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::add_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), and Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::sub_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run().
rhs()
template<typename _Lhs, typename _Rhs, int Option> EIGEN_DEVICE_FUNC const RhsNestedCleaned& Eigen::Product< _Lhs, _Rhs, Option >::rhs () const inline
Definition at line 104 of file Product.h.
Referenced by Eigen::internal::product_evaluator< Product< Lhs, Rhs, Options >, ProductTag, LhsShape, RhsShape >::product_evaluator(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, AliasFreeProduct >, ProductTag, PermutationShape, SparseShape >::product_evaluator(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, AliasFreeProduct >, ProductTag, SparseShape, PermutationShape >::product_evaluator(), Eigen::internal::product_evaluator< Product< LhsView, Rhs, DefaultProduct >, ProductTag, SparseSelfAdjointShape, SparseShape >::product_evaluator(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::add_assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::sub_assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::add_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), and Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::sub_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run().
rows()
template<typename _Lhs, typename _Rhs, int Option> EIGEN_DEVICE_FUNC Index Eigen::Product< _Lhs, _Rhs, Option >::rows (void) const inline
Definition at line 100 of file Product.h.
Referenced by Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, AliasFreeProduct >, internal::assign_op< typename DstXprType::Scalar, typename Product< Lhs, Rhs, AliasFreeProduct >::Scalar >, Sparse2Dense >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::add_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::sub_assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run(), and Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, DefaultProduct >, internal::assign_op< Scalar, typename Product< Lhs, Rhs, DefaultProduct >::Scalar >, Dense2Triangular >::run().
Field Documentation
m_lhs
template<typename _Lhs, typename _Rhs, int Option> LhsNested Eigen::Product< _Lhs, _Rhs, Option >::m_lhs protected
Definition at line 108 of file Product.h.
m_rhs
template<typename _Lhs, typename _Rhs, int Option> RhsNested Eigen::Product< _Lhs, _Rhs, Option >::m_rhs protected
Definition at line 109 of file Product.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/Product.h