pairinteraction: Eigen::SkylineInplaceLU< MatrixType > Class Template Reference
Eigen::SkylineInplaceLU< MatrixType > Class Template Reference
Inplace LU decomposition of a skyline matrix and associated features.
#include <SkylineInplaceLU.h>
Public Member Functions
SkylineInplaceLU (MatrixType &matrix, int flags=0)
void setPrecision (RealScalar v)
RealScalar precision () const
void setFlags (int f)
int flags () const
void setOrderingMethod (int m)
int orderingMethod () const
void compute ()
void computeRowMajor ()
template<typename BDerived , typename XDerived >
bool solve (const MatrixBase< BDerived > &b, MatrixBase< XDerived > *x, const int transposed=0) const
bool succeeded (void) const
Protected Types
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef NumTraits< typename MatrixType::Scalar >::Real RealScalar
Protected Attributes
RealScalar m_precision
int m_flags
int m_status
bool m_succeeded
MatrixType & m_lu
Detailed Description
template<typename MatrixType>
class Eigen::SkylineInplaceLU< MatrixType >
Inplace LU decomposition of a skyline matrix and associated features.
Parameters
MatrixType the type of the matrix of which we are computing the LU factorization
Definition at line 25 of file SkylineInplaceLU.h.
Member Typedef Documentation
Index
template<typename MatrixType > typedef MatrixType::Index Eigen::SkylineInplaceLU< MatrixType >::Index protected
Definition at line 28 of file SkylineInplaceLU.h.
RealScalar
template<typename MatrixType > typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::SkylineInplaceLU< MatrixType >::RealScalar protected
Definition at line 30 of file SkylineInplaceLU.h.
Scalar
template<typename MatrixType > typedef MatrixType::Scalar Eigen::SkylineInplaceLU< MatrixType >::Scalar protected
Definition at line 27 of file SkylineInplaceLU.h.
Constructor & Destructor Documentation
SkylineInplaceLU()
template<typename MatrixType > Eigen::SkylineInplaceLU< MatrixType >::SkylineInplaceLU (MatrixType & matrix, int flags = 0) inline
Creates a LU object and compute the respective factorization of matrix using flags flags.
Definition at line 36 of file SkylineInplaceLU.h.
References Eigen::SkylineInplaceLU< MatrixType >::compute(), Eigen::SkylineInplaceLU< MatrixType >::computeRowMajor(), Eigen::SkylineInplaceLU< MatrixType >::m_lu, and Eigen::SkylineInplaceLU< MatrixType >::m_precision.
Member Function Documentation
compute()
template<typename MatrixType > void Eigen::SkylineInplaceLU< MatrixType >::compute ()
Computes/re-computes the LU factorization
Computes / recomputes the in place LU decomposition of the SkylineInplaceLU. using the default algorithm.
Definition at line 120 of file SkylineInplaceLU.h.
References col(), cols, eigen_assert, i, Eigen::SkylineInplaceLU< MatrixType >::m_lu, row(), and rows.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::orderingMethod(), and Eigen::SkylineInplaceLU< MatrixType >::SkylineInplaceLU().
computeRowMajor()
template<typename MatrixType > void Eigen::SkylineInplaceLU< MatrixType >::computeRowMajor ()
Definition at line 184 of file SkylineInplaceLU.h.
References col(), cols, eigen_assert, Eigen::SkylineInplaceLU< MatrixType >::m_lu, offset, row(), and rows.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::orderingMethod(), and Eigen::SkylineInplaceLU< MatrixType >::SkylineInplaceLU().
flags()
template<typename MatrixType > int Eigen::SkylineInplaceLU< MatrixType >::flags () const inline
Returns
the current flags
Definition at line 76 of file SkylineInplaceLU.h.
References Eigen::SkylineInplaceLU< MatrixType >::m_flags.
orderingMethod()
template<typename MatrixType > int Eigen::SkylineInplaceLU< MatrixType >::orderingMethod () const inline
Definition at line 84 of file SkylineInplaceLU.h.
References b, Eigen::SkylineInplaceLU< MatrixType >::compute(), Eigen::SkylineInplaceLU< MatrixType >::computeRowMajor(), Eigen::SkylineInplaceLU< MatrixType >::m_flags, Eigen::SkylineInplaceLU< MatrixType >::solve(), and x.
precision()
template<typename MatrixType > RealScalar Eigen::SkylineInplaceLU< MatrixType >::precision () const inline
Returns
the current precision.
See also
setPrecision()
Definition at line 59 of file SkylineInplaceLU.h.
References Eigen::SkylineInplaceLU< MatrixType >::m_precision.
setFlags()
template<typename MatrixType > void Eigen::SkylineInplaceLU< MatrixType >::setFlags (int f) inline
Sets the flags. Possible values are:
CompleteFactorization
IncompleteFactorization
MemoryEfficient
one of the ordering methods
etc...
See also
flags()
Definition at line 71 of file SkylineInplaceLU.h.
setOrderingMethod()
template<typename MatrixType > void Eigen::SkylineInplaceLU< MatrixType >::setOrderingMethod (int m) inline
Definition at line 80 of file SkylineInplaceLU.h.
References m, and Eigen::SkylineInplaceLU< MatrixType >::m_flags.
setPrecision()
template<typename MatrixType > void Eigen::SkylineInplaceLU< MatrixType >::setPrecision (RealScalar v) inline
Sets the relative threshold value used to prune zero coefficients during the decomposition.
Setting a value greater than zero speeds up computation, and yields to an imcomplete factorization with fewer non zero coefficients. Such approximate factors are especially useful to initialize an iterative solver.
Note that the exact meaning of this parameter might depends on the actual backend. Moreover, not all backends support this feature.
See also
precision()
Definition at line 52 of file SkylineInplaceLU.h.
References Eigen::SkylineInplaceLU< MatrixType >::m_precision, and v.
solve()
template<typename MatrixType > template<typename BDerived , typename XDerived > bool Eigen::SkylineInplaceLU< MatrixType >::solve (const MatrixBase< BDerived > & b, MatrixBase< XDerived > * x, const int transposed = 0) const
Returns
the lower triangular matrix L
the upper triangular matrix U
Computes *x = U^-1 L^-1 b
If transpose is set to SvTranspose or SvAdjoint, the solution of the transposed/adjoint system is computed instead.
Not all backends implement the solution of the transposed or adjoint system.
Definition at line 307 of file SkylineInplaceLU.h.
References col(), cols, Eigen::SkylineInplaceLU< MatrixType >::m_lu, row(), rows, and Eigen::DenseBase< Derived >::value().
Referenced by Eigen::SkylineInplaceLU< MatrixType >::orderingMethod().
succeeded()
template<typename MatrixType > bool Eigen::SkylineInplaceLU< MatrixType >::succeeded (void) const inline
Returns
true if the factorization succeeded
Definition at line 103 of file SkylineInplaceLU.h.
References Eigen::SkylineInplaceLU< MatrixType >::m_succeeded.
Field Documentation
m_flags
template<typename MatrixType > int Eigen::SkylineInplaceLU< MatrixType >::m_flags protected
Definition at line 109 of file SkylineInplaceLU.h.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::flags(), Eigen::SkylineInplaceLU< MatrixType >::orderingMethod(), and Eigen::SkylineInplaceLU< MatrixType >::setOrderingMethod().
m_lu
template<typename MatrixType > MatrixType& Eigen::SkylineInplaceLU< MatrixType >::m_lu protected
Definition at line 112 of file SkylineInplaceLU.h.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::compute(), Eigen::SkylineInplaceLU< MatrixType >::computeRowMajor(), Eigen::SkylineInplaceLU< MatrixType >::SkylineInplaceLU(), and Eigen::SkylineInplaceLU< MatrixType >::solve().
m_precision
template<typename MatrixType > RealScalar Eigen::SkylineInplaceLU< MatrixType >::m_precision protected
Definition at line 108 of file SkylineInplaceLU.h.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::precision(), Eigen::SkylineInplaceLU< MatrixType >::setPrecision(), and Eigen::SkylineInplaceLU< MatrixType >::SkylineInplaceLU().
m_status
template<typename MatrixType > int Eigen::SkylineInplaceLU< MatrixType >::m_status mutable protected
Definition at line 110 of file SkylineInplaceLU.h.
m_succeeded
template<typename MatrixType > bool Eigen::SkylineInplaceLU< MatrixType >::m_succeeded protected
Definition at line 111 of file SkylineInplaceLU.h.
Referenced by Eigen::SkylineInplaceLU< MatrixType >::succeeded().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/Skyline/SkylineInplaceLU.h