pairinteraction: STL_interface< real > Class Template Reference
STL_interface< real > Class Template Reference
#include <STL_interface.hh>
Public Types
typedef real real_type
typedef std::vector< real > stl_vector
typedef std::vector< stl_vector > stl_matrix
typedef stl_matrix gene_matrix
typedef stl_vector gene_vector
Static Public Member Functions
static std::string name (void)
static void free_matrix (gene_matrix &, int)
static void free_vector (gene_vector &)
static void matrix_from_stl (gene_matrix &A, stl_matrix &A_stl)
static void vector_from_stl (gene_vector &B, stl_vector &B_stl)
static void vector_to_stl (gene_vector &B, stl_vector &B_stl)
static void matrix_to_stl (gene_matrix &A, stl_matrix &A_stl)
static void copy_vector (const gene_vector &source, gene_vector &cible, int N)
static void copy_matrix (const gene_matrix &source, gene_matrix &cible, int N)
static void aat_product (const gene_matrix &A, gene_matrix &X, int N)
static void matrix_matrix_product (const gene_matrix &A, const gene_matrix &B, gene_matrix &X, int N)
static void matrix_vector_product (gene_matrix &A, gene_vector &B, gene_vector &X, int N)
static void symv (gene_matrix &A, gene_vector &B, gene_vector &X, int N)
static void syr2 (gene_matrix &A, gene_vector &B, gene_vector &X, int N)
static void ger (gene_matrix &A, gene_vector &X, gene_vector &Y, int N)
static void atv_product (gene_matrix &A, gene_vector &B, gene_vector &X, int N)
static void axpy (real coef, const gene_vector &X, gene_vector &Y, int N)
static void axpby (real a, const gene_vector &X, real b, gene_vector &Y, int N)
static void trisolve_lower (const gene_matrix &L, const gene_vector &B, gene_vector &X, int N)
static real norm_diff (const stl_vector &A, const stl_vector &B)
static real norm_diff (const stl_matrix &A, const stl_matrix &B)
static void display_vector (const stl_vector &A)
Detailed Description
template<class real>
class STL_interface< real >
Definition at line 29 of file STL_interface.hh.
Member Typedef Documentation
gene_matrix
template<class real > typedef stl_matrix STL_interface< real >::gene_matrix
Definition at line 38 of file STL_interface.hh.
gene_vector
template<class real > typedef stl_vector STL_interface< real >::gene_vector
Definition at line 40 of file STL_interface.hh.
real_type
template<class real > typedef real STL_interface< real >::real_type
Definition at line 33 of file STL_interface.hh.
stl_matrix
template<class real > typedef std::vector<stl_vector > STL_interface< real >::stl_matrix
Definition at line 36 of file STL_interface.hh.
stl_vector
template<class real > typedef std::vector<real> STL_interface< real >::stl_vector
Definition at line 35 of file STL_interface.hh.
Member Function Documentation
aat_product()
template<class real > static void STL_interface< real >::aat_product (const gene_matrix & A, gene_matrix & X, int N) inline static
Definition at line 94 of file STL_interface.hh.
Referenced by Action_aat_product< Interface >::check_result().
atv_product()
template<class real > static void STL_interface< real >::atv_product (gene_matrix & A, gene_vector & B, gene_vector & X, int N) inline static
Definition at line 171 of file STL_interface.hh.
Referenced by Action_atv_product< Interface >::check_result().
axpby()
template<class real > static void STL_interface< real >::axpby (real a, const gene_vector & X, real b, gene_vector & Y, int N) inline static
Definition at line 187 of file STL_interface.hh.
Referenced by Action_axpby< Interface >::check_result().
axpy()
template<class real > static void STL_interface< real >::axpy (real coef, const gene_vector & X, gene_vector & Y, int N) inline static
Definition at line 182 of file STL_interface.hh.
Referenced by Action_axpy< Interface >::check_result().
copy_matrix()
template<class real > static void STL_interface< real >::copy_matrix (const gene_matrix & source, gene_matrix & cible, int N) inline static
Definition at line 75 of file STL_interface.hh.
copy_vector()
template<class real > static void STL_interface< real >::copy_vector (const gene_vector & source, gene_vector & cible, int N) inline static
Definition at line 68 of file STL_interface.hh.
display_vector()
template<class real > static void STL_interface< real >::display_vector (const stl_vector & A) inline static
Definition at line 234 of file STL_interface.hh.
Referenced by Action_lu_solve< Interface >::calculate().
free_matrix()
template<class real > static void STL_interface< real >::free_matrix (gene_matrix & , int) inline static
Definition at line 47 of file STL_interface.hh.
free_vector()
template<class real > static void STL_interface< real >::free_vector (gene_vector &) inline static
Definition at line 49 of file STL_interface.hh.
ger()
template<class real > static void STL_interface< real >::ger (gene_matrix & A, gene_vector & X, gene_vector & Y, int N) inline static
Definition at line 162 of file STL_interface.hh.
Referenced by Action_ger< Interface >::check_result().
matrix_from_stl()
template<class real > static void STL_interface< real >::matrix_from_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 51 of file STL_interface.hh.
matrix_matrix_product()
template<class real > static void STL_interface< real >::matrix_matrix_product (const gene_matrix & A, const gene_matrix & B, gene_matrix & X, int N) inline static
Definition at line 112 of file STL_interface.hh.
Referenced by Action_matrix_matrix_product_bis< Interface >::calculate(), and Action_matrix_matrix_product< Interface >::check_result().
matrix_to_stl()
template<class real > static void STL_interface< real >::matrix_to_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 64 of file STL_interface.hh.
matrix_vector_product()
template<class real > static void STL_interface< real >::matrix_vector_product (gene_matrix & A, gene_vector & B, gene_vector & X, int N) inline static
Definition at line 125 of file STL_interface.hh.
Referenced by Action_lu_solve< Interface >::calculate(), and Action_matrix_vector_product< Interface >::check_result().
name()
template<class real > static std::string STL_interface< real >::name (void) inline static
Definition at line 42 of file STL_interface.hh.
norm_diff() [1/2]
template<class real > static real STL_interface< real >::norm_diff (const stl_vector & A, const stl_vector & B) inline static
Definition at line 203 of file STL_interface.hh.
Referenced by Action_matrix_matrix_product_bis< Interface >::calculate(), Action_lu_solve< Interface >::calculate(), Action_axpby< Interface >::check_result(), Action_ger< Interface >::check_result(), Action_atv_product< Interface >::check_result(), Action_syr2< Interface >::check_result(), Action_symv< Interface >::check_result(), Action_axpy< Interface >::check_result(), Action_trisolve< Interface >::check_result(), Action_ata_product< Interface >::check_result(), Action_aat_product< Interface >::check_result(), Action_matrix_matrix_product< Interface >::check_result(), and Action_matrix_vector_product< Interface >::check_result().
norm_diff() [2/2]
template<class real > static real STL_interface< real >::norm_diff (const stl_matrix & A, const stl_matrix & B) inline static
Definition at line 217 of file STL_interface.hh.
symv()
template<class real > static void STL_interface< real >::symv (gene_matrix & A, gene_vector & B, gene_vector & X, int N) inline static
Definition at line 136 of file STL_interface.hh.
Referenced by Action_symv< Interface >::check_result().
syr2()
template<class real > static void STL_interface< real >::syr2 (gene_matrix & A, gene_vector & B, gene_vector & X, int N) inline static
Definition at line 153 of file STL_interface.hh.
Referenced by Action_syr2< Interface >::check_result().
trisolve_lower()
template<class real > static void STL_interface< real >::trisolve_lower (const gene_matrix & L, const gene_vector & B, gene_vector & X, int N) inline static
Definition at line 192 of file STL_interface.hh.
Referenced by Action_trisolve< Interface >::check_result().
vector_from_stl()
template<class real > static void STL_interface< real >::vector_from_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 55 of file STL_interface.hh.
vector_to_stl()
template<class real > static void STL_interface< real >::vector_to_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 59 of file STL_interface.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/libs/STL/STL_interface.hh