pairinteraction: Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > Class Template Reference
Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > Class Template Reference
#include <TensorForwardDeclarations.h>
Public Types
typedef internal::traits< TensorStridingSlicingOp >::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef internal::nested< TensorStridingSlicingOp >::type Nested
typedef internal::traits< TensorStridingSlicingOp >::StorageKind StorageKind
typedef internal::traits< TensorStridingSlicingOp >::Index Index
Public Types inherited from Eigen::TensorBase< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > >
typedef internal::traits< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp (const XprType &expr, const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC const StartIndices & startIndices () const
EIGEN_DEVICE_FUNC const StartIndices & stopIndices () const
EIGEN_DEVICE_FUNC const StartIndices & strides () const
EIGEN_DEVICE_FUNC const internal::remove_all< typename XprType::Nested >::type & expression () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp & operator= (const TensorStridingSlicingOp &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp & operator= (const OtherDerived &other)
Public Member Functions inherited from Eigen::TensorBase< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > shuffle (const Shuffle &shuffle) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > shuffle (const Shuffle &shuffle)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > > stride (const Strides &strides)
TensorDevice< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >, DeviceType > device (const DeviceType &device)
Protected Attributes
XprType::Nested m_xpr
const StartIndices m_startIndices
const StopIndices m_stopIndices
const Strides m_strides
Additional Inherited Members
Static Public Attributes inherited from Eigen::TensorBase< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > >
static const int NumDimensions
Protected Member Functions inherited from Eigen::TensorBase< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & derived () const
Detailed Description
template<typename StartIndices, typename StopIndices, typename Strides, typename XprType>
class Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >
Definition at line 56 of file TensorForwardDeclarations.h.
Member Typedef Documentation
CoeffReturnType
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > typedef XprType::CoeffReturnType Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::CoeffReturnType
Definition at line 641 of file TensorMorphing.h.
Index
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > typedef internal::traits<TensorStridingSlicingOp>::Index Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::Index
Definition at line 644 of file TensorMorphing.h.
Nested
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > typedef internal::nested<TensorStridingSlicingOp>::type Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::Nested
Definition at line 642 of file TensorMorphing.h.
Scalar
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > typedef internal::traits<TensorStridingSlicingOp>::Scalar Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::Scalar
Definition at line 640 of file TensorMorphing.h.
StorageKind
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > typedef internal::traits<TensorStridingSlicingOp>::StorageKind Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::StorageKind
Definition at line 643 of file TensorMorphing.h.
Constructor & Destructor Documentation
TensorStridingSlicingOp()
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::TensorStridingSlicingOp (const XprType & expr, const StartIndices & startIndices, const StopIndices & stopIndices, const Strides & strides) inline
Definition at line 646 of file TensorMorphing.h.
Member Function Documentation
expression()
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > EIGEN_DEVICE_FUNC const internal::remove_all<typename XprType::Nested>::type& Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::expression () const inline
Definition at line 661 of file TensorMorphing.h.
operator=() [1/2]
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp& Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::operator= (const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType > & other) inline
Definition at line 664 of file TensorMorphing.h.
References Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run().
operator=() [2/2]
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp& Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::operator= (const OtherDerived & other) inline
Definition at line 675 of file TensorMorphing.h.
References Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run().
startIndices()
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > EIGEN_DEVICE_FUNC const StartIndices& Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::startIndices () const inline
Definition at line 653 of file TensorMorphing.h.
Referenced by Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::TensorEvaluator().
stopIndices()
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > EIGEN_DEVICE_FUNC const StartIndices& Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::stopIndices () const inline
Definition at line 655 of file TensorMorphing.h.
Referenced by Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::TensorEvaluator().
strides()
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > EIGEN_DEVICE_FUNC const StartIndices& Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::strides () const inline
Definition at line 657 of file TensorMorphing.h.
Field Documentation
m_startIndices
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > const StartIndices Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::m_startIndices protected
Definition at line 686 of file TensorMorphing.h.
m_stopIndices
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > const StopIndices Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::m_stopIndices protected
Definition at line 687 of file TensorMorphing.h.
m_strides
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > const Strides Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::m_strides protected
Definition at line 688 of file TensorMorphing.h.
m_xpr
template<typename StartIndices , typename StopIndices , typename Strides , typename XprType > XprType::Nested Eigen::TensorStridingSlicingOp< StartIndices, StopIndices, Strides, XprType >::m_xpr protected
Definition at line 685 of file TensorMorphing.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorForwardDeclarations.h
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h