pairinteraction: IcoSphere Class Reference
IcoSphere Class Reference
#include <icosphere.h>
Public Member Functions
IcoSphere (unsigned int levels=1)
const std::vector< Eigen::Vector3f > & vertices () const
const std::vector< int > & indices (int level) const
void draw (int level)
Protected Member Functions
void _subdivide ()
Protected Attributes
std::vector< Eigen::Vector3f > mVertices
std::vector< std::vector< int > * > mIndices
std::vector< int > mListIds
Detailed Description
Definition at line 16 of file icosphere.h.
Constructor & Destructor Documentation
IcoSphere()
IcoSphere::IcoSphere (unsigned int levels = 1)
Definition at line 36 of file icosphere.cpp.
References i.
Member Function Documentation
_subdivide()
void IcoSphere::_subdivide (void) protected
Definition at line 61 of file icosphere.cpp.
References i, and std::swap().
Referenced by vertices().
draw()
void IcoSphere::draw (int level)
Definition at line 100 of file icosphere.cpp.
References data, and size.
Referenced by GpuHelper::drawUnitSphere(), and vertices().
indices()
const std::vector< int > & IcoSphere::indices (int level) const
Definition at line 54 of file icosphere.cpp.
Referenced by vertices().
vertices()
const std::vector<Eigen::Vector3f>& IcoSphere::vertices () const inline
Definition at line 20 of file icosphere.h.
References _subdivide(), draw(), indices(), and mVertices.
Field Documentation
mIndices
std::vector<std::vector<int>*> IcoSphere::mIndices protected
Definition at line 26 of file icosphere.h.
mListIds
std::vector<int> IcoSphere::mListIds protected
Definition at line 27 of file icosphere.h.
mVertices
std::vector<Eigen::Vector3f> IcoSphere::mVertices protected
Definition at line 25 of file icosphere.h.
Referenced by vertices().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/demos/opengl/icosphere.h
/travis/libpairinteraction/eigen/demos/opengl/icosphere.cpp