pairinteraction: Eigen::Spline< _Scalar, _Dim, _Degree > Class Template Reference
Eigen::Spline< _Scalar, _Dim, _Degree > Class Template Reference
Geometry » Reference » Splines_Module
A class representing multi-dimensional spline curves.
#include <Spline.h>
Public Types
enum { Dimension = _Dim }
enum { Degree = _Degree }
typedef _Scalar Scalar
typedef SplineTraits< Spline >::PointType PointType
The point type the spline is representing.
typedef SplineTraits< Spline >::KnotVectorType KnotVectorType
The data type used to store knot vectors.
typedef SplineTraits< Spline >::ParameterVectorType ParameterVectorType
The data type used to store parameter vectors.
typedef SplineTraits< Spline >::BasisVectorType BasisVectorType
The data type used to store non-zero basis functions.
typedef SplineTraits< Spline >::BasisDerivativeType BasisDerivativeType
The data type used to store the values of the basis function derivatives.
typedef SplineTraits< Spline >::ControlPointVectorType ControlPointVectorType
The data type representing the spline's control points.
Public Member Functions
Spline ()
Creates a (constant) zero spline. For Splines with dynamic degree, the resulting degree will be 0.
template<typename OtherVectorType , typename OtherArrayType >
Spline (const OtherVectorType &knots, const OtherArrayType &ctrls)
Creates a spline from a knot vector and control points.
template<int OtherDegree>
Spline (const Spline< Scalar, Dimension, OtherDegree > &spline)
Copy constructor for splines.
const KnotVectorType & knots () const
Returns the knots of the underlying spline.
const ControlPointVectorType & ctrls () const
Returns the ctrls of the underlying spline.
PointType operator() (Scalar u) const
Returns the spline value at a given site \(u\).
SplineTraits< Spline >::DerivativeType derivatives (Scalar u, DenseIndex order) const
Evaluation of spline derivatives of up-to given order.
template<int DerivativeOrder>
SplineTraits< Spline, DerivativeOrder >::DerivativeType derivatives (Scalar u, DenseIndex order=DerivativeOrder) const
Evaluation of spline derivatives of up-to given order.
SplineTraits< Spline >::BasisVectorType basisFunctions (Scalar u) const
Computes the non-zero basis functions at the given site.
SplineTraits< Spline >::BasisDerivativeType basisFunctionDerivatives (Scalar u, DenseIndex order) const
Computes the non-zero spline basis function derivatives up to given order.
template<int DerivativeOrder>
SplineTraits< Spline, DerivativeOrder >::BasisDerivativeType basisFunctionDerivatives (Scalar u, DenseIndex order=DerivativeOrder) const
Computes the non-zero spline basis function derivatives up to given order.
DenseIndex degree () const
Returns the spline degree.
DenseIndex span (Scalar u) const
Returns the span within the knot vector in which u is falling.
Static Public Member Functions
static DenseIndex Span (typename SplineTraits< Spline >::Scalar u, DenseIndex degree, const typename SplineTraits< Spline >::KnotVectorType &knots)
Computes the spang within the provided knot vector in which u is falling.
static BasisVectorType BasisFunctions (Scalar u, DenseIndex degree, const KnotVectorType &knots)
Returns the spline's non-zero basis functions.
static BasisDerivativeType BasisFunctionDerivatives (const Scalar u, const DenseIndex order, const DenseIndex degree, const KnotVectorType &knots)
Computes the non-zero spline basis function derivatives up to given order.
Detailed Description
template<typename _Scalar, int _Dim, int _Degree>
class Eigen::Spline< _Scalar, _Dim, _Degree >
A class representing multi-dimensional spline curves.
The class represents B-splines with non-uniform knot vectors. Each control point of the B-spline is associated with a basis function
\begin{align*} C(u) & = \sum_{i=0}^{n}N_{i,p}(u)P_i \end{align*}
Template Parameters
_Scalar The underlying data type (typically float or double)
_Dim The curve dimension (e.g. 2 or 3)
_Degree Per default set to Dynamic; could be set to the actual desired degree for optimization purposes (would result in stack allocation of several temporary variables).
Definition at line 35 of file Spline.h.
Member Typedef Documentation
BasisDerivativeType
template<typename _Scalar, int _Dim, int _Degree> typedef SplineTraits<Spline>::BasisDerivativeType Eigen::Spline< _Scalar, _Dim, _Degree >::BasisDerivativeType
The data type used to store the values of the basis function derivatives.
Definition at line 55 of file Spline.h.
BasisVectorType
template<typename _Scalar, int _Dim, int _Degree> typedef SplineTraits<Spline>::BasisVectorType Eigen::Spline< _Scalar, _Dim, _Degree >::BasisVectorType
The data type used to store non-zero basis functions.
Definition at line 52 of file Spline.h.
ControlPointVectorType
template<typename _Scalar, int _Dim, int _Degree> typedef SplineTraits<Spline>::ControlPointVectorType Eigen::Spline< _Scalar, _Dim, _Degree >::ControlPointVectorType
The data type representing the spline's control points.
Definition at line 58 of file Spline.h.
KnotVectorType
template<typename _Scalar, int _Dim, int _Degree> typedef SplineTraits<Spline>::KnotVectorType Eigen::Spline< _Scalar, _Dim, _Degree >::KnotVectorType
The data type used to store knot vectors.
Definition at line 46 of file Spline.h.
ParameterVectorType
template<typename _Scalar, int _Dim, int _Degree> typedef SplineTraits<Spline>::ParameterVectorType Eigen::Spline< _Scalar, _Dim, _Degree >::ParameterVectorType
The data type used to store parameter vectors.
Definition at line 49 of file Spline.h.
PointType
template<typename _Scalar, int _Dim, int _Degree> typedef SplineTraits<Spline>::PointType Eigen::Spline< _Scalar, _Dim, _Degree >::PointType
The point type the spline is representing.
Definition at line 43 of file Spline.h.
Scalar
template<typename _Scalar, int _Dim, int _Degree> typedef _Scalar Eigen::Spline< _Scalar, _Dim, _Degree >::Scalar
The spline curve's scalar type.
Definition at line 38 of file Spline.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int _Dim, int _Degree> anonymous enum
Enumerator
Dimension
The spline curve's dimension.
Definition at line 39 of file Spline.h.
anonymous enum
template<typename _Scalar, int _Dim, int _Degree> anonymous enum
Enumerator
Degree
The spline curve's degree.
Definition at line 40 of file Spline.h.
Constructor & Destructor Documentation
Spline() [1/3]
template<typename _Scalar, int _Dim, int _Degree> Eigen::Spline< _Scalar, _Dim, _Degree >::Spline () inline
Creates a (constant) zero spline. For Splines with dynamic degree, the resulting degree will be 0.
Definition at line 64 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::Degree, and Eigen::Dynamic.
Spline() [2/3]
template<typename _Scalar, int _Dim, int _Degree> template<typename OtherVectorType , typename OtherArrayType > Eigen::Spline< _Scalar, _Dim, _Degree >::Spline (const OtherVectorType & knots, const OtherArrayType & ctrls) inline
Creates a spline from a knot vector and control points.
Parameters
knots The spline's knot vector.
ctrls The spline's control point vector.
Definition at line 81 of file Spline.h.
Spline() [3/3]
template<typename _Scalar, int _Dim, int _Degree> template<int OtherDegree> Eigen::Spline< _Scalar, _Dim, _Degree >::Spline (const Spline< Scalar, Dimension, OtherDegree > & spline) inline
Copy constructor for splines.
Parameters
spline The input spline.
Definition at line 88 of file Spline.h.
Member Function Documentation
basisFunctionDerivatives() [1/2]
template<typename _Scalar , int _Dim, int _Degree> SplineTraits< Spline< _Scalar, _Dim, _Degree >, DerivativeOrder >::BasisDerivativeType Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctionDerivatives (Scalar u, DenseIndex order) const
Computes the non-zero spline basis function derivatives up to given order.
The function computes
\begin{align*} \frac{d^i}{du^i} N_{i,p}(u), \hdots, \frac{d^i}{du^i} N_{i+p+1,p}(u) \end{align*}
with i ranging from 0 up to the specified order.
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis function derivatives are computed.
order The order up to which the basis function derivatives are computes.
Definition at line 481 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), and Eigen::Spline< _Scalar, _Dim, _Degree >::knots().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls().
basisFunctionDerivatives() [2/2]
template<typename _Scalar, int _Dim, int _Degree> template<int DerivativeOrder> SplineTraits<Spline,DerivativeOrder>::BasisDerivativeType Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctionDerivatives (Scalar u, DenseIndex order = DerivativeOrder) const
Computes the non-zero spline basis function derivatives up to given order.
The function computes
\begin{align*} \frac{d^i}{du^i} N_{i,p}(u), \hdots, \frac{d^i}{du^i} N_{i+p+1,p}(u) \end{align*}
with i ranging from 0 up to the specified order.
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis function derivatives are computed.
order The order up to which the basis function derivatives are computes. Using the template version of this function is more efficieent since temporary objects are allocated on the stack whenever this is possible.
BasisFunctionDerivatives()
template<typename _Scalar, int _Dim, int _Degree> SplineTraits< Spline< _Scalar, _Dim, _Degree > >::BasisDerivativeType Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctionDerivatives (const Scalar u, const DenseIndex order, const DenseIndex degree, const KnotVectorType & knots) static
Computes the non-zero spline basis function derivatives up to given order.
The function computes
\begin{align*} \frac{d^i}{du^i} N_{i,p}(u), \hdots, \frac{d^i}{du^i} N_{i+p+1,p}(u) \end{align*}
with i ranging from 0 up to the specified order.
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis function derivatives are computed.
order The order up to which the basis function derivatives are computes.
degree The degree of the underlying spline
knots The underlying spline's knot vector.
Definition at line 500 of file Spline.h.
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls().
basisFunctions()
template<typename _Scalar , int _Dim, int _Degree> SplineTraits< Spline< _Scalar, _Dim, _Degree > >::BasisVectorType Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions (Scalar u) const
Computes the non-zero basis functions at the given site.
Splines have local support and a point from their image is defined by exactly \(p+1\) control points \(P_i\) where \(p\) is the spline degree.
This function computes the \(p+1\) non-zero basis function values for a given parameter value \(u\). It returns
\begin{align*} N_{i,p}(u), \hdots, N_{i+p+1,p}(u) \end{align*}
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis functions are computed.
Definition at line 363 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), Eigen::Spline< _Scalar, _Dim, _Degree >::knots(), min, n, p, and Eigen::Spline< _Scalar, _Dim, _Degree >::span().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls(), and Eigen::Spline< _Scalar, _Dim, _Degree >::operator()().
BasisFunctions()
template<typename _Scalar, int _Dim, int _Degree> Spline< _Scalar, _Dim, _Degree >::BasisVectorType Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctions (Scalar u, DenseIndex degree, const KnotVectorType & knots) static
Returns the spline's non-zero basis functions.
The function computes and returns
\begin{align*} N_{i,p}(u), \hdots, N_{i+p+1,p}(u) \end{align*}
Parameters
u The site at which the basis functions are computed.
degree The degree of the underlying spline.
knots The underlying spline's knot vector.
Definition at line 247 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), i, Eigen::Spline< _Scalar, _Dim, _Degree >::knots(), p, and Eigen::Spline< _Scalar, _Dim, _Degree >::Span().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions(), and Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls().
ctrls()
template<typename _Scalar, int _Dim, int _Degree> const ControlPointVectorType& Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls () const inline
Returns the ctrls of the underlying spline.
Definition at line 99 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctionDerivatives(), Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctionDerivatives(), Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), Eigen::Spline< _Scalar, _Dim, _Degree >::derivatives(), Eigen::Spline< _Scalar, _Dim, _Degree >::knots(), Eigen::Spline< _Scalar, _Dim, _Degree >::operator()(), p, Eigen::Spline< _Scalar, _Dim, _Degree >::span(), and Eigen::Spline< _Scalar, _Dim, _Degree >::Span().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::operator()().
degree()
template<typename _Scalar , int _Dim, int _Degree> DenseIndex Eigen::Spline< _Scalar, _Dim, _Degree >::degree () const
Returns the spline degree.
Definition at line 282 of file Spline.h.
References Eigen::Dynamic.
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctionDerivatives(), Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls(), Eigen::Spline< _Scalar, _Dim, _Degree >::operator()(), Eigen::Spline< _Scalar, _Dim, _Degree >::span(), and Eigen::Spline< _Scalar, _Dim, _Degree >::Span().
derivatives() [1/2]
template<typename _Scalar , int _Dim, int _Degree> SplineTraits< Spline< _Scalar, _Dim, _Degree >, DerivativeOrder >::DerivativeType Eigen::Spline< _Scalar, _Dim, _Degree >::derivatives (Scalar u, DenseIndex order) const
Evaluation of spline derivatives of up-to given order.
The function returns
\begin{align*} \frac{d^i}{du^i}C(u) & = \sum_{i=0}^{n} \frac{d^i}{du^i} N_{i,p}(u)P_i \end{align*}
for i ranging between 0 and order.
Parameters
u Parameter \(u \in [0;1]\) at which the spline derivative is evaluated.
order The order up to which the derivatives are computed.
Definition at line 344 of file Spline.h.
References Eigen::derivativesImpl(), and res.
Referenced by check_global_interpolation_with_derivatives2d(), and Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls().
derivatives() [2/2]
template<typename _Scalar, int _Dim, int _Degree> template<int DerivativeOrder> SplineTraits<Spline,DerivativeOrder>::DerivativeType Eigen::Spline< _Scalar, _Dim, _Degree >::derivatives (Scalar u, DenseIndex order = DerivativeOrder) const
Evaluation of spline derivatives of up-to given order.
The function returns
\begin{align*} \frac{d^i}{du^i}C(u) & = \sum_{i=0}^{n} \frac{d^i}{du^i} N_{i,p}(u)P_i \end{align*}
for i ranging between 0 and order.
Parameters
u Parameter \(u \in [0;1]\) at which the spline derivative is evaluated.
order The order up to which the derivatives are computed. Using the template version of this function is more efficieent since temporary objects are allocated on the stack whenever this is possible.
knots()
template<typename _Scalar, int _Dim, int _Degree> const KnotVectorType& Eigen::Spline< _Scalar, _Dim, _Degree >::knots () const inline
Returns the knots of the underlying spline.
Definition at line 94 of file Spline.h.
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctionDerivatives(), Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls(), eval_spline3d_onbrks(), Eigen::Spline< _Scalar, _Dim, _Degree >::span(), and Eigen::Spline< _Scalar, _Dim, _Degree >::Span().
operator()()
template<typename _Scalar , int _Dim, int _Degree> Spline< _Scalar, _Dim, _Degree >::PointType Eigen::Spline< _Scalar, _Dim, _Degree >::operator() (Scalar u) const
Returns the spline value at a given site \(u\).
The function returns
\begin{align*} C(u) & = \sum_{i=0}^{n}N_{i,p}P_i \end{align*}
Parameters
u Parameter \(u \in [0;1]\) at which the spline is evaluated.
Returns
The spline value at the given location \(u\).
Definition at line 297 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls(), Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), Eigen::Spline< _Scalar, _Dim, _Degree >::Dimension, p, and Eigen::Spline< _Scalar, _Dim, _Degree >::span().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls().
span()
template<typename _Scalar , int _Dim, int _Degree> DenseIndex Eigen::Spline< _Scalar, _Dim, _Degree >::span (Scalar u) const
Returns the span within the knot vector in which u is falling.
Parameters
u The site for which the span is determined.
Definition at line 291 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), Eigen::Spline< _Scalar, _Dim, _Degree >::knots(), and Eigen::Spline< _Scalar, _Dim, _Degree >::Span().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::basisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls(), Eigen::derivativesImpl(), and Eigen::Spline< _Scalar, _Dim, _Degree >::operator()().
Span()
template<typename _Scalar , int _Dim, int _Degree> DenseIndex Eigen::Spline< _Scalar, _Dim, _Degree >::Span (typename SplineTraits< Spline< _Scalar, _Dim, _Degree > >::Scalar u, DenseIndex degree, const typename SplineTraits< Spline< _Scalar, _Dim, _Degree > >::KnotVectorType & knots) static
Computes the spang within the provided knot vector in which u is falling.
Definition at line 234 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), and Eigen::Spline< _Scalar, _Dim, _Degree >::knots().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::BasisFunctions(), Eigen::Spline< _Scalar, _Dim, _Degree >::ctrls(), and Eigen::Spline< _Scalar, _Dim, _Degree >::span().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/Splines/Spline.h