pairinteraction: Eigen::DynamicSGroup Class Reference
Eigen::DynamicSGroup Class Reference
Dynamic symmetry group.
#include <DynamicSymmetry.h>
Public Member Functions
DynamicSGroup ()
DynamicSGroup (const DynamicSGroup &o)
DynamicSGroup (DynamicSGroup &&o)
DynamicSGroup & operator= (const DynamicSGroup &o)
DynamicSGroup & operator= (DynamicSGroup &&o)
void add (int one, int two, int flags=0)
template<typename Gen_ >
void add (Gen_)
void addSymmetry (int one, int two)
void addAntiSymmetry (int one, int two)
void addHermiticity (int one, int two)
void addAntiHermiticity (int one, int two)
template<typename Op , typename RV , typename Index , std::size_t N, typename... Args>
RV apply (const std::array< Index, N > &idx, RV initial, Args &&... args) const
template<typename Op , typename RV , typename Index , typename... Args>
RV apply (const std::vector< Index > &idx, RV initial, Args &&... args) const
int globalFlags () const
std::size_t size () const
template<typename Tensor_ , typename... IndexTypes>
internal::tensor_symmetry_value_setter< Tensor_, DynamicSGroup > operator() (Tensor_ &tensor, typename Tensor_::Index firstIndex, IndexTypes... otherIndices) const
template<typename Tensor_ >
internal::tensor_symmetry_value_setter< Tensor_, DynamicSGroup > operator() (Tensor_ &tensor, std::array< typename Tensor_::Index, Tensor_::NumIndices > const &indices) const
Detailed Description
Dynamic symmetry group.
The DynamicSGroup class represents a symmetry group that need not be known at compile time. It is useful if one wants to support arbitrary run-time defineable symmetries for tensors, but it is also instantiated if a symmetry group is defined at compile time that would be either too large for the compiler to reasonably generate (using templates to calculate this at compile time is very inefficient) or that the compiler could generate the group but that it wouldn't make sense to unroll the loop for setting coefficients anymore.
Definition at line 15 of file DynamicSymmetry.h.
Constructor & Destructor Documentation
DynamicSGroup() [1/3]
Eigen::DynamicSGroup::DynamicSGroup () inline explicit
Definition at line 18 of file DynamicSymmetry.h.
DynamicSGroup() [2/3]
Eigen::DynamicSGroup::DynamicSGroup (const DynamicSGroup & o) inline
Definition at line 19 of file DynamicSymmetry.h.
DynamicSGroup() [3/3]
Eigen::DynamicSGroup::DynamicSGroup (DynamicSGroup && o) inline
Definition at line 20 of file DynamicSymmetry.h.
References std::swap().
Member Function Documentation
add() [1/2]
void Eigen::DynamicSGroup::add (int one, int two, int flags = 0) inline
Definition at line 195 of file DynamicSymmetry.h.
References Eigen::ConjugationFlag, e(), eigen_assert, model_potential::g(), Eigen::GlobalImagFlag, Eigen::GlobalRealFlag, Eigen::GlobalZeroFlag, i, Eigen::NegationFlag, and p.
Referenced by addAntiHermiticity(), addAntiSymmetry(), addHermiticity(), addSymmetry(), operator=(), and Eigen::DynamicSGroupFromTemplateArgs< Gen >::operator=().
add() [2/2]
template<typename Gen_ > void Eigen::DynamicSGroup::add (Gen_) inline
Definition at line 27 of file DynamicSymmetry.h.
References add().
Referenced by add().
addAntiHermiticity()
void Eigen::DynamicSGroup::addAntiHermiticity (int one, int two) inline
Definition at line 31 of file DynamicSymmetry.h.
References add(), Eigen::ConjugationFlag, and Eigen::NegationFlag.
addAntiSymmetry()
void Eigen::DynamicSGroup::addAntiSymmetry (int one, int two) inline
Definition at line 29 of file DynamicSymmetry.h.
References add(), and Eigen::NegationFlag.
addHermiticity()
void Eigen::DynamicSGroup::addHermiticity (int one, int two) inline
Definition at line 30 of file DynamicSymmetry.h.
References add(), and Eigen::ConjugationFlag.
addSymmetry()
void Eigen::DynamicSGroup::addSymmetry (int one, int two) inline
Definition at line 28 of file DynamicSymmetry.h.
References add().
apply() [1/2]
template<typename Op , typename RV , typename Index , std::size_t N, typename... Args> RV Eigen::DynamicSGroup::apply (const std::array< Index, N > & idx, RV initial, Args &&... args) const inline
Definition at line 34 of file DynamicSymmetry.h.
References eigen_assert, i, Eigen::TensorSycl::run(), and size().
apply() [2/2]
template<typename Op , typename RV , typename Index , typename... Args> RV Eigen::DynamicSGroup::apply (const std::vector< Index > & idx, RV initial, Args &&... args) const inline
Definition at line 43 of file DynamicSymmetry.h.
References eigen_assert, i, Eigen::TensorSycl::run(), and size().
globalFlags()
int Eigen::DynamicSGroup::globalFlags () const inline
Definition at line 51 of file DynamicSymmetry.h.
operator()() [1/2]
template<typename Tensor_ , typename... IndexTypes> internal::tensor_symmetry_value_setter<Tensor_, DynamicSGroup> Eigen::DynamicSGroup::operator() (Tensor_ & tensor, typename Tensor_::Index firstIndex, IndexTypes... otherIndices) const inline
Definition at line 55 of file DynamicSymmetry.h.
operator()() [2/2]
template<typename Tensor_ > internal::tensor_symmetry_value_setter<Tensor_, DynamicSGroup> Eigen::DynamicSGroup::operator() (Tensor_ & tensor, std::array< typename Tensor_::Index, Tensor_::NumIndices > const & indices) const inline
Definition at line 62 of file DynamicSymmetry.h.
References i.
operator=() [1/2]
DynamicSGroup& Eigen::DynamicSGroup::operator= (const DynamicSGroup & o) inline
Definition at line 21 of file DynamicSymmetry.h.
Referenced by Eigen::DynamicSGroupFromTemplateArgs< Gen >::operator=().
operator=() [2/2]
DynamicSGroup& Eigen::DynamicSGroup::operator= (DynamicSGroup && o) inline
Definition at line 22 of file DynamicSymmetry.h.
References add(), and std::swap().
size()
std::size_t Eigen::DynamicSGroup::size () const inline
Definition at line 52 of file DynamicSymmetry.h.
Referenced by apply().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/TensorSymmetry/DynamicSymmetry.h