pairinteraction: Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType > Class Template Reference
Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType > Class Template Reference
Modified Incomplete Cholesky with dual threshold.
#include <IncompleteCholesky.h>
Public Types
enum { UpLo = _UpLo }
enum { ColsAtCompileTime = Dynamic, MaxColsAtCompileTime = Dynamic }
typedef NumTraits< Scalar >::Real RealScalar
typedef _OrderingType OrderingType
typedef OrderingType::PermutationType PermutationType
typedef PermutationType::StorageIndex StorageIndex
typedef SparseMatrix< Scalar, ColMajor, StorageIndex > FactorType
typedef Matrix< Scalar, Dynamic, 1 > VectorSx
typedef Matrix< RealScalar, Dynamic, 1 > VectorRx
typedef Matrix< StorageIndex, Dynamic, 1 > VectorIx
typedef std::vector< std::list< StorageIndex > > VectorList
Public Member Functions
IncompleteCholesky ()
template<typename MatrixType >
IncompleteCholesky (const MatrixType &matrix)
Index rows () const
Index cols () const
ComputationInfo info () const
Reports whether previous computation was successful.
void setInitialShift (RealScalar shift)
Set the initial shift parameter \(\sigma \).
template<typename MatrixType >
void analyzePattern (const MatrixType &mat)
Computes the fill reducing permutation vector using the sparsity pattern of mat.
template<typename MatrixType >
void factorize (const MatrixType &mat)
Performs the numerical factorization of the input matrix mat.
template<typename MatrixType >
void compute (const MatrixType &mat)
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
const FactorType & matrixL () const
const VectorRx & scalingS () const
const PermutationType & permutationP () const
template<typename _MatrixType >
void factorize (const _MatrixType &mat)
Public Member Functions inherited from Eigen::SparseSolverBase< IncompleteCholesky< Scalar, _UpLo, _OrderingType > >
SparseSolverBase ()
~SparseSolverBase ()
IncompleteCholesky< Scalar, _UpLo, _OrderingType > & derived ()
const IncompleteCholesky< Scalar, _UpLo, _OrderingType > & derived () const
const Solve< IncompleteCholesky< Scalar, _UpLo, _OrderingType >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< IncompleteCholesky< Scalar, _UpLo, _OrderingType >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< IncompleteCholesky< Scalar, _UpLo, _OrderingType > > Base
Protected Attributes
FactorType m_L
VectorRx m_scale
RealScalar m_initialShift
bool m_analysisIsOk
bool m_factorizationIsOk
ComputationInfo m_info
PermutationType m_perm
Protected Attributes inherited from Eigen::SparseSolverBase< IncompleteCholesky< Scalar, _UpLo, _OrderingType > >
bool m_isInitialized
Detailed Description
template<typename Scalar, int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>>
class Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >
Modified Incomplete Cholesky with dual threshold.
References : C-J. Lin and J. J. Moré, Incomplete Cholesky Factorizations with Limited memory, SIAM J. Sci. Comput. 21(1), pp. 24-45, 1999
Template Parameters
Scalar the scalar type of the input matrices
_UpLo The triangular part that will be used for the computations. It can be Lower or Upper. Default is Lower.
_OrderingType The ordering method to use, either AMDOrdering<> or NaturalOrdering<>. Default is AMDOrdering<int>, unless EIGEN_MPL2_ONLY is defined, in which case the default is NaturalOrdering<int>.
It performs the following incomplete factorization: \(S P A P' S \approx L L' \) where L is a lower triangular factor, S is a diagonal scaling matrix, and P is a fill-in reducing permutation as computed by the ordering method.
Shifting strategy: Let \(B = S P A P' S \) be the scaled matrix on which the factorization is carried out, and \(\beta \) be the minimum value of the diagonal. If \(\beta > 0 \) then, the factorization is directly performed on the matrix B. Otherwise, the factorization is performed on the shifted matrix \(B + (\sigma+|\beta| I \) where \(\sigma \) is the initial shift value as returned and set by setInitialShift() method. The default value is \(\sigma = 10^{-3} \). If the factorization fails, then the shift in doubled until it succeed or a maximum of ten attempts. If it still fails, as returned by the info() method, then you can either increase the initial shift, or better use another preconditioning technique.
Definition at line 51 of file IncompleteCholesky.h.
Member Typedef Documentation
Base
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef SparseSolverBase<IncompleteCholesky<Scalar,_UpLo,_OrderingType> > Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::Base protected
Definition at line 54 of file IncompleteCholesky.h.
FactorType
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef SparseMatrix<Scalar,ColMajor,StorageIndex> Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::FactorType
Definition at line 61 of file IncompleteCholesky.h.
OrderingType
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef _OrderingType Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::OrderingType
Definition at line 58 of file IncompleteCholesky.h.
PermutationType
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef OrderingType::PermutationType Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::PermutationType
Definition at line 59 of file IncompleteCholesky.h.
RealScalar
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef NumTraits<Scalar>::Real Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::RealScalar
Definition at line 57 of file IncompleteCholesky.h.
StorageIndex
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef PermutationType::StorageIndex Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::StorageIndex
Definition at line 60 of file IncompleteCholesky.h.
VectorIx
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef Matrix<StorageIndex,Dynamic, 1> Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::VectorIx
Definition at line 64 of file IncompleteCholesky.h.
VectorList
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef std::vector<std::list<StorageIndex> > Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::VectorList
Definition at line 65 of file IncompleteCholesky.h.
VectorRx
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef Matrix<RealScalar,Dynamic,1> Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::VectorRx
Definition at line 63 of file IncompleteCholesky.h.
VectorSx
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> typedef Matrix<Scalar,Dynamic,1> Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::VectorSx
Definition at line 62 of file IncompleteCholesky.h.
Member Enumeration Documentation
anonymous enum
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> anonymous enum
Enumerator
UpLo
Definition at line 66 of file IncompleteCholesky.h.
anonymous enum
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
Definition at line 67 of file IncompleteCholesky.h.
Constructor & Destructor Documentation
IncompleteCholesky() [1/2]
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::IncompleteCholesky () inline
Default constructor leaving the object in a partly non-initialized stage.
You must call compute() or the pair analyzePattern()/factorize() to make it valid.
See also
IncompleteCholesky(const MatrixType&)
Definition at line 79 of file IncompleteCholesky.h.
IncompleteCholesky() [2/2]
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> template<typename MatrixType > Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::IncompleteCholesky (const MatrixType & matrix) inline
Constructor computing the incomplete factorization for the given matrix matrix.
Definition at line 84 of file IncompleteCholesky.h.
References Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::compute().
Member Function Documentation
_solve_impl()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> template<typename Rhs , typename Dest > void Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl (const Rhs & b, Dest & x) const inline
Definition at line 155 of file IncompleteCholesky.h.
References Eigen::SparseMatrixBase< Derived >::adjoint(), b, eigen_assert, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_factorizationIsOk, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_perm, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_scale, Eigen::SparseSolverBase< IncompleteCholesky< Scalar, _UpLo, _OrderingType > >::solve(), triangularView< Lower >(), and x.
analyzePattern()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> template<typename MatrixType > void Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern (const MatrixType & mat) inline
Computes the fill reducing permutation vector using the sparsity pattern of mat.
Definition at line 117 of file IncompleteCholesky.h.
References Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_analysisIsOk, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_info, Eigen::SparseSolverBase< IncompleteCholesky< Scalar, _UpLo, _OrderingType > >::m_isInitialized, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_perm, mat, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), and Eigen::Success.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::compute().
cols()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> Index Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::cols (void) const inline
Returns
number of columns of the factored matrix
Definition at line 93 of file IncompleteCholesky.h.
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L.
compute()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> template<typename MatrixType > void Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::compute (const MatrixType & mat) inline
Computes or re-computes the incomplete Cholesky factorization of the input matrix mat
It is a shortcut for a sequential call to the analyzePattern() and factorize() methods.
See also
analyzePattern(), factorize()
Definition at line 147 of file IncompleteCholesky.h.
References Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize().
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::IncompleteCholesky().
factorize() [1/2]
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> template<typename MatrixType > void Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize (const MatrixType & mat)
Performs the numerical factorization of the input matrix mat.
The method analyzePattern() or compute() must have been called beforehand with a matrix having the same pattern.
See also
compute(), analyzePattern()
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::compute().
factorize() [2/2]
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> template<typename _MatrixType > void Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize (const _MatrixType & mat)
Definition at line 196 of file IncompleteCholesky.h.
References abs2(), col(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), conj(), eigen_assert, eigen_internal_assert, i, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), j, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_analysisIsOk, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_factorizationIsOk, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_info, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_initialShift, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_perm, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_scale, min, n, Eigen::SparseCompressedBase< Derived >::nonZeros(), Eigen::NumericalIssue, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), p, Eigen::internal::QuickSplit(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::setZero(), sqrt(), Eigen::Success, std::swap(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr().
info()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> ComputationInfo Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::info () const inline
Reports whether previous computation was successful.
It triggers an assertion if *this has not been initialized through the respective constructor, or a call to compute() or analyzePattern().
Returns
Success if computation was successful, NumericalIssue if the matrix appears to be negative.
Definition at line 104 of file IncompleteCholesky.h.
References eigen_assert, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_info, and Eigen::SparseSolverBase< IncompleteCholesky< Scalar, _UpLo, _OrderingType > >::m_isInitialized.
matrixL()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> const FactorType& Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::matrixL () const inline
Returns
the sparse lower triangular factor L
Definition at line 169 of file IncompleteCholesky.h.
References eigen_assert, and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L.
permutationP()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> const PermutationType& Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::permutationP () const inline
Returns
the fill-in reducing permutation P (can be empty for a natural ordering)
Definition at line 175 of file IncompleteCholesky.h.
References eigen_assert, and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_perm.
rows()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> Index Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::rows (void) const inline
Returns
number of rows of the factored matrix
Definition at line 90 of file IncompleteCholesky.h.
References Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
scalingS()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> const VectorRx& Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::scalingS () const inline
Returns
a vector representing the scaling factor S
Definition at line 172 of file IncompleteCholesky.h.
References eigen_assert, and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_scale.
setInitialShift()
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> void Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::setInitialShift (RealScalar shift) inline
Set the initial shift parameter \(\sigma \).
Definition at line 112 of file IncompleteCholesky.h.
References Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_initialShift.
Field Documentation
m_analysisIsOk
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> bool Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_analysisIsOk protected
Definition at line 181 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize().
m_factorizationIsOk
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> bool Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_factorizationIsOk protected
Definition at line 182 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize().
m_info
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> ComputationInfo Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_info protected
Definition at line 183 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::info().
m_initialShift
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> RealScalar Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_initialShift protected
Definition at line 180 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::setInitialShift().
m_L
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> FactorType Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_L protected
Definition at line 178 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::cols(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::matrixL(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::rows().
m_perm
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> PermutationType Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_perm protected
Definition at line 184 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::permutationP().
m_scale
template<typename Scalar , int _UpLo = Lower, typename _OrderingType = AMDOrdering<int>> VectorRx Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::m_scale protected
Definition at line 179 of file IncompleteCholesky.h.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), and Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::scalingS().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h