pairinteraction: Eigen::DiagonalPreconditioner< _Scalar > Class Template Reference
Eigen::DiagonalPreconditioner< _Scalar > Class Template Reference
Sparse linear algebra » Reference » IterativeLinearSolvers_Module
A preconditioner based on the digonal entries.
#include <BasicPreconditioners.h>
Public Types
enum { ColsAtCompileTime = Dynamic, MaxColsAtCompileTime = Dynamic }
typedef Vector::StorageIndex StorageIndex
Public Member Functions
DiagonalPreconditioner ()
template<typename MatType >
DiagonalPreconditioner (const MatType &mat)
Index rows () const
Index cols () const
template<typename MatType >
DiagonalPreconditioner & analyzePattern (const MatType &)
template<typename MatType >
DiagonalPreconditioner & factorize (const MatType &mat)
template<typename MatType >
DiagonalPreconditioner & compute (const MatType &mat)
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
template<typename Rhs >
const Solve< DiagonalPreconditioner, Rhs > solve (const MatrixBase< Rhs > &b) const
ComputationInfo info ()
Protected Attributes
Vector m_invdiag
bool m_isInitialized
Detailed Description
template<typename _Scalar>
class Eigen::DiagonalPreconditioner< _Scalar >
A preconditioner based on the digonal entries.
This class allows to approximately solve for A.x = b problems assuming A is a diagonal matrix. In other words, this preconditioner neglects all off diagonal entries and, in Eigen's language, solves for:
A.diagonal().asDiagonal() . x = b
Template Parameters
_Scalar the type of the scalar.
This preconditioner is suitable for both selfadjoint and general problems. The diagonal entries are pre-inverted and stored into a dense vector.
Note
A variant that has yet to be implemented would attempt to preserve the norm of each column.
See also
class LeastSquareDiagonalPreconditioner, class ConjugateGradient
Definition at line 36 of file BasicPreconditioners.h.
Member Typedef Documentation
StorageIndex
template<typename _Scalar > typedef Vector::StorageIndex Eigen::DiagonalPreconditioner< _Scalar >::StorageIndex
Definition at line 41 of file BasicPreconditioners.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
Definition at line 42 of file BasicPreconditioners.h.
Constructor & Destructor Documentation
DiagonalPreconditioner() [1/2]
template<typename _Scalar > Eigen::DiagonalPreconditioner< _Scalar >::DiagonalPreconditioner () inline
Definition at line 47 of file BasicPreconditioners.h.
DiagonalPreconditioner() [2/2]
template<typename _Scalar > template<typename MatType > Eigen::DiagonalPreconditioner< _Scalar >::DiagonalPreconditioner (const MatType & mat) inline explicit
Definition at line 50 of file BasicPreconditioners.h.
References Eigen::DiagonalPreconditioner< _Scalar >::compute().
Member Function Documentation
_solve_impl()
template<typename _Scalar > template<typename Rhs , typename Dest > void Eigen::DiagonalPreconditioner< _Scalar >::_solve_impl (const Rhs & b, Dest & x) const inline
Definition at line 89 of file BasicPreconditioners.h.
References Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag.
analyzePattern()
template<typename _Scalar > template<typename MatType > DiagonalPreconditioner& Eigen::DiagonalPreconditioner< _Scalar >::analyzePattern (const MatType &) inline
Definition at line 59 of file BasicPreconditioners.h.
cols()
template<typename _Scalar > Index Eigen::DiagonalPreconditioner< _Scalar >::cols (void) const inline
Definition at line 56 of file BasicPreconditioners.h.
References Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag.
compute()
template<typename _Scalar > template<typename MatType > DiagonalPreconditioner& Eigen::DiagonalPreconditioner< _Scalar >::compute (const MatType & mat) inline
Definition at line 82 of file BasicPreconditioners.h.
References Eigen::DiagonalPreconditioner< _Scalar >::factorize().
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::DiagonalPreconditioner(), and Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::LeastSquareDiagonalPreconditioner().
factorize()
template<typename _Scalar > template<typename MatType > DiagonalPreconditioner& Eigen::DiagonalPreconditioner< _Scalar >::factorize (const MatType & mat) inline
Definition at line 65 of file BasicPreconditioners.h.
References j, Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag, Eigen::DiagonalPreconditioner< _Scalar >::m_isInitialized, and Eigen::PlainObjectBase< Derived >::resize().
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::compute(), and Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::compute().
info()
template<typename _Scalar > ComputationInfo Eigen::DiagonalPreconditioner< _Scalar >::info () inline
Definition at line 103 of file BasicPreconditioners.h.
References Eigen::Success.
rows()
template<typename _Scalar > Index Eigen::DiagonalPreconditioner< _Scalar >::rows (void) const inline
Definition at line 55 of file BasicPreconditioners.h.
References Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag.
solve()
template<typename _Scalar > template<typename Rhs > const Solve<DiagonalPreconditioner, Rhs> Eigen::DiagonalPreconditioner< _Scalar >::solve (const MatrixBase< Rhs > & b) const inline
Definition at line 95 of file BasicPreconditioners.h.
References eigen_assert, Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag, and Eigen::DiagonalPreconditioner< _Scalar >::m_isInitialized.
Field Documentation
m_invdiag
template<typename _Scalar > Vector Eigen::DiagonalPreconditioner< _Scalar >::m_invdiag protected
Definition at line 106 of file BasicPreconditioners.h.
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::_solve_impl(), Eigen::DiagonalPreconditioner< _Scalar >::cols(), Eigen::DiagonalPreconditioner< _Scalar >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), Eigen::DiagonalPreconditioner< _Scalar >::rows(), and Eigen::DiagonalPreconditioner< _Scalar >::solve().
m_isInitialized
template<typename _Scalar > bool Eigen::DiagonalPreconditioner< _Scalar >::m_isInitialized protected
Definition at line 107 of file BasicPreconditioners.h.
Referenced by Eigen::DiagonalPreconditioner< _Scalar >::factorize(), and Eigen::DiagonalPreconditioner< _Scalar >::solve().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h