pairinteraction: Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > Class Template Reference
Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Permutation matrix.
#include <PermutationMatrix.h>
Public Types
typedef const PermutationMatrix & Nested
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
Public Types inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >
enum
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
typedef Matrix< StorageIndex, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix< IndicesType::SizeAtCompileTime, IndicesType::MaxSizeAtCompileTime, StorageIndex > PlainPermutationType
typedef PlainPermutationType PlainObject
typedef Inverse< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > > InverseReturnType
typedef void Scalar
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
PermutationMatrix ()
PermutationMatrix (Index size)
template<typename OtherDerived >
PermutationMatrix (const PermutationBase< OtherDerived > &other)
PermutationMatrix (const PermutationMatrix &other)
template<typename Other >
PermutationMatrix (const MatrixBase< Other > &indices)
template<typename Other >
PermutationMatrix (const TranspositionsBase< Other > &tr)
template<typename Other >
PermutationMatrix & operator= (const PermutationBase< Other > &other)
template<typename Other >
PermutationMatrix & operator= (const TranspositionsBase< Other > &tr)
PermutationMatrix & operator= (const PermutationMatrix &other)
const IndicesType & indices () const
IndicesType & indices ()
template<typename Other >
PermutationMatrix (const InverseImpl< Other, PermutationStorage > &other)
template<typename Lhs , typename Rhs >
PermutationMatrix (internal::PermPermProduct_t, const Lhs &lhs, const Rhs &rhs)
Public Member Functions inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & operator= (const PermutationBase< OtherDerived > &other)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & operator= (const TranspositionsBase< OtherDerived > &tr)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & operator= (const PermutationBase &other)
Index rows () const
Index cols () const
Index size () const
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index newSize)
void setIdentity ()
void setIdentity (Index newSize)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & applyTranspositionOnTheLeft (Index i, Index j)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & applyTranspositionOnTheRight (Index i, Index j)
InverseReturnType inverse () const
InverseReturnType transpose () const
PlainPermutationType operator* (const PermutationBase< Other > &other) const
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other) const
Index determinant () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
IndicesType m_indices
Additional Inherited Members
Protected Member Functions inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >
void assignTranspose (const PermutationBase< OtherDerived > &other)
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Detailed Description
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex>
class Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >
Permutation matrix.
Template Parameters
SizeAtCompileTime the number of rows/cols, or Dynamic
MaxSizeAtCompileTime the maximum number of rows/cols, or Dynamic. This optional parameter defaults to SizeAtCompileTime. Most of the time, you should not have to specify it.
_StorageIndex the integer type of the indices
This class represents a permutation matrix, internally stored as a vector of integers.
See also
class PermutationBase, class PermutationWrapper, class DiagonalMatrix
Definition at line 308 of file PermutationMatrix.h.
Member Typedef Documentation
IndicesType
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> typedef Traits::IndicesType Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::IndicesType
Definition at line 317 of file PermutationMatrix.h.
Nested
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> typedef const PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::Nested
Definition at line 314 of file PermutationMatrix.h.
StorageIndex
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> typedef Traits::StorageIndex Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::StorageIndex
Definition at line 318 of file PermutationMatrix.h.
Constructor & Destructor Documentation
PermutationMatrix() [1/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix () inline
Definition at line 321 of file PermutationMatrix.h.
PermutationMatrix() [2/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (Index size) inline explicit
Constructs an uninitialized permutation matrix of given size.
Definition at line 326 of file PermutationMatrix.h.
PermutationMatrix() [3/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename OtherDerived > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (const PermutationBase< OtherDerived > & other) inline
Copy constructor.
Definition at line 333 of file PermutationMatrix.h.
PermutationMatrix() [4/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (const PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & other) inline
Standard copy constructor. Defined only to prevent a default copy constructor from hiding the other templated constructor
Definition at line 339 of file PermutationMatrix.h.
PermutationMatrix() [5/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (const MatrixBase< Other > & indices) inline explicit
Generic constructor from expression of the indices. The indices array has the meaning that the permutations sends each integer i to indices[i].
Warning
It is your responsibility to check that the indices array that you passes actually describes a permutation, i.e., each value between 0 and n-1 occurs exactly once, where n is the array's size.
Definition at line 350 of file PermutationMatrix.h.
PermutationMatrix() [6/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (const TranspositionsBase< Other > & tr) inline explicit
Convert the Transpositions tr to a permutation matrix
Definition at line 355 of file PermutationMatrix.h.
PermutationMatrix() [7/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (const InverseImpl< Other, PermutationStorage > & other) inline
Definition at line 397 of file PermutationMatrix.h.
PermutationMatrix() [8/8]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename Lhs , typename Rhs > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix (internal::PermPermProduct_t , const Lhs & lhs, const Rhs & rhs) inline
Definition at line 406 of file PermutationMatrix.h.
Member Function Documentation
indices() [1/2]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> const IndicesType& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices () const inline
const version of indices().
Definition at line 388 of file PermutationMatrix.h.
Referenced by Eigen::FullPivLU< _MatrixType >::_solve_impl_transposed(), Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::internal::lmqrsolv(), Eigen::internal::minimum_degree_ordering(), Eigen::MetisOrdering< StorageIndex >::operator()(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run(), Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run(), sparse_permutations(), testLmder(), and testLmdif().
indices() [2/2]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> IndicesType& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices () inline
Returns
a reference to the stored array representing the permutation.
Definition at line 390 of file PermutationMatrix.h.
operator=() [1/3]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename Other > PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::operator= (const PermutationBase< Other > & other) inline
Copies the other permutation into *this
Definition at line 363 of file PermutationMatrix.h.
operator=() [2/3]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> template<typename Other > PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::operator= (const TranspositionsBase< Other > & tr) inline
Assignment from the Transpositions tr
Definition at line 371 of file PermutationMatrix.h.
operator=() [3/3]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::operator= (const PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 380 of file PermutationMatrix.h.
Field Documentation
m_indices
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename _StorageIndex> IndicesType Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::m_indices protected
Definition at line 415 of file PermutationMatrix.h.
Referenced by Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/PermutationMatrix.h