pairinteraction: Eigen::PartialPivLU< _MatrixType > Class Template Reference
Eigen::PartialPivLU< _MatrixType > Class Template Reference
Dense linear problems and decompositions » Reference » LU_Module
LU decomposition of a matrix with partial pivoting, and related features.
#include <ForwardDeclarations.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef SolverBase< PartialPivLU > Base
typedef PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime > PermutationType
typedef Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime > TranspositionType
typedef MatrixType::PlainObject PlainObject
Public Types inherited from Eigen::SolverBase< PartialPivLU< _MatrixType > >
enum
typedef EigenBase< PartialPivLU< _MatrixType > > Base
typedef internal::traits< PartialPivLU< _MatrixType > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef internal::add_const< Transpose< const PartialPivLU< _MatrixType > > >::type ConstTransposeReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType >::type AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
PartialPivLU ()
Default Constructor.
PartialPivLU (Index size)
Default Constructor with memory preallocation.
template<typename InputType >
PartialPivLU (const EigenBase< InputType > &matrix)
template<typename InputType >
PartialPivLU (EigenBase< InputType > &matrix)
template<typename InputType >
PartialPivLU & compute (const EigenBase< InputType > &matrix)
const MatrixType & matrixLU () const
const PermutationType & permutationP () const
template<typename Rhs >
const Solve< PartialPivLU, Rhs > solve (const MatrixBase< Rhs > &b) const
RealScalar rcond () const
const Inverse< PartialPivLU > inverse () const
Scalar determinant () const
MatrixType reconstructedMatrix () const
Index rows () const
Index cols () const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
Public Member Functions inherited from Eigen::SolverBase< PartialPivLU< _MatrixType > >
SolverBase ()
~SolverBase ()
const Solve< PartialPivLU< _MatrixType >, Rhs > solve (const MatrixBase< Rhs > &b) const
ConstTransposeReturnType transpose () const
AdjointReturnType adjoint () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void compute ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_lu
PermutationType m_p
TranspositionType m_rowsTranspositions
RealScalar m_l1_norm
signed char m_det_p
bool m_isInitialized
Detailed Description
template<typename _MatrixType>
class Eigen::PartialPivLU< _MatrixType >
LU decomposition of a matrix with partial pivoting, and related features.
Template Parameters
_MatrixType the type of the matrix of which we are computing the LU decomposition
This class represents a LU decomposition of a square invertible matrix, with partial pivoting: the matrix A is decomposed as A = PLU where L is unit-lower-triangular, U is upper-triangular, and P is a permutation matrix.
Typically, partial pivoting LU decomposition is only considered numerically stable for square invertible matrices. Thus LAPACK's dgesv and dgesvx require the matrix to be square and invertible. The present class does the same. It will assert that the matrix is square, but it won't (actually it can't) check that the matrix is invertible: it is your task to check that you only use this decomposition on invertible matrices.
The guaranteed safe alternative, working for all matrices, is the full pivoting LU decomposition, provided by class FullPivLU.
This is not a rank-revealing LU decomposition. Many features are intentionally absent from this class, such as rank computation. If you need these features, use class FullPivLU.
This LU decomposition is suitable to invert invertible matrices. It is what MatrixBase::inverse() uses in the general case. On the other hand, it is not suitable to determine whether a given matrix is invertible.
The data of the LU decomposition can be directly accessed through the methods matrixLU(), permutationP().
This class supports the inplace decomposition mechanism.
See also
MatrixBase::partialPivLu(), MatrixBase::determinant(), MatrixBase::inverse(), MatrixBase::computeInverse(), class FullPivLU
Definition at line 250 of file ForwardDeclarations.h.
Member Typedef Documentation
Base
template<typename _MatrixType> typedef SolverBase<PartialPivLU> Eigen::PartialPivLU< _MatrixType >::Base
Definition at line 81 of file PartialPivLU.h.
MatrixType
template<typename _MatrixType> typedef _MatrixType Eigen::PartialPivLU< _MatrixType >::MatrixType
Definition at line 80 of file PartialPivLU.h.
PermutationType
template<typename _MatrixType> typedef PermutationMatrix<RowsAtCompileTime, MaxRowsAtCompileTime> Eigen::PartialPivLU< _MatrixType >::PermutationType
Definition at line 88 of file PartialPivLU.h.
PlainObject
template<typename _MatrixType> typedef MatrixType::PlainObject Eigen::PartialPivLU< _MatrixType >::PlainObject
Definition at line 90 of file PartialPivLU.h.
TranspositionType
template<typename _MatrixType> typedef Transpositions<RowsAtCompileTime, MaxRowsAtCompileTime> Eigen::PartialPivLU< _MatrixType >::TranspositionType
Definition at line 89 of file PartialPivLU.h.
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType> anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 84 of file PartialPivLU.h.
Constructor & Destructor Documentation
PartialPivLU() [1/4]
template<typename MatrixType > Eigen::PartialPivLU< MatrixType >::PartialPivLU ()
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via PartialPivLU::compute(const MatrixType&).
Definition at line 292 of file PartialPivLU.h.
PartialPivLU() [2/4]
template<typename MatrixType > Eigen::PartialPivLU< MatrixType >::PartialPivLU (Index size) explicit
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
PartialPivLU()
Definition at line 303 of file PartialPivLU.h.
PartialPivLU() [3/4]
template<typename MatrixType > template<typename InputType > Eigen::PartialPivLU< MatrixType >::PartialPivLU (const EigenBase< InputType > & matrix) explicit
Constructor.
Parameters
matrix the matrix of which to compute the LU decomposition.
Warning
The matrix should have full rank (e.g. if it's square, it should be invertible). If you need to deal with non-full rank, use class FullPivLU instead.
Definition at line 315 of file PartialPivLU.h.
PartialPivLU() [4/4]
template<typename MatrixType > template<typename InputType > Eigen::PartialPivLU< MatrixType >::PartialPivLU (EigenBase< InputType > & matrix) explicit
Constructor for inplace decomposition
Parameters
matrix the matrix of which to compute the LU decomposition.
Warning
The matrix should have full rank (e.g. if it's square, it should be invertible). If you need to deal with non-full rank, use class FullPivLU instead.
Definition at line 328 of file PartialPivLU.h.
Member Function Documentation
_solve_impl()
template<typename _MatrixType> template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::PartialPivLU< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const inline
Definition at line 226 of file PartialPivLU.h.
_solve_impl_transposed()
template<typename _MatrixType> template<bool Conjugate, typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::PartialPivLU< _MatrixType >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const inline
Definition at line 248 of file PartialPivLU.h.
check_template_parameters()
template<typename _MatrixType> static void Eigen::PartialPivLU< _MatrixType >::check_template_parameters () inline static protected
Definition at line 276 of file PartialPivLU.h.
cols()
template<typename _MatrixType> Index Eigen::PartialPivLU< _MatrixType >::cols (void) const inline
Definition at line 221 of file PartialPivLU.h.
compute() [1/2]
template<typename _MatrixType> template<typename InputType > PartialPivLU& Eigen::PartialPivLU< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
Definition at line 129 of file PartialPivLU.h.
Referenced by ctms_decompositions(), and main().
compute() [2/2]
template<typename MatrixType > void Eigen::PartialPivLU< MatrixType >::compute () protected
Definition at line 515 of file PartialPivLU.h.
determinant()
template<typename MatrixType > PartialPivLU< MatrixType >::Scalar Eigen::PartialPivLU< MatrixType >::determinant () const
Returns
the determinant of the matrix of which *this is the LU decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the LU decomposition has already been computed.
Note
For fixed-size matrices of size up to 4, MatrixBase::determinant() offers optimized paths.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow.
See also
MatrixBase::determinant()
Definition at line 539 of file PartialPivLU.h.
inverse()
template<typename _MatrixType> const Inverse<PartialPivLU> Eigen::PartialPivLU< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the LU decomposition.
Warning
The matrix being decomposed here is assumed to be invertible. If you need to check for invertibility, use class FullPivLU instead.
See also
MatrixBase::inverse(), LU::inverse()
Definition at line 197 of file PartialPivLU.h.
Referenced by lu_partial_piv().
matrixLU()
template<typename _MatrixType> const MatrixType& Eigen::PartialPivLU< _MatrixType >::matrixLU () const inline
Returns
the LU decomposition matrix: the upper-triangular part is U, the unit-lower-triangular part is L (at least for square matrices; in the non-square case, special care is needed, see the documentation of class FullPivLU).
See also
matrixL(), matrixU()
Definition at line 141 of file PartialPivLU.h.
Referenced by main().
permutationP()
template<typename _MatrixType> const PermutationType& Eigen::PartialPivLU< _MatrixType >::permutationP () const inline
Returns
the permutation matrix P.
Definition at line 149 of file PartialPivLU.h.
rcond()
template<typename _MatrixType> RealScalar Eigen::PartialPivLU< _MatrixType >::rcond () const inline
Returns
an estimate of the reciprocal condition number of the matrix of which *this is the LU decomposition.
Definition at line 184 of file PartialPivLU.h.
Referenced by lu_partial_piv().
reconstructedMatrix()
template<typename MatrixType > MatrixType Eigen::PartialPivLU< MatrixType >::reconstructedMatrix () const
Returns
the matrix represented by the decomposition, i.e., it returns the product: P^{-1} L U. This function is provided for debug purpose.
Definition at line 549 of file PartialPivLU.h.
Referenced by lu_partial_piv().
rows()
template<typename _MatrixType> Index Eigen::PartialPivLU< _MatrixType >::rows (void) const inline
Definition at line 220 of file PartialPivLU.h.
solve()
template<typename _MatrixType> template<typename Rhs > const Solve<PartialPivLU, Rhs> Eigen::PartialPivLU< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method returns the solution x to the equation Ax=b, where A is the matrix of which *this is the LU decomposition.
Parameters
b the right-hand-side of the equation to solve. Can be a vector or a matrix, the only requirement in order for the equation to make sense is that b.rows()==A.rows(), where A is the matrix of which *this is the LU decomposition.
Returns
the solution.
Example:
Output:
Since this PartialPivLU class assumes anyway that the matrix A is invertible, the solution theoretically exists and is unique regardless of b.
See also
TriangularView::solve(), inverse(), computeInverse()
Definition at line 175 of file PartialPivLU.h.
Referenced by ctms_decompositions(), lu_partial_piv(), and main().
Field Documentation
m_det_p
template<typename _MatrixType> signed char Eigen::PartialPivLU< _MatrixType >::m_det_p protected
Definition at line 287 of file PartialPivLU.h.
m_isInitialized
template<typename _MatrixType> bool Eigen::PartialPivLU< _MatrixType >::m_isInitialized protected
Definition at line 288 of file PartialPivLU.h.
m_l1_norm
template<typename _MatrixType> RealScalar Eigen::PartialPivLU< _MatrixType >::m_l1_norm protected
Definition at line 286 of file PartialPivLU.h.
m_lu
template<typename _MatrixType> MatrixType Eigen::PartialPivLU< _MatrixType >::m_lu protected
Definition at line 283 of file PartialPivLU.h.
m_p
template<typename _MatrixType> PermutationType Eigen::PartialPivLU< _MatrixType >::m_p protected
Definition at line 284 of file PartialPivLU.h.
m_rowsTranspositions
template<typename _MatrixType> TranspositionType Eigen::PartialPivLU< _MatrixType >::m_rowsTranspositions protected
Definition at line 285 of file PartialPivLU.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/LU/PartialPivLU.h