pairinteraction: Eigen::HouseholderQR< _MatrixType > Class Template Reference
Eigen::HouseholderQR< _MatrixType > Class Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Householder QR decomposition of a matrix.
#include <ForwardDeclarations.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< Scalar, RowsAtCompileTime, RowsAtCompileTime,(MatrixType::Flags &RowMajorBit) ? RowMajor :ColMajor, MaxRowsAtCompileTime, MaxRowsAtCompileTime > MatrixQType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType >::type > HouseholderSequenceType
Public Member Functions
HouseholderQR ()
Default Constructor.
HouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
HouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
HouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename Rhs >
const Solve< HouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ () const
const MatrixType & matrixQR () const
template<typename InputType >
HouseholderQR & compute (const EigenBase< InputType > &matrix)
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
RowVectorType m_temp
bool m_isInitialized
Detailed Description
template<typename _MatrixType>
class Eigen::HouseholderQR< _MatrixType >
Householder QR decomposition of a matrix.
Template Parameters
_MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a QR decomposition of a matrix A into matrices Q and R such that
\[ \mathbf{A} = \mathbf{Q} \, \mathbf{R} \]
by using Householder transformations. Here, Q a unitary matrix and R an upper triangular matrix. The result is stored in a compact way compatible with LAPACK.
Note that no pivoting is performed. This is not a rank-revealing decomposition. If you want that feature, use FullPivHouseholderQR or ColPivHouseholderQR instead.
This Householder QR decomposition is faster, but less numerically stable and less feature-full than FullPivHouseholderQR or ColPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::householderQr()
Definition at line 254 of file ForwardDeclarations.h.
Member Typedef Documentation
HCoeffsType
template<typename _MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::HouseholderQR< _MatrixType >::HCoeffsType
Definition at line 60 of file HouseholderQR.h.
HouseholderSequenceType
template<typename _MatrixType> typedef HouseholderSequence<MatrixType,typename internal::remove_all<typename HCoeffsType::ConjugateReturnType>::type> Eigen::HouseholderQR< _MatrixType >::HouseholderSequenceType
Definition at line 62 of file HouseholderQR.h.
MatrixQType
template<typename _MatrixType> typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, (MatrixType::Flags&RowMajorBit) ? RowMajor : ColMajor, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::HouseholderQR< _MatrixType >::MatrixQType
Definition at line 59 of file HouseholderQR.h.
MatrixType
template<typename _MatrixType> typedef _MatrixType Eigen::HouseholderQR< _MatrixType >::MatrixType
Definition at line 48 of file HouseholderQR.h.
RealScalar
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::HouseholderQR< _MatrixType >::RealScalar
Definition at line 56 of file HouseholderQR.h.
RowVectorType
template<typename _MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::HouseholderQR< _MatrixType >::RowVectorType
Definition at line 61 of file HouseholderQR.h.
Scalar
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::HouseholderQR< _MatrixType >::Scalar
Definition at line 55 of file HouseholderQR.h.
StorageIndex
template<typename _MatrixType> typedef MatrixType::StorageIndex Eigen::HouseholderQR< _MatrixType >::StorageIndex
Definition at line 58 of file HouseholderQR.h.
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 49 of file HouseholderQR.h.
Constructor & Destructor Documentation
HouseholderQR() [1/4]
template<typename _MatrixType> Eigen::HouseholderQR< _MatrixType >::HouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via HouseholderQR::compute(const MatrixType&).
Definition at line 70 of file HouseholderQR.h.
HouseholderQR() [2/4]
template<typename _MatrixType> Eigen::HouseholderQR< _MatrixType >::HouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
HouseholderQR()
Definition at line 78 of file HouseholderQR.h.
HouseholderQR() [3/4]
template<typename _MatrixType> template<typename InputType > Eigen::HouseholderQR< _MatrixType >::HouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
HouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
Definition at line 97 of file HouseholderQR.h.
HouseholderQR() [4/4]
template<typename _MatrixType> template<typename InputType > Eigen::HouseholderQR< _MatrixType >::HouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
HouseholderQR(const EigenBase&)
Definition at line 115 of file HouseholderQR.h.
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType> template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::HouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::hCoeffs().
_solve_impl() [2/2]
template<typename _MatrixType> template<typename RhsType , typename DstType > void Eigen::HouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
Definition at line 350 of file HouseholderQR.h.
absDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
Definition at line 236 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), qr_invertible(), and qr_verify_assert().
check_template_parameters()
template<typename _MatrixType> static void Eigen::HouseholderQR< _MatrixType >::check_template_parameters () inline static protected
Definition at line 222 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace().
cols()
template<typename _MatrixType> Index Eigen::HouseholderQR< _MatrixType >::cols (void) const inline
Definition at line 206 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::_solve_impl(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::internal::householder_qr_inplace_unblocked(), and Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run().
compute()
template<typename _MatrixType> template<typename InputType > HouseholderQR& Eigen::HouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
Definition at line 170 of file HouseholderQR.h.
Referenced by ctms_decompositions(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::HouseholderQR(), and qr_invertible().
computeInPlace()
template<typename MatrixType > void Eigen::HouseholderQR< MatrixType >::computeInPlace () protected
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class HouseholderQR, HouseholderQR(const MatrixType&)
Definition at line 379 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::check_template_parameters(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), and Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::HouseholderQR().
hCoeffs()
template<typename _MatrixType> const HCoeffsType& Eigen::HouseholderQR< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
Definition at line 212 of file HouseholderQR.h.
Referenced by householder().
householderQ()
template<typename _MatrixType> HouseholderSequenceType Eigen::HouseholderQR< _MatrixType >::householderQ (void) const inline
This method returns an expression of the unitary matrix Q as a sequence of Householder transformations.
The returned expression can directly be used to perform matrix products. It can also be assigned to a dense Matrix object. Here is an example showing how to recover the full or thin matrix Q, as well as how to perform matrix products using operator*:
Example:
Output:
Definition at line 154 of file HouseholderQR.h.
Referenced by Eigen::createRandomPIMatrixOfRank(), qr(), qr_fixedsize(), qr_invertible(), qr_verify_assert(), randomMatrixWithRealEivals(), randomMatrixWithImagEivals< MatrixType, 0 >::run(), randomMatrixWithImagEivals< MatrixType, 1 >::run(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), and Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep().
logAbsDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
Definition at line 245 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), qr_invertible(), and qr_verify_assert().
matrixQR()
template<typename _MatrixType> const MatrixType& Eigen::HouseholderQR< _MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored in a LAPACK-compatible way.
Definition at line 163 of file HouseholderQR.h.
Referenced by householder(), qr(), qr_fixedsize(), qr_verify_assert(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), and Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep().
rows()
template<typename _MatrixType> Index Eigen::HouseholderQR< _MatrixType >::rows (void) const inline
Definition at line 205 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::_solve_impl(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::internal::householder_qr_inplace_unblocked(), and Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run().
solve()
template<typename _MatrixType> template<typename Rhs > const Solve<HouseholderQR, Rhs> Eigen::HouseholderQR< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition, if any exists.
Parameters
b the right-hand-side of the equation to solve.
Returns
a solution.
Example:
Output:
Definition at line 140 of file HouseholderQR.h.
Referenced by ctms_decompositions(), Eigen::SplineFitting< SplineType >::Interpolate(), qr_fixedsize(), qr_invertible(), and qr_verify_assert().
Field Documentation
m_hCoeffs
template<typename _MatrixType> HCoeffsType Eigen::HouseholderQR< _MatrixType >::m_hCoeffs protected
Definition at line 230 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::_solve_impl(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::hCoeffs(), and Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::householderQ().
m_isInitialized
template<typename _MatrixType> bool Eigen::HouseholderQR< _MatrixType >::m_isInitialized protected
Definition at line 232 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::absDeterminant(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::householderQ(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::logAbsDeterminant(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::matrixQR(), and Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::solve().
m_qr
template<typename _MatrixType> MatrixType Eigen::HouseholderQR< _MatrixType >::m_qr protected
Definition at line 229 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::_solve_impl(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::absDeterminant(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::cols(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::householderQ(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::logAbsDeterminant(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::matrixQR(), and Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::rows().
m_temp
template<typename _MatrixType> RowVectorType Eigen::HouseholderQR< _MatrixType >::m_temp protected
Definition at line 231 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/QR/HouseholderQR.h