pairinteraction: Eigen::LevenbergMarquardt< _FunctorType > Class Template Reference
Eigen::LevenbergMarquardt< _FunctorType > Class Template Reference
Performs non linear optimization over a non-linear function, using a variant of the Levenberg Marquardt algorithm.
#include <LevenbergMarquardt.h>
Data Structures
struct Parameters
Public Types
typedef _FunctorType FunctorType
typedef FunctorType::QRSolver QRSolver
typedef FunctorType::JacobianType JacobianType
typedef JacobianType::Scalar Scalar
typedef JacobianType::RealScalar RealScalar
typedef QRSolver::StorageIndex PermIndex
typedef Matrix< Scalar, Dynamic, 1 > FVectorType
typedef PermutationMatrix< Dynamic, Dynamic > PermutationType
typedef DenseIndex Index
typedef Matrix< Scalar, Dynamic, 1 > FVectorType
typedef Matrix< Scalar, Dynamic, Dynamic > JacobianType
Public Member Functions
LevenbergMarquardt (FunctorType &functor)
LevenbergMarquardtSpace::Status minimize (FVectorType &x)
LevenbergMarquardtSpace::Status minimizeInit (FVectorType &x)
LevenbergMarquardtSpace::Status minimizeOneStep (FVectorType &x)
LevenbergMarquardtSpace::Status lmder1 (FVectorType &x, const Scalar tol=std::sqrt(NumTraits< Scalar >::epsilon()))
void resetParameters ()
void setXtol (RealScalar xtol)
void setFtol (RealScalar ftol)
void setGtol (RealScalar gtol)
void setFactor (RealScalar factor)
void setEpsilon (RealScalar epsfcn)
void setMaxfev (Index maxfev)
void setExternalScaling (bool value)
RealScalar xtol () const
RealScalar ftol () const
RealScalar gtol () const
RealScalar factor () const
RealScalar epsilon () const
Index maxfev () const
FVectorType & diag ()
Index iterations ()
Index nfev ()
Index njev ()
RealScalar fnorm ()
RealScalar gnorm ()
RealScalar lm_param (void)
FVectorType & fvec ()
JacobianType & jacobian ()
JacobianType & matrixR ()
PermutationType permutation ()
ComputationInfo info () const
Reports whether the minimization was successful.
LevenbergMarquardt (FunctorType &_functor)
LevenbergMarquardtSpace::Status lmder1 (FVectorType &x, const Scalar tol=sqrt_epsilon())
LevenbergMarquardtSpace::Status minimize (FVectorType &x)
LevenbergMarquardtSpace::Status minimizeInit (FVectorType &x)
LevenbergMarquardtSpace::Status minimizeOneStep (FVectorType &x)
LevenbergMarquardtSpace::Status lmstr1 (FVectorType &x, const Scalar tol=sqrt_epsilon())
LevenbergMarquardtSpace::Status minimizeOptimumStorage (FVectorType &x)
LevenbergMarquardtSpace::Status minimizeOptimumStorageInit (FVectorType &x)
LevenbergMarquardtSpace::Status minimizeOptimumStorageOneStep (FVectorType &x)
void resetParameters (void)
Scalar lm_param (void)
Static Public Member Functions
static LevenbergMarquardtSpace::Status lmdif1 (FunctorType &functor, FVectorType &x, Index *nfev, const Scalar tol=std::sqrt(NumTraits< Scalar >::epsilon()))
static LevenbergMarquardtSpace::Status lmdif1 (FunctorType &functor, FVectorType &x, Index *nfev, const Scalar tol=sqrt_epsilon())
Data Fields
Parameters parameters
FVectorType fvec
FVectorType qtf
FVectorType diag
JacobianType fjac
PermutationMatrix< Dynamic, Dynamic > permutation
Index nfev
Index njev
Index iter
Scalar fnorm
Scalar gnorm
bool useExternalScaling
Detailed Description
template<typename _FunctorType>
class Eigen::LevenbergMarquardt< _FunctorType >
Performs non linear optimization over a non-linear function, using a variant of the Levenberg Marquardt algorithm.
Check wikipedia for more information. http://en.wikipedia.org/wiki/Levenberg%E2%80%93Marquardt_algorithm
Definition at line 110 of file LevenbergMarquardt.h.
Member Typedef Documentation
FunctorType
template<typename _FunctorType> typedef _FunctorType Eigen::LevenbergMarquardt< _FunctorType >::FunctorType
Definition at line 113 of file LevenbergMarquardt.h.
FVectorType [1/2]
template<typename _FunctorType> typedef Matrix< Scalar, Dynamic, 1 > Eigen::LevenbergMarquardt< _FunctorType >::FVectorType
Definition at line 76 of file LevenbergMarquardt.h.
FVectorType [2/2]
template<typename _FunctorType> typedef Matrix<Scalar,Dynamic,1> Eigen::LevenbergMarquardt< _FunctorType >::FVectorType
Definition at line 119 of file LevenbergMarquardt.h.
Index
template<typename _FunctorType> typedef DenseIndex Eigen::LevenbergMarquardt< _FunctorType >::Index
Definition at line 58 of file LevenbergMarquardt.h.
JacobianType [1/2]
template<typename _FunctorType> typedef Matrix< Scalar, Dynamic, Dynamic > Eigen::LevenbergMarquardt< _FunctorType >::JacobianType
Definition at line 77 of file LevenbergMarquardt.h.
JacobianType [2/2]
template<typename _FunctorType> typedef FunctorType::JacobianType Eigen::LevenbergMarquardt< _FunctorType >::JacobianType
Definition at line 115 of file LevenbergMarquardt.h.
PermIndex
template<typename _FunctorType> typedef QRSolver::StorageIndex Eigen::LevenbergMarquardt< _FunctorType >::PermIndex
Definition at line 118 of file LevenbergMarquardt.h.
PermutationType
template<typename _FunctorType> typedef PermutationMatrix<Dynamic,Dynamic> Eigen::LevenbergMarquardt< _FunctorType >::PermutationType
Definition at line 120 of file LevenbergMarquardt.h.
QRSolver
template<typename _FunctorType> typedef FunctorType::QRSolver Eigen::LevenbergMarquardt< _FunctorType >::QRSolver
Definition at line 114 of file LevenbergMarquardt.h.
RealScalar
template<typename _FunctorType> typedef JacobianType::RealScalar Eigen::LevenbergMarquardt< _FunctorType >::RealScalar
Definition at line 117 of file LevenbergMarquardt.h.
Scalar
template<typename _FunctorType> typedef JacobianType::Scalar Eigen::LevenbergMarquardt< _FunctorType >::Scalar
Definition at line 116 of file LevenbergMarquardt.h.
Constructor & Destructor Documentation
LevenbergMarquardt() [1/2]
template<typename _FunctorType> Eigen::LevenbergMarquardt< _FunctorType >::LevenbergMarquardt (FunctorType & functor) inline
Definition at line 122 of file LevenbergMarquardt.h.
References sqrt(), and x.
LevenbergMarquardt() [2/2]
template<typename _FunctorType> Eigen::LevenbergMarquardt< _FunctorType >::LevenbergMarquardt (FunctorType & _functor) inline
Definition at line 55 of file LevenbergMarquardt.h.
Member Function Documentation
diag()
template<typename _FunctorType> FVectorType& Eigen::LevenbergMarquardt< _FunctorType >::diag () inline
Returns
a reference to the diagonal of the jacobian
Definition at line 197 of file LevenbergMarquardt.h.
epsilon()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::epsilon () const inline
Returns
the error precision
Definition at line 191 of file LevenbergMarquardt.h.
factor()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::factor () const inline
Returns
the step bound for the diagonal shift
Definition at line 188 of file LevenbergMarquardt.h.
fnorm()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::fnorm () inline
Returns
the norm of current vector function
Definition at line 209 of file LevenbergMarquardt.h.
ftol()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::ftol () const inline
Returns
the tolerance for the norm of the vector function
Definition at line 182 of file LevenbergMarquardt.h.
fvec()
template<typename _FunctorType> FVectorType& Eigen::LevenbergMarquardt< _FunctorType >::fvec () inline
Returns
a reference to the current vector function
Definition at line 219 of file LevenbergMarquardt.h.
gnorm()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::gnorm () inline
Returns
the norm of the gradient of the error
Definition at line 212 of file LevenbergMarquardt.h.
gtol()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::gtol () const inline
Returns
the tolerance for the norm of the gradient of the error vector
Definition at line 185 of file LevenbergMarquardt.h.
info()
template<typename _FunctorType> ComputationInfo Eigen::LevenbergMarquardt< _FunctorType >::info () const inline
Reports whether the minimization was successful.
Returns
Success if the minimization was succesful, NumericalIssue if a numerical problem arises during the minimization process, for exemple during the QR factorization NoConvergence if the minimization did not converge after the maximum number of function evaluation allowed InvalidInput if the input matrix is invalid
Definition at line 243 of file LevenbergMarquardt.h.
References m, and n.
iterations()
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::iterations () inline
Returns
the number of iterations performed
Definition at line 200 of file LevenbergMarquardt.h.
jacobian()
template<typename _FunctorType> JacobianType& Eigen::LevenbergMarquardt< _FunctorType >::jacobian () inline
Returns
a reference to the matrix where the current Jacobian matrix is stored
Definition at line 223 of file LevenbergMarquardt.h.
lm_param() [1/2]
template<typename _FunctorType> Scalar Eigen::LevenbergMarquardt< _FunctorType >::lm_param (void) inline
Definition at line 116 of file LevenbergMarquardt.h.
References abs(), abs2(), Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::LevenbergMarquardtSpace::CosinusTooSmall, e(), eigen_assert, Eigen::LevenbergMarquardtSpace::FtolTooSmall, Eigen::LevenbergMarquardtSpace::GtolTooSmall, Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), Eigen::LevenbergMarquardtSpace::ImproperInputParameters, j, Eigen::LevenbergMarquardt< _FunctorType >::lmder1(), m, Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), max, min, Eigen::LevenbergMarquardt< _FunctorType >::minimize(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeInit(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep(), n, Eigen::LevenbergMarquardtSpace::NotStarted, ratio, Eigen::LevenbergMarquardtSpace::RelativeErrorAndReductionTooSmall, Eigen::LevenbergMarquardtSpace::RelativeErrorTooSmall, Eigen::LevenbergMarquardtSpace::RelativeReductionTooSmall, Eigen::LevenbergMarquardtSpace::Running, sqrt(), mpfr::sum(), Eigen::LevenbergMarquardtSpace::TooManyFunctionEvaluation, Eigen::LevenbergMarquardtSpace::UserAsked, and Eigen::LevenbergMarquardtSpace::XtolTooSmall.
lm_param() [2/2]
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::lm_param (void) inline
Returns
the LevenbergMarquardt parameter
Definition at line 215 of file LevenbergMarquardt.h.
lmder1() [1/2]
template<typename _FunctorType> LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< _FunctorType >::lmder1 (FVectorType & x, const Scalar tol = sqrt_epsilon())
lmder1() [2/2]
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::lmder1 (FVectorType & x, const Scalar tol = std::sqrt(NumTraits<Scalar>::epsilon()))
Definition at line 344 of file LevenbergMarquardt.h.
References Eigen::LevenbergMarquardtSpace::ImproperInputParameters, m, and n.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), test_lmder(), and testLmder1().
lmdif1() [1/2]
template<typename _FunctorType> static LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< _FunctorType >::lmdif1 (FunctorType & functor, FVectorType & x, Index * nfev, const Scalar tol = sqrt_epsilon()) static
lmdif1() [2/2]
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::lmdif1 (FunctorType & functor, FVectorType & x, Index * nfev, const Scalar tol = std::sqrt(NumTraits<Scalar>::epsilon())) static
Definition at line 367 of file LevenbergMarquardt.h.
References Eigen::LevenbergMarquardtSpace::ImproperInputParameters, info, m, Eigen::LevenbergMarquardt< _FunctorType >::minimize(), n, Eigen::LevenbergMarquardt< _FunctorType >::nfev, Eigen::LevenbergMarquardt< _FunctorType >::setFtol(), Eigen::LevenbergMarquardt< _FunctorType >::setMaxfev(), and Eigen::LevenbergMarquardt< _FunctorType >::setXtol().
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorage().
lmstr1()
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::lmstr1 (FVectorType & x, const Scalar tol = sqrt_epsilon())
Definition at line 363 of file LevenbergMarquardt.h.
References Eigen::LevenbergMarquardtSpace::ImproperInputParameters, m, and n.
Referenced by testLmstr1().
matrixR()
template<typename _FunctorType> JacobianType& Eigen::LevenbergMarquardt< _FunctorType >::matrixR () inline
Returns
a reference to the triangular matrix R from the QR of the jacobian matrix.
See also
jacobian()
Definition at line 228 of file LevenbergMarquardt.h.
Referenced by testLmder(), and testLmdif().
maxfev()
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::maxfev () const inline
Returns
the maximum number of function evaluation
Definition at line 194 of file LevenbergMarquardt.h.
minimize() [1/2]
template<typename _FunctorType> LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< _FunctorType >::minimize (FVectorType & x)
minimize() [2/2]
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::minimize (FVectorType & x)
Definition at line 277 of file LevenbergMarquardt.h.
References Eigen::LevenbergMarquardtSpace::ImproperInputParameters, and Eigen::LevenbergMarquardtSpace::Running.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Eigen::LevenbergMarquardt< _FunctorType >::lmdif1(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorage(), test_minimizeLM(), testLmder(), testLmdif(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), and testNistThurber().
minimizeInit() [1/2]
template<typename _FunctorType> LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< _FunctorType >::minimizeInit (FVectorType & x)
minimizeInit() [2/2]
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::minimizeInit (FVectorType & x)
Definition at line 294 of file LevenbergMarquardt.h.
References eigen_assert, Eigen::LevenbergMarquardtSpace::ImproperInputParameters, Eigen::InvalidInput, j, m, n, Eigen::LevenbergMarquardtSpace::NotStarted, and Eigen::LevenbergMarquardtSpace::UserAsked.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), test_minimizeSteps(), and test_sparseLM_T().
minimizeOneStep() [1/2]
template<typename _FunctorType> LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep (FVectorType & x)
minimizeOneStep() [2/2]
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::minimizeOneStep (FVectorType & x)
Definition at line 21 of file LMonestep.h.
References abs(), abs2(), Eigen::LevenbergMarquardtSpace::CosinusTooSmall, e(), eigen_assert, Eigen::LevenbergMarquardtSpace::FtolTooSmall, Eigen::LevenbergMarquardtSpace::GtolTooSmall, Eigen::LevenbergMarquardtSpace::ImproperInputParameters, j, Eigen::internal::lmpar2(), max, min, n, Eigen::NoConvergence, Eigen::NumericalIssue, ratio, Eigen::LevenbergMarquardtSpace::RelativeErrorAndReductionTooSmall, Eigen::LevenbergMarquardtSpace::RelativeErrorTooSmall, Eigen::LevenbergMarquardtSpace::RelativeReductionTooSmall, Eigen::LevenbergMarquardtSpace::Running, sqrt(), Eigen::Success, Eigen::LevenbergMarquardtSpace::TooManyFunctionEvaluation, Eigen::LevenbergMarquardtSpace::UserAsked, and Eigen::LevenbergMarquardtSpace::XtolTooSmall.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), and test_minimizeSteps().
minimizeOptimumStorage()
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::minimizeOptimumStorage (FVectorType & x)
Definition at line 613 of file LevenbergMarquardt.h.
References Eigen::LevenbergMarquardtSpace::ImproperInputParameters, info, Eigen::LevenbergMarquardt< _FunctorType >::lmdif1(), m, Eigen::LevenbergMarquardt< _FunctorType >::minimize(), n, Eigen::LevenbergMarquardt< _FunctorType >::nfev, Eigen::LevenbergMarquardt< _FunctorType >::parameters, and Eigen::LevenbergMarquardtSpace::Running.
Referenced by testLmstr().
minimizeOptimumStorageInit()
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::minimizeOptimumStorageInit (FVectorType & x)
Definition at line 385 of file LevenbergMarquardt.h.
References eigen_assert, Eigen::LevenbergMarquardtSpace::ImproperInputParameters, j, m, n, Eigen::LevenbergMarquardtSpace::NotStarted, and Eigen::LevenbergMarquardtSpace::UserAsked.
minimizeOptimumStorageOneStep()
template<typename FunctorType , typename Scalar > LevenbergMarquardtSpace::Status Eigen::LevenbergMarquardt< FunctorType, Scalar >::minimizeOptimumStorageOneStep (FVectorType & x)
Definition at line 434 of file LevenbergMarquardt.h.
References abs(), abs2(), Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::LevenbergMarquardtSpace::CosinusTooSmall, e(), eigen_assert, Eigen::LevenbergMarquardtSpace::FtolTooSmall, Eigen::LevenbergMarquardtSpace::GtolTooSmall, Eigen::ColPivHouseholderQR< _MatrixType >::hCoeffs(), i, j, m, Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), max, min, n, ratio, Eigen::LevenbergMarquardtSpace::RelativeErrorAndReductionTooSmall, Eigen::LevenbergMarquardtSpace::RelativeErrorTooSmall, Eigen::LevenbergMarquardtSpace::RelativeReductionTooSmall, Eigen::LevenbergMarquardtSpace::Running, sqrt(), mpfr::sum(), Eigen::LevenbergMarquardtSpace::TooManyFunctionEvaluation, Eigen::LevenbergMarquardtSpace::UserAsked, and Eigen::LevenbergMarquardtSpace::XtolTooSmall.
nfev()
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::nfev () inline
Returns
the number of functions evaluation
Definition at line 203 of file LevenbergMarquardt.h.
njev()
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::njev () inline
Returns
the number of jacobian evaluation
Definition at line 206 of file LevenbergMarquardt.h.
permutation()
template<typename _FunctorType> PermutationType Eigen::LevenbergMarquardt< _FunctorType >::permutation () inline
the permutation used in the QR factorization
Definition at line 232 of file LevenbergMarquardt.h.
resetParameters() [1/2]
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::resetParameters (void) inline
Definition at line 104 of file LevenbergMarquardt.h.
resetParameters() [2/2]
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::resetParameters () inline
Sets the default parameters
Definition at line 145 of file LevenbergMarquardt.h.
References sqrt().
Referenced by testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistMGH09(), testNistMGH17(), testNistRat43(), and testNistThurber().
setEpsilon()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setEpsilon (RealScalar epsfcn) inline
Sets the error precision
Definition at line 170 of file LevenbergMarquardt.h.
setExternalScaling()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setExternalScaling (bool value) inline
Use an external Scaling. If set to true, pass a nonzero diagonal to diag()
Definition at line 176 of file LevenbergMarquardt.h.
setFactor()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setFactor (RealScalar factor) inline
Sets the step bound for the diagonal shift
Definition at line 167 of file LevenbergMarquardt.h.
Referenced by testNistBoxBOD().
setFtol()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setFtol (RealScalar ftol) inline
Sets the tolerance for the norm of the vector function
Definition at line 161 of file LevenbergMarquardt.h.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lmdif1(), testNistBoxBOD(), testNistChwirut2(), testNistMGH17(), testNistRat43(), and testNistThurber().
setGtol()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setGtol (RealScalar gtol) inline
Sets the tolerance for the norm of the gradient of the error vector
Definition at line 164 of file LevenbergMarquardt.h.
setMaxfev()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setMaxfev (Index maxfev) inline
Sets the maximum number of function evaluation
Definition at line 173 of file LevenbergMarquardt.h.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lmdif1(), testNistBennett5(), testNistMGH09(), and testNistMGH17().
setXtol()
template<typename _FunctorType> void Eigen::LevenbergMarquardt< _FunctorType >::setXtol (RealScalar xtol) inline
Sets the tolerance for the norm of the solution vector
Definition at line 158 of file LevenbergMarquardt.h.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lmdif1(), testNistBoxBOD(), testNistChwirut2(), testNistMGH17(), testNistRat43(), and testNistThurber().
xtol()
template<typename _FunctorType> RealScalar Eigen::LevenbergMarquardt< _FunctorType >::xtol () const inline
Returns
the tolerance for the norm of the solution vector
Definition at line 179 of file LevenbergMarquardt.h.
Field Documentation
diag
template<typename _FunctorType> FVectorType Eigen::LevenbergMarquardt< _FunctorType >::diag
Definition at line 107 of file LevenbergMarquardt.h.
fjac
template<typename _FunctorType> JacobianType Eigen::LevenbergMarquardt< _FunctorType >::fjac
Definition at line 108 of file LevenbergMarquardt.h.
Referenced by testLmder(), and testLmdif().
fnorm
template<typename _FunctorType> Scalar Eigen::LevenbergMarquardt< _FunctorType >::fnorm
Definition at line 113 of file LevenbergMarquardt.h.
fvec
template<typename _FunctorType> FVectorType Eigen::LevenbergMarquardt< _FunctorType >::fvec
Definition at line 107 of file LevenbergMarquardt.h.
Referenced by testLmder(), testLmder1(), testLmdif(), testLmstr(), testLmstr1(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), and testNistThurber().
gnorm
template<typename _FunctorType> Scalar Eigen::LevenbergMarquardt< _FunctorType >::gnorm
Definition at line 113 of file LevenbergMarquardt.h.
iter
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::iter
Definition at line 112 of file LevenbergMarquardt.h.
nfev
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::nfev
Definition at line 110 of file LevenbergMarquardt.h.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lmdif1(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorage(), testLmder(), testLmder1(), testLmdif(), testLmstr(), testLmstr1(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), and testNistThurber().
njev
template<typename _FunctorType> Index Eigen::LevenbergMarquardt< _FunctorType >::njev
Definition at line 111 of file LevenbergMarquardt.h.
Referenced by testLmder(), testLmder1(), testLmstr(), testLmstr1(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), and testNistThurber().
parameters
template<typename _FunctorType> Parameters Eigen::LevenbergMarquardt< _FunctorType >::parameters
Definition at line 106 of file LevenbergMarquardt.h.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorage(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistMGH09(), testNistMGH17(), testNistRat43(), and testNistThurber().
permutation
template<typename _FunctorType> PermutationMatrix<Dynamic,Dynamic> Eigen::LevenbergMarquardt< _FunctorType >::permutation
Definition at line 109 of file LevenbergMarquardt.h.
Referenced by testLmder(), and testLmdif().
qtf
template<typename _FunctorType> FVectorType Eigen::LevenbergMarquardt< _FunctorType >::qtf
Definition at line 107 of file LevenbergMarquardt.h.
useExternalScaling
template<typename _FunctorType> bool Eigen::LevenbergMarquardt< _FunctorType >::useExternalScaling
Definition at line 114 of file LevenbergMarquardt.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/LevenbergMarquardt/LevenbergMarquardt.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/LevenbergMarquardt/LMonestep.h