pairinteraction: Eigen::TensorSlicingOp< StartIndices, Sizes, XprType > Class Template Reference
Eigen::TensorSlicingOp< StartIndices, Sizes, XprType > Class Template Reference
#include <TensorForwardDeclarations.h>
Public Types
typedef Eigen::internal::traits< TensorSlicingOp >::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef Eigen::internal::nested< TensorSlicingOp >::type Nested
typedef Eigen::internal::traits< TensorSlicingOp >::StorageKind StorageKind
typedef Eigen::internal::traits< TensorSlicingOp >::Index Index
Public Types inherited from Eigen::TensorBase< TensorSlicingOp< StartIndices, Sizes, XprType > >
typedef internal::traits< TensorSlicingOp< StartIndices, Sizes, XprType > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp (const XprType &expr, const StartIndices &indices, const Sizes &sizes)
EIGEN_DEVICE_FUNC const StartIndices & startIndices () const
EIGEN_DEVICE_FUNC const Sizes & sizes () const
EIGEN_DEVICE_FUNC const internal::remove_all< typename XprType::Nested >::type & expression () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp & operator= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp & operator= (const TensorSlicingOp &other)
Public Member Functions inherited from Eigen::TensorBase< TensorSlicingOp< StartIndices, Sizes, XprType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorSlicingOp< StartIndices, Sizes, XprType > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorSlicingOp< StartIndices, Sizes, XprType > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorSlicingOp< StartIndices, Sizes, XprType >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorSlicingOp< StartIndices, Sizes, XprType >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorSlicingOp< StartIndices, Sizes, XprType > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorSlicingOp< StartIndices, Sizes, XprType > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorSlicingOp< StartIndices, Sizes, XprType > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorSlicingOp< StartIndices, Sizes, XprType > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorSlicingOp< StartIndices, Sizes, XprType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorSlicingOp< StartIndices, Sizes, XprType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorSlicingOp< StartIndices, Sizes, XprType > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorSlicingOp< StartIndices, Sizes, XprType > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorSlicingOp< StartIndices, Sizes, XprType > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorSlicingOp< StartIndices, Sizes, XprType > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorSlicingOp< StartIndices, Sizes, XprType > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorSlicingOp< StartIndices, Sizes, XprType > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorSlicingOp< StartIndices, Sizes, XprType > > shuffle (const Shuffle &shuffle) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorSlicingOp< StartIndices, Sizes, XprType > > shuffle (const Shuffle &shuffle)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorSlicingOp< StartIndices, Sizes, XprType > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorSlicingOp< StartIndices, Sizes, XprType > > stride (const Strides &strides)
TensorDevice< TensorSlicingOp< StartIndices, Sizes, XprType >, DeviceType > device (const DeviceType &device)
Protected Attributes
XprType::Nested m_xpr
const StartIndices m_indices
const Sizes m_sizes
Additional Inherited Members
Static Public Attributes inherited from Eigen::TensorBase< TensorSlicingOp< StartIndices, Sizes, XprType > >
static const int NumDimensions
Protected Member Functions inherited from Eigen::TensorBase< TensorSlicingOp< StartIndices, Sizes, XprType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< StartIndices, Sizes, XprType > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< StartIndices, Sizes, XprType > & derived () const
Detailed Description
template<typename StartIndices, typename Sizes, typename XprType>
class Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >
Definition at line 51 of file TensorForwardDeclarations.h.
Member Typedef Documentation
CoeffReturnType
template<typename StartIndices, typename Sizes, typename XprType> typedef XprType::CoeffReturnType Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::CoeffReturnType
Definition at line 240 of file TensorMorphing.h.
Index
template<typename StartIndices, typename Sizes, typename XprType> typedef Eigen::internal::traits<TensorSlicingOp>::Index Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::Index
Definition at line 243 of file TensorMorphing.h.
Nested
template<typename StartIndices, typename Sizes, typename XprType> typedef Eigen::internal::nested<TensorSlicingOp>::type Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::Nested
Definition at line 241 of file TensorMorphing.h.
Scalar
template<typename StartIndices, typename Sizes, typename XprType> typedef Eigen::internal::traits<TensorSlicingOp>::Scalar Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::Scalar
Definition at line 239 of file TensorMorphing.h.
StorageKind
template<typename StartIndices, typename Sizes, typename XprType> typedef Eigen::internal::traits<TensorSlicingOp>::StorageKind Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::StorageKind
Definition at line 242 of file TensorMorphing.h.
Constructor & Destructor Documentation
TensorSlicingOp()
template<typename StartIndices, typename Sizes, typename XprType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::TensorSlicingOp (const XprType & expr, const StartIndices & indices, const Sizes & sizes) inline
Definition at line 245 of file TensorMorphing.h.
Member Function Documentation
expression()
template<typename StartIndices, typename Sizes, typename XprType> EIGEN_DEVICE_FUNC const internal::remove_all<typename XprType::Nested>::type& Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::expression () const inline
Definition at line 255 of file TensorMorphing.h.
operator=() [1/2]
template<typename StartIndices, typename Sizes, typename XprType> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp& Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::operator= (const OtherDerived & other) inline
Definition at line 259 of file TensorMorphing.h.
References Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run().
operator=() [2/2]
template<typename StartIndices, typename Sizes, typename XprType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp& Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::operator= (const TensorSlicingOp< StartIndices, Sizes, XprType > & other) inline
Definition at line 268 of file TensorMorphing.h.
References Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run().
sizes()
template<typename StartIndices, typename Sizes, typename XprType> EIGEN_DEVICE_FUNC const Sizes& Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::sizes () const inline
Definition at line 251 of file TensorMorphing.h.
Referenced by Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorEvaluator().
startIndices()
template<typename StartIndices, typename Sizes, typename XprType> EIGEN_DEVICE_FUNC const StartIndices& Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::startIndices () const inline
Definition at line 249 of file TensorMorphing.h.
Referenced by Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorEvaluator().
Field Documentation
m_indices
template<typename StartIndices, typename Sizes, typename XprType> const StartIndices Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::m_indices protected
Definition at line 279 of file TensorMorphing.h.
m_sizes
template<typename StartIndices, typename Sizes, typename XprType> const Sizes Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::m_sizes protected
Definition at line 280 of file TensorMorphing.h.
m_xpr
template<typename StartIndices, typename Sizes, typename XprType> XprType::Nested Eigen::TensorSlicingOp< StartIndices, Sizes, XprType >::m_xpr protected
Definition at line 278 of file TensorMorphing.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorForwardDeclarations.h
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h