pairinteraction: Action_syr2< Interface > Class Template Reference
Action_syr2< Interface > Class Template Reference
#include <action_syr2.hh>
Public Member Functions
BTL_DONT_INLINE Action_syr2 (int size)
Action_syr2 (const Action_syr2 &)
BTL_DONT_INLINE ~Action_syr2 (void)
double nb_op_base (void)
BTL_DONT_INLINE void initialize (void)
BTL_DONT_INLINE void calculate (void)
BTL_DONT_INLINE void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_syr2< Interface >
Definition at line 32 of file action_syr2.hh.
Constructor & Destructor Documentation
Action_syr2() [1/2]
template<class Interface > BTL_DONT_INLINE Action_syr2< Interface >::Action_syr2 (int size) inline
Definition at line 38 of file action_syr2.hh.
References X.
Action_syr2() [2/2]
template<class Interface > Action_syr2< Interface >::Action_syr2 (const Action_syr2< Interface > &) inline
Definition at line 57 of file action_syr2.hh.
References INFOS.
~Action_syr2()
template<class Interface > BTL_DONT_INLINE Action_syr2< Interface >::~Action_syr2 (void) inline
Definition at line 64 of file action_syr2.hh.
References X.
Member Function Documentation
calculate()
template<class Interface > BTL_DONT_INLINE void Action_syr2< Interface >::calculate (void) inline
Definition at line 90 of file action_syr2.hh.
References BTL_ASM_COMMENT, syr2(), and X.
check_result()
template<class Interface > BTL_DONT_INLINE void Action_syr2< Interface >::check_result (void) inline
Definition at line 96 of file action_syr2.hh.
References e(), INFOS, STL_interface< real >::norm_diff(), STL_interface< real >::syr2(), and X.
initialize()
template<class Interface > BTL_DONT_INLINE void Action_syr2< Interface >::initialize (void) inline
Definition at line 84 of file action_syr2.hh.
References X.
name()
template<class Interface > static std::string Action_syr2< Interface >::name (void) inline static
Definition at line 75 of file action_syr2.hh.
nb_op_base()
template<class Interface > double Action_syr2< Interface >::nb_op_base (void) inline
Definition at line 80 of file action_syr2.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_syr2.hh