pairinteraction: Action_axpby< Interface > Class Template Reference
Action_axpby< Interface > Class Template Reference
#include <action_axpby.hh>
Public Member Functions
Action_axpby (int size)
Action_axpby (const Action_axpby &)
~Action_axpby (void)
double nb_op_base (void)
void initialize (void)
void calculate (void)
void check_result (void)
Static Public Member Functions
static std::string name (void)
Detailed Description
template<class Interface>
class Action_axpby< Interface >
Definition at line 31 of file action_axpby.hh.
Constructor & Destructor Documentation
Action_axpby() [1/2]
template<class Interface > Action_axpby< Interface >::Action_axpby (int size) inline
Definition at line 36 of file action_axpby.hh.
References MESSAGE, and X.
Action_axpby() [2/2]
template<class Interface > Action_axpby< Interface >::Action_axpby (const Action_axpby< Interface > &) inline
Definition at line 54 of file action_axpby.hh.
References INFOS.
~Action_axpby()
template<class Interface > Action_axpby< Interface >::~Action_axpby (void) inline
Definition at line 61 of file action_axpby.hh.
References MESSAGE, and X.
Member Function Documentation
calculate()
template<class Interface > void Action_axpby< Interface >::calculate (void) inline
Definition at line 87 of file action_axpby.hh.
References BTL_ASM_COMMENT, and X.
check_result()
template<class Interface > void Action_axpby< Interface >::check_result (void) inline
Definition at line 93 of file action_axpby.hh.
References STL_interface< real >::axpby(), e(), INFOS, STL_interface< real >::norm_diff(), and X.
initialize()
template<class Interface > void Action_axpby< Interface >::initialize (void) inline
Definition at line 82 of file action_axpby.hh.
References X.
name()
template<class Interface > static std::string Action_axpby< Interface >::name (void) inline static
Definition at line 73 of file action_axpby.hh.
nb_op_base()
template<class Interface > double Action_axpby< Interface >::nb_op_base (void) inline
Definition at line 78 of file action_axpby.hh.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/actions/action_axpby.hh