pairinteraction: mpfr::mpreal Class Reference
mpfr::mpreal Class Reference
#include <mpreal.h>
Public Member Functions
mpreal ()
mpreal (const mpreal &u)
mpreal (const mpf_t u)
mpreal (const mpz_t u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const mpq_t u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const double u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const long double u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const unsigned long long int u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const long long int u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const unsigned long int u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const unsigned int u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const long int u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const int u, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const mpfr_t u, bool shared=false)
mpreal (const char *s, mp_prec_t prec=mpreal::get_default_prec(), int base=10, mp_rnd_t mode=mpreal::get_default_rnd())
mpreal (const std::string &s, mp_prec_t prec=mpreal::get_default_prec(), int base=10, mp_rnd_t mode=mpreal::get_default_rnd())
~mpreal ()
mpreal & operator= (const mpreal &v)
mpreal & operator= (const mpf_t v)
mpreal & operator= (const mpz_t v)
mpreal & operator= (const mpq_t v)
mpreal & operator= (const long double v)
mpreal & operator= (const double v)
mpreal & operator= (const unsigned long int v)
mpreal & operator= (const unsigned long long int v)
mpreal & operator= (const long long int v)
mpreal & operator= (const unsigned int v)
mpreal & operator= (const long int v)
mpreal & operator= (const int v)
mpreal & operator= (const char *s)
mpreal & operator= (const std::string &s)
template<typename real_t >
mpreal & operator= (const std::complex< real_t > &z)
mpreal & operator+= (const mpreal &v)
mpreal & operator+= (const mpf_t v)
mpreal & operator+= (const mpz_t v)
mpreal & operator+= (const mpq_t v)
mpreal & operator+= (const long double u)
mpreal & operator+= (const double u)
mpreal & operator+= (const unsigned long int u)
mpreal & operator+= (const unsigned int u)
mpreal & operator+= (const long int u)
mpreal & operator+= (const int u)
mpreal & operator+= (const long long int u)
mpreal & operator+= (const unsigned long long int u)
mpreal & operator-= (const long long int u)
mpreal & operator-= (const unsigned long long int u)
mpreal & operator*= (const long long int u)
mpreal & operator*= (const unsigned long long int u)
mpreal & operator/= (const long long int u)
mpreal & operator/= (const unsigned long long int u)
const mpreal operator+ () const
mpreal & operator++ ()
const mpreal operator++ (int)
mpreal & operator-= (const mpreal &v)
mpreal & operator-= (const mpz_t v)
mpreal & operator-= (const mpq_t v)
mpreal & operator-= (const long double u)
mpreal & operator-= (const double u)
mpreal & operator-= (const unsigned long int u)
mpreal & operator-= (const unsigned int u)
mpreal & operator-= (const long int u)
mpreal & operator-= (const int u)
const mpreal operator- () const
mpreal & operator-- ()
const mpreal operator-- (int)
mpreal & operator*= (const mpreal &v)
mpreal & operator*= (const mpz_t v)
mpreal & operator*= (const mpq_t v)
mpreal & operator*= (const long double v)
mpreal & operator*= (const double v)
mpreal & operator*= (const unsigned long int v)
mpreal & operator*= (const unsigned int v)
mpreal & operator*= (const long int v)
mpreal & operator*= (const int v)
mpreal & operator/= (const mpreal &v)
mpreal & operator/= (const mpz_t v)
mpreal & operator/= (const mpq_t v)
mpreal & operator/= (const long double v)
mpreal & operator/= (const double v)
mpreal & operator/= (const unsigned long int v)
mpreal & operator/= (const unsigned int v)
mpreal & operator/= (const long int v)
mpreal & operator/= (const int v)
mpreal & operator<<= (const unsigned long int u)
mpreal & operator<<= (const unsigned int u)
mpreal & operator<<= (const long int u)
mpreal & operator<<= (const int u)
mpreal & operator>>= (const unsigned long int u)
mpreal & operator>>= (const unsigned int u)
mpreal & operator>>= (const long int u)
mpreal & operator>>= (const int u)
bool toBool () const
long toLong (mp_rnd_t mode=GMP_RNDZ) const
unsigned long toULong (mp_rnd_t mode=GMP_RNDZ) const
long long toLLong (mp_rnd_t mode=GMP_RNDZ) const
unsigned long long toULLong (mp_rnd_t mode=GMP_RNDZ) const
float toFloat (mp_rnd_t mode=GMP_RNDN) const
double toDouble (mp_rnd_t mode=GMP_RNDN) const
long double toLDouble (mp_rnd_t mode=GMP_RNDN) const
::mpfr_ptr mpfr_ptr ()
::mpfr_srcptr mpfr_ptr () const
::mpfr_srcptr mpfr_srcptr () const
std::string toString (int n=-1, int b=10, mp_rnd_t mode=mpreal::get_default_rnd()) const
std::string toString (const std::string &format) const
std::ostream & output (std::ostream &os) const
mp_prec_t get_prec () const
void set_prec (mp_prec_t prec, mp_rnd_t rnd_mode=get_default_rnd())
mpreal & setPrecision (int Precision, mp_rnd_t RoundingMode=get_default_rnd())
int getPrecision () const
mpreal & setInf (int Sign=+1)
mpreal & setNan ()
mpreal & setZero (int Sign=+1)
mpreal & setSign (int Sign, mp_rnd_t RoundingMode=get_default_rnd())
mp_exp_t get_exp ()
int set_exp (mp_exp_t e)
int check_range (int t, mp_rnd_t rnd_mode=get_default_rnd())
int subnormalize (int t, mp_rnd_t rnd_mode=get_default_rnd())
bool fits_in_bits (double x, int n)
Static Public Member Functions
static mp_rnd_t get_default_rnd ()
static mp_prec_t get_default_prec ()
static void set_default_prec (mp_prec_t prec)
static void set_default_rnd (mp_rnd_t rnd_mode)
static mp_exp_t get_emin (void)
static mp_exp_t get_emax (void)
static mp_exp_t get_emin_min (void)
static mp_exp_t get_emin_max (void)
static mp_exp_t get_emax_min (void)
static mp_exp_t get_emax_max (void)
static int set_emin (mp_exp_t exp)
static int set_emax (mp_exp_t exp)
Friends
const mpreal operator- (const unsigned long int b, const mpreal &a)
const mpreal operator- (const unsigned int b, const mpreal &a)
const mpreal operator- (const long int b, const mpreal &a)
const mpreal operator- (const int b, const mpreal &a)
const mpreal operator- (const double b, const mpreal &a)
const mpreal operator/ (const unsigned long int b, const mpreal &a)
const mpreal operator/ (const unsigned int b, const mpreal &a)
const mpreal operator/ (const long int b, const mpreal &a)
const mpreal operator/ (const int b, const mpreal &a)
const mpreal operator/ (const double b, const mpreal &a)
const mpreal sqr (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sqrt (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sqrt (const unsigned long int v, mp_rnd_t rnd_mode)
const mpreal cbrt (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal root (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const mpz_t b, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const unsigned long int b, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const long int b, mp_rnd_t rnd_mode)
const mpreal pow (const unsigned long int a, const mpreal &b, mp_rnd_t rnd_mode)
const mpreal pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode)
const mpreal fabs (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal abs (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal dim (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode)
const mpreal mul_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode)
const mpreal mul_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode)
const mpreal div_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode)
const mpreal div_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode)
int cmpabs (const mpreal &a, const mpreal &b)
const mpreal log (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal log2 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal logb (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal log10 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal exp (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal exp2 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal exp10 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal log1p (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal expm1 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal cos (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sin (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal tan (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sec (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal csc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal cot (const mpreal &v, mp_rnd_t rnd_mode)
int sin_cos (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acos (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal asin (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal atan (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal atan2 (const mpreal &y, const mpreal &x, mp_rnd_t rnd_mode)
const mpreal acot (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal asec (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acsc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal cosh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sinh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal tanh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sech (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal csch (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal coth (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acosh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal asinh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal atanh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acoth (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal asech (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acsch (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal hypot (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal fac_ui (unsigned long int v, mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal eint (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal gamma (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal tgamma (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal lngamma (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal lgamma (const mpreal &v, int *signp, mp_rnd_t rnd_mode)
const mpreal zeta (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal erf (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal erfc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal besselj0 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal besselj1 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal besseljn (long n, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal bessely0 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal bessely1 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal besselyn (long n, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal fma (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode)
const mpreal fms (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode)
const mpreal agm (const mpreal &v1, const mpreal &v2, mp_rnd_t rnd_mode)
const mpreal sum (const mpreal tab[], const unsigned long int n, int &status, mp_rnd_t rnd_mode)
int sgn (const mpreal &v)
int sinh_cosh (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal li2 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal fmod (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal rec_sqrt (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rem (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal mod (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal digamma (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal ai (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal urandom (gmp_randstate_t &state, mp_rnd_t rnd_mode)
const mpreal grandom (gmp_randstate_t &state, mp_rnd_t rnd_mode)
const mpreal grandom (unsigned int seed)
const mpreal random (unsigned int seed)
const mpreal modf (const mpreal &v, mpreal &n)
const mpreal const_log2 (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_pi (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_euler (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_catalan (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_infinity (int sign, mp_prec_t prec)
std::ostream & operator<< (std::ostream &os, const mpreal &v)
std::istream & operator>> (std::istream &is, mpreal &v)
const mpreal rint (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal ceil (const mpreal &v)
const mpreal floor (const mpreal &v)
const mpreal round (const mpreal &v)
const mpreal trunc (const mpreal &v)
const mpreal rint_ceil (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rint_floor (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rint_round (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rint_trunc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal frac (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal remainder (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal remquo (long *q, const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal nexttoward (const mpreal &x, const mpreal &y)
const mpreal nextabove (const mpreal &x)
const mpreal nextbelow (const mpreal &x)
const mpreal urandomb (gmp_randstate_t &state)
const mpreal random2 (mp_size_t size, mp_exp_t exp)
bool() isnan (const mpreal &v)
bool() isinf (const mpreal &v)
bool() isfinite (const mpreal &v)
bool isnum (const mpreal &v)
bool iszero (const mpreal &v)
bool isint (const mpreal &v)
bool isregular (const mpreal &v)
void swap (mpreal &x, mpreal &y)
const mpreal fmax (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal fmin (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
Detailed Description
Definition at line 142 of file mpreal.h.
Constructor & Destructor Documentation
mpreal() [1/16]
mpfr::mpreal::mpreal () inline
Definition at line 564 of file mpreal.h.
References get_default_prec(), mpfr_ptr(), mpfr_set_zero_fast, and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec(), mpfr::machine_epsilon(), mpfr::maxval(), mpfr::minval(), mpreal(), mpfr::operator*(), operator*=(), operator+(), mpfr::operator+(), operator+=(), mpfr::operator-(), operator-=(), mpfr::operator/(), operator/=(), mpfr::pow(), and mpfr::sqrt().
mpreal() [2/16]
mpfr::mpreal::mpreal (const mpreal & u) inline
Definition at line 572 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), mpreal(), MPREAL_MSVC_DEBUGVIEW_CODE, and operator=().
mpreal() [3/16]
mpfr::mpreal::mpreal (const mpf_t u) inline
Definition at line 613 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [4/16]
mpfr::mpreal::mpreal (const mpz_t u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 621 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [5/16]
mpfr::mpreal::mpreal (const mpq_t u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 629 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [6/16]
mpfr::mpreal::mpreal (const double u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 637 of file mpreal.h.
References fits_in_bits(), mpfr_ptr(), MPREAL_DOUBLE_BITS_OVERFLOW, and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [7/16]
mpfr::mpreal::mpreal (const long double u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 654 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [8/16]
mpfr::mpreal::mpreal (const unsigned long long int u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 662 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [9/16]
mpfr::mpreal::mpreal (const long long int u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 670 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [10/16]
mpfr::mpreal::mpreal (const unsigned long int u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 678 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [11/16]
mpfr::mpreal::mpreal (const unsigned int u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 686 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [12/16]
mpfr::mpreal::mpreal (const long int u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 694 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [13/16]
mpfr::mpreal::mpreal (const int u, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 702 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [14/16]
mpfr::mpreal::mpreal (const mpfr_t u, bool shared = false) inline
Definition at line 598 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [15/16]
mpfr::mpreal::mpreal (const char * s, mp_prec_t prec = mpreal::get_default_prec(), int base = 10, mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 710 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
mpreal() [16/16]
mpfr::mpreal::mpreal (const std::string & s, mp_prec_t prec = mpreal::get_default_prec(), int base = 10, mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 718 of file mpreal.h.
References mpfr_ptr(), MPREAL_MSVC_DEBUGVIEW_CODE, and x.
~mpreal()
mpfr::mpreal::~mpreal () inline
Definition at line 734 of file mpreal.h.
References mpfr_ptr().
Referenced by get_default_prec().
Member Function Documentation
check_range()
int mpfr::mpreal::check_range (int t, mp_rnd_t rnd_mode = get_default_rnd()) inline
Definition at line 2104 of file mpreal.h.
References mpfr_ptr().
Referenced by get_default_prec().
fits_in_bits()
bool mpfr::mpreal::fits_in_bits (double x, int n) inline
Definition at line 2676 of file mpreal.h.
References mpfr::frexp(), i, IsInf, mpfr::ldexp(), and mpfr::modf().
Referenced by get_default_prec(), mpreal(), and operator=().
get_default_prec()
static mp_prec_t mpfr::mpreal::get_default_prec () inline static
Definition at line 150 of file mpreal.h.
References a, abs, acos, acosh, acot, acoth, acsc, acsch, agm, ai, asec, asech, asin, asinh, atan, atan2, atanh, b, besselj0, besselj1, besseljn, bessely0, bessely1, besselyn, c, cbrt, ceil, check_range(), cmpabs, const_catalan, const_euler, const_infinity, const_log2, const_pi, cos, cosh, cot, coth, csc, csch, digamma, dim, div_2si, div_2ui, e(), eint, erf, erfc, exp, exp10, exp2, expm1, fabs, fac_ui, fits_in_bits(), floor, fma, fmax, fmin, fmod, fms, frac, gamma, get_default_rnd(), get_emax(), get_emax_max(), get_emax_min(), get_emin(), get_emin_max(), get_emin_min(), get_exp(), get_prec(), getPrecision(), grandom, hypot, int(), isfinite, isinf, isint, isnan, isnum, isregular, iszero, lgamma, li2, lngamma, log, log10, log1p, log2, logb, mod, modf, mpfr_ptr(), mpfr_srcptr(), mpreal(), MPREAL_MSVC_DEBUGVIEW_DATA, mul_2si, mul_2ui, n, nextabove, nextbelow, nexttoward, operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/, operator/=(), operator<<, operator<<=(), operator=(), operator>>, operator>>=(), output(), pow, Eigen::numext::q, random, random2, rec_sqrt, rem, remainder, remquo, rint, rint_ceil, rint_floor, rint_round, rint_trunc, root, round, s, sec, sech, set_default_prec(), set_default_rnd(), set_emax(), set_emin(), set_exp(), set_prec(), setInf(), setNan(), setPrecision(), setSign(), setZero(), sgn, sign(), sin, sin_cos, sinh, sinh_cosh, size, sqr, sqrt, subnormalize(), sum, swap, tan, tanh, tgamma, toBool(), toDouble(), toFloat(), toLDouble(), toLLong(), toLong(), toString(), toULLong(), toULong(), trunc, urandom, urandomb, v, v1(), v2(), x, y, zeta, and ~mpreal().
Referenced by std::numeric_limits< mpfr::mpreal >::digits(), mpreal(), and mpfr::operator/().
get_default_rnd()
static mp_rnd_t mpfr::mpreal::get_default_rnd () inline static
Definition at line 149 of file mpreal.h.
Referenced by get_default_prec(), mpfr::ldexp(), mpreal(), mpfr::operator*(), operator*=(), mpfr::operator+(), operator+=(), operator-(), mpfr::operator-(), operator-=(), mpfr::operator/(), operator/=(), operator<<=(), operator=(), mpfr::operator>>(), operator>>=(), output(), std::numeric_limits< mpfr::mpreal >::round_error(), and std::numeric_limits< mpfr::mpreal >::round_style().
get_emax()
mp_exp_t mpfr::mpreal::get_emax (void) inline static
Definition at line 2126 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::maxval().
get_emax_max()
mp_exp_t mpfr::mpreal::get_emax_max (void) inline static
Definition at line 2151 of file mpreal.h.
Referenced by get_default_prec().
get_emax_min()
mp_exp_t mpfr::mpreal::get_emax_min (void) inline static
Definition at line 2146 of file mpreal.h.
Referenced by get_default_prec().
get_emin()
mp_exp_t mpfr::mpreal::get_emin (void) inline static
Definition at line 2116 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::minval().
get_emin_max()
mp_exp_t mpfr::mpreal::get_emin_max (void) inline static
Definition at line 2141 of file mpreal.h.
Referenced by get_default_prec().
get_emin_min()
mp_exp_t mpfr::mpreal::get_emin_min (void) inline static
Definition at line 2136 of file mpreal.h.
Referenced by get_default_prec().
get_exp()
mp_exp_t mpfr::mpreal::get_exp () inline
Definition at line 1996 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
get_prec()
mp_prec_t mpfr::mpreal::get_prec () const inline
Definition at line 1985 of file mpreal.h.
References mpfr_srcptr().
Referenced by mpfr::agm(), mpfr::fma(), mpfr::fmod(), mpfr::fms(), and get_default_prec().
getPrecision()
int mpfr::mpreal::getPrecision () const inline
Definition at line 1946 of file mpreal.h.
References int(), and mpfr_srcptr().
Referenced by mpfr::atan2(), mpfr::besseljn(), mpfr::besselyn(), std::numeric_limits< mpfr::mpreal >::digits(), std::numeric_limits< mpfr::mpreal >::digits10(), get_default_prec(), mpfr::hypot(), mpfr::remainder(), and mpfr::remquo().
mpfr_ptr() [1/2]
mpfr_ptr mpfr::mpreal::mpfr_ptr () inline
Definition at line 1721 of file mpreal.h.
Referenced by mpfr::atan2(), mpfr::besseljn(), mpfr::besselyn(), check_range(), mpfr::cmpabs(), mpfr::const_catalan(), mpfr::const_euler(), mpfr::const_infinity(), mpfr::const_log2(), mpfr::const_pi(), mpfr::copysign(), mpfr::dim(), mpfr::div_2si(), mpfr::div_2ui(), mpfr::fac_ui(), mpfr::frexp(), get_default_prec(), mpfr::grandom(), mpfr::hypot(), mpfr::ldexp(), mpfr::lgamma(), mpreal(), mpfr::mul_2si(), mpfr::mul_2ui(), mpfr::operator*(), operator*=(), mpfr::operator+(), operator+=(), operator-(), mpfr::operator-(), operator-=(), mpfr::operator/(), operator/=(), operator<<=(), operator=(), mpfr::operator>>(), operator>>=(), mpfr::random2(), mpfr::remainder(), mpfr::remquo(), mpfr::root(), set_exp(), set_prec(), setInf(), setNan(), setPrecision(), setSign(), setZero(), mpfr::sin_cos(), mpfr::sqrt(), subnormalize(), mpfr::sum(), mpfr::urandom(), mpfr::urandomb(), and ~mpreal().
mpfr_ptr() [2/2]
mpfr_srcptr mpfr::mpreal::mpfr_ptr () const inline
Definition at line 1722 of file mpreal.h.
mpfr_srcptr()
mpfr_srcptr mpfr::mpreal::mpfr_srcptr () const inline
Definition at line 1723 of file mpreal.h.
Referenced by mpfr::atan2(), mpfr::besseljn(), mpfr::besselyn(), mpfr::cmpabs(), mpfr::copysign(), mpfr::dim(), mpfr::div_2si(), mpfr::div_2ui(), mpfr::frexp(), get_default_prec(), get_exp(), get_prec(), getPrecision(), mpfr::hypot(), mpfr::isint(), mpfr::isregular(), mpfr::iszero(), mpfr::ldexp(), mpfr::lgamma(), mpreal(), mpfr::mul_2si(), mpfr::mul_2ui(), mpfr::operator*(), operator*=(), mpfr::operator+(), operator+=(), operator-(), mpfr::operator-(), operator-=(), mpfr::operator/(), operator/=(), mpfr::operator<(), operator<<=(), mpfr::operator<=(), operator=(), mpfr::operator==(), mpfr::operator>(), mpfr::operator>=(), operator>>=(), output(), mpfr::remainder(), mpfr::remquo(), mpfr::root(), setSign(), mpfr::sgn(), mpfr::signbit(), mpfr::sin_cos(), mpfr::sum(), toBool(), toDouble(), toFloat(), toLDouble(), toLLong(), toLong(), toString(), toULLong(), and toULong().
operator*=() [1/11]
mpreal & mpfr::mpreal::operator*= (const long long int u) inline
Definition at line 1155 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
operator*=() [2/11]
mpreal & mpfr::mpreal::operator*= (const unsigned long long int u) inline
Definition at line 1156 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [3/11]
mpreal & mpfr::mpreal::operator*= (const mpreal & v) inline
Definition at line 1320 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [4/11]
mpreal & mpfr::mpreal::operator*= (const mpz_t v) inline
Definition at line 1327 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [5/11]
mpreal & mpfr::mpreal::operator*= (const mpq_t v) inline
Definition at line 1334 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [6/11]
mpreal & mpfr::mpreal::operator*= (const long double v) inline
Definition at line 1341 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [7/11]
mpreal & mpfr::mpreal::operator*= (const double v) inline
Definition at line 1348 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [8/11]
mpreal & mpfr::mpreal::operator*= (const unsigned long int v) inline
Definition at line 1359 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [9/11]
mpreal & mpfr::mpreal::operator*= (const unsigned int v) inline
Definition at line 1366 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [10/11]
mpreal & mpfr::mpreal::operator*= (const long int v) inline
Definition at line 1373 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator*=() [11/11]
mpreal & mpfr::mpreal::operator*= (const int v) inline
Definition at line 1380 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+()
const mpreal mpfr::mpreal::operator+ () const inline
Definition at line 1160 of file mpreal.h.
References mpreal().
Referenced by get_default_prec().
operator++() [1/2]
mpreal & mpfr::mpreal::operator++ () inline
Definition at line 1169 of file mpreal.h.
Referenced by get_default_prec().
operator++() [2/2]
const mpreal mpfr::mpreal::operator++ (int) inline
Definition at line 1174 of file mpreal.h.
References x.
operator+=() [1/12]
mpreal & mpfr::mpreal::operator+= (const mpreal & v) inline
Definition at line 1076 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
operator+=() [2/12]
mpreal & mpfr::mpreal::operator+= (const mpf_t v) inline
Definition at line 1083 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [3/12]
mpreal & mpfr::mpreal::operator+= (const mpz_t v) inline
Definition at line 1090 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [4/12]
mpreal & mpfr::mpreal::operator+= (const mpq_t v) inline
Definition at line 1097 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [5/12]
mpreal & mpfr::mpreal::operator+= (const long double u) inline
Definition at line 1104 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [6/12]
mpreal & mpfr::mpreal::operator+= (const double u) inline
Definition at line 1111 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [7/12]
mpreal & mpfr::mpreal::operator+= (const unsigned long int u) inline
Definition at line 1123 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [8/12]
mpreal & mpfr::mpreal::operator+= (const unsigned int u) inline
Definition at line 1130 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [9/12]
mpreal & mpfr::mpreal::operator+= (const long int u) inline
Definition at line 1137 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [10/12]
mpreal & mpfr::mpreal::operator+= (const int u) inline
Definition at line 1144 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [11/12]
mpreal & mpfr::mpreal::operator+= (const long long int u) inline
Definition at line 1151 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator+=() [12/12]
mpreal & mpfr::mpreal::operator+= (const unsigned long long int u) inline
Definition at line 1152 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-()
const mpreal mpfr::mpreal::operator- () const inline
Definition at line 1263 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and mpfr_srcptr().
Referenced by get_default_prec().
operator--() [1/2]
mpreal & mpfr::mpreal::operator-- () inline
Definition at line 1181 of file mpreal.h.
Referenced by get_default_prec().
operator--() [2/2]
const mpreal mpfr::mpreal::operator-- (int) inline
Definition at line 1186 of file mpreal.h.
References x.
operator-=() [1/11]
mpreal & mpfr::mpreal::operator-= (const long long int u) inline
Definition at line 1153 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
operator-=() [2/11]
mpreal & mpfr::mpreal::operator-= (const unsigned long long int u) inline
Definition at line 1154 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [3/11]
mpreal & mpfr::mpreal::operator-= (const mpreal & v) inline
Definition at line 1195 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [4/11]
mpreal & mpfr::mpreal::operator-= (const mpz_t v) inline
Definition at line 1202 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [5/11]
mpreal & mpfr::mpreal::operator-= (const mpq_t v) inline
Definition at line 1209 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [6/11]
mpreal & mpfr::mpreal::operator-= (const long double u) inline
Definition at line 1216 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [7/11]
mpreal & mpfr::mpreal::operator-= (const double u) inline
Definition at line 1223 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [8/11]
mpreal & mpfr::mpreal::operator-= (const unsigned long int u) inline
Definition at line 1235 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [9/11]
mpreal & mpfr::mpreal::operator-= (const unsigned int u) inline
Definition at line 1242 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [10/11]
mpreal & mpfr::mpreal::operator-= (const long int u) inline
Definition at line 1249 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator-=() [11/11]
mpreal & mpfr::mpreal::operator-= (const int u) inline
Definition at line 1256 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [1/11]
mpreal & mpfr::mpreal::operator/= (const long long int u) inline
Definition at line 1157 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
operator/=() [2/11]
mpreal & mpfr::mpreal::operator/= (const unsigned long long int u) inline
Definition at line 1158 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [3/11]
mpreal & mpfr::mpreal::operator/= (const mpreal & v) inline
Definition at line 1396 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [4/11]
mpreal & mpfr::mpreal::operator/= (const mpz_t v) inline
Definition at line 1403 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [5/11]
mpreal & mpfr::mpreal::operator/= (const mpq_t v) inline
Definition at line 1410 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [6/11]
mpreal & mpfr::mpreal::operator/= (const long double v) inline
Definition at line 1417 of file mpreal.h.
References mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [7/11]
mpreal & mpfr::mpreal::operator/= (const double v) inline
Definition at line 1424 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), mpreal(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [8/11]
mpreal & mpfr::mpreal::operator/= (const unsigned long int v) inline
Definition at line 1435 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [9/11]
mpreal & mpfr::mpreal::operator/= (const unsigned int v) inline
Definition at line 1442 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [10/11]
mpreal & mpfr::mpreal::operator/= (const long int v) inline
Definition at line 1449 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator/=() [11/11]
mpreal & mpfr::mpreal::operator/= (const int v) inline
Definition at line 1456 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator<<=() [1/4]
mpreal & mpfr::mpreal::operator<<= (const unsigned long int u) inline
Definition at line 1513 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
operator<<=() [2/4]
mpreal & mpfr::mpreal::operator<<= (const unsigned int u) inline
Definition at line 1520 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator<<=() [3/4]
mpreal & mpfr::mpreal::operator<<= (const long int u) inline
Definition at line 1527 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator<<=() [4/4]
mpreal & mpfr::mpreal::operator<<= (const int u) inline
Definition at line 1534 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [1/15]
mpreal & mpfr::mpreal::operator= (const mpreal & v) inline
Definition at line 907 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec(), and mpreal().
operator=() [2/15]
mpreal & mpfr::mpreal::operator= (const mpf_t v) inline
Definition at line 926 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [3/15]
mpreal & mpfr::mpreal::operator= (const mpz_t v) inline
Definition at line 934 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [4/15]
mpreal & mpfr::mpreal::operator= (const mpq_t v) inline
Definition at line 942 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [5/15]
mpreal & mpfr::mpreal::operator= (const long double v) inline
Definition at line 950 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [6/15]
mpreal & mpfr::mpreal::operator= (const double v) inline
Definition at line 958 of file mpreal.h.
References fits_in_bits(), get_default_rnd(), mpfr_ptr(), MPREAL_DOUBLE_BITS_OVERFLOW, and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [7/15]
mpreal & mpfr::mpreal::operator= (const unsigned long int v) inline
Definition at line 974 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [8/15]
mpreal & mpfr::mpreal::operator= (const unsigned long long int v) inline
Definition at line 990 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [9/15]
mpreal & mpfr::mpreal::operator= (const long long int v) inline
Definition at line 998 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [10/15]
mpreal & mpfr::mpreal::operator= (const unsigned int v) inline
Definition at line 982 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [11/15]
mpreal & mpfr::mpreal::operator= (const long int v) inline
Definition at line 1006 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [12/15]
mpreal & mpfr::mpreal::operator= (const int v) inline
Definition at line 1014 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [13/15]
mpreal & mpfr::mpreal::operator= (const char * s) inline
Definition at line 1022 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [14/15]
mpreal & mpfr::mpreal::operator= (const std::string & s) inline
Definition at line 1045 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator=() [15/15]
template<typename real_t > mpreal & mpfr::mpreal::operator= (const std::complex< real_t > & z) inline
Definition at line 1069 of file mpreal.h.
operator>>=() [1/4]
mpreal & mpfr::mpreal::operator>>= (const unsigned long int u) inline
Definition at line 1541 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
operator>>=() [2/4]
mpreal & mpfr::mpreal::operator>>= (const unsigned int u) inline
Definition at line 1548 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator>>=() [3/4]
mpreal & mpfr::mpreal::operator>>= (const long int u) inline
Definition at line 1555 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
operator>>=() [4/4]
mpreal & mpfr::mpreal::operator>>= (const int u) inline
Definition at line 1562 of file mpreal.h.
References get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
output()
std::ostream & mpfr::mpreal::output (std::ostream & os) const inline
Definition at line 1873 of file mpreal.h.
References get_default_rnd(), mpfr_srcptr(), and s.
Referenced by get_default_prec(), and mpfr::operator<<().
set_default_prec()
void mpfr::mpreal::set_default_prec (mp_prec_t prec) inline static
Definition at line 2666 of file mpreal.h.
Referenced by get_default_prec(), and test_mpreal_support().
set_default_rnd()
void mpfr::mpreal::set_default_rnd (mp_rnd_t rnd_mode) inline static
Definition at line 2671 of file mpreal.h.
Referenced by get_default_prec().
set_emax()
int mpfr::mpreal::set_emax (mp_exp_t exp) inline static
Definition at line 2131 of file mpreal.h.
Referenced by get_default_prec().
set_emin()
int mpfr::mpreal::set_emin (mp_exp_t exp) inline static
Definition at line 2121 of file mpreal.h.
Referenced by get_default_prec().
set_exp()
int mpfr::mpreal::set_exp (mp_exp_t e) inline
Definition at line 2001 of file mpreal.h.
References mpfr_ptr(), MPREAL_MSVC_DEBUGVIEW_CODE, and x.
Referenced by get_default_prec().
set_prec()
void mpfr::mpreal::set_prec (mp_prec_t prec, mp_rnd_t rnd_mode = get_default_rnd()) inline
Definition at line 1990 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by mpfr::agm(), mpfr::fma(), mpfr::fmod(), mpfr::fms(), and get_default_prec().
setInf()
mpreal & mpfr::mpreal::setInf (int Sign = +1) inline
Definition at line 1958 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
setNan()
mpreal & mpfr::mpreal::setNan () inline
Definition at line 1965 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec(), std::numeric_limits< mpfr::mpreal >::quiet_NaN(), and std::numeric_limits< mpfr::mpreal >::signaling_NaN().
setPrecision()
mpreal & mpfr::mpreal::setPrecision (int Precision, mp_rnd_t RoundingMode = get_default_rnd()) inline
Definition at line 1951 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
setSign()
mpreal & mpfr::mpreal::setSign (int Sign, mp_rnd_t RoundingMode = get_default_rnd()) inline
Definition at line 1939 of file mpreal.h.
References mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec(), mpfr::mod(), and setZero().
setZero()
mpreal & mpfr::mpreal::setZero (int Sign = +1) inline
Definition at line 1972 of file mpreal.h.
References mpfr_ptr(), MPREAL_MSVC_DEBUGVIEW_CODE, and setSign().
Referenced by get_default_prec().
subnormalize()
int mpfr::mpreal::subnormalize (int t, mp_rnd_t rnd_mode = get_default_rnd()) inline
Definition at line 2109 of file mpreal.h.
References mpfr_ptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by get_default_prec().
toBool()
bool mpfr::mpreal::toBool () const inline
Definition at line 1712 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toDouble()
double mpfr::mpreal::toDouble (mp_rnd_t mode = GMP_RNDN) const inline
Definition at line 1716 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toFloat()
float mpfr::mpreal::toFloat (mp_rnd_t mode = GMP_RNDN) const inline
Definition at line 1715 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toLDouble()
long double mpfr::mpreal::toLDouble (mp_rnd_t mode = GMP_RNDN) const inline
Definition at line 1717 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toLLong()
long long mpfr::mpreal::toLLong (mp_rnd_t mode = GMP_RNDZ) const inline
Definition at line 1718 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toLong()
long mpfr::mpreal::toLong (mp_rnd_t mode = GMP_RNDZ) const inline
Definition at line 1713 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toString() [1/2]
std::string mpfr::mpreal::toString (int n = -1, int b = 10, mp_rnd_t mode = mpreal::get_default_rnd()) const inline
Definition at line 1755 of file mpreal.h.
References mpfr::bits2digits(), exp, mpfr::max(), mpfr_srcptr(), ptr, and s.
Referenced by get_default_prec().
toString() [2/2]
std::string mpfr::mpreal::toString (const std::string & format) const inline
Definition at line 1735 of file mpreal.h.
References mpfr_srcptr(), and s.
toULLong()
unsigned long long mpfr::mpreal::toULLong (mp_rnd_t mode = GMP_RNDZ) const inline
Definition at line 1719 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
toULong()
unsigned long mpfr::mpreal::toULong (mp_rnd_t mode = GMP_RNDZ) const inline
Definition at line 1714 of file mpreal.h.
References mpfr_srcptr().
Referenced by get_default_prec().
Friends And Related Function Documentation
abs
const mpreal abs (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2223 of file mpreal.h.
Referenced by get_default_prec(), mpfr::isEqualFuzzy(), mpfr::isEqualUlps(), mpfr::logb(), and mpfr::operator/().
acos
const mpreal acos (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2236 of file mpreal.h.
Referenced by mpfr::acos(), mpfr::asec(), and get_default_prec().
acosh
const mpreal acosh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2255 of file mpreal.h.
Referenced by mpfr::acosh(), mpfr::asech(), and get_default_prec().
acot
const mpreal acot (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2242 of file mpreal.h.
Referenced by get_default_prec().
acoth
const mpreal acoth (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2245 of file mpreal.h.
Referenced by get_default_prec().
acsc
const mpreal acsc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2244 of file mpreal.h.
Referenced by get_default_prec().
acsch
const mpreal acsch (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2247 of file mpreal.h.
Referenced by get_default_prec().
agm
const mpreal agm (const mpreal & v1, const mpreal & v2, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2366 of file mpreal.h.
Referenced by get_default_prec().
ai
const mpreal ai (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2467 of file mpreal.h.
Referenced by mpfr::ai(), and get_default_prec().
asec
const mpreal asec (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2243 of file mpreal.h.
Referenced by get_default_prec().
asech
const mpreal asech (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2246 of file mpreal.h.
Referenced by get_default_prec().
asin
const mpreal asin (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2237 of file mpreal.h.
Referenced by mpfr::acsc(), mpfr::asin(), and get_default_prec().
asinh
const mpreal asinh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2256 of file mpreal.h.
Referenced by mpfr::acsch(), mpfr::asinh(), and get_default_prec().
atan
const mpreal atan (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2238 of file mpreal.h.
Referenced by mpfr::acot(), mpfr::atan(), and get_default_prec().
atan2
const mpreal atan2 (const mpreal & y, const mpreal & x, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2273 of file mpreal.h.
Referenced by get_default_prec().
atanh
const mpreal atanh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2257 of file mpreal.h.
Referenced by mpfr::acoth(), mpfr::atanh(), and get_default_prec().
besselj0
const mpreal besselj0 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2268 of file mpreal.h.
Referenced by get_default_prec().
besselj1
const mpreal besselj1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2269 of file mpreal.h.
Referenced by get_default_prec().
besseljn
const mpreal besseljn (long n, const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2322 of file mpreal.h.
Referenced by get_default_prec().
bessely0
const mpreal bessely0 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2270 of file mpreal.h.
Referenced by get_default_prec().
bessely1
const mpreal bessely1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2271 of file mpreal.h.
Referenced by get_default_prec().
besselyn
const mpreal besselyn (long n, const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2329 of file mpreal.h.
Referenced by get_default_prec().
cbrt
const mpreal cbrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2221 of file mpreal.h.
Referenced by mpfr::cbrt(), and get_default_prec().
ceil
const mpreal ceil (const mpreal & v) friend
Definition at line 2509 of file mpreal.h.
Referenced by get_default_prec().
cmpabs
int cmpabs (const mpreal & a, const mpreal & b) friend
Definition at line 2208 of file mpreal.h.
Referenced by get_default_prec().
const_catalan
const mpreal const_catalan (mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2493 of file mpreal.h.
Referenced by get_default_prec().
const_euler
const mpreal const_euler (mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2486 of file mpreal.h.
Referenced by get_default_prec().
const_infinity
const mpreal const_infinity (int sign = 1, mp_prec_t prec = mpreal::get_default_prec()) friend
Definition at line 2500 of file mpreal.h.
Referenced by get_default_prec().
const_log2
const mpreal const_log2 (mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2472 of file mpreal.h.
Referenced by get_default_prec().
const_pi
const mpreal const_pi (mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2479 of file mpreal.h.
Referenced by get_default_prec().
cos
const mpreal cos (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2230 of file mpreal.h.
Referenced by mpfr::cos(), and get_default_prec().
cosh
const mpreal cosh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2249 of file mpreal.h.
Referenced by mpfr::cosh(), and get_default_prec().
cot
const mpreal cot (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2235 of file mpreal.h.
Referenced by mpfr::cot(), and get_default_prec().
coth
const mpreal coth (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2254 of file mpreal.h.
Referenced by mpfr::coth(), and get_default_prec().
csc
const mpreal csc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2234 of file mpreal.h.
Referenced by mpfr::csc(), and get_default_prec().
csch
const mpreal csch (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2253 of file mpreal.h.
Referenced by mpfr::csch(), and get_default_prec().
digamma
const mpreal digamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2466 of file mpreal.h.
Referenced by mpfr::digamma(), and get_default_prec().
dim
const mpreal dim (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2201 of file mpreal.h.
Referenced by alignedbox(), alignedboxCastTests(), get_default_prec(), hyperplane(), and parametrizedline().
div_2si
const mpreal div_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 1632 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator/(), and mpfr::operator>>().
div_2ui
const mpreal div_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 1625 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator/(), and mpfr::operator>>().
eint
const mpreal eint (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2261 of file mpreal.h.
Referenced by mpfr::eint(), and get_default_prec().
erf
const mpreal erf (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2266 of file mpreal.h.
Referenced by mpfr::erf(), and get_default_prec().
erfc
const mpreal erfc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2267 of file mpreal.h.
Referenced by mpfr::erfc(), and get_default_prec().
exp
const mpreal exp (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2227 of file mpreal.h.
Referenced by get_default_prec(), mpfr::ldexp(), mpfr::random2(), and toString().
exp10
const mpreal exp10 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2229 of file mpreal.h.
Referenced by mpfr::exp10(), and get_default_prec().
exp2
const mpreal exp2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2228 of file mpreal.h.
Referenced by mpfr::exp2(), and get_default_prec().
expm1
const mpreal expm1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2260 of file mpreal.h.
Referenced by mpfr::expm1(), and get_default_prec().
fabs
const mpreal fabs (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2222 of file mpreal.h.
Referenced by get_default_prec().
fac_ui
const mpreal fac_ui (unsigned long int v, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2301 of file mpreal.h.
Referenced by get_default_prec().
floor
const mpreal floor (const mpreal & v) friend
Definition at line 2516 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::mod().
fma
const mpreal fma (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2336 of file mpreal.h.
Referenced by get_default_prec().
fmax
const mpreal fmax (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2550 of file mpreal.h.
Referenced by get_default_prec().
fmin
const mpreal fmin (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2557 of file mpreal.h.
Referenced by get_default_prec().
fmod
const mpreal fmod (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2440 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::rem().
fms
const mpreal fms (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2351 of file mpreal.h.
Referenced by get_default_prec().
frac
const mpreal frac (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2542 of file mpreal.h.
Referenced by mpfr::frac(), and get_default_prec().
gamma
const mpreal gamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2262 of file mpreal.h.
Referenced by mpfr::gamma(), get_default_prec(), and mpfr::tgamma().
grandom [1/2]
const mpreal grandom (gmp_randstate_t & state, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2639 of file mpreal.h.
Referenced by get_default_prec().
grandom [2/2]
const mpreal grandom (unsigned int seed = 0) friend
Definition at line 2646 of file mpreal.h.
hypot
const mpreal hypot (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2280 of file mpreal.h.
Referenced by get_default_prec().
isfinite
bool() isfinite (const mpreal & v) friend
Definition at line 1702 of file mpreal.h.
Referenced by get_default_prec().
isinf
bool() isinf (const mpreal & v) friend
Definition at line 1701 of file mpreal.h.
Referenced by get_default_prec().
isint
bool isint (const mpreal & v) friend
Definition at line 1704 of file mpreal.h.
Referenced by get_default_prec().
isnan
bool() isnan (const mpreal & v) friend
Definition at line 1700 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator<(), mpfr::operator<=(), mpfr::operator==(), mpfr::operator>(), and mpfr::operator>=().
isnum
bool isnum (const mpreal & v) friend
Referenced by get_default_prec().
isregular
bool isregular (const mpreal & v) friend
Definition at line 1707 of file mpreal.h.
Referenced by get_default_prec().
iszero
bool iszero (const mpreal & v) friend
Definition at line 1703 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::mod().
lgamma
const mpreal lgamma (const mpreal & v, int * signp = 0, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2310 of file mpreal.h.
Referenced by get_default_prec().
li2
const mpreal li2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2404 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::li2().
lngamma
const mpreal lngamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2264 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::lngamma().
log
const mpreal log (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2224 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::log().
log10
const mpreal log10 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2226 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::log10().
log1p
const mpreal log1p (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2259 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::log1p().
log2
const mpreal log2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2225 of file mpreal.h.
Referenced by get_default_prec(), mpfr::log2(), and mpfr::logb().
logb
const mpreal logb (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2240 of file mpreal.h.
Referenced by get_default_prec().
mod
const mpreal mod (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2415 of file mpreal.h.
Referenced by get_default_prec().
modf
const mpreal modf (const mpreal & v, mpreal & n) friend
Definition at line 2094 of file mpreal.h.
Referenced by get_default_prec().
mul_2si
const mpreal mul_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 1618 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator/(), and mpfr::operator<<().
mul_2ui
const mpreal mul_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 1610 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator/(), and mpfr::operator<<().
nextabove
const mpreal nextabove (const mpreal & x) friend
Definition at line 2571 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::machine_epsilon().
nextbelow
const mpreal nextbelow (const mpreal & x) friend
Definition at line 2578 of file mpreal.h.
Referenced by get_default_prec().
nexttoward
const mpreal nexttoward (const mpreal & x, const mpreal & y) friend
Definition at line 2564 of file mpreal.h.
Referenced by get_default_prec().
operator- [1/5]
const mpreal operator- (const unsigned long int b, const mpreal & a) friend
Definition at line 1290 of file mpreal.h.
operator- [2/5]
const mpreal operator- (const unsigned int b, const mpreal & a) friend
Definition at line 1297 of file mpreal.h.
operator- [3/5]
const mpreal operator- (const long int b, const mpreal & a) friend
Definition at line 1304 of file mpreal.h.
operator- [4/5]
const mpreal operator- (const int b, const mpreal & a) friend
Definition at line 1311 of file mpreal.h.
operator- [5/5]
const mpreal operator- (const double b, const mpreal & a) friend
Definition at line 1277 of file mpreal.h.
operator/ [1/5]
const mpreal operator/ (const unsigned long int b, const mpreal & a) friend
Definition at line 1470 of file mpreal.h.
Referenced by get_default_prec().
operator/ [2/5]
const mpreal operator/ (const unsigned int b, const mpreal & a) friend
Definition at line 1477 of file mpreal.h.
operator/ [3/5]
const mpreal operator/ (const long int b, const mpreal & a) friend
Definition at line 1484 of file mpreal.h.
operator/ [4/5]
const mpreal operator/ (const int b, const mpreal & a) friend
Definition at line 1491 of file mpreal.h.
operator/ [5/5]
const mpreal operator/ (const double b, const mpreal & a) friend
Definition at line 1498 of file mpreal.h.
operator<<
std::ostream& operator<< (std::ostream & os, const mpreal & v) friend
Definition at line 1899 of file mpreal.h.
Referenced by get_default_prec().
operator>>
std::istream& operator>> (std::istream & is, mpreal & v) friend
Definition at line 1904 of file mpreal.h.
Referenced by get_default_prec().
pow [1/6]
const mpreal pow (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2683 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator/(), and mpfr::pow().
pow [2/6]
const mpreal pow (const mpreal & a, const mpz_t b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2690 of file mpreal.h.
pow [3/6]
const mpreal pow (const mpreal & a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2697 of file mpreal.h.
pow [4/6]
const mpreal pow (const mpreal & a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2709 of file mpreal.h.
pow [5/6]
const mpreal pow (const unsigned long int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2731 of file mpreal.h.
pow [6/6]
const mpreal pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode) friend
Definition at line 2766 of file mpreal.h.
random
const mpreal random (unsigned int seed = 0) friend
Definition at line 2614 of file mpreal.h.
Referenced by get_default_prec().
random2
const mpreal random2 (mp_size_t size, mp_exp_t exp) friend
Definition at line 2602 of file mpreal.h.
Referenced by get_default_prec().
rec_sqrt
const mpreal rec_sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2455 of file mpreal.h.
Referenced by get_default_prec().
rem
const mpreal rem (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2409 of file mpreal.h.
Referenced by get_default_prec().
remainder
const mpreal remainder (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2287 of file mpreal.h.
Referenced by get_default_prec().
remquo
const mpreal remquo (long * q, const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2294 of file mpreal.h.
Referenced by get_default_prec().
rint
const mpreal rint (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2537 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::rint().
rint_ceil
const mpreal rint_ceil (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2538 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::rint_ceil().
rint_floor
const mpreal rint_floor (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2539 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::rint_floor().
rint_round
const mpreal rint_round (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2540 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::rint_round().
rint_trunc
const mpreal rint_trunc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2541 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::rint_trunc().
root
const mpreal root (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2194 of file mpreal.h.
Referenced by get_default_prec().
round
const mpreal round (const mpreal & v) friend
Definition at line 2523 of file mpreal.h.
Referenced by get_default_prec().
sec
const mpreal sec (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2233 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::sec().
sech
const mpreal sech (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2252 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::sech().
sgn
int sgn (const mpreal & v) friend
Definition at line 1934 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::mod().
sin
const mpreal sin (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2231 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::sin().
sin_cos
int sin_cos (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2213 of file mpreal.h.
Referenced by get_default_prec().
sinh
const mpreal sinh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2250 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::sinh().
sinh_cosh
int sinh_cosh (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2399 of file mpreal.h.
Referenced by get_default_prec().
sqr
const mpreal sqr (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2164 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::sqr().
sqrt [1/2]
const mpreal sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2167 of file mpreal.h.
Referenced by get_default_prec(), mpfr::operator/(), and mpfr::sqrt().
sqrt [2/2]
const mpreal sqrt (const unsigned long int v, mp_rnd_t rnd_mode) friend
Definition at line 2170 of file mpreal.h.
sum
const mpreal sum (const mpreal tab[], const unsigned long int n, int & status, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2381 of file mpreal.h.
Referenced by array(), and get_default_prec().
swap
void swap (mpfr::mpreal & x, mpfr::mpreal & y) friend
Definition at line 2546 of file mpreal.h.
Referenced by get_default_prec().
tan
const mpreal tan (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2232 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::tan().
tanh
const mpreal tanh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2251 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::tanh().
tgamma
const mpreal tgamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2263 of file mpreal.h.
Referenced by get_default_prec().
trunc
const mpreal trunc (const mpreal & v) friend
Definition at line 2530 of file mpreal.h.
Referenced by get_default_prec().
urandom
const mpreal urandom (gmp_randstate_t & state, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2593 of file mpreal.h.
Referenced by get_default_prec().
urandomb
const mpreal urandomb (gmp_randstate_t & state) friend
Definition at line 2585 of file mpreal.h.
Referenced by get_default_prec().
zeta
const mpreal zeta (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) friend
Definition at line 2265 of file mpreal.h.
Referenced by get_default_prec(), and mpfr::zeta().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/test/mpreal/mpreal.h