pairinteraction: Eigen::PermutationBase< Derived > Class Template Reference
Eigen::PermutationBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for permutations.
#include <PermutationMatrix.h>
Public Types
enum {
Flags = Traits::Flags, RowsAtCompileTime = Traits::RowsAtCompileTime, ColsAtCompileTime = Traits::ColsAtCompileTime, MaxRowsAtCompileTime = Traits::MaxRowsAtCompileTime,
MaxColsAtCompileTime = Traits::MaxColsAtCompileTime
}
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
typedef Matrix< StorageIndex, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix< IndicesType::SizeAtCompileTime, IndicesType::MaxSizeAtCompileTime, StorageIndex > PlainPermutationType
typedef PlainPermutationType PlainObject
typedef Inverse< Derived > InverseReturnType
typedef void Scalar
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const PermutationBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &tr)
Derived & operator= (const PermutationBase &other)
Index rows () const
Index cols () const
Index size () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index newSize)
void setIdentity ()
void setIdentity (Index newSize)
Derived & applyTranspositionOnTheLeft (Index i, Index j)
Derived & applyTranspositionOnTheRight (Index i, Index j)
InverseReturnType inverse () const
InverseReturnType transpose () const
template<typename Other >
PlainPermutationType operator* (const PermutationBase< Other > &other) const
template<typename Other >
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other) const
Index determinant () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
template<typename OtherDerived >
void assignTranspose (const PermutationBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Friends
template<typename Other >
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other, const PermutationBase &perm)
Detailed Description
template<typename Derived>
class Eigen::PermutationBase< Derived >
Base class for permutations.
Template Parameters
Derived the derived class
This class is the base class for all expressions representing a permutation matrix, internally stored as a vector of integers. The convention followed here is that if \(\sigma \) is a permutation, the corresponding permutation matrix \(P_\sigma \) is such that if \((e_1,\ldots,e_p) \) is the canonical basis, we have:
\[ P_\sigma(e_i) = e_{\sigma(i)}. \]
This convention ensures that for any two permutations \(\sigma, \tau \), we have:
\[ P_{\sigma\circ\tau} = P_\sigma P_\tau. \]
Permutation matrices are square and invertible.
Notice that in addition to the member functions and operators listed here, there also are non-member operator* to multiply any kind of permutation object with any kind of matrix expression (MatrixBase) on either side.
See also
class PermutationMatrix, class PermutationWrapper
Definition at line 46 of file PermutationMatrix.h.
Member Typedef Documentation
DenseMatrixType
template<typename Derived> typedef Matrix<StorageIndex,RowsAtCompileTime,ColsAtCompileTime,0,MaxRowsAtCompileTime,MaxColsAtCompileTime> Eigen::PermutationBase< Derived >::DenseMatrixType
Definition at line 63 of file PermutationMatrix.h.
IndicesType
template<typename Derived> typedef Traits::IndicesType Eigen::PermutationBase< Derived >::IndicesType
Definition at line 53 of file PermutationMatrix.h.
InverseReturnType
template<typename Derived> typedef Inverse<Derived> Eigen::PermutationBase< Derived >::InverseReturnType
Definition at line 68 of file PermutationMatrix.h.
PlainObject
template<typename Derived> typedef PlainPermutationType Eigen::PermutationBase< Derived >::PlainObject
Definition at line 66 of file PermutationMatrix.h.
PlainPermutationType
template<typename Derived> typedef PermutationMatrix<IndicesType::SizeAtCompileTime,IndicesType::MaxSizeAtCompileTime,StorageIndex> Eigen::PermutationBase< Derived >::PlainPermutationType
Definition at line 65 of file PermutationMatrix.h.
Scalar
template<typename Derived> typedef void Eigen::PermutationBase< Derived >::Scalar
Definition at line 69 of file PermutationMatrix.h.
StorageIndex
template<typename Derived> typedef Traits::StorageIndex Eigen::PermutationBase< Derived >::StorageIndex
Definition at line 61 of file PermutationMatrix.h.
Member Enumeration Documentation
anonymous enum
template<typename Derived> anonymous enum
Enumerator
Flags
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 54 of file PermutationMatrix.h.
Member Function Documentation
applyTranspositionOnTheLeft()
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft (Index i, Index j) inline
Multiplies *this by the transposition \((ij)\) on the left.
Returns
a reference to *this.
Warning
This is much slower than applyTranspositionOnTheRight(Index,Index): this has linear complexity and requires a lot of branching.
See also
applyTranspositionOnTheRight(Index,Index)
Definition at line 166 of file PermutationMatrix.h.
applyTranspositionOnTheRight()
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight (Index i, Index j) inline
Multiplies *this by the transposition \((ij)\) on the right.
Returns
a reference to *this.
This is a fast operation, it only consists in swapping two indices.
See also
applyTranspositionOnTheLeft(Index,Index)
Definition at line 185 of file PermutationMatrix.h.
Referenced by Eigen::FullPivLU< _MatrixType >::computeInPlace().
assignProduct()
template<typename Derived> template<typename Lhs , typename Rhs > void Eigen::PermutationBase< Derived >::assignProduct (const Lhs & lhs, const Rhs & rhs) inline protected
Definition at line 216 of file PermutationMatrix.h.
assignTranspose()
template<typename Derived> template<typename OtherDerived > void Eigen::PermutationBase< Derived >::assignTranspose (const PermutationBase< OtherDerived > & other) inline protected
Definition at line 211 of file PermutationMatrix.h.
cols()
template<typename Derived> Index Eigen::PermutationBase< Derived >::cols (void) const inline
Returns
the number of columns
Definition at line 105 of file PermutationMatrix.h.
determinant()
template<typename Derived> Index Eigen::PermutationBase< Derived >::determinant () const inline
Returns
the determinant of the permutation matrix, which is either 1 or -1 depending on the parity of the permutation.
This function is O(n) procedure allocating a buffer of n booleans.
Definition at line 253 of file PermutationMatrix.h.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize().
evalTo()
template<typename Derived> template<typename DenseDerived > void Eigen::PermutationBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const inline
Definition at line 112 of file PermutationMatrix.h.
indices() [1/2]
template<typename Derived> const IndicesType& Eigen::PermutationBase< Derived >::indices () const inline
const version of indices().
Definition at line 130 of file PermutationMatrix.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::assignTranspose(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::operator=(), and Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=().
indices() [2/2]
template<typename Derived> IndicesType& Eigen::PermutationBase< Derived >::indices () inline
Returns
a reference to the stored array representing the permutation.
Definition at line 132 of file PermutationMatrix.h.
inverse()
template<typename Derived> InverseReturnType Eigen::PermutationBase< Derived >::inverse () const inline
Returns
the inverse permutation matrix.
Note
Definition at line 196 of file PermutationMatrix.h.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::_solve_impl(), Eigen::FullPivLU< _MatrixType >::_solve_impl_transposed(), cod(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), inverse_permutation_4x4(), qr(), qr_fixedsize(), and Eigen::FullPivLU< _MatrixType >::reconstructedMatrix().
operator*() [1/2]
template<typename Derived> template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const PermutationBase< Other > & other) const inline
Returns
the product permutation matrix.
Note
Definition at line 230 of file PermutationMatrix.h.
operator*() [2/2]
template<typename Derived> template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const InverseImpl< Other, PermutationStorage > & other) const inline
Returns
the product of a permutation with another inverse permutation.
Note
Definition at line 238 of file PermutationMatrix.h.
operator=() [1/3]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::PermutationBase< Derived >::operator= (const PermutationBase< OtherDerived > & other) inline
Copies the other permutation into *this
Definition at line 74 of file PermutationMatrix.h.
operator=() [2/3]
template<typename Derived> template<typename OtherDerived > Derived& Eigen::PermutationBase< Derived >::operator= (const TranspositionsBase< OtherDerived > & tr) inline
Assignment from the Transpositions tr
Definition at line 82 of file PermutationMatrix.h.
operator=() [3/3]
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::operator= (const PermutationBase< Derived > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 94 of file PermutationMatrix.h.
resize()
template<typename Derived> void Eigen::PermutationBase< Derived >::resize (Index newSize) inline
Resizes to given size.
Definition at line 136 of file PermutationMatrix.h.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::PardisoLLT< MatrixType, _UpLo >::getMatrix(), Eigen::PardisoLDLT< MatrixType, Options >::getMatrix(), Eigen::internal::minimum_degree_ordering(), and Eigen::MetisOrdering< StorageIndex >::operator()().
rows()
template<typename Derived> Index Eigen::PermutationBase< Derived >::rows (void) const inline
Returns
the number of rows
Definition at line 102 of file PermutationMatrix.h.
setIdentity() [1/2]
template<typename Derived> void Eigen::PermutationBase< Derived >::setIdentity () inline
Sets *this to be the identity permutation matrix
Definition at line 142 of file PermutationMatrix.h.
Referenced by Eigen::FullPivLU< _MatrixType >::computeInPlace().
setIdentity() [2/2]
template<typename Derived> void Eigen::PermutationBase< Derived >::setIdentity (Index newSize) inline
Sets *this to be the identity permutation matrix of given size.
Definition at line 151 of file PermutationMatrix.h.
size()
template<typename Derived> Index Eigen::PermutationBase< Derived >::size () const inline
Returns
the size of a side of the respective square matrix, i.e., the number of indices
Definition at line 108 of file PermutationMatrix.h.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::size().
toDenseMatrix()
template<typename Derived> DenseMatrixType Eigen::PermutationBase< Derived >::toDenseMatrix () const inline
Returns
a Matrix object initialized from this permutation matrix. Notice that it is inefficient to return this Matrix object by value. For efficiency, favor using the Matrix constructor taking EigenBase objects.
Definition at line 124 of file PermutationMatrix.h.
transpose()
template<typename Derived> InverseReturnType Eigen::PermutationBase< Derived >::transpose () const inline
Returns
the tranpose permutation matrix.
Note
Definition at line 202 of file PermutationMatrix.h.
Referenced by Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run().
Friends And Related Function Documentation
operator*
template<typename Derived> template<typename Other > PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > & other, const PermutationBase< Derived > & perm) friend
Returns
the product of an inverse permutation with another permutation.
Note
Definition at line 246 of file PermutationMatrix.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/PermutationMatrix.h