pairinteraction: Eigen::TensorImagePatchOp< Rows, Cols, XprType > Class Template Reference
Eigen::TensorImagePatchOp< Rows, Cols, XprType > Class Template Reference
#include <TensorForwardDeclarations.h>
Public Types
typedef Eigen::internal::traits< TensorImagePatchOp >::Scalar Scalar
typedef Eigen::NumTraits< Scalar >::Real RealScalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef Eigen::internal::nested< TensorImagePatchOp >::type Nested
typedef Eigen::internal::traits< TensorImagePatchOp >::StorageKind StorageKind
typedef Eigen::internal::traits< TensorImagePatchOp >::Index Index
Public Types inherited from Eigen::TensorBase< TensorImagePatchOp< Rows, Cols, XprType >, ReadOnlyAccessors >
typedef internal::traits< TensorImagePatchOp< Rows, Cols, XprType > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp (const XprType &expr, DenseIndex patch_rows, DenseIndex patch_cols, DenseIndex row_strides, DenseIndex col_strides, DenseIndex in_row_strides, DenseIndex in_col_strides, DenseIndex row_inflate_strides, DenseIndex col_inflate_strides, PaddingType padding_type, Scalar padding_value)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp (const XprType &expr, DenseIndex patch_rows, DenseIndex patch_cols, DenseIndex row_strides, DenseIndex col_strides, DenseIndex in_row_strides, DenseIndex in_col_strides, DenseIndex row_inflate_strides, DenseIndex col_inflate_strides, DenseIndex padding_top, DenseIndex padding_bottom, DenseIndex padding_left, DenseIndex padding_right, Scalar padding_value)
EIGEN_DEVICE_FUNC DenseIndex patch_rows () const
EIGEN_DEVICE_FUNC DenseIndex patch_cols () const
EIGEN_DEVICE_FUNC DenseIndex row_strides () const
EIGEN_DEVICE_FUNC DenseIndex col_strides () const
EIGEN_DEVICE_FUNC DenseIndex in_row_strides () const
EIGEN_DEVICE_FUNC DenseIndex in_col_strides () const
EIGEN_DEVICE_FUNC DenseIndex row_inflate_strides () const
EIGEN_DEVICE_FUNC DenseIndex col_inflate_strides () const
EIGEN_DEVICE_FUNC bool padding_explicit () const
EIGEN_DEVICE_FUNC DenseIndex padding_top () const
EIGEN_DEVICE_FUNC DenseIndex padding_bottom () const
EIGEN_DEVICE_FUNC DenseIndex padding_left () const
EIGEN_DEVICE_FUNC DenseIndex padding_right () const
EIGEN_DEVICE_FUNC PaddingType padding_type () const
EIGEN_DEVICE_FUNC Scalar padding_value () const
EIGEN_DEVICE_FUNC const internal::remove_all< typename XprType::Nested >::type & expression () const
Public Member Functions inherited from Eigen::TensorBase< TensorImagePatchOp< Rows, Cols, XprType >, ReadOnlyAccessors >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorImagePatchOp< Rows, Cols, XprType > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorImagePatchOp< Rows, Cols, XprType > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorImagePatchOp< Rows, Cols, XprType >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorImagePatchOp< Rows, Cols, XprType >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorImagePatchOp< Rows, Cols, XprType > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorImagePatchOp< Rows, Cols, XprType > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorImagePatchOp< Rows, Cols, XprType > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorImagePatchOp< Rows, Cols, XprType > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorImagePatchOp< Rows, Cols, XprType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorImagePatchOp< Rows, Cols, XprType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorImagePatchOp< Rows, Cols, XprType > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorImagePatchOp< Rows, Cols, XprType > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorImagePatchOp< Rows, Cols, XprType > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorImagePatchOp< Rows, Cols, XprType > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorImagePatchOp< Rows, Cols, XprType > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorImagePatchOp< Rows, Cols, XprType > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorImagePatchOp< Rows, Cols, XprType > > shuffle (const Shuffle &shuffle) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorImagePatchOp< Rows, Cols, XprType > > shuffle (const Shuffle &shuffle)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorImagePatchOp< Rows, Cols, XprType > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorImagePatchOp< Rows, Cols, XprType > > stride (const Strides &strides)
TensorDevice< TensorImagePatchOp< Rows, Cols, XprType >, DeviceType > device (const DeviceType &device)
Protected Attributes
XprType::Nested m_xpr
const DenseIndex m_patch_rows
const DenseIndex m_patch_cols
const DenseIndex m_row_strides
const DenseIndex m_col_strides
const DenseIndex m_in_row_strides
const DenseIndex m_in_col_strides
const DenseIndex m_row_inflate_strides
const DenseIndex m_col_inflate_strides
const bool m_padding_explicit
const DenseIndex m_padding_top
const DenseIndex m_padding_bottom
const DenseIndex m_padding_left
const DenseIndex m_padding_right
const PaddingType m_padding_type
const Scalar m_padding_value
Additional Inherited Members
Static Public Attributes inherited from Eigen::TensorBase< TensorImagePatchOp< Rows, Cols, XprType >, ReadOnlyAccessors >
static const int NumDimensions
Protected Member Functions inherited from Eigen::TensorBase< TensorImagePatchOp< Rows, Cols, XprType >, ReadOnlyAccessors >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorImagePatchOp< Rows, Cols, XprType > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorImagePatchOp< Rows, Cols, XprType > & derived () const
Detailed Description
template<DenseIndex Rows, DenseIndex Cols, typename XprType>
class Eigen::TensorImagePatchOp< Rows, Cols, XprType >
Definition at line 45 of file TensorForwardDeclarations.h.
Member Typedef Documentation
CoeffReturnType
template<DenseIndex Rows, DenseIndex Cols, typename XprType> typedef XprType::CoeffReturnType Eigen::TensorImagePatchOp< Rows, Cols, XprType >::CoeffReturnType
Definition at line 63 of file TensorImagePatch.h.
Index
template<DenseIndex Rows, DenseIndex Cols, typename XprType> typedef Eigen::internal::traits<TensorImagePatchOp>::Index Eigen::TensorImagePatchOp< Rows, Cols, XprType >::Index
Definition at line 66 of file TensorImagePatch.h.
Nested
template<DenseIndex Rows, DenseIndex Cols, typename XprType> typedef Eigen::internal::nested<TensorImagePatchOp>::type Eigen::TensorImagePatchOp< Rows, Cols, XprType >::Nested
Definition at line 64 of file TensorImagePatch.h.
RealScalar
template<DenseIndex Rows, DenseIndex Cols, typename XprType> typedef Eigen::NumTraits<Scalar>::Real Eigen::TensorImagePatchOp< Rows, Cols, XprType >::RealScalar
Definition at line 62 of file TensorImagePatch.h.
Scalar
template<DenseIndex Rows, DenseIndex Cols, typename XprType> typedef Eigen::internal::traits<TensorImagePatchOp>::Scalar Eigen::TensorImagePatchOp< Rows, Cols, XprType >::Scalar
Definition at line 61 of file TensorImagePatch.h.
StorageKind
template<DenseIndex Rows, DenseIndex Cols, typename XprType> typedef Eigen::internal::traits<TensorImagePatchOp>::StorageKind Eigen::TensorImagePatchOp< Rows, Cols, XprType >::StorageKind
Definition at line 65 of file TensorImagePatch.h.
Constructor & Destructor Documentation
TensorImagePatchOp() [1/2]
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorImagePatchOp< Rows, Cols, XprType >::TensorImagePatchOp (const XprType & expr, DenseIndex patch_rows, DenseIndex patch_cols, DenseIndex row_strides, DenseIndex col_strides, DenseIndex in_row_strides, DenseIndex in_col_strides, DenseIndex row_inflate_strides, DenseIndex col_inflate_strides, PaddingType padding_type, Scalar padding_value) inline
Definition at line 68 of file TensorImagePatch.h.
TensorImagePatchOp() [2/2]
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorImagePatchOp< Rows, Cols, XprType >::TensorImagePatchOp (const XprType & expr, DenseIndex patch_rows, DenseIndex patch_cols, DenseIndex row_strides, DenseIndex col_strides, DenseIndex in_row_strides, DenseIndex in_col_strides, DenseIndex row_inflate_strides, DenseIndex col_inflate_strides, DenseIndex padding_top, DenseIndex padding_bottom, DenseIndex padding_left, DenseIndex padding_right, Scalar padding_value) inline
Definition at line 80 of file TensorImagePatch.h.
Member Function Documentation
col_inflate_strides()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::col_inflate_strides () const inline
Definition at line 110 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
col_strides()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::col_strides () const inline
Definition at line 102 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
expression()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC const internal::remove_all<typename XprType::Nested>::type& Eigen::TensorImagePatchOp< Rows, Cols, XprType >::expression () const inline
Definition at line 128 of file TensorImagePatch.h.
in_col_strides()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::in_col_strides () const inline
Definition at line 106 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
in_row_strides()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::in_row_strides () const inline
Definition at line 104 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_bottom()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_bottom () const inline
Definition at line 116 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_explicit()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC bool Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_explicit () const inline
Definition at line 112 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_left()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_left () const inline
Definition at line 118 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_right()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_right () const inline
Definition at line 120 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_top()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_top () const inline
Definition at line 114 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_type()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC PaddingType Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_type () const inline
Definition at line 122 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
padding_value()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC Scalar Eigen::TensorImagePatchOp< Rows, Cols, XprType >::padding_value () const inline
Definition at line 124 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
patch_cols()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::patch_cols () const inline
Definition at line 98 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
patch_rows()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::patch_rows () const inline
Definition at line 96 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
row_inflate_strides()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::row_inflate_strides () const inline
Definition at line 108 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
row_strides()
template<DenseIndex Rows, DenseIndex Cols, typename XprType> EIGEN_DEVICE_FUNC DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::row_strides () const inline
Definition at line 100 of file TensorImagePatch.h.
Referenced by Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator().
Field Documentation
m_col_inflate_strides
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_col_inflate_strides protected
Definition at line 139 of file TensorImagePatch.h.
m_col_strides
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_col_strides protected
Definition at line 135 of file TensorImagePatch.h.
m_in_col_strides
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_in_col_strides protected
Definition at line 137 of file TensorImagePatch.h.
m_in_row_strides
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_in_row_strides protected
Definition at line 136 of file TensorImagePatch.h.
m_padding_bottom
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_bottom protected
Definition at line 142 of file TensorImagePatch.h.
m_padding_explicit
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const bool Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_explicit protected
Definition at line 140 of file TensorImagePatch.h.
m_padding_left
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_left protected
Definition at line 143 of file TensorImagePatch.h.
m_padding_right
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_right protected
Definition at line 144 of file TensorImagePatch.h.
m_padding_top
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_top protected
Definition at line 141 of file TensorImagePatch.h.
m_padding_type
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const PaddingType Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_type protected
Definition at line 145 of file TensorImagePatch.h.
m_padding_value
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const Scalar Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_padding_value protected
Definition at line 146 of file TensorImagePatch.h.
m_patch_cols
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_patch_cols protected
Definition at line 133 of file TensorImagePatch.h.
m_patch_rows
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_patch_rows protected
Definition at line 132 of file TensorImagePatch.h.
m_row_inflate_strides
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_row_inflate_strides protected
Definition at line 138 of file TensorImagePatch.h.
m_row_strides
template<DenseIndex Rows, DenseIndex Cols, typename XprType> const DenseIndex Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_row_strides protected
Definition at line 134 of file TensorImagePatch.h.
m_xpr
template<DenseIndex Rows, DenseIndex Cols, typename XprType> XprType::Nested Eigen::TensorImagePatchOp< Rows, Cols, XprType >::m_xpr protected
Definition at line 131 of file TensorImagePatch.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorForwardDeclarations.h
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h