pairinteraction: Eigen::MatrixPowerAtomic< MatrixType > Class Template Reference
Eigen::MatrixPowerAtomic< MatrixType > Class Template Reference
Class for computing matrix powers.
#include <MatrixPower.h>
Public Member Functions
MatrixPowerAtomic (const MatrixType &T, RealScalar p)
Constructor.
void compute (ResultType &res) const
Compute the matrix power.
Detailed Description
template<typename MatrixType>
class Eigen::MatrixPowerAtomic< MatrixType >
Class for computing matrix powers.
Template Parameters
MatrixType type of the base, expected to be an instantiation of the Matrix class template.
This class is capable of computing triangular real/complex matrices raised to a power in the interval \((-1, 1) \).
Note
Currently this class is only used by MatrixPower. One may insist that this be nested into MatrixPower. This class is here to faciliate future development of triangular matrix functions.
Definition at line 87 of file MatrixPower.h.
Constructor & Destructor Documentation
MatrixPowerAtomic()
template<typename MatrixType > Eigen::MatrixPowerAtomic< MatrixType >::MatrixPowerAtomic (const MatrixType & T, RealScalar p)
Constructor.
Parameters
[in] T the base of the matrix power.
[in] p the exponent of the matrix power, should be in \((-1, 1) \).
The class stores a reference to T, so it should not be changed (or destroyed) before evaluation. Only the upper triangular part of T is read.
Definition at line 136 of file MatrixPower.h.
References eigen_assert.
Member Function Documentation
compute()
template<typename MatrixType > void Eigen::MatrixPowerAtomic< MatrixType >::compute (ResultType & res) const
Compute the matrix power.
Parameters
[out] res \(A^p \) where A and p are specified in the constructor.
Definition at line 144 of file MatrixPower.h.
References abs(), eigen_assert, eval(), i, L, mpfr::ldexp(), Eigen::matrix_sqrt_triangular(), p, Eigen::half_impl::pow(), and res.
Referenced by Eigen::MatrixPower< MatrixType >::compute(), Eigen::MatrixPowerReturnValue< Derived >::evalTo(), and Eigen::MatrixPower< MatrixType >::operator()().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixPower.h