pairinteraction: Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout > Class Template Reference
Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout > Class Template Reference
#include <TensorConvolution.h>
Public Member Functions
IndexMapper (const InputDims &input_dims, const array< Index, NumKernelDims > &kernel_dims, const array< Index, NumKernelDims > &indices)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaInputPlaneToTensorInputOffset (Index p) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaOutputPlaneToTensorOutputOffset (Index p) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaInputKernelToTensorInputOffset (Index i) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaOutputKernelToTensorOutputOffset (Index i) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaInputKernelToTensorInputOffset (Index i, Index j) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaOutputKernelToTensorOutputOffset (Index i, Index j) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaInputKernelToTensorInputOffset (Index i, Index j, Index k) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index mapCudaOutputKernelToTensorOutputOffset (Index i, Index j, Index k) const
Detailed Description
template<typename Index, typename InputDims, int NumKernelDims, int Layout>
class Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >
Definition at line 25 of file TensorConvolution.h.
Constructor & Destructor Documentation
IndexMapper()
template<typename Index, typename InputDims, int NumKernelDims, int Layout> Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::IndexMapper (const InputDims & input_dims, const array< Index, NumKernelDims > & kernel_dims, const array< Index, NumKernelDims > & indices) inline
Definition at line 27 of file TensorConvolution.h.
References Eigen::ColMajor, i, and offset.
Member Function Documentation
mapCudaInputKernelToTensorInputOffset() [1/3]
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputKernelToTensorInputOffset (Index i) const inline
Definition at line 164 of file TensorConvolution.h.
References Eigen::ColMajor, and offset.
Referenced by Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data().
mapCudaInputKernelToTensorInputOffset() [2/3]
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputKernelToTensorInputOffset (Index i, Index j) const inline
Definition at line 178 of file TensorConvolution.h.
References Eigen::ColMajor, and offset.
mapCudaInputKernelToTensorInputOffset() [3/3]
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputKernelToTensorInputOffset (Index i, Index j, Index k) const inline
Definition at line 192 of file TensorConvolution.h.
References Eigen::ColMajor, and offset.
mapCudaInputPlaneToTensorInputOffset()
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputPlaneToTensorInputOffset (Index p) const inline
Definition at line 116 of file TensorConvolution.h.
References Eigen::ColMajor.
Referenced by Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data().
mapCudaOutputKernelToTensorOutputOffset() [1/3]
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputKernelToTensorOutputOffset (Index i) const inline
Definition at line 171 of file TensorConvolution.h.
References Eigen::ColMajor, and offset.
Referenced by Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data().
mapCudaOutputKernelToTensorOutputOffset() [2/3]
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputKernelToTensorOutputOffset (Index i, Index j) const inline
Definition at line 185 of file TensorConvolution.h.
References Eigen::ColMajor, and offset.
mapCudaOutputKernelToTensorOutputOffset() [3/3]
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputKernelToTensorOutputOffset (Index i, Index j, Index k) const inline
Definition at line 200 of file TensorConvolution.h.
References Eigen::ColMajor, and offset.
mapCudaOutputPlaneToTensorOutputOffset()
template<typename Index, typename InputDims, int NumKernelDims, int Layout> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Index Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputPlaneToTensorOutputOffset (Index p) const inline
Definition at line 140 of file TensorConvolution.h.
References Eigen::ColMajor.
Referenced by Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorConvolution.h