pairinteraction: STL_Perf_Analyzer< ACTION > Class Template Reference
STL_Perf_Analyzer< ACTION > Class Template Reference
#include <STL_perf_analyzer.hh>
Public Member Functions
STL_Perf_Analyzer (unsigned long long nb_sample=DEFAULT_NB_SAMPLE)
STL_Perf_Analyzer (const STL_Perf_Analyzer &)
~STL_Perf_Analyzer (void)
double eval_mflops (int size)
Detailed Description
template<class ACTION>
class STL_Perf_Analyzer< ACTION >
Definition at line 27 of file STL_perf_analyzer.hh.
Constructor & Destructor Documentation
STL_Perf_Analyzer() [1/2]
template<class ACTION > STL_Perf_Analyzer< ACTION >::STL_Perf_Analyzer (unsigned long long nb_sample = DEFAULT_NB_SAMPLE) inline
Definition at line 29 of file STL_perf_analyzer.hh.
References MESSAGE.
STL_Perf_Analyzer() [2/2]
template<class ACTION > STL_Perf_Analyzer< ACTION >::STL_Perf_Analyzer (const STL_Perf_Analyzer< ACTION > &) inline
Definition at line 33 of file STL_perf_analyzer.hh.
References INFOS.
~STL_Perf_Analyzer()
template<class ACTION > STL_Perf_Analyzer< ACTION >::~STL_Perf_Analyzer (void) inline
Definition at line 37 of file STL_perf_analyzer.hh.
References MESSAGE.
Member Function Documentation
eval_mflops()
template<class ACTION > double STL_Perf_Analyzer< ACTION >::eval_mflops (int size) inline
Definition at line 42 of file STL_perf_analyzer.hh.
References STL_Timer::check(), STL_Timer::get_time(), STL_Timer::start(), and STL_Timer::start_baseline().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/timers/STL_perf_analyzer.hh