pairinteraction: eigen3_interface< real, SIZE > Class Template Reference
eigen3_interface< real, SIZE > Class Template Reference
#include <eigen3_interface.hh>
Public Types
enum { IsFixedSize = (SIZE!=Dynamic) }
typedef real real_type
typedef std::vector< real > stl_vector
typedef std::vector< stl_vector > stl_matrix
typedef Eigen::Matrix< real, SIZE, SIZE > gene_matrix
typedef Eigen::Matrix< real, SIZE, 1 > gene_vector
Static Public Member Functions
static std::string name (void)
static void free_matrix (gene_matrix &, int)
static void free_vector (gene_vector &)
static BTL_DONT_INLINE void matrix_from_stl (gene_matrix &A, stl_matrix &A_stl)
static BTL_DONT_INLINE void vector_from_stl (gene_vector &B, stl_vector &B_stl)
static BTL_DONT_INLINE void vector_to_stl (gene_vector &B, stl_vector &B_stl)
static BTL_DONT_INLINE void matrix_to_stl (gene_matrix &A, stl_matrix &A_stl)
static void matrix_matrix_product (const gene_matrix &A, const gene_matrix &B, gene_matrix &X, int)
static void transposed_matrix_matrix_product (const gene_matrix &A, const gene_matrix &B, gene_matrix &X, int)
static void aat_product (const gene_matrix &A, gene_matrix &X, int)
static void matrix_vector_product (const gene_matrix &A, const gene_vector &B, gene_vector &X, int)
static void symv (const gene_matrix &A, const gene_vector &B, gene_vector &X, int)
template<typename Dest , typename Src >
static void triassign (Dest &dst, const Src &src)
static EIGEN_DONT_INLINE void syr2 (gene_matrix &A, gene_vector &X, gene_vector &Y, int N)
static EIGEN_DONT_INLINE void ger (gene_matrix &A, gene_vector &X, gene_vector &Y, int N)
static EIGEN_DONT_INLINE void rot (gene_vector &A, gene_vector &B, real c, real s, int)
static void atv_product (gene_matrix &A, gene_vector &B, gene_vector &X, int)
static void axpy (real coef, const gene_vector &X, gene_vector &Y, int)
static void axpby (real a, const gene_vector &X, real b, gene_vector &Y, int)
static EIGEN_DONT_INLINE void copy_matrix (const gene_matrix &source, gene_matrix &cible, int)
static EIGEN_DONT_INLINE void copy_vector (const gene_vector &source, gene_vector &cible, int)
static void trisolve_lower (const gene_matrix &L, const gene_vector &B, gene_vector &X, int)
static void trisolve_lower_matrix (const gene_matrix &L, const gene_matrix &B, gene_matrix &X, int)
static void trmm (const gene_matrix &L, const gene_matrix &B, gene_matrix &X, int)
static void cholesky (const gene_matrix &X, gene_matrix &C, int)
static void lu_decomp (const gene_matrix &X, gene_matrix &C, int)
static void partial_lu_decomp (const gene_matrix &X, gene_matrix &C, int N)
static void tridiagonalization (const gene_matrix &X, gene_matrix &C, int N)
static void hessenberg (const gene_matrix &X, gene_matrix &C, int)
Detailed Description
template<class real, int SIZE = Dynamic>
class eigen3_interface< real, SIZE >
Definition at line 28 of file eigen3_interface.hh.
Member Typedef Documentation
gene_matrix
template<class real , int SIZE = Dynamic> typedef Eigen::Matrix<real,SIZE,SIZE> eigen3_interface< real, SIZE >::gene_matrix
Definition at line 40 of file eigen3_interface.hh.
gene_vector
template<class real , int SIZE = Dynamic> typedef Eigen::Matrix<real,SIZE,1> eigen3_interface< real, SIZE >::gene_vector
Definition at line 41 of file eigen3_interface.hh.
real_type
template<class real , int SIZE = Dynamic> typedef real eigen3_interface< real, SIZE >::real_type
Definition at line 35 of file eigen3_interface.hh.
stl_matrix
template<class real , int SIZE = Dynamic> typedef std::vector<stl_vector> eigen3_interface< real, SIZE >::stl_matrix
Definition at line 38 of file eigen3_interface.hh.
stl_vector
template<class real , int SIZE = Dynamic> typedef std::vector<real> eigen3_interface< real, SIZE >::stl_vector
Definition at line 37 of file eigen3_interface.hh.
Member Enumeration Documentation
anonymous enum
template<class real , int SIZE = Dynamic> anonymous enum
Enumerator
IsFixedSize
Definition at line 33 of file eigen3_interface.hh.
Member Function Documentation
aat_product()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::aat_product (const gene_matrix & A, gene_matrix & X, int) inline static
Definition at line 99 of file eigen3_interface.hh.
References setZero(), and triangularView< Lower >().
atv_product()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::atv_product (gene_matrix & A, gene_vector & B, gene_vector & X, int) inline static
Definition at line 173 of file eigen3_interface.hh.
axpby()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::axpby (real a, const gene_vector & X, real b, gene_vector & Y, int) inline static
Definition at line 181 of file eigen3_interface.hh.
axpy()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::axpy (real coef, const gene_vector & X, gene_vector & Y, int) inline static
Definition at line 177 of file eigen3_interface.hh.
References X.
cholesky()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::cholesky (const gene_matrix & X, gene_matrix & C, int) inline static
Definition at line 205 of file eigen3_interface.hh.
References X.
copy_matrix()
template<class real , int SIZE = Dynamic> static EIGEN_DONT_INLINE void eigen3_interface< real, SIZE >::copy_matrix (const gene_matrix & source, gene_matrix & cible, int) inline static
Definition at line 185 of file eigen3_interface.hh.
copy_vector()
template<class real , int SIZE = Dynamic> static EIGEN_DONT_INLINE void eigen3_interface< real, SIZE >::copy_vector (const gene_vector & source, gene_vector & cible, int) inline static
Definition at line 189 of file eigen3_interface.hh.
free_matrix()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::free_matrix (gene_matrix & , int) inline static
Definition at line 48 of file eigen3_interface.hh.
free_vector()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::free_vector (gene_vector &) inline static
Definition at line 50 of file eigen3_interface.hh.
ger()
template<class real , int SIZE = Dynamic> static EIGEN_DONT_INLINE void eigen3_interface< real, SIZE >::ger (gene_matrix & A, gene_vector & X, gene_vector & Y, int N) inline static
Definition at line 164 of file eigen3_interface.hh.
hessenberg()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::hessenberg (const gene_matrix & X, gene_matrix & C, int) inline static
Definition at line 232 of file eigen3_interface.hh.
References X.
lu_decomp()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::lu_decomp (const gene_matrix & X, gene_matrix & C, int) inline static
Definition at line 214 of file eigen3_interface.hh.
matrix_from_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen3_interface< real, SIZE >::matrix_from_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 52 of file eigen3_interface.hh.
References Eigen::PlainObjectBase< Derived >::coeffRef(), i, j, Eigen::PlainObjectBase< Derived >::resize(), and size.
matrix_matrix_product()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::matrix_matrix_product (const gene_matrix & A, const gene_matrix & B, gene_matrix & X, int) inline static
Definition at line 87 of file eigen3_interface.hh.
matrix_to_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen3_interface< real, SIZE >::matrix_to_stl (gene_matrix & A, stl_matrix & A_stl) inline static
Definition at line 76 of file eigen3_interface.hh.
matrix_vector_product()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::matrix_vector_product (const gene_matrix & A, const gene_vector & B, gene_vector & X, int) inline static
Definition at line 104 of file eigen3_interface.hh.
name()
template<class real , int SIZE = Dynamic> static std::string eigen3_interface< real, SIZE >::name (void) inline static
Definition at line 43 of file eigen3_interface.hh.
References EIGEN_MAKESTRING.
partial_lu_decomp()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::partial_lu_decomp (const gene_matrix & X, gene_matrix & C, int N) inline static
Definition at line 218 of file eigen3_interface.hh.
rot()
template<class real , int SIZE = Dynamic> static EIGEN_DONT_INLINE void eigen3_interface< real, SIZE >::rot (gene_vector & A, gene_vector & B, real c, real s, int) inline static
Definition at line 169 of file eigen3_interface.hh.
References Eigen::internal::apply_rotation_in_the_plane().
symv()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::symv (const gene_matrix & A, const gene_vector & B, gene_vector & X, int) inline static
Definition at line 108 of file eigen3_interface.hh.
syr2()
template<class real , int SIZE = Dynamic> static EIGEN_DONT_INLINE void eigen3_interface< real, SIZE >::syr2 (gene_matrix & A, gene_vector & X, gene_vector & Y, int N) inline static
Definition at line 158 of file eigen3_interface.hh.
transposed_matrix_matrix_product()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::transposed_matrix_matrix_product (const gene_matrix & A, const gene_matrix & B, gene_matrix & X, int) inline static
Definition at line 91 of file eigen3_interface.hh.
triassign()
template<class real , int SIZE = Dynamic> template<typename Dest , typename Src > static void eigen3_interface< real, SIZE >::triassign (Dest & dst, const Src & src) inline static
Definition at line 113 of file eigen3_interface.hh.
References j, Eigen::RowMajorBit, and size.
tridiagonalization()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::tridiagonalization (const gene_matrix & X, gene_matrix & C, int N) inline static
Definition at line 226 of file eigen3_interface.hh.
trisolve_lower()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::trisolve_lower (const gene_matrix & L, const gene_vector & B, gene_vector & X, int) inline static
Definition at line 193 of file eigen3_interface.hh.
References triangularView< Lower >().
trisolve_lower_matrix()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::trisolve_lower_matrix (const gene_matrix & L, const gene_matrix & B, gene_matrix & X, int) inline static
Definition at line 197 of file eigen3_interface.hh.
trmm()
template<class real , int SIZE = Dynamic> static void eigen3_interface< real, SIZE >::trmm (const gene_matrix & L, const gene_matrix & B, gene_matrix & X, int) inline static
Definition at line 201 of file eigen3_interface.hh.
References triangularView< Lower >().
vector_from_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen3_interface< real, SIZE >::vector_from_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 62 of file eigen3_interface.hh.
References Eigen::PlainObjectBase< Derived >::coeffRef(), i, and Eigen::PlainObjectBase< Derived >::resize().
vector_to_stl()
template<class real , int SIZE = Dynamic> static BTL_DONT_INLINE void eigen3_interface< real, SIZE >::vector_to_stl (gene_vector & B, stl_vector & B_stl) inline static
Definition at line 70 of file eigen3_interface.hh.
References Eigen::PlainObjectBase< Derived >::coeff(), and i.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/bench/btl/libs/eigen3/eigen3_interface.hh