pairinteraction: Eigen::MaxSizeVector< T > Class Template Reference
Eigen::MaxSizeVector< T > Class Template Reference
The MaxSizeVector class.
#include <MaxSizeVector.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MaxSizeVector (size_t n)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MaxSizeVector (size_t n, const T &init)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~MaxSizeVector ()
void resize (size_t n)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void push_back (const T &t)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & operator[] (size_t i) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & operator[] (size_t i)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & back ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & back () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void pop_back ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool empty () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T * begin ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T * end ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T * begin () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T * end () const
Detailed Description
template<typename T>
class Eigen::MaxSizeVector< T >
The MaxSizeVector class.
The MaxSizeVector provides a subset of std::vector functionality.
The goal is to provide basic std::vector operations when using std::vector is not an option (e.g. on GPU or when compiling using FMA/AVX, as this can cause either compilation failures or illegal instruction failures).
Beware: The constructors are not API compatible with these of std::vector.
Definition at line 31 of file MaxSizeVector.h.
Constructor & Destructor Documentation
MaxSizeVector() [1/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::MaxSizeVector< T >::MaxSizeVector (size_t n) inline explicit
Definition at line 35 of file MaxSizeVector.h.
MaxSizeVector() [2/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::MaxSizeVector< T >::MaxSizeVector (size_t n, const T & init) inline
Definition at line 44 of file MaxSizeVector.h.
~MaxSizeVector()
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::MaxSizeVector< T >::~MaxSizeVector () inline
Definition at line 51 of file MaxSizeVector.h.
Member Function Documentation
back() [1/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::MaxSizeVector< T >::back () inline
Definition at line 89 of file MaxSizeVector.h.
Referenced by Eigen::SimpleThreadPoolTempl< Environment >::Schedule().
back() [2/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::MaxSizeVector< T >::back () const inline
Definition at line 95 of file MaxSizeVector.h.
begin() [1/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T* Eigen::MaxSizeVector< T >::begin () inline
Definition at line 122 of file MaxSizeVector.h.
begin() [2/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T* Eigen::MaxSizeVector< T >::begin () const inline
Definition at line 128 of file MaxSizeVector.h.
data() [1/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T* Eigen::MaxSizeVector< T >::data () inline
Definition at line 116 of file MaxSizeVector.h.
data() [2/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T* Eigen::MaxSizeVector< T >::data () const inline
Definition at line 119 of file MaxSizeVector.h.
empty()
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::MaxSizeVector< T >::empty () const inline
Definition at line 113 of file MaxSizeVector.h.
Referenced by Eigen::SimpleThreadPoolTempl< Environment >::Schedule().
end() [1/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T* Eigen::MaxSizeVector< T >::end () inline
Definition at line 125 of file MaxSizeVector.h.
end() [2/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T* Eigen::MaxSizeVector< T >::end () const inline
Definition at line 131 of file MaxSizeVector.h.
operator[]() [1/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::MaxSizeVector< T >::operator[] (size_t i) const inline
Definition at line 77 of file MaxSizeVector.h.
operator[]() [2/2]
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::MaxSizeVector< T >::operator[] (size_t i) inline
Definition at line 83 of file MaxSizeVector.h.
pop_back()
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MaxSizeVector< T >::pop_back () inline
Definition at line 101 of file MaxSizeVector.h.
Referenced by Eigen::SimpleThreadPoolTempl< Environment >::Schedule().
push_back()
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MaxSizeVector< T >::push_back (const T & t) inline
Definition at line 71 of file MaxSizeVector.h.
Referenced by Eigen::NonBlockingThreadPoolTempl< Environment >::NonBlockingThreadPoolTempl(), Eigen::SimpleThreadPoolTempl< Environment >::SimpleThreadPoolTempl(), and Eigen::SimpleThreadPoolTempl< Environment >::WorkerLoop().
resize()
template<typename T> void Eigen::MaxSizeVector< T >::resize (size_t n) inline
Definition at line 58 of file MaxSizeVector.h.
size()
template<typename T> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::MaxSizeVector< T >::size () const inline
Definition at line 110 of file MaxSizeVector.h.
Referenced by Eigen::NonBlockingThreadPoolTempl< Environment >::CurrentThreadId(), Eigen::EventCount::EventCount(), Eigen::SimpleThreadPoolTempl< Environment >::NumThreads(), Eigen::NonBlockingThreadPoolTempl< Environment >::NumThreads(), and Eigen::NonBlockingThreadPoolTempl< Environment >::~NonBlockingThreadPoolTempl().
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/util/MaxSizeVector.h