pairinteraction: Eigen::KdBVH< _Scalar, _Dim, _Object > Class Template Reference
Eigen::KdBVH< _Scalar, _Dim, _Object > Class Template Reference
A simple bounding volume hierarchy based on AlignedBox.
#include <KdBVH.h>
Public Types
enum { Dim = _Dim }
typedef _Object Object
typedef std::vector< Object, aligned_allocator< Object > > ObjectList
typedef _Scalar Scalar
typedef AlignedBox< Scalar, Dim > Volume
typedef std::vector< Volume, aligned_allocator< Volume > > VolumeList
typedef int Index
typedef const int * VolumeIterator
typedef const Object * ObjectIterator
Public Member Functions
KdBVH ()
template<typename Iter >
KdBVH (Iter begin, Iter end)
template<typename OIter , typename BIter >
KdBVH (OIter begin, OIter end, BIter boxBegin, BIter boxEnd)
template<typename Iter >
void init (Iter begin, Iter end)
template<typename OIter , typename BIter >
void init (OIter begin, OIter end, BIter boxBegin, BIter boxEnd)
Index getRootIndex () const
EIGEN_STRONG_INLINE void getChildren (Index index, VolumeIterator &outVBegin, VolumeIterator &outVEnd, ObjectIterator &outOBegin, ObjectIterator &outOEnd) const
const Volume & getVolume (Index index) const
Detailed Description
template<typename _Scalar, int _Dim, typename _Object>
class Eigen::KdBVH< _Scalar, _Dim, _Object >
A simple bounding volume hierarchy based on AlignedBox.
Parameters
_Scalar The underlying scalar type of the bounding boxes
_Dim The dimension of the space in which the hierarchy lives
_Object The object type that lives in the hierarchy. It must have value semantics. Either bounding_box(_Object) must be defined and return an AlignedBox<_Scalar, _Dim> or bounding boxes must be provided to the tree initializer.
This class provides a simple (as opposed to optimized) implementation of a bounding volume hierarchy analogous to a Kd-tree. Given a sequence of objects, it computes their bounding boxes, constructs a Kd-tree of their centers and builds a BVH with the structure of that Kd-tree. When the elements of the tree are too expensive to be copied around, it is useful for _Object to be a pointer.
Definition at line 67 of file KdBVH.h.
Member Typedef Documentation
Index
template<typename _Scalar, int _Dim, typename _Object> typedef int Eigen::KdBVH< _Scalar, _Dim, _Object >::Index
Definition at line 76 of file KdBVH.h.
Object
template<typename _Scalar, int _Dim, typename _Object> typedef _Object Eigen::KdBVH< _Scalar, _Dim, _Object >::Object
Definition at line 71 of file KdBVH.h.
ObjectIterator
template<typename _Scalar, int _Dim, typename _Object> typedef const Object* Eigen::KdBVH< _Scalar, _Dim, _Object >::ObjectIterator
Definition at line 78 of file KdBVH.h.
ObjectList
template<typename _Scalar, int _Dim, typename _Object> typedef std::vector<Object, aligned_allocator<Object> > Eigen::KdBVH< _Scalar, _Dim, _Object >::ObjectList
Definition at line 72 of file KdBVH.h.
Scalar
template<typename _Scalar, int _Dim, typename _Object> typedef _Scalar Eigen::KdBVH< _Scalar, _Dim, _Object >::Scalar
Definition at line 73 of file KdBVH.h.
Volume
template<typename _Scalar, int _Dim, typename _Object> typedef AlignedBox<Scalar, Dim> Eigen::KdBVH< _Scalar, _Dim, _Object >::Volume
Definition at line 74 of file KdBVH.h.
VolumeIterator
template<typename _Scalar, int _Dim, typename _Object> typedef const int* Eigen::KdBVH< _Scalar, _Dim, _Object >::VolumeIterator
Definition at line 77 of file KdBVH.h.
VolumeList
template<typename _Scalar, int _Dim, typename _Object> typedef std::vector<Volume, aligned_allocator<Volume> > Eigen::KdBVH< _Scalar, _Dim, _Object >::VolumeList
Definition at line 75 of file KdBVH.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int _Dim, typename _Object> anonymous enum
Enumerator
Dim
Definition at line 70 of file KdBVH.h.
Constructor & Destructor Documentation
KdBVH() [1/3]
template<typename _Scalar, int _Dim, typename _Object> Eigen::KdBVH< _Scalar, _Dim, _Object >::KdBVH () inline
Definition at line 80 of file KdBVH.h.
KdBVH() [2/3]
template<typename _Scalar, int _Dim, typename _Object> template<typename Iter > Eigen::KdBVH< _Scalar, _Dim, _Object >::KdBVH (Iter begin, Iter end) inline
Given an iterator range over Object references, constructs the BVH. Requires that bounding_box(Object) return a Volume.
Definition at line 83 of file KdBVH.h.
KdBVH() [3/3]
template<typename _Scalar, int _Dim, typename _Object> template<typename OIter , typename BIter > Eigen::KdBVH< _Scalar, _Dim, _Object >::KdBVH (OIter begin, OIter end, BIter boxBegin, BIter boxEnd) inline
Given an iterator range over Object references and an iterator range over their bounding boxes, constructs the BVH
Definition at line 86 of file KdBVH.h.
Member Function Documentation
getChildren()
template<typename _Scalar, int _Dim, typename _Object> EIGEN_STRONG_INLINE void Eigen::KdBVH< _Scalar, _Dim, _Object >::getChildren (Index index, VolumeIterator & outVBegin, VolumeIterator & outVEnd, ObjectIterator & outOBegin, ObjectIterator & outOEnd) const inline
Given an index of a node, on exit, outVBegin and outVEnd range over the indices of the volume children of the node and outOBegin and outOEnd range over the object children of the node
Definition at line 132 of file KdBVH.h.
getRootIndex()
template<typename _Scalar, int _Dim, typename _Object> Index Eigen::KdBVH< _Scalar, _Dim, _Object >::getRootIndex () const inline
Returns
the index of the root of the hierarchy
Definition at line 128 of file KdBVH.h.
getVolume()
template<typename _Scalar, int _Dim, typename _Object> const Volume& Eigen::KdBVH< _Scalar, _Dim, _Object >::getVolume (Index index) const inline
Returns
the bounding box of the node at index
Definition at line 164 of file KdBVH.h.
References mpfr::dim(), eigen_assert, Eigen::internal::vector_int_pair< Scalar, Dim >::first, int(), Eigen::internal::vector_int_pair< Scalar, Dim >::second, v1(), and v2().
init() [1/2]
template<typename _Scalar, int _Dim, typename _Object> template<typename Iter > void Eigen::KdBVH< _Scalar, _Dim, _Object >::init (Iter begin, Iter end) inline
Given an iterator range over Object references, constructs the BVH, overwriting whatever is in there currently. Requires that bounding_box(Object) return a Volume.
Definition at line 90 of file KdBVH.h.
References Eigen::KdBVH< _Scalar, _Dim, _Object >::init().
Referenced by Eigen::KdBVH< _Scalar, _Dim, _Object >::init().
init() [2/2]
template<typename _Scalar, int _Dim, typename _Object> template<typename OIter , typename BIter > void Eigen::KdBVH< _Scalar, _Dim, _Object >::init (OIter begin, OIter end, BIter boxBegin, BIter boxEnd) inline
Given an iterator range over Object references and an iterator range over their bounding boxes, constructs the BVH, overwriting whatever is in there currently.
Definition at line 94 of file KdBVH.h.
References i, n, and Eigen::internal::vector_int_pair< Scalar, Dim >::second.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/BVH/KdBVH.h