pairinteraction: Portable_Perf_Analyzer< Action > Class Template Reference
Portable_Perf_Analyzer< Action > Class Template Reference
#include <portable_perf_analyzer.hh>
Public Member Functions
Portable_Perf_Analyzer ()
Portable_Perf_Analyzer (const Portable_Perf_Analyzer &)
~Portable_Perf_Analyzer ()
BTL_DONT_INLINE double eval_mflops (int size)
BTL_DONT_INLINE double time_calculate (Action &action)
unsigned long long get_nb_calc ()
Portable_Perf_Analyzer (void)
Portable_Perf_Analyzer (const Portable_Perf_Analyzer &)
~Portable_Perf_Analyzer (void)
double eval_mflops (int size)
double time_init (Action &action)
double time_calculate (Action &action)
unsigned long long get_nb_calc (void)
Detailed Description
template<class Action>
class Portable_Perf_Analyzer< Action >
Definition at line 28 of file portable_perf_analyzer.hh.
Constructor & Destructor Documentation
Portable_Perf_Analyzer() [1/4]
template<class Action> Portable_Perf_Analyzer< Action >::Portable_Perf_Analyzer () inline
Definition at line 30 of file portable_perf_analyzer.hh.
References MESSAGE.
Portable_Perf_Analyzer() [2/4]
template<class Action> Portable_Perf_Analyzer< Action >::Portable_Perf_Analyzer (const Portable_Perf_Analyzer< Action > &) inline
Definition at line 33 of file portable_perf_analyzer.hh.
References INFOS.
~Portable_Perf_Analyzer() [1/2]
template<class Action> Portable_Perf_Analyzer< Action >::~Portable_Perf_Analyzer () inline
Definition at line 37 of file portable_perf_analyzer.hh.
References MESSAGE.
Portable_Perf_Analyzer() [3/4]
template<class Action> Portable_Perf_Analyzer< Action >::Portable_Perf_Analyzer (void) inline
Definition at line 29 of file portable_perf_analyzer_old.hh.
References MESSAGE.
Portable_Perf_Analyzer() [4/4]
template<class Action> Portable_Perf_Analyzer< Action >::Portable_Perf_Analyzer (const Portable_Perf_Analyzer< Action > &) inline
Definition at line 32 of file portable_perf_analyzer_old.hh.
References INFOS.
~Portable_Perf_Analyzer() [2/2]
template<class Action> Portable_Perf_Analyzer< Action >::~Portable_Perf_Analyzer (void) inline
Definition at line 36 of file portable_perf_analyzer_old.hh.
References MESSAGE.
Member Function Documentation
eval_mflops() [1/2]
template<class Action> BTL_DONT_INLINE double Portable_Perf_Analyzer< Action >::eval_mflops (int size) inline
Definition at line 41 of file portable_perf_analyzer.hh.
References i, BtlConfig::Instance, min, MIN_TIME, Portable_Perf_Analyzer< Action >::time_calculate(), and BtlConfig::tries.
eval_mflops() [2/2]
template<class Action> double Portable_Perf_Analyzer< Action >::eval_mflops (int size) inline
Definition at line 42 of file portable_perf_analyzer_old.hh.
References i, min, MIN_TIME, Portable_Perf_Analyzer< Action >::time_calculate(), and Portable_Perf_Analyzer< Action >::time_init().
get_nb_calc() [1/2]
template<class Action> unsigned long long Portable_Perf_Analyzer< Action >::get_nb_calc () inline
Definition at line 89 of file portable_perf_analyzer.hh.
get_nb_calc() [2/2]
template<class Action> unsigned long long Portable_Perf_Analyzer< Action >::get_nb_calc (void) inline
Definition at line 121 of file portable_perf_analyzer_old.hh.
time_calculate() [1/2]
template<class Action> BTL_DONT_INLINE double Portable_Perf_Analyzer< Action >::time_calculate (Action & action) inline
Definition at line 76 of file portable_perf_analyzer.hh.
References Portable_Timer::start(), Portable_Timer::stop(), and Portable_Timer::user_time().
Referenced by Portable_Perf_Analyzer< Action >::eval_mflops().
time_calculate() [2/2]
template<class Action> double Portable_Perf_Analyzer< Action >::time_calculate (Action & action) inline
Definition at line 108 of file portable_perf_analyzer_old.hh.
References Portable_Timer::start(), Portable_Timer::stop(), and Portable_Timer::user_time().
time_init()
template<class Action> double Portable_Perf_Analyzer< Action >::time_init (Action & action) inline
Definition at line 97 of file portable_perf_analyzer_old.hh.
References Portable_Timer::start(), Portable_Timer::stop(), and Portable_Timer::user_time().
Referenced by Portable_Perf_Analyzer< Action >::eval_mflops().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/bench/btl/generic_bench/timers/portable_perf_analyzer.hh
/travis/libpairinteraction/eigen/bench/btl/generic_bench/timers/portable_perf_analyzer_old.hh