pairinteraction: Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType > Class Template Reference
Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Generic expression where a coefficient-wise binary operator is applied to two expressions.
#include <CwiseBinaryOp.h>
Public Types
typedef internal::remove_all< BinaryOp >::type Functor
typedef internal::remove_all< LhsType >::type Lhs
typedef internal::remove_all< RhsType >::type Rhs
typedef CwiseBinaryOpImpl< BinaryOp, LhsType, RhsType, typename internal::cwise_promote_storage_type< typename internal::traits< LhsType >::StorageKind, typename internal::traits< Rhs >::StorageKind, BinaryOp >::ret >::Base Base
typedef internal::ref_selector< LhsType >::type LhsNested
typedef internal::ref_selector< RhsType >::type RhsNested
typedef internal::remove_reference< LhsNested >::type _LhsNested
typedef internal::remove_reference< RhsNested >::type _RhsNested
Public Types inherited from Eigen::CwiseBinaryOpImpl< BinaryOp, LhsType, RhsType, internal::cwise_promote_storage_type< internal::traits< LhsType >::StorageKind, internal::traits< RhsType >::StorageKind, BinaryOp >::ret >
typedef internal::generic_xpr_base< CwiseBinaryOp< BinaryOp, LhsType, RhsType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CwiseBinaryOp (const Lhs &aLhs, const Rhs &aRhs, const BinaryOp &func=BinaryOp())
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index cols () const
EIGEN_DEVICE_FUNC const _LhsNested & lhs () const
EIGEN_DEVICE_FUNC const _RhsNested & rhs () const
EIGEN_DEVICE_FUNC const BinaryOp & functor () const
Protected Attributes
LhsNested m_lhs
RhsNested m_rhs
const BinaryOp m_functor
Detailed Description
template<typename BinaryOp, typename LhsType, typename RhsType>
class Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >
Generic expression where a coefficient-wise binary operator is applied to two expressions.
Template Parameters
BinaryOp template functor implementing the operator
LhsType the type of the left-hand side
RhsType the type of the right-hand side
This class represents an expression where a coefficient-wise binary operator is applied to two expressions. It is the return type of binary operators, by which we mean only those binary operators where both the left-hand side and the right-hand side are Eigen expressions. For example, the return type of matrix1+matrix2 is a CwiseBinaryOp.
Most of the time, this is the only way that it is used, so you typically don't have to name CwiseBinaryOp types explicitly.
See also
MatrixBase::binaryExpr(const MatrixBase<OtherDerived> &,const CustomBinaryOp &) const, class CwiseUnaryOp, class CwiseNullaryOp
Definition at line 77 of file CwiseBinaryOp.h.
Member Typedef Documentation
_LhsNested
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::remove_reference<LhsNested>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::_LhsNested
Definition at line 100 of file CwiseBinaryOp.h.
_RhsNested
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::remove_reference<RhsNested>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::_RhsNested
Definition at line 101 of file CwiseBinaryOp.h.
Base
template<typename BinaryOp, typename LhsType, typename RhsType> typedef CwiseBinaryOpImpl< BinaryOp, LhsType, RhsType, typename internal::cwise_promote_storage_type<typename internal::traits<LhsType>::StorageKind, typename internal::traits<Rhs>::StorageKind, BinaryOp>::ret>::Base Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Base
Definition at line 95 of file CwiseBinaryOp.h.
Functor
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::remove_all<BinaryOp>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Functor
Definition at line 87 of file CwiseBinaryOp.h.
Lhs
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::remove_all<LhsType>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Lhs
Definition at line 88 of file CwiseBinaryOp.h.
LhsNested
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::ref_selector<LhsType>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::LhsNested
Definition at line 98 of file CwiseBinaryOp.h.
Rhs
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::remove_all<RhsType>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Rhs
Definition at line 89 of file CwiseBinaryOp.h.
RhsNested
template<typename BinaryOp, typename LhsType, typename RhsType> typedef internal::ref_selector<RhsType>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::RhsNested
Definition at line 99 of file CwiseBinaryOp.h.
Constructor & Destructor Documentation
CwiseBinaryOp()
template<typename BinaryOp, typename LhsType, typename RhsType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::CwiseBinaryOp (const Lhs & aLhs, const Rhs & aRhs, const BinaryOp & func = BinaryOp()) inline
Definition at line 104 of file CwiseBinaryOp.h.
References eigen_assert, EIGEN_CHECK_BINARY_COMPATIBILIY, and EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE.
Member Function Documentation
cols()
template<typename BinaryOp, typename LhsType, typename RhsType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols () const inline
Definition at line 122 of file CwiseBinaryOp.h.
References Eigen::Dynamic.
functor()
template<typename BinaryOp, typename LhsType, typename RhsType> EIGEN_DEVICE_FUNC const BinaryOp& Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::functor () const inline
Returns
the functor representing the binary operation
Definition at line 138 of file CwiseBinaryOp.h.
lhs()
template<typename BinaryOp, typename LhsType, typename RhsType> EIGEN_DEVICE_FUNC const _LhsNested& Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs () const inline
Returns
the left hand side nested expression
Definition at line 132 of file CwiseBinaryOp.h.
Referenced by Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::extract(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::extractScalarFactor(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::extractScalarFactor(), Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::run(), and Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run().
rhs()
template<typename BinaryOp, typename LhsType, typename RhsType> EIGEN_DEVICE_FUNC const _RhsNested& Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs () const inline
Returns
the right hand side nested expression
Definition at line 135 of file CwiseBinaryOp.h.
Referenced by Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::extract(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::extractScalarFactor(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::extractScalarFactor(), Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::run(), and Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run().
rows()
template<typename BinaryOp, typename LhsType, typename RhsType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows () const inline
Definition at line 114 of file CwiseBinaryOp.h.
References Eigen::Dynamic.
Field Documentation
m_functor
template<typename BinaryOp, typename LhsType, typename RhsType> const BinaryOp Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_functor protected
Definition at line 143 of file CwiseBinaryOp.h.
m_lhs
template<typename BinaryOp, typename LhsType, typename RhsType> LhsNested Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_lhs protected
Definition at line 141 of file CwiseBinaryOp.h.
m_rhs
template<typename BinaryOp, typename LhsType, typename RhsType> RhsNested Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_rhs protected
Definition at line 142 of file CwiseBinaryOp.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/CwiseBinaryOp.h