pairinteraction: Eigen::Transform< _Scalar, _Dim, _Mode, _Options > Class Template Reference
Eigen::Transform< _Scalar, _Dim, _Mode, _Options > Class Template Reference
Geometry » Reference » Geometry_Module
Represents an homogeneous transformation in a N dimensional space.
#include <ForwardDeclarations.h>
Public Types
enum { TransformTimeDiagonalMode = ((Mode==int(Isometry))?Affine:int(Mode)) }
typedef _Scalar Scalar
typedef Eigen::Index StorageIndex
typedef Eigen::Index Index
typedef internal::make_proper_matrix_type< Scalar, Rows, HDim, Options >::type MatrixType
typedef const MatrixType ConstMatrixType
typedef Matrix< Scalar, Dim, Dim, Options > LinearMatrixType
typedef Block< MatrixType, Dim, Dim, int(Mode)==(AffineCompact) &&(Options &RowMajor)==0 > LinearPart
typedef const Block< ConstMatrixType, Dim, Dim, int(Mode)==(AffineCompact) &&(Options &RowMajor)==0 > ConstLinearPart
typedef internal::conditional< int(Mode)==int(AffineCompact), MatrixType &, Block< MatrixType, Dim, HDim > >::type AffinePart
typedef internal::conditional< int(Mode)==int(AffineCompact), const MatrixType &, const Block< const MatrixType, Dim, HDim > >::type ConstAffinePart
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Block< MatrixType, Dim, 1,!(internal::traits< MatrixType >::Flags &RowMajorBit)> TranslationPart
typedef const Block< ConstMatrixType, Dim, 1,!(internal::traits< MatrixType >::Flags &RowMajorBit)> ConstTranslationPart
typedef Translation< Scalar, Dim > TranslationType
typedef Transform< Scalar, Dim, TransformTimeDiagonalMode > TransformTimeDiagonalReturnType
typedef internal::transform_take_affine_part< Transform > take_affine_part
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (_Scalar, _Dim==Dynamic ? Dynamic :(_Dim+1) *(_Dim+1)) enum
EIGEN_DEVICE_FUNC Transform ()
EIGEN_DEVICE_FUNC Transform (const Transform &other)
EIGEN_DEVICE_FUNC Transform (const TranslationType &t)
EIGEN_DEVICE_FUNC Transform (const UniformScaling< Scalar > &s)
template<typename Derived >
EIGEN_DEVICE_FUNC Transform (const RotationBase< Derived, Dim > &r)
EIGEN_DEVICE_FUNC Transform & operator= (const Transform &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & operator= (const EigenBase< OtherDerived > &other)
template<int OtherOptions>
EIGEN_DEVICE_FUNC Transform (const Transform< Scalar, Dim, Mode, OtherOptions > &other)
template<int OtherMode, int OtherOptions>
EIGEN_DEVICE_FUNC Transform (const Transform< Scalar, Dim, OtherMode, OtherOptions > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & operator= (const ReturnByValue< OtherDerived > &other)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const MatrixType & matrix () const
EIGEN_DEVICE_FUNC MatrixType & matrix ()
EIGEN_DEVICE_FUNC ConstLinearPart linear () const
EIGEN_DEVICE_FUNC LinearPart linear ()
EIGEN_DEVICE_FUNC ConstAffinePart affine () const
EIGEN_DEVICE_FUNC AffinePart affine ()
EIGEN_DEVICE_FUNC ConstTranslationPart translation () const
EIGEN_DEVICE_FUNC TranslationPart translation ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const internal::transform_right_product_impl< Transform, OtherDerived >::ResultType operator* (const EigenBase< OtherDerived > &other) const
template<typename DiagonalDerived >
EIGEN_DEVICE_FUNC const TransformTimeDiagonalReturnType operator* (const DiagonalBase< DiagonalDerived > &b) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & operator*= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const Transform operator* (const Transform &other) const
template<int OtherMode, int OtherOptions>
EIGEN_DEVICE_FUNC internal::transform_transform_product_impl< Transform, Transform< Scalar, Dim, OtherMode, OtherOptions > >::ResultType operator* (const Transform< Scalar, Dim, OtherMode, OtherOptions > &other) const
EIGEN_DEVICE_FUNC void setIdentity ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & scale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & prescale (const MatrixBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC Transform & scale (const Scalar &s)
EIGEN_DEVICE_FUNC Transform & prescale (const Scalar &s)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & translate (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform & pretranslate (const MatrixBase< OtherDerived > &other)
template<typename RotationType >
EIGEN_DEVICE_FUNC Transform & rotate (const RotationType &rotation)
template<typename RotationType >
EIGEN_DEVICE_FUNC Transform & prerotate (const RotationType &rotation)
EIGEN_DEVICE_FUNC Transform & shear (const Scalar &sx, const Scalar &sy)
EIGEN_DEVICE_FUNC Transform & preshear (const Scalar &sx, const Scalar &sy)
EIGEN_DEVICE_FUNC Transform & operator= (const TranslationType &t)
EIGEN_DEVICE_FUNC Transform & operator*= (const TranslationType &t)
EIGEN_DEVICE_FUNC Transform operator* (const TranslationType &t) const
EIGEN_DEVICE_FUNC Transform & operator= (const UniformScaling< Scalar > &t)
EIGEN_DEVICE_FUNC Transform & operator*= (const UniformScaling< Scalar > &s)
EIGEN_DEVICE_FUNC TransformTimeDiagonalReturnType operator* (const UniformScaling< Scalar > &s) const
EIGEN_DEVICE_FUNC Transform & operator*= (const DiagonalMatrix< Scalar, Dim > &s)
template<typename Derived >
EIGEN_DEVICE_FUNC Transform & operator= (const RotationBase< Derived, Dim > &r)
template<typename Derived >
EIGEN_DEVICE_FUNC Transform & operator*= (const RotationBase< Derived, Dim > &r)
template<typename Derived >
EIGEN_DEVICE_FUNC Transform operator* (const RotationBase< Derived, Dim > &r) const
EIGEN_DEVICE_FUNC const LinearMatrixType rotation () const
template<typename RotationMatrixType , typename ScalingMatrixType >
EIGEN_DEVICE_FUNC void computeRotationScaling (RotationMatrixType *rotation, ScalingMatrixType *scaling) const
template<typename ScalingMatrixType , typename RotationMatrixType >
EIGEN_DEVICE_FUNC void computeScalingRotation (ScalingMatrixType *scaling, RotationMatrixType *rotation) const
template<typename PositionDerived , typename OrientationType , typename ScaleDerived >
EIGEN_DEVICE_FUNC Transform & fromPositionOrientationScale (const MatrixBase< PositionDerived > &position, const OrientationType &orientation, const MatrixBase< ScaleDerived > &scale)
EIGEN_DEVICE_FUNC Transform inverse (TransformTraits traits=(TransformTraits) Mode) const
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC Scalar * data ()
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< Transform, Transform< NewScalarType, Dim, Mode, Options > >::type cast () const
template<typename OtherScalarType >
EIGEN_DEVICE_FUNC Transform (const Transform< OtherScalarType, Dim, Mode, Options > &other)
EIGEN_DEVICE_FUNC bool isApprox (const Transform &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC void makeAffine ()
EIGEN_DEVICE_FUNC Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim, Dim > linearExt ()
EIGEN_DEVICE_FUNC const Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim, Dim > linearExt () const
EIGEN_DEVICE_FUNC Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim, 1 > translationExt ()
EIGEN_DEVICE_FUNC const Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim, 1 > translationExt () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & scale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & prescale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & translate (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & pretranslate (const MatrixBase< OtherDerived > &other)
template<typename RotationType >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & rotate (const RotationType &rotation)
template<typename RotationType >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & prerotate (const RotationType &rotation)
template<typename Derived >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & operator= (const RotationBase< Derived, Dim > &r)
template<typename Derived>
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > operator* (const RotationBase< Derived, Dim > &r) const
template<typename PositionDerived , typename OrientationType , typename ScaleDerived >
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & fromPositionOrientationScale (const MatrixBase< PositionDerived > &position, const OrientationType &orientation, const MatrixBase< ScaleDerived > &scale)
Static Public Member Functions
static EIGEN_DEVICE_FUNC const Transform Identity ()
Returns an identity transformation.
Static Protected Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void check_template_params ()
Protected Attributes
MatrixType m_matrix
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const internal::transform_left_product_impl< OtherDerived, Mode, Options, _Dim, _Dim+1 >::ResultType operator* (const EigenBase< OtherDerived > &a, const Transform &b)
template<typename DiagonalDerived >
EIGEN_DEVICE_FUNC friend TransformTimeDiagonalReturnType operator* (const DiagonalBase< DiagonalDerived > &a, const Transform &b)
Detailed Description
template<typename _Scalar, int _Dim, int _Mode, int _Options>
class Eigen::Transform< _Scalar, _Dim, _Mode, _Options >
Represents an homogeneous transformation in a N dimensional space.
Template Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_Dim the dimension of the space
_Mode the type of the transformation. Can be:
Affine: the transformation is stored as a (Dim+1)^2 matrix, where the last row is assumed to be [0 ... 0 1].
AffineCompact: the transformation is stored as a (Dim)x(Dim+1) matrix.
Projective: the transformation is stored as a (Dim+1)^2 matrix without any assumption.
_Options has the same meaning as in class Matrix. It allows to specify DontAlign and/or RowMajor. These Options are passed directly to the underlying matrix type.
The homography is internally represented and stored by a matrix which is available through the matrix() method. To understand the behavior of this class you have to think a Transform object as its internal matrix representation. The chosen convention is right multiply:
v' = T * v
Therefore, an affine transformation matrix M is shaped like this:
\(\left(\begin{array}{cc} linear & translation\\ 0 ... 0 & 1 \end{array} \right) \)
Note that for a projective transformation the last row can be anything, and then the interpretation of different parts might be sightly different.
However, unlike a plain matrix, the Transform class provides many features simplifying both its assembly and usage. In particular, it can be composed with any other transformations (Transform,Translation,RotationBase,DiagonalMatrix) and can be directly used to transform implicit homogeneous vectors. All these operations are handled via the operator*. For the composition of transformations, its principle consists to first convert the right/left hand sides of the product to a compatible (Dim+1)^2 matrix and then perform a pure matrix product. Of course, internally, operator* tries to perform the minimal number of operations according to the nature of each terms. Likewise, when applying the transform to points, the latters are automatically promoted to homogeneous vectors before doing the matrix product. The conventions to homogeneous representations are performed as follow:
Translation t (Dim)x(1): \(\left(\begin{array}{cc} I & t \\ 0\,...\,0 & 1 \end{array} \right) \)
Rotation R (Dim)x(Dim): \(\left(\begin{array}{cc} R & 0\\ 0\,...\,0 & 1 \end{array} \right) \)
Scaling DiagonalMatrix S (Dim)x(Dim): \(\left(\begin{array}{cc} S & 0\\ 0\,...\,0 & 1 \end{array} \right) \)
Column point v (Dim)x(1): \(\left(\begin{array}{c} v\\ 1 \end{array} \right) \)
Set of column points V1...Vn (Dim)x(n): \(\left(\begin{array}{ccc} v_1 & ... & v_n\\ 1 & ... & 1 \end{array} \right) \)
The concatenation of a Transform object with any kind of other transformation always returns a Transform object.
A little exception to the "as pure matrix product" rule is the case of the transformation of non homogeneous vectors by an affine transformation. In that case the last matrix row can be ignored, and the product returns non homogeneous vectors.
Since, for instance, a Dim x Dim matrix is interpreted as a linear transformation, it is not possible to directly transform Dim vectors stored in a Dim x Dim matrix. The solution is either to use a Dim x Dynamic matrix or explicitly request a vector transformation by making the vector homogeneous:
m' = T * m.colwise().homogeneous();
Note that there is zero overhead.
Conversion methods from/to Qt's QMatrix and QTransform are available if the preprocessor token EIGEN_QT_SUPPORT is defined.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_TRANSFORM_PLUGIN.
See also
class Matrix, class Quaternion
Definition at line 274 of file ForwardDeclarations.h.
Member Typedef Documentation
AffinePart
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef internal::conditional<int(Mode)==int(AffineCompact), MatrixType&, Block<MatrixType,Dim,HDim> >::type Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::AffinePart
type of read/write reference to the affine part of the transformation
Definition at line 229 of file Transform.h.
ConstAffinePart
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef internal::conditional<int(Mode)==int(AffineCompact), const MatrixType&, const Block<const MatrixType,Dim,HDim> >::type Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::ConstAffinePart
type of read reference to the affine part of the transformation
Definition at line 233 of file Transform.h.
ConstLinearPart
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef const Block<ConstMatrixType,Dim,Dim,int(Mode)==(AffineCompact) && (Options&RowMajor)==0> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::ConstLinearPart
type of read reference to the linear part of the transformation
Definition at line 225 of file Transform.h.
ConstMatrixType
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef const MatrixType Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::ConstMatrixType
constified MatrixType
Definition at line 219 of file Transform.h.
ConstTranslationPart
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef const Block<ConstMatrixType,Dim,1,!(internal::traits<MatrixType>::Flags & RowMajorBit)> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::ConstTranslationPart
type of a read reference to the translation part of the rotation
Definition at line 239 of file Transform.h.
Index
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Eigen::Index Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Index
Deprecated:
since Eigen 3.3
Definition at line 215 of file Transform.h.
LinearMatrixType
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Matrix<Scalar,Dim,Dim,Options> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::LinearMatrixType
type of the matrix used to represent the linear part of the transformation
Definition at line 221 of file Transform.h.
LinearPart
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Block<MatrixType,Dim,Dim,int(Mode)==(AffineCompact) && (Options&RowMajor)==0> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::LinearPart
type of read/write reference to the linear part of the transformation
Definition at line 223 of file Transform.h.
MatrixType
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef internal::make_proper_matrix_type<Scalar,Rows,HDim,Options>::type Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::MatrixType
type of the matrix used to represent the transformation
Definition at line 217 of file Transform.h.
Scalar
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef _Scalar Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Scalar
the scalar type of the coefficients
Definition at line 211 of file Transform.h.
StorageIndex
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Eigen::Index Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::StorageIndex
Definition at line 214 of file Transform.h.
take_affine_part
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef internal::transform_take_affine_part<Transform> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::take_affine_part
Definition at line 288 of file Transform.h.
TransformTimeDiagonalReturnType
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Transform<Scalar,Dim,TransformTimeDiagonalMode> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::TransformTimeDiagonalReturnType
The return type of the product between a diagonal matrix and a transform
Definition at line 246 of file Transform.h.
TranslationPart
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Block<MatrixType,Dim,1,!(internal::traits<MatrixType>::Flags & RowMajorBit)> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::TranslationPart
type of a read/write reference to the translation part of the rotation
Definition at line 237 of file Transform.h.
TranslationType
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Translation<Scalar,Dim> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::TranslationType
corresponding translation type
Definition at line 241 of file Transform.h.
VectorType
template<typename _Scalar, int _Dim, int _Mode, int _Options> typedef Matrix<Scalar,Dim,1> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::VectorType
type of a vector
Definition at line 235 of file Transform.h.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int _Dim, int _Mode, int _Options> anonymous enum
Enumerator
TransformTimeDiagonalMode
Definition at line 244 of file Transform.h.
Constructor & Destructor Documentation
Transform() [1/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform () inline
Default constructor without initialization of the meaningful coefficients. If Mode==Affine, then the last row is set to [0 ... 0 1]
Definition at line 256 of file Transform.h.
Transform() [2/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const Transform< _Scalar, _Dim, _Mode, _Options > & other) inline
Definition at line 262 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::m_matrix.
Transform() [3/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const TranslationType & t) inline explicit
Definition at line 268 of file Transform.h.
Transform() [4/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const UniformScaling< Scalar > & s) inline explicit
Definition at line 273 of file Transform.h.
References s.
Transform() [5/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename Derived > EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const RotationBase< Derived, Dim > & r) inline explicit
Definition at line 279 of file Transform.h.
Transform() [6/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const EigenBase< OtherDerived > & other) inline explicit
Constructs and initializes a transformation from a Dim^2 or a (Dim+1)^2 matrix.
Definition at line 292 of file Transform.h.
References Eigen::EigenBase< Derived >::derived(), EIGEN_STATIC_ASSERT, and Eigen::TensorSycl::run().
Transform() [7/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const Transform< Scalar, Dim, Mode, OtherOptions > & other) inline
Definition at line 313 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
Transform() [8/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<int OtherMode, int OtherOptions> EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const Transform< Scalar, Dim, OtherMode, OtherOptions > & other) inline
Definition at line 321 of file Transform.h.
References Eigen::Affine, Eigen::AffineCompact, EIGEN_IMPLIES, EIGEN_STATIC_ASSERT, int(), Eigen::Isometry, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Eigen::internal::transform_traits< Transform >::Mode, Eigen::Projective, Eigen::TensorSycl::run(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Transform() [9/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const ReturnByValue< OtherDerived > & other) inline
Definition at line 362 of file Transform.h.
References Eigen::ReturnByValue< Derived >::evalTo().
Transform() [10/10]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherScalarType > EIGEN_DEVICE_FUNC Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform (const Transform< OtherScalarType, Dim, Mode, Options > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 637 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
Member Function Documentation
affine() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC ConstAffinePart Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::affine () const inline
Returns
a read-only expression of the Dim x HDim affine part of the transformation
Definition at line 405 of file Transform.h.
References Eigen::TensorSycl::run().
Referenced by Eigen::internal::take_matrix_for_product< Transform< Scalar, Dim, Mode, Options > >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), and Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >::run().
affine() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC AffinePart Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::affine () inline
Returns
a writable expression of the Dim x HDim affine part of the transformation
Definition at line 407 of file Transform.h.
References Eigen::TensorSycl::run().
cast()
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<Transform,Transform<NewScalarType,Dim,Mode,Options> >::type Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 632 of file Transform.h.
check_template_params()
template<typename _Scalar, int _Dim, int _Mode, int _Options> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::check_template_params () inline static protected
Definition at line 690 of file Transform.h.
References Eigen::DontAlign, EIGEN_STATIC_ASSERT, and Eigen::RowMajor.
cols()
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Index Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cols (void) const inline
Definition at line 385 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::cols().
computeRotationScaling()
template<typename Scalar , int Dim, int Mode, int Options> template<typename RotationMatrixType , typename ScalingMatrixType > EIGEN_DEVICE_FUNC void Eigen::Transform< Scalar, Dim, Mode, Options >::computeRotationScaling (RotationMatrixType * rotation, ScalingMatrixType * scaling) const
decomposes the linear part of the transformation as a product rotation x scaling, the scaling being not necessarily positive.
If either pointer is zero, the corresponding computation is skipped.
See also
computeScalingRotation(), rotation(), class SVD
Definition at line 1079 of file Transform.h.
References Eigen::ComputeFullU, Eigen::ComputeFullV, determinant(), m, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixU(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::singularValues(), svd(), and x.
computeScalingRotation()
template<typename Scalar , int Dim, int Mode, int Options> template<typename ScalingMatrixType , typename RotationMatrixType > EIGEN_DEVICE_FUNC void Eigen::Transform< Scalar, Dim, Mode, Options >::computeScalingRotation (ScalingMatrixType * scaling, RotationMatrixType * rotation) const
decomposes the linear part of the transformation as a product scaling x rotation, the scaling being not necessarily positive.
If either pointer is zero, the corresponding computation is skipped.
See also
computeRotationScaling(), rotation(), class SVD
Definition at line 1108 of file Transform.h.
References Eigen::ComputeFullU, Eigen::ComputeFullV, determinant(), m, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixU(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::singularValues(), svd(), and x.
data() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC const Scalar* Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data () const inline
Returns
a const pointer to the column major internal matrix
Definition at line 622 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::data().
data() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Scalar* Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data () inline
Returns
a non-const pointer to the column major internal matrix
Definition at line 624 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::data().
EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE()
template<typename _Scalar, int _Dim, int _Mode, int _Options> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (_Scalar , _Dim = =Dynamic ? Dynamic : (_Dim+1)*(_Dim+1)) inline
< space dimension in which the transformation holds
< size of a respective homogeneous vector
Definition at line 204 of file Transform.h.
References Eigen::AffineCompact, Eigen::internal::transform_traits< Transform >::Dim, Eigen::internal::transform_traits< Transform >::HDim, int(), and Eigen::internal::transform_traits< Transform >::Mode.
fromPositionOrientationScale() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename PositionDerived , typename OrientationType , typename ScaleDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale (const MatrixBase< PositionDerived > & position, const OrientationType & orientation, const MatrixBase< ScaleDerived > & scale)
fromPositionOrientationScale() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename PositionDerived , typename OrientationType , typename ScaleDerived > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale (const MatrixBase< PositionDerived > & position, const OrientationType & orientation, const MatrixBase< ScaleDerived > & scale)
Convenient method to set *this from a position, orientation and scale of a 3D object.
Definition at line 1130 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal().
Identity()
template<typename _Scalar, int _Dim, int _Mode, int _Options> static EIGEN_DEVICE_FUNC const Transform Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Identity () inline static
Returns an identity transformation.
Todo:
In the future this function should be returning a Transform expression.
Definition at line 539 of file Transform.h.
References s, and scale.
inverse()
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > Eigen::Transform< Scalar, Dim, Mode, Options >::inverse (TransformTraits hint = (TransformTraits)Mode) const inline
Returns
the inverse transformation according to some given knowledge on *this.
Parameters
hint allows to optimize the inversion process when the transformation is known to be not a general transformation (optional). The possible values are:
Projective if the transformation is not necessarily affine, i.e., if the last row is not guaranteed to be [0 ... 0 1]
Affine if the last row can be assumed to be [0 ... 0 1]
Isometry if the transformation is only a concatenations of translations and rotations. The default is the template class parameter Mode.
Warning
unless traits is always set to NoShear or NoScaling, this function requires the generic inverse method of MatrixBase defined in the LU module. If you forget to include this module, then you will get hard to debug linking errors.
See also
MatrixBase::inverse()
Definition at line 1202 of file Transform.h.
References Eigen::Affine, eigen_assert, Eigen::Isometry, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::makeAffine(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Eigen::Projective, res, and Eigen::internal::projective_transform_inverse< TransformType, Mode >::run().
isApprox()
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC bool Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::isApprox (const Transform< _Scalar, _Dim, _Mode, _Options > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
Definition at line 647 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::m_matrix.
linear() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC ConstLinearPart Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear () const inline
Returns
a read-only expression of the linear part of the transformation
Definition at line 400 of file Transform.h.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::internal::rotation_base_generic_product_selector< RotationDerived, DiagonalMatrix< Scalar, Dim, MaxDim >, false >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
linear() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC LinearPart Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear () inline
Returns
a writable expression of the linear part of the transformation
Definition at line 402 of file Transform.h.
linearExt() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,Dim> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linearExt () inline
Definition at line 661 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*().
linearExt() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC const Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,Dim> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linearExt () const inline
Definition at line 667 of file Transform.h.
makeAffine()
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC void Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::makeAffine () inline
Sets the last row to [0 ... 0 1]
Definition at line 652 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), and Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run().
matrix() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC const MatrixType& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix () const inline
Returns
a read-only expression of the transformation matrix
Definition at line 395 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::internal::take_matrix_for_product< Transform< Scalar, Dim, Projective, Options > >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_construct_from_matrix< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, true >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, AffineCompact, LhsOptions >, Transform< Scalar, Dim, Projective, RhsOptions >, true >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, Projective, LhsOptions >, Transform< Scalar, Dim, AffineCompact, RhsOptions >, true >::run(), test_openglsupport(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
matrix() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC MatrixType& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix () inline
Returns
a writable expression of the transformation matrix
Definition at line 397 of file Transform.h.
operator()() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Scalar Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator() (Index row, Index col) const inline
shortcut for m_matrix(row,col);
See also
MatrixBase::operator(Index,Index) const
Definition at line 389 of file Transform.h.
operator()() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Scalar& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator() (Index row, Index col) inline
shortcut for m_matrix(row,col);
See also
MatrixBase::operator(Index,Index)
Definition at line 392 of file Transform.h.
operator*() [1/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const internal::transform_right_product_impl<Transform, OtherDerived>::ResultType Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const EigenBase< OtherDerived > & other) const inline
Returns
an expression of the product between the transform *this and a matrix expression other.
The right-hand-side other can be either:
an homogeneous vector of size Dim+1,
a set of homogeneous vectors of size Dim+1 x N,
a transformation matrix of size Dim+1 x Dim+1.
Moreover, if *this represents an affine transformation (i.e., Mode!=Projective), then other can also be:
a point of size Dim (computes:
this->linear() * other + this->translation()
),
a set of N points as a Dim x N matrix (computes:
(this->linear() * other).colwise() + this->translation()
),
In all cases, the return type is a matrix or vector of same sizes as the right-hand-side other.
If you want to interpret other as a linear or affine transformation, then first convert it to a Transform<> type, or do your own cooking.
Finally, if you want to apply Affine transformations to vectors, then explicitly apply the linear part only:
Affine3f A;
Vector3f v1, v2;
v2 = A.linear() * v1;
Definition at line 441 of file Transform.h.
References Eigen::EigenBase< Derived >::derived(), and Eigen::TensorSycl::run().
operator*() [2/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename DiagonalDerived > EIGEN_DEVICE_FUNC const TransformTimeDiagonalReturnType Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const DiagonalBase< DiagonalDerived > & b) const inline
Returns
The product expression of a transform a times a diagonal matrix b
The rhs diagonal matrix is interpreted as an affine scaling transformation. The product results in a Transform of the same type (mode) as the lhs only if the lhs mode is no isometry. In that case, the returned transform is an affinity.
Definition at line 464 of file Transform.h.
References b, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linearExt(), and res.
operator*() [3/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC const Transform Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const Transform< _Scalar, _Dim, _Mode, _Options > & other) const inline
Concatenates two transformations
Definition at line 493 of file Transform.h.
References Eigen::TensorSycl::run().
operator*() [4/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<int OtherMode, int OtherOptions> EIGEN_DEVICE_FUNC internal::transform_transform_product_impl<Transform,Transform<Scalar,Dim,OtherMode,OtherOptions> >::ResultType Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const Transform< Scalar, Dim, OtherMode, OtherOptions > & other) const inline
Concatenates two different transformations
Definition at line 526 of file Transform.h.
References Eigen::TensorSycl::run().
operator*() [5/8]
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > Eigen::Transform< Scalar, Dim, Mode, Options >::operator* (const TranslationType & t) const inline
Definition at line 1010 of file Transform.h.
References res, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), and Eigen::Translation< _Scalar, _Dim >::vector().
operator*() [6/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC TransformTimeDiagonalReturnType Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const UniformScaling< Scalar > & s) const inline
Definition at line 588 of file Transform.h.
References Eigen::UniformScaling< _Scalar >::factor(), res, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale().
operator*() [7/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename Derived > EIGEN_DEVICE_FUNC Transform Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const RotationBase< Derived, Dim > & r) const inline
operator*() [8/8]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename Derived> EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator* (const RotationBase< Derived, Dim > & r) const inline
Definition at line 1038 of file Transform.h.
References Eigen::RotationBase< Derived, _Dim >::derived(), res, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate().
operator*=() [1/5]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*= (const EigenBase< OtherDerived > & other) inline
Definition at line 490 of file Transform.h.
operator*=() [2/5]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*= (const TranslationType & t) inline
Definition at line 577 of file Transform.h.
References Eigen::Translation< _Scalar, _Dim >::vector().
operator*=() [3/5]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*= (const UniformScaling< Scalar > & s) inline
Definition at line 585 of file Transform.h.
References Eigen::UniformScaling< _Scalar >::factor(), and scale.
operator*=() [4/5]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*= (const DiagonalMatrix< Scalar, Dim > & s) inline
Definition at line 596 of file Transform.h.
References s.
operator*=() [5/5]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename Derived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*= (const RotationBase< Derived, Dim > & r) inline
Definition at line 601 of file Transform.h.
References inverse(), Eigen::internal::transform_traits< Transform >::Mode, and Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
operator=() [1/7]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator= (const Transform< _Scalar, _Dim, _Mode, _Options > & other) inline
Definition at line 285 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::m_matrix.
operator=() [2/7]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator= (const EigenBase< OtherDerived > & other) inline
Set *this from a Dim^2 or (Dim+1)^2 matrix.
Definition at line 303 of file Transform.h.
References Eigen::EigenBase< Derived >::derived(), EIGEN_STATIC_ASSERT, and Eigen::TensorSycl::run().
operator=() [3/7]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator= (const ReturnByValue< OtherDerived > & other) inline
Definition at line 369 of file Transform.h.
References Eigen::ReturnByValue< Derived >::evalTo().
operator=() [4/7]
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::operator= (const TranslationType & t) inline
Definition at line 1001 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::setIdentity(), and Eigen::Translation< _Scalar, _Dim >::vector().
operator=() [5/7]
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::operator= (const UniformScaling< Scalar > & t) inline
Definition at line 1018 of file Transform.h.
References Eigen::UniformScaling< _Scalar >::factor(), and Eigen::PlainObjectBase< Derived >::setZero().
operator=() [6/7]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename Derived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator= (const RotationBase< Derived, Dim > & r) inline
operator=() [7/7]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename Derived > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator= (const RotationBase< Derived, Dim > & r) inline
Definition at line 1028 of file Transform.h.
prerotate() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename RotationType > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::prerotate (const RotationType & rotation) inline
prerotate() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename RotationType > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::prerotate (const RotationType & rotation)
Applies on the left the rotation represented by the rotation rotation to *this and returns a reference to *this.
See rotate() for further details.
See also
rotate()
Definition at line 958 of file Transform.h.
prescale() [1/3]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::prescale (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::UniformScaling< _Scalar >::operator*().
prescale() [2/3]
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::prescale (const Scalar & s) inline
Applies on the left a uniform scale of a factor c to *this and returns a reference to *this.
See also
scale(Scalar)
Definition at line 884 of file Transform.h.
References EIGEN_STATIC_ASSERT, and Eigen::Isometry.
prescale() [3/3]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::prescale (const MatrixBase< OtherDerived > & other)
Applies on the left the non uniform scale transformation represented by the vector other to *this and returns a reference to *this.
See also
scale()
Definition at line 871 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal(), Eigen::internal::transform_traits< Transform >::Dim, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Isometry.
preshear()
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::preshear (const Scalar & sx, const Scalar & sy)
Applies on the left the shear transformation represented by the vector other to *this and returns a reference to *this.
Warning
2D only.
See also
shear()
Definition at line 988 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim, EIGEN_STATIC_ASSERT, and Eigen::Isometry.
pretranslate() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::pretranslate (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::Translation< _Scalar, _Dim >::operator*().
pretranslate() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::pretranslate (const MatrixBase< OtherDerived > & other)
Applies on the left the translation matrix represented by the vector other to *this and returns a reference to *this.
See also
translate()
Definition at line 912 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Projective.
rotate() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename RotationType > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate (const RotationType & rotation) inline
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*().
rotate() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename RotationType > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate (const RotationType & rotation)
Applies on the right the rotation represented by the rotation rotation to *this and returns a reference to *this.
The template parameter RotationType is the type of the rotation which must be known by internal::toRotationMatrix<>.
Natively supported types includes:
any scalar (2D),
a Dim x Dim matrix expression,
a Quaternion (3D),
a AngleAxis (3D)
This mechanism is easily extendable to support user types such as Euler angles, or a pair of Quaternion for 4D rotations.
See also
rotate(Scalar), class Quaternion, class AngleAxis, prerotate(RotationType)
Definition at line 942 of file Transform.h.
rotation()
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC const Transform< Scalar, Dim, Mode, Options >::LinearMatrixType Eigen::Transform< Scalar, Dim, Mode, Options >::rotation () const
Returns
the rotation part of the transformation
See also
computeRotationScaling(), computeScalingRotation(), class SVD
Definition at line 1058 of file Transform.h.
rows()
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Index Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rows (void) const inline
Definition at line 384 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::cols(), int(), Eigen::internal::transform_traits< Transform >::Mode, and Eigen::Projective.
scale() [1/3]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*().
scale() [2/3]
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::scale (const Scalar & s) inline
Applies on the right a uniform scale of a factor c to *this and returns a reference to *this.
See also
prescale(Scalar)
Definition at line 857 of file Transform.h.
References EIGEN_STATIC_ASSERT, Eigen::Isometry, and s.
scale() [3/3]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale (const MatrixBase< OtherDerived > & other)
Applies on the right the non uniform scale transformation represented by the vector other to *this and returns a reference to *this.
See also
prescale()
Definition at line 844 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal(), Eigen::internal::transform_traits< Transform >::Dim, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Isometry.
setIdentity()
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC void Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::setIdentity () inline
See also
MatrixBase::setIdentity()
Definition at line 533 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=().
shear()
template<typename Scalar , int Dim, int Mode, int Options> EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::shear (const Scalar & sx, const Scalar & sy)
Applies on the right the shear transformation represented by the vector other to *this and returns a reference to *this.
Warning
2D only.
See also
preshear()
Definition at line 972 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim, EIGEN_STATIC_ASSERT, and Eigen::Isometry.
translate() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*().
translate() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate (const MatrixBase< OtherDerived > & other)
Applies on the right the translation matrix represented by the vector other to *this and returns a reference to *this.
See also
pretranslate()
Definition at line 898 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim, and EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
translation() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC ConstTranslationPart Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation () const inline
Returns
a read-only expression of the translation vector of the transformation
Definition at line 410 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::transform(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
translation() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC TranslationPart Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation () inline
Returns
a writable expression of the translation vector of the transformation
Definition at line 412 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim, and EIGEN_STRONG_INLINE.
translationExt() [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,1> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translationExt () inline
Definition at line 674 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim.
translationExt() [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> EIGEN_DEVICE_FUNC const Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,1> Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translationExt () const inline
Definition at line 680 of file Transform.h.
References Eigen::internal::transform_traits< Transform >::Dim.
Friends And Related Function Documentation
operator* [1/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename OtherDerived > EIGEN_DEVICE_FUNC const internal::transform_left_product_impl<OtherDerived,Mode,Options,_Dim,_Dim+1>::ResultType operator* (const EigenBase< OtherDerived > & a, const Transform< _Scalar, _Dim, _Mode, _Options > & b) friend
Returns
the product expression of a transformation matrix a times a transform b
The left hand side other can be either:
a linear transformation matrix of size Dim x Dim,
an affine transformation matrix of size Dim x Dim+1,
a general transformation matrix of size Dim+1 x Dim+1.
Definition at line 453 of file Transform.h.
operator* [2/2]
template<typename _Scalar, int _Dim, int _Mode, int _Options> template<typename DiagonalDerived > EIGEN_DEVICE_FUNC friend TransformTimeDiagonalReturnType operator* (const DiagonalBase< DiagonalDerived > & a, const Transform< _Scalar, _Dim, _Mode, _Options > & b) friend
Returns
The product expression of a diagonal matrix a times a transform b
The lhs diagonal matrix is interpreted as an affine scaling transformation. The product results in a Transform of the same type (mode) as the lhs only if the lhs mode is no isometry. In that case, the returned transform is an affinity.
Definition at line 479 of file Transform.h.
Field Documentation
m_matrix
template<typename _Scalar, int _Dim, int _Mode, int _Options> MatrixType Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::m_matrix protected
Definition at line 250 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::isApprox(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/Eigen/src/Geometry/Transform.h