pairinteraction: MandelbrotThread Class Reference
MandelbrotThread Class Reference
#include <mandelbrot.h>
Public Member Functions
MandelbrotThread (MandelbrotWidget *w, int i)
void run ()
template<typename Real >
void render (int img_width, int img_height)
Friends
class MandelbrotWidget
Detailed Description
Definition at line 20 of file mandelbrot.h.
Constructor & Destructor Documentation
MandelbrotThread()
MandelbrotThread::MandelbrotThread (MandelbrotWidget * w, int i) inline
Definition at line 29 of file mandelbrot.h.
References render(), and run().
Referenced by MandelbrotWidget::MandelbrotWidget().
Member Function Documentation
render()
template<typename Real > void MandelbrotThread::render (int img_width, int img_height)
Definition at line 31 of file mandelbrot.cpp.
References eval(), i, ITERATE, j, x, and y.
Referenced by MandelbrotThread().
run()
void MandelbrotThread::run ()
Definition at line 111 of file mandelbrot.cpp.
References e().
Referenced by MandelbrotThread().
Friends And Related Function Documentation
MandelbrotWidget
friend class MandelbrotWidget friend
Definition at line 22 of file mandelbrot.h.
The documentation for this class was generated from the following files:
/travis/libpairinteraction/eigen/demos/mandelbrot/mandelbrot.h
/travis/libpairinteraction/eigen/demos/mandelbrot/mandelbrot.cpp