pairinteraction: /travis/libpairinteraction/eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h File Reference
CommonCwiseBinaryOps.h File Reference
Functions
template<typename CustomBinaryOp , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp< CustomBinaryOp, const Derived, const OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_and_op, const Derived, const OtherDerived > operator && (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CwiseBinaryOp< internal::scalar_boolean_or_op, const Derived, const OtherDerived > operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
Function Documentation
binaryExpr()
template<typename CustomBinaryOp , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
Output:
See also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
Definition at line 43 of file CommonCwiseBinaryOps.h.
References EIGEN_MAKE_SCALAR_BINARY_OP, EIGEN_MAKE_SCALAR_BINARY_OP_ONTHERIGHT, Eigen::UniformScaling< _Scalar >::operator*(), operator/(), and product().
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::cwiseMax(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::cwiseMin(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::igamma(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::igammac(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator &&(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator!=(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator*(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator+(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator-(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator/(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator<(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator<=(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator==(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator>(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator>=(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator^(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator||(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::polygamma(), and Eigen::TensorBase< Derived, ReadOnlyAccessors >::zeta().
operator &&()
template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_and_op, const Derived, const OtherDerived> operator&& (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean and operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator||(), select()
Definition at line 91 of file CommonCwiseBinaryOps.h.
References EIGEN_STATIC_ASSERT.
operator||()
template<typename OtherDerived > EIGEN_DEVICE_FUNC const CwiseBinaryOp<internal::scalar_boolean_or_op, const Derived, const OtherDerived> operator|| (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise boolean or operator of *this and other
Warning
this operator is for expression of bool only.
Example:
Output:
See also
operator&&(), select()
Definition at line 110 of file CommonCwiseBinaryOps.h.
References EIGEN_STATIC_ASSERT.