pairinteraction: /travis/libpairinteraction/eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h File Reference
CommonCwiseUnaryOps.h File Reference
Data Structures
struct CastXpr< NewType >
Typedefs
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, const Derived &>::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, const CwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived >, const Derived &>::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived &>::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
Functions
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real ()
EIGEN_DEVICE_FUNC const ImagReturnType imag ()
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
Typedef Documentation
ConjugateReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type ConjugateReturnType
Definition at line 19 of file CommonCwiseUnaryOps.h.
ImagReturnType
typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> ImagReturnType
Definition at line 31 of file CommonCwiseUnaryOps.h.
NegativeReturnType
typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> NegativeReturnType
Definition at line 35 of file CommonCwiseUnaryOps.h.
NonConstImagReturnType
typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> NonConstImagReturnType
Definition at line 33 of file CommonCwiseUnaryOps.h.
NonConstRealReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type NonConstRealReturnType
Definition at line 29 of file CommonCwiseUnaryOps.h.
RealReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type RealReturnType
Definition at line 24 of file CommonCwiseUnaryOps.h.
Function Documentation
cast()
template<typename NewType > EIGEN_DEVICE_FUNC CastXpr<NewType>::Type cast () const
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
Definition at line 62 of file CommonCwiseUnaryOps.h.
References conjugate(), and EIGEN_DOC_UNARY_ADDONS.
Referenced by mixingtypes(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*(), Eigen::operator*(), and polynomialsolver().
conjugate()
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
Definition at line 74 of file CommonCwiseUnaryOps.h.
References EIGEN_DOC_UNARY_ADDONS.
Referenced by SystemBase< StateTwo >::addHamiltonianentry(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), cast(), Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::inverse(), product(), product_extra(), symm(), trmm(), and trmv().
imag()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
Returns
a non const expression of the imaginary part of *this.
See also
real()
Definition at line 95 of file CommonCwiseUnaryOps.h.
References EIGEN_DOC_UNARY_ADDONS, and unaryExpr().
Referenced by array_complex(), array_real(), basicStuffComplex(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::EigenSolver< CompanionMatrixType >::eigenvectors(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), householder(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::makeHouseholder(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::scalar_imag_op< Scalar >::operator()(), Eigen::internal::tensor_symmetry_value_setter< Tensor_, Symmetry_, Flags >::operator=(), packetmath_complex(), Eigen::internal::pgather< std::complex< double >, Packet2cd >(), Eigen::internal::pgather< std::complex< float >, Packet4cf >(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::EigenSolver< CompanionMatrixType >::pseudoEigenvalueMatrix(), real(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, true >::run(), Eigen::internal::trmv_selector< Mode, ColMajor >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and unaryViewExpr().
operator-()
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const inline
Returns
an expression of the opposite of *this
Definition at line 45 of file CommonCwiseUnaryOps.h.
real()
EIGEN_DEVICE_FUNC RealReturnType real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
Returns
a non const expression of the real part of *this.
See also
imag()
Definition at line 86 of file CommonCwiseUnaryOps.h.
References EIGEN_DOC_UNARY_ADDONS, and imag().
Referenced by unaryViewExpr().
unaryExpr()
template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp<CustomUnaryOp, const Derived> unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
Definition at line 121 of file CommonCwiseUnaryOps.h.
References EIGEN_DOC_UNARY_ADDONS, and unaryViewExpr().
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::abs(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::ceil(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::conjugate(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::cube(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::digamma(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::erf(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::erfc(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::exp(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::floor(), imag(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::imag(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::inverse(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::lgamma(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::log(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::log1p(), main(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator%(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator*(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator+(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator-(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator/(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::pow(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::real(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::round(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::rsqrt(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::sigmoid(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::sign(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::sqrt(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::square(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::tanh(), and Eigen::TensorBase< Derived, ReadOnlyAccessors >::TensorCwiseUnaryOp().
unaryViewExpr()
template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView<CustomViewOp, const Derived> unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See also
unaryExpr, binaryExpr class CwiseUnaryOp
Definition at line 142 of file CommonCwiseUnaryOps.h.
References EIGEN_DOC_UNARY_ADDONS, imag(), and real().
Referenced by unaryExpr().