pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/ComplexSchur_matrixT.cpp File Reference
ComplexSchur_matrixT.cpp File Reference
Functions
cout<< "Here is a random 4x4 matrix, A:"<< endl<< A<< endl<< endl;ComplexSchur< MatrixXcf > schurOfA (A, false)
Variables
MatrixXcf A = MatrixXcf::Random(4,4)
Function Documentation
schurOfA()
cout<< "Here is a random 4x4 matrix, A:" << endl << A << endl << endl;ComplexSchur<MatrixXcf> schurOfA (A , false)
Referenced by Eigen::MatrixPower< MatrixType >::compute(), Eigen::internal::matrix_sqrt_compute< MatrixType, 0 >::run(), Eigen::internal::matrix_sqrt_compute< MatrixType, 1 >::run(), and Eigen::internal::matrix_function_compute< MatrixType, 1 >::run().
Variable Documentation
A
MatrixXcf A = MatrixXcf::Random(4,4)
Definition at line 1 of file ComplexSchur_matrixT.cpp.