pairinteraction: /travis/libpairinteraction/eigen/blas/fortran/complexdots.f File Reference
complexdots.f File Reference
Functions/Subroutines
complex function cdotc (N, CX, INCX, CY, INCY)
complex function cdotu (N, CX, INCX, CY, INCY)
double complex function zdotc (N, CX, INCX, CY, INCY)
double complex function zdotu (N, CX, INCX, CY, INCY)
Function/Subroutine Documentation
cdotc()
complex function cdotc (integer N, complex, dimension(*) CX, integer INCX, complex, dimension(*) CY, integer INCY)
Definition at line 2 of file complexdots.f.
References cdotc(), and cdotcw().
cdotu()
complex function cdotu (integer N, complex, dimension(*) CX, integer INCX, complex, dimension(*) CY, integer INCY)
Definition at line 13 of file complexdots.f.
References cdotu(), and cdotuw().
zdotc()
double complex function zdotc (integer N, double complex, dimension(*) CX, integer INCX, double complex, dimension(*) CY, integer INCY)
Definition at line 24 of file complexdots.f.
References zdotc(), and zdotcw().
zdotu()
double complex function zdotu (integer N, double complex, dimension(*) CX, integer INCX, double complex, dimension(*) CY, integer INCY)
Definition at line 35 of file complexdots.f.
References zdotu(), and zdotuw().