pairinteraction: /travis/libpairinteraction/eigen/test/corners.cpp File Reference
corners.cpp File Reference
#include "main.h"
Macros
#define COMPARE_CORNER(A, B)
Functions
template<typename MatrixType >
void corners (const MatrixType &m)
template<typename MatrixType , int CRows, int CCols, int SRows, int SCols>
void corners_fixedsize ()
void test_corners ()
Macro Definition Documentation
COMPARE_CORNER
#define COMPARE_CORNER (A, B)
Value:
VERIFY_IS_EQUAL(matrix.A, matrix.B); \
  VERIFY_IS_EQUAL(const_matrix.A, const_matrix.B);
Definition at line 12 of file corners.cpp.
Referenced by corners().
Function Documentation
corners()
template<typename MatrixType > void corners (const MatrixType & m)
Definition at line 16 of file corners.cpp.
References block(), bottomLeftCorner(), bottomRightCorner(), bottomRows(), c, cols, COMPARE_CORNER, leftCols(), matrix(), middleCols(), middleRows(), rightCols(), rows, topLeftCorner(), topRightCorner(), and topRows().
corners_fixedsize()
template<typename MatrixType , int CRows, int CCols, int SRows, int SCols> void corners_fixedsize ()
Definition at line 46 of file corners.cpp.
References c, cols, matrix(), rows, and VERIFY_IS_EQUAL.
test_corners()
void test_corners ()
Definition at line 105 of file corners.cpp.
References i.