pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/Cwise_product.cpp File Reference
Cwise_product.cpp File Reference
Variables
Array33i a = Array33i::Random()
Array33i b = Array33i::Random()
Array33i c = a * b
Variable Documentation
a
Scalar * a = Array33i::Random()
Definition at line 1 of file Cwise_product.cpp.
Referenced by __attribute__(), Camera::activateGL(), mpfr::agm(), aliasing_with_resize(), areApprox(), areApproxAbs(), Eigen::internal::array_get(), array_special_functions(), Eigen::internal::assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::add_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::sub_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::mul_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::div_assign_op< DstScalar, SrcScalar >::assignPacket(), mpfr::atan2(), bandmatrix(), bdcsvd(), bench(), bench_prod(), bench_svd(), benchBasic_loop(), Eigen::betainc(), bug_127(), call_ref(), call_ref_1(), call_ref_2(), call_ref_3(), call_ref_4(), call_ref_5(), call_ref_6(), call_ref_7(), cblat3(), ceilh(), check0(), check2(), numpy::internal::check_array_sanity(), compare_bdc_jacobi(), comparisons(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::createRandomPIMatrixOfRank(), dblat3(), Eigen::SuperLU< _MatrixType >::determinant(), dontalign(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), eigensolver(), eigensolver_verify_assert(), eulerangles(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize(), Eigen::SimplicialLLT< _MatrixType, _UpLo, _Ordering >::factorize(), Eigen::SimplicialLDLT< _MatrixType, _UpLo, _Ordering >::factorize(), Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::factorize(), fixedSizeMatrixConstruction(), mpfr::fma(), mpfr::fmax(), mpfr::fmin(), mpfr::fmod(), mpfr::fms(), gemm(), gemv(), generalized_eigensolver_real(), ger(), gerc(), geru(), mpfr::mpreal::get_default_prec(), hemv(), her(), her2(), mpfr::hypot(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::initFactorization(), jacobi(), jacobisvd(), jacobisvd_verify_assert(), lines(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadLhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhs(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadLhs(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadLhsUnaligned(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhsUnaligned(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadLhsUnaligned(), mag2(), main(), Eigen::internal::manage_caching_sizes_helper(), mapQuaternion(), Eigen::half_impl::max(), Eigen::half_impl::min(), mpfr::nextabove(), mpfr::nextbelow(), mpfr::nexttoward(), non_projective_only(), Eigen::NonBlockingThreadPoolTempl< Environment >::NonBlockingThreadPoolTempl(), MakeComplexOp< Scalar >::operator()(), Eigen::internal::scalar_opposite_op< Scalar >::operator()(), Eigen::internal::scalar_cast_op< Eigen::half, float >::operator()(), Eigen::internal::abs_knowing_score< Scalar, typename scalar_score_coeff_op< Scalar >::Score_is_abs >::operator()(), Eigen::internal::scalar_cast_op< Scalar, NewType >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_UNORD >::operator()(), Eigen::internal::scalar_inverse_op< Scalar >::operator()(), Eigen::internal::scalar_square_op< Scalar >::operator()(), Eigen::internal::scalar_cube_op< Scalar >::operator()(), Eigen::internal::scalar_isnan_op< Scalar >::operator()(), Eigen::internal::scalar_isinf_op< Scalar >::operator()(), Eigen::internal::scalar_isfinite_op< Scalar >::operator()(), Eigen::internal::scalar_boolean_not_op< Scalar >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::half_impl::operator*=(), Eigen::half_impl::operator+=(), Eigen::internal::operator-(), mpfr::operator-(), Eigen::half_impl::operator-=(), mpfr::operator/(), Eigen::half_impl::operator/=(), Eigen::half::operator=(), Eigen::internal::pabs(), Eigen::internal::pabs< Packet4f >(), Eigen::internal::padd< Packet2d >(), Eigen::internal::pand< Packet2d >(), Eigen::internal::pandnot< Packet2d >(), Eigen::internal::pblend(), Eigen::internal::pbroadcast4< Packet2d >(), Eigen::internal::pbroadcast4< Packet4f >(), Eigen::internal::pbroadcast4< Packet4i >(), Eigen::internal::pcast(), Eigen::internal::pcast< Packet4f, Packet4i >(), Eigen::internal::pcast< Packet4i, Packet4f >(), Eigen::internal::pcast< Packet8f, Packet8i >(), Eigen::internal::pcast< Packet8i, Packet8f >(), Eigen::internal::pceil< Packet2d >(), Eigen::internal::pconj(), Eigen::internal::pdiv< Packet2d >(), Eigen::internal::pfirst(), Eigen::internal::pfirst< Packet2d >(), Eigen::internal::pfirst< Packet4i >(), Eigen::internal::pfloor< Packet2d >(), Eigen::internal::plset(), Eigen::internal::plset< Packet16f >(), Eigen::internal::plset< Packet2d >(), Eigen::internal::plset< Packet4d >(), Eigen::internal::plset< Packet4f >(), Eigen::internal::plset< Packet4i >(), Eigen::internal::plset< Packet8d >(), Eigen::internal::plset< Packet8f >(), Eigen::internal::pmadd(), Eigen::internal::pmax< Packet2d >(), Eigen::internal::pmin< Packet2d >(), Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pmul< Packet2d >(), Eigen::internal::pnegate(), Eigen::internal::por< Packet2d >(), Numerov::power_kernel(), Eigen::internal::predux(), Eigen::internal::predux< Packet2d >(), Eigen::internal::predux< Packet4i >(), Eigen::internal::predux_downto4(), Eigen::internal::predux_max(), Eigen::internal::predux_max< Packet2d >(), Eigen::internal::predux_min(), Eigen::internal::predux_min< Packet2d >(), Eigen::internal::predux_min< Packet4i >(), Eigen::internal::predux_mul(), Eigen::internal::predux_mul< Packet2cf >(), Eigen::internal::predux_mul< Packet2d >(), Eigen::internal::predux_mul< Packet4i >(), Eigen::internal::preduxp< Packet2d >(), Eigen::internal::prefetch< int32_t >(), Eigen::internal::preverse(), Eigen::internal::pround< Packet2d >(), Eigen::internal::pscatter< std::complex< double >, Packet1cd >(), Eigen::internal::pset1(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::pset1< Packet4i >(), Eigen::internal::pstore1< Packet16f >(), Eigen::internal::pstore1< Packet16i >(), Eigen::internal::pstore1< Packet2d >(), Eigen::internal::pstore1< Packet4d >(), Eigen::internal::pstore1< Packet8d >(), Eigen::internal::pstore1< Packet8f >(), Eigen::internal::pstore1< Packet8i >(), Eigen::internal::psub< Packet2d >(), Eigen::internal::ptranspose(), Eigen::internal::pxor< Packet2d >(), qr(), qr_invertible(), quaternion(), utils::randint(), regression_bug_654(), mpfr::remainder(), mpfr::remquo(), rotg(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::cross3_impl< Architecture::SSE, VectorLhs, VectorRhs, float, true >::run(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::not_op::run(), Eigen::internal::negation_op::run(), Eigen::internal::palign_impl< Offset, Packet2d >::run(), Eigen::internal::igammac_impl< Scalar >::run(), Eigen::internal::igamma_impl< Scalar >::run(), evaluate_defaults_action_t::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run(), Eigen::internal::betainc_impl< Scalar >::run(), sblat3(), selfadjointeigensolver(), SystemTwo::setAngle(), slerp_legacy(), StateTwo::StateTwo(), svd_verify_assert(), symm(), symv(), syr2k(), syrk(), tbsv(), test_add(), test_div(), test_evaluators(), test_misc1(), test_mul(), test_sub(), test_unalignedcount(), transform_products(), transformations(), trmm(), trmv(), trsm(), trsv(), upperbidiag(), zblat3(), and zero_sized_objects().
b
Array33i b = Array33i::Random()
Definition at line 1 of file Cwise_product.cpp.
c
Array33i c = a * b
Definition at line 2 of file Cwise_product.cpp.