pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/Cwise_array_power_array.cpp File Reference
Cwise_array_power_array.cpp File Reference
Functions
Array< double, 1, 3 > x (8, 25, 3)
Array< double, 1, 3 > e (1./3., 0.5, 2.)
Function Documentation
e()
Array<double,1,3> e (1./ 3., 0. 5, 2.)
Referenced by __attribute__(), Eigen::DynamicSGroup::add(), SystemTwo::addInteraction(), SystemOne::addInteraction(), RenderingWidget::animate(), bench(), BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE_TEMPLATE(), HamiltonianOne::build(), SystemBase< StateTwo >::buildRotator(), HamiltonianTwo::calculate(), Action_matrix_matrix_product_bis< Interface >::calculate(), Action_lu_solve< Interface >::calculate(), cblat1(), check0(), check2(), check_global_interpolation2d(), Action_axpby< Interface >::check_result(), Action_ger< Interface >::check_result(), Action_atv_product< Interface >::check_result(), Action_syr2< Interface >::check_result(), Action_symv< Interface >::check_result(), Action_axpy< Interface >::check_result(), Action_trisolve< Interface >::check_result(), Action_ata_product< Interface >::check_result(), Action_aat_product< Interface >::check_result(), Action_matrix_matrix_product< Interface >::check_result(), Action_matrix_vector_product< Interface >::check_result(), clarf(), clarfb(), clarfg(), clarft(), combine(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), chwirut2_functor::df(), rat42_functor::df(), MGH10_functor::df(), BoxBOD_functor::df(), Bennett5_functor::df(), rat43_functor::df(), eckerle4_functor::df(), Hamiltonianmatrix::diagonalize(), SystemBase< StateTwo >::diagonalize(), GpuHelper::drawVector(), GpuHelper::drawVectorBox(), Eigen::NumTraits< Real >::dummy_precision(), Eigen::NumTraits< float >::dummy_precision(), Eigen::NumTraits< double >::dummy_precision(), Eigen::NumTraits< long double >::dummy_precision(), Eigen::NumTraits< Eigen::half >::dummy_precision(), dump_table_for_subset(), efficiency_of_subset(), EIGEN_LAPACK_FUNC(), energycutoff(), eval_closed_spline2d(), eval_spline3d(), eval_spline3d_onbrks(), four_denorms(), Eigen::EulerAngles< _Scalar, _System >::FromRotation(), mpfr::mpreal::get_default_prec(), Eigen::BenchTimer::getCpuTime(), Eigen::BenchTimer::getRealTime(), hyperplane(), ilaclc(), ilaclr(), ilaslr(), Eigen::IterScaling< _MatrixType >::init(), SystemTwo::initializeInteraction(), SystemOne::initializeInteraction(), inplace(), Numerov::integrate(), lda(), linearStructure(), lines(), Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Hamiltonianmatrix::load(), main(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorageOneStep(), Eigen::internal::minimum_degree_ordering(), WignerD::operator()(), Eigen::internal::pexp< Packet4d >(), Eigen::internal::plog< Packet4f >(), Eigen::RunQueue< Work, kSize >::PopBack(), Eigen::RunQueue< Work, kSize >::PopBackHalf(), Eigen::RunQueue< Work, kSize >::PopFront(), Eigen::internal::pseudo_inverse(), Eigen::RunQueue< Work, kSize >::PushBack(), Eigen::RunQueue< Work, kSize >::PushFront(), quaternion(), MandelbrotThread::run(), benchmark_t::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, float >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, double >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, long double >::run(), sblat1(), second(), slamch(), slarf(), slarfb(), slarfg(), slarft(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep(), sparse_basic(), sparse_extra(), sparse_product(), sparse_vector(), stable_norm(), Portable_Timer::start(), Portable_Timer::stop(), svd_inf_nan(), svd_least_square(), sycl_queue(), test_matrix_exponential(), test_matrix_power(), test_multithread_contraction(), test_precision< double >(), Eigen::test_precision< double >(), test_precision< float >(), Eigen::test_precision< float >(), Eigen::test_precision< long double >(), Eigen::test_precision< Real >(), testMatrixType(), TreeTest< Dim >::testMinimize2(), testNistHahn1(), triangular_square(), verify_euler_ranged(), and no_defect::what().
x()
Array<double,1,3> x (8 , 25 , 3)