pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/Cwise_arg.cpp File Reference
Cwise_arg.cpp File Reference
Variables
ArrayXcf v = ArrayXcf::Random(3)
Variable Documentation
v
ArrayXcf v = ArrayXcf::Random(3)
Definition at line 1 of file Cwise_arg.cpp.
Referenced by Eigen::RotationBase< Derived, 3 >::_transformVector(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::append(), Eigen::array< Index, ContractDims >::array(), array_special_functions(), Eigen::internal::assign_sparse_to_sparse(), Eigen::internal::bicgstab(), big_sparse_triplet(), Eigen::bounding_box(), bug_1260(), bug_1261(), bug_1308(), check_extremity_accuracy(), check_qtvector_matrix(), check_qtvector_quaternion(), check_qtvector_transform(), check_stddeque_matrix(), check_stddeque_quaternion(), check_stddeque_transform(), check_stdlist_matrix(), check_stdlist_quaternion(), check_stdlist_transform(), check_stdvector_matrix(), check_stdvector_quaternion(), check_stdvector_transform(), Eigen::TensorEvaluator< const TensorTupleReducerOp< ReduceOp, Dims, ArgType >, Device >::coeff(), combine(), Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::RealSchur< MatrixType >::computeFromHessenberg(), Eigen::createRandomPIMatrixOfRank(), DenseLM< Scalar >::df(), sparseGaussianTest< Scalar >::df(), divacNorm(), dontalign(), mpfr::fac_ui(), fillMatrix(), fillSpdMatrix(), mpfr::mpreal::get_default_prec(), Eigen::internal::gmres(), Eigen::householderSequence(), ScalarWithExceptions::init(), SystemTwo::initializeBasis(), initSparse(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::isApprox(), jacobi(), lines(), main(), Eigen::internal::manage_multi_threading(), map_class_vector(), sparseGaussianTest< Scalar >::model(), DenseLM< Scalar >::model(), ScalarWithExceptions::operator!=(), TestFunc1< _Scalar, NX, NY >::operator()(), DenseLM< Scalar >::operator()(), sparseGaussianTest< Scalar >::operator()(), ScalarWithExceptions::operator*(), ScalarWithExceptions::operator+(), ScalarWithExceptions::operator+=(), ScalarWithExceptions::operator-(), ScalarWithExceptions::operator-=(), mpfr::operator/(), Eigen::internal::operator<<(), Eigen::half_impl::operator<<(), ScalarWithExceptions::operator=(), Eigen::DynamicSGroupFromTemplateArgs< Gen >::operator=(), ScalarWithExceptions::operator==(), Eigen::internal::pblend(), Eigen::internal::preduxp< Packet4f >(), Eigen::internal::preduxp< Packet4i >(), Eigen::internal::pset1< Packet4f >(), Eigen::internal::pset1< Packet4i >(), Eigen::randomPermutationVector(), Eigen::internal::RandomToTypeNormal(), Eigen::internal::rcond_invmatrix_L1_norm_estimate(), regression_bug_654(), resize(), Eigen::rightHouseholderSequence(), times2_op::run(), ScalarWithExceptions::ScalarWithExceptions(), Basisnames< StateTwo >::set(), Eigen::SkylineInplaceLU< MatrixType >::setPrecision(), sparse_vector(), stable_norm(), svd_check_full(), svd_preallocate(), test3dRotation(), test_denseLM_T(), test_evaluators(), test_sparseLM_T(), test_stress_runqueue(), test_zerosized(), TreeTest< Dim >::testIntersect2(), TreeTest< Dim >::testMinimize2(), Eigen::internal::treePostorder(), triggerVectorBadAlloc(), vectorRedux(), vectorVisitor(), and ScalarWithExceptions::~ScalarWithExceptions().