pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/cxx11_tensor_forced_eval_sycl.cpp File Reference
cxx11_tensor_forced_eval_sycl.cpp File Reference
#include "main.h"
#include <unsupported/Eigen/CXX11/Tensor>
Macros
#define EIGEN_TEST_NO_LONGDOUBLE
#define EIGEN_TEST_NO_COMPLEX
#define EIGEN_TEST_FUNC cxx11_tensor_forced_eval_sycl
#define EIGEN_DEFAULT_DENSE_INDEX_TYPE int
#define EIGEN_USE_SYCL
Functions
void test_forced_eval_sycl (const Eigen::SyclDevice &sycl_device)
void test_cxx11_tensor_forced_eval_sycl ()
Macro Definition Documentation
EIGEN_DEFAULT_DENSE_INDEX_TYPE
#define EIGEN_DEFAULT_DENSE_INDEX_TYPE int
Definition at line 17 of file cxx11_tensor_forced_eval_sycl.cpp.
EIGEN_TEST_FUNC
#define EIGEN_TEST_FUNC cxx11_tensor_forced_eval_sycl
Definition at line 16 of file cxx11_tensor_forced_eval_sycl.cpp.
EIGEN_TEST_NO_COMPLEX
#define EIGEN_TEST_NO_COMPLEX
Definition at line 15 of file cxx11_tensor_forced_eval_sycl.cpp.
EIGEN_TEST_NO_LONGDOUBLE
#define EIGEN_TEST_NO_LONGDOUBLE
Definition at line 14 of file cxx11_tensor_forced_eval_sycl.cpp.
EIGEN_USE_SYCL
#define EIGEN_USE_SYCL
Definition at line 18 of file cxx11_tensor_forced_eval_sycl.cpp.
Function Documentation
test_cxx11_tensor_forced_eval_sycl()
void test_cxx11_tensor_forced_eval_sycl ()
Definition at line 66 of file cxx11_tensor_forced_eval_sycl.cpp.
References CALL_SUBTEST, s, and test_forced_eval_sycl().
test_forced_eval_sycl()
void test_forced_eval_sycl (const Eigen::SyclDevice & sycl_device)
c=(a+b)*b
Definition at line 25 of file cxx11_tensor_forced_eval_sycl.cpp.
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimensions(), and Eigen::DSizes< DenseIndex, NumDims >::TotalSize().
Referenced by test_cxx11_tensor_forced_eval_sycl().