pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/cxx11_tensor_uint128.cpp File Reference
cxx11_tensor_uint128.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Typedefs
typedef __uint128_t uint128_t
Functions
void VERIFY_EQUAL (TensorUInt128< uint64_t, uint64_t > actual, uint128_t expected)
void test_add ()
void test_sub ()
void test_mul ()
void test_div ()
void test_misc1 ()
void test_misc2 ()
void test_cxx11_tensor_uint128 ()
Typedef Documentation
uint128_t
typedef __uint128_t uint128_t
Definition at line 18 of file cxx11_tensor_uint128.cpp.
Function Documentation
test_add()
void test_add ()
Definition at line 40 of file cxx11_tensor_uint128.cpp.
References a, b, i, j, and VERIFY_EQUAL().
Referenced by test_cxx11_tensor_uint128().
test_cxx11_tensor_uint128()
void test_cxx11_tensor_uint128 ()
Definition at line 147 of file cxx11_tensor_uint128.cpp.
References test_add(), test_div(), test_misc1(), test_misc2(), test_mul(), and test_sub().
test_div()
void test_div ()
Definition at line 97 of file cxx11_tensor_uint128.cpp.
References a, b, i, j, and VERIFY_EQUAL().
Referenced by test_cxx11_tensor_uint128().
test_misc1()
void test_misc1 ()
Definition at line 116 of file cxx11_tensor_uint128.cpp.
References a, b, i, j, and VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_uint128().
test_misc2()
void test_misc2 ()
Definition at line 131 of file cxx11_tensor_uint128.cpp.
References VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_uint128().
test_mul()
void test_mul ()
Definition at line 78 of file cxx11_tensor_uint128.cpp.
References a, b, i, j, and VERIFY_EQUAL().
Referenced by test_cxx11_tensor_uint128().
test_sub()
void test_sub ()
Definition at line 59 of file cxx11_tensor_uint128.cpp.
References a, b, i, j, and VERIFY_EQUAL().
Referenced by test_cxx11_tensor_uint128().
VERIFY_EQUAL()
void VERIFY_EQUAL (TensorUInt128< uint64_t, uint64_t > actual, uint128_t expected)
Definition at line 27 of file cxx11_tensor_uint128.cpp.
References Eigen::internal::TensorUInt128< HIGH, LOW >::lower(), and Eigen::internal::TensorUInt128< HIGH, LOW >::upper().
Referenced by test_add(), test_div(), test_mul(), and test_sub().