pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/cxx11_tensor_image_patch.cpp File Reference
cxx11_tensor_image_patch.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Functions
void test_simple_patch ()
void test_patch_padding_valid ()
void test_patch_padding_valid_same_value ()
void test_patch_padding_same ()
void test_patch_no_extra_dim ()
void test_imagenet_patches ()
void test_cxx11_tensor_image_patch ()
Function Documentation
test_cxx11_tensor_image_patch()
void test_cxx11_tensor_image_patch ()
Definition at line 749 of file cxx11_tensor_image_patch.cpp.
References test_imagenet_patches(), test_patch_no_extra_dim(), test_patch_padding_same(), test_patch_padding_valid(), test_patch_padding_valid_same_value(), and test_simple_patch().
test_imagenet_patches()
void test_imagenet_patches ()
Definition at line 556 of file cxx11_tensor_image_patch.cpp.
References b, c, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), i, j, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::resize(), Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::setRandom(), Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::swap_layout(), and VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_image_patch().
test_patch_no_extra_dim()
void test_patch_no_extra_dim ()
Definition at line 408 of file cxx11_tensor_image_patch.cpp.
References c, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), i, j, Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::setRandom(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::swap_layout(), and VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_image_patch().
test_patch_padding_same()
void test_patch_padding_same ()
Definition at line 332 of file cxx11_tensor_image_patch.cpp.
References b, c, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), i, j, Eigen::PADDING_SAME, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::swap_layout(), and VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_image_patch().
test_patch_padding_valid()
void test_patch_padding_valid ()
Definition at line 183 of file cxx11_tensor_image_patch.cpp.
References b, c, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), i, j, Eigen::PADDING_VALID, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::swap_layout(), and VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_image_patch().
test_patch_padding_valid_same_value()
void test_patch_padding_valid_same_value ()
Definition at line 259 of file cxx11_tensor_image_patch.cpp.
Referenced by test_cxx11_tensor_image_patch().
test_simple_patch()
void test_simple_patch ()
Definition at line 16 of file cxx11_tensor_image_patch.cpp.
References b, c, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), i, j, Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::setRandom(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), Eigen::TensorBase< Tensor< Scalar_, NumIndices_, Options_, IndexType_ > >::swap_layout(), and VERIFY_IS_EQUAL.
Referenced by test_cxx11_tensor_image_patch().