pairinteraction: /travis/libpairinteraction/eigen/blas/testing/dblat1.f File Reference
dblat1.f File Reference
Functions/Subroutines
program dblat1
DBLAT1
subroutine header
subroutine check0 (SFAC)
subroutine check1 (SFAC)
subroutine check2 (SFAC)
subroutine check3 (SFAC)
subroutine stest (LEN, SCOMP, STRUE, SSIZE, SFAC)
subroutine testdsdot (SCOMP, STRUE, SSIZE, SFAC)
subroutine stest1 (SCOMP1, STRUE1, SSIZE, SFAC)
double precision function sdiff (SA, SB)
subroutine itest1 (ICOMP, ITRUE)
Function/Subroutine Documentation
check0()
subroutine check0 (double precision SFAC)
Definition at line 127 of file dblat1.f.
References a, b, c, drotg(), drotmg(), e(), j, stest(), and stest1().
Referenced by dblat1(), and sblat1().
check1()
subroutine check1 (double precision SFAC)
Definition at line 243 of file dblat1.f.
References dscal(), itest1(), max, stest(), and stest1().
check2()
subroutine check2 (double precision SFAC)
Definition at line 337 of file dblat1.f.
References a, abs, b, c, daxpy(), dcopy(), drotm(), dswap(), e(), m, min, stest(), stest1(), and testdsdot().
check3()
subroutine check3 (double precision SFAC)
Definition at line 681 of file dblat1.f.
References abs, drot(), min, and stest().
Referenced by dblat1(), and sblat1().
dblat1()
program dblat1 ()
DBLAT1
Purpose:
    Test program for the DOUBLE PRECISION Level 1 BLAS.
    Based upon the original BLAS test routine together with:
    F06EAF Example Program Text
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 38 of file dblat1.f.
References check0(), check1(), check2(), check3(), header(), and x.
header()
subroutine header ()
Definition at line 96 of file dblat1.f.
References x.
itest1()
subroutine itest1 (integer ICOMP, integer ITRUE)
Definition at line 1026 of file dblat1.f.
References x.
sdiff()
double precision function sdiff (double precision SA, double precision SB)
Definition at line 1016 of file dblat1.f.
References sdiff().
stest()
subroutine stest (integer LEN, double precision, dimension(len) SCOMP, double precision, dimension(len) STRUE, double precision, dimension(len) SSIZE, double precision SFAC)
Definition at line 887 of file dblat1.f.
References abs, and x.
stest1()
subroutine stest1 (double precision SCOMP1, double precision STRUE1, double precision, dimension(*) SSIZE, double precision SFAC)
Definition at line 991 of file dblat1.f.
References stest().
testdsdot()
subroutine testdsdot (real SCOMP, real STRUE, real SSIZE, real SFAC)
Definition at line 943 of file dblat1.f.
References abs, and x.
Referenced by check2().