pairinteraction: /travis/libpairinteraction/eigen/blas/testing/dblat2.f File Reference
dblat2.f File Reference
Functions/Subroutines
program dblat2
DBLAT2
subroutine dchk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine dchk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine dchk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, XT, G, Z)
subroutine dchk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine dchk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine dchk6 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine dchke (ISNUM, SRNAMT, NOUT)
subroutine dmake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, KL, KU, RESET, TRANSL)
subroutine dmvch (TRANS, M, N, ALPHA, A, NMAX, X, INCX, BETA, Y, INCY, YT, G, YY, EPS, ERR, FATAL, NOUT, MV)
logical function lde (RI, RJ, LR)
logical function lderes (TYPE, UPLO, M, N, AA, AS, LDA)
double precision function dbeg (RESET)
double precision function ddiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 3096 of file dblat2.f.
dbeg()
double precision function dbeg (logical RESET)
Definition at line 3034 of file dblat2.f.
Referenced by dbeg().
dblat2()
program dblat2 ()
DBLAT2
Purpose:
 Test program for the DOUBLE PRECISION Level 2 Blas.
 The program must be driven by a short data file. The first 18 records
 of the file are read using list-directed input, the last 16 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 34 lines:
 'dblat2.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'DBLAT2.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 4                 NUMBER OF VALUES OF K
 0 1 2 4           VALUES OF K
 4                 NUMBER OF VALUES OF INCX AND INCY
 1 2 -1 -2         VALUES OF INCX AND INCY
 3                 NUMBER OF VALUES OF ALPHA
 0.0 1.0 0.7       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 0.0 1.0 0.9       VALUES OF BETAC
 DGEMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DGBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DSYMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DSBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DSPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DTRMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DTBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DTPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 DTRSV  T PUT F FOR NO TEST. SAME COLUMNS.
 DTBSV  T PUT F FOR NO TEST. SAME COLUMNS.
 DTPSV  T PUT F FOR NO TEST. SAME COLUMNS.
 DGER   T PUT F FOR NO TEST. SAME COLUMNS.
 DSYR   T PUT F FOR NO TEST. SAME COLUMNS.
 DSPR   T PUT F FOR NO TEST. SAME COLUMNS.
 DSYR2  T PUT F FOR NO TEST. SAME COLUMNS.
 DSPR2  T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
    See:
       Dongarra J. J., Du Croz J. J., Hammarling S.  and Hanson R. J..
       An  extended  set of Fortran  Basic Linear Algebra Subprograms.
       Technical  Memoranda  Nos. 41 (revision 3) and 81,  Mathematics
       and  Computer Science  Division,  Argonne  National Laboratory,
       9700 South Cass Avenue, Argonne, Illinois 60439, US.
       Or
       NAG  Technical Reports TR3/87 and TR4/87,  Numerical Algorithms
       Group  Ltd.,  NAG  Central  Office,  256  Banbury  Road, Oxford
       OX2 7DE, UK,  and  Numerical Algorithms Group Inc.,  1101  31st
       Street,  Suite 100,  Downers Grove,  Illinois 60515-1263,  USA.
 -- Written on 10-August-1987.
    Richard Hanson, Sandia National Labs.
    Jeremy Du Croz, NAG Central Office.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 103 of file dblat2.f.
References abs, dchk1(), dchk2(), dchk3(), dchk4(), dchk5(), dchk6(), dchke(), dmvch(), max, min, p, x, and y.
dchk1()
subroutine dchk1 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, double precision, dimension(nalf) ALF, integer NBET, double precision, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, double precision, dimension(nmax, nmax) A, double precision, dimension(nmax*nmax) AA, double precision, dimension(nmax*nmax) AS, double precision, dimension(nmax) X, double precision, dimension(nmax*incmax) XX, double precision, dimension(nmax*incmax) XS, double precision, dimension(nmax) Y, double precision, dimension(nmax*incmax) YY, double precision, dimension(nmax*incmax) YS, double precision, dimension(nmax) YT, double precision, dimension(nmax) G)
Definition at line 434 of file dblat2.f.
References abs, dgbmv(), dgemv(), dmake(), dmvch(), lda, m, max, min, n, x, and y.
Referenced by dblat2(), and dblat3().
dchk2()
subroutine dchk2 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, double precision, dimension(nalf) ALF, integer NBET, double precision, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, double precision, dimension(nmax, nmax) A, double precision, dimension(nmax*nmax) AA, double precision, dimension(nmax*nmax) AS, double precision, dimension(nmax) X, double precision, dimension(nmax*incmax) XX, double precision, dimension(nmax*incmax) XS, double precision, dimension(nmax) Y, double precision, dimension(nmax*incmax) YY, double precision, dimension(nmax*incmax) YS, double precision, dimension(nmax) YT, double precision, dimension(nmax) G)
Definition at line 775 of file dblat2.f.
References abs, dmake(), dmvch(), dsbmv(), dspmv(), dsymv(), lda, max, n, x, and y.
Referenced by dblat2(), and dblat3().
dchk3()
subroutine dchk3 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, double precision, dimension(nmax, nmax) A, double precision, dimension(nmax*nmax) AA, double precision, dimension(nmax*nmax) AS, double precision, dimension(nmax) X, double precision, dimension(nmax*incmax) XX, double precision, dimension(nmax*incmax) XS, double precision, dimension(nmax) XT, double precision, dimension(nmax) G, double precision, dimension(nmax) Z)
Definition at line 1117 of file dblat2.f.
References abs, dmake(), dmvch(), dtbmv(), dtbsv(), dtpmv(), dtpsv(), dtrmv(), dtrsv(), lda, max, n, and x.
Referenced by dblat2(), and dblat3().
dchk4()
subroutine dchk4 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, double precision, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, double precision, dimension(nmax, nmax) A, double precision, dimension(nmax*nmax) AA, double precision, dimension(nmax*nmax) AS, double precision, dimension(nmax) X, double precision, dimension(nmax*incmax) XX, double precision, dimension(nmax*incmax) XS, double precision, dimension(nmax) Y, double precision, dimension(nmax*incmax) YY, double precision, dimension(nmax*incmax) YS, double precision, dimension(nmax) YT, double precision, dimension(nmax) G, double precision, dimension(nmax) Z)
Definition at line 1475 of file dblat2.f.
References abs, dger(), dmake(), dmvch(), j, lda, m, max, min, n, x, and y.
Referenced by dblat2(), and dblat3().
dchk5()
subroutine dchk5 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, double precision, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, double precision, dimension(nmax, nmax) A, double precision, dimension(nmax*nmax) AA, double precision, dimension(nmax*nmax) AS, double precision, dimension(nmax) X, double precision, dimension(nmax*incmax) XX, double precision, dimension(nmax*incmax) XS, double precision, dimension(nmax) Y, double precision, dimension(nmax*incmax) YY, double precision, dimension(nmax*incmax) YS, double precision, dimension(nmax) YT, double precision, dimension(nmax) G, double precision, dimension(nmax) Z)
Definition at line 1736 of file dblat2.f.
References abs, dmake(), dmvch(), dspr(), dsyr(), lda, max, n, x, and y.
Referenced by dblat2(), and dblat3().
dchk6()
subroutine dchk6 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, double precision, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, double precision, dimension(nmax, nmax) A, double precision, dimension(nmax*nmax) AA, double precision, dimension(nmax*nmax) AS, double precision, dimension(nmax) X, double precision, dimension(nmax*incmax) XX, double precision, dimension(nmax*incmax) XS, double precision, dimension(nmax) Y, double precision, dimension(nmax*incmax) YY, double precision, dimension(nmax*incmax) YS, double precision, dimension(nmax) YT, double precision, dimension(nmax) G, double precision, dimension(nmax, 2) Z)
Definition at line 2014 of file dblat2.f.
References abs, dmake(), dmvch(), dspr2(), dsyr2(), j, lda, max, n, x, and y.
Referenced by dblat2().
dchke()
subroutine dchke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 2326 of file dblat2.f.
References chkxer(), dgbmv(), dgemv(), dger(), dsbmv(), dspmv(), dspr(), dspr2(), dsymv(), dsyr(), dsyr2(), dtbmv(), dtbsv(), dtpmv(), dtpsv(), dtrmv(), and dtrsv().
Referenced by dblat2(), and dblat3().
ddiff()
double precision function ddiff (double precision X, double precision Y)
Definition at line 3080 of file dblat2.f.
Referenced by ddiff().
dmake()
subroutine dmake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, double precision, dimension(nmax, *) A, integer NMAX, double precision, dimension(*) AA, integer LDA, integer KL, integer KU, logical RESET, double precision TRANSL)
Definition at line 2653 of file dblat2.f.
References max, and min.
Referenced by dchk1(), dchk2(), dchk3(), dchk4(), dchk5(), and dchk6().
dmvch()
subroutine dmvch (character*1 TRANS, integer M, integer N, double precision ALPHA, double precision, dimension(nmax, *) A, integer NMAX, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY, double precision, dimension(*) YT, double precision, dimension(*) G, double precision, dimension(*) YY, double precision EPS, double precision ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 2829 of file dblat2.f.
References abs, max, and sqrt().
Referenced by dblat2(), dchk1(), dchk2(), dchk3(), dchk4(), dchk5(), and dchk6().
lde()
logical function lde (double precision, dimension(*) RI, double precision, dimension(*) RJ, integer LR)
Definition at line 2945 of file dblat2.f.
Referenced by lde().
lderes()
logical function lderes (character*2 TYPE, character*1 UPLO, integer M, integer N, double precision, dimension(lda, *) AA, double precision, dimension(lda, *) AS, integer LDA)
Definition at line 2975 of file dblat2.f.
Referenced by lderes().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 3124 of file dblat2.f.