pairinteraction: /travis/libpairinteraction/eigen/test/determinant.cpp File Reference
determinant.cpp File Reference
#include "main.h"
#include <Eigen/LU>
Functions
template<typename MatrixType >
void determinant (const MatrixType &m)
void test_determinant ()
Function Documentation
determinant()
template<typename MatrixType > void determinant (const MatrixType & m)
Definition at line 14 of file determinant.cpp.
References conj(), eval(), i, j, m1, m2(), size, VERIFY_IS_APPROX, and x.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::computeInverseWithCheck(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), Eigen::SuperLU< _MatrixType >::determinant(), Eigen::PartialPivLU< Matrix< Scalar, Dynamic, Dynamic > >::inverse(), Eigen::SuperLU< _MatrixType >::permutationQ(), Eigen::FullPivLU< _MatrixType >::rcond(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run(), and Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run().
test_determinant()
void test_determinant ()
Definition at line 54 of file determinant.cpp.
References i.