pairinteraction: /travis/libpairinteraction/eigen/test/dynalloc.cpp File Reference
dynalloc.cpp File Reference
#include "main.h"
Data Structures
struct MyStruct
class MyClassA
Macros
#define ALIGNMENT 1
Typedefs
typedef Matrix< float, 8, 1 > Vector8f
Functions
void check_handmade_aligned_malloc ()
void check_aligned_malloc ()
void check_aligned_new ()
void check_aligned_stack_alloc ()
template<typename T >
void check_dynaligned ()
template<typename T >
void check_custom_new_delete ()
void test_dynalloc ()
Macro Definition Documentation
ALIGNMENT
#define ALIGNMENT 1
Definition at line 15 of file dynalloc.cpp.
Referenced by check_aligned_malloc(), check_aligned_new(), check_aligned_stack_alloc(), check_dynaligned(), and check_handmade_aligned_malloc().
Typedef Documentation
Vector8f
typedef Matrix<float,8,1> Vector8f
Definition at line 18 of file dynalloc.cpp.
Function Documentation
check_aligned_malloc()
void check_aligned_malloc ()
Definition at line 32 of file dynalloc.cpp.
References Eigen::internal::aligned_free(), Eigen::internal::aligned_malloc(), ALIGNMENT, i, j, p, and VERIFY.
Referenced by test_dynalloc().
check_aligned_new()
void check_aligned_new ()
Definition at line 44 of file dynalloc.cpp.
References Eigen::internal::aligned_delete(), ALIGNMENT, i, j, p, and VERIFY.
Referenced by test_dynalloc().
check_aligned_stack_alloc()
void check_aligned_stack_alloc ()
Definition at line 56 of file dynalloc.cpp.
References ALIGNMENT, ei_declare_aligned_stack_constructed_variable, i, j, p, and VERIFY.
Referenced by test_dynalloc().
check_custom_new_delete()
template<typename T > void check_custom_new_delete ()
Definition at line 96 of file dynalloc.cpp.
check_dynaligned()
template<typename T > void check_dynaligned ()
Definition at line 84 of file dynalloc.cpp.
References ALIGNMENT, and VERIFY.
check_handmade_aligned_malloc()
void check_handmade_aligned_malloc ()
Definition at line 20 of file dynalloc.cpp.
References ALIGNMENT, Eigen::internal::handmade_aligned_free(), Eigen::internal::handmade_aligned_malloc(), i, j, p, and VERIFY.
Referenced by test_dynalloc().
test_dynalloc()
void test_dynalloc ()
Definition at line 122 of file dynalloc.cpp.
References CALL_SUBTEST, check_aligned_malloc(), check_aligned_new(), check_aligned_stack_alloc(), check_handmade_aligned_malloc(), and i.