pairinteraction: /travis/libpairinteraction/eigen/scripts/eigen_gen_credits.cpp File Reference
eigen_gen_credits.cpp File Reference
#include <string>
#include <sstream>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <map>
#include <list>
Data Structures
struct contributor
Functions
std::string contributor_name (const std::string &line)
map< string, int > contributors_map_from_churn_output (const char *filename)
string lastname (const string &name)
void add_online_info_into_contributors_list (list< contributor > &contributors_list, const char *filename)
int main ()
Function Documentation
add_online_info_into_contributors_list()
void add_online_info_into_contributors_list (list< contributor > & contributors_list, const char * filename)
Definition at line 133 of file eigen_gen_credits.cpp.
References c, contributor::misc, contributor::name, and contributor::url.
Referenced by main().
contributor_name()
std::string contributor_name (const std::string & line)
Definition at line 13 of file eigen_gen_credits.cpp.
Referenced by contributors_map_from_churn_output().
contributors_map_from_churn_output()
map<string,int> contributors_map_from_churn_output (const char * filename)
Definition at line 67 of file eigen_gen_credits.cpp.
References contributor_name().
Referenced by main().
lastname()
string lastname (const string & name)
Definition at line 110 of file eigen_gen_credits.cpp.
Referenced by contributor::operator<().
main()
int main (void)
Definition at line 186 of file eigen_gen_credits.cpp.
References add_online_info_into_contributors_list(), c, contributor::changedlines, contributor::changesets, contributors_map_from_churn_output(), i, and contributor::name.