pairinteraction: /travis/libpairinteraction/eigen/test/eigensolver_complex.cpp File Reference
eigensolver_complex.cpp File Reference
#include "main.h"
#include <limits>
#include <Eigen/Eigenvalues>
#include <Eigen/LU>
Functions
template<typename MatrixType >
bool find_pivot (typename MatrixType::Scalar tol, MatrixType &diffs, Index col=0)
template<typename VectorType >
void verify_is_approx_upto_permutation (const VectorType &vec1, const VectorType &vec2)
template<typename MatrixType >
void eigensolver (const MatrixType &m)
template<typename MatrixType >
void eigensolver_verify_assert (const MatrixType &m)
void test_eigensolver_complex ()
Function Documentation
eigensolver()
template<typename MatrixType > void eigensolver (const MatrixType & m)
Definition at line 72 of file eigensolver_complex.cpp.
References a, cols, Eigen::ComplexEigenSolver< _MatrixType >::compute(), eig, Eigen::ComplexEigenSolver< _MatrixType >::eigenvalues(), Eigen::ComplexEigenSolver< _MatrixType >::eigenvectors(), eval(), Eigen::ComplexEigenSolver< _MatrixType >::info(), Eigen::NoConvergence, rows, Eigen::ComplexEigenSolver< _MatrixType >::setMaxIterations(), Eigen::Success, VERIFY, VERIFY_IS_APPROX, verify_is_approx_upto_permutation(), VERIFY_IS_EQUAL, and VERIFY_IS_MUCH_SMALLER_THAN.
Referenced by Hamiltonianmatrix::diagonalize(), SystemBase< StateTwo >::diagonalize(), main(), and test_boostmultiprec().
eigensolver_verify_assert()
template<typename MatrixType > void eigensolver_verify_assert (const MatrixType & m)
Definition at line 145 of file eigensolver_complex.cpp.
References a, Eigen::ComplexEigenSolver< _MatrixType >::compute(), eig, Eigen::ComplexEigenSolver< _MatrixType >::eigenvalues(), Eigen::ComplexEigenSolver< _MatrixType >::eigenvectors(), and VERIFY_RAISES_ASSERT.
find_pivot()
template<typename MatrixType > bool find_pivot (typename MatrixType::Scalar tol, MatrixType & diffs, Index col = 0)
Definition at line 16 of file eigensolver_complex.cpp.
References col(), i, and n.
Referenced by verify_is_approx_upto_permutation().
test_eigensolver_complex()
void test_eigensolver_complex ()
Definition at line 156 of file eigensolver_complex.cpp.
References i, and s.
verify_is_approx_upto_permutation()
template<typename VectorType > void verify_is_approx_upto_permutation (const VectorType & vec1, const VectorType & vec2)
Definition at line 55 of file eigensolver_complex.cpp.
References cwiseAbs2(), find_pivot(), n, and VERIFY.
Referenced by eigensolver().