pairinteraction: /travis/libpairinteraction/eigen/test/eigensolver_generic.cpp File Reference
eigensolver_generic.cpp File Reference
#include "main.h"
#include <limits>
#include <Eigen/Eigenvalues>
Functions
template<typename MatrixType >
void eigensolver (const MatrixType &m)
template<typename MatrixType >
void eigensolver_verify_assert (const MatrixType &m)
void test_eigensolver_generic ()
Function Documentation
eigensolver()
template<typename MatrixType > void eigensolver (const MatrixType & m)
Definition at line 15 of file eigensolver_generic.cpp.
References a, cols, Eigen::EigenSolver< _MatrixType >::compute(), eig, Eigen::EigenSolver< _MatrixType >::eigenvalues(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), eval(), Eigen::EigenSolver< _MatrixType >::info(), Eigen::NoConvergence, Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvectors(), rows, Eigen::EigenSolver< _MatrixType >::setMaxIterations(), Eigen::Success, VERIFY, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, and VERIFY_IS_MUCH_SMALLER_THAN.
eigensolver_verify_assert()
template<typename MatrixType > void eigensolver_verify_assert (const MatrixType & m)
Definition at line 90 of file eigensolver_generic.cpp.
References a, Eigen::EigenSolver< _MatrixType >::compute(), eig, Eigen::EigenSolver< _MatrixType >::eigenvalues(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvectors(), and VERIFY_RAISES_ASSERT.
test_eigensolver_generic()
void test_eigensolver_generic ()
Definition at line 104 of file eigensolver_generic.cpp.
References i, and s.