pairinteraction: /travis/libpairinteraction/eigen/lapack/eigenvalues.cpp File Reference
eigenvalues.cpp File Reference
#include "lapack_common.h"
#include <Eigen/Eigenvalues>
Functions
else if (UPLO(*uplo)==INVALID) *info
else if * lda (1, *n)) *info=-5;else if((!query_size) &&*lwork< std::max(1, 3 **n-1)) *info=-8;if(*info!=0
if (query_size)
if (eig.info()==NoConvergence)
make_vector (w, *n)
if (computeVectors) matrix(a
Variables
* info = 0
if n return
PlainMatrixType mat * n
else mat = matrix(a,*n,*n,*lda)
bool computeVectors = *jobz=='V' || *jobz=='v'
SelfAdjointEigenSolver< PlainMatrixType > eig (mat, computeVectors?ComputeEigenvectors:EigenvaluesOnly)
* lda = eig.eigenvectors()
Function Documentation
if() [1/4]
else if (UPLO * uplo = =INVALID)
Definition at line 60 of file cholesky.cpp.
References adjoint(), and Eigen::Upper.
if() [2/4]
if (query_size)
Definition at line 32 of file eigenvalues.cpp.
if() [3/4]
if (eig. info() = =NoConvergence)
Definition at line 48 of file eigenvalues.cpp.
References eig, make_vector(), and matrix().
if() [4/4]
if (computeVectors)
lda()
else if* lda (1 , * n)
Definition at line 23 of file eigenvalues.cpp.
References e(), info, SCALAR_SUFFIX_UP, and xerbla_().
make_vector()
make_vector (w , * n)
Referenced by if().
Variable Documentation
computeVectors
bool computeVectors = *jobz=='V' || *jobz=='v'
Definition at line 45 of file eigenvalues.cpp.
eig
SelfAdjointEigenSolver<PlainMatrixType> eig(mat, computeVectors?ComputeEigenvectors:EigenvaluesOnly)
Referenced by bug_1204(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresComputeDeflationData(), eigensolver(), eigensolver_verify_assert(), generalized_eigensolver_real(), if(), main(), Eigen::DGMRES< _MatrixType, _Preconditioner >::schurValues(), and selfadjointeigensolver().
info
else if n* info = 0
Definition at line 19 of file eigenvalues.cpp.
Referenced by lda().
lda
else if * lda = eig.eigenvectors()
Definition at line 59 of file eigenvalues.cpp.
Referenced by cchk1(), cchk2(), cchk3(), cchk4(), cchk5(), cchk6(), chbmv_(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::column_bmod(), dchk1(), dchk2(), dchk3(), dchk4(), dchk5(), dchk6(), dsbmv_(), gemm(), gemv(), ger(), gerc(), geru(), hemv(), her(), her2(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::panel_bmod(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::pivotL(), schk1(), schk2(), schk3(), schk4(), schk5(), schk6(), Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::solveInPlace(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveInPlace(), ssbmv_(), symm(), symv(), syr2k(), syrk(), tbsv(), trmm(), trmv(), trsm(), trsv(), zchk1(), zchk2(), zchk3(), zchk4(), zchk5(), zchk6(), and zhbmv_().
mat
else mat = matrix(a,*n,*n,*lda)
Definition at line 43 of file eigenvalues.cpp.
n
* n
Definition at line 41 of file eigenvalues.cpp.
return
return
Definition at line 38 of file eigenvalues.cpp.