pairinteraction: /travis/libpairinteraction/eigen/demos/mix_eigen_and_c/example.c File Reference
example.c File Reference
#include "binary_library.h"
#include "stdio.h"
Functions
void demo_MatrixXd ()
void print_array (double *array, int n)
void demo_Map_MatrixXd ()
int main ()
Function Documentation
demo_Map_MatrixXd()
void demo_Map_MatrixXd ()
Definition at line 42 of file example.c.
References i, Map_MatrixXd_add(), Map_MatrixXd_delete(), Map_MatrixXd_new(), and print_array().
Referenced by main().
demo_MatrixXd()
void demo_MatrixXd ()
Definition at line 13 of file example.c.
References MatrixXd_delete(), MatrixXd_multiply(), MatrixXd_new(), MatrixXd_print(), MatrixXd_set_coeff(), and MatrixXd_set_zero().
Referenced by main().
main()
int main (void)
Definition at line 61 of file example.c.
References demo_Map_MatrixXd(), and demo_MatrixXd().
print_array()
void print_array (double * array, int n)
Definition at line 35 of file example.c.
References m, Map_MatrixXd_delete(), Map_MatrixXd_new(), and Map_MatrixXd_print().
Referenced by demo_Map_MatrixXd().