pairinteraction: /travis/libpairinteraction/eigen/test/exceptions.cpp File Reference
exceptions.cpp File Reference
#include "main.h"
Data Structures
struct my_exception
class ScalarWithExceptions
Macros
#define EIGEN_STACK_ALLOCATION_LIMIT 100000000
#define CHECK_MEMLEAK(OP)
Functions
ScalarWithExceptions real (const ScalarWithExceptions &x)
ScalarWithExceptions imag (const ScalarWithExceptions &)
ScalarWithExceptions conj (const ScalarWithExceptions &x)
void memoryleak ()
void test_exceptions ()
Macro Definition Documentation
CHECK_MEMLEAK
#define CHECK_MEMLEAK (OP)
Value:
{                                 \
    ScalarWithExceptions::countdown = 100;                  \
    int before = ScalarWithExceptions::instances;           \
    bool exception_thrown = false;                         \
    try { OP; }                              \
    catch (my_exception) {                                  \
      exception_thrown = true;                              \
      VERIFY(ScalarWithExceptions::instances==before && "memory leak detected in " && EIGEN_MAKESTRING(OP)); \
    } \
    VERIFY(exception_thrown && " no exception thrown in " && EIGEN_MAKESTRING(OP)); \
  }
Definition at line 80 of file exceptions.cpp.
Referenced by memoryleak().
EIGEN_STACK_ALLOCATION_LIMIT
#define EIGEN_STACK_ALLOCATION_LIMIT 100000000
Definition at line 15 of file exceptions.cpp.
Function Documentation
conj()
ScalarWithExceptions conj (const ScalarWithExceptions & x)
Definition at line 74 of file exceptions.cpp.
References ScalarWithExceptions::countdown, ScalarWithExceptions::instances, and x.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), adjoint(), Eigen::internal::apply_rotation_in_the_plane(), array_complex(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), SystemBase< StateTwo >::conjugate(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::cross(), determinant(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::dot(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize_preordered(), jacobi(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2_dummy, StorageOrder >::operator()(), Eigen::internal::conj_if< true >::operator()(), Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder >::operator()(), Eigen::internal::scalar_conjugate_op< Scalar >::operator()(), Eigen::JacobiRotation< Scalar >::operator*(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2_dummy, StorageOrder >::pack(), packetmath(), Eigen::internal::pconj(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), product_extra(), product_selfadjoint(), randMatrixSpecialUnitary(), Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate(), rotg(), adjoint_specific< true >::run(), internal::rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Lower >::run(), adjoint_specific< false >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn >::run(), internal::packed_rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Upper >::run(), Eigen::internal::cross3_impl< Arch, VectorLhs, VectorRhs, Scalar, Vectorizable >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::unitOrthogonal_selector< Derived, Size >::run(), Eigen::internal::unitOrthogonal_selector< Derived, 3 >::run(), Eigen::internal::unitOrthogonal_selector< Derived, 2 >::run(), Eigen::internal::tensor_symmetry_assign_value< Tensor_ >::run(), Eigen::internal::sparse_selfadjoint_time_dense_product(), syr2k(), Eigen::JacobiRotation< Scalar >::transpose(), Eigen::internal::tridiagonalization_inplace(), trmm(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), Eigen::internal::ldlt_inplace< Lower >::updateInPlace(), and Eigen::internal::upperbidiagonalization_blocked_helper().
imag()
ScalarWithExceptions imag (const ScalarWithExceptions &)
Definition at line 73 of file exceptions.cpp.
memoryleak()
void memoryleak ()
Definition at line 92 of file exceptions.cpp.
References CHECK_MEMLEAK, dot(), EIGEN_MAKESTRING, ScalarWithExceptions::instances, m1, m2(), n, OP, v1(), and VERIFY.
Referenced by test_exceptions().
real()
ScalarWithExceptions real (const ScalarWithExceptions & x)
Definition at line 72 of file exceptions.cpp.
References x.
test_exceptions()
void test_exceptions ()
Definition at line 110 of file exceptions.cpp.
References CALL_SUBTEST, and memoryleak().