pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/FFTW.cpp File Reference
FFTW.cpp File Reference
#include "main.h"
#include <unsupported/Eigen/FFT>
Data Structures
struct VectorType< Container, Scalar >
struct VectorType< StdVectorContainer, Scalar >
struct VectorType< EigenVectorContainer, Scalar >
Enumerations
enum { StdVectorContainer, EigenVectorContainer }
Functions
template<typename T >
std::complex< T > RandomCpx ()
template<typename T >
complex< long double > promote (complex< T > x)
complex< long double > promote (float x)
complex< long double > promote (double x)
complex< long double > promote (long double x)
template<typename VT1 , typename VT2 >
long double fft_rmse (const VT1 &fftbuf, const VT2 &timebuf)
template<typename VT1 , typename VT2 >
long double dif_rmse (const VT1 buf1, const VT2 buf2)
template<int Container, typename T >
void test_scalar_generic (int nfft)
template<typename T >
void test_scalar (int nfft)
template<int Container, typename T >
void test_complex_generic (int nfft)
template<typename T >
void test_complex (int nfft)
void test_return_by_value (int len)
void test_FFTW ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
StdVectorContainer
EigenVectorContainer
Definition at line 63 of file FFTW.cpp.
Function Documentation
dif_rmse()
template<typename VT1 , typename VT2 > long double dif_rmse (const VT1 buf1, const VT2 buf2)
Definition at line 51 of file FFTW.cpp.
References abs2(), min, n, and sqrt().
Referenced by test_complex_generic(), and test_scalar_generic().
fft_rmse()
template<typename VT1 , typename VT2 > long double fft_rmse (const VT1 & fftbuf, const VT2 & timebuf)
Definition at line 29 of file FFTW.cpp.
References abs2(), acos(), exp(), promote(), sqrt(), and x.
Referenced by test_complex_generic(), and test_scalar_generic().
promote() [1/4]
template<typename T > complex<long double> promote (complex< T > x)
Definition at line 21 of file FFTW.cpp.
Referenced by fft_rmse().
promote() [2/4]
complex<long double> promote (float x)
Definition at line 23 of file FFTW.cpp.
promote() [3/4]
complex<long double> promote (double x)
Definition at line 24 of file FFTW.cpp.
promote() [4/4]
complex<long double> promote (long double x)
Definition at line 25 of file FFTW.cpp.
RandomCpx()
template<typename T > std::complex<T> RandomCpx ()
Definition at line 14 of file FFTW.cpp.
test_complex()
template<typename T > void test_complex (int nfft)
Definition at line 175 of file FFTW.cpp.
test_complex_generic()
template<int Container, typename T > void test_complex_generic (int nfft)
Definition at line 141 of file FFTW.cpp.
References dif_rmse(), fft_rmse(), and VERIFY.
test_FFTW()
void test_FFTW ()
Definition at line 228 of file FFTW.cpp.
References CALL_SUBTEST, and test_return_by_value().
test_return_by_value()
void test_return_by_value (int len)
Definition at line 211 of file FFTW.cpp.
References test_precision< float >(), and VERIFY.
Referenced by test_FFTW().
test_scalar()
template<typename T > void test_scalar (int nfft)
Definition at line 133 of file FFTW.cpp.
test_scalar_generic()
template<int Container, typename T > void test_scalar_generic (int nfft)
Definition at line 78 of file FFTW.cpp.
References dif_rmse(), fft_rmse(), and VERIFY.