pairinteraction: /travis/libpairinteraction/eigen/test/first_aligned.cpp File Reference
first_aligned.cpp File Reference
#include "main.h"
Data Structures
struct some_non_vectorizable_type
Functions
template<typename Scalar >
void test_first_aligned_helper (Scalar *array, int size)
template<typename Scalar >
void test_none_aligned_helper (Scalar *array, int size)
void test_first_aligned ()
Function Documentation
test_first_aligned()
void test_first_aligned ()
Definition at line 29 of file first_aligned.cpp.
References EIGEN_ALIGN16, test_first_aligned_helper(), and test_none_aligned_helper().
test_first_aligned_helper()
template<typename Scalar > void test_first_aligned_helper (Scalar * array, int size)
Definition at line 13 of file first_aligned.cpp.
References size, and VERIFY.
Referenced by test_first_aligned().
test_none_aligned_helper()
template<typename Scalar > void test_none_aligned_helper (Scalar * array, int size)
Definition at line 20 of file first_aligned.cpp.
References EIGEN_UNUSED_VARIABLE, size, and VERIFY.
Referenced by test_first_aligned().