pairinteraction: /travis/libpairinteraction/eigen/test/geo_hyperplane.cpp File Reference
geo_hyperplane.cpp File Reference
#include "main.h"
#include <Eigen/Geometry>
#include <Eigen/LU>
#include <Eigen/QR>
Functions
template<typename HyperplaneType >
void hyperplane (const HyperplaneType &_plane)
template<typename Scalar >
void lines ()
template<typename Scalar >
void planes ()
template<typename Scalar >
void hyperplane_alignment ()
void test_geo_hyperplane ()
Function Documentation
hyperplane()
template<typename HyperplaneType > void hyperplane (const HyperplaneType & _plane)
Definition at line 16 of file geo_hyperplane.cpp.
References abs(), abs2(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal(), mpfr::mpreal::dim, mpfr::dim(), e(), Eigen::Isometry, p0, p1, rot(), VERIFY_IS_APPROX, and VERIFY_IS_MUCH_SMALLER_THAN.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
hyperplane_alignment()
template<typename Scalar > void hyperplane_alignment ()
Definition at line 156 of file geo_hyperplane.cpp.
References EIGEN_ALIGN_MAX, p1, size, VERIFY_IS_APPROX, and VERIFY_RAISES_ASSERT.
lines()
template<typename Scalar > void lines ()
Definition at line 89 of file geo_hyperplane.cpp.
References a, abs(), e(), i, v, VERIFY, and VERIFY_IS_APPROX.
planes()
template<typename Scalar > void planes ()
Definition at line 130 of file geo_hyperplane.cpp.
References abs(), i, p0, Eigen::half_impl::pow(), v1(), v2(), VERIFY_IS_APPROX, and VERIFY_IS_MUCH_SMALLER_THAN.
test_geo_hyperplane()
void test_geo_hyperplane ()
Definition at line 184 of file geo_hyperplane.cpp.
References i.