pairinteraction: /travis/libpairinteraction/eigen/test/geo_alignedbox.cpp File Reference
geo_alignedbox.cpp File Reference
#include "main.h"
#include <Eigen/Geometry>
#include <Eigen/LU>
#include <Eigen/QR>
#include <iostream>
Functions
template<typename T >
EIGEN_DONT_INLINE void kill_extra_precision (T &x)
template<typename BoxType >
void alignedbox (const BoxType &_box)
template<typename BoxType >
void alignedboxCastTests (const BoxType &_box)
void specificTest1 ()
void specificTest2 ()
void test_geo_alignedbox ()
Function Documentation
alignedbox()
template<typename BoxType > void alignedbox (const BoxType & _box)
Definition at line 22 of file geo_alignedbox.cpp.
References mpfr::mpreal::dim, mpfr::dim(), i, kill_extra_precision(), p0, p1, VERIFY, and VERIFY_IS_APPROX.
alignedboxCastTests()
template<typename BoxType > void alignedboxCastTests (const BoxType & _box)
Definition at line 86 of file geo_alignedbox.cpp.
References mpfr::mpreal::dim, mpfr::dim(), p0, p1, and VERIFY_IS_APPROX.
kill_extra_precision()
template<typename T > EIGEN_DONT_INLINE void kill_extra_precision (T & x)
Definition at line 19 of file geo_alignedbox.cpp.
References eigen_assert.
Referenced by alignedbox().
specificTest1()
void specificTest1 ()
Definition at line 112 of file geo_alignedbox.cpp.
References m, and VERIFY_IS_APPROX.
specificTest2()
void specificTest2 ()
Definition at line 139 of file geo_alignedbox.cpp.
References m, and VERIFY_IS_APPROX.
test_geo_alignedbox()
void test_geo_alignedbox ()
Definition at line 165 of file geo_alignedbox.cpp.
References i.