pairinteraction: /travis/libpairinteraction/eigen/bench/btl/data/gnuplot_common_settings.hh File Reference
gnuplot_common_settings.hh File Reference
Variables
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy x = reinterpret_cast<Scalar*>(px)
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set offsets
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set view
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set samples
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set isosamples
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size ratio
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set origin
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set set xzeroaxis lt lw set x2zeroaxis lt lw set yzeroaxis lt lw set y2zeroaxis lt lw set tics in set ticslevel set tics scale
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set set xzeroaxis lt lw set x2zeroaxis lt lw set yzeroaxis lt lw set y2zeroaxis lt lw set tics in set ticslevel set tics set mxtics default set mytics default set mx2tics default set my2tics default set xtics border mirror norotate autofreq set ytics border mirror norotate autofreq set ztics border nomirror norotate autofreq set nox2tics set noy2tics set timestamp bottom norotate offset
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set set xzeroaxis lt lw set x2zeroaxis lt lw set yzeroaxis lt lw set y2zeroaxis lt lw set tics in set ticslevel set tics set mxtics default set mytics default set mx2tics default set my2tics default set xtics border mirror norotate autofreq set ytics border mirror norotate autofreq set ztics border nomirror norotate autofreq set nox2tics set noy2tics set timestamp bottom norotate set rrange [*:*] noreverse nowriteback set trange [*:*] noreverse nowriteback set urange [*:*] noreverse nowriteback set vrange [*:*] noreverse nowriteback set xlabel matrix size set x2label set timefmt d m y n H
Variable Documentation
H
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set set xzeroaxis lt lw set x2zeroaxis lt lw set yzeroaxis lt lw set y2zeroaxis lt lw set tics in set ticslevel set tics set mxtics default set mytics default set mx2tics default set my2tics default set xtics border mirror norotate autofreq set ytics border mirror norotate autofreq set ztics border nomirror norotate autofreq set nox2tics set noy2tics set timestamp bottom norotate set rrange [ * : * ] noreverse nowriteback set trange [ * : * ] noreverse nowriteback set urange [ * : * ] noreverse nowriteback set vrange [ * : * ] noreverse nowriteback set xlabel matrix size set x2label set timefmt d m y n H
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by Eigen::internal::gmres().
isosamples
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set isosamples
Definition at line 12 of file gnuplot_common_settings.hh.
offset
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set set xzeroaxis lt lw set x2zeroaxis lt lw set yzeroaxis lt lw set y2zeroaxis lt lw set tics in set ticslevel set tics set mxtics default set mytics default set mx2tics default set my2tics default set xtics border mirror norotate autofreq set ytics border mirror norotate autofreq set ztics border nomirror norotate autofreq set nox2tics set noy2tics set timestamp bottom norotate set rrange [ * : * ] noreverse nowriteback set trange [ * : * ] noreverse nowriteback set urange [ * : * ] noreverse nowriteback set vrange [ * : * ] noreverse nowriteback set xlabel matrix size set x2label set timefmt d m y n set y2label set yrange [ * : * ] noreverse nowriteback set y2range [ * : * ] noreverse nowriteback set zlabel offset
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::chip(), Eigen::TensorBase< TensorConversionOp< TargetType, XprType >, ReadOnlyAccessors >::chip(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::coeff(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::coeffRef(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::column_bmod(), Eigen::SkylineInplaceLU< MatrixType >::computeRowMajor(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::data(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::IndexMapper(), Eigen::SparseMatrix< scalar_t >::makeCompressed(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputKernelToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputKernelToTensorOutputOffset(), Eigen::internal::CoeffLoader< Tensor, true >::offsetBuffer(), Eigen::ScanLauncher< Self, Reducer, Device >::operator()(), Eigen::internal::GaussianGenerator< T, Index, NumDims >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, ColMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::gemm_pack_rhs< Scalar, Index, DataMapper, nr, ColMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::gemm_pack_rhs< Scalar, Index, DataMapper, nr, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::internal::sparse_matrix_block_impl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols >::operator=(), packetmath(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::panel_bmod(), Eigen::SparseMatrix< scalar_t >::reserveInnerVectors(), internal::packed_rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::setBlockStructure(), and Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::setShift().
offsets
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set offsets
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by InsertZeros::eval().
origin
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set origin
Definition at line 12 of file gnuplot_common_settings.hh.
ratio
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size ratio
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOneStep(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorageOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), and Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep().
samples
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set samples
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by svd_fill_random().
scale
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set set set set surface set nocontour set clabel set mapping cartesian set nohidden3d set cntrparam order set cntrparam linear set cntrparam levels auto set cntrparam points set size set set xzeroaxis lt lw set x2zeroaxis lt lw set yzeroaxis lt lw set y2zeroaxis lt lw set tics in set ticslevel set tics scale
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by Eigen::BDCSVD< _MatrixType >::compute(), Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), Eigen::RealSchur< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), eigen33(), FancySpheres::FancySpheres(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Identity(), lapackNorm(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*=(), rotg(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::setShift(), and Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNorm().
view
set noclip points set clip one set noclip two set bar set border lt lw set xdata set ydata set zdata set x2data set y2data set boxwidth set dummy y set format x g set format y g set format x2 g set format y2 g set format z g set angles radians set nogrid set key title set key left top Right noreverse box linetype linewidth samplen spacing width set nolabel set noarrow set nologscale set logscale x set set pointsize set encoding default set nopolar set noparametric set view
Definition at line 12 of file gnuplot_common_settings.hh.
x
Scalar * x = reinterpret_cast<Scalar*>(px)
Examples:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Definition at line 12 of file gnuplot_common_settings.hh.
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), Eigen::PastixBase< PastixLU< _MatrixType > >::_solve_impl(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::_solve_impl(), Eigen::LeastSquaresConjugateGradient< _MatrixType, _Preconditioner >::_solve_impl(), Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solve_impl(), Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::internal::apply_rotation_in_the_plane(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheLeft(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheRight(), Eigen::Array< StorageIndex, 64, 1, DontAlign >::Array(), array_special_functions(), asum(), basicStuff(), testing::Benchmark::Benchmark(), Bennett5_functor::Bennett5_functor(), Eigen::betainc(), Eigen::internal::bicgstab(), BoxBOD_functor::BoxBOD_functor(), bug_817(), call_solver(), cblat1(), cblat2(), cblat3(), cchk1(), cchk2(), cchk3(), cchk4(), cchk5(), cchk6(), mpfr::ceil(), chbmv_(), check(), check_atan2(), check_in_range(), check_qtvector_matrix(), check_qtvector_quaternion(), check_qtvector_transform(), check_sparse_solving(), check_sparse_solving_real_cases(), check_stddeque_matrix(), check_stddeque_quaternion(), check_stddeque_transform(), check_stdlist_matrix(), check_stdlist_quaternion(), check_stdlist_transform(), check_stdvector_matrix(), check_stdvector_quaternion(), check_stdvector_transform(), check_unalignedassert_good(), chpmv_(), cmmch(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), conj(), Eigen::conj(), Eigen::internal::conjugate_gradient(), mpfr::const_catalan(), mpfr::const_euler(), mpfr::const_infinity(), mpfr::const_log2(), mpfr::const_pi(), copy(), csr_sum_duplicates(), ctms_decompositions(), dblat1(), dblat2(), dblat3(), dchk1(), dchk2(), dchk3(), dchk4(), dchk5(), dchk6(), determinant(), Eigen::SuperLU< _MatrixType >::determinant(), Eigen::NumericalDiff< _Functor, mode >::df(), chwirut2_functor::df(), hahn1_functor::df(), MGH09_functor::df(), thurber_functor::df(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmres(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresApplyDeflation(), mpfr::div_2si(), mpfr::div_2ui(), dmmch(), Eigen::internal::dogleg(), dont_over_optimize(), dot(), dsbmv_(), dsdot(), dspmv_(), eckerle4_functor::eckerle4_functor(), Eigen::EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(), Eigen::internal::blas_traits< CwiseNullaryOp< scalar_constant_op< Scalar >, Plain1 > >::extract(), mpfr::fac_ui(), fft_rmse(), findidx(), mpfr::floor(), Eigen::internal::generic_fast_tanh_float(), ger(), gerc(), geru(), get_compact_vector(), mpfr::mpreal::get_default_prec(), Eigen::internal::gmres(), mpfr::grandom(), header(), hemv(), her(), her2(), hpr(), hpr2(), init_matrix_symm(), DenseLM< Scalar >::initPoints(), sparseGaussianTest< Scalar >::initPoints(), inplace(), Eigen::isNotNaN(), itest1(), lanczos1_functor::lanczos1_functor(), mpfr::ldexp(), Eigen::internal::least_square_conjugate_gradient(), Eigen::LevenbergMarquardt< _FunctorType >::LevenbergMarquardt(), mpfr::lgamma(), Eigen::internal::lmpar(), Eigen::internal::lmpar2(), Eigen::internal::lmqrsolv(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::logDeterminant(), mpfr::machine_epsilon(), main(), Trackball::mapToSphere(), Eigen::Matrix< Scalar, Deg, 1 >::Matrix(), MGH10_functor::MGH10_functor(), MGH17_functor::MGH17_functor(), misra1d_functor::misra1d_functor(), sparseGaussianTest< Scalar >::model(), DenseLM< Scalar >::model(), mpfr::mpreal::mpreal(), mpfr::mul_2si(), mpfr::mul_2ui(), Eigen::internal::negate(), nrm2(), CwiseClampOp< Scalar >::operator()(), Eigen::internal::conj_if< false >::operator()(), TestFunc1< _Scalar, NX, NY >::operator()(), chwirut2_functor::operator()(), hahn1_functor::operator()(), MGH09_functor::operator()(), thurber_functor::operator()(), mpfr::mpreal::operator++(), mpfr::operator-(), mpfr::mpreal::operator--(), mpfr::operator/(), Eigen::SkylineInplaceLU< MatrixType >::orderingMethod(), Eigen::internal::pblend(), Eigen::internal::conj_if< false >::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pcplxflip< Packet2cd >(), Eigen::internal::pcplxflip< Packet2cf >(), Eigen::internal::pcplxflip< Packet4cf >(), Eigen::internal::pexp< Packet4d >(), Eigen::internal::pexp< Packet4f >(), Eigen::internal::pfirst< Packet4f >(), Eigen::internal::pfirst< Packet4i >(), Eigen::internal::pfloor< Packet2d >(), Eigen::internal::plog< Packet4f >(), Eigen::internal::plog< Packet8f >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::poly_eval(), Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::pow(), mpfr::pow(), product(), Eigen::internal::prsqrt< Packet4d >(), Eigen::internal::prsqrt< Packet4f >(), Eigen::internal::psin< Packet8f >(), Eigen::internal::psqrt< Packet4d >(), Eigen::internal::psqrt< Packet8f >(), Eigen::internal::pstore1< Packet2d >(), Eigen::internal::ptanh< Packet8f >(), Eigen::internal::ptranspose(), qr(), qr_fixedsize(), qr_kahan_matrix(), Eigen::internal::qrsolv(), ramp(), mpfr::random2(), Eigen::internal::RandomToTypeNormal(), rat42_functor::rat42_functor(), rat43_functor::rat43_functor(), real(), Eigen::real(), mpfr::rec_sqrt(), MandelbrotThread::render(), resizeLikeTest(), reverse(), rot(), mpfr::round(), Eigen::internal::reverse_packet_cond< PacketType, false >::run(), Eigen::internal::cast_impl< Real, std::complex< Real > >::run(), Eigen::internal::take_matrix_for_product< MatrixOrTransformType >::run(), sblat1(), sblat2(), sblat3(), schk1(), schk2(), schk3(), schk4(), schk5(), schk6(), sdsdot(), mpfr::mpreal::set_exp(), setinnerrand_eigen(), Eigen::DGMRES< _MatrixType, _Preconditioner >::setMaxEigenv(), setrand_eigen_compact(), setrand_eigen_dynamic(), setrand_eigen_gnu_hash(), setrand_eigen_google_dense(), setrand_eigen_google_sparse(), setrand_eigen_sumeq(), setrand_scipy(), setrand_ublas_genvec(), setrand_ublas_mapped(), Eigen::BDCSVD< _MatrixType >::setSwitchSize(), sin_over_x(), smmch(), sparse_basic(), sparse_extra(), sparse_product(), spr(), spr2(), SQR(), mpfr::sqrt(), ssbmv_(), sspmv_(), stest(), packet_helper< false, Packet >::store(), mpfr::sum(), svd_least_square(), symv(), syr(), syr2(), tbsv(), test_aliasing(), test_autodiff_hessian(), test_central(), test_denseLM_T(), test_forward(), test_numtraits(), test_random_setter(), test_sparseLM_T(), test_sparseqr_scalar(), test_spqr_scalar(), testChkder(), testdsdot(), testGeneral(), testHybrd(), testHybrd1(), testHybrj(), testHybrj1(), testLmder(), testLmder1(), testLmdif(), testLmdif1(), testLmstr(), testLmstr1(), testLogThenExp(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), testNistThurber(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::toRotationMatrix(), tpmv(), tpsv(), mpfr::trunc(), Eigen::UmfPackLU< _MatrixType >::umfpackReportStatus(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), mpfr::urandom(), mpfr::urandomb(), model_potential::V(), verify_component_wise(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::TensorEvaluator< Arg2Type, Device >::writePacket(), Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorLayoutSwapOp< ArgType >, Device >::writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket(), Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorReverseOp< ReverseDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writePacket(), Eigen::internal::mapbase_evaluator< Map< PlainObjectType, MapOptions, StrideType >, PlainObjectType >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::writePacket(), zblat1(), zblat2(), zblat3(), zchk1(), zchk2(), zchk3(), zchk4(), zchk5(), zchk6(), zhbmv_(), zhpmv_(), zmmch(), and Eigen::PastixBase< PastixLU< _MatrixType > >::~PastixBase().