pairinteraction: Geometry_Module
Geometry_Module
Geometry » Reference
Modules
Global aligned box typedefs
Data Structures
class Eigen::Map< const Quaternion< _Scalar >, _Options >
Quaternion expression mapping a constant memory buffer.
class Eigen::Map< Quaternion< _Scalar >, _Options >
Expression of a quaternion from a memory buffer.
class Eigen::AlignedBox< _Scalar, _AmbientDim >
An axis aligned box.
class Eigen::AngleAxis< _Scalar >
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
class Eigen::Homogeneous< MatrixType, _Direction >
Expression of one (or a set of) homogeneous vector(s)
class Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >
A hyperplane.
class Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >
A parametrized line.
class Eigen::QuaternionBase< Derived >
Base class for quaternion expressions.
class Eigen::Quaternion< _Scalar, _Options >
The quaternion class used to represent 3D orientations and rotations.
class Eigen::Rotation2D< _Scalar >
Represents a rotation/orientation in a 2 dimensional space.
class Scaling
Represents a generic uniform scaling transformation.
class Eigen::Transform< _Scalar, _Dim, _Mode, _Options >
Represents an homogeneous transformation in a N dimensional space.
class Eigen::Translation< _Scalar, _Dim >
Represents a translation transformation.
Typedefs
typedef AngleAxis< float > Eigen::AngleAxisf
typedef AngleAxis< double > Eigen::AngleAxisd
typedef Quaternion< float > Eigen::Quaternionf
typedef Quaternion< double > Eigen::Quaterniond
typedef Map< Quaternion< float >, 0 > Eigen::QuaternionMapf
typedef Map< Quaternion< double >, 0 > Eigen::QuaternionMapd
typedef Map< Quaternion< float >, Aligned > Eigen::QuaternionMapAlignedf
typedef Map< Quaternion< double >, Aligned > Eigen::QuaternionMapAlignedd
typedef Rotation2D< float > Eigen::Rotation2Df
typedef Rotation2D< double > Eigen::Rotation2Dd
typedef DiagonalMatrix< float, 2 > Eigen::AlignedScaling2f
typedef DiagonalMatrix< double, 2 > Eigen::AlignedScaling2d
typedef DiagonalMatrix< float, 3 > Eigen::AlignedScaling3f
typedef DiagonalMatrix< double, 3 > Eigen::AlignedScaling3d
typedef Transform< float, 2, Isometry > Eigen::Isometry2f
typedef Transform< float, 3, Isometry > Eigen::Isometry3f
typedef Transform< double, 2, Isometry > Eigen::Isometry2d
typedef Transform< double, 3, Isometry > Eigen::Isometry3d
typedef Transform< float, 2, Affine > Eigen::Affine2f
typedef Transform< float, 3, Affine > Eigen::Affine3f
typedef Transform< double, 2, Affine > Eigen::Affine2d
typedef Transform< double, 3, Affine > Eigen::Affine3d
typedef Transform< float, 2, AffineCompact > Eigen::AffineCompact2f
typedef Transform< float, 3, AffineCompact > Eigen::AffineCompact3f
typedef Transform< double, 2, AffineCompact > Eigen::AffineCompact2d
typedef Transform< double, 3, AffineCompact > Eigen::AffineCompact3d
typedef Transform< float, 2, Projective > Eigen::Projective2f
typedef Transform< float, 3, Projective > Eigen::Projective3f
typedef Transform< double, 2, Projective > Eigen::Projective2d
typedef Transform< double, 3, Projective > Eigen::Projective3d
typedef Translation< float, 2 > Eigen::Translation2f
typedef Translation< double, 2 > Eigen::Translation2d
typedef Translation< float, 3 > Eigen::Translation3f
typedef Translation< double, 3 > Eigen::Translation3d
Functions
UniformScaling< float > Eigen::Scaling (float s)
UniformScaling< double > Eigen::Scaling (double s)
template<typename RealScalar >
UniformScaling< std::complex< RealScalar > > Eigen::Scaling (const std::complex< RealScalar > &s)
template<typename Scalar >
DiagonalMatrix< Scalar, 2 > Eigen::Scaling (const Scalar &sx, const Scalar &sy)
template<typename Scalar >
DiagonalMatrix< Scalar, 3 > Eigen::Scaling (const Scalar &sx, const Scalar &sy, const Scalar &sz)
template<typename Derived >
const DiagonalWrapper< const Derived > Eigen::Scaling (const MatrixBase< Derived > &coeffs)
template<typename Derived , typename OtherDerived >
internal::umeyama_transform_matrix_type< Derived, OtherDerived >::type Eigen::umeyama (const MatrixBase< Derived > &src, const MatrixBase< OtherDerived > &dst, bool with_scaling=true)
Returns the transformation between two point sets.
EIGEN_DEVICE_FUNC Matrix< Scalar, 3, 1 > Eigen::MatrixBase< Derived >::eulerAngles (Index a0, Index a1, Index a2) const
EIGEN_DEVICE_FUNC HomogeneousReturnType Eigen::MatrixBase< Derived >::homogeneous () const
EIGEN_DEVICE_FUNC HomogeneousReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::homogeneous () const
EIGEN_DEVICE_FUNC const HNormalizedReturnType Eigen::MatrixBase< Derived >::hnormalized () const
homogeneous normalization
EIGEN_DEVICE_FUNC const HNormalizedReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::hnormalized () const
column or row-wise homogeneous normalization
template<typename OtherDerived >
EIGEN_DEVICE_FUNC MatrixBase< Derived >::template cross_product_return_type< OtherDerived >::type Eigen::MatrixBase< Derived >::cross (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC PlainObject Eigen::MatrixBase< Derived >::cross3 (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const CrossReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::cross (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC PlainObject Eigen::MatrixBase< Derived >::unitOrthogonal (void) const
template<typename Derived , typename Scalar >
operator* (const MatrixBase< Derived > &matrix, const UniformScaling< Scalar > &s)
Detailed Description
Typedef Documentation
Affine2d
typedef Transform<double,2,Affine> Eigen::Affine2d
Definition at line 712 of file Transform.h.
Affine2f
typedef Transform<float,2,Affine> Eigen::Affine2f
Definition at line 708 of file Transform.h.
Affine3d
typedef Transform<double,3,Affine> Eigen::Affine3d
Definition at line 714 of file Transform.h.
Affine3f
typedef Transform<float,3,Affine> Eigen::Affine3f
Definition at line 710 of file Transform.h.
AffineCompact2d
typedef Transform<double,2,AffineCompact> Eigen::AffineCompact2d
Definition at line 721 of file Transform.h.
AffineCompact2f
typedef Transform<float,2,AffineCompact> Eigen::AffineCompact2f
Definition at line 717 of file Transform.h.
AffineCompact3d
typedef Transform<double,3,AffineCompact> Eigen::AffineCompact3d
Definition at line 723 of file Transform.h.
AffineCompact3f
typedef Transform<float,3,AffineCompact> Eigen::AffineCompact3f
Definition at line 719 of file Transform.h.
AlignedScaling2d
typedef DiagonalMatrix<double,2> Eigen::AlignedScaling2d
Deprecated:
Definition at line 148 of file Scaling.h.
AlignedScaling2f
typedef DiagonalMatrix<float, 2> Eigen::AlignedScaling2f
Deprecated:
Definition at line 146 of file Scaling.h.
AlignedScaling3d
typedef DiagonalMatrix<double,3> Eigen::AlignedScaling3d
Deprecated:
Definition at line 152 of file Scaling.h.
AlignedScaling3f
typedef DiagonalMatrix<float, 3> Eigen::AlignedScaling3f
Deprecated:
Definition at line 150 of file Scaling.h.
AngleAxisd
typedef AngleAxis<double> Eigen::AngleAxisd
double precision angle-axis type
Definition at line 160 of file AngleAxis.h.
AngleAxisf
typedef AngleAxis<float> Eigen::AngleAxisf
single precision angle-axis type
Definition at line 157 of file AngleAxis.h.
Isometry2d
typedef Transform<double,2,Isometry> Eigen::Isometry2d
Definition at line 703 of file Transform.h.
Isometry2f
typedef Transform<float,2,Isometry> Eigen::Isometry2f
Definition at line 699 of file Transform.h.
Isometry3d
typedef Transform<double,3,Isometry> Eigen::Isometry3d
Definition at line 705 of file Transform.h.
Isometry3f
typedef Transform<float,3,Isometry> Eigen::Isometry3f
Definition at line 701 of file Transform.h.
Projective2d
typedef Transform<double,2,Projective> Eigen::Projective2d
Definition at line 730 of file Transform.h.
Projective2f
typedef Transform<float,2,Projective> Eigen::Projective2f
Definition at line 726 of file Transform.h.
Projective3d
typedef Transform<double,3,Projective> Eigen::Projective3d
Definition at line 732 of file Transform.h.
Projective3f
typedef Transform<float,3,Projective> Eigen::Projective3f
Definition at line 728 of file Transform.h.
Quaterniond
typedef Quaternion<double> Eigen::Quaterniond
double precision quaternion type
Definition at line 305 of file Quaternion.h.
Quaternionf
typedef Quaternion<float> Eigen::Quaternionf
single precision quaternion type
Definition at line 302 of file Quaternion.h.
QuaternionMapAlignedd
typedef Map<Quaternion<double>, Aligned> Eigen::QuaternionMapAlignedd
Map a 16-byte aligned array of double precision scalars as a quaternion
Definition at line 417 of file Quaternion.h.
QuaternionMapAlignedf
typedef Map<Quaternion<float>, Aligned> Eigen::QuaternionMapAlignedf
Map a 16-byte aligned array of single precision scalars as a quaternion
Definition at line 414 of file Quaternion.h.
QuaternionMapd
typedef Map<Quaternion<double>, 0> Eigen::QuaternionMapd
Map an unaligned array of double precision scalars as a quaternion
Definition at line 411 of file Quaternion.h.
QuaternionMapf
typedef Map<Quaternion<float>, 0> Eigen::QuaternionMapf
Map an unaligned array of single precision scalars as a quaternion
Definition at line 408 of file Quaternion.h.
Rotation2Dd
typedef Rotation2D<double> Eigen::Rotation2Dd
double precision 2D rotation type
Definition at line 168 of file Rotation2D.h.
Rotation2Df
typedef Rotation2D<float> Eigen::Rotation2Df
single precision 2D rotation type
Definition at line 165 of file Rotation2D.h.
Translation2d
typedef Translation<double,2> Eigen::Translation2d
Definition at line 175 of file Translation.h.
Translation2f
typedef Translation<float, 2> Eigen::Translation2f
Definition at line 174 of file Translation.h.
Translation3d
typedef Translation<double,3> Eigen::Translation3d
Definition at line 177 of file Translation.h.
Translation3f
typedef Translation<float, 3> Eigen::Translation3f
Definition at line 176 of file Translation.h.
Function Documentation
cross() [1/2]
template<typename Derived> template<typename OtherDerived > EIGEN_DEVICE_FUNC MatrixBase<Derived>::template cross_product_return_type<OtherDerived>::type Eigen::MatrixBase< Derived >::cross (const MatrixBase< OtherDerived > & other) const inline
Returns
the cross product of *this and other
Here is a very good explanation of cross-product: http://xkcd.com/199/
With complex numbers, the cross product is implemented as \((\mathbf{a}+i\mathbf{b}) \times (\mathbf{c}+i\mathbf{d}) = (\mathbf{a} \times \mathbf{c} - \mathbf{b} \times \mathbf{d}) - i(\mathbf{a} \times \mathbf{d} - \mathbf{b} \times \mathbf{c})\)
See also
MatrixBase::cross3()
Definition at line 34 of file OrthoMethods.h.
cross() [2/2]
template<typename ExpressionType , int Direction> template<typename OtherDerived > EIGEN_DEVICE_FUNC const VectorwiseOp< ExpressionType, Direction >::CrossReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::cross (const MatrixBase< OtherDerived > & other) const
Returns
a matrix expression of the cross product of each column or row of the referenced expression with the other vector.
The referenced matrix must have one dimension equal to 3. The result matrix has the same dimensions than the referenced one.
See also
MatrixBase::cross()
Definition at line 110 of file OrthoMethods.h.
References cols, conjugate(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, mat, res, rows, and Eigen::Vertical.
cross3()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC MatrixBase< Derived >::PlainObject Eigen::MatrixBase< Derived >::cross3 (const MatrixBase< OtherDerived > & other) const inline
Returns
the cross product of *this and other using only the x, y, and z coefficients
The size of *this and other must be four. This function is especially useful when using 4D vectors instead of 3D ones to get advantage of SSE/AltiVec vectorization.
See also
MatrixBase::cross()
Definition at line 82 of file OrthoMethods.h.
eulerAngles()
template<typename Derived > EIGEN_DEVICE_FUNC Matrix< typename MatrixBase< Derived >::Scalar, 3, 1 > Eigen::MatrixBase< Derived >::eulerAngles (Index a0, Index a1, Index a2) const inline
Returns
the Euler-angles of the rotation matrix *this using the convention defined by the triplet (a0,a1,a2)
Each of the three parameters a0,a1,a2 represents the respective rotation axis as an integer in {0,1,2}. For instance, in:
Vector3f ea = mat.eulerAngles(2, 0, 2);
"2" represents the z axis and "0" the x axis, etc. The returned angles are such that we have the following equality:
mat == AngleAxisf(ea[0], Vector3f::UnitZ())
     * AngleAxisf(ea[1], Vector3f::UnitX())
     * AngleAxisf(ea[2], Vector3f::UnitZ());
This corresponds to the right-multiply conventions (with right hand side frames).
The returned angles are in the ranges [0:pi]x[-pi:pi]x[-pi:pi].
See also
class AngleAxis
Definition at line 37 of file EulerAngles.h.
hnormalized() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC const MatrixBase< Derived >::HNormalizedReturnType Eigen::MatrixBase< Derived >::hnormalized () const inline
homogeneous normalization
Returns
a vector expression of the N-1 first coefficients of *this divided by that last coefficient.
This can be used to convert homogeneous coordinates to affine coordinates.
It is essentially a shortcut for:
this->head(this->size()-1)/this->coeff(this->size()-1);
Example:
Output:
See also
VectorwiseOp::hnormalized()
Definition at line 172 of file Homogeneous.h.
hnormalized() [2/2]
template<typename ExpressionType , int Direction> EIGEN_DEVICE_FUNC const VectorwiseOp< ExpressionType, Direction >::HNormalizedReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::hnormalized () const inline
column or row-wise homogeneous normalization
Returns
an expression of the first N-1 coefficients of each column (or row) of *this divided by the last coefficient of each column (or row).
This can be used to convert homogeneous coordinates to affine coordinates.
It is conceptually equivalent to calling MatrixBase::hnormalized() to each column (or row) of *this.
Example:
Output:
See also
MatrixBase::hnormalized()
Definition at line 196 of file Homogeneous.h.
References cols, Eigen::Horizontal, rows, and Eigen::Vertical.
homogeneous() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC MatrixBase< Derived >::HomogeneousReturnType Eigen::MatrixBase< Derived >::homogeneous () const inline
Returns
a vector expression that is one longer than the vector argument, with the value 1 symbolically appended as the last coefficient.
This can be used to convert affine coordinates to homogeneous coordinates.
Example:
Output:
See also
VectorwiseOp::homogeneous(), class Homogeneous
Definition at line 130 of file Homogeneous.h.
homogeneous() [2/2]
template<typename ExpressionType , int Direction> EIGEN_DEVICE_FUNC Homogeneous< ExpressionType, Direction > Eigen::VectorwiseOp< ExpressionType, Direction >::homogeneous () const inline
Returns
an expression where the value 1 is symbolically appended as the final coefficient to each column (or row) of the matrix.
This can be used to convert affine coordinates to homogeneous coordinates.
Example:
Output:
See also
MatrixBase::homogeneous(), class Homogeneous
Definition at line 148 of file Homogeneous.h.
operator*()
template<typename Derived , typename Scalar > operator* (const MatrixBase< Derived > & matrix, const UniformScaling< Scalar > & s) related
Concatenates a linear transformation matrix and a uniform scaling
Definition at line 117 of file Scaling.h.
Referenced by binaryExpr().
Scaling() [1/6]
UniformScaling<float> Eigen::Scaling (float s) inline
Constructs a uniform scaling from scale factor s
Definition at line 121 of file Scaling.h.
References s.
Referenced by FancySpheres::draw(), FancySpheres::FancySpheres(), test_openglsupport(), and transform_associativity().
Scaling() [2/6]
UniformScaling<double> Eigen::Scaling (double s) inline
Constructs a uniform scaling from scale factor s
Definition at line 123 of file Scaling.h.
References s.
Scaling() [3/6]
template<typename RealScalar > UniformScaling<std::complex<RealScalar> > Eigen::Scaling (const std::complex< RealScalar > & s) inline
Constructs a uniform scaling from scale factor s
Definition at line 126 of file Scaling.h.
References s.
Scaling() [4/6]
template<typename Scalar > DiagonalMatrix<Scalar,2> Eigen::Scaling (const Scalar & sx, const Scalar & sy) inline
Constructs a 2D axis aligned scaling
Definition at line 131 of file Scaling.h.
Scaling() [5/6]
template<typename Scalar > DiagonalMatrix<Scalar,3> Eigen::Scaling (const Scalar & sx, const Scalar & sy, const Scalar & sz) inline
Constructs a 3D axis aligned scaling
Definition at line 135 of file Scaling.h.
Scaling() [6/6]
template<typename Derived > const DiagonalWrapper<const Derived> Eigen::Scaling (const MatrixBase< Derived > & coeffs) inline
Constructs an axis aligned scaling expression from vector expression coeffs This is an alias for coeffs.asDiagonal()
Definition at line 142 of file Scaling.h.
References Eigen::MatrixBase< Derived >::asDiagonal().
umeyama()
template<typename Derived , typename OtherDerived > internal::umeyama_transform_matrix_type<Derived, OtherDerived>::type Eigen::umeyama (const MatrixBase< Derived > & src, const MatrixBase< OtherDerived > & dst, bool with_scaling = true)
Returns the transformation between two point sets.
The algorithm is based on: "Least-squares estimation of transformation parameters between two point patterns", Shinji Umeyama, PAMI 1991, DOI: 10.1109/34.88573
It estimates parameters \(c, \mathbf{R}, \) and \(\mathbf{t} \) such that
\begin{align*} \frac{1}{n} \sum_{i=1}^n \vert\vert y_i - (c\mathbf{R}x_i + \mathbf{t}) \vert\vert_2^2 \end{align*}
is minimized.
The algorithm is based on the analysis of the covariance matrix \(\Sigma_{\mathbf{x}\mathbf{y}} \in \mathbb{R}^{d \times d} \) of the input point sets \(\mathbf{x} \) and \(\mathbf{y} \) where \(d\) is corresponding to the dimension (which is typically small). The analysis is involving the SVD having a complexity of \(O(d^3)\) though the actual computational effort lies in the covariance matrix computation which has an asymptotic lower bound of \(O(dm)\) when the input point sets have dimension \(d \times m\).
Currently the method is working only for floating point matrices.
Todo:
Should the return type of umeyama() become a Transform?
Parameters
src Source points \(\mathbf{x} = \left(x_1, \hdots, x_n \right) \).
dst Destination points \(\mathbf{y} = \left(y_1, \hdots, y_n \right) \).
with_scaling Sets \(c=1 \) when false is passed.
Returns
The homogeneous transformation
\begin{align*} T = \begin{bmatrix} c\mathbf{R} & \mathbf{t} \\ \mathbf{0} & 1 \end{bmatrix} \end{align*}
minimizing the resudiual above. This transformation is always returned as an Eigen::Matrix.
Definition at line 95 of file Umeyama.h.
References c, Eigen::DenseBase< Derived >::colwise(), Eigen::ComputeFullU, Eigen::ComputeFullV, EIGEN_SIZE_MIN_PREFER_DYNAMIC, EIGEN_STATIC_ASSERT, m, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixU(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV(), n, Eigen::DenseBase< Derived >::rowwise(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::singularValues(), and svd().
Referenced by run_fixed_size_test(), and run_test().
unitOrthogonal()
template<typename Derived > EIGEN_DEVICE_FUNC MatrixBase< Derived >::PlainObject Eigen::MatrixBase< Derived >::unitOrthogonal (void) const inline
Returns
a unit vector which is orthogonal to *this
The size of *this must be at least 2. If the size is exactly 2, then the returned vector is a counter clock wise rotation of *this, i.e., (-y,x).normalized().
See also
cross()
Definition at line 226 of file OrthoMethods.h.