pairinteraction: Householder_Module
Householder_Module
Dense matrix and array manipulation » Reference
Data Structures
class Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >
Sequence of Householder reflections acting on subspaces with decreasing size.
Functions
template<typename VectorsType , typename CoeffsType >
HouseholderSequence< VectorsType, CoeffsType > Eigen::householderSequence (const VectorsType &v, const CoeffsType &h)
Convenience function for constructing a Householder sequence.
template<typename VectorsType , typename CoeffsType >
HouseholderSequence< VectorsType, CoeffsType, OnTheRight > Eigen::rightHouseholderSequence (const VectorsType &v, const CoeffsType &h)
Convenience function for constructing a Householder sequence.
Detailed Description
Function Documentation
householderSequence()
template<typename VectorsType , typename CoeffsType > HouseholderSequence<VectorsType,CoeffsType> Eigen::householderSequence (const VectorsType & v, const CoeffsType & h)
Convenience function for constructing a Householder sequence.
\
Returns
A HouseholderSequence constructed from the specified arguments.
Definition at line 451 of file HouseholderSequence.h.
References v.
Referenced by Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::_solve_impl(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::_solve_impl(), and Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::_solve_impl().
rightHouseholderSequence()
template<typename VectorsType , typename CoeffsType > HouseholderSequence<VectorsType,CoeffsType,OnTheRight> Eigen::rightHouseholderSequence (const VectorsType & v, const CoeffsType & h)
Convenience function for constructing a Householder sequence.
\
Returns
A HouseholderSequence constructed from the specified arguments.
This function differs from householderSequence() in that the template argument OnTheSide of the constructed HouseholderSequence is set to OnTheRight, instead of the default OnTheLeft.
Definition at line 463 of file HouseholderSequence.h.
References v.