pairinteraction: /travis/libpairinteraction/eigen/test/householder.cpp File Reference
householder.cpp File Reference
#include "main.h"
#include <Eigen/QR>
Functions
template<typename MatrixType >
void householder (const MatrixType &m)
void test_householder ()
Function Documentation
householder()
template<typename MatrixType > void householder (const MatrixType & m)
Definition at line 13 of file householder.cpp.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), alpha, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), cols, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), hc, Eigen::HouseholderQR< _MatrixType >::hCoeffs(), imag(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length(), m1, m2(), Eigen::HouseholderQR< _MatrixType >::matrixQR(), max, qr(), rows, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength(), setZero(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose(), v1(), v2(), VERIFY, VERIFY_IS_APPROX, and VERIFY_IS_MUCH_SMALLER_THAN.
test_householder()
void test_householder ()
Definition at line 126 of file householder.cpp.
References i.