pairinteraction: /travis/libpairinteraction/eigen/bench/btl/generic_bench/init/init_matrix.hh File Reference
init_matrix.hh File Reference
Functions
template<double init_function, class Vector >
BTL_DONT_INLINE void init_row (Vector &X, int size, int row)
template<double init_function, class Vector >
BTL_DONT_INLINE void init_matrix (Vector &A, int size)
template<double init_function, class Matrix >
BTL_DONT_INLINE void init_matrix_symm (Matrix &A, int size)
Function Documentation
init_matrix()
template<double init_function, class Vector > BTL_DONT_INLINE void init_matrix (Vector & A, int size)
Definition at line 43 of file init_matrix.hh.
References row(), and size.
init_matrix_symm()
template<double init_function, class Matrix > BTL_DONT_INLINE void init_matrix_symm (Matrix & A, int size)
Definition at line 51 of file init_matrix.hh.
References col(), resize(), row(), and x.
init_row()
template<double init_function, class Vector > BTL_DONT_INLINE void init_row (Vector & X, int size, int row)
Definition at line 28 of file init_matrix.hh.
References j.