pairinteraction: /travis/libpairinteraction/eigen/test/inplace_decomposition.cpp File Reference
inplace_decomposition.cpp File Reference
#include "main.h"
#include <Eigen/LU>
#include <Eigen/Cholesky>
#include <Eigen/QR>
Functions
template<typename DecType , typename MatrixType >
void inplace (bool square=false, bool SPD=false)
void test_inplace_decomposition ()
Function Documentation
inplace()
template<typename DecType , typename MatrixType > void inplace (bool square = false, bool SPD = false)
Definition at line 17 of file inplace_decomposition.cpp.
References b, cols, Eigen::Dynamic, e(), EIGEN_TEST_MAX_SIZE, rows, Eigen::SPD, square(), VERIFY_IS_APPROX, VERIFY_IS_EQUAL, VERIFY_IS_NOT_APPROX, and x.
Referenced by Eigen::internal::fftw_impl< _Scalar >::get_plan().
test_inplace_decomposition()
void test_inplace_decomposition ()
Definition at line 82 of file inplace_decomposition.cpp.
References EIGEN_UNUSED, and i.