pairinteraction: /travis/libpairinteraction/Interface.cpp File Reference
Interface.cpp File Reference
#include "Communication.h"
#include "ConfParser.h"
#include "HamiltonianOne.h"
#include "HamiltonianTwo.h"
#include <codecvt>
#include <iostream>
#include <locale>
#include <memory>
#include <boost/filesystem.hpp>
Functions
int thread_ctrl (int num_threads)
int compute (const std::string &config_name, const std::string &output_name, std::string const &endpoint)
int mainMatrixElement (std::string const &element, std::string const &row, std::string const &col, int power)
Function Documentation
compute()
int compute (const std::string & config_name, const std::string & output_name, std::string const & endpoint)
Definition at line 59 of file Interface.cpp.
References Configuration::count(), BasisnamesOne::fromBoth(), BasisnamesOne::fromFirst(), BasisnamesOne::fromSecond(), Configuration::load_from_json(), zmq::endpoint::name, and Eigen::setNbThreads().
mainMatrixElement()
int mainMatrixElement (std::string const & element, std::string const & row, std::string const & col, int power)
Definition at line 126 of file Interface.cpp.
References BasisnamesOne::fromStates(), StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
thread_ctrl()
int thread_ctrl (int num_threads)
Definition at line 42 of file Interface.cpp.
References zmq::endpoint::name.