pairinteraction: /travis/libpairinteraction/Interface.h File Reference
Interface.h File Reference
#include <string>
Functions
int thread_ctrl (int num_threads=-1)
int compute (std::string const &config_name, std::string const &output_name, std::string const &wendpoint)
int mainMatrixElement (std::string const &element, std::string const &row, std::string const &col, int power)
Function Documentation
compute()
int compute (std::string const & config_name, std::string const & output_name, std::string const & wendpoint)
Definition at line 59 of file Interface.cpp.
References Configuration::count(), BasisnamesOne::fromBoth(), BasisnamesOne::fromFirst(), BasisnamesOne::fromSecond(), Configuration::load_from_json(), and zmq::endpoint::name.
Referenced by main().
mainMatrixElement()
int mainMatrixElement (std::string const & element, std::string const & row, std::string const & col, int power)
Definition at line 126 of file Interface.cpp.
References BasisnamesOne::fromStates(), StateOne::j, StateOne::l, StateOne::m, and StateOne::n.
thread_ctrl()
int thread_ctrl (int num_threads = -1)
Definition at line 42 of file Interface.cpp.
References zmq::endpoint::name.