pairinteraction: /travis/libpairinteraction/eigen/bench/perf_monitoring/gemm/lazy_gemm.cpp File Reference
lazy_gemm.cpp File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <Eigen/Core>
#include "../../BenchTimer.h"
Typedefs
typedef SCALAR Scalar
Functions
template<typename MatA , typename MatB , typename MatC >
EIGEN_DONT_INLINE void lazy_gemm (const MatA &A, const MatB &B, MatC &C)
template<int m, int n, int k, int TA>
EIGEN_DONT_INLINE double bench ()
template<int m, int n, int k>
double bench_t (int t)
EIGEN_DONT_INLINE double bench_mnk (int m, int n, int k, int t)
int main (int argc, char **argv)
Typedef Documentation
Scalar
typedef SCALAR Scalar
Definition at line 12 of file lazy_gemm.cpp.
Function Documentation
bench()
template<int m, int n, int k, int TA> EIGEN_DONT_INLINE double bench ()
Definition at line 26 of file lazy_gemm.cpp.
References BENCH, Eigen::BenchTimer::best(), e(), lazy_gemm(), m, max, min, and n.
bench_mnk()
EIGEN_DONT_INLINE double bench_mnk (int m, int n, int k, int t)
Definition at line 63 of file lazy_gemm.cpp.
Referenced by main().
bench_t()
template<int m, int n, int k> double bench_t (int t)
Definition at line 54 of file lazy_gemm.cpp.
References EIGEN_DONT_INLINE.
lazy_gemm()
template<typename MatA , typename MatB , typename MatC > EIGEN_DONT_INLINE void lazy_gemm (const MatA & A, const MatB & B, MatC & C)
Definition at line 16 of file lazy_gemm.cpp.
References EIGEN_DONT_INLINE.
Referenced by bench().
main()
int main (int argc, char ** argv)
Definition at line 83 of file lazy_gemm.cpp.
References bench_mnk(), m, n, and results.