pairinteraction: /travis/libpairinteraction/eigen/blas/level1_impl.h File Reference
level1_impl.h File Reference
#include "common.h"
Functions
int EIGEN_BLAS_FUNC() axpy (const int *n, const RealScalar *palpha, const RealScalar *px, const int *incx, RealScalar *py, const int *incy)
int EIGEN_BLAS_FUNC() copy (int *n, RealScalar *px, int *incx, RealScalar *py, int *incy)
int EIGEN_CAT (EIGEN_CAT(i, SCALAR_SUFFIX), amax_)(int *n
if incx make_vector (x, *n).cwiseAbs().maxCoeff(&ret)
else make_vector (x, *n, std::abs(*incx)).cwiseAbs().maxCoeff(&ret)
return int (ret)+1
int EIGEN_CAT (EIGEN_CAT(i, SCALAR_SUFFIX), amin_)(int *n
int EIGEN_BLAS_FUNC() rotg (RealScalar *pa, RealScalar *pb, RealScalar *pc, RealScalar *ps)
int EIGEN_BLAS_FUNC() scal (int *n, RealScalar *palpha, RealScalar *px, int *incx)
int EIGEN_BLAS_FUNC() swap (int *n, RealScalar *px, int *incx, RealScalar *py, int *incy)
Variables
int RealScalar * px
int RealScalar int * incx
Scalar * x = reinterpret_cast<Scalar*>(px)
DenseIndex ret = int(internal::llt_inplace<Scalar, Lower>::blocked(A))
Function Documentation
axpy()
int EIGEN_BLAS_FUNC() axpy (const int * n, const RealScalar * palpha, const RealScalar * px, const int * incx, RealScalar * py, const int * incy)
Definition at line 12 of file level1_impl.h.
References alpha, incx, incy, make_vector(), n, palpha, px, py, x, and y.
Referenced by Action_axpy< Interface >::calculate().
copy()
int EIGEN_BLAS_FUNC() copy (int * n, RealScalar * px, int * incx, RealScalar * py, int * incy)
Definition at line 29 of file level1_impl.h.
References i, incx, incy, make_vector(), n, px, py, x, and y.
EIGEN_CAT() [1/2]
int EIGEN_CAT (EIGEN_CAT(i, SCALAR_SUFFIX) , amax_)
EIGEN_CAT() [2/2]
int EIGEN_CAT (EIGEN_CAT(i, SCALAR_SUFFIX) , amin_)
int()
return int (ret)
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::adjoint(), testing::Benchmark::Benchmark(), mpfr::bits2digits(), Eigen::internal::call_assignment_no_alias(), Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::check_coordinates(), check_qtvector_quaternion(), check_qtvector_transform(), cod_fixedsize(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::colIndexByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::colIndexByOuterInner(), Eigen::Homogeneous< MatrixType, _Direction >::cols(), Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), std::numeric_limits< mpfr::mpreal >::digits(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::dumpMemory(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE(), gemv(), mpfr::mpreal::get_default_prec(), mpfr::mpreal::getPrecision(), Eigen::KdBVH< _Scalar, _Dim, _Object >::getVolume(), hemv(), her(), her2(), hpr(), hpr2(), initSparse(), Eigen::DenseBase< Derived >::innerSize(), insertCoefficient(), Eigen::IOFormat::IOFormat(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::lazyProduct(), main(), Trackball::mapToSphere(), Eigen::internal::get_boxes_helper< ObjectList, VolumeList, int >::operator()(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator*(), Eigen::DenseBase< Derived >::outerSize(), Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::outerStride(), Eigen::Map< SparseMatrix< _Scalar, _Flags, _StorageIndex > >::outerStride(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::diagonal_product_evaluator_base< Lhs, Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight >::packet_impl(), MandelbrotWidget::paintEvent(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::internal::kissfft_impl< _Scalar >::PlanKey(), qr_fixedsize(), Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::rowIndexByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::rowIndexByOuterInner(), Eigen::Homogeneous< MatrixType, _Direction >::rows(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rows(), Eigen::internal::default_digits10_impl< T, false, false >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, Dynamic >::run(), Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >::run(), Eigen::internal::triangular_product_impl< Mode, false, Lhs, true, Rhs, false >::run(), Eigen::internal::redux_impl< Func, Derived, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::selfadjoint_product_impl< Lhs, 0, true, Rhs, RhsMode, false >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::first_aligned_impl< Alignment, Derived, false >::run(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, GemvProduct >::scaleAndAddTo(), set_repeat_from_string(), set_seed_from_string(), size_log(), Eigen::internal::SkylineProduct< LhsNested, RhsNested, ProductMode >::SkylineProduct(), Eigen::internal::MappedSuperNodalMatrix< Scalar, StorageIndex >::solveInPlace(), sparse_basic(), sparse_extra(), spr(), spr2(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNorm(), symv(), syr(), syr2(), tbsv(), test_assign(), TreeTest< Dim >::testIntersect1(), TreeTest< Dim >::testIntersect2(), TreeTest< Dim >::testMinimize1(), TreeTest< Dim >::testMinimize2(), tpmv(), tpsv(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), trmv(), and trsv().
make_vector() [1/2]
if incx make_vector (x , * n) &
Referenced by axpy(), copy(), scal(), and swap().
make_vector() [2/2]
else make_vector (x , * n, std::abs * incx) &
rotg()
int EIGEN_BLAS_FUNC() rotg (RealScalar * pa, RealScalar * pb, RealScalar * pc, RealScalar * ps)
Definition at line 76 of file level1_impl.h.
References a, abs(), abs2(), alpha, b, c, conj(), pc, ps, s, scale, and sqrt().
scal()
int EIGEN_BLAS_FUNC() scal (int * n, RealScalar * palpha, RealScalar * px, int * incx)
Definition at line 139 of file level1_impl.h.
References abs(), alpha, incx, make_vector(), palpha, and px.
swap()
int EIGEN_BLAS_FUNC() swap (int * n, RealScalar * px, int * incx, RealScalar * py, int * incy)
Definition at line 152 of file level1_impl.h.
References incy, make_vector(), px, py, reverse(), and y.
Referenced by Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::operator=(), Eigen::Tuple< U, V >::swap(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::swap(), triangular_rect(), and triangular_square().
Variable Documentation
incx
int RealScalar int* incx
Initial value:
{
  if(*n<=0) return 0
Definition at line 55 of file level1_impl.h.
Referenced by axpy(), copy(), and scal().
px
int RealScalar* px
Definition at line 54 of file level1_impl.h.
Referenced by axpy(), copy(), scal(), and swap().
ret
else ret = int(internal::llt_inplace<Scalar, Lower>::blocked(A))
Definition at line 59 of file level1_impl.h.
Referenced by Eigen::atan2(), Eigen::internal::llt_inplace< Scalar, Lower >::blocked(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu(), compute_block_size(), get_compact_vector(), Eigen::nbThreads(), Eigen::internal::p4ui_CONJ_XOR(), print_n< N >::run(), Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run(), Eigen::internal::first_aligned_impl< Alignment, Derived, false >::run(), BtlString::split(), Eigen::test_isApprox(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), and Eigen::verifyIsApprox().
x
Scalar* x = reinterpret_cast<Scalar*>(px)
Definition at line 57 of file level1_impl.h.
Referenced by axpy(), and copy().