pairinteraction: /travis/libpairinteraction/eigen/blas/level2_impl.h File Reference
level2_impl.h File Reference
#include "common.h"
Data Structures
struct general_matrix_vector_product_wrapper< Index, Scalar, StorageOrder, ConjugateLhs, ConjugateRhs >
Functions
int EIGEN_BLAS_FUNC() gemv (const char *opa, const int *m, const int *n, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *pb, const int *incb, const RealScalar *pbeta, RealScalar *pc, const int *incc)
int EIGEN_BLAS_FUNC() trsv (const char *uplo, const char *opa, const char *diag, const int *n, const RealScalar *pa, const int *lda, RealScalar *pb, const int *incb)
int EIGEN_BLAS_FUNC() trmv (const char *uplo, const char *opa, const char *diag, const int *n, const RealScalar *pa, const int *lda, RealScalar *pb, const int *incb)
int EIGEN_BLAS_FUNC() gbmv (char *trans, int *m, int *n, int *kl, int *ku, RealScalar *palpha, RealScalar *pa, int *lda, RealScalar *px, int *incx, RealScalar *pbeta, RealScalar *py, int *incy)
int EIGEN_BLAS_FUNC() tbsv (char *uplo, char *op, char *diag, int *n, int *k, RealScalar *pa, int *lda, RealScalar *px, int *incx)
int EIGEN_BLAS_FUNC() tpmv (char *uplo, char *opa, char *diag, int *n, RealScalar *pap, RealScalar *px, int *incx)
int EIGEN_BLAS_FUNC() tpsv (char *uplo, char *opa, char *diag, int *n, RealScalar *pap, RealScalar *px, int *incx)
Function Documentation
gbmv()
int EIGEN_BLAS_FUNC() gbmv (char * trans, int * m, int * n, int * kl, int * ku, RealScalar * palpha, RealScalar * pa, int * lda, RealScalar * px, int * incx, RealScalar * pbeta, RealScalar * py, int * incy)
GBMV performs one of the matrix-vector operations
y := alpha*A*x + beta*y, or y := alpha*A'*x + beta*y,
where alpha and beta are scalars, x and y are vectors and A is an m by n band matrix, with kl sub-diagonals and ku super-diagonals.
Definition at line 218 of file level2_impl.h.
gemv()
int EIGEN_BLAS_FUNC() gemv (const char * opa, const int * m, const int * n, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * pb, const int * incb, const RealScalar * pbeta, RealScalar * pc, const int * incc)
Definition at line 26 of file level2_impl.h.
References a, alpha, b, c, copy_back(), get_compact_vector(), info, int(), INVALID, lda, m, make_vector(), max, n, NOTR, OP, palpha, pc, SCALAR_SUFFIX_UP, std::swap(), and xerbla_().
tbsv()
int EIGEN_BLAS_FUNC() tbsv (char * uplo, char * op, char * diag, int * n, int * k, RealScalar * pa, int * lda, RealScalar * px, int * incx)
DTBSV solves one of the systems of equations
A*x = b, or A'*x = b,
where b and x are n element vectors and A is an n by n unit, or non-unit, upper or lower triangular band matrix, with (k + 1) diagonals.
No test for singularity or near-singularity is included in this routine. Such tests must be performed before calling this routine.
Definition at line 350 of file level2_impl.h.
References a, copy_back(), DIAG, get_compact_vector(), incx, info, int(), INVALID, lda, n, OP, px, SCALAR_SUFFIX_UP, UNIT, UPLO, x, and xerbla_().
tpmv()
int EIGEN_BLAS_FUNC() tpmv (char * uplo, char * opa, char * diag, int * n, RealScalar * pap, RealScalar * px, int * incx)
DTPMV performs one of the matrix-vector operations
x := A*x, or x := A'*x,
where x is an n element vector and A is an n by n unit, or non-unit, upper or lower triangular matrix, supplied in packed form.
Definition at line 424 of file level2_impl.h.
References copy_back(), Eigen::PlainObjectBase< Derived >::data(), DIAG, get_compact_vector(), incx, info, int(), INVALID, n, OP, px, res, SCALAR_SUFFIX_UP, Eigen::PlainObjectBase< Derived >::setZero(), UPLO, x, and xerbla_().
tpsv()
int EIGEN_BLAS_FUNC() tpsv (char * uplo, char * opa, char * diag, int * n, RealScalar * pap, RealScalar * px, int * incx)
DTPSV solves one of the systems of equations
A*x = b, or A'*x = b,
where b and x are n element vectors and A is an n by n unit, or non-unit, upper or lower triangular matrix, supplied in packed form.
No test for singularity or near-singularity is included in this routine. Such tests must be performed before calling this routine.
Definition at line 499 of file level2_impl.h.
References copy_back(), DIAG, get_compact_vector(), incx, info, int(), INVALID, n, OP, px, SCALAR_SUFFIX_UP, UPLO, x, and xerbla_().
trmv()
int EIGEN_BLAS_FUNC() trmv (const char * uplo, const char * opa, const char * diag, const int * n, const RealScalar * pa, const int * lda, RealScalar * pb, const int * incb)
Definition at line 145 of file level2_impl.h.
References a, b, copy_back(), Eigen::PlainObjectBase< Derived >::data(), DIAG, get_compact_vector(), info, int(), INVALID, lda, max, n, OP, res, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, Eigen::PlainObjectBase< Derived >::setZero(), UPLO, and xerbla_().
trsv()
int EIGEN_BLAS_FUNC() trsv (const char * uplo, const char * opa, const char * diag, const int * n, const RealScalar * pa, const int * lda, RealScalar * pb, const int * incb)
Definition at line 86 of file level2_impl.h.
References a, b, copy_back(), DIAG, get_compact_vector(), info, int(), INVALID, lda, max, n, OP, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, UPLO, and xerbla_().