pairinteraction: /travis/libpairinteraction/eigen/blas/level1_real_impl.h File Reference
level1_real_impl.h File Reference
#include "common.h"
Functions
RealScalar EIGEN_BLAS_FUNC() asum (int *n, RealScalar *px, int *incx)
Scalar EIGEN_BLAS_FUNC() dot (int *n, RealScalar *px, int *incx, RealScalar *py, int *incy)
Scalar EIGEN_BLAS_FUNC() nrm2 (int *n, RealScalar *px, int *incx)
int EIGEN_BLAS_FUNC() rot (int *n, RealScalar *px, int *incx, RealScalar *py, int *incy, RealScalar *pc, RealScalar *ps)
Function Documentation
asum()
RealScalar EIGEN_BLAS_FUNC() asum (int * n, RealScalar * px, int * incx)
Definition at line 14 of file level1_real_impl.h.
References abs(), incx, make_vector(), n, px, and x.
dot()
Scalar EIGEN_BLAS_FUNC() dot (int * n, RealScalar * px, int * incx, RealScalar * py, int * incy)
Definition at line 27 of file level1_real_impl.h.
References incx, incy, make_vector(), n, px, py, reverse(), mpfr::sum(), x, and y.
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::isUnitary(), memoryleak(), adjoint_specific< true >::run(), adjoint_specific< false >::run(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::slerp(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::squaredDistance().
nrm2()
Scalar EIGEN_BLAS_FUNC() nrm2 (int * n, RealScalar * px, int * incx)
Definition at line 46 of file level1_real_impl.h.
References abs(), incx, make_vector(), n, px, and x.
rot()
int EIGEN_BLAS_FUNC() rot (int * n, RealScalar * px, int * incx, RealScalar * py, int * incy, RealScalar * pc, RealScalar * ps)
Definition at line 57 of file level1_real_impl.h.
References abs(), Eigen::internal::apply_rotation_in_the_plane(), c, incx, incy, make_vector(), n, pc, ps, px, py, rvx(), rvy(), s, vx(), vy(), x, and y.
Referenced by HamiltonianTwo::calculate(), Action_rot< Interface >::calculate(), Eigen::MatrixPower< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), Eigen::RealSchur< MatrixType >::computeFromHessenberg(), Eigen::EulerAngles< _Scalar, _System >::EulerAngles(), hyperplane(), jacobi(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and test_openglsupport().