pairinteraction: /travis/libpairinteraction/eigen/blas/level3_impl.h File Reference
level3_impl.h File Reference
#include <iostream>
#include "common.h"
Functions
int EIGEN_BLAS_FUNC() gemm (const char *opa, const char *opb, const int *m, const int *n, const int *k, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *pb, const int *ldb, const RealScalar *pbeta, RealScalar *pc, const int *ldc)
int EIGEN_BLAS_FUNC() trsm (const char *side, const char *uplo, const char *opa, const char *diag, const int *m, const int *n, const RealScalar *palpha, const RealScalar *pa, const int *lda, RealScalar *pb, const int *ldb)
int EIGEN_BLAS_FUNC() trmm (const char *side, const char *uplo, const char *opa, const char *diag, const int *m, const int *n, const RealScalar *palpha, const RealScalar *pa, const int *lda, RealScalar *pb, const int *ldb)
int EIGEN_BLAS_FUNC() symm (const char *side, const char *uplo, const int *m, const int *n, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *pb, const int *ldb, const RealScalar *pbeta, RealScalar *pc, const int *ldc)
int EIGEN_BLAS_FUNC() syrk (const char *uplo, const char *op, const int *n, const int *k, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *pbeta, RealScalar *pc, const int *ldc)
int EIGEN_BLAS_FUNC() syr2k (const char *uplo, const char *op, const int *n, const int *k, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *pb, const int *ldb, const RealScalar *pbeta, RealScalar *pc, const int *ldc)
Function Documentation
gemm()
int EIGEN_BLAS_FUNC() gemm (const char * opa, const char * opb, const int * m, const int * n, const int * k, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * pb, const int * ldb, const RealScalar * pbeta, RealScalar * pc, const int * ldc)
Definition at line 12 of file level3_impl.h.
References a, alpha, b, c, info, INVALID, lda, m, matrix(), max, n, NOTR, OP, palpha, pc, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, and xerbla_().
symm()
int EIGEN_BLAS_FUNC() symm (const char * side, const char * uplo, const int * m, const int * n, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * pb, const int * ldb, const RealScalar * pbeta, RealScalar * pc, const int * ldc)
Definition at line 287 of file level3_impl.h.
References a, alpha, b, c, info, INVALID, lda, LEFT, LO, Eigen::Lower, m, matA(), matrix(), max, n, palpha, pc, RIGHT, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, SIDE, size, UP, UPLO, Eigen::Upper, and xerbla_().
Referenced by cholesky(), cholesky_cplx(), matrix_l1_norm(), and test_chol_update().
syr2k()
int EIGEN_BLAS_FUNC() syr2k (const char * uplo, const char * op, const int * n, const int * k, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * pb, const int * ldb, const RealScalar * pbeta, RealScalar * pc, const int * ldc)
Definition at line 437 of file level3_impl.h.
References a, ADJ, alpha, b, c, conj(), EIGEN_BLAS_FUNC, info, INVALID, ISCOMPLEX, lda, LEFT, LO, Eigen::Lower, m, matrix(), max, n, NOTR, OP, palpha, pc, RIGHT, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, setZero(), SIDE, size, Eigen::StrictlyLower, Eigen::StrictlyUpper, TR, UP, UPLO, Eigen::Upper, and xerbla_().
syrk()
int EIGEN_BLAS_FUNC() syrk (const char * uplo, const char * op, const int * n, const int * k, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * pbeta, RealScalar * pc, const int * ldc)
Definition at line 357 of file level3_impl.h.
References a, ADJ, alpha, c, info, INVALID, ISCOMPLEX, lda, Eigen::Lower, matrix(), max, n, NOTR, OP, palpha, pc, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, setZero(), UP, UPLO, Eigen::Upper, and xerbla_().
trmm()
int EIGEN_BLAS_FUNC() trmm (const char * side, const char * uplo, const char * opa, const char * diag, const int * m, const int * n, const RealScalar * palpha, const RealScalar * pa, const int * lda, RealScalar * pb, const int * ldb)
Definition at line 183 of file level3_impl.h.
References a, alpha, b, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), DIAG, info, INVALID, lda, LEFT, m, matrix(), max, n, OP, Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride(), palpha, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, SIDE, UPLO, and xerbla_().
Referenced by Action_trmm< Interface >::calculate().
trsm()
int EIGEN_BLAS_FUNC() trsm (const char * side, const char * uplo, const char * opa, const char * diag, const int * m, const int * n, const RealScalar * palpha, const RealScalar * pa, const int * lda, RealScalar * pb, const int * ldb)
Definition at line 78 of file level3_impl.h.
References a, alpha, b, DIAG, info, INVALID, lda, LEFT, m, matrix(), max, n, OP, palpha, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, SIDE, UPLO, and xerbla_().