pairinteraction: /travis/libpairinteraction/eigen/blas/level2_real_impl.h File Reference
level2_real_impl.h File Reference
#include "common.h"
Functions
int EIGEN_BLAS_FUNC() symv (const char *uplo, const int *n, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *px, const int *incx, const RealScalar *pbeta, RealScalar *py, const int *incy)
int EIGEN_BLAS_FUNC() syr (const char *uplo, const int *n, const RealScalar *palpha, const RealScalar *px, const int *incx, RealScalar *pc, const int *ldc)
int EIGEN_BLAS_FUNC() syr2 (const char *uplo, const int *n, const RealScalar *palpha, const RealScalar *px, const int *incx, const RealScalar *py, const int *incy, RealScalar *pc, const int *ldc)
int EIGEN_BLAS_FUNC() spr (char *uplo, int *n, Scalar *palpha, Scalar *px, int *incx, Scalar *pap)
int EIGEN_BLAS_FUNC() spr2 (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *py, int *incy, RealScalar *pap)
int EIGEN_BLAS_FUNC() ger (int *m, int *n, Scalar *palpha, Scalar *px, int *incx, Scalar *py, int *incy, Scalar *pa, int *lda)
Function Documentation
ger()
int EIGEN_BLAS_FUNC() ger (int * m, int * n, Scalar * palpha, Scalar * px, int * incx, Scalar * py, int * incy, Scalar * pa, int * lda)
DGER performs the rank 1 operation
A := alpha*x*y' + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
Definition at line 278 of file level2_real_impl.h.
References a, alpha, get_compact_vector(), incx, incy, info, lda, m, max, n, palpha, px, py, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, x, xerbla_(), and y.
Referenced by Action_ger< Interface >::calculate().
spr()
int EIGEN_BLAS_FUNC() spr (char * uplo, int * n, Scalar * palpha, Scalar * px, int * incx, Scalar * pap)
DSBMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n symmetric band matrix, with k super-diagonals.DSPMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n symmetric matrix, supplied in packed form.DSPR performs the symmetric rank 1 operation
A := alpha*x*x' + A,
where alpha is a real scalar, x is an n element vector and A is an n by n symmetric matrix, supplied in packed form.
Definition at line 186 of file level2_real_impl.h.
References alpha, get_compact_vector(), incx, info, int(), INVALID, n, palpha, px, SCALAR_SUFFIX_UP, UPLO, x, and xerbla_().
spr2()
int EIGEN_BLAS_FUNC() spr2 (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * py, int * incy, RealScalar * pap)
DSPR2 performs the symmetric rank 2 operation
A := alpha*x*y' + alpha*y*x' + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n symmetric matrix, supplied in packed form.
Definition at line 230 of file level2_real_impl.h.
References alpha, get_compact_vector(), incx, incy, info, int(), INVALID, n, palpha, px, py, SCALAR_SUFFIX_UP, UPLO, x, xerbla_(), and y.
symv()
int EIGEN_BLAS_FUNC() symv (const char * uplo, const int * n, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * px, const int * incx, const RealScalar * pbeta, RealScalar * py, const int * incy)
Definition at line 13 of file level2_real_impl.h.
References a, alpha, copy_back(), get_compact_vector(), incx, incy, info, int(), INVALID, lda, make_vector(), max, n, palpha, px, py, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, UPLO, x, xerbla_(), and y.
Referenced by Action_symv< Interface >::calculate().
syr()
int EIGEN_BLAS_FUNC() syr (const char * uplo, const int * n, const RealScalar * palpha, const RealScalar * px, const int * incx, RealScalar * pc, const int * ldc)
Definition at line 65 of file level2_real_impl.h.
References alpha, c, get_compact_vector(), incx, info, int(), INVALID, max, n, palpha, pc, px, SCALAR_SUFFIX_UP, UPLO, x, and xerbla_().
syr2()
int EIGEN_BLAS_FUNC() syr2 (const char * uplo, const int * n, const RealScalar * palpha, const RealScalar * px, const int * incx, const RealScalar * py, const int * incy, RealScalar * pc, const int * ldc)
Definition at line 105 of file level2_real_impl.h.
References alpha, c, get_compact_vector(), incx, incy, info, int(), INVALID, max, n, palpha, pc, px, py, SCALAR_SUFFIX_UP, UPLO, x, xerbla_(), and y.
Referenced by Action_syr2< Interface >::calculate().