pairinteraction: /travis/libpairinteraction/eigen/blas/level2_cplx_impl.h File Reference
level2_cplx_impl.h File Reference
#include "common.h"
Functions
int EIGEN_BLAS_FUNC() hemv (const char *uplo, const int *n, const RealScalar *palpha, const RealScalar *pa, const int *lda, const RealScalar *px, const int *incx, const RealScalar *pbeta, RealScalar *py, const int *incy)
int EIGEN_BLAS_FUNC() hpr (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *pap)
int EIGEN_BLAS_FUNC() hpr2 (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *py, int *incy, RealScalar *pap)
int EIGEN_BLAS_FUNC() her (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *pa, int *lda)
int EIGEN_BLAS_FUNC() her2 (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *py, int *incy, RealScalar *pa, int *lda)
int EIGEN_BLAS_FUNC() geru (int *m, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *py, int *incy, RealScalar *pa, int *lda)
int EIGEN_BLAS_FUNC() gerc (int *m, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *py, int *incy, RealScalar *pa, int *lda)
Function Documentation
gerc()
int EIGEN_BLAS_FUNC() gerc (int * m, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * py, int * incy, RealScalar * pa, int * lda)
ZGERC performs the rank 1 operation
A := alpha*x*conjg(y') + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
Definition at line 332 of file level2_cplx_impl.h.
References a, alpha, get_compact_vector(), incx, incy, info, lda, m, max, n, palpha, px, py, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, x, xerbla_(), and y.
geru()
int EIGEN_BLAS_FUNC() geru (int * m, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * py, int * incy, RealScalar * pa, int * lda)
ZGERU performs the rank 1 operation
A := alpha*x*y' + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
Definition at line 295 of file level2_cplx_impl.h.
References a, alpha, get_compact_vector(), incx, incy, info, lda, m, max, n, palpha, px, py, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, x, xerbla_(), and y.
hemv()
int EIGEN_BLAS_FUNC() hemv (const char * uplo, const int * n, const RealScalar * palpha, const RealScalar * pa, const int * lda, const RealScalar * px, const int * incx, const RealScalar * pbeta, RealScalar * py, const int * incy)
ZHEMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n hermitian matrix.
Definition at line 19 of file level2_cplx_impl.h.
References a, alpha, copy_back(), get_compact_vector(), incx, incy, info, int(), INVALID, lda, make_vector(), max, n, palpha, px, py, Eigen::TensorSycl::run(), SCALAR_SUFFIX_UP, UPLO, x, xerbla_(), and y.
her()
int EIGEN_BLAS_FUNC() her (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * pa, int * lda)
ZHER performs the hermitian rank 1 operation
A := alpha*x*conjg(x') + A,
where alpha is a real scalar, x is an n element vector and A is an n by n hermitian matrix.
Definition at line 197 of file level2_cplx_impl.h.
References a, alpha, get_compact_vector(), incx, info, int(), INVALID, lda, matrix(), max, n, palpha, px, SCALAR_SUFFIX_UP, UPLO, x, and xerbla_().
her2()
int EIGEN_BLAS_FUNC() her2 (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * py, int * incy, RealScalar * pa, int * lda)
ZHER2 performs the hermitian rank 2 operation
A := alpha*x*conjg(y') + conjg(alpha)*y*conjg(x') + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n hermitian matrix.
Definition at line 244 of file level2_cplx_impl.h.
References a, alpha, get_compact_vector(), incx, incy, info, int(), INVALID, lda, matrix(), max, n, palpha, px, py, SCALAR_SUFFIX_UP, UPLO, x, xerbla_(), and y.
hpr()
int EIGEN_BLAS_FUNC() hpr (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * pap)
ZHBMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n hermitian band matrix, with k super-diagonals.ZHPMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n hermitian matrix, supplied in packed form.ZHPR performs the hermitian rank 1 operation
A := alpha*x*conjg(x') + A,
where alpha is a real scalar, x is an n element vector and A is an n by n hermitian matrix, supplied in packed form.
Definition at line 105 of file level2_cplx_impl.h.
References alpha, get_compact_vector(), incx, info, int(), INVALID, n, palpha, px, SCALAR_SUFFIX_UP, UPLO, x, and xerbla_().
hpr2()
int EIGEN_BLAS_FUNC() hpr2 (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * py, int * incy, RealScalar * pap)
ZHPR2 performs the hermitian rank 2 operation
A := alpha*x*conjg(y') + conjg(alpha)*y*conjg(x') + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n hermitian matrix, supplied in packed form.
Definition at line 149 of file level2_cplx_impl.h.
References alpha, get_compact_vector(), incx, incy, info, int(), INVALID, n, palpha, px, py, SCALAR_SUFFIX_UP, UPLO, x, xerbla_(), and y.