pairinteraction: /travis/libpairinteraction/eigen/test/mapped_matrix.cpp File Reference
mapped_matrix.cpp File Reference
#include "main.h"
Macros
#define EIGEN_NO_STATIC_ASSERT
#define EIGEN_TESTMAP_MAX_SIZE 256
Functions
template<typename VectorType >
void map_class_vector (const VectorType &m)
template<typename MatrixType >
void map_class_matrix (const MatrixType &m)
template<typename VectorType >
void map_static_methods (const VectorType &m)
template<typename PlainObjectType >
void check_const_correctness (const PlainObjectType &)
template<typename Scalar >
void map_not_aligned_on_scalar ()
void test_mapped_matrix ()
Macro Definition Documentation
EIGEN_NO_STATIC_ASSERT
#define EIGEN_NO_STATIC_ASSERT
Definition at line 11 of file mapped_matrix.cpp.
EIGEN_TESTMAP_MAX_SIZE
#define EIGEN_TESTMAP_MAX_SIZE 256
Definition at line 16 of file mapped_matrix.cpp.
Referenced by map_class_vector().
Function Documentation
check_const_correctness()
template<typename PlainObjectType > void check_const_correctness (const PlainObjectType &)
Definition at line 148 of file mapped_matrix.cpp.
References Eigen::LvalueBit, and VERIFY.
map_class_matrix()
template<typename MatrixType > void map_class_matrix (const MatrixType & m)
Definition at line 52 of file mapped_matrix.cpp.
References Eigen::internal::aligned_delete(), cols, EIGEN_MAX_ALIGN_BYTES, i, rows, size, VERIFY_IS_APPROX, and VERIFY_IS_EQUAL.
map_class_vector()
template<typename VectorType > void map_class_vector (const VectorType & m)
Definition at line 18 of file mapped_matrix.cpp.
References Eigen::internal::aligned_delete(), Eigen::AlignedMax, EIGEN_MAX_ALIGN_BYTES, EIGEN_TESTMAP_MAX_SIZE, size, VERIFY_IS_EQUAL, and VERIFY_RAISES_ASSERT.
map_not_aligned_on_scalar()
template<typename Scalar > void map_not_aligned_on_scalar ()
Definition at line 163 of file mapped_matrix.cpp.
References Eigen::internal::aligned_delete(), m2(), size, and VERIFY_IS_EQUAL.
map_static_methods()
template<typename VectorType > void map_static_methods (const VectorType & m)
Definition at line 122 of file mapped_matrix.cpp.
References Eigen::internal::aligned_delete(), EIGEN_MAX_ALIGN_BYTES, size, and VERIFY_IS_EQUAL.
test_mapped_matrix()
void test_mapped_matrix ()
Definition at line 184 of file mapped_matrix.cpp.
References i.