pairinteraction: /travis/libpairinteraction/eigen/test/mapstride.cpp File Reference
mapstride.cpp File Reference
#include "main.h"
Functions
template<int Alignment, typename VectorType >
void map_class_vector (const VectorType &m)
template<int Alignment, typename MatrixType >
void map_class_matrix (const MatrixType &_m)
void test_mapstride ()
Function Documentation
map_class_matrix()
template<int Alignment, typename MatrixType > void map_class_matrix (const MatrixType & _m)
Definition at line 51 of file mapstride.cpp.
References Eigen::Aligned, Eigen::internal::aligned_delete(), cols, Eigen::Dynamic, EIGEN_MAX_ALIGN_BYTES, i, Eigen::Map< PlainObjectType, MapOptions, StrideType >::innerStride(), j, m, Eigen::Map< PlainObjectType, MapOptions, StrideType >::outerStride(), rows, VERIFY, and VERIFY_IS_APPROX.
map_class_vector()
template<int Alignment, typename VectorType > void map_class_vector (const VectorType & m)
Definition at line 12 of file mapstride.cpp.
References Eigen::Aligned, Eigen::internal::aligned_delete(), i, size, v, and VERIFY.
test_mapstride()
void test_mapstride ()
Definition at line 149 of file mapstride.cpp.
References i.