pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/matrix_functions.h File Reference
matrix_functions.h File Reference
#include "main.h"
#include <unsupported/Eigen/MatrixFunctions>
Data Structures
struct processTriangularMatrix< MatrixType, IsComplex >
struct processTriangularMatrix< MatrixType, 0 >
struct generateTestMatrix< MatrixType, IsComplex >
struct generateTestMatrix< MatrixType, 0 >
struct generateTestMatrix< MatrixType, 1 >
Functions
template<typename Derived , typename OtherDerived >
Derived::RealScalar relerr (const MatrixBase< Derived > &A, const MatrixBase< OtherDerived > &B)
Function Documentation
relerr()
template<typename Derived , typename OtherDerived > Derived::RealScalar relerr (const MatrixBase< Derived > & A, const MatrixBase< OtherDerived > & B)
Definition at line 64 of file matrix_functions.h.
References cwiseAbs2(), Eigen::MatrixBase< Derived >::cwiseAbs2(), min, sqrt(), and mpfr::sum().
Referenced by Eigen::internal::blueNorm_impl(), pblueNorm(), test2dHyperbolicRotation(), test2dRotation(), and testPascal().