pairinteraction: /travis/libpairinteraction/eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h File Reference
MatrixCwiseUnaryOps.h File Reference
Typedefs
typedef CwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > CwiseAbsReturnType
typedef CwiseUnaryOp< internal::scalar_abs2_op< Scalar >, const Derived > CwiseAbs2ReturnType
typedef CwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > CwiseSqrtReturnType
typedef CwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > CwiseSignReturnType
typedef CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > CwiseInverseReturnType
Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const
Typedef Documentation
CwiseAbs2ReturnType
typedef CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> CwiseAbs2ReturnType
Definition at line 16 of file MatrixCwiseUnaryOps.h.
CwiseAbsReturnType
typedef CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> CwiseAbsReturnType
Definition at line 15 of file MatrixCwiseUnaryOps.h.
CwiseInverseReturnType
typedef CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> CwiseInverseReturnType
Definition at line 19 of file MatrixCwiseUnaryOps.h.
CwiseSignReturnType
typedef CwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> CwiseSignReturnType
Definition at line 18 of file MatrixCwiseUnaryOps.h.
CwiseSqrtReturnType
typedef CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> CwiseSqrtReturnType
Definition at line 17 of file MatrixCwiseUnaryOps.h.
Function Documentation
cwiseAbs()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbsReturnType cwiseAbs () const
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See also
cwiseAbs2()
Definition at line 32 of file MatrixCwiseUnaryOps.h.
References cwiseAbs2(), EIGEN_DOC_UNARY_ADDONS, and EIGEN_STRONG_INLINE.
Referenced by BOOST_AUTO_TEST_CASE(), SystemBase< StateTwo >::getConnections(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::hypotNorm(), orthomethods_3(), and Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNormalize().
cwiseAbs2()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseAbs2ReturnType cwiseAbs2 () const
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See also
cwiseAbs()
Definition at line 45 of file MatrixCwiseUnaryOps.h.
References cwiseSqrt(), EIGEN_DOC_UNARY_ADDONS, mpfr::root(), and square().
Referenced by areNotApprox(), cwiseAbs(), relerr(), Eigen::test_relative_error(), and verify_is_approx_upto_permutation().
cwiseInverse()
EIGEN_DEVICE_FUNC const CwiseInverseReturnType cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See also
cwiseProduct()
Definition at line 83 of file MatrixCwiseUnaryOps.h.
Referenced by cwiseSign(), and Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::inverse().
cwiseSign()
EIGEN_DEVICE_FUNC const CwiseSignReturnType cwiseSign () const inline
Returns
an expression of the coefficient-wise signum of *this.
Example:
Output:
Definition at line 69 of file MatrixCwiseUnaryOps.h.
References cwiseInverse(), EIGEN_DOC_UNARY_ADDONS, and inverse().
Referenced by cwiseSqrt().
cwiseSqrt()
EIGEN_DEVICE_FUNC const CwiseSqrtReturnType cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See also
cwisePow(), cwiseSquare()
Definition at line 58 of file MatrixCwiseUnaryOps.h.
References cwiseSign(), EIGEN_DOC_UNARY_ADDONS, and sign().
Referenced by cwiseAbs2().