pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/MatrixBase_col.cpp File Reference
MatrixBase_col.cpp File Reference
Functions
m col (1)
Variables
Matrix3d m = Matrix3d::Identity()
Function Documentation
col()
m col (1)
Referenced by Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheRight(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignCoeffByOuterInner(), Eigen::SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::assignGeneric(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >::assignPacketByOuterInner(), block(), SystemBase< StateTwo >::buildBasis(), Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::check_coordinates(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff(), Eigen::SparseMatrix< scalar_t >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::coeff(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffExistLower(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffExistUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffLower(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRef(), Eigen::SparseMatrix< scalar_t >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefLower(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffRefUpper(), Eigen::SkylineMatrix< _Scalar, _Options >::coeffUpper(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::col(), internal::colamd_r(), internal::colamd_recommended(), Eigen::internal::coletree(), combine(), Eigen::SkylineInplaceLU< MatrixType >::compute(), Eigen::SPQR< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::SkylineInplaceLU< MatrixType >::computeRowMajor(), sparseGaussianTest< Scalar >::df(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fill(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), find_pivot(), SystemOne::incorporate(), init_matrix_symm(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< scalar_t >::insert(), Eigen::SkylineMatrix< _Scalar, _Options >::insert(), Eigen::SparseMatrix< scalar_t >::insertBackUncompressed(), Eigen::SparseMatrix< scalar_t >::insertCompressed(), Eigen::SparseMatrix< scalar_t >::insertUncompressed(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::isUnitary(), Eigen::loadMarketVector(), circulant_functor< ArgType >::operator()(), Eigen::internal::companion< _Scalar, _Deg >::operator()(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::keep_diag::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::SimplicialCholeskyBase< Derived >::keep_diag::operator()(), Eigen::RandomSetter< SparseMatrixType, MapTraits, OuterPacketBits >::operator()(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet(), Eigen::internal::redux_evaluator< _XprType >::packet(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::packet(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::processRow(), randMatrixUnitary(), Hamiltonianmatrix::removeUnnecessaryBasisvectors(), Eigen::DenseBase< Derived >::reverseInPlace(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IteratorBased >::InnerIterator::row(), internal::band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, RowMajor >::run(), internal::band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, RowMajor >::run(), vectorization_logic< Scalar, Enable >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), vectorization_logic_half< Scalar, Enable >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::triangular_assignment_loop< Kernel, Mode, UnrollCount, SetOpposite >::run(), Eigen::internal::skyline_col_major_time_dense_product(), Eigen::internal::skyline_row_major_time_dense_product(), Eigen::SkylineInplaceLU< MatrixType >::solve(), sparse_block(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, Mode, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::triangular_dense_assignment_kernel(), verifyIsQuasiTriangular(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< ArrayWrapper< TArgType > >::writePacket(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
Variable Documentation
m
Matrix3d m = Matrix3d::Identity()
Definition at line 1 of file MatrixBase_col.cpp.