pairinteraction: /travis/libpairinteraction/eigen/bench/btl/data/mean.cxx File Reference
mean.cxx File Reference
#include "utilities.h"
#include <vector>
#include <string>
#include <iostream>
#include <fstream>
#include "bench_parameter.hh"
#include "utils/xy_file.hh"
#include <set>
Data Structures
class Lib_Mean
Functions
double mean_calc (const vector< int > &tab_sizes, const vector< double > &tab_mflops, const int size_min, const int size_max)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 64 of file mean.cxx.
References Lib_Mean::_mean_in_cache, Lib_Mean::_mean_out_of_cache, relicense::filename, i, INFOS, mean_calc(), and read_xy_file().
mean_calc()
double mean_calc (const vector< int > & tab_sizes, const vector< double > & tab_mflops, const int size_min, const int size_max)
Definition at line 153 of file mean.cxx.
References i, INFOS, and size.
Referenced by main().