pairinteraction: /travis/libpairinteraction/eigen/test/mixingtypes.cpp File Reference
mixingtypes.cpp File Reference
#include "main.h"
Macros
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO
#define EIGEN_NO_STATIC_ASSERT
#define EIGEN_SCALAR_BINARY_OP_PLUGIN { g_called |= (!internal::is_same<LhsScalar,RhsScalar>::value); }
#define VERIFY_MIX_SCALAR(XPR, REF)
Functions
template<int SizeAtCompileType>
void mixingtypes (int size=SizeAtCompileType)
void test_mixingtypes ()
Macro Definition Documentation
EIGEN_INITIALIZE_MATRICES_BY_ZERO
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO
Definition at line 12 of file mixingtypes.cpp.
EIGEN_NO_STATIC_ASSERT
#define EIGEN_NO_STATIC_ASSERT
Definition at line 15 of file mixingtypes.cpp.
EIGEN_SCALAR_BINARY_OP_PLUGIN
#define EIGEN_SCALAR_BINARY_OP_PLUGIN { g_called |= (!internal::is_same<LhsScalar,RhsScalar>::value); }
Definition at line 27 of file mixingtypes.cpp.
VERIFY_MIX_SCALAR
#define VERIFY_MIX_SCALAR (XPR, REF)
Value:
g_called = false; \
  VERIFY_IS_APPROX(XPR,REF); \
  VERIFY( g_called && #XPR" not properly optimized");
Definition at line 33 of file mixingtypes.cpp.
Referenced by mixingtypes().
Function Documentation
mixingtypes()
template<int SizeAtCompileType> void mixingtypes (int size = SizeAtCompileType)
Definition at line 38 of file mixingtypes.cpp.
References abs(), adjoint(), cast(), EIGEN_EMPTY, eval(), md, mf, min, Eigen::half_impl::pow(), size, sqrt(), triangularView< Lower >(), VERIFY_IS_APPROX, VERIFY_MIX_SCALAR, and VERIFY_RAISES_ASSERT.
test_mixingtypes()
void test_mixingtypes ()
Definition at line 289 of file mixingtypes.cpp.
References i.