pairinteraction: Eigen::TensorSycl::internal Namespace Reference
Eigen::TensorSycl::internal Namespace Reference
Data Structures
struct AccessorConstructor
struct CalculateIndex
struct CalculateIndex< N, Arg >
struct CalculateIndex< N, Arg1, Arg2 >
struct CalculateIndex< N, Arg1, Arg2, Arg3 >
struct CategoryCount
struct CategoryCount< Arg, Args... >
struct CategoryCount<>
struct CategoryHelper
struct CategoryHelper< Category, NoOP, utility::tuple::Tuple< T... > >
struct CategoryHelper< Category, OP, utility::tuple::Tuple< T... > >
struct ConvertToDeviceExpression
This struct is used to convert the MakePointer in the host expression to the MakeGlobalPointer for the device expression. For the leafNodes containing the pointer. This is due to the fact that the address space of the pointer T* is different on the host and the device.
struct createPlaceHolderExpression
template deduction for PlaceHolderExpression struct
struct DeviceConvertor
struct DimConstr
struct DimConstr< Dim, 0 >
struct EvalToLHSConstructor
struct ExprConstructor
struct ExtractAccessor
struct ExtractAccessor< TensorEvaluator< BinaryCategory< OP, LHSExpr, RHSExpr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorCwiseBinaryOp
struct ExtractAccessor< TensorEvaluator< const BinaryCategory< OP, LHSExpr, RHSExpr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is const TensorCwiseBinaryOp
struct ExtractAccessor< TensorEvaluator< const TensorAssignOp< LHSExpr, RHSExpr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is const TensorAssignOp
struct ExtractAccessor< TensorEvaluator< const TensorEvalToOp< Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is const TensorEvalToOp
struct ExtractAccessor< TensorEvaluator< const TensorForcedEvalOp< Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is const TensorForcedEvalOp
struct ExtractAccessor< TensorEvaluator< const TensorReductionOp< OP, Dim, Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is const TensorReductionOp
struct ExtractAccessor< TensorEvaluator< const TensorSelectOp< IfExpr, ThenExpr, ElseExpr >, Dev > >
struct ExtractAccessor< TensorEvaluator< const TernaryCategory< OP, Arg1Expr, Arg2Expr, Arg3Expr >, Dev > >
struct ExtractAccessor< TensorEvaluator< const UnaryCategory< OP, RHSExpr >, Dev > >
struct ExtractAccessor< TensorEvaluator< TensorAssignOp< LHSExpr, RHSExpr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorAssignOp
struct ExtractAccessor< TensorEvaluator< TensorEvalToOp< Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorEvalToOp
struct ExtractAccessor< TensorEvaluator< TensorForcedEvalOp< Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorForcedEvalOp
struct ExtractAccessor< TensorEvaluator< TensorReductionOp< OP, Dim, Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorReductionOp
struct ExtractAccessor< TensorEvaluator< TensorSelectOp< IfExpr, ThenExpr, ElseExpr >, Dev > >
struct ExtractAccessor< TensorEvaluator< TernaryCategory< OP, Arg1Expr, Arg2Expr, Arg3Expr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorCwiseTernaryOp
struct ExtractAccessor< TensorEvaluator< UnaryCategory< OP, RHSExpr >, Dev > >
specialisation of the ExtractAccessor struct when the node type is TensorCwiseNullaryOp, TensorCwiseUnaryOp and TensorBroadcastingOp
struct FunctorExtractor
struct FunctorExtractor< TensorEvaluator< BinaryCategory< OP, LHSExpr, RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< const BinaryCategory< OP, LHSExpr, RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< const TensorAssignOp< LHSExpr, RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< const TensorEvalToOp< RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > >
struct FunctorExtractor< TensorEvaluator< const TensorSelectOp< IfExpr, ThenExpr, ElseExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< const TernaryCategory< OP, Arg1Expr, Arg2Expr, Arg3Expr >, Dev > >
struct FunctorExtractor< TensorEvaluator< const UnaryCategory< OP, RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< TensorAssignOp< LHSExpr, RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< TensorEvalToOp< RHSExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > >
struct FunctorExtractor< TensorEvaluator< TensorSelectOp< IfExpr, ThenExpr, ElseExpr >, Dev > >
struct FunctorExtractor< TensorEvaluator< TernaryCategory< OP, Arg1Expr, Arg2Expr, Arg3Expr >, Dev > >
struct FunctorExtractor< TensorEvaluator< UnaryCategory< OP, RHSExpr >, Dev > >
struct LeafCount
LeafCount used to counting terminal nodes. The total number of leaf nodes is used by MakePlaceHolderExprHelper to find the order of the leaf node in a expression tree at compile time.
struct LeafCount< CategoryExpr< OP, RHSExpr... > >
struct LeafCount< const CategoryExpr< OP, RHSExpr... > >
struct LeafCount< const TensorAssignOp< LHSExpr, RHSExpr > >
specialisation of the LeafCount struct when the node type is const TensorAssignOp
struct LeafCount< const TensorEvalToOp< Expr > >
specialisation of the LeafCount struct when the node type is const TensorEvalToOp
struct LeafCount< const TensorForcedEvalOp< Expr > >
specialisation of the LeafCount struct when the node type is const TensorForcedEvalOp
struct LeafCount< const TensorMap< PlainObjectType, Options_, MakePointer_ > >
specialisation of the LeafCount struct when the node type is const TensorMap
struct LeafCount< const TensorReductionOp< OP, Dim, Expr > >
specialisation of the LeafCount struct when the node type is const TensorReductionOp
struct LeafCount< const TensorSelectOp< IfExpr, ThenExpr, ElseExpr > >
specialisation of the LeafCount struct when the node type is const TensorSelectOp is an exception
struct LeafCount< TensorAssignOp< LHSExpr, RHSExpr > >
struct LeafCount< TensorEvalToOp< Expr > >
specialisation of the LeafCount struct when the node type is TensorEvalToOp
struct LeafCount< TensorForcedEvalOp< Expr > >
specialisation of the LeafCount struct when the node type is TensorForcedEvalOp
struct LeafCount< TensorMap< PlainObjectType, Options_, MakePointer_ > >
specialisation of the LeafCount struct when the node type is TensorMap
struct LeafCount< TensorReductionOp< OP, Dim, Expr > >
specialisation of the LeafCount struct when the node type is TensorReductionOp
struct LeafCount< TensorSelectOp< IfExpr, ThenExpr, ElseExpr > >
specialisation of the LeafCount struct when the node type is TensorSelectOp
struct NonOpConversion
struct PlaceHolder
PlaceHolder is used to replace the TensorMap in the expression tree. PlaceHolder contains the order of the leaf node in the expression tree.
struct PlaceHolderExpression
it is used to create the PlaceHolder expression. The PlaceHolder expression is a copy of expression type in which the TensorMap of the has been replaced with PlaceHolder.
struct ValueCondition
struct ValueCondition< false, X, Y >
Functions
template<typename OrigExpr , typename IndexExpr , typename FuncD , typename... Params>
auto createDeviceExpression (FuncD &funcD, const utility::tuple::Tuple< Params... > &t) -> decltype(ExprConstructor< OrigExpr, IndexExpr, Params... >(funcD, t))
template deduction for ExprConstructor struct
template<typename Evaluator >
auto createTupleOfAccessors (cl::sycl::handler &cgh, const Evaluator &expr) -> decltype(ExtractAccessor< Evaluator >::getTuple(cgh, expr))
template deduction for ExtractAccessor
template<typename Evaluator >
auto extractFunctors (const Evaluator &evaluator) -> FunctorExtractor< Evaluator >
template deduction function for FunctorExtractor
Function Documentation
createDeviceExpression()
template<typename OrigExpr , typename IndexExpr , typename FuncD , typename... Params> auto Eigen::TensorSycl::internal::createDeviceExpression (FuncD & funcD, const utility::tuple::Tuple< Params... > & t) -> decltype(ExprConstructor<OrigExpr, IndexExpr, Params...>(funcD, t))
template deduction for ExprConstructor struct
Definition at line 229 of file TensorSyclExprConstructor.h.
createTupleOfAccessors()
template<typename Evaluator > auto Eigen::TensorSycl::internal::createTupleOfAccessors (cl::sycl::handler & cgh, const Evaluator & expr) -> decltype(ExtractAccessor<Evaluator>::getTuple(cgh, expr))
template deduction for ExtractAccessor
Definition at line 196 of file TensorSyclExtractAccessor.h.
Referenced by Eigen::internal::FullReducer< Self, Op, const Eigen::SyclDevice, Vectorizable >::run(), and Eigen::internal::InnerReducer< Self, Op, const Eigen::SyclDevice >::run().
extractFunctors()
template<typename Evaluator > auto Eigen::TensorSycl::internal::extractFunctors (const Evaluator & evaluator) -> FunctorExtractor<Evaluator> inline
template deduction function for FunctorExtractor
Definition at line 170 of file TensorSyclExtractFunctors.h.
Referenced by Eigen::TensorSycl::run(), Eigen::internal::FullReducer< Self, Op, const Eigen::SyclDevice, Vectorizable >::run(), and Eigen::internal::InnerReducer< Self, Op, const Eigen::SyclDevice >::run().