pairinteraction: Eigen::numext Namespace Reference
Eigen::numext Namespace Reference
Functions
template<>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE float sqrt (const float &x)
template<>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE double sqrt (const double &x)
template<typename T >
EIGEN_STRONG_INLINE void swap (T &a, T &b)
template<typename T >
T div_ceil (const T &a, const T &b)
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (lgamma, Scalar) lgamma(const Scalar &x)
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (digamma, Scalar) digamma(const Scalar &x)
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (zeta, Scalar) zeta(const Scalar &x
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (polygamma, Scalar) polygamma(const Scalar &n
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (erf, Scalar) erf(const Scalar &x)
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (erfc, Scalar) erfc(const Scalar &x)
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (igamma, Scalar) igamma(const Scalar &a
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (igammac, Scalar) igammac(const Scalar &a
template<typename Scalar >
EIGEN_DEVICE_FUNC EIGEN_MATHFUNC_RETVAL (betainc, Scalar) betainc(const Scalar &a
Variables
EIGEN_DEVICE_FUNC const Scalar & q
EIGEN_DEVICE_FUNC const Scalar & x
EIGEN_DEVICE_FUNC const Scalar & b
Function Documentation
div_ceil()
template<typename T > T Eigen::numext::div_ceil (const T & a, const T & b)
Definition at line 483 of file Meta.h.
References b.
Referenced by Eigen::internal::evaluateProductBlockingSizesHeuristic().
EIGEN_MATHFUNC_RETVAL() [1/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (lgamma , Scalar) const & inline
Definition at line 1507 of file SpecialFunctionsImpl.h.
References EIGEN_MATHFUNC_IMPL, lgamma(), and Eigen::internal::cephes::polevl< Scalar, N >::run().
EIGEN_MATHFUNC_RETVAL() [2/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (digamma , Scalar) const & inline
Definition at line 1513 of file SpecialFunctionsImpl.h.
References digamma(), EIGEN_MATHFUNC_IMPL, EIGEN_MATHFUNC_RETVAL, Eigen::internal::cephes::polevl< Scalar, N >::run(), and Eigen::zeta().
EIGEN_MATHFUNC_RETVAL() [3/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (zeta , Scalar) const & inline
EIGEN_MATHFUNC_RETVAL() [4/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (polygamma , Scalar) const & inline
EIGEN_MATHFUNC_RETVAL() [5/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (erf , Scalar) const & inline
Definition at line 1531 of file SpecialFunctionsImpl.h.
References EIGEN_MATHFUNC_IMPL, erf(), and Eigen::internal::cephes::polevl< Scalar, N >::run().
EIGEN_MATHFUNC_RETVAL() [6/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (erfc , Scalar) const & inline
Definition at line 1537 of file SpecialFunctionsImpl.h.
References a, Eigen::betainc(), EIGEN_MATHFUNC_IMPL, EIGEN_MATHFUNC_RETVAL, erfc(), Eigen::igamma(), Eigen::igammac(), Eigen::internal::cephes::polevl< Scalar, N >::run(), and x.
EIGEN_MATHFUNC_RETVAL() [7/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (igamma , Scalar) const & inline
EIGEN_MATHFUNC_RETVAL() [8/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (igammac , Scalar) const & inline
EIGEN_MATHFUNC_RETVAL() [9/9]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::numext::EIGEN_MATHFUNC_RETVAL (betainc , Scalar) const & inline
sqrt() [1/2]
template<> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE float Eigen::numext::sqrt (const float & x)
Definition at line 540 of file MathFunctions.h.
References EIGEN_ALWAYS_INLINE, and Eigen::internal::pfirst().
Referenced by Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::norm(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::normalize(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::normalized(), Eigen::internal::scalar_sqrt_op< Scalar >::operator()(), Eigen::internal::scalar_rsqrt_op< Scalar >::operator()(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNormalize(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::stableNormalized(), and Eigen::test_relative_error().
sqrt() [2/2]
template<> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE double Eigen::numext::sqrt (const double & x)
Definition at line 547 of file MathFunctions.h.
References Eigen::internal::pfirst().
swap()
template<typename T > EIGEN_STRONG_INLINE void Eigen::numext::swap (T & a, T & b)
Definition at line 471 of file Meta.h.
References std::swap().
Referenced by Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run(), Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::swap(), Eigen::Tuple< U, V >::swap(), and Eigen::TensorContractionEvaluatorBase< TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType >, Device > >::TensorContractionEvaluatorBase().
Variable Documentation
b
EIGEN_DEVICE_FUNC const Scalar& Eigen::numext::b
Definition at line 1556 of file SpecialFunctionsImpl.h.
Referenced by Eigen::internal::zeta_impl_series< float >::run(), Eigen::internal::zeta_impl_series< double >::run(), Eigen::internal::zeta_impl< Scalar >::run(), and Eigen::internal::betainc_impl< Scalar >::run().
q
EIGEN_DEVICE_FUNC const Scalar& Eigen::numext::q
Initial value:
{
    return EIGEN_MATHFUNC_IMPL(zeta, Scalar)::run(x, q)
Definition at line 1520 of file SpecialFunctionsImpl.h.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::AngleAxis< _Scalar >::AngleAxis(), array_special_functions(), Eigen::internal::companion< _Scalar, _Deg >::balancedR(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly_generic(), check_slerp(), cod(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), Eigen::RealSchur< MatrixType >::computeFromHessenberg(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::NonBlockingThreadPoolTempl< Environment >::CurrentThreadId(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), EulerAngles< _Scalar >::EulerAngles(), FancySpheres::FancySpheres(), mpfr::mpreal::get_default_prec(), MatrixElements::getRadial(), Eigen::AngleAxis< _Scalar >::inverse(), jacobi(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::internal::minimum_degree_ordering(), RenderingWidget::mouseMoveEvent(), Camera::position(), MatrixElements::precalculateDiamagnetism(), MatrixElements::precalculateMultipole(), MatrixElements::precalculateRadial(), Eigen::internal::pseudo_inverse(), qr(), quaternion(), Eigen::internal::RandomToTypeNormal(), mpfr::remquo(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::NonBlockingThreadPoolTempl< Environment >::Schedule(), selectionRulesMomentum(), selectionRulesMultipole(), Camera::setOrientation(), test_basic_runqueue(), test_empty_runqueue(), test_stress_runqueue(), Camera::updateViewMatrix(), and verify_euler_ranged().
x
EIGEN_DEVICE_FUNC const Scalar const Scalar & Eigen::numext::x
Initial value:
{
    return EIGEN_MATHFUNC_IMPL(polygamma, Scalar)::run(n, x)
Definition at line 1526 of file SpecialFunctionsImpl.h.
Referenced by EIGEN_MATHFUNC_RETVAL(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::igammac_impl< Scalar >::run(), Eigen::internal::igamma_impl< Scalar >::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::internal::polygamma_impl< Scalar >::run(), and Eigen::internal::betainc_impl< Scalar >::run().