pairinteraction: std Namespace Reference
std Namespace Reference
Data Structures
class deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >
struct hash< StateOne >
struct hash< StateTwo >
struct hash< std::array< int, 2 > >
class list< T, EIGEN_ALIGNED_ALLOCATOR< T > >
class numeric_limits< Eigen::AutoDiffScalar< T > >
struct numeric_limits< Eigen::half >
class numeric_limits< mpfr::mpreal >
class vector< T, EIGEN_ALIGNED_ALLOCATOR< T > >
Functions
template<>
void swap (mpfr::mpreal &x, mpfr::mpreal &y)
Function Documentation
swap()
template<> void std::swap (mpfr::mpreal & x, mpfr::mpreal & y) inline
Definition at line 2986 of file mpreal.h.
References mpfr::swap().
Referenced by IcoSphere::_subdivide(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::applyTranspositionOnTheRight(), Eigen::internal::swap_assign_op< DstEvaluatorTypeT::Scalar >::assignCoeff(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::atWithInsertion(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Eigen::internal::computeFromTridiagonal_impl(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::computeInPlace(), Eigen::DynamicSGroup::DynamicSGroup(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), gemv(), initSparse(), Eigen::internal::matrix_function_permute_schur(), Eigen::DynamicSGroup::operator=(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::operator=(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::operator=(), Eigen::internal::parallelize_gemm(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::pivotL(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::internal::SparseLUImpl< _MatrixType::Scalar, _MatrixType::StorageIndex >::pruneL(), Eigen::internal::QuickSplit(), Eigen::randomPermutationVector(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate(), Eigen::SparseMatrix< scalar_t >::reserveInnerVectors(), Eigen::internal::sortWithPermutation(), Eigen::internal::CompressedStorage< Scalar, StorageIndex >::swap(), Eigen::SkylineStorage< Scalar >::swap(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::swap(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::swap(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::swap(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::swap(), Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::swap(), Eigen::numext::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::swap(), Eigen::internal::swap(), Eigen::SkylineMatrix< _Scalar, _Options >::swap(), Eigen::SparseMatrix< scalar_t >::swap(), testVectorType(), and Eigen::internal::ldlt_inplace< Lower >::unblocked().