pairinteraction: mpfr Namespace Reference
mpfr Namespace Reference
Namespaces
internal
Data Structures
class conversion_overflow
class mpreal
Functions
template<typename Rhs >
const internal::result_type< Rhs >::type operator+ (const mpreal &lhs, const Rhs &rhs)
template<typename Lhs >
const internal::result_type< Lhs >::type operator+ (const Lhs &lhs, const mpreal &rhs)
template<typename Rhs >
const internal::result_type< Rhs >::type operator- (const mpreal &lhs, const Rhs &rhs)
template<typename Lhs >
const internal::result_type< Lhs >::type operator- (const Lhs &lhs, const mpreal &rhs)
template<typename Rhs >
const internal::result_type< Rhs >::type operator* (const mpreal &lhs, const Rhs &rhs)
template<typename Lhs >
const internal::result_type< Lhs >::type operator* (const Lhs &lhs, const mpreal &rhs)
template<typename Rhs >
const internal::result_type< Rhs >::type operator/ (const mpreal &lhs, const Rhs &rhs)
template<typename Lhs >
const internal::result_type< Lhs >::type operator/ (const Lhs &lhs, const mpreal &rhs)
const mpreal sqrt (const unsigned int v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal sqrt (const long int v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal sqrt (const int v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal sqrt (const long double v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal sqrt (const double v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal abs (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const long double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long double a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const double a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const long double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const long double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned int a, const double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const long double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long int a, const double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const long double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const int a, const double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long double a, const long double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long double a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long double a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long double a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const long double a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const double a, const double b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const double a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const double a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const double a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const double a, const int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal mul_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal mul_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal div_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal div_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
mpreal machine_epsilon (mp_prec_t prec=mpreal::get_default_prec())
mpreal machine_epsilon (const mpreal &x)
mpreal minval (mp_prec_t prec=mpreal::get_default_prec())
mpreal maxval (mp_prec_t prec=mpreal::get_default_prec())
bool isEqualFuzzy (const mpreal &a, const mpreal &b, const mpreal &eps)
bool isEqualFuzzy (const mpreal &a, const mpreal &b)
bool isEqualUlps (const mpreal &a, const mpreal &b, int maxUlps)
mp_prec_t digits2bits (int d)
int bits2digits (mp_prec_t b)
const mpreal() max (const mpreal &x, const mpreal &y)
const mpreal() min (const mpreal &x, const mpreal &y)
const mpreal operator+ (const mpreal &a, const mpreal &b)
const mpreal operator- (const mpreal &a, const mpreal &b)
const mpreal operator- (const double b, const mpreal &a)
const mpreal operator- (const unsigned long int b, const mpreal &a)
const mpreal operator- (const unsigned int b, const mpreal &a)
const mpreal operator- (const long int b, const mpreal &a)
const mpreal operator- (const int b, const mpreal &a)
const mpreal operator* (const mpreal &a, const mpreal &b)
const mpreal operator/ (const mpreal &a, const mpreal &b)
const mpreal operator/ (const unsigned long int b, const mpreal &a)
const mpreal operator/ (const unsigned int b, const mpreal &a)
const mpreal operator/ (const long int b, const mpreal &a)
const mpreal operator/ (const int b, const mpreal &a)
const mpreal operator/ (const double b, const mpreal &a)
const mpreal operator<< (const mpreal &v, const unsigned long int k)
const mpreal operator<< (const mpreal &v, const unsigned int k)
const mpreal operator<< (const mpreal &v, const long int k)
const mpreal operator<< (const mpreal &v, const int k)
const mpreal operator>> (const mpreal &v, const unsigned long int k)
const mpreal operator>> (const mpreal &v, const long int k)
const mpreal operator>> (const mpreal &v, const unsigned int k)
const mpreal operator>> (const mpreal &v, const int k)
bool operator> (const mpreal &a, const mpreal &b)
bool operator> (const mpreal &a, const unsigned long int b)
bool operator> (const mpreal &a, const unsigned int b)
bool operator> (const mpreal &a, const long int b)
bool operator> (const mpreal &a, const int b)
bool operator> (const mpreal &a, const long double b)
bool operator> (const mpreal &a, const double b)
bool operator>= (const mpreal &a, const mpreal &b)
bool operator>= (const mpreal &a, const unsigned long int b)
bool operator>= (const mpreal &a, const long int b)
bool operator>= (const mpreal &a, const int b)
bool operator>= (const mpreal &a, const long double b)
bool operator>= (const mpreal &a, const double b)
bool operator< (const mpreal &a, const mpreal &b)
bool operator< (const mpreal &a, const unsigned long int b)
bool operator< (const mpreal &a, const unsigned int b)
bool operator< (const mpreal &a, const long int b)
bool operator< (const mpreal &a, const int b)
bool operator< (const mpreal &a, const long double b)
bool operator< (const mpreal &a, const double b)
bool operator<= (const mpreal &a, const mpreal &b)
bool operator<= (const mpreal &a, const unsigned long int b)
bool operator<= (const mpreal &a, const unsigned int b)
bool operator<= (const mpreal &a, const long int b)
bool operator<= (const mpreal &a, const int b)
bool operator<= (const mpreal &a, const long double b)
bool operator<= (const mpreal &a, const double b)
bool operator== (const mpreal &a, const mpreal &b)
bool operator== (const mpreal &a, const unsigned long int b)
bool operator== (const mpreal &a, const unsigned int b)
bool operator== (const mpreal &a, const long int b)
bool operator== (const mpreal &a, const int b)
bool operator== (const mpreal &a, const long double b)
bool operator== (const mpreal &a, const double b)
bool operator!= (const mpreal &a, const mpreal &b)
bool operator!= (const mpreal &a, const unsigned long int b)
bool operator!= (const mpreal &a, const unsigned int b)
bool operator!= (const mpreal &a, const long int b)
bool operator!= (const mpreal &a, const int b)
bool operator!= (const mpreal &a, const long double b)
bool operator!= (const mpreal &a, const double b)
bool() isnan (const mpreal &op)
bool() isinf (const mpreal &op)
bool() isfinite (const mpreal &op)
bool iszero (const mpreal &op)
bool isint (const mpreal &op)
bool isregular (const mpreal &op)
template<class T >
std::string toString (T t, std::ios_base &(*f)(std::ios_base &))
std::ostream & operator<< (std::ostream &os, const mpreal &v)
std::istream & operator>> (std::istream &is, mpreal &v)
int sgn (const mpreal &op)
const mpreal frexp (const mpreal &x, mp_exp_t *exp, mp_rnd_t mode=mpreal::get_default_rnd())
const mpreal ldexp (const mpreal &v, mp_exp_t exp)
const mpreal scalbn (const mpreal &v, mp_exp_t exp)
mpreal copysign (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
bool signbit (const mpreal &x)
const mpreal modf (const mpreal &v, mpreal &n)
const mpreal sqr (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal sqrt (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal sqrt (const unsigned long int x, mp_rnd_t r)
const mpreal root (const mpreal &x, unsigned long int k, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal dim (const mpreal &a, const mpreal &b, mp_rnd_t r=mpreal::get_default_rnd())
int cmpabs (const mpreal &a, const mpreal &b)
int sin_cos (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal cbrt (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal fabs (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal log (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal log2 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal log10 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal exp (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal exp2 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal exp10 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal cos (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal sin (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal tan (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal sec (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal csc (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal cot (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal acos (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal asin (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal atan (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal logb (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal acot (const mpreal &v, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal asec (const mpreal &v, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal acsc (const mpreal &v, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal acoth (const mpreal &v, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal asech (const mpreal &v, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal acsch (const mpreal &v, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal cosh (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal sinh (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal tanh (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal sech (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal csch (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal coth (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal acosh (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal asinh (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal atanh (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal log1p (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal expm1 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal eint (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal gamma (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal tgamma (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal lngamma (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal zeta (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal erf (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal erfc (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal besselj0 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal besselj1 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal bessely0 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal bessely1 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal atan2 (const mpreal &y, const mpreal &x, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal hypot (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal remainder (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal remquo (long *q, const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal fac_ui (unsigned long int v, mp_prec_t prec=mpreal::get_default_prec(), mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal lgamma (const mpreal &v, int *signp=0, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal besseljn (long n, const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal besselyn (long n, const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal fma (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal fms (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal agm (const mpreal &v1, const mpreal &v2, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal sum (const mpreal tab[], const unsigned long int n, int &status, mp_rnd_t mode=mpreal::get_default_rnd())
int sinh_cosh (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal li2 (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal rem (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal mod (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal fmod (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal rec_sqrt (const mpreal &v, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal digamma (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal ai (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal const_log2 (mp_prec_t p=mpreal::get_default_prec(), mp_rnd_t r=mpreal::get_default_rnd())
const mpreal const_pi (mp_prec_t p=mpreal::get_default_prec(), mp_rnd_t r=mpreal::get_default_rnd())
const mpreal const_euler (mp_prec_t p=mpreal::get_default_prec(), mp_rnd_t r=mpreal::get_default_rnd())
const mpreal const_catalan (mp_prec_t p=mpreal::get_default_prec(), mp_rnd_t r=mpreal::get_default_rnd())
const mpreal const_infinity (int sign=1, mp_prec_t p=mpreal::get_default_prec())
const mpreal ceil (const mpreal &v)
const mpreal floor (const mpreal &v)
const mpreal round (const mpreal &v)
const mpreal trunc (const mpreal &v)
const mpreal rint (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal rint_ceil (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal rint_floor (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal rint_round (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal rint_trunc (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
const mpreal frac (const mpreal &x, mp_rnd_t r=mpreal::get_default_rnd())
void swap (mpreal &a, mpreal &b)
const mpreal fmax (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal fmin (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal nexttoward (const mpreal &x, const mpreal &y)
const mpreal nextabove (const mpreal &x)
const mpreal nextbelow (const mpreal &x)
const mpreal urandomb (gmp_randstate_t &state)
const mpreal urandom (gmp_randstate_t &state, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal random2 (mp_size_t size, mp_exp_t exp)
const mpreal random (unsigned int seed=0)
const mpreal grandom (gmp_randstate_t &state, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal grandom (unsigned int seed=0)
const mpreal pow (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const mpz_t b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const mpreal &a, const long int b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::get_default_rnd())
const mpreal pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode)
Function Documentation
abs()
const mpreal mpfr::abs (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2223 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
acos()
const mpreal mpfr::acos (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2236 of file mpreal.h.
References mpfr::mpreal::acos, and MPREAL_UNARY_MATH_FUNCTION_BODY.
acosh()
const mpreal mpfr::acosh (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2255 of file mpreal.h.
References mpfr::mpreal::acosh, and MPREAL_UNARY_MATH_FUNCTION_BODY.
acot()
const mpreal mpfr::acot (const mpreal & v, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2242 of file mpreal.h.
References mpfr::mpreal::atan.
acoth()
const mpreal mpfr::acoth (const mpreal & v, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2245 of file mpreal.h.
References mpfr::mpreal::atanh.
acsc()
const mpreal mpfr::acsc (const mpreal & v, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2244 of file mpreal.h.
References mpfr::mpreal::asin.
acsch()
const mpreal mpfr::acsch (const mpreal & v, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2247 of file mpreal.h.
References mpfr::mpreal::asinh.
agm()
const mpreal mpfr::agm (const mpreal & v1, const mpreal & v2, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2366 of file mpreal.h.
References a, mpfr::mpreal::get_prec(), p1, and mpfr::mpreal::set_prec().
ai()
const mpreal mpfr::ai (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2467 of file mpreal.h.
References mpfr::mpreal::ai, and MPREAL_UNARY_MATH_FUNCTION_BODY.
Referenced by initSparse(), main(), Eigen::internal::pgather< int, Packet4i >(), Eigen::internal::pscatter< int, Packet4i >(), and Eigen::internal::palign_impl< Offset, Packet2d >::run().
asec()
const mpreal mpfr::asec (const mpreal & v, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2243 of file mpreal.h.
References mpfr::mpreal::acos.
asech()
const mpreal mpfr::asech (const mpreal & v, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2246 of file mpreal.h.
References mpfr::mpreal::acosh.
asin()
const mpreal mpfr::asin (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2237 of file mpreal.h.
References mpfr::mpreal::asin, and MPREAL_UNARY_MATH_FUNCTION_BODY.
asinh()
const mpreal mpfr::asinh (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2256 of file mpreal.h.
References mpfr::mpreal::asinh, and MPREAL_UNARY_MATH_FUNCTION_BODY.
atan()
const mpreal mpfr::atan (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2238 of file mpreal.h.
References mpfr::mpreal::atan, and MPREAL_UNARY_MATH_FUNCTION_BODY.
atan2()
const mpreal mpfr::atan2 (const mpreal & y, const mpreal & x, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2273 of file mpreal.h.
References a, mpfr::mpreal::getPrecision(), max(), mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
atanh()
const mpreal mpfr::atanh (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2257 of file mpreal.h.
References mpfr::mpreal::atanh, and MPREAL_UNARY_MATH_FUNCTION_BODY.
besselj0()
const mpreal mpfr::besselj0 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2268 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
besselj1()
const mpreal mpfr::besselj1 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2269 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
besseljn()
const mpreal mpfr::besseljn (long n, const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2322 of file mpreal.h.
References mpfr::mpreal::getPrecision(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), n, and y.
bessely0()
const mpreal mpfr::bessely0 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2270 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
bessely1()
const mpreal mpfr::bessely1 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2271 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
besselyn()
const mpreal mpfr::besselyn (long n, const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2329 of file mpreal.h.
References mpfr::mpreal::getPrecision(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), n, and y.
bits2digits()
int mpfr::bits2digits (mp_prec_t b) inline
Definition at line 1925 of file mpreal.h.
References floor(), and int().
Referenced by std::numeric_limits< mpfr::mpreal >::digits10(), operator/(), and mpfr::mpreal::toString().
cbrt()
const mpreal mpfr::cbrt (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2221 of file mpreal.h.
References mpfr::mpreal::cbrt, and MPREAL_UNARY_MATH_FUNCTION_BODY.
ceil()
const mpreal mpfr::ceil (const mpreal & v) inline
Definition at line 2509 of file mpreal.h.
References x.
cmpabs()
int mpfr::cmpabs (const mpreal & a, const mpreal & b) inline
Definition at line 2208 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
const_catalan()
const mpreal mpfr::const_catalan (mp_prec_t p = mpreal::get_default_prec(), mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2493 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), p, and x.
const_euler()
const mpreal mpfr::const_euler (mp_prec_t p = mpreal::get_default_prec(), mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2486 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), p, and x.
const_infinity()
const mpreal mpfr::const_infinity (int sign = 1, mp_prec_t p = mpreal::get_default_prec()) inline
Definition at line 2500 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), p, sign(), and x.
Referenced by std::numeric_limits< mpfr::mpreal >::infinity().
const_log2()
const mpreal mpfr::const_log2 (mp_prec_t p = mpreal::get_default_prec(), mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2472 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), p, and x.
const_pi()
const mpreal mpfr::const_pi (mp_prec_t p = mpreal::get_default_prec(), mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2479 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), p, and x.
copysign()
mpreal mpfr::copysign (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2082 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
cos()
const mpreal mpfr::cos (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2230 of file mpreal.h.
References mpfr::mpreal::cos, and MPREAL_UNARY_MATH_FUNCTION_BODY.
cosh()
const mpreal mpfr::cosh (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2249 of file mpreal.h.
References mpfr::mpreal::cosh, and MPREAL_UNARY_MATH_FUNCTION_BODY.
cot()
const mpreal mpfr::cot (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2235 of file mpreal.h.
References mpfr::mpreal::cot, and MPREAL_UNARY_MATH_FUNCTION_BODY.
coth()
const mpreal mpfr::coth (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2254 of file mpreal.h.
References mpfr::mpreal::coth, and MPREAL_UNARY_MATH_FUNCTION_BODY.
csc()
const mpreal mpfr::csc (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2234 of file mpreal.h.
References mpfr::mpreal::csc, and MPREAL_UNARY_MATH_FUNCTION_BODY.
csch()
const mpreal mpfr::csch (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2253 of file mpreal.h.
References mpfr::mpreal::csch, and MPREAL_UNARY_MATH_FUNCTION_BODY.
digamma()
const mpreal mpfr::digamma (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2466 of file mpreal.h.
References mpfr::mpreal::digamma, and MPREAL_UNARY_MATH_FUNCTION_BODY.
digits2bits()
mp_prec_t mpfr::digits2bits (int d) inline
Definition at line 1918 of file mpreal.h.
References ceil().
Referenced by operator/().
dim()
const mpreal mpfr::dim (const mpreal & a, const mpreal & b, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2201 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and y.
Referenced by alignedbox(), alignedboxCastTests(), Eigen::Array< StorageIndex, 64, 1, DontAlign >::Array(), Eigen::TensorBase< Derived, ReadOnlyAccessors >::chip(), Eigen::TensorBase< TensorConversionOp< TargetType, XprType >, ReadOnlyAccessors >::chip(), Eigen::RealQZ< MatrixType >::compute(), numpy::internal::convert(), Eigen::KdBVH< _Scalar, _Dim, _Object >::getVolume(), hyperplane(), Eigen::Matrix< Scalar, Deg, 1 >::Matrix(), parametrizedline(), real_qz(), run_fixed_size_test(), run_test(), and test_umeyama().
div_2si()
const mpreal mpfr::div_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 1632 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
div_2ui()
const mpreal mpfr::div_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 1625 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
eint()
const mpreal mpfr::eint (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2261 of file mpreal.h.
References mpfr::mpreal::eint, and MPREAL_UNARY_MATH_FUNCTION_BODY.
erf()
const mpreal mpfr::erf (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2266 of file mpreal.h.
References mpfr::mpreal::erf, and MPREAL_UNARY_MATH_FUNCTION_BODY.
erfc()
const mpreal mpfr::erfc (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2267 of file mpreal.h.
References mpfr::mpreal::erfc, and MPREAL_UNARY_MATH_FUNCTION_BODY.
exp()
const mpreal mpfr::exp (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2227 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
exp10()
const mpreal mpfr::exp10 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2229 of file mpreal.h.
References mpfr::mpreal::exp10, and MPREAL_UNARY_MATH_FUNCTION_BODY.
exp2()
const mpreal mpfr::exp2 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2228 of file mpreal.h.
References mpfr::mpreal::exp2, and MPREAL_UNARY_MATH_FUNCTION_BODY.
expm1()
const mpreal mpfr::expm1 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2260 of file mpreal.h.
References mpfr::mpreal::expm1, and MPREAL_UNARY_MATH_FUNCTION_BODY.
fabs()
const mpreal mpfr::fabs (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2222 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
fac_ui()
const mpreal mpfr::fac_ui (unsigned long int v, mp_prec_t prec = mpreal::get_default_prec(), mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2301 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), v, and x.
floor()
const mpreal mpfr::floor (const mpreal & v) inline
Definition at line 2516 of file mpreal.h.
References x.
fma()
const mpreal mpfr::fma (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2336 of file mpreal.h.
References a, mpfr::mpreal::get_prec(), p1, and mpfr::mpreal::set_prec().
Referenced by Eigen::internal::pinsertlast().
fmax()
const mpreal mpfr::fmax (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2550 of file mpreal.h.
References a.
fmin()
const mpreal mpfr::fmin (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2557 of file mpreal.h.
References a.
Referenced by BasisnamesOne::fromBoth().
fmod()
const mpreal mpfr::fmod (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2440 of file mpreal.h.
References a, mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
Referenced by Eigen::MatrixPower< MatrixType >::compute(), Eigen::internal::scalar_fmod_op< Scalar >::operator()(), Eigen::Rotation2D< _Scalar >::smallestAngle(), and Eigen::Rotation2D< _Scalar >::smallestPositiveAngle().
fms()
const mpreal mpfr::fms (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2351 of file mpreal.h.
References a, mpfr::mpreal::get_prec(), p1, and mpfr::mpreal::set_prec().
frac()
const mpreal mpfr::frac (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2542 of file mpreal.h.
References mpfr::mpreal::frac, and MPREAL_UNARY_MATH_FUNCTION_BODY.
frexp()
const mpreal mpfr::frexp (const mpreal & x, mp_exp_t * exp, mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 2008 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and y.
Referenced by mpfr::mpreal::fits_in_bits(), Eigen::internal::matrix_exp_computeUV< MatrixType, float >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, double >::run(), and Eigen::internal::matrix_exp_computeUV< MatrixType, long double >::run().
gamma()
const mpreal mpfr::gamma (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2262 of file mpreal.h.
References mpfr::mpreal::gamma, and MPREAL_UNARY_MATH_FUNCTION_BODY.
Referenced by SystemBase< StateTwo >::derotate(), SystemBase< StateTwo >::getOverlap(), SystemOne::incorporate(), SystemBase< StateTwo >::rotate(), SystemBase< StateTwo >::SystemBase(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
grandom() [1/2]
const mpreal mpfr::grandom (gmp_randstate_t & state, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2639 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), and x.
Referenced by grandom().
grandom() [2/2]
const mpreal mpfr::grandom (unsigned int seed = 0) inline
Definition at line 2646 of file mpreal.h.
References grandom().
hypot()
const mpreal mpfr::hypot (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2280 of file mpreal.h.
References a, mpfr::mpreal::getPrecision(), max(), mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect().
isEqualFuzzy() [1/2]
bool mpfr::isEqualFuzzy (const mpreal & a, const mpreal & b, const mpreal & eps) inline
Definition at line 2070 of file mpreal.h.
References mpfr::mpreal::abs.
Referenced by isEqualFuzzy(), and operator/().
isEqualFuzzy() [2/2]
bool mpfr::isEqualFuzzy (const mpreal & a, const mpreal & b) inline
Definition at line 2075 of file mpreal.h.
References mpfr::mpreal::abs, isEqualFuzzy(), machine_epsilon(), max(), and min().
isEqualUlps()
bool mpfr::isEqualUlps (const mpreal & a, const mpreal & b, int maxUlps) inline
Definition at line 2065 of file mpreal.h.
References mpfr::mpreal::abs, machine_epsilon(), and max().
Referenced by operator/().
isfinite()
bool() mpfr::isfinite (const mpreal & op) inline
Definition at line 1702 of file mpreal.h.
isinf()
bool() mpfr::isinf (const mpreal & op) inline
Definition at line 1701 of file mpreal.h.
isint()
bool mpfr::isint (const mpreal & op) inline
Definition at line 1704 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
isnan()
bool() mpfr::isnan (const mpreal & op) inline
Definition at line 1700 of file mpreal.h.
isregular()
bool mpfr::isregular (const mpreal & op) inline
Definition at line 1707 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
iszero()
bool mpfr::iszero (const mpreal & op) inline
Definition at line 1703 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
ldexp()
const mpreal mpfr::ldexp (const mpreal & v, mp_exp_t exp) inline
Definition at line 2020 of file mpreal.h.
References mpfr::mpreal::exp, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
Referenced by Eigen::MatrixPowerAtomic< MatrixType >::compute(), mpfr::mpreal::fits_in_bits(), Eigen::internal::MatrixExponentialScalingOp< RealScalar >::operator()(), scalbn(), test2dHyperbolicRotation(), and test2dRotation().
lgamma()
const mpreal mpfr::lgamma (const mpreal & v, int * signp = 0, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2310 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
li2()
const mpreal mpfr::li2 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2404 of file mpreal.h.
References mpfr::mpreal::li2, and MPREAL_UNARY_MATH_FUNCTION_BODY.
lngamma()
const mpreal mpfr::lngamma (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2264 of file mpreal.h.
References mpfr::mpreal::lngamma, and MPREAL_UNARY_MATH_FUNCTION_BODY.
log()
const mpreal mpfr::log (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2224 of file mpreal.h.
References mpfr::mpreal::log, and MPREAL_UNARY_MATH_FUNCTION_BODY.
log10()
const mpreal mpfr::log10 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2226 of file mpreal.h.
References mpfr::mpreal::log10, and MPREAL_UNARY_MATH_FUNCTION_BODY.
log1p()
const mpreal mpfr::log1p (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2259 of file mpreal.h.
References mpfr::mpreal::log1p, and MPREAL_UNARY_MATH_FUNCTION_BODY.
log2()
const mpreal mpfr::log2 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2225 of file mpreal.h.
References mpfr::mpreal::log2, and MPREAL_UNARY_MATH_FUNCTION_BODY.
logb()
const mpreal mpfr::logb (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2240 of file mpreal.h.
References mpfr::mpreal::abs, and mpfr::mpreal::log2.
machine_epsilon() [1/2]
mpreal mpfr::machine_epsilon (mp_prec_t prec = mpreal::get_default_prec()) inline
Definition at line 2034 of file mpreal.h.
References mpfr::mpreal::mpreal().
Referenced by std::numeric_limits< mpfr::mpreal >::epsilon(), isEqualFuzzy(), isEqualUlps(), maxval(), and operator/().
machine_epsilon() [2/2]
mpreal mpfr::machine_epsilon (const mpreal & x) inline
Definition at line 2040 of file mpreal.h.
References mpfr::mpreal::nextabove, and x.
max()
const mpreal() mpfr::max (const mpreal & x, const mpreal & y)
Definition at line 2547 of file mpreal.h.
Referenced by atan2(), hypot(), isEqualFuzzy(), isEqualUlps(), operator*(), operator+(), operator-(), operator/(), remainder(), remquo(), and mpfr::mpreal::toString().
maxval()
mpreal mpfr::maxval (mp_prec_t prec = mpreal::get_default_prec()) inline
Definition at line 2059 of file mpreal.h.
References mpfr::mpreal::get_emax(), machine_epsilon(), and mpfr::mpreal::mpreal().
Referenced by Eigen::EigenSolver< CompanionMatrixType >::compute(), SystemBase< StateTwo >::getConnections(), SystemBase< StateTwo >::getMainStates(), SystemBase< StateTwo >::getVectorindex(), std::numeric_limits< mpfr::mpreal >::lowest(), std::numeric_limits< mpfr::mpreal >::max(), and operator/().
min()
const mpreal() mpfr::min (const mpreal & x, const mpreal & y)
Definition at line 2548 of file mpreal.h.
Referenced by std::numeric_limits< mpfr::mpreal >::denorm_min(), isEqualFuzzy(), and operator/().
minval()
mpreal mpfr::minval (mp_prec_t prec = mpreal::get_default_prec()) inline
Definition at line 2052 of file mpreal.h.
References mpfr::mpreal::get_emin(), and mpfr::mpreal::mpreal().
Referenced by std::numeric_limits< mpfr::mpreal >::min(), and operator/().
mod()
const mpreal mpfr::mod (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2415 of file mpreal.h.
References mpfr::mpreal::floor, mpfr::mpreal::iszero, m, mpfr::mpreal::setSign(), mpfr::mpreal::sgn, and y.
modf()
const mpreal mpfr::modf (const mpreal & v, mpreal & n) inline
Definition at line 2094 of file mpreal.h.
Referenced by mpfr::mpreal::fits_in_bits().
mul_2si()
const mpreal mpfr::mul_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 1618 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
mul_2ui()
const mpreal mpfr::mul_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 1610 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
nextabove()
const mpreal mpfr::nextabove (const mpreal & x) inline
Definition at line 2571 of file mpreal.h.
References a.
nextbelow()
const mpreal mpfr::nextbelow (const mpreal & x) inline
Definition at line 2578 of file mpreal.h.
References a.
nexttoward()
const mpreal mpfr::nexttoward (const mpreal & x, const mpreal & y) inline
Definition at line 2564 of file mpreal.h.
References a.
operator!=() [1/7]
bool mpfr::operator!= (const mpreal & a, const mpreal & b) inline
Definition at line 1692 of file mpreal.h.
References b.
operator!=() [2/7]
bool mpfr::operator!= (const mpreal & a, const unsigned long int b) inline
Definition at line 1693 of file mpreal.h.
References b.
operator!=() [3/7]
bool mpfr::operator!= (const mpreal & a, const unsigned int b) inline
Definition at line 1694 of file mpreal.h.
References b.
operator!=() [4/7]
bool mpfr::operator!= (const mpreal & a, const long int b) inline
Definition at line 1695 of file mpreal.h.
References b.
operator!=() [5/7]
bool mpfr::operator!= (const mpreal & a, const int b) inline
Definition at line 1696 of file mpreal.h.
References b.
operator!=() [6/7]
bool mpfr::operator!= (const mpreal & a, const long double b) inline
Definition at line 1697 of file mpreal.h.
References b.
operator!=() [7/7]
bool mpfr::operator!= (const mpreal & a, const double b) inline
Definition at line 1698 of file mpreal.h.
References b.
operator*() [1/3]
template<typename Rhs > const internal::result_type<Rhs>::type mpfr::operator* (const mpreal & lhs, const Rhs & rhs) inline
Definition at line 781 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator*() [2/3]
template<typename Lhs > const internal::result_type<Lhs>::type mpfr::operator* (const Lhs & lhs, const mpreal & rhs) inline
Definition at line 785 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator*() [3/3]
const mpreal mpfr::operator* (const mpreal & a, const mpreal & b) inline
Definition at line 1387 of file mpreal.h.
References c, mpfr::mpreal::get_default_rnd(), max(), mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
operator+() [1/3]
template<typename Rhs > const internal::result_type<Rhs>::type mpfr::operator+ (const mpreal & lhs, const Rhs & rhs) inline
Definition at line 763 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator+() [2/3]
template<typename Lhs > const internal::result_type<Lhs>::type mpfr::operator+ (const Lhs & lhs, const mpreal & rhs) inline
Definition at line 767 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator+() [3/3]
const mpreal mpfr::operator+ (const mpreal & a, const mpreal & b) inline
Definition at line 1162 of file mpreal.h.
References c, mpfr::mpreal::get_default_rnd(), max(), mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
operator-() [1/8]
template<typename Rhs > const internal::result_type<Rhs>::type mpfr::operator- (const mpreal & lhs, const Rhs & rhs) inline
Definition at line 772 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator-() [2/8]
template<typename Lhs > const internal::result_type<Lhs>::type mpfr::operator- (const Lhs & lhs, const mpreal & rhs) inline
Definition at line 776 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator-() [3/8]
const mpreal mpfr::operator- (const mpreal & a, const mpreal & b) inline
Definition at line 1270 of file mpreal.h.
References c, mpfr::mpreal::get_default_rnd(), max(), mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
operator-() [4/8]
const mpreal mpfr::operator- (const double b, const mpreal & a) inline
Definition at line 1277 of file mpreal.h.
References a, b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator-() [5/8]
const mpreal mpfr::operator- (const unsigned long int b, const mpreal & a) inline
Definition at line 1290 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator-() [6/8]
const mpreal mpfr::operator- (const unsigned int b, const mpreal & a) inline
Definition at line 1297 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator-() [7/8]
const mpreal mpfr::operator- (const long int b, const mpreal & a) inline
Definition at line 1304 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator-() [8/8]
const mpreal mpfr::operator- (const int b, const mpreal & a) inline
Definition at line 1311 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator/() [1/8]
template<typename Rhs > const internal::result_type<Rhs>::type mpfr::operator/ (const mpreal & lhs, const Rhs & rhs) inline
Definition at line 790 of file mpreal.h.
References mpfr::mpreal::mpreal().
operator/() [2/8]
template<typename Lhs > const internal::result_type<Lhs>::type mpfr::operator/ (const Lhs & lhs, const mpreal & rhs) inline
Definition at line 794 of file mpreal.h.
References a, mpfr::mpreal::abs, b, bits2digits(), digits2bits(), mpfr::mpreal::div_2si, mpfr::mpreal::div_2ui, mpfr::mpreal::get_default_prec(), mpfr::mpreal::get_default_rnd(), isEqualFuzzy(), isEqualUlps(), machine_epsilon(), max(), maxval(), min(), minval(), mpfr::mpreal::mpreal(), mpfr::mpreal::mul_2si, mpfr::mpreal::mul_2ui, mpfr::mpreal::pow, mpfr::mpreal::sqrt, v, x, and y.
operator/() [3/8]
const mpreal mpfr::operator/ (const mpreal & a, const mpreal & b) inline
Definition at line 1463 of file mpreal.h.
References c, mpfr::mpreal::get_default_rnd(), max(), and mpfr::mpreal::mpfr_srcptr().
operator/() [4/8]
const mpreal mpfr::operator/ (const unsigned long int b, const mpreal & a) inline
Definition at line 1470 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator/() [5/8]
const mpreal mpfr::operator/ (const unsigned int b, const mpreal & a) inline
Definition at line 1477 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator/() [6/8]
const mpreal mpfr::operator/ (const long int b, const mpreal & a) inline
Definition at line 1484 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator/() [7/8]
const mpreal mpfr::operator/ (const int b, const mpreal & a) inline
Definition at line 1491 of file mpreal.h.
References b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator/() [8/8]
const mpreal mpfr::operator/ (const double b, const mpreal & a) inline
Definition at line 1498 of file mpreal.h.
References a, b, mpfr::mpreal::get_default_rnd(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and x.
operator<() [1/7]
bool mpfr::operator< (const mpreal & a, const mpreal & b) inline
Definition at line 1668 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
operator<() [2/7]
bool mpfr::operator< (const mpreal & a, const unsigned long int b) inline
Definition at line 1669 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<() [3/7]
bool mpfr::operator< (const mpreal & a, const unsigned int b) inline
Definition at line 1670 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<() [4/7]
bool mpfr::operator< (const mpreal & a, const long int b) inline
Definition at line 1671 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<() [5/7]
bool mpfr::operator< (const mpreal & a, const int b) inline
Definition at line 1672 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<() [6/7]
bool mpfr::operator< (const mpreal & a, const long double b) inline
Definition at line 1673 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<() [7/7]
bool mpfr::operator< (const mpreal & a, const double b) inline
Definition at line 1674 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<<() [1/5]
const mpreal mpfr::operator<< (const mpreal & v, const unsigned long int k) inline
Definition at line 1569 of file mpreal.h.
References mpfr::mpreal::mul_2ui.
operator<<() [2/5]
const mpreal mpfr::operator<< (const mpreal & v, const unsigned int k) inline
Definition at line 1574 of file mpreal.h.
References mpfr::mpreal::mul_2ui.
operator<<() [3/5]
const mpreal mpfr::operator<< (const mpreal & v, const long int k) inline
Definition at line 1579 of file mpreal.h.
References mpfr::mpreal::mul_2si.
operator<<() [4/5]
const mpreal mpfr::operator<< (const mpreal & v, const int k) inline
Definition at line 1584 of file mpreal.h.
References mpfr::mpreal::mul_2si.
operator<<() [5/5]
std::ostream& mpfr::operator<< (std::ostream & os, const mpreal & v) inline
Definition at line 1899 of file mpreal.h.
References mpfr::mpreal::output().
operator<=() [1/7]
bool mpfr::operator<= (const mpreal & a, const mpreal & b) inline
Definition at line 1676 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
operator<=() [2/7]
bool mpfr::operator<= (const mpreal & a, const unsigned long int b) inline
Definition at line 1677 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<=() [3/7]
bool mpfr::operator<= (const mpreal & a, const unsigned int b) inline
Definition at line 1678 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<=() [4/7]
bool mpfr::operator<= (const mpreal & a, const long int b) inline
Definition at line 1679 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<=() [5/7]
bool mpfr::operator<= (const mpreal & a, const int b) inline
Definition at line 1680 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<=() [6/7]
bool mpfr::operator<= (const mpreal & a, const long double b) inline
Definition at line 1681 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator<=() [7/7]
bool mpfr::operator<= (const mpreal & a, const double b) inline
Definition at line 1682 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator==() [1/7]
bool mpfr::operator== (const mpreal & a, const mpreal & b) inline
Definition at line 1684 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
operator==() [2/7]
bool mpfr::operator== (const mpreal & a, const unsigned long int b) inline
Definition at line 1685 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator==() [3/7]
bool mpfr::operator== (const mpreal & a, const unsigned int b) inline
Definition at line 1686 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator==() [4/7]
bool mpfr::operator== (const mpreal & a, const long int b) inline
Definition at line 1687 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator==() [5/7]
bool mpfr::operator== (const mpreal & a, const int b) inline
Definition at line 1688 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator==() [6/7]
bool mpfr::operator== (const mpreal & a, const long double b) inline
Definition at line 1689 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator==() [7/7]
bool mpfr::operator== (const mpreal & a, const double b) inline
Definition at line 1690 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>() [1/7]
bool mpfr::operator> (const mpreal & a, const mpreal & b) inline
Definition at line 1652 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
operator>() [2/7]
bool mpfr::operator> (const mpreal & a, const unsigned long int b) inline
Definition at line 1653 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>() [3/7]
bool mpfr::operator> (const mpreal & a, const unsigned int b) inline
Definition at line 1654 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>() [4/7]
bool mpfr::operator> (const mpreal & a, const long int b) inline
Definition at line 1655 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>() [5/7]
bool mpfr::operator> (const mpreal & a, const int b) inline
Definition at line 1656 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>() [6/7]
bool mpfr::operator> (const mpreal & a, const long double b) inline
Definition at line 1657 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>() [7/7]
bool mpfr::operator> (const mpreal & a, const double b) inline
Definition at line 1658 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>=() [1/6]
bool mpfr::operator>= (const mpreal & a, const mpreal & b) inline
Definition at line 1660 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
operator>=() [2/6]
bool mpfr::operator>= (const mpreal & a, const unsigned long int b) inline
Definition at line 1661 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>=() [3/6]
bool mpfr::operator>= (const mpreal & a, const long int b) inline
Definition at line 1663 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>=() [4/6]
bool mpfr::operator>= (const mpreal & a, const int b) inline
Definition at line 1664 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>=() [5/6]
bool mpfr::operator>= (const mpreal & a, const long double b) inline
Definition at line 1665 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>=() [6/6]
bool mpfr::operator>= (const mpreal & a, const double b) inline
Definition at line 1666 of file mpreal.h.
References b, EIGEN_NOT_A_MACRO, mpfr::mpreal::isnan, and mpfr::mpreal::mpfr_srcptr().
operator>>() [1/5]
const mpreal mpfr::operator>> (const mpreal & v, const unsigned long int k) inline
Definition at line 1589 of file mpreal.h.
References mpfr::mpreal::div_2ui.
operator>>() [2/5]
const mpreal mpfr::operator>> (const mpreal & v, const long int k) inline
Definition at line 1594 of file mpreal.h.
References mpfr::mpreal::div_2si.
operator>>() [3/5]
const mpreal mpfr::operator>> (const mpreal & v, const unsigned int k) inline
Definition at line 1599 of file mpreal.h.
References mpfr::mpreal::div_2ui.
operator>>() [4/5]
const mpreal mpfr::operator>> (const mpreal & v, const int k) inline
Definition at line 1604 of file mpreal.h.
References mpfr::mpreal::div_2si.
operator>>() [5/5]
std::istream& mpfr::operator>> (std::istream & is, mpreal & v) inline
Definition at line 1904 of file mpreal.h.
References mpfr::mpreal::get_default_rnd(), and mpfr::mpreal::mpfr_ptr().
pow() [1/48]
const mpreal mpfr::pow (const mpreal & a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2704 of file mpreal.h.
References mpfr::mpreal::pow.
pow() [2/48]
const mpreal mpfr::pow (const mpreal & a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2716 of file mpreal.h.
References mpfr::mpreal::pow.
pow() [3/48]
const mpreal mpfr::pow (const mpreal & a, const long double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2721 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [4/48]
const mpreal mpfr::pow (const mpreal & a, const double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2726 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [5/48]
const mpreal mpfr::pow (const unsigned int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2738 of file mpreal.h.
References mpfr::mpreal::pow.
pow() [6/48]
const mpreal mpfr::pow (const long int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2743 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [7/48]
const mpreal mpfr::pow (const int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2749 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [8/48]
const mpreal mpfr::pow (const long double a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2755 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [9/48]
const mpreal mpfr::pow (const double a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2760 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [10/48]
const mpreal mpfr::pow (const unsigned long int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2773 of file mpreal.h.
References mpfr::mpreal::pow.
pow() [11/48]
const mpreal mpfr::pow (const unsigned long int a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2778 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [12/48]
const mpreal mpfr::pow (const unsigned long int a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2784 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [13/48]
const mpreal mpfr::pow (const unsigned long int a, const long double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2790 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [14/48]
const mpreal mpfr::pow (const unsigned long int a, const double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2795 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [15/48]
const mpreal mpfr::pow (const unsigned int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2801 of file mpreal.h.
References mpfr::mpreal::pow.
pow() [16/48]
const mpreal mpfr::pow (const unsigned int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2806 of file mpreal.h.
References mpfr::mpreal::pow.
pow() [17/48]
const mpreal mpfr::pow (const unsigned int a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2811 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [18/48]
const mpreal mpfr::pow (const unsigned int a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2817 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [19/48]
const mpreal mpfr::pow (const unsigned int a, const long double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2823 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [20/48]
const mpreal mpfr::pow (const unsigned int a, const double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2828 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [21/48]
const mpreal mpfr::pow (const long int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2834 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [22/48]
const mpreal mpfr::pow (const long int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2840 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [23/48]
const mpreal mpfr::pow (const long int a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2846 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [24/48]
const mpreal mpfr::pow (const long int a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2857 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [25/48]
const mpreal mpfr::pow (const long int a, const long double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2868 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [26/48]
const mpreal mpfr::pow (const long int a, const double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2874 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [27/48]
const mpreal mpfr::pow (const int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2881 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [28/48]
const mpreal mpfr::pow (const int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2887 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [29/48]
const mpreal mpfr::pow (const int a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2893 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [30/48]
const mpreal mpfr::pow (const int a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2904 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [31/48]
const mpreal mpfr::pow (const int a, const long double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2915 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [32/48]
const mpreal mpfr::pow (const int a, const double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2921 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [33/48]
const mpreal mpfr::pow (const long double a, const long double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2928 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [34/48]
const mpreal mpfr::pow (const long double a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2933 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [35/48]
const mpreal mpfr::pow (const long double a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2938 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [36/48]
const mpreal mpfr::pow (const long double a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2943 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [37/48]
const mpreal mpfr::pow (const long double a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2948 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [38/48]
const mpreal mpfr::pow (const double a, const double b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2953 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [39/48]
const mpreal mpfr::pow (const double a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2958 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [40/48]
const mpreal mpfr::pow (const double a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2963 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [41/48]
const mpreal mpfr::pow (const double a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2968 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [42/48]
const mpreal mpfr::pow (const double a, const int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2973 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::pow.
pow() [43/48]
const mpreal mpfr::pow (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2683 of file mpreal.h.
References x.
pow() [44/48]
const mpreal mpfr::pow (const mpreal & a, const mpz_t b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2690 of file mpreal.h.
References x.
pow() [45/48]
const mpreal mpfr::pow (const mpreal & a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2697 of file mpreal.h.
References x.
pow() [46/48]
const mpreal mpfr::pow (const mpreal & a, const long int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2709 of file mpreal.h.
References x.
pow() [47/48]
const mpreal mpfr::pow (const unsigned long int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2731 of file mpreal.h.
References x.
pow() [48/48]
const mpreal mpfr::pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode) inline
Definition at line 2766 of file mpreal.h.
References x.
random()
const mpreal mpfr::random (unsigned int seed = 0) inline
Definition at line 2614 of file mpreal.h.
References urandom().
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::sample(), Eigen::TensorBase< TensorConversionOp< TargetType, XprType >, ReadOnlyAccessors >::setRandom(), TreeTest< Dim >::testIntersect1(), TreeTest< Dim >::testIntersect2(), TreeTest< Dim >::testMinimize1(), and TreeTest< Dim >::testMinimize2().
random2()
const mpreal mpfr::random2 (mp_size_t size, mp_exp_t exp) inline
Definition at line 2602 of file mpreal.h.
References mpfr::mpreal::exp, mpfr::mpreal::mpfr_ptr(), size, and x.
rec_sqrt()
const mpreal mpfr::rec_sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2455 of file mpreal.h.
References x.
rem()
const mpreal mpfr::rem (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2409 of file mpreal.h.
References mpfr::mpreal::fmod.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::packet(), and Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writePacket().
remainder()
const mpreal mpfr::remainder (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2287 of file mpreal.h.
References a, mpfr::mpreal::getPrecision(), max(), mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
Referenced by find_partition_with_efficiency_higher_than(), and operator<<().
remquo()
const mpreal mpfr::remquo (long * q, const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2294 of file mpreal.h.
References a, mpfr::mpreal::getPrecision(), max(), mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and Eigen::numext::q.
rint()
const mpreal mpfr::rint (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2537 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::rint.
rint_ceil()
const mpreal mpfr::rint_ceil (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2538 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::rint_ceil.
rint_floor()
const mpreal mpfr::rint_floor (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2539 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::rint_floor.
rint_round()
const mpreal mpfr::rint_round (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2540 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::rint_round.
rint_trunc()
const mpreal mpfr::rint_trunc (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2541 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::rint_trunc.
root()
const mpreal mpfr::root (const mpreal & x, unsigned long int k, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2194 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), and y.
Referenced by Eigen::internal::coletree(), and cwiseAbs2().
round()
const mpreal mpfr::round (const mpreal & v) inline
Definition at line 2523 of file mpreal.h.
References x.
scalbn()
const mpreal mpfr::scalbn (const mpreal & v, mp_exp_t exp) inline
Definition at line 2029 of file mpreal.h.
References ldexp().
sec()
const mpreal mpfr::sec (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2233 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::sec.
sech()
const mpreal mpfr::sech (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2252 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::sech.
sgn()
int mpfr::sgn (const mpreal & op) inline
Definition at line 1934 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
signbit()
bool mpfr::signbit (const mpreal & x) inline
Definition at line 2089 of file mpreal.h.
References mpfr::mpreal::mpfr_srcptr().
sin()
const mpreal mpfr::sin (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2231 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::sin.
sin_cos()
int mpfr::sin_cos (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2213 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), and mpfr::mpreal::mpfr_srcptr().
sinh()
const mpreal mpfr::sinh (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2250 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::sinh.
sinh_cosh()
int mpfr::sinh_cosh (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2399 of file mpreal.h.
sqr()
const mpreal mpfr::sqr (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2164 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::sqr.
Referenced by mmtr().
sqrt() [1/7]
const mpreal mpfr::sqrt (const unsigned int v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2177 of file mpreal.h.
References mpfr::mpreal::sqrt.
sqrt() [2/7]
const mpreal mpfr::sqrt (const long int v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2182 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::sqrt.
sqrt() [3/7]
const mpreal mpfr::sqrt (const int v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2188 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::sqrt.
sqrt() [4/7]
const mpreal mpfr::sqrt (const long double v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2218 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::sqrt.
sqrt() [5/7]
const mpreal mpfr::sqrt (const double v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2219 of file mpreal.h.
References mpfr::mpreal::mpreal(), and mpfr::mpreal::sqrt.
sqrt() [6/7]
const mpreal mpfr::sqrt (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2167 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY.
sqrt() [7/7]
const mpreal mpfr::sqrt (const unsigned long int x, mp_rnd_t r) inline
Definition at line 2170 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), x, and y.
sum()
const mpreal mpfr::sum (const mpreal tab[], const unsigned long int n, int & status, mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 2381 of file mpreal.h.
References i, mpfr::mpreal::mpfr_ptr(), mpfr::mpreal::mpfr_srcptr(), n, p, and x.
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::addTo(), array(), big_sparse_triplet(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::internal::dogleg(), dot(), dotuw(), dsdot(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::evalTo(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), foo(), Eigen::LevenbergMarquardt< _FunctorType >::lm_param(), Eigen::internal::lmpar(), matrixRedux(), Eigen::LevenbergMarquardt< _FunctorType >::minimizeOptimumStorageOneStep(), Eigen::TensorDevice< ExpressionType, DeviceType >::operator+=(), Eigen::internal::pabs< Packet4f >(), Eigen::internal::pblend(), Eigen::internal::pfirst< Packet4i >(), Eigen::internal::predux< Packet16f >(), Eigen::internal::predux< Packet4f >(), Eigen::internal::predux< Packet4i >(), Eigen::internal::predux< Packet8d >(), Eigen::internal::preduxp< Packet4f >(), Eigen::internal::preduxp< Packet4i >(), product(), product1x1(), relerr(), internal::packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >::run(), internal::band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, RowMajor >::run(), Eigen::internal::dot_nocheck< T, U, NeedToTranspose >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >::run(), Eigen::internal::dot_nocheck< T, U, true >::run(), internal::packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor >::run(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::subTo(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::sum(), Eigen::SparseMatrix< scalar_t >::sum(), Eigen::test_relative_error(), test_stress_runqueue(), Eigen::SkylineMatrix< _Scalar, _Options >::~SkylineMatrix(), Eigen::SparseMatrix< scalar_t >::~SparseMatrix(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::~SparseVector().
swap()
void mpfr::swap (mpreal & a, mpreal & b) inline
Definition at line 2546 of file mpreal.h.
Referenced by std::swap().
tan()
const mpreal mpfr::tan (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2232 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::tan.
tanh()
const mpreal mpfr::tanh (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2251 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::tanh.
tgamma()
const mpreal mpfr::tgamma (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2263 of file mpreal.h.
References mpfr::mpreal::gamma, and MPREAL_UNARY_MATH_FUNCTION_BODY.
Referenced by whittaker_functions::RadialWFWhittaker().
toString()
template<class T > std::string mpfr::toString (T t, std::ios_base &(*)(std::ios_base &) f) inline
Definition at line 1726 of file mpreal.h.
trunc()
const mpreal mpfr::trunc (const mpreal & v) inline
Definition at line 2530 of file mpreal.h.
References x.
urandom()
const mpreal mpfr::urandom (gmp_randstate_t & state, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2593 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), and x.
Referenced by random().
urandomb()
const mpreal mpfr::urandomb (gmp_randstate_t & state) inline
Definition at line 2585 of file mpreal.h.
References mpfr::mpreal::mpfr_ptr(), and x.
zeta()
const mpreal mpfr::zeta (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2265 of file mpreal.h.
References MPREAL_UNARY_MATH_FUNCTION_BODY, and mpfr::mpreal::zeta.