pairinteraction: relicense Namespace Reference
relicense Namespace Reference
Functions
def update (text)
Variables
string lgpl3_header
string mpl2_header
exclusions = set(['relicense.py'])
rootdir = sys.argv[1]
filename = os.path.join(root, basename)
fo = file(filename)
text = fo.read()
updated
Function Documentation
update()
def relicense.update (text)
Definition at line 46 of file relicense.py.
Referenced by GpuHelper.forceMatrixTarget(), Eigen::internal.handmade_aligned_realloc(), MandelbrotWidget.mouseMoveEvent(), MandelbrotWidget.mousePressEvent(), MandelbrotWidget.paintEvent(), Eigen::LDLT< _MatrixType, _UpLo >.rankUpdate(), and Eigen::internal::ldlt_inplace< Upper >.update().
Variable Documentation
exclusions
relicense.exclusions = set(['relicense.py'])
Definition at line 44 of file relicense.py.
filename
relicense.filename = os.path.join(root, basename)
Definition at line 57 of file relicense.py.
Referenced by bench(), bench_static(), Eigen::MatrixMarketIterator< Scalar >.Getnextvalidmatrix(), sqlite::handle.handle(), and main().
fo
relicense.fo = file(filename)
Definition at line 58 of file relicense.py.
lgpl3_header
string relicense.lgpl3_header
Initial value:
 =  '''
 // Eigen is free software; you can redistribute it and/or
 // modify it under the terms of the GNU Lesser General Public
 // License as published by the Free Software Foundation; either
 // version 3 of the License, or (at your option) any later version.
 //
 // Alternatively, you can redistribute it and/or
 // modify it under the terms of the GNU General Public License as
 // published by the Free Software Foundation; either version 2 of
 // the License, or (at your option) any later version.
 //
 // Eigen is distributed in the hope that it will be useful, but WITHOUT ANY
 // WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 // FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License or the
 // GNU General Public License for more details.
 //
 // You should have received a copy of the GNU Lesser General Public
 // License and a copy of the GNU General Public License along with
 // Eigen. If not, see <http://www.gnu.org/licenses/>.
 '''
Definition at line 14 of file relicense.py.
mpl2_header
string relicense.mpl2_header
Initial value:
 =  """
 // This Source Code Form is subject to the terms of the Mozilla
 // Public License v. 2.0. If a copy of the MPL was not distributed
 // with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 """
Definition at line 35 of file relicense.py.
rootdir
relicense.rootdir = sys.argv[1]
Definition at line 51 of file relicense.py.
text
relicense.text = fo.read()
Definition at line 59 of file relicense.py.
updated
relicense.updated
Definition at line 62 of file relicense.py.