pairinteraction: boost::serialization Namespace Reference
boost::serialization Namespace Reference
Functions
template<class Archive , typename _Scalar , int _Options, typename _Index >
void serialize (Archive &ar, Eigen::SparseMatrix< _Scalar, _Options, _Index > &m, const unsigned int version)
template<class Archive , typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
void serialize (Archive &ar, Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &m, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, boost::filesystem::path &p, const unsigned int version)
Function Documentation
serialize() [1/3]
template<class Archive , typename _Scalar , int _Options, typename _Index > void boost::serialization::serialize (Archive & ar, Eigen::SparseMatrix< _Scalar, _Options, _Index > & m, const unsigned int version)
Definition at line 26 of file serialization_eigen.h.
References cols, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize(), Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::nonZeros(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros(), rows, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr().
serialize() [2/3]
template<class Archive > void boost::serialization::serialize (Archive & ar, boost::filesystem::path & p, const unsigned int version)
Definition at line 26 of file serialization_path.h.
References s.
serialize() [3/3]
template<class Archive , typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> void boost::serialization::serialize (Archive & ar, Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & m, const unsigned int version)
Definition at line 62 of file serialization_eigen.h.
References cols, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::cols(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), rows, and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::rows().