pairinteraction: Eigen Namespace Reference
Eigen Namespace Reference
Namespace containing all symbols from the Eigen library.
Namespaces
Architecture
half_impl
HybridNonLinearSolverSpace
internal
LevenbergMarquardtSpace
numext
TensorSycl
Data Structures
class aligned_allocator
STL compatible allocator to use with with 16 byte aligned types.
class aligned_allocator_indirection
class AlignedBox
An axis aligned box.
class AMDOrdering
class AngleAxis
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
struct AntiHermiticity
struct AntiSymmetry
class ArpackGeneralizedSelfAdjointEigenSolver
class Array
General-purpose arrays with easy API for coefficient-wise operations.
class array
class array< T, 0 >
class ArrayBase
Base class for all 1D and 2D array, and related expressions.
class ArrayWrapper
Expression of a mathematical vector or matrix as an array object.
struct ArrayXpr
class AutoDiffJacobian
class AutoDiffScalar
A scalar type replacement with automatic differentation capability.
class AutoDiffVector
struct BandShape
class BDCSVD
class Bidiagonal Divide and Conquer SVD
class BenchTimer
class BiCGSTAB
A bi conjugate gradient stabilized solver for sparse square problems.
class Block
Expression of a fixed-size or dynamic-size block.
class BlockImpl
class BlockImpl< const SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols, true, Sparse >
class BlockImpl< SparseMatrix< _Scalar, _Options, _StorageIndex >, BlockRows, BlockCols, true, Sparse >
class BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Dense >
class BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >
class BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >
class BlockSparseMatrix
A versatile sparse matrix representation where each element is a block.
class BlockSparseMatrixView
class BlockSparseTimeDenseProduct
class BlockVectorReturn
class BlockVectorView
class CholmodBase
The base class for the direct Cholesky factorization of Cholmod.
class CholmodDecomposition
A general Cholesky factorization and solver based on Cholmod.
class CholmodSimplicialLDLT
A simplicial direct Cholesky (LDLT) factorization and solver based on Cholmod.
class CholmodSimplicialLLT
A simplicial direct Cholesky (LLT) factorization and solver based on Cholmod.
class CholmodSupernodalLLT
A supernodal Cholesky (LLT) factorization and solver based on Cholmod.
class COLAMDOrdering
class ColPivHouseholderQR
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
class CommaInitializer
Helper class used by the comma initializer operator.
class CompleteOrthogonalDecomposition
Complete orthogonal decomposition (COD) of a matrix.
class ComplexEigenSolver
Computes eigenvalues and eigenvectors of general complex matrices.
class ComplexSchur
Performs a complex Schur decomposition of a real or complex square matrix.
struct Cond
class Conjugate
class ConjugateGradient
A conjugate gradient solver for sparse (or dense) self-adjoint problems.
struct ConversionSubExprEval
struct ConversionSubExprEval< true, Eval, Scalar >
class Cross
class CwiseBinaryOp
Generic expression where a coefficient-wise binary operator is applied to two expressions.
class CwiseBinaryOpImpl
class CwiseBinaryOpImpl< BinaryOp, Lhs, Rhs, Sparse >
class CwiseNullaryOp
Generic expression of a matrix where all coefficients are defined by a functor.
class CwiseTernaryOp
Generic expression where a coefficient-wise ternary operator is applied to two expressions.
class CwiseTernaryOpImpl
class CwiseUnaryOp
Generic expression where a coefficient-wise unary operator is applied to an expression.
class CwiseUnaryOpImpl
class CwiseUnaryView
Generic lvalue expression of a coefficient-wise unary operator of a matrix or a vector.
class CwiseUnaryViewImpl
class CwiseUnaryViewImpl< ViewOp, MatrixType, Dense >
struct DefaultDevice
struct Dense
class DenseBase
Base class for all dense matrices, vectors, and arrays.
class DenseCoeffsBase
class DenseCoeffsBase< Derived, DirectAccessors >
Base class providing direct read-only coefficient access to matrices and arrays.
class DenseCoeffsBase< Derived, DirectWriteAccessors >
Base class providing direct read/write coefficient access to matrices and arrays.
class DenseCoeffsBase< Derived, ReadOnlyAccessors >
Base class providing read-only coefficient access to matrices and arrays.
class DenseCoeffsBase< Derived, WriteAccessors >
Base class providing read/write coefficient access to matrices and arrays.
struct DenseFunctor
struct DenseShape
struct DenseSparseProductReturnType
class DenseStorage
class DenseStorage< T, 0, _Rows, _Cols, _Options >
class DenseStorage< T, 0, _Rows, Dynamic, _Options >
class DenseStorage< T, 0, Dynamic, _Cols, _Options >
class DenseStorage< T, 0, Dynamic, Dynamic, _Options >
class DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >
class DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >
class DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >
class DenseStorage< T, Size, _Rows, Dynamic, _Options >
class DenseStorage< T, Size, Dynamic, _Cols, _Options >
class DenseStorage< T, Size, Dynamic, Dynamic, _Options >
class DenseTimeSparseProduct
class DGMRES
A Restarted GMRES with deflation. This class implements a modification of the GMRES solver for sparse linear systems. The basis is built with modified Gram-Schmidt. At each restart, a few approximated eigenvectors corresponding to the smallest eigenvalues are used to build a preconditioner for the next cycle. This preconditioner for deflation can be combined with any other preconditioner, the IncompleteLUT for instance. The preconditioner is applied at right of the matrix and the combination is multiplicative.
class Diagonal
Expression of a diagonal/subdiagonal/superdiagonal in a matrix.
class DiagonalBase
class DiagonalMatrix
Represents a diagonal matrix with its storage.
class DiagonalPreconditioner
A preconditioner based on the digonal entries.
class DiagonalProduct
struct DiagonalShape
class DiagonalWrapper
Expression of a diagonal matrix.
struct DimensionList
struct DSizes
class DynamicSGroup
Dynamic symmetry group.
class DynamicSGroupFromTemplateArgs
class DynamicSkylineMatrix
class DynamicSparseMatrix
A sparse matrix class designed for matrix assembly purpose.
struct eigen_assert_exception
class EigenBase
class EigenSolver
Computes eigenvalues and eigenvectors of general matrices.
class EulerAngles
Represents a rotation in a 3 dimensional space as three Euler angles.
class EulerSystem
Represents a fixed Euler rotation system.
class EventCount
class Flagged
class ForceAlignedAccess
Enforce aligned packet loads and stores regardless of what is requested.
class FullPivHouseholderQR
Householder rank-revealing QR decomposition of a matrix with full pivoting.
class FullPivLU
LU decomposition of a matrix with complete pivoting, and related features.
struct general_product_to_triangular_selector
struct general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >
struct general_product_to_triangular_selector< MatrixType, ProductType, UpLo, true >
class GeneralizedEigenSolver
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
class GeneralizedSelfAdjointEigenSolver
Computes eigenvalues and eigenvectors of the generalized selfadjoint eigen problem.
struct GenericNumTraits
class GMRES
A GMRES solver for sparse square problems.
struct half
struct Hermiticity
class HessenbergDecomposition
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
class Homogeneous
Expression of one (or a set of) homogeneous vector(s)
struct HomogeneousShape
class HouseholderQR
Householder QR decomposition of a matrix.
class HouseholderSequence
Sequence of Householder reflections acting on subspaces with decreasing size.
class HybridNonLinearSolver
Finds a zero of a system of n nonlinear functions in n variables by a modification of the Powell hybrid method ("dogleg").
class Hyperplane
A hyperplane.
class IdentityPreconditioner
A naive preconditioner which approximates any matrix as the identity matrix.
class IncompleteCholesky
Modified Incomplete Cholesky with dual threshold.
class IncompleteLU
class IncompleteLUT
Incomplete LU factorization with dual-threshold strategy.
struct IndexPair
class InnerIterator
An InnerIterator allows to loop over the element of any matrix expression.
class InnerStride
Convenience specialization of Stride to specify only an inner stride See class Map for some examples.
class Inverse
Expression of the inverse of another expression.
class InverseImpl
class InverseImpl< PermutationType, PermutationStorage >
class IOFormat
Stores a set of parameters controlling the way matrices are printed.
class IterationController
Controls the iterations of the iterative solvers.
class IterativeSolverBase
Base class for linear iterative solvers.
class IterScaling
iterative scaling algorithm to equilibrate rows and column norms in matrices
class JacobiRotation
Rotation given by a cosine-sine pair.
class JacobiSVD
Two-sided Jacobi SVD decomposition of a rectangular matrix.
class KdBVH
A simple bounding volume hierarchy based on AlignedBox.
class KroneckerProduct
Kronecker tensor product helper class for dense matrices.
class KroneckerProductBase
The base class of dense and sparse Kronecker product.
class KroneckerProductSparse
Kronecker tensor product helper class for sparse matrices.
struct LazyProductReturnType
class LDLT
Robust Cholesky decomposition of a matrix with pivoting.
class LeastSquareDiagonalPreconditioner
Jacobi preconditioner for LeastSquaresConjugateGradient.
class LeastSquaresConjugateGradient
A conjugate gradient solver for sparse (or dense) least-square problems.
class LevenbergMarquardt
Performs non linear optimization over a non-linear function, using a variant of the Levenberg Marquardt algorithm.
class LLT
Standard Cholesky decomposition (LL^T) of a matrix and associated features.
struct MakePointer
class Map
A matrix or vector expression mapping an existing array of data.
class Map< const Quaternion< _Scalar >, _Options >
Quaternion expression mapping a constant memory buffer.
class Map< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >
class Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, _PacketAccess >
class Map< Quaternion< _Scalar >, _Options >
Expression of a quaternion from a memory buffer.
class Map< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >
Specialization of class Map for SparseMatrix-like storage.
class Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, PacketAccess >
class MapBase
class MapBase< Derived, ReadOnlyAccessors >
Base class for dense Map and Block expression with direct access.
class MapBase< Derived, WriteAccessors >
Base class for non-const dense Map and Block expression with direct access.
class MappedSkylineMatrix
class MappedSparseMatrix
Sparse matrix.
class Matrix
The matrix class, also used for vectors and row-vectors.
class MatrixBase
Base class for all dense matrices, vectors, and expressions.
class MatrixComplexPowerReturnValue
Proxy for the matrix power of some matrix (expression).
struct MatrixExponentialReturnValue
Proxy for the matrix exponential of some matrix (expression).
class MatrixFunctionReturnValue
Proxy for the matrix function of some matrix (expression).
class MatrixLogarithmReturnValue
Proxy for the matrix logarithm of some matrix (expression).
class MatrixMarketIterator
Iterator to browse matrices from a specified folder.
class MatrixPower
Class for computing matrix powers.
class MatrixPowerAtomic
Class for computing matrix powers.
class MatrixPowerParenthesesReturnValue
Proxy for the matrix power of some matrix.
class MatrixPowerReturnValue
Proxy for the matrix power of some matrix (expression).
class MatrixSquareRootReturnValue
Proxy for the matrix square root of some matrix (expression).
class MatrixWrapper
Expression of an array as a mathematical vector or matrix.
struct MatrixXpr
struct max_n_1
struct max_n_1< 0 >
class MaxSizeVector
The MaxSizeVector class.
class MetisOrdering
class MINRES
A minimal residual solver for sparse symmetric problems.
class NaturalOrdering
class NestByValue
Expression which must be nested by value.
class NoAlias
Pseudo expression providing an operator = assuming no aliasing.
class NonBlockingThreadPoolTempl
class NumericalDiff
class NumTraits
Holds information about the various numeric (i.e. scalar) types allowed by Eigen.
struct NumTraits< Array< Scalar, Rows, Cols, Options, MaxRows, MaxCols > >
struct NumTraits< AutoDiffScalar< DerType > >
struct NumTraits< boost::multiprecision::detail::expression< T1, T2, T3, T4, T5 > >
struct NumTraits< double >
struct NumTraits< Eigen::half >
struct NumTraits< float >
struct NumTraits< long double >
struct NumTraits< Real >
struct NumTraits< std::complex< _Real > >
struct NumTraits< std::string >
struct NumTraits< void >
class OuterStride
Convenience specialization of Stride to specify only an outer stride See class Map for some examples.
struct PacketConverter
struct PacketConverter< TensorEvaluator, SrcPacket, TgtPacket, 1, 2 >
struct PacketConverter< TensorEvaluator, SrcPacket, TgtPacket, 2, 1 >
struct PacketConverter< TensorEvaluator, SrcPacket, TgtPacket, 4, 1 >
struct PacketType
class ParametrizedLine
A parametrized line.
class PardisoImpl
class PardisoLDLT
A sparse direct Cholesky (LDLT) factorization and solver based on the PARDISO library.
class PardisoLLT
A sparse direct Cholesky (LLT) factorization and solver based on the PARDISO library.
class PardisoLU
A sparse direct LU factorization and solver based on the PARDISO library.
class PartialPivLU
LU decomposition of a matrix with partial pivoting, and related features.
class PartialReduxExpr
Generic expression of a partially reduxed matrix.
class PastixBase
class PastixLDLT
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
class PastixLLT
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
class PastixLU
Interface to the PaStix solver.
class PermutationBase
Base class for permutations.
class PermutationMatrix
Permutation matrix.
struct PermutationShape
struct PermutationStorage
class PermutationWrapper
Class to view a vector of integers as a permutation matrix.
class PlainObjectBase
class PolynomialSolver
A polynomial solver.
class PolynomialSolver< _Scalar, 1 >
class PolynomialSolverBase
Defined to be inherited by polynomial solvers: it provides convenient methods such as.
class Product
Expression of the product of two arbitrary matrices or vectors.
class ProductImpl
class ProductImpl< Lhs, Rhs, Option, Dense >
struct ProductReturnType
class Quaternion
The quaternion class used to represent 3D orientations and rotations.
class QuaternionBase
Base class for quaternion expressions.
class RandomSetter
The RandomSetter is a wrapper object allowing to set/update a sparse matrix with random access.
class RealQZ
Performs a real QZ decomposition of a pair of square matrices.
class RealSchur
Performs a real Schur decomposition of a square matrix.
class Ref
A matrix or vector expression mapping an existing expression.
class Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >
class Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >
class Ref< const TPlainObjectType, Options, StrideType >
class Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >
A sparse matrix expression referencing an existing sparse expression.
class Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >
A sparse vector expression referencing an existing sparse vector expression.
class RefBase
class Replicate
Expression of the multiple replication of a matrix or vector.
class ReturnByValue
class Reverse
Expression of the reverse of a vector or matrix.
class Rotation2D
Represents a rotation/orientation in a 2 dimensional space.
class RotationBase
Common base class for compact rotation representations.
class RunQueue
class ScalarBinaryOpTraits
Determines whether the given binary operation of two numeric types is allowed and what the scalar return type is.
struct ScalarBinaryOpTraits< AutoDiffScalar< DerType >, typename DerType::Scalar, BinOp >
struct ScalarBinaryOpTraits< T, T, BinaryOp >
struct ScalarBinaryOpTraits< T, typename NumTraits< typename internal::enable_if< NumTraits< T >::IsComplex, T >::type >::Real, BinaryOp >
struct ScalarBinaryOpTraits< T, void, BinaryOp >
struct ScalarBinaryOpTraits< typename DerType::Scalar, AutoDiffScalar< DerType >, BinOp >
struct ScalarBinaryOpTraits< typename NumTraits< typename internal::enable_if< NumTraits< T >::IsComplex, T >::type >::Real, T, BinaryOp >
struct ScalarBinaryOpTraits< void, T, BinaryOp >
struct ScalarBinaryOpTraits< void, void, BinaryOp >
struct ScanLauncher
class Select
Expression of a coefficient wise version of the C++ ternary operator ?:
struct selfadjoint_product_selector
struct selfadjoint_product_selector< MatrixType, OtherType, UpLo, false >
struct selfadjoint_product_selector< MatrixType, OtherType, UpLo, true >
struct selfadjoint_rank1_update
struct selfadjoint_rank1_update< Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs >
struct selfadjoint_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >
class SelfAdjointEigenSolver
Computes eigenvalues and eigenvectors of selfadjoint matrices.
struct SelfAdjointShape
class SelfAdjointView
Expression of a selfadjoint matrix from a triangular part of a dense matrix.
class SGroup
Symmetry group, initialized from template arguments.
class SimpleThreadPoolTempl
class SimplicialCholesky
class SimplicialCholeskyBase
A base class for direct sparse Cholesky factorizations.
class SimplicialLDLT
A direct sparse LDLT Cholesky factorizations without square root.
class SimplicialLLT
A direct sparse LLT Cholesky factorizations.
struct Sizes
class SkylineInplaceLU
Inplace LU decomposition of a skyline matrix and associated features.
class SkylineMatrix
The main skyline matrix class.
class SkylineMatrixBase
Base class of any skyline matrices or skyline expressions.
class SkylineProduct
struct SkylineProductReturnType
class SkylineStorage
class SkylineVector
struct SluMatrix
struct SluMatrixMapHelper
struct SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >
struct SluMatrixMapHelper< SparseMatrixBase< Derived > >
class Solve
Pseudo expression representing a solving operation.
class SolveImpl
class SolveImpl< Decomposition, RhsType, Dense >
class SolverBase
A base class for matrix decomposition and solvers.
struct SolverShape
struct SolverStorage
class SolveWithGuess
Pseudo expression representing a solving operation.
struct Sparse
class SparseCompressedBase
Common base class for sparse [compressed]-{row|column}-storage format.
class SparseDenseOuterProduct
struct SparseDenseProductReturnType
class SparseDiagonalProduct
struct SparseFunctor
class SparseLU
Sparse supernodal LU factorization for general matrices.
struct SparseLUMatrixLReturnType
struct SparseLUMatrixUReturnType
class SparseMapBase
class SparseMapBase< Derived, ReadOnlyAccessors >
Common base class for Map and Ref instance of sparse matrix and vector.
class SparseMapBase< Derived, WriteAccessors >
Common base class for writable Map and Ref instance of sparse matrix and vector.
class SparseMatrix
A versatible sparse matrix representation.
class SparseMatrixBase
Base class of any sparse matrices or sparse expressions.
class SparseQR
Sparse left-looking rank-revealing QR factorization.
struct SparseQR_QProduct
struct SparseQRMatrixQReturnType
struct SparseQRMatrixQTransposeReturnType
class SparseSelfAdjointView
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
struct SparseShape
class SparseSolverBase
A base class for sparse solvers.
class SparseSparseProduct
struct SparseSparseProductReturnType
class SparseSymmetricPermutationProduct
class SparseTimeDenseProduct
class SparseVector
a sparse vector class
class SparseView
Expression of a dense or sparse matrix with zero or too small values removed.
class Spline
A class representing multi-dimensional spline curves.
struct SplineFitting
Spline fitting methods.
struct SplineTraits
struct SplineTraits< Spline< _Scalar, _Dim, _Degree >, _DerivativeOrder >
Compile-time attributes of the Spline class for fixed degree.
struct SplineTraits< Spline< _Scalar, _Dim, _Degree >, Dynamic >
Compile-time attributes of the Spline class for Dynamic degree.
class SPQR
Sparse QR factorization based on SuiteSparseQR library.
struct SPQR_QProduct
struct SPQRMatrixQReturnType
struct SPQRMatrixQTransposeReturnType
class StaticSGroup
Static symmetry group.
struct StdMapTraits
struct StlThreadEnvironment
class Stride
Holds strides information for Map.
class SuperLU
A sparse direct LU factorization and solver based on the SuperLU library.
class SuperLUBase
The base class for the direct and incomplete LU factorization of SuperLU.
class SVDBase
Base class of SVD algorithms.
class SwapWrapper
struct Symmetry
class Tensor
The tensor class.
class TensorAssignOp
class TensorBase
The tensor base class.
class TensorBase< Derived, ReadOnlyAccessors >
class TensorBroadcastingOp
class TensorChippingOp
class TensorConcatenationOp
Tensor concatenation class.
struct TensorContractionEvaluatorBase
class TensorContractionOp
class TensorConversionOp
Tensor conversion class. This class makes it possible to vectorize type casting operations when the number of scalars per packet in the source and the destination type differ.
class TensorConvolutionOp
class TensorCostModel
class TensorCustomBinaryOp
Tensor custom class.
class TensorCustomUnaryOp
Tensor custom class.
class TensorCwiseBinaryOp
class TensorCwiseNullaryOp
class TensorCwiseTernaryOp
class TensorCwiseUnaryOp
class TensorDevice
Pseudo expression providing an operator = that will evaluate its argument on the specified computing 'device' (GPU, thread pool, ...)
class TensorEvalToOp
class TensorEvaluator
A cost model used to limit the number of threads used for evaluating tensor expression.
struct TensorEvaluator< const Derived, Device >
struct TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >
struct TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >
struct TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >
struct TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >
struct TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType >, Device >
struct TensorEvaluator< const TensorConversionOp< TargetType, ArgType >, Device >
struct TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >
struct TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >
struct TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >
struct TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >
struct TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >
struct TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >
struct TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >
struct TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >
struct TensorEvaluator< const TensorForcedEvalOp< ArgType, MakePointer_ >, Device >
struct TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >
struct TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >
struct TensorEvaluator< const TensorIndexTupleOp< ArgType >, Device >
struct TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >
struct TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >
struct TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >
struct TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >
struct TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >
struct TensorEvaluator< const TensorRef< Derived >, Device >
struct TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >
struct TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >
struct TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >
struct TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >
struct TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >
struct TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
struct TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >
struct TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >
struct TensorEvaluator< const TensorTupleReducerOp< ReduceOp, Dims, ArgType >, Device >
struct TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >
struct TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >
struct TensorEvaluator< TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >
struct TensorEvaluator< TensorLayoutSwapOp< ArgType >, Device >
struct TensorEvaluator< TensorRef< Derived >, Device >
struct TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >
struct TensorEvaluator< TensorReverseOp< ReverseDimensions, ArgType >, Device >
struct TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >
struct TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
struct TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >
struct TensorEvaluator< TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >
class TensorFFTOp
class TensorFixedSize
The fixed sized version of the tensor class.
class TensorForcedEvalOp
class TensorGeneratorOp
class TensorImagePatchOp
class TensorIndexTupleOp
class TensorInflationOp
class TensorLayoutSwapOp
class TensorMap
A tensor expression mapping an existing array of data.
class TensorOpCost
class TensorPaddingOp
class TensorPatchOp
class TensorReductionOp
class TensorRef
A reference to a tensor expression The expression will be evaluated lazily (as much as possible).
class TensorReshapingOp
class TensorReverseOp
class TensorScanOp
class TensorSelectOp
class TensorShufflingOp
class TensorSlicingOp
class TensorStorage
class TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >
class TensorStorage< T, FixedDimensions, Options_ >
class TensorStridingOp
class TensorStridingSlicingOp
class TensorTupleReducerOp
class TensorVolumePatchOp
class ThreadPoolInterface
class Transform
Represents an homogeneous transformation in a N dimensional space.
class Translation
Represents a translation transformation.
class Transpose
Expression of the transpose of a matrix.
class Transpose< TranspositionsBase< TranspositionsDerived > >
class TransposeImpl
class TransposeImpl< MatrixType, Dense >
class TransposeImpl< MatrixType, Sparse >
class Transpositions
Represents a sequence of transpositions (row/column interchange)
class TranspositionsBase
struct TranspositionsShape
struct TranspositionsStorage
class TranspositionsWrapper
class TriangularBase
Base class for triangular part in a matrix.
struct TriangularShape
class TriangularView
Expression of a triangular part in a matrix.
class TriangularViewImpl
class TriangularViewImpl< _MatrixType, _Mode, Dense >
Base class for a triangular part in a dense matrix.
class TriangularViewImpl< MatrixType, Mode, Sparse >
Base class for a triangular part in a sparse matrix.
class Tridiagonalization
Tridiagonal decomposition of a selfadjoint matrix.
class Triplet
A small structure to hold a non zero as a triplet (i,j,value).
struct Tuple
class UmfPackLU
A sparse LU factorization and solver based on UmfPack.
class UniformScaling
class VectorBlock
Expression of a fixed-size or dynamic-size sub-vector.
class VectorwiseOp
Pseudo expression providing partial reduction operations.
class WithFormat
Pseudo expression providing matrix output with given format.
Typedefs
typedef EIGEN_DEFAULT_DENSE_INDEX_TYPE DenseIndex
typedef EIGEN_DEFAULT_DENSE_INDEX_TYPE Index
The Index type as used for the API.
typedef std::complex< double > dcomplex
typedef std::complex< float > scomplex
typedef int BlasIndex
typedef AngleAxis< float > AngleAxisf
typedef AngleAxis< double > AngleAxisd
typedef Quaternion< float > Quaternionf
typedef Quaternion< double > Quaterniond
typedef Map< Quaternion< float >, 0 > QuaternionMapf
typedef Map< Quaternion< double >, 0 > QuaternionMapd
typedef Map< Quaternion< float >, Aligned > QuaternionMapAlignedf
typedef Map< Quaternion< double >, Aligned > QuaternionMapAlignedd
typedef Rotation2D< float > Rotation2Df
typedef Rotation2D< double > Rotation2Dd
typedef DiagonalMatrix< float, 2 > AlignedScaling2f
typedef DiagonalMatrix< double, 2 > AlignedScaling2d
typedef DiagonalMatrix< float, 3 > AlignedScaling3f
typedef DiagonalMatrix< double, 3 > AlignedScaling3d
typedef Transform< float, 2, Isometry > Isometry2f
typedef Transform< float, 3, Isometry > Isometry3f
typedef Transform< double, 2, Isometry > Isometry2d
typedef Transform< double, 3, Isometry > Isometry3d
typedef Transform< float, 2, Affine > Affine2f
typedef Transform< float, 3, Affine > Affine3f
typedef Transform< double, 2, Affine > Affine2d
typedef Transform< double, 3, Affine > Affine3d
typedef Transform< float, 2, AffineCompact > AffineCompact2f
typedef Transform< float, 3, AffineCompact > AffineCompact3f
typedef Transform< double, 2, AffineCompact > AffineCompact2d
typedef Transform< double, 3, AffineCompact > AffineCompact3d
typedef Transform< float, 2, Projective > Projective2f
typedef Transform< float, 3, Projective > Projective3f
typedef Transform< double, 2, Projective > Projective2d
typedef Transform< double, 3, Projective > Projective3d
typedef Translation< float, 2 > Translation2f
typedef Translation< double, 2 > Translation2d
typedef Translation< float, 3 > Translation3f
typedef Translation< double, 3 > Translation3d
typedef NonBlockingThreadPoolTempl< StlThreadEnvironment > NonBlockingThreadPool
typedef SimpleThreadPoolTempl< StlThreadEnvironment > SimpleThreadPool
typedef Spline< float, 2 > Spline2f
2D float B-spline with dynamic degree.
typedef Spline< float, 3 > Spline3f
3D float B-spline with dynamic degree.
typedef Spline< double, 2 > Spline2d
2D double B-spline with dynamic degree.
typedef Spline< double, 3 > Spline3d
3D double B-spline with dynamic degree.
Enumerations
enum { CPU_TIMER = 0, REAL_TIMER = 1 }
enum CholmodMode { CholmodAuto, CholmodSimplicialLLt, CholmodSupernodalLLt, CholmodLDLt }
enum { Large = 2, Small = 3 }
enum { DontAlignCols = 1 }
enum { StreamPrecision = -1, FullPrecision = -2 }
enum UpLoType {
Lower =0x1, Upper =0x2, UnitDiag =0x4, ZeroDiag =0x8,
UnitLower =UnitDiag|Lower, UnitUpper =UnitDiag|Upper, StrictlyLower =ZeroDiag|Lower, StrictlyUpper =ZeroDiag|Upper,
SelfAdjoint =0x10, Symmetric =0x20
}
enum AlignmentType {
Unaligned =0, Aligned8 =8, Aligned16 =16, Aligned32 =32,
Aligned64 =64, Aligned128 =128, AlignedMask =255, Aligned =16,
AlignedMax = Unaligned
}
enum CornerType { TopLeft, TopRight, BottomLeft, BottomRight }
enum DirectionType { Vertical, Horizontal, BothDirections }
enum TraversalType {
DefaultTraversal, LinearTraversal, InnerVectorizedTraversal, LinearVectorizedTraversal,
SliceVectorizedTraversal, InvalidTraversal, AllAtOnceTraversal
}
enum UnrollingType { NoUnrolling, InnerUnrolling, CompleteUnrolling }
enum SpecializedType { Specialized, BuiltIn }
enum StorageOptions { ColMajor = 0, RowMajor = 0x1, AutoAlign = 0, DontAlign = 0x2 }
enum SideType { OnTheLeft = 1, OnTheRight = 2 }
enum NoChange_t { NoChange }
enum Sequential_t { Sequential }
enum Default_t { Default }
enum AmbiVectorMode { IsDense = 0, IsSparse }
enum AccessorLevels { ReadOnlyAccessors, WriteAccessors, DirectAccessors, DirectWriteAccessors }
enum DecompositionOptions {
Pivoting = 0x01, NoPivoting = 0x02, ComputeFullU = 0x04, ComputeThinU = 0x08,
ComputeFullV = 0x10, ComputeThinV = 0x20, EigenvaluesOnly = 0x40, ComputeEigenvectors = 0x80,
EigVecMask = EigenvaluesOnly | ComputeEigenvectors, Ax_lBx = 0x100, ABx_lx = 0x200, BAx_lx = 0x400,
GenEigMask = Ax_lBx | ABx_lx | BAx_lx
}
enum QRPreconditioners { NoQRPreconditioner, HouseholderQRPreconditioner, ColPivHouseholderQRPreconditioner, FullPivHouseholderQRPreconditioner }
enum ComputationInfo { Success = 0, NumericalIssue = 1, NoConvergence = 2, InvalidInput = 3 }
enum TransformTraits { Isometry = 0x1, Affine = 0x2, AffineCompact = 0x10 | Affine, Projective = 0x20 }
enum ProductImplType {
DefaultProduct =0, LazyProduct, AliasFreeProduct, CoeffBasedProductMode,
LazyCoeffBasedProductMode, OuterProduct, InnerProduct, GemvProduct,
GemmProduct
}
enum Action { GetAction, SetAction }
enum SimplicialCholeskyMode { SimplicialCholeskyLLT, SimplicialCholeskyLDLT }
enum { StandardCompressedFormat = 2 }
enum FFTResultType { RealPart = 0, ImagPart = 1, BothParts = 2 }
enum FFTDirection { FFT_FORWARD = 0, FFT_REVERSE = 1 }
enum PaddingType { PADDING_VALID = 1, PADDING_SAME = 2 }
enum { NegationFlag = 0x01, ConjugationFlag = 0x02 }
enum { GlobalRealFlag = 0x01, GlobalImagFlag = 0x02, GlobalZeroFlag = 0x03 }
enum EulerAxis { EULER_X = 1, EULER_Y = 2, EULER_Z = 3 }
Representation of a fixed signed rotation axis for EulerSystem.
enum NumericalDiffMode { Forward, Central }
enum AdditionalProductEvaluationMode { SkylineTimeDenseProduct, SkylineTimeSkylineProduct, DenseTimeSkylineProduct }
enum { IsSkyline = SkylineBit }
enum { SPD = 0x100, NonSymmetric = 0x0 }
Functions
template<typename _Scalar , int _Options, typename _StorageIndex >
cholmod_sparse viewAsCholmod (Ref< SparseMatrix< _Scalar, _Options, _StorageIndex > > mat)
template<typename _Scalar , int _Options, typename _Index >
const cholmod_sparse viewAsCholmod (const SparseMatrix< _Scalar, _Options, _Index > &mat)
template<typename _Scalar , int _Options, typename _Index >
const cholmod_sparse viewAsCholmod (const SparseVector< _Scalar, _Options, _Index > &mat)
template<typename _Scalar , int _Options, typename _Index , unsigned int UpLo>
cholmod_sparse viewAsCholmod (const SparseSelfAdjointView< const SparseMatrix< _Scalar, _Options, _Index >, UpLo > &mat)
template<typename Derived >
cholmod_dense viewAsCholmod (MatrixBase< Derived > &mat)
template<typename Scalar , int Flags, typename StorageIndex >
MappedSparseMatrix< Scalar, Flags, StorageIndex > viewAsEigen (cholmod_sparse &cm)
template<typename Derived >
const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (Derived, typename Derived::Scalar, pow) pow(const Eigen
template<typename Derived >
const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE (typename Derived::Scalar, Derived, pow) pow(const typename Derived
template<typename MatrixDerived , typename PermutationDerived >
EIGEN_DEVICE_FUNC const Product< MatrixDerived, PermutationDerived, AliasFreeProduct > operator* (const MatrixBase< MatrixDerived > &matrix, const PermutationBase< PermutationDerived > &permutation)
template<typename PermutationDerived , typename MatrixDerived >
EIGEN_DEVICE_FUNC const Product< PermutationDerived, MatrixDerived, AliasFreeProduct > operator* (const PermutationBase< PermutationDerived > &permutation, const MatrixBase< MatrixDerived > &matrix)
std::ptrdiff_t l1CacheSize ()
std::ptrdiff_t l2CacheSize ()
std::ptrdiff_t l3CacheSize ()
void setCpuCacheSizes (std::ptrdiff_t l1, std::ptrdiff_t l2, std::ptrdiff_t l3)
void initParallel ()
int nbThreads ()
void setNbThreads (int v)
template<typename MatrixDerived , typename TranspositionsDerived >
EIGEN_DEVICE_FUNC const Product< MatrixDerived, TranspositionsDerived, AliasFreeProduct > operator* (const MatrixBase< MatrixDerived > &matrix, const TranspositionsBase< TranspositionsDerived > &transpositions)
template<typename TranspositionsDerived , typename MatrixDerived >
EIGEN_DEVICE_FUNC const Product< TranspositionsDerived, MatrixDerived, AliasFreeProduct > operator* (const TranspositionsBase< TranspositionsDerived > &transpositions, const MatrixBase< MatrixDerived > &matrix)
UniformScaling< float > Scaling (float s)
UniformScaling< double > Scaling (double s)
template<typename RealScalar >
UniformScaling< std::complex< RealScalar > > Scaling (const std::complex< RealScalar > &s)
template<typename Scalar >
DiagonalMatrix< Scalar, 2 > Scaling (const Scalar &sx, const Scalar &sy)
template<typename Scalar >
DiagonalMatrix< Scalar, 3 > Scaling (const Scalar &sx, const Scalar &sy, const Scalar &sz)
template<typename Derived >
const DiagonalWrapper< const Derived > Scaling (const MatrixBase< Derived > &coeffs)
template<typename Derived , typename OtherDerived >
internal::umeyama_transform_matrix_type< Derived, OtherDerived >::type umeyama (const MatrixBase< Derived > &src, const MatrixBase< OtherDerived > &dst, bool with_scaling=true)
Returns the transformation between two point sets.
template<typename OtherDerived , typename VectorsType , typename CoeffsType , int Side>
internal::matrix_type_times_scalar_type< typename VectorsType::Scalar, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other, const HouseholderSequence< VectorsType, CoeffsType, Side > &h)
Computes the product of a matrix with a Householder sequence.
template<typename VectorsType , typename CoeffsType >
HouseholderSequence< VectorsType, CoeffsType > householderSequence (const VectorsType &v, const CoeffsType &h)
Convenience function for constructing a Householder sequence.
template<typename VectorsType , typename CoeffsType >
HouseholderSequence< VectorsType, CoeffsType, OnTheRight > rightHouseholderSequence (const VectorsType &v, const CoeffsType &h)
Convenience function for constructing a Householder sequence.
template<typename DenseDerived , typename SparseDerived >
EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_sum_op< typename DenseDerived::Scalar, typename SparseDerived::Scalar >, const DenseDerived, const SparseDerived > operator+ (const MatrixBase< DenseDerived > &a, const SparseMatrixBase< SparseDerived > &b)
template<typename SparseDerived , typename DenseDerived >
EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_sum_op< typename SparseDerived::Scalar, typename DenseDerived::Scalar >, const SparseDerived, const DenseDerived > operator+ (const SparseMatrixBase< SparseDerived > &a, const MatrixBase< DenseDerived > &b)
template<typename DenseDerived , typename SparseDerived >
EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_difference_op< typename DenseDerived::Scalar, typename SparseDerived::Scalar >, const DenseDerived, const SparseDerived > operator- (const MatrixBase< DenseDerived > &a, const SparseMatrixBase< SparseDerived > &b)
template<typename SparseDerived , typename DenseDerived >
EIGEN_STRONG_INLINE const CwiseBinaryOp< internal::scalar_difference_op< typename SparseDerived::Scalar, typename DenseDerived::Scalar >, const SparseDerived, const DenseDerived > operator- (const SparseMatrixBase< SparseDerived > &a, const MatrixBase< DenseDerived > &b)
template<typename SparseDerived , typename PermDerived >
const Product< SparseDerived, PermDerived, AliasFreeProduct > operator* (const SparseMatrixBase< SparseDerived > &matrix, const PermutationBase< PermDerived > &perm)
template<typename SparseDerived , typename PermDerived >
const Product< PermDerived, SparseDerived, AliasFreeProduct > operator* (const PermutationBase< PermDerived > &perm, const SparseMatrixBase< SparseDerived > &matrix)
template<typename SparseDerived , typename PermutationType >
const Product< SparseDerived, Inverse< PermutationType >, AliasFreeProduct > operator* (const SparseMatrixBase< SparseDerived > &matrix, const InverseImpl< PermutationType, PermutationStorage > &tperm)
template<typename SparseDerived , typename PermutationType >
const Product< Inverse< PermutationType >, SparseDerived, AliasFreeProduct > operator* (const InverseImpl< PermutationType, PermutationStorage > &tperm, const SparseMatrixBase< SparseDerived > &matrix)
void umfpack_defaults (double control[UMFPACK_CONTROL], double)
void umfpack_defaults (double control[UMFPACK_CONTROL], std::complex< double >)
void umfpack_report_info (double control[UMFPACK_CONTROL], double info[UMFPACK_INFO], double)
void umfpack_report_info (double control[UMFPACK_CONTROL], double info[UMFPACK_INFO], std::complex< double >)
void umfpack_report_status (double control[UMFPACK_CONTROL], int status, double)
void umfpack_report_status (double control[UMFPACK_CONTROL], int status, std::complex< double >)
void umfpack_report_control (double control[UMFPACK_CONTROL], double)
void umfpack_report_control (double control[UMFPACK_CONTROL], std::complex< double >)
void umfpack_free_numeric (void **Numeric, double)
void umfpack_free_numeric (void **Numeric, std::complex< double >)
void umfpack_free_symbolic (void **Symbolic, double)
void umfpack_free_symbolic (void **Symbolic, std::complex< double >)
int umfpack_symbolic (int n_row, int n_col, const int Ap[], const int Ai[], const double Ax[], void **Symbolic, const double Control [UMFPACK_CONTROL], double Info [UMFPACK_INFO])
int umfpack_symbolic (int n_row, int n_col, const int Ap[], const int Ai[], const std::complex< double > Ax[], void **Symbolic, const double Control [UMFPACK_CONTROL], double Info [UMFPACK_INFO])
int umfpack_numeric (const int Ap[], const int Ai[], const double Ax[], void *Symbolic, void **Numeric, const double Control[UMFPACK_CONTROL], double Info [UMFPACK_INFO])
int umfpack_numeric (const int Ap[], const int Ai[], const std::complex< double > Ax[], void *Symbolic, void **Numeric, const double Control[UMFPACK_CONTROL], double Info [UMFPACK_INFO])
int umfpack_solve (int sys, const int Ap[], const int Ai[], const double Ax[], double X[], const double B[], void *Numeric, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO])
int umfpack_solve (int sys, const int Ap[], const int Ai[], const std::complex< double > Ax[], std::complex< double > X[], const std::complex< double > B[], void *Numeric, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO])
int umfpack_get_lunz (int *lnz, int *unz, int *n_row, int *n_col, int *nz_udiag, void *Numeric, double)
int umfpack_get_lunz (int *lnz, int *unz, int *n_row, int *n_col, int *nz_udiag, void *Numeric, std::complex< double >)
int umfpack_get_numeric (int Lp[], int Lj[], double Lx[], int Up[], int Ui[], double Ux[], int P[], int Q[], double Dx[], int *do_recip, double Rs[], void *Numeric)
int umfpack_get_numeric (int Lp[], int Lj[], std::complex< double > Lx[], int Up[], int Ui[], std::complex< double > Ux[], int P[], int Q[], std::complex< double > Dx[], int *do_recip, double Rs[], void *Numeric)
int umfpack_get_determinant (double *Mx, double *Ex, void *NumericHandle, double User_Info [UMFPACK_INFO])
int umfpack_get_determinant (std::complex< double > *Mx, double *Ex, void *NumericHandle, double User_Info [UMFPACK_INFO])
template<>
Real test_precision< Real > ()
template<typename Lhs , typename Rhs >
const Product< Lhs, Rhs > prod (const Lhs &lhs, const Rhs &rhs)
template<typename Lhs , typename Rhs >
const Product< Lhs, Rhs, LazyProduct > lazyprod (const Lhs &lhs, const Rhs &rhs)
template<typename DstXprType , typename SrcXprType >
EIGEN_STRONG_INLINE DstXprType & copy_using_evaluator (const EigenBase< DstXprType > &dst, const SrcXprType &src)
template<typename DstXprType , template< typename > class StorageBase, typename SrcXprType >
EIGEN_STRONG_INLINE const DstXprType & copy_using_evaluator (const NoAlias< DstXprType, StorageBase > &dst, const SrcXprType &src)
template<typename DstXprType , typename SrcXprType >
EIGEN_STRONG_INLINE DstXprType & copy_using_evaluator (const PlainObjectBase< DstXprType > &dst, const SrcXprType &src)
template<typename DstXprType , typename SrcXprType >
void add_assign_using_evaluator (const DstXprType &dst, const SrcXprType &src)
template<typename DstXprType , typename SrcXprType >
void subtract_assign_using_evaluator (const DstXprType &dst, const SrcXprType &src)
template<typename DstXprType , typename SrcXprType >
void multiply_assign_using_evaluator (const DstXprType &dst, const SrcXprType &src)
template<typename DstXprType , typename SrcXprType >
void divide_assign_using_evaluator (const DstXprType &dst, const SrcXprType &src)
template<typename DstXprType , typename SrcXprType >
void swap_using_evaluator (const DstXprType &dst, const SrcXprType &src)
template<typename T >
NumTraits< T >::Real test_precision ()
template<>
float test_precision< float > ()
template<>
double test_precision< double > ()
template<>
long double test_precision< long double > ()
template<>
float test_precision< std::complex< float > > ()
template<>
double test_precision< std::complex< double > > ()
template<>
long double test_precision< std::complex< long double > > ()
bool test_isApprox (const short &a, const short &b)
bool test_isApprox (const unsigned short &a, const unsigned short &b)
bool test_isApprox (const unsigned int &a, const unsigned int &b)
bool test_isApprox (const long &a, const long &b)
bool test_isApprox (const unsigned long &a, const unsigned long &b)
bool test_isApprox (const int &a, const int &b)
bool test_isMuchSmallerThan (const int &a, const int &b)
bool test_isApproxOrLessThan (const int &a, const int &b)
bool test_isApprox (const float &a, const float &b)
bool test_isMuchSmallerThan (const float &a, const float &b)
bool test_isApproxOrLessThan (const float &a, const float &b)
bool test_isApprox (const double &a, const double &b)
bool test_isMuchSmallerThan (const double &a, const double &b)
bool test_isApproxOrLessThan (const double &a, const double &b)
bool test_isApprox (const std::complex< float > &a, const std::complex< float > &b)
bool test_isMuchSmallerThan (const std::complex< float > &a, const std::complex< float > &b)
bool test_isApprox (const std::complex< double > &a, const std::complex< double > &b)
bool test_isMuchSmallerThan (const std::complex< double > &a, const std::complex< double > &b)
bool test_isApprox (const std::complex< long double > &a, const std::complex< long double > &b)
bool test_isMuchSmallerThan (const std::complex< long double > &a, const std::complex< long double > &b)
bool test_isApprox (const long double &a, const long double &b)
bool test_isMuchSmallerThan (const long double &a, const long double &b)
bool test_isApproxOrLessThan (const long double &a, const long double &b)
bool test_isApprox (const half &a, const half &b)
bool test_isMuchSmallerThan (const half &a, const half &b)
bool test_isApproxOrLessThan (const half &a, const half &b)
template<typename T1 , typename T2 >
NumTraits< typename T1::RealScalar >::NonInteger test_relative_error (const EigenBase< T1 > &a, const EigenBase< T2 > &b)
template<typename T1 , typename T2 >
T1::RealScalar test_relative_error (const T1 &a, const T2 &b, const typename T1::Coefficients *=0)
template<typename T1 , typename T2 >
T1::Scalar test_relative_error (const T1 &a, const T2 &b, const typename T1::MatrixType *=0)
template<typename S , int D>
S test_relative_error (const Translation< S, D > &a, const Translation< S, D > &b)
template<typename S , int D, int O>
S test_relative_error (const ParametrizedLine< S, D, O > &a, const ParametrizedLine< S, D, O > &b)
template<typename S , int D>
S test_relative_error (const AlignedBox< S, D > &a, const AlignedBox< S, D > &b)
template<typename T1 , typename T2 >
T1::RealScalar test_relative_error (const MatrixBase< T1 > &a, const SparseMatrixBase< T2 > &b)
template<typename T1 , typename T2 >
T1::RealScalar test_relative_error (const SparseMatrixBase< T1 > &a, const MatrixBase< T2 > &b)
template<typename T1 , typename T2 >
T1::RealScalar test_relative_error (const SparseMatrixBase< T1 > &a, const SparseMatrixBase< T2 > &b)
template<typename T1 , typename T2 >
NumTraits< typename NumTraits< T1 >::Real >::NonInteger test_relative_error (const T1 &a, const T2 &b, typename internal::enable_if< internal::is_arithmetic< typename NumTraits< T1 >::Real >::value, T1 >::type *=0)
template<typename T >
T test_relative_error (const Rotation2D< T > &a, const Rotation2D< T > &b)
template<typename T >
T test_relative_error (const AngleAxis< T > &a, const AngleAxis< T > &b)
template<typename Type1 , typename Type2 >
bool test_isApprox (const Type1 &a, const Type2 &b, typename Type1::Scalar *=0)
template<typename T >
NumTraits< typename T::Scalar >::Real get_test_precision (const T &, const typename T::Scalar *=0)
template<typename T >
NumTraits< T >::Real get_test_precision (const T &, typename internal::enable_if< internal::is_arithmetic< typename NumTraits< T >::Real >::value, T >::type *=0)
template<typename Type1 , typename Type2 >
bool verifyIsApprox (const Type1 &a, const Type2 &b)
template<typename Scalar , typename ScalarRef >
bool test_isApproxWithRef (const Scalar &a, const Scalar &b, const ScalarRef &ref)
template<typename Derived1 , typename Derived2 >
bool test_isMuchSmallerThan (const MatrixBase< Derived1 > &m1, const MatrixBase< Derived2 > &m2)
template<typename Derived >
bool test_isMuchSmallerThan (const MatrixBase< Derived > &m, const typename NumTraits< typename internal::traits< Derived >::Scalar >::Real &s)
template<typename Derived >
bool test_isUnitary (const MatrixBase< Derived > &m)
template<typename T , typename U >
bool test_is_equal (const T &actual, const U &expected, bool expect_equal=true)
template<typename MatrixType >
void createRandomPIMatrixOfRank (Index desired_rank, Index rows, Index cols, MatrixType &m)
template<typename PermutationVectorType >
void randomPermutationVector (PermutationVectorType &v, Index size)
template<typename T >
bool isNotNaN (const T &x)
template<typename T >
bool isPlusInf (const T &x)
template<typename T >
bool isMinusInf (const T &x)
Box2d bounding_box (const Vector2d &v)
template<typename Dims1 , typename Dims2 >
EIGEN_DEVICE_FUNC bool dimensions_match (Dims1 &dims1, Dims2 &dims2)
template<typename ADerived , typename BDerived , typename XDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseTernaryOp< internal::scalar_betainc_op< typename XDerived::Scalar >, const ADerived, const BDerived, const XDerived > betainc (const ADerived &a, const BDerived &b, const XDerived &x)
template<typename T >
std::ostream & operator<< (std::ostream &os, const TensorBase< T, ReadOnlyAccessors > &expr)
template<typename T1 , typename T2 >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const T1 & choose (Cond< true >, const T1 &first, const T2 &)
template<typename T1 , typename T2 >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const T2 & choose (Cond< false >, const T1 &, const T2 &second)
template<typename T , typename X , typename Y >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE T divup (const X x, const Y y)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE T divup (const T x, const T y)
template<typename U , typename V >
EIGEN_CONSTEXPR EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool operator== (const Tuple< U, V > &x, const Tuple< U, V > &y)
template<typename U , typename V >
EIGEN_CONSTEXPR EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool operator!= (const Tuple< U, V > &x, const Tuple< U, V > &y)
template<class T , std::size_t N>
EIGEN_DEVICE_FUNC bool operator== (const array< T, N > &lhs, const array< T, N > &rhs)
template<typename NewDerType >
AutoDiffScalar< NewDerType > MakeAutoDiffScalar (const typename NewDerType::Scalar &value, const NewDerType &der)
template<typename DerType >
const AutoDiffScalar< DerType > & conj (const AutoDiffScalar< DerType > &x)
template<typename DerType >
const AutoDiffScalar< DerType > & real (const AutoDiffScalar< DerType > &x)
template<typename DerType >
DerType::Scalar imag (const AutoDiffScalar< DerType > &)
return (x<=y ? ADS(x) :ADS(y))
return (x >=y ? ADS(x) :ADS(y))
return (x< y ? ADS(x) :ADS(y))
return (x > y ? ADS(x) :ADS(y))
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (abs, using std::abs;return Eigen::MakeAutoDiffScalar(abs(x.value()), x.derivatives() *(x.value()< 0 ? -1 :1));) EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(abs2
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (sqrt, using std::sqrt;Scalar sqrtx=sqrt(x.value());return Eigen::MakeAutoDiffScalar(sqrtx, x.derivatives() *(Scalar(0.5)/sqrtx));) EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(cos
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (sin, using std::sin;using std::cos;return Eigen::MakeAutoDiffScalar(sin(x.value()), x.derivatives() *cos(x.value()));) EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(exp
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (log, using std::log;return Eigen::MakeAutoDiffScalar(log(x.value()), x.derivatives() *(Scalar(1)/x.value()));) template< typename DerType > inline const Eigen
template<typename DerTypeA , typename DerTypeB >
const AutoDiffScalar< Matrix< typename internal::traits< typename internal::remove_all< DerTypeA >::type >::Scalar, Dynamic, 1 > > atan2 (const AutoDiffScalar< DerTypeA > &a, const AutoDiffScalar< DerTypeB > &b)
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (tan, using std::tan;using std::cos;return Eigen::MakeAutoDiffScalar(tan(x.value()), x.derivatives() *(Scalar(1)/numext::abs2(cos(x.value()))));) EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(asin
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (acos, using std::sqrt;using std::acos;return Eigen::MakeAutoDiffScalar(acos(x.value()), x.derivatives() *(Scalar(-1)/sqrt(1-numext::abs2(x.value()))));) EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(tanh
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (sinh, using std::sinh;using std::cosh;return Eigen::MakeAutoDiffScalar(sinh(x.value()), x.derivatives() *cosh(x.value()));) EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(cosh
template<typename BVH , typename Intersector >
void BVIntersect (const BVH &tree, Intersector &intersector)
template<typename BVH1 , typename BVH2 , typename Intersector >
void BVIntersect (const BVH1 &tree1, const BVH2 &tree2, Intersector &intersector)
template<typename BVH , typename Minimizer >
Minimizer::Scalar BVMinimize (const BVH &tree, Minimizer &minimizer)
template<typename BVH1 , typename BVH2 , typename Minimizer >
Minimizer::Scalar BVMinimize (const BVH1 &tree1, const BVH2 &tree2, Minimizer &minimizer)
void ssaupd_ (int *ido, char *bmat, int *n, char *which, int *nev, float *tol, float *resid, int *ncv, float *v, int *ldv, int *iparam, int *ipntr, float *workd, float *workl, int *lworkl, int *info)
void sseupd_ (int *rvec, char *All, int *select, float *d, float *z, int *ldz, float *sigma, char *bmat, int *n, char *which, int *nev, float *tol, float *resid, int *ncv, float *v, int *ldv, int *iparam, int *ipntr, float *workd, float *workl, int *lworkl, int *ierr)
void dsaupd_ (int *ido, char *bmat, int *n, char *which, int *nev, double *tol, double *resid, int *ncv, double *v, int *ldv, int *iparam, int *ipntr, double *workd, double *workl, int *lworkl, int *info)
void dseupd_ (int *rvec, char *All, int *select, double *d, double *z, int *ldz, double *sigma, char *bmat, int *n, char *which, int *nev, double *tol, double *resid, int *ncv, double *v, int *ldv, int *iparam, int *ipntr, double *workd, double *workl, int *lworkl, int *ierr)
template<typename A , typename B >
KroneckerProduct< A, B > kroneckerProduct (const MatrixBase< A > &a, const MatrixBase< B > &b)
template<typename A , typename B >
KroneckerProductSparse< A, B > kroneckerProduct (const EigenBase< A > &a, const EigenBase< B > &b)
template<typename MatrixType , typename ResultType >
void matrix_sqrt_quasi_triangular (const MatrixType &arg, ResultType &result)
Compute matrix square root of quasi-triangular matrix.
template<typename MatrixType , typename ResultType >
void matrix_sqrt_triangular (const MatrixType &arg, ResultType &result)
Compute matrix square root of triangular matrix.
template<typename Polynomials , typename T >
T poly_eval_horner (const Polynomials &poly, const T &x)
template<typename Polynomials , typename T >
T poly_eval (const Polynomials &poly, const T &x)
template<typename Polynomial >
NumTraits< typename Polynomial::Scalar >::Real cauchy_max_bound (const Polynomial &poly)
template<typename Polynomial >
NumTraits< typename Polynomial::Scalar >::Real cauchy_min_bound (const Polynomial &poly)
template<typename RootVector , typename Polynomial >
void roots_to_monicPolynomial (const RootVector &rv, Polynomial &poly)
bool getMarketHeader (const std::string &filename, int &sym, bool &iscomplex, bool &isvector)
template<typename SparseMatrixType >
bool loadMarket (SparseMatrixType &mat, const std::string &filename)
template<typename VectorType >
bool loadMarketVector (VectorType &vec, const std::string &filename)
template<typename SparseMatrixType >
bool saveMarket (const SparseMatrixType &mat, const std::string &filename, int sym=0)
template<typename VectorType >
bool saveMarketVector (const VectorType &vec, const std::string &filename)
template<typename Derived , typename ExponentDerived >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_igamma_op< typename Derived::Scalar >, const Derived, const ExponentDerived > igamma (const Eigen::ArrayBase< Derived > &a, const Eigen::ArrayBase< ExponentDerived > &x)
template<typename Derived , typename ExponentDerived >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_igammac_op< typename Derived::Scalar >, const Derived, const ExponentDerived > igammac (const Eigen::ArrayBase< Derived > &a, const Eigen::ArrayBase< ExponentDerived > &x)
template<typename DerivedN , typename DerivedX >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_polygamma_op< typename DerivedX::Scalar >, const DerivedN, const DerivedX > polygamma (const Eigen::ArrayBase< DerivedN > &n, const Eigen::ArrayBase< DerivedX > &x)
template<typename ArgADerived , typename ArgBDerived , typename ArgXDerived >
const Eigen::CwiseTernaryOp< Eigen::internal::scalar_betainc_op< typename ArgXDerived::Scalar >, const ArgADerived, const ArgBDerived, const ArgXDerived > betainc (const Eigen::ArrayBase< ArgADerived > &a, const Eigen::ArrayBase< ArgBDerived > &b, const Eigen::ArrayBase< ArgXDerived > &x)
template<typename DerivedX , typename DerivedQ >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_zeta_op< typename DerivedX::Scalar >, const DerivedX, const DerivedQ > zeta (const Eigen::ArrayBase< DerivedX > &x, const Eigen::ArrayBase< DerivedQ > &q)
template<typename SplineType , typename DerivativeType >
void derivativesImpl (const SplineType &spline, typename SplineType::Scalar u, DenseIndex order, DerivativeType &der)
template<typename KnotVectorType >
void KnotAveraging (const KnotVectorType &parameters, DenseIndex degree, KnotVectorType &knots)
Computes knot averages.The knots are computed as
\begin{align*} u_0 & = \hdots = u_p = 0 \\ u_{m-p} & = \hdots = u_{m} = 1 \\ u_{j+p} & = \frac{1}{p}\sum_{i=j}^{j+p-1}\bar{u}_i \quad\quad j=1,\hdots,n-p \end{align*}
where \(p\) is the degree and \(m+1\) the number knots of the desired interpolating spline.
template<typename KnotVectorType , typename ParameterVectorType , typename IndexArray >
void KnotAveragingWithDerivatives (const ParameterVectorType &parameters, const unsigned int degree, const IndexArray &derivativeIndices, KnotVectorType &knots)
Computes knot averages when derivative constraints are present. Note that this is a technical interpretation of the referenced article since the algorithm contained therein is incorrect as written.
template<typename PointArrayType , typename KnotVectorType >
void ChordLengths (const PointArrayType &pts, KnotVectorType &chord_lengths)
Computes chord length parameters which are required for spline interpolation.
template<typename T , typename Derived >
T test_relative_error (const AlignedVector3< T > &a, const MatrixBase< Derived > &b)
template<typename Scalar , int Dim>
AlignedBox< Scalar, Dim > bounding_box (const Matrix< Scalar, Dim, 1 > &v)
Variables
const int Dynamic = -1
const int DynamicIndex = 0xffffff
const int Infinity = -1
const int HugeCost = 10000
const unsigned int RowMajorBit = 0x1
const unsigned int EvalBeforeNestingBit = 0x2
EIGEN_DEPRECATED const unsigned int EvalBeforeAssigningBit = 0x4
const unsigned int PacketAccessBit = 0x8
const unsigned int ActualPacketAccessBit = 0x0
const unsigned int LinearAccessBit = 0x10
const unsigned int LvalueBit = 0x20
const unsigned int DirectAccessBit = 0x40
EIGEN_DEPRECATED const unsigned int AlignedBit = 0x80
const unsigned int NestByRefBit = 0x100
const unsigned int NoPreferredStorageOrderBit = 0x200
const unsigned int CompressedAccessBit = 0x400
const unsigned int HereditaryBits
const int CoherentAccessPattern = 0x1
const int InnerRandomAccessPattern = 0x2 | CoherentAccessPattern
const int OuterRandomAccessPattern = 0x4 | CoherentAccessPattern
const int RandomAccessPattern = 0x8 | OuterRandomAccessPattern | InnerRandomAccessPattern
const T & y
Scalar expx = exp(x.value())
const unsigned int SkylineBit = 0x1200
Detailed Description
Namespace containing all symbols from the Eigen library.
Typedef Documentation
BlasIndex
typedef int Eigen::BlasIndex
Definition at line 119 of file MKL_support.h.
dcomplex
typedef std::complex<double> Eigen::dcomplex
Definition at line 113 of file MKL_support.h.
DenseIndex
typedef EIGEN_DEFAULT_DENSE_INDEX_TYPE Eigen::DenseIndex
Definition at line 25 of file Meta.h.
Index
typedef EIGEN_DEFAULT_DENSE_INDEX_TYPE Eigen::Index
The Index type as used for the API.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
Preprocessor directives, StorageIndex.
Examples:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Definition at line 33 of file Meta.h.
NonBlockingThreadPool
typedef NonBlockingThreadPoolTempl<StlThreadEnvironment> Eigen::NonBlockingThreadPool
Definition at line 270 of file NonBlockingThreadPool.h.
scomplex
typedef std::complex<float> Eigen::scomplex
Definition at line 114 of file MKL_support.h.
SimpleThreadPool
typedef SimpleThreadPoolTempl<StlThreadEnvironment> Eigen::SimpleThreadPool
Definition at line 150 of file SimpleThreadPool.h.
Spline2d
typedef Spline<double,2> Eigen::Spline2d
2D double B-spline with dynamic degree.
Definition at line 87 of file SplineFwd.h.
Spline2f
typedef Spline<float,2> Eigen::Spline2f
2D float B-spline with dynamic degree.
Definition at line 81 of file SplineFwd.h.
Spline3d
typedef Spline<double,3> Eigen::Spline3d
3D double B-spline with dynamic degree.
Definition at line 90 of file SplineFwd.h.
Spline3f
typedef Spline<float,3> Eigen::Spline3f
3D float B-spline with dynamic degree.
Definition at line 84 of file SplineFwd.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CPU_TIMER
REAL_TIMER
Definition at line 43 of file BenchTimer.h.
anonymous enum
anonymous enum
Enumerator
Large
Small
Definition at line 16 of file GeneralProduct.h.
anonymous enum
anonymous enum
Enumerator
DontAlignCols
Definition at line 16 of file IO.h.
anonymous enum
anonymous enum
Enumerator
StreamPrecision
FullPrecision
Definition at line 17 of file IO.h.
anonymous enum
anonymous enum
Enumerator
StandardCompressedFormat
used by Ref<SparseMatrix> to specify whether the input storage must be in standard compressed form
Definition at line 15 of file SparseRef.h.
anonymous enum
anonymous enum
Enumerator
NegationFlag
ConjugationFlag
Definition at line 15 of file Symmetry.h.
anonymous enum
anonymous enum
Enumerator
GlobalRealFlag
GlobalImagFlag
GlobalZeroFlag
Definition at line 20 of file Symmetry.h.
anonymous enum
anonymous enum
Enumerator
IsSkyline
Definition at line 24 of file SkylineUtil.h.
anonymous enum
anonymous enum
Enumerator
SPD
NonSymmetric
Definition at line 16 of file MatrixMarketIterator.h.
Action
enum Eigen::Action
Enumerator
GetAction
SetAction
Definition at line 488 of file Constants.h.
AdditionalProductEvaluationMode
enum Eigen::AdditionalProductEvaluationMode
Enumerator
SkylineTimeDenseProduct
SkylineTimeSkylineProduct
DenseTimeSkylineProduct
Definition at line 23 of file SkylineUtil.h.
AmbiVectorMode
enum Eigen::AmbiVectorMode
Enumerator
IsDense
IsSparse
Definition at line 356 of file Constants.h.
CholmodMode
enum Eigen::CholmodMode
Enumerator
CholmodAuto
CholmodSimplicialLLt
CholmodSupernodalLLt
CholmodLDLt
Definition at line 162 of file CholmodSupport.h.
Default_t
enum Eigen::Default_t
Enumerator
Default
Definition at line 352 of file Constants.h.
EulerAxis
enum Eigen::EulerAxis
Representation of a fixed signed rotation axis for EulerSystem.
Values here represent:
The axis of the rotation: X, Y or Z.
The sign (i.e. direction of the rotation along the axis): positive(+) or negative(-)
Therefore, this could express all the axes {+X,+Y,+Z,-X,-Y,-Z}
For positive axis, use +EULER_{axis}, and for negative axis use -EULER_{axis}.
Enumerator
EULER_X
the X axis
EULER_Y
the Y axis
EULER_Z
the Z axis
Definition at line 55 of file EulerSystem.h.
FFTDirection
enum Eigen::FFTDirection
Enumerator
FFT_FORWARD
FFT_REVERSE
Definition at line 82 of file TensorForwardDeclarations.h.
FFTResultType
enum Eigen::FFTResultType
Enumerator
RealPart
ImagPart
BothParts
Definition at line 76 of file TensorForwardDeclarations.h.
NoChange_t
enum Eigen::NoChange_t
Enumerator
NoChange
Definition at line 350 of file Constants.h.
NumericalDiffMode
enum Eigen::NumericalDiffMode
Enumerator
Forward
Central
Definition at line 18 of file NumericalDiff.h.
PaddingType
enum Eigen::PaddingType
Enumerator
PADDING_VALID
PADDING_SAME
Definition at line 265 of file TensorTraits.h.
ProductImplType
enum Eigen::ProductImplType
Enumerator
DefaultProduct
LazyProduct
AliasFreeProduct
CoeffBasedProductMode
LazyCoeffBasedProductMode
OuterProduct
InnerProduct
GemvProduct
GemmProduct
Definition at line 483 of file Constants.h.
Sequential_t
enum Eigen::Sequential_t
Enumerator
Sequential
Definition at line 351 of file Constants.h.
SimplicialCholeskyMode
enum Eigen::SimplicialCholeskyMode
Enumerator
SimplicialCholeskyLLT
SimplicialCholeskyLDLT
Definition at line 15 of file SimplicialCholesky.h.
SpecializedType
enum Eigen::SpecializedType
Enumerator
Specialized
BuiltIn
Definition at line 310 of file Constants.h.
TraversalType
enum Eigen::TraversalType
Enumerator
DefaultTraversal
LinearTraversal
InnerVectorizedTraversal
LinearVectorizedTraversal
SliceVectorizedTraversal
InvalidTraversal
AllAtOnceTraversal
Definition at line 276 of file Constants.h.
UnrollingType
enum Eigen::UnrollingType
Enumerator
NoUnrolling
InnerUnrolling
CompleteUnrolling
Definition at line 298 of file Constants.h.
Function Documentation
add_assign_using_evaluator()
template<typename DstXprType , typename SrcXprType > void Eigen::add_assign_using_evaluator (const DstXprType & dst, const SrcXprType & src)
Definition at line 53 of file evaluators.cpp.
References Eigen::internal::call_assignment().
Referenced by test_evaluators().
atan2()
template<typename DerTypeA , typename DerTypeB > const AutoDiffScalar<Matrix<typename internal::traits<typename internal::remove_all<DerTypeA>::type>::Scalar,Dynamic,1> > Eigen::atan2 (const AutoDiffScalar< DerTypeA > & a, const AutoDiffScalar< DerTypeB > & b) inline
Definition at line 622 of file AutoDiffScalar.h.
References abs2(), acos(), asin(), cos(), cosh(), Eigen::AutoDiffScalar< _DerType >::derivatives(), EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY(), MakeAutoDiffScalar(), ret, sinh(), sqrt(), tan(), tanh(), and Eigen::AutoDiffScalar< _DerType >::value().
Referenced by Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::angularDistance(), array_complex(), check_atan2(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::eulerAngles(), Eigen::Rotation2D< _Scalar >::fromRotationMatrix(), EulerAngles< _Scalar >::operator=(), and Eigen::AngleAxis< _Scalar >::operator=().
betainc() [1/2]
template<typename ADerived , typename BDerived , typename XDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseTernaryOp<internal::scalar_betainc_op<typename XDerived::Scalar>, const ADerived, const BDerived, const XDerived> Eigen::betainc (const ADerived & a, const BDerived & b, const XDerived & x)
Returns
an expression of the coefficient-wise betainc(x, a, b) to the given tensors.
This function computes the regularized incomplete beta function (integral).
Definition at line 24 of file TensorGlobalFunctions.h.
References a, b, and x.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_betainc_op< Scalar >::operator()(), and Eigen::internal::pbetainc().
betainc() [2/2]
template<typename ArgADerived , typename ArgBDerived , typename ArgXDerived > const Eigen::CwiseTernaryOp<Eigen::internal::scalar_betainc_op<typename ArgXDerived::Scalar>, const ArgADerived, const ArgBDerived, const ArgXDerived> Eigen::betainc (const Eigen::ArrayBase< ArgADerived > & a, const Eigen::ArrayBase< ArgBDerived > & b, const Eigen::ArrayBase< ArgXDerived > & x) inline
Returns
an expression of the coefficient-wise betainc(x, a, b) to the given arrays.
This function computes the regularized incomplete beta function (integral).
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of betainc(T,T,T) for any scalar type T to be supported.
See also
Eigen::betainc(), Eigen::lgamma()
Definition at line 90 of file SpecialFunctionsArrayAPI.h.
bounding_box() [1/2]
Box2d Eigen::bounding_box (const Vector2d & v)
Definition at line 9 of file BVH_Example.cpp.
Referenced by Eigen::internal::get_boxes_helper< ObjectList, VolumeList, int >::operator()().
bounding_box() [2/2]
template<typename Scalar , int Dim> AlignedBox<Scalar, Dim> Eigen::bounding_box (const Matrix< Scalar, Dim, 1 > & v)
Definition at line 17 of file BVH.cpp.
References v.
BVIntersect() [1/2]
template<typename BVH , typename Intersector > void Eigen::BVIntersect (const BVH & tree, Intersector & intersector)
Given a BVH, runs the query encapsulated by intersector. The Intersector type must provide the following members:
bool intersectVolume(const BVH::Volume &volume) //returns true if volume intersects the query
bool intersectObject(const BVH::Object &object) //returns true if the search should terminate immediately
Definition at line 79 of file BVAlgorithms.h.
References Eigen::internal::intersect_helper().
Referenced by TreeTest< Dim >::testIntersect1(), and TreeTest< Dim >::testIntersect2().
BVIntersect() [2/2]
template<typename BVH1 , typename BVH2 , typename Intersector > void Eigen::BVIntersect (const BVH1 & tree1, const BVH2 & tree2, Intersector & intersector)
Given two BVH's, runs the query on their Cartesian product encapsulated by intersector. The Intersector type must provide the following members:
bool intersectVolumeVolume(const BVH1::Volume &v1, const BVH2::Volume &v2) //returns true if product of volumes intersects the query
bool intersectVolumeObject(const BVH1::Volume &v1, const BVH2::Object &o2) //returns true if the volume-object product intersects the query
bool intersectObjectVolume(const BVH1::Object &o1, const BVH2::Volume &v2) //returns true if the volume-object product intersects the query
bool intersectObjectObject(const BVH1::Object &o1, const BVH2::Object &o2) //returns true if the search should terminate immediately
Definition at line 93 of file BVAlgorithms.h.
References Eigen::internal::intersect_helper().
BVMinimize() [1/2]
template<typename BVH , typename Minimizer > Minimizer::Scalar Eigen::BVMinimize (const BVH & tree, Minimizer & minimizer)
Given a BVH, runs the query encapsulated by minimizer.
Returns
the minimum value. The Minimizer type must provide the following members:
typedef Scalar //the numeric type of what is being minimized--not necessarily the Scalar type of the BVH (if it has one)
Scalar minimumOnVolume(const BVH::Volume &volume)
Scalar minimumOnObject(const BVH::Object &object)
Definition at line 219 of file BVAlgorithms.h.
References max, and Eigen::internal::minimize_helper().
Referenced by main(), TreeTest< Dim >::testMinimize1(), and TreeTest< Dim >::testMinimize2().
BVMinimize() [2/2]
template<typename BVH1 , typename BVH2 , typename Minimizer > Minimizer::Scalar Eigen::BVMinimize (const BVH1 & tree1, const BVH2 & tree2, Minimizer & minimizer)
Given two BVH's, runs the query on their cartesian product encapsulated by minimizer.
Returns
the minimum value. The Minimizer type must provide the following members:
typedef Scalar //the numeric type of what is being minimized--not necessarily the Scalar type of the BVH (if it has one)
Scalar minimumOnVolumeVolume(const BVH1::Volume &v1, const BVH2::Volume &v2)
Scalar minimumOnVolumeObject(const BVH1::Volume &v1, const BVH2::Object &o2)
Scalar minimumOnObjectVolume(const BVH1::Object &o1, const BVH2::Volume &v2)
Scalar minimumOnObjectObject(const BVH1::Object &o1, const BVH2::Object &o2)
Definition at line 235 of file BVAlgorithms.h.
References max, min, and Eigen::internal::minimize_helper().
cauchy_max_bound()
template<typename Polynomial > NumTraits<typename Polynomial::Scalar>::Real Eigen::cauchy_max_bound (const Polynomial & poly) inline
Returns
a maximum bound for the absolute value of any root of the polynomial.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. \(1 + 3x^2 \) is stored as a vector \([ 1, 0, 3 ] \).
Precondition: the leading coefficient of the input polynomial poly must be non zero
Definition at line 75 of file PolynomialUtils.h.
References abs(), eigen_assert, and i.
Referenced by CauchyBounds().
cauchy_min_bound()
template<typename Polynomial > NumTraits<typename Polynomial::Scalar>::Real Eigen::cauchy_min_bound (const Polynomial & poly) inline
Returns
a minimum bound for the absolute value of any non zero root of the polynomial.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. \(1 + 3x^2 \) is stored as a vector \([ 1, 0, 3 ] \).
Definition at line 98 of file PolynomialUtils.h.
References abs(), i, and j.
Referenced by CauchyBounds().
choose() [1/2]
template<typename T1 , typename T2 > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const T1& Eigen::choose (Cond< true > , const T1 & first, const T2 &)
Definition at line 18 of file TensorMeta.h.
References EIGEN_ALWAYS_INLINE.
choose() [2/2]
template<typename T1 , typename T2 > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const T2& Eigen::choose (Cond< false > , const T1 & , const T2 & second)
Definition at line 23 of file TensorMeta.h.
References EIGEN_ALWAYS_INLINE, and second().
conj()
template<typename DerType > const AutoDiffScalar<DerType>& Eigen::conj (const AutoDiffScalar< DerType > & x) inline
Definition at line 542 of file AutoDiffScalar.h.
References x.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::extractScalarFactor(), Eigen::internal::kissfft_impl< _Scalar >::fwd(), Eigen::internal::kissfft_impl< _Scalar >::inv(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::makeHouseholder(), Eigen::internal::scalar_conjugate_op< Scalar >::operator()(), Eigen::JacobiRotation< Scalar >::operator*(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::JacobiRotation< Scalar >::transpose(), and Eigen::internal::tridiagonalization_inplace().
copy_using_evaluator() [1/3]
template<typename DstXprType , typename SrcXprType > EIGEN_STRONG_INLINE DstXprType& Eigen::copy_using_evaluator (const EigenBase< DstXprType > & dst, const SrcXprType & src)
Definition at line 22 of file evaluators.cpp.
References Eigen::internal::call_assignment(), Eigen::EigenBase< Derived >::const_cast_derived(), and EIGEN_STRONG_INLINE.
Referenced by test_evaluators().
copy_using_evaluator() [2/3]
template<typename DstXprType , template< typename > class StorageBase, typename SrcXprType > EIGEN_STRONG_INLINE const DstXprType& Eigen::copy_using_evaluator (const NoAlias< DstXprType, StorageBase > & dst, const SrcXprType & src)
Definition at line 30 of file evaluators.cpp.
References Eigen::internal::call_assignment(), EIGEN_STRONG_INLINE, and Eigen::NoAlias< ExpressionType, StorageBase >::expression().
copy_using_evaluator() [3/3]
template<typename DstXprType , typename SrcXprType > EIGEN_STRONG_INLINE DstXprType& Eigen::copy_using_evaluator (const PlainObjectBase< DstXprType > & dst, const SrcXprType & src)
Definition at line 38 of file evaluators.cpp.
References Eigen::internal::call_assignment(), Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, Eigen::PlainObjectBase< Derived >::resizeLike(), and Eigen::PlainObjectBase< Derived >::rows().
createRandomPIMatrixOfRank()
template<typename MatrixType > void Eigen::createRandomPIMatrixOfRank (Index desired_rank, Index rows, Index cols, MatrixType & m)
Creates a random Partial Isometry matrix of given rank.
A partial isometry is a matrix all of whose singular values are either 0 or 1. This is very useful to test rank-revealing algorithms.
Definition at line 557 of file main.h.
References a, b, Eigen::HouseholderQR< _MatrixType >::householderQ(), min, randomPermutationVector(), Eigen::PlainObjectBase< Derived >::setZero(), size, and v.
Referenced by cod(), cod_fixedsize(), inverse(), lu_non_invertible(), qr(), qr_fixedsize(), svd_fill_random(), and test_is_equal().
derivativesImpl()
template<typename SplineType , typename DerivativeType > void Eigen::derivativesImpl (const SplineType & spline, typename SplineType::Scalar u, DenseIndex order, DerivativeType & der)
Definition at line 313 of file Spline.h.
References Eigen::Spline< _Scalar, _Dim, _Degree >::Dimension, min, n, p, and Eigen::Spline< _Scalar, _Dim, _Degree >::span().
Referenced by Eigen::Spline< _Scalar, _Dim, _Degree >::derivatives().
dimensions_match()
template<typename Dims1 , typename Dims2 > EIGEN_DEVICE_FUNC bool Eigen::dimensions_match (Dims1 & dims1, Dims2 & dims2)
Definition at line 422 of file TensorDimensions.h.
References Eigen::TensorSycl::run().
Referenced by Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::TensorEvaluator(), and Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TensorEvaluator().
divide_assign_using_evaluator()
template<typename DstXprType , typename SrcXprType > void Eigen::divide_assign_using_evaluator (const DstXprType & dst, const SrcXprType & src)
Definition at line 74 of file evaluators.cpp.
References Eigen::internal::call_assignment().
Referenced by test_evaluators().
divup() [1/2]
template<typename T , typename X , typename Y > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE T Eigen::divup (const X x, const Y y)
Definition at line 30 of file TensorMeta.h.
References EIGEN_ALWAYS_INLINE.
divup() [2/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE T Eigen::divup (const T x, const T y)
Definition at line 36 of file TensorMeta.h.
dsaupd_()
void Eigen::dsaupd_ (int * ido, char * bmat, int * n, char * which, int * nev, double * tol, double * resid, int * ncv, double * v, int * ldv, int * iparam, int * ipntr, double * workd, double * workl, int * lworkl, int * info)
Referenced by Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), and Eigen::internal::arpack_wrapper< double, double >::saupd().
dseupd_()
void Eigen::dseupd_ (int * rvec, char * All, int * select, double * d, double * z, int * ldz, double * sigma, char * bmat, int * n, char * which, int * nev, double * tol, double * resid, int * ncv, double * v, int * ldv, int * iparam, int * ipntr, double * workd, double * workl, int * lworkl, int * ierr)
Referenced by Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), and Eigen::internal::arpack_wrapper< double, double >::seupd().
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [1/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (abs , using std::abs;return Eigen::MakeAutoDiffScalar(abs(x.value()), x.derivatives() *(x.value()< 0 ? -1 :1));)
Referenced by atan2().
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [2/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (sqrt , using std::sqrt;Scalar sqrtx = sqrt(x.value()); return Eigen::MakeAutoDiffScalar(sqrtx,x.derivatives() * (Scalar(0.5) / sqrtx));)
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [3/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (sin , using std::sin;using std::cos;return Eigen::MakeAutoDiffScalar(sin(x.value()), x.derivatives() *cos(x.value()));)
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [4/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (log , using std::log;return Eigen::MakeAutoDiffScalar(log(x.value()), x.derivatives() *(Scalar(1)/x.value()));) const
Definition at line 605 of file AutoDiffScalar.h.
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [5/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (tan , using std::tan;using std::cos;return Eigen::MakeAutoDiffScalar(tan(x.value()), x.derivatives() *(Scalar(1)/numext::abs2(cos(x.value()))));)
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [6/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (acos , using std::sqrt;using std::acos;return Eigen::MakeAutoDiffScalar(acos(x.value()), x.derivatives() *(Scalar(-1)/sqrt(1-numext::abs2(x.value()))));)
EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY() [7/7]
Eigen::EIGEN_AUTODIFF_DECLARE_GLOBAL_UNARY (sinh , using std::sinh;using std::cosh;return Eigen::MakeAutoDiffScalar(sinh(x.value()), x.derivatives() *cosh(x.value()));)
EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE()
template<typename Derived > const Eigen::EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (Derived , typename Derived::Scalar , pow) const inline
Definition at line 113 of file GlobalFunctions.h.
References Eigen::ArrayBase< Derived >::pow().
Referenced by Eigen::UniformScaling< _Scalar >::isApprox(), and Eigen::AutoDiffScalar< _DerType >::operator/().
EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE()
template<typename Derived > const Eigen::EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE (typename Derived::Scalar , Derived , pow) const inline
Definition at line 168 of file GlobalFunctions.h.
References abs2(), EIGEN_ARRAY_DECLARE_GLOBAL_EIGEN_UNARY, imag(), and x.
Referenced by Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::pow().
get_test_precision() [1/2]
template<typename T > NumTraits<typename T::Scalar>::Real Eigen::get_test_precision (const T & , const typename T::Scalar * = 0)
Definition at line 476 of file main.h.
Referenced by verifyIsApprox().
get_test_precision() [2/2]
template<typename T > NumTraits<T>::Real Eigen::get_test_precision (const T & , typename internal::enable_if< internal::is_arithmetic< typename NumTraits< T >::Real >::value, T >::type * = 0)
Definition at line 482 of file main.h.
getMarketHeader()
bool Eigen::getMarketHeader (const std::string & filename, int & sym, bool & iscomplex, bool & isvector) inline
Definition at line 109 of file MarketIO.h.
References eigen_assert, SelfAdjoint, and Symmetric.
Referenced by Eigen::MatrixMarketIterator< Scalar >::Getnextvalidmatrix().
igamma()
template<typename Derived , typename ExponentDerived > const Eigen::CwiseBinaryOp<Eigen::internal::scalar_igamma_op<typename Derived::Scalar>, const Derived, const ExponentDerived> Eigen::igamma (const Eigen::ArrayBase< Derived > & a, const Eigen::ArrayBase< ExponentDerived > & x) inline
Returns
an expression of the coefficient-wise igamma(a, x) to the given arrays.
This function computes the coefficient-wise incomplete gamma function.
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of igammac(T,T) for any scalar type T to be supported.
See also
Eigen::igammac(), Eigen::lgamma()
Definition at line 28 of file SpecialFunctionsArrayAPI.h.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_igamma_op< Scalar >::operator()(), and Eigen::internal::pigamma().
igammac()
template<typename Derived , typename ExponentDerived > const Eigen::CwiseBinaryOp<Eigen::internal::scalar_igammac_op<typename Derived::Scalar>, const Derived, const ExponentDerived> Eigen::igammac (const Eigen::ArrayBase< Derived > & a, const Eigen::ArrayBase< ExponentDerived > & x) inline
Returns
an expression of the coefficient-wise igammac(a, x) to the given arrays.
This function computes the coefficient-wise complementary incomplete gamma function.
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of igammac(T,T) for any scalar type T to be supported.
See also
Eigen::igamma(), Eigen::lgamma()
Definition at line 48 of file SpecialFunctionsArrayAPI.h.
Referenced by array_special_functions(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_igammac_op< Scalar >::operator()(), and Eigen::internal::pigammac().
imag()
template<typename DerType > DerType::Scalar Eigen::imag (const AutoDiffScalar< DerType > &) inline
Definition at line 546 of file AutoDiffScalar.h.
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::bfly3(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly4(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly5(), EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::pcplxflip(), Eigen::internal::pmul(), Eigen::PolynomialSolverBase< _Scalar, 1 >::realRoots(), Eigen::PolynomialSolverBase< _Scalar, 1 >::selectRealRoot_withRespectToAbsRealPart(), and Eigen::PolynomialSolverBase< _Scalar, 1 >::selectRealRoot_withRespectToRealPart().
initParallel()
void Eigen::initParallel () inline
Must be call first when calling Eigen from multiple threads
Definition at line 48 of file Parallelizer.h.
References GetAction, Eigen::internal::manage_caching_sizes(), and Eigen::internal::manage_multi_threading().
Referenced by main(), Eigen::internal::parallelize_gemm(), and Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::run().
isMinusInf()
template<typename T > bool Eigen::isMinusInf (const T & x)
Definition at line 622 of file main.h.
isNotNaN()
template<typename T > bool Eigen::isNotNaN (const T & x)
Definition at line 612 of file main.h.
References x.
isPlusInf()
template<typename T > bool Eigen::isPlusInf (const T & x)
Definition at line 617 of file main.h.
Referenced by stable_norm().
kroneckerProduct() [1/2]
template<typename A , typename B > KroneckerProduct<A,B> Eigen::kroneckerProduct (const MatrixBase< A > & a, const MatrixBase< B > & b)
Computes Kronecker tensor product of two dense matrices
Warning
If you want to replace a matrix by its Kronecker product with some matrix, do NOT do this:
A = kroneckerProduct(A,B); // bug!!! caused by aliasing effect
instead, use eval() to work around this:
A = kroneckerProduct(A,B).eval();
Parameters
a Dense matrix a
b Dense matrix b
Returns
Kronecker tensor product of a and b
Definition at line 271 of file KroneckerTensorProduct.h.
kroneckerProduct() [2/2]
template<typename A , typename B > KroneckerProductSparse<A,B> Eigen::kroneckerProduct (const EigenBase< A > & a, const EigenBase< B > & b)
Computes Kronecker tensor product of two matrices, at least one of which is sparse
Warning
If you want to replace a matrix by its Kronecker product with some matrix, do NOT do this:
A = kroneckerProduct(A,B); // bug!!! caused by aliasing effect
instead, use eval() to work around this:
A = kroneckerProduct(A,B).eval();
Parameters
a Dense/sparse matrix a
b Dense/sparse matrix b
Returns
Kronecker tensor product of a and b, stored in a sparse matrix
Definition at line 298 of file KroneckerTensorProduct.h.
References Eigen::EigenBase< Derived >::derived().
l1CacheSize()
std::ptrdiff_t Eigen::l1CacheSize () inline
Returns
the currently set level 1 cpu cache size (in bytes) used to estimate the ideal blocking size parameters.
See also
setCpuCacheSize
Definition at line 2111 of file GeneralBlockPanelKernel.h.
References GetAction, and Eigen::internal::manage_caching_sizes().
Referenced by Eigen::internal::CacheSizes::CacheSizes(), and Eigen::DefaultDevice::firstLevelCacheSize().
l2CacheSize()
std::ptrdiff_t Eigen::l2CacheSize () inline
Returns
the currently set level 2 cpu cache size (in bytes) used to estimate the ideal blocking size parameters.
See also
setCpuCacheSize
Definition at line 2120 of file GeneralBlockPanelKernel.h.
References GetAction, and Eigen::internal::manage_caching_sizes().
Referenced by Eigen::internal::CacheSizes::CacheSizes().
l3CacheSize()
std::ptrdiff_t Eigen::l3CacheSize () inline
Returns
the currently set level 3 cpu cache size (in bytes) used to estimate the ideal blocking size paramete\ rs.
See also
setCpuCacheSize
Definition at line 2130 of file GeneralBlockPanelKernel.h.
References GetAction, and Eigen::internal::manage_caching_sizes().
Referenced by Eigen::internal::CacheSizes::CacheSizes(), and Eigen::DefaultDevice::lastLevelCacheSize().
lazyprod()
template<typename Lhs , typename Rhs > const Product<Lhs,Rhs,LazyProduct> Eigen::lazyprod (const Lhs & lhs, const Rhs & rhs)
Definition at line 15 of file evaluators.cpp.
References EIGEN_STRONG_INLINE.
Referenced by test_evaluators().
loadMarket()
template<typename SparseMatrixType > bool Eigen::loadMarket (SparseMatrixType & mat, const std::string & filename)
Definition at line 133 of file MarketIO.h.
Referenced by Eigen::MatrixMarketIterator< Scalar >::matrix().
loadMarketVector()
template<typename VectorType > bool Eigen::loadMarketVector (VectorType & vec, const std::string & filename)
Definition at line 193 of file MarketIO.h.
References col(), eigen_assert, Eigen::internal::GetVectorElt(), i, and n.
Referenced by Eigen::MatrixMarketIterator< Scalar >::refX(), and Eigen::MatrixMarketIterator< Scalar >::rhs().
MakeAutoDiffScalar()
template<typename NewDerType > AutoDiffScalar<NewDerType> Eigen::MakeAutoDiffScalar (const typename NewDerType::Scalar & value, const NewDerType & der) inline
Definition at line 36 of file AutoDiffScalar.h.
Referenced by atan2(), Eigen::AutoDiffScalar< _DerType >::operator*(), and Eigen::AutoDiffScalar< _DerType >::operator/().
matrix_sqrt_quasi_triangular()
template<typename MatrixType , typename ResultType > void Eigen::matrix_sqrt_quasi_triangular (const MatrixType & arg, ResultType & result)
Compute matrix square root of quasi-triangular matrix.
Template Parameters
MatrixType type of arg, the argument of matrix square root, expected to be an instantiation of the Matrix class template.
ResultType type of result, where result is to be stored.
Parameters
[in] arg argument of matrix square root.
[out] result matrix square root of upper Hessenberg part of arg.
This function computes the square root of the upper quasi-triangular matrix stored in the upper Hessenberg part of arg. Only the upper Hessenberg part of result is updated, the rest is not touched. See MatrixBase::sqrt() for details on how this computation is implemented.
See also
MatrixSquareRoot, MatrixSquareRootQuasiTriangular
Definition at line 182 of file MatrixSquareRoot.h.
References eigen_assert, Eigen::internal::matrix_sqrt_quasi_triangular_diagonal(), and Eigen::internal::matrix_sqrt_quasi_triangular_off_diagonal().
Referenced by Eigen::internal::matrix_sqrt_compute< MatrixType, 0 >::run().
matrix_sqrt_triangular()
template<typename MatrixType , typename ResultType > void Eigen::matrix_sqrt_triangular (const MatrixType & arg, ResultType & result)
Compute matrix square root of triangular matrix.
Template Parameters
MatrixType type of arg, the argument of matrix square root, expected to be an instantiation of the Matrix class template.
ResultType type of result, where result is to be stored.
Parameters
[in] arg argument of matrix square root.
[out] result matrix square root of upper triangular part of arg.
Only the upper triangular part (including the diagonal) of result is updated, the rest is not touched. See MatrixBase::sqrt() for details on how this computation is implemented.
See also
MatrixSquareRoot, MatrixSquareRootQuasiTriangular
Definition at line 206 of file MatrixSquareRoot.h.
References eigen_assert, i, IsComplex, j, and sqrt().
Referenced by Eigen::MatrixPowerAtomic< MatrixType >::compute(), Eigen::internal::matrix_log_compute_big(), and Eigen::internal::matrix_sqrt_compute< MatrixType, 1 >::run().
multiply_assign_using_evaluator()
template<typename DstXprType , typename SrcXprType > void Eigen::multiply_assign_using_evaluator (const DstXprType & dst, const SrcXprType & src)
Definition at line 67 of file evaluators.cpp.
References Eigen::internal::call_assignment().
Referenced by test_evaluators().
nbThreads()
int Eigen::nbThreads () inline
Returns
the max number of threads reserved for Eigen
See also
setNbThreads
Definition at line 58 of file Parallelizer.h.
References GetAction, Eigen::internal::manage_multi_threading(), and ret.
Referenced by Eigen::internal::parallelize_gemm(), and Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::run().
operator!=()
template<typename U , typename V > EIGEN_CONSTEXPR EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::operator!= (const Tuple< U, V > & x, const Tuple< U, V > & y)
Definition at line 148 of file TensorMeta.h.
References y.
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator!=().
operator*() [1/9]
template<typename SparseDerived , typename PermDerived > const Product<SparseDerived, PermDerived, AliasFreeProduct> Eigen::operator* (const SparseMatrixBase< SparseDerived > & matrix, const PermutationBase< PermDerived > & perm) inline
Returns
the matrix with the permutation applied to the columns
Definition at line 147 of file SparsePermutation.h.
References Eigen::EigenBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [2/9]
template<typename SparseDerived , typename PermDerived > const Product<PermDerived, SparseDerived, AliasFreeProduct> Eigen::operator* (const PermutationBase< PermDerived > & perm, const SparseMatrixBase< SparseDerived > & matrix) inline
Returns
the matrix with the permutation applied to the rows
Definition at line 154 of file SparsePermutation.h.
References AliasFreeProduct, Eigen::EigenBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [3/9]
template<typename SparseDerived , typename PermutationType > const Product<SparseDerived, Inverse<PermutationType>, AliasFreeProduct> Eigen::operator* (const SparseMatrixBase< SparseDerived > & matrix, const InverseImpl< PermutationType, PermutationStorage > & tperm) inline
Returns
the matrix with the inverse permutation applied to the columns.
Definition at line 162 of file SparsePermutation.h.
References AliasFreeProduct, Eigen::EigenBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [4/9]
template<typename SparseDerived , typename PermutationType > const Product<Inverse<PermutationType>, SparseDerived, AliasFreeProduct> Eigen::operator* (const InverseImpl< PermutationType, PermutationStorage > & tperm, const SparseMatrixBase< SparseDerived > & matrix) inline
Returns
the matrix with the inverse permutation applied to the rows.
Definition at line 171 of file SparsePermutation.h.
References AliasFreeProduct, Eigen::EigenBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [5/9]
template<typename MatrixDerived , typename TranspositionsDerived > EIGEN_DEVICE_FUNC const Product<MatrixDerived, TranspositionsDerived, AliasFreeProduct> Eigen::operator* (const MatrixBase< MatrixDerived > & matrix, const TranspositionsBase< TranspositionsDerived > & transpositions)
Returns
the matrix with the transpositions applied to the columns.
Definition at line 338 of file Transpositions.h.
References Eigen::TranspositionsBase< Derived >::derived().
operator*() [6/9]
template<typename TranspositionsDerived , typename MatrixDerived > EIGEN_DEVICE_FUNC const Product<TranspositionsDerived, MatrixDerived, AliasFreeProduct> Eigen::operator* (const TranspositionsBase< TranspositionsDerived > & transpositions, const MatrixBase< MatrixDerived > & matrix)
Returns
the matrix with the transpositions applied to the rows.
Definition at line 350 of file Transpositions.h.
References Eigen::TranspositionsBase< Derived >::derived().
operator*() [7/9]
template<typename OtherDerived , typename VectorsType , typename CoeffsType , int Side> internal::matrix_type_times_scalar_type<typename VectorsType::Scalar,OtherDerived>::Type Eigen::operator* (const MatrixBase< OtherDerived > & other, const HouseholderSequence< VectorsType, CoeffsType, Side > & h)
Computes the product of a matrix with a Householder sequence.
Parameters
[in] other Matrix being multiplied.
[in] h HouseholderSequence being multiplied.
Returns
Expression object representing the product.
This function computes \(MH \) where \(M \) is the matrix other and \(H \) is the Householder sequence represented by h.
Definition at line 438 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), cast(), and res.
operator*() [8/9]
template<typename MatrixDerived , typename PermutationDerived > EIGEN_DEVICE_FUNC const Product<MatrixDerived, PermutationDerived, AliasFreeProduct> Eigen::operator* (const MatrixBase< MatrixDerived > & matrix, const PermutationBase< PermutationDerived > & permutation)
Returns
the matrix with the permutation applied to the columns.
Definition at line 543 of file PermutationMatrix.h.
References Eigen::EigenBase< Derived >::derived().
operator*() [9/9]
template<typename PermutationDerived , typename MatrixDerived > EIGEN_DEVICE_FUNC const Product<PermutationDerived, MatrixDerived, AliasFreeProduct> Eigen::operator* (const PermutationBase< PermutationDerived > & permutation, const MatrixBase< MatrixDerived > & matrix)
Returns
the matrix with the permutation applied to the rows.
Definition at line 555 of file PermutationMatrix.h.
References Eigen::EigenBase< Derived >::derived().
operator+() [1/2]
template<typename DenseDerived , typename SparseDerived > EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_sum_op<typename DenseDerived::Scalar,typename SparseDerived::Scalar>, const DenseDerived, const SparseDerived> Eigen::operator+ (const MatrixBase< DenseDerived > & a, const SparseMatrixBase< SparseDerived > & b)
Definition at line 698 of file SparseCwiseBinaryOp.h.
References Eigen::SparseMatrixBase< Derived >::derived(), and EIGEN_STRONG_INLINE.
operator+() [2/2]
template<typename SparseDerived , typename DenseDerived > EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_sum_op<typename SparseDerived::Scalar,typename DenseDerived::Scalar>, const SparseDerived, const DenseDerived> Eigen::operator+ (const SparseMatrixBase< SparseDerived > & a, const MatrixBase< DenseDerived > & b)
Definition at line 705 of file SparseCwiseBinaryOp.h.
References Eigen::SparseMatrixBase< Derived >::derived(), and EIGEN_STRONG_INLINE.
operator-() [1/2]
template<typename DenseDerived , typename SparseDerived > EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_difference_op<typename DenseDerived::Scalar,typename SparseDerived::Scalar>, const DenseDerived, const SparseDerived> Eigen::operator- (const MatrixBase< DenseDerived > & a, const SparseMatrixBase< SparseDerived > & b)
Definition at line 712 of file SparseCwiseBinaryOp.h.
References Eigen::SparseMatrixBase< Derived >::derived(), and EIGEN_STRONG_INLINE.
operator-() [2/2]
template<typename SparseDerived , typename DenseDerived > EIGEN_STRONG_INLINE const CwiseBinaryOp<internal::scalar_difference_op<typename SparseDerived::Scalar,typename DenseDerived::Scalar>, const SparseDerived, const DenseDerived> Eigen::operator- (const SparseMatrixBase< SparseDerived > & a, const MatrixBase< DenseDerived > & b)
Definition at line 719 of file SparseCwiseBinaryOp.h.
References Eigen::SparseMatrixBase< Derived >::derived().
operator<<()
template<typename T > std::ostream& Eigen::operator<< (std::ostream & os, const TensorBase< T, ReadOnlyAccessors > & expr)
Definition at line 59 of file TensorIO.h.
References eval(), and Eigen::internal::TensorPrinter< Tensor, Rank >::run().
operator==() [1/2]
template<typename U , typename V > EIGEN_CONSTEXPR EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::operator== (const Tuple< U, V > & x, const Tuple< U, V > & y)
Definition at line 142 of file TensorMeta.h.
References EIGEN_CONSTEXPR, EIGEN_STRONG_INLINE, Eigen::Tuple< U, V >::first, and Eigen::Tuple< U, V >::second.
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator==().
operator==() [2/2]
template<class T , std::size_t N> EIGEN_DEVICE_FUNC bool Eigen::operator== (const array< T, N > & lhs, const array< T, N > & rhs)
Definition at line 183 of file EmulateArray.h.
References i.
poly_eval()
template<typename Polynomials , typename T > T Eigen::poly_eval (const Polynomials & poly, const T & x) inline
Returns
the evaluation of the polynomial at x using stabilized Horner algorithm.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. \(1 + 3x^2 \) is stored as a vector \([ 1, 0, 3 ] \).
[in] x : the value to evaluate the polynomial at.
Definition at line 46 of file PolynomialUtils.h.
References abs2(), i, poly_eval_horner(), Eigen::half_impl::pow(), and x.
Referenced by aux_evalSolver(), main(), and realRoots_to_monicPolynomial_test().
poly_eval_horner()
template<typename Polynomials , typename T > T Eigen::poly_eval_horner (const Polynomials & poly, const T & x) inline
Returns
the evaluation of the polynomial at x using Horner algorithm.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. \(1 + 3x^2 \) is stored as a vector \([ 1, 0, 3 ] \).
[in] x : the value to evaluate the polynomial at.
Note for stability: \(|x| \le 1 \)
Definition at line 28 of file PolynomialUtils.h.
References i.
Referenced by poly_eval().
polygamma()
template<typename DerivedN , typename DerivedX > const Eigen::CwiseBinaryOp<Eigen::internal::scalar_polygamma_op<typename DerivedX::Scalar>, const DerivedN, const DerivedX> Eigen::polygamma (const Eigen::ArrayBase< DerivedN > & n, const Eigen::ArrayBase< DerivedX > & x) inline
Returns
an expression of the coefficient-wise polygamma(n, x) to the given arrays.
It returns the n -th derivative of the digamma(psi) evaluated at x.
Note
This function supports only float and double scalar types in c++11 mode. To support other scalar types, or float/double in non c++11 mode, the user has to provide implementations of polygamma(T,T) for any scalar type T to be supported.
See also
Eigen::digamma()
Definition at line 70 of file SpecialFunctionsArrayAPI.h.
Referenced by array_special_functions(), Eigen::internal::scalar_polygamma_op< Scalar >::operator()(), operator^(), and Eigen::internal::ppolygamma().
prod()
template<typename Lhs , typename Rhs > const Product<Lhs,Rhs> Eigen::prod (const Lhs & lhs, const Rhs & rhs)
Definition at line 8 of file evaluators.cpp.
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_solve_impl(), Eigen::internal::array_prod(), Eigen::SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::determinant(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::internal::predux< Packet4i >(), Eigen::internal::predux_mul< Packet2cf >(), Eigen::internal::predux_mul< Packet4f >(), Eigen::internal::predux_mul< Packet4i >(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >::run(), and test_evaluators().
randomPermutationVector()
template<typename PermutationVectorType > void Eigen::randomPermutationVector (PermutationVectorType & v, Index size)
Definition at line 597 of file main.h.
References i, j, n, size, std::swap(), and v.
Referenced by createRandomPIMatrixOfRank(), permutationmatrices(), and sparse_permutations().
real()
template<typename DerType > const AutoDiffScalar<DerType>& Eigen::real (const AutoDiffScalar< DerType > & x) inline
Definition at line 544 of file AutoDiffScalar.h.
References x.
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::bfly3(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly4(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly5(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::internal::kissfft_impl< _Scalar >::inv(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::logDeterminant(), Eigen::internal::matrix_sqrt_quasi_triangular_2x2_diagonal_block(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::pcplxflip(), Eigen::internal::pmul(), Eigen::PolynomialSolverBase< _Scalar, 1 >::realRoots(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run(), and Eigen::Tridiagonalization< _MatrixType >::subDiagonal().
return() [1/4]
Eigen::return (x<=y ? ADSx) :ADS(y)
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::factorize().
return() [2/4]
Eigen::return (x >=y ? ADSx) :ADS(y)
return() [3/4]
Eigen::return ()
return() [4/4]
Eigen::return (x , y ? ADSx) :ADS(y)
roots_to_monicPolynomial()
template<typename RootVector , typename Polynomial > void Eigen::roots_to_monicPolynomial (const RootVector & rv, Polynomial & poly)
Given the roots of a polynomial compute the coefficients in the monomial basis of the monic polynomial with same roots and minimal degree. If RootVector is a vector of complexes, Polynomial should also be a vector of complexes.
Parameters
[in] rv : a vector containing the roots of a polynomial.
[out] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. \(3 + x^2 \) is stored as a vector \([ 3, 0, 1 ] \).
Definition at line 127 of file PolynomialUtils.h.
References i, and j.
Referenced by CauchyBounds(), main(), polynomialsolver(), and realRoots_to_monicPolynomial_test().
saveMarket()
template<typename SparseMatrixType > bool Eigen::saveMarket (const SparseMatrixType & mat, const std::string & filename, int sym = 0)
Definition at line 225 of file MarketIO.h.
References header(), j, and Eigen::internal::PutMatrixElt().
saveMarketVector()
template<typename VectorType > bool Eigen::saveMarketVector (const VectorType & vec, const std::string & filename)
Definition at line 251 of file MarketIO.h.
References i, and Eigen::internal::putVectorElt().
setCpuCacheSizes()
void Eigen::setCpuCacheSizes (std::ptrdiff_t l1, std::ptrdiff_t l2, std::ptrdiff_t l3) inline
Set the cpu L1 and L2 cache sizes (in bytes). These values are use to adjust the size of the blocks for the algorithms working per blocks.
See also
computeProductBlockingSizes
Definition at line 2142 of file GeneralBlockPanelKernel.h.
References Eigen::internal::manage_caching_sizes(), and SetAction.
Referenced by main().
setNbThreads()
void Eigen::setNbThreads (int v) inline
Sets the max number of threads reserved for Eigen
See also
nbThreads
Definition at line 67 of file Parallelizer.h.
References Eigen::internal::manage_multi_threading(), and SetAction.
Referenced by compute(), and main().
ssaupd_()
void Eigen::ssaupd_ (int * ido, char * bmat, int * n, char * which, int * nev, float * tol, float * resid, int * ncv, float * v, int * ldv, int * iparam, int * ipntr, float * workd, float * workl, int * lworkl, int * info)
Referenced by Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), and Eigen::internal::arpack_wrapper< float, float >::saupd().
sseupd_()
void Eigen::sseupd_ (int * rvec, char * All, int * select, float * d, float * z, int * ldz, float * sigma, char * bmat, int * n, char * which, int * nev, float * tol, float * resid, int * ncv, float * v, int * ldv, int * iparam, int * ipntr, float * workd, float * workl, int * lworkl, int * ierr)
Referenced by Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), and Eigen::internal::arpack_wrapper< float, float >::seupd().
subtract_assign_using_evaluator()
template<typename DstXprType , typename SrcXprType > void Eigen::subtract_assign_using_evaluator (const DstXprType & dst, const SrcXprType & src)
Definition at line 60 of file evaluators.cpp.
References Eigen::internal::call_assignment().
Referenced by test_evaluators().
swap_using_evaluator()
template<typename DstXprType , typename SrcXprType > void Eigen::swap_using_evaluator (const DstXprType & dst, const SrcXprType & src)
Definition at line 81 of file evaluators.cpp.
References Eigen::internal::call_assignment().
Referenced by test_evaluators().
test_is_equal()
template<typename T , typename U > bool Eigen::test_is_equal (const T & actual, const U & expected, bool expect_equal = true)
Definition at line 537 of file main.h.
References cols, createRandomPIMatrixOfRank(), m, and rows.
Referenced by test_isUnitary().
test_isApprox() [1/14]
bool Eigen::test_isApprox (const short & a, const short & b) inline
Definition at line 313 of file main.h.
Referenced by test_isApproxWithRef(), and verifyIsApprox().
test_isApprox() [2/14]
bool Eigen::test_isApprox (const unsigned short & a, const unsigned short & b) inline
Definition at line 315 of file main.h.
test_isApprox() [3/14]
bool Eigen::test_isApprox (const unsigned int & a, const unsigned int & b) inline
Definition at line 317 of file main.h.
test_isApprox() [4/14]
bool Eigen::test_isApprox (const long & a, const long & b) inline
Definition at line 319 of file main.h.
test_isApprox() [5/14]
bool Eigen::test_isApprox (const unsigned long & a, const unsigned long & b) inline
Definition at line 321 of file main.h.
test_isApprox() [6/14]
bool Eigen::test_isApprox (const int & a, const int & b) inline
Definition at line 324 of file main.h.
test_isApprox() [7/14]
bool Eigen::test_isApprox (const float & a, const float & b) inline
Definition at line 331 of file main.h.
References test_precision< float >().
test_isApprox() [8/14]
bool Eigen::test_isApprox (const double & a, const double & b) inline
Definition at line 338 of file main.h.
References test_precision< double >().
test_isApprox() [9/14]
bool Eigen::test_isApprox (const std::complex< float > & a, const std::complex< float > & b) inline
Definition at line 346 of file main.h.
References test_precision().
test_isApprox() [10/14]
bool Eigen::test_isApprox (const std::complex< double > & a, const std::complex< double > & b) inline
Definition at line 351 of file main.h.
References test_precision().
test_isApprox() [11/14]
bool Eigen::test_isApprox (const std::complex< long double > & a, const std::complex< long double > & b) inline
Definition at line 357 of file main.h.
References test_precision().
test_isApprox() [12/14]
bool Eigen::test_isApprox (const long double & a, const long double & b) inline
Definition at line 365 of file main.h.
References ret, and test_precision< long double >().
test_isApprox() [13/14]
bool Eigen::test_isApprox (const half & a, const half & b) inline
Definition at line 380 of file main.h.
test_isApprox() [14/14]
template<typename Type1 , typename Type2 > bool Eigen::test_isApprox (const Type1 & a, const Type2 & b, typename Type1::Scalar * = 0) inline
Definition at line 469 of file main.h.
test_isApproxOrLessThan() [1/5]
bool Eigen::test_isApproxOrLessThan (const int & a, const int & b) inline
Definition at line 328 of file main.h.
test_isApproxOrLessThan() [2/5]
bool Eigen::test_isApproxOrLessThan (const float & a, const float & b) inline
Definition at line 335 of file main.h.
References test_precision< float >().
test_isApproxOrLessThan() [3/5]
bool Eigen::test_isApproxOrLessThan (const double & a, const double & b) inline
Definition at line 342 of file main.h.
References test_precision< double >().
test_isApproxOrLessThan() [4/5]
bool Eigen::test_isApproxOrLessThan (const long double & a, const long double & b) inline
Definition at line 376 of file main.h.
References test_precision< long double >().
test_isApproxOrLessThan() [5/5]
bool Eigen::test_isApproxOrLessThan (const half & a, const half & b) inline
Definition at line 384 of file main.h.
test_isApproxWithRef()
template<typename Scalar , typename ScalarRef > bool Eigen::test_isApproxWithRef (const Scalar & a, const Scalar & b, const ScalarRef & ref) inline
Definition at line 507 of file main.h.
References test_isApprox().
Referenced by adjoint_specific< true >::run(), and adjoint_specific< false >::run().
test_isMuchSmallerThan() [1/10]
bool Eigen::test_isMuchSmallerThan (const int & a, const int & b) inline
Definition at line 326 of file main.h.
Referenced by verify_euler_ranged().
test_isMuchSmallerThan() [2/10]
bool Eigen::test_isMuchSmallerThan (const float & a, const float & b) inline
Definition at line 333 of file main.h.
References test_precision< float >().
test_isMuchSmallerThan() [3/10]
bool Eigen::test_isMuchSmallerThan (const double & a, const double & b) inline
Definition at line 340 of file main.h.
References test_precision< double >().
test_isMuchSmallerThan() [4/10]
bool Eigen::test_isMuchSmallerThan (const std::complex< float > & a, const std::complex< float > & b) inline
Definition at line 348 of file main.h.
References test_precision().
test_isMuchSmallerThan() [5/10]
bool Eigen::test_isMuchSmallerThan (const std::complex< double > & a, const std::complex< double > & b) inline
Definition at line 353 of file main.h.
References test_precision().
test_isMuchSmallerThan() [6/10]
bool Eigen::test_isMuchSmallerThan (const std::complex< long double > & a, const std::complex< long double > & b) inline
Definition at line 359 of file main.h.
References test_precision().
test_isMuchSmallerThan() [7/10]
bool Eigen::test_isMuchSmallerThan (const long double & a, const long double & b) inline
Definition at line 374 of file main.h.
References test_precision< long double >().
test_isMuchSmallerThan() [8/10]
bool Eigen::test_isMuchSmallerThan (const half & a, const half & b) inline
Definition at line 382 of file main.h.
test_isMuchSmallerThan() [9/10]
template<typename Derived1 , typename Derived2 > bool Eigen::test_isMuchSmallerThan (const MatrixBase< Derived1 > & m1, const MatrixBase< Derived2 > & m2) inline
Definition at line 513 of file main.h.
References Eigen::DenseBase< Derived >::isMuchSmallerThan(), and test_precision().
test_isMuchSmallerThan() [10/10]
template<typename Derived > bool Eigen::test_isMuchSmallerThan (const MatrixBase< Derived > & m, const typename NumTraits< typename internal::traits< Derived >::Scalar >::Real & s) inline
Definition at line 520 of file main.h.
References Eigen::DenseBase< Derived >::isMuchSmallerThan(), and test_precision().
test_isUnitary()
template<typename Derived > bool Eigen::test_isUnitary (const MatrixBase< Derived > & m) inline
Definition at line 527 of file main.h.
References Eigen::MatrixBase< Derived >::isUnitary(), test_is_equal(), and test_precision().
test_precision()
template<typename T > NumTraits<T>::Real Eigen::test_precision () inline
Definition at line 305 of file main.h.
Referenced by test_isApprox(), test_isMuchSmallerThan(), and test_isUnitary().
test_precision< double >()
template<> double Eigen::test_precision< double > () inline
Definition at line 307 of file main.h.
References e().
Referenced by test_isApprox(), test_isApproxOrLessThan(), test_isMuchSmallerThan(), test_precision< std::complex< double > >(), and test_precision< std::complex< double > >().
test_precision< float >()
template<> float Eigen::test_precision< float > () inline
Definition at line 306 of file main.h.
References e().
Referenced by test_isApprox(), test_isApproxOrLessThan(), test_isMuchSmallerThan(), test_precision< std::complex< float > >(), and test_precision< std::complex< float > >().
test_precision< long double >()
template<> long double Eigen::test_precision< long double > () inline
Definition at line 308 of file main.h.
References e().
Referenced by test_isApprox(), test_isApproxOrLessThan(), test_isMuchSmallerThan(), and test_precision< std::complex< long double > >().
test_precision< Real >()
template<> Real Eigen::test_precision< Real > ()
Definition at line 83 of file boostmultiprec.cpp.
References e().
Referenced by boost::multiprecision::get_test_precision(), boost::multiprecision::test_isApprox(), boost::multiprecision::test_isApproxOrLessThan(), and boost::multiprecision::test_isMuchSmallerThan().
test_precision< std::complex< double > >()
template<> double Eigen::test_precision< std::complex< double > > () inline
Definition at line 310 of file main.h.
References test_precision< double >().
test_precision< std::complex< float > >()
template<> float Eigen::test_precision< std::complex< float > > () inline
Definition at line 309 of file main.h.
References test_precision< float >().
test_precision< std::complex< long double > >()
template<> long double Eigen::test_precision< std::complex< long double > > () inline
Definition at line 311 of file main.h.
References test_precision< long double >().
test_relative_error() [1/13]
template<typename T , typename Derived > T Eigen::test_relative_error (const AlignedVector3< T > & a, const MatrixBase< Derived > & b)
Definition at line 16 of file alignedvector3.cpp.
References test_relative_error().
test_relative_error() [2/13]
template<typename T1 , typename T2 > NumTraits<typename T1::RealScalar>::NonInteger Eigen::test_relative_error (const EigenBase< T1 > & a, const EigenBase< T2 > & b)
Definition at line 389 of file main.h.
References cwiseAbs2(), Eigen::EigenBase< Derived >::derived(), min, sqrt(), and mpfr::sum().
Referenced by test_relative_error(), and verifyIsApprox().
test_relative_error() [3/13]
template<typename T1 , typename T2 > T1::RealScalar Eigen::test_relative_error (const T1 & a, const T2 & b, const typename T1::Coefficients * = 0)
Definition at line 399 of file main.h.
References test_relative_error().
test_relative_error() [4/13]
template<typename T1 , typename T2 > T1::Scalar Eigen::test_relative_error (const T1 & a, const T2 & b, const typename T1::MatrixType * = 0)
Definition at line 405 of file main.h.
References test_relative_error().
test_relative_error() [5/13]
template<typename S , int D> S Eigen::test_relative_error (const Translation< S, D > & a, const Translation< S, D > & b)
Definition at line 411 of file main.h.
References test_relative_error(), and Eigen::Translation< _Scalar, _Dim >::vector().
test_relative_error() [6/13]
template<typename S , int D, int O> S Eigen::test_relative_error (const ParametrizedLine< S, D, O > & a, const ParametrizedLine< S, D, O > & b)
Definition at line 417 of file main.h.
References max, Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::origin(), and test_relative_error().
test_relative_error() [7/13]
template<typename S , int D> S Eigen::test_relative_error (const AlignedBox< S, D > & a, const AlignedBox< S, D > & b)
Definition at line 423 of file main.h.
References max, Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), Eigen::AlignedBox< _Scalar, _AmbientDim >::min(), and test_relative_error().
test_relative_error() [8/13]
template<typename T1 , typename T2 > T1::RealScalar Eigen::test_relative_error (const MatrixBase< T1 > & a, const SparseMatrixBase< T2 > & b)
Definition at line 430 of file main.h.
References test_relative_error(), and Eigen::SparseMatrixBase< Derived >::toDense().
test_relative_error() [9/13]
template<typename T1 , typename T2 > T1::RealScalar Eigen::test_relative_error (const SparseMatrixBase< T1 > & a, const MatrixBase< T2 > & b)
Definition at line 437 of file main.h.
References b, test_relative_error(), and Eigen::SparseMatrixBase< Derived >::toDense().
test_relative_error() [10/13]
template<typename T1 , typename T2 > T1::RealScalar Eigen::test_relative_error (const SparseMatrixBase< T1 > & a, const SparseMatrixBase< T2 > & b)
Definition at line 444 of file main.h.
References test_relative_error(), and Eigen::SparseMatrixBase< Derived >::toDense().
test_relative_error() [11/13]
template<typename T1 , typename T2 > NumTraits<typename NumTraits<T1>::Real>::NonInteger Eigen::test_relative_error (const T1 & a, const T2 & b, typename internal::enable_if< internal::is_arithmetic< typename NumTraits< T1 >::Real >::value, T1 >::type * = 0)
Definition at line 450 of file main.h.
References abs2(), and Eigen::numext::sqrt().
test_relative_error() [12/13]
template<typename T > T Eigen::test_relative_error (const Rotation2D< T > & a, const Rotation2D< T > & b)
Definition at line 457 of file main.h.
References Eigen::Rotation2D< _Scalar >::angle(), and test_relative_error().
test_relative_error() [13/13]
template<typename T > T Eigen::test_relative_error (const AngleAxis< T > & a, const AngleAxis< T > & b)
Definition at line 463 of file main.h.
References Eigen::AngleAxis< _Scalar >::angle(), Eigen::AngleAxis< _Scalar >::axis(), max, and test_relative_error().
umfpack_defaults() [1/2]
void Eigen::umfpack_defaults (double control[UMFPACK_CONTROL], double) inline
Definition at line 20 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::init().
umfpack_defaults() [2/2]
void Eigen::umfpack_defaults (double control[UMFPACK_CONTROL], std::complex< double >) inline
Definition at line 23 of file UmfPackSupport.h.
umfpack_free_numeric() [1/2]
void Eigen::umfpack_free_numeric (void ** Numeric, double) inline
Definition at line 44 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::compute(), Eigen::UmfPackLU< _MatrixType >::factorize(), and Eigen::UmfPackLU< _MatrixType >::~UmfPackLU().
umfpack_free_numeric() [2/2]
void Eigen::umfpack_free_numeric (void ** Numeric, std::complex< double >) inline
Definition at line 47 of file UmfPackSupport.h.
umfpack_free_symbolic() [1/2]
void Eigen::umfpack_free_symbolic (void ** Symbolic, double) inline
Definition at line 50 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::compute(), and Eigen::UmfPackLU< _MatrixType >::~UmfPackLU().
umfpack_free_symbolic() [2/2]
void Eigen::umfpack_free_symbolic (void ** Symbolic, std::complex< double >) inline
Definition at line 53 of file UmfPackSupport.h.
umfpack_get_determinant() [1/2]
int Eigen::umfpack_get_determinant (double * Mx, double * Ex, void * NumericHandle, double User_Info[UMFPACK_INFO]) inline
Definition at line 124 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::determinant().
umfpack_get_determinant() [2/2]
int Eigen::umfpack_get_determinant (std::complex< double > * Mx, double * Ex, void * NumericHandle, double User_Info[UMFPACK_INFO]) inline
Definition at line 129 of file UmfPackSupport.h.
umfpack_get_lunz() [1/2]
int Eigen::umfpack_get_lunz (int * lnz, int * unz, int * n_row, int * n_col, int * nz_udiag, void * Numeric, double) inline
Definition at line 98 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::extractData().
umfpack_get_lunz() [2/2]
int Eigen::umfpack_get_lunz (int * lnz, int * unz, int * n_row, int * n_col, int * nz_udiag, void * Numeric, std::complex< double >) inline
Definition at line 103 of file UmfPackSupport.h.
umfpack_get_numeric() [1/2]
int Eigen::umfpack_get_numeric (int Lp[], int Lj[], double Lx[], int Up[], int Ui[], double Ux[], int P[], int Q[], double Dx[], int * do_recip, double Rs[], void * Numeric) inline
Definition at line 108 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::extractData().
umfpack_get_numeric() [2/2]
int Eigen::umfpack_get_numeric (int Lp[], int Lj[], std::complex< double > Lx[], int Up[], int Ui[], std::complex< double > Ux[], int P[], int Q[], std::complex< double > Dx[], int * do_recip, double Rs[], void * Numeric) inline
Definition at line 114 of file UmfPackSupport.h.
umfpack_numeric() [1/2]
int Eigen::umfpack_numeric (const int Ap[], const int Ai[], const double Ax[], void * Symbolic, void ** Numeric, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO]) inline
Definition at line 70 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::factorize_impl().
umfpack_numeric() [2/2]
int Eigen::umfpack_numeric (const int Ap[], const int Ai[], const std::complex< double > Ax[], void * Symbolic, void ** Numeric, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO]) inline
Definition at line 77 of file UmfPackSupport.h.
umfpack_report_control() [1/2]
void Eigen::umfpack_report_control (double control[UMFPACK_CONTROL], double) inline
Definition at line 38 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::umfpackReportControl().
umfpack_report_control() [2/2]
void Eigen::umfpack_report_control (double control[UMFPACK_CONTROL], std::complex< double >) inline
Definition at line 41 of file UmfPackSupport.h.
umfpack_report_info() [1/2]
void Eigen::umfpack_report_info (double control[UMFPACK_CONTROL], double info[UMFPACK_INFO], double) inline
Definition at line 26 of file UmfPackSupport.h.
References info.
Referenced by Eigen::UmfPackLU< _MatrixType >::umfpackReportInfo().
umfpack_report_info() [2/2]
void Eigen::umfpack_report_info (double control[UMFPACK_CONTROL], double info[UMFPACK_INFO], std::complex< double >) inline
Definition at line 29 of file UmfPackSupport.h.
References info.
umfpack_report_status() [1/2]
void Eigen::umfpack_report_status (double control[UMFPACK_CONTROL], int status, double) inline
Definition at line 32 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::umfpackReportStatus().
umfpack_report_status() [2/2]
void Eigen::umfpack_report_status (double control[UMFPACK_CONTROL], int status, std::complex< double >) inline
Definition at line 35 of file UmfPackSupport.h.
umfpack_solve() [1/2]
int Eigen::umfpack_solve (int sys, const int Ap[], const int Ai[], const double Ax[], double X[], const double B[], void * Numeric, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO]) inline
Definition at line 84 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::_solve_impl().
umfpack_solve() [2/2]
int Eigen::umfpack_solve (int sys, const int Ap[], const int Ai[], const std::complex< double > Ax[], std::complex< double > X[], const std::complex< double > B[], void * Numeric, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO]) inline
Definition at line 91 of file UmfPackSupport.h.
umfpack_symbolic() [1/2]
int Eigen::umfpack_symbolic (int n_row, int n_col, const int Ap[], const int Ai[], const double Ax[], void ** Symbolic, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO]) inline
Definition at line 56 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern_impl().
umfpack_symbolic() [2/2]
int Eigen::umfpack_symbolic (int n_row, int n_col, const int Ap[], const int Ai[], const std::complex< double > Ax[], void ** Symbolic, const double Control[UMFPACK_CONTROL], double Info[UMFPACK_INFO]) inline
Definition at line 63 of file UmfPackSupport.h.
verifyIsApprox()
template<typename Type1 , typename Type2 > bool Eigen::verifyIsApprox (const Type1 & a, const Type2 & b) inline
Definition at line 489 of file main.h.
References get_test_precision(), ret, test_isApprox(), and test_relative_error().
viewAsCholmod() [1/5]
template<typename _Scalar , int _Options, typename _StorageIndex > cholmod_sparse Eigen::viewAsCholmod (Ref< SparseMatrix< _Scalar, _Options, _StorageIndex > > mat)
Wraps the Eigen sparse matrix mat into a Cholmod sparse matrix object. Note that the data are shared.
Definition at line 58 of file CholmodSupport.h.
References eigen_assert, mat, res, and Eigen::TensorSycl::run().
Referenced by Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve_impl(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::analyzePattern(), Eigen::SPQR< _MatrixType >::compute(), Eigen::SPQR_QProduct< SPQRType, Derived >::evalTo(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::factorize(), and viewAsCholmod().
viewAsCholmod() [2/5]
template<typename _Scalar , int _Options, typename _Index > const cholmod_sparse Eigen::viewAsCholmod (const SparseMatrix< _Scalar, _Options, _Index > & mat)
Definition at line 105 of file CholmodSupport.h.
References Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::const_cast_derived(), res, and viewAsCholmod().
viewAsCholmod() [3/5]
template<typename _Scalar , int _Options, typename _Index > const cholmod_sparse Eigen::viewAsCholmod (const SparseVector< _Scalar, _Options, _Index > & mat)
Definition at line 112 of file CholmodSupport.h.
References Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _StorageIndex > >::const_cast_derived(), res, and viewAsCholmod().
viewAsCholmod() [4/5]
template<typename _Scalar , int _Options, typename _Index , unsigned int UpLo> cholmod_sparse Eigen::viewAsCholmod (const SparseSelfAdjointView< const SparseMatrix< _Scalar, _Options, _Index >, UpLo > & mat)
Returns a view of the Eigen sparse matrix mat as Cholmod sparse matrix. The data are not copied but shared.
Definition at line 121 of file CholmodSupport.h.
References Lower, mat, res, Upper, and viewAsCholmod().
viewAsCholmod() [5/5]
template<typename Derived > cholmod_dense Eigen::viewAsCholmod (MatrixBase< Derived > & mat)
Returns a view of the Eigen dense matrix mat as Cholmod dense matrix. The data are not copied but shared.
Definition at line 134 of file CholmodSupport.h.
References EIGEN_STATIC_ASSERT, res, RowMajorBit, and Eigen::TensorSycl::run().
viewAsEigen()
template<typename Scalar , int Flags, typename StorageIndex > MappedSparseMatrix<Scalar,Flags,StorageIndex> Eigen::viewAsEigen (cholmod_sparse & cm)
Returns a view of the Cholmod sparse matrix cm as an Eigen sparse matrix. The data are not copied but shared.
Definition at line 155 of file CholmodSupport.h.
zeta()
template<typename DerivedX , typename DerivedQ > const Eigen::CwiseBinaryOp<Eigen::internal::scalar_zeta_op<typename DerivedX::Scalar>, const DerivedX, const DerivedQ> Eigen::zeta (const Eigen::ArrayBase< DerivedX > & x, const Eigen::ArrayBase< DerivedQ > & q) inline
Returns
an expression of the coefficient-wise zeta(x, q) to the given arrays.
It returns the Riemann zeta function of two arguments x and q:
Parameters
x is the exposent, it must be > 1
q is the shift, it must be > 0
Note
This function supports only float and double scalar types. To support other scalar types, the user has to provide implementations of zeta(T,T) for any scalar type T to be supported.
See also
ArrayBase::zeta()
Definition at line 114 of file SpecialFunctionsArrayAPI.h.
Referenced by Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_zeta_op< Scalar >::operator()(), and Eigen::internal::pzeta().
Variable Documentation
ActualPacketAccessBit
const unsigned int Eigen::ActualPacketAccessBit = 0x0
Definition at line 102 of file Constants.h.
CoherentAccessPattern
const int Eigen::CoherentAccessPattern = 0x1
Definition at line 47 of file SparseUtil.h.
Dynamic
const int Eigen::Dynamic = -1
This value means that a positive quantity (e.g., a size) is not known at compile-time, and that instead the value is stored in some runtime variable.
Changing the value of Dynamic breaks the ABI, as Dynamic is often used as a template parameter for Matrix.
Definition at line 21 of file Constants.h.
Referenced by __attribute__(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_check_template_params(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::adjoint(), Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), Eigen::DenseBase< Derived >::all(), Eigen::SVDBase< BDCSVD< _MatrixType > >::allocate(), Eigen::DenseBase< Derived >::any(), Eigen::internal::apply_rotation_in_the_plane(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), array(), Eigen::Array< StorageIndex, 64, 1, DontAlign >::Array(), numpy::as(), numpy::internal::as_dense_impl(), Eigen::internal::companion< _Scalar, _Deg >::balance(), basicStuff(), benchBasic_loop(), Eigen::Block< VectorType, internal::traits< VectorType >::Flags &RowMajorBit ? 1 :Size, internal::traits< VectorType >::Flags &RowMajorBit ? Size :1 >::Block(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::blockInnerIndex(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::blockInnerSize(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::blockOuterIndex(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::blockOuterSize(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::blockPtr(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::BlockSparseMatrix(), Eigen::internal::call_triangular_assignment_loop(), cholesky(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef(), Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), Eigen::CwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >::cols(), Eigen::MatrixPower< MatrixType >::cols(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::cols(), ctms_decompositions(), Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::CwiseNullaryOp(), Eigen::Spline< _Scalar, _Dim, _Degree >::degree(), dense_storage_assignment(), dense_storage_copy(), diagonal(), Eigen::AlignedBox< _Scalar, _AmbientDim >::dim(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::dim(), Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::evalTo(), Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::evalTo(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::evaluator< PartialReduxExpr< ArgType, MemberOp, Direction > >::evaluator(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::innerSize(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::innerToBlock(), inplace(), jacobisvd_verify_assert(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::lazyProduct(), lu_invertible(), lu_non_invertible(), map_class_matrix(), Eigen::MapBase< Derived, ReadOnlyAccessors >::MapBase(), Eigen::Matrix< Scalar, Deg, 1 >::Matrix(), eigen2_interface< real, SIZE >::name(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::nonZeros(), Eigen::AutoDiffJacobian< Functor >::operator()(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator*(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::operator=(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::outerSize(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::outerToBlock(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::DenseBase< Derived >::prod(), product_extra(), Eigen::Replicate< MatrixType, RowFactor, ColFactor >::Replicate(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::reserve(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows(), Eigen::CwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >::rows(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::rows(), Eigen::internal::LU_kernel_bmod< SegSizeAtCompileTime >::run(), Eigen::internal::determinant_impl< Derived, DeterminantType >::run(), Eigen::internal::lpNorm_selector< Derived, Infinity >::run(), Eigen::internal::make_coherent_impl< Matrix< A_Scalar, A_Rows, A_Cols, A_Options, A_MaxRows, A_MaxCols >, B >::run(), Eigen::internal::make_coherent_impl< A, Matrix< B_Scalar, B_Rows, B_Cols, B_Options, B_MaxRows, B_MaxCols > >::run(), Eigen::internal::make_coherent_impl< Matrix< A_Scalar, A_Rows, A_Cols, A_Options, A_MaxRows, A_MaxCols >, Matrix< B_Scalar, B_Rows, B_Cols, B_Options, B_MaxRows, B_MaxCols > >::run(), run_nesting_ops_2(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, GemmProduct >::scaleAndAddTo(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::setBlockStructure(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::setFromTriplets(), Eigen::internal::SkylineProduct< LhsNested, RhsNested, ProductMode >::SkylineProduct(), Eigen::Spline< _Scalar, _Dim, _Degree >::Spline(), Eigen::Stride< 0, Value >::Stride(), Eigen::DenseBase< Derived >::sum(), svd_min_norm(), svd_test_all_computation_options(), svd_verify_assert(), swap(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::swap(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap(), test_boostmultiprec(), test_hessenberg(), test_mpreal_support(), Eigen::DenseBase< Derived >::transposeInPlace(), Eigen::internal::upperbidiagonalization_inplace_blocked(), vectorwiseop_array(), verifySizeOf(), Eigen::DenseBase< Derived >::visit(), zeroSizedMatrix(), and zeroSizedVector().
DynamicIndex
const int Eigen::DynamicIndex = 0xffffff
This value means that a signed quantity (e.g., a signed index) is not known at compile-time, and that instead its value has to be specified at runtime.
Definition at line 26 of file Constants.h.
expx
Scalar Eigen::expx = exp(x.value())
Definition at line 602 of file AutoDiffScalar.h.
HereditaryBits
const unsigned int Eigen::HereditaryBits
Initial value:
= RowMajorBit
                                  | EvalBeforeNestingBit
Definition at line 190 of file Constants.h.
HugeCost
const int Eigen::HugeCost = 10000
This value means that the cost to evaluate an expression coefficient is either very expensive or cannot be known at compile time.
This value has to be positive to (1) simplify cost computation, and (2) allow to distinguish between a very expensive and very very expensive expressions. It thus must also be large enough to make sure unrolling won't happen and that sub expressions will be evaluated, but not too large to avoid overflow.
Definition at line 39 of file Constants.h.
Referenced by Eigen::internal::call_triangular_assignment_loop(), and Eigen::internal::evaluator< PartialReduxExpr< ArgType, MemberOp, Direction > >::evaluator().
Infinity
const int Eigen::Infinity = -1
This value means +Infinity; it is currently used only as the p parameter to MatrixBase::lpNorm<int>(). The value Infinity there means the L-infinity norm.
Definition at line 31 of file Constants.h.
Referenced by main().
InnerRandomAccessPattern
const int Eigen::InnerRandomAccessPattern = 0x2 | CoherentAccessPattern
Definition at line 48 of file SparseUtil.h.
NestByRefBit
const unsigned int Eigen::NestByRefBit = 0x100
Definition at line 164 of file Constants.h.
OuterRandomAccessPattern
const int Eigen::OuterRandomAccessPattern = 0x4 | CoherentAccessPattern
Definition at line 49 of file SparseUtil.h.
Referenced by Eigen::internal::assign_sparse_to_sparse().
RandomAccessPattern
const int Eigen::RandomAccessPattern = 0x8 | OuterRandomAccessPattern | InnerRandomAccessPattern
Definition at line 50 of file SparseUtil.h.
SkylineBit
const unsigned int Eigen::SkylineBit = 0x1200
Definition at line 21 of file SkylineUtil.h.
y
const AutoDiffScalar< DerType > & Eigen::y
Initial value:
{
  typedef AutoDiffScalar<typename Eigen::internal::remove_all<DerType>::type::PlainObject> ADS
Definition at line 548 of file AutoDiffScalar.h.
Referenced by Eigen::SPQR< _MatrixType >::_solve_impl(), Eigen::SparseQR< _MatrixType, _OrderingType >::_solve_impl(), Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::internal::apply_rotation_in_the_plane(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheLeft(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheRight(), Eigen::internal::bicgstab(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::factorize_preordered(), Eigen::internal::gmres(), Eigen::SplineFitting< SplineType >::InterpolateWithDerivatives(), main(), Trackball::mapToSphere(), Eigen::Matrix< Scalar, Deg, 1 >::Matrix(), Eigen::internal::matrix_log_compute_2x2(), operator!=(), Eigen::internal::pexp< Packet4f >(), Eigen::internal::plog< Packet4f >(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::ptranspose(), Eigen::internal::RandomToTypeNormal(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >::run(), Eigen::internal::igammac_impl< Scalar >::run(), setinnerrand_eigen(), setrand_eigen_compact(), setrand_eigen_dynamic(), setrand_eigen_gnu_hash(), setrand_eigen_google_dense(), setrand_eigen_google_sparse(), setrand_eigen_sumeq(), setrand_scipy(), setrand_ublas_genvec(), setrand_ublas_mapped(), and Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::toRotationMatrix().