pairinteraction: Eigen::TensorSycl Namespace Reference
Eigen::TensorSycl Namespace Reference
Namespaces
internal
Functions
template<typename Expr , typename Dev >
void run (Expr &expr, Dev &dev)
Function Documentation
run()
template<typename Expr , typename Dev > void Eigen::TensorSycl::run (Expr & expr, Dev & dev)
The run function in tensor sycl convert the expression tree to a buffer based expression tree; creates the expression tree for the device with accessor to buffers; construct the kernel and submit it to the sycl queue.
Definition at line 33 of file TensorSyclRun.h.
References Eigen::TensorEvaluator< Derived, Device >::cleanup(), Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded(), and Eigen::TensorSycl::internal::extractFunctors().
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, SparseShape, SparseShape, ProductType >::addTo(), adjoint(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::affine(), Eigen::DynamicSGroup::apply(), Eigen::internal::array_get(), benchmark_t::benchmark_t(), Eigen::internal::call_assignment_no_alias(), Eigen::internal::call_assignment_no_alias_no_transpose(), Eigen::internal::call_dense_assignment_loop(), Eigen::ComplexSchur< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::computeDirect(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::computeInverseAndDetWithCheck(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::conjugate(), Eigen::dimensions_match(), Eigen::TensorContractionEvaluatorBase< TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType >, Device > >::evalGemv(), Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType, MakePointer_ >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorConversionOp< TargetType, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::internal::generic_product_impl< Lhs, Rhs, SparseShape, SparseShape, ProductType >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, PermutationShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, MatrixShape, PermutationShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Inverse< Lhs >, Rhs, PermutationShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Inverse< Rhs >, MatrixShape, PermutationShape, ProductTag >::evalTo(), gemm(), ger(), gerc(), geru(), hemv(), mapstaticmethods(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::RotationBase< Derived, 3 >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::operator*(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::operator=(), Eigen::TensorEvaluator< const TensorConversionOp< TargetType, ArgType >, Device >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), Eigen::internal::pblend(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::predux_max< Packet2d >(), Eigen::internal::ptranspose(), Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate(), Eigen::DenseBase< Derived >::redux(), Eigen::VectorwiseOp< ExpressionType, Direction >::reverseInPlace(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, Side, Mode, Conjugate, TriStorageOrder, RowMajor >::run(), mapstaticmethods_impl< PlainObjectType, false, IsVector >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >::run(), internal::general_rank1_update< Scalar, Index, RowMajor, ConjLhs, ConjRhs >::run(), Eigen::selfadjoint_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, UpLo, Version >::run(), internal::selfadjoint_packed_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, true >::run(), Eigen::internal::TensorExecutor< Expression, DefaultDevice, true >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, LhsIsTriangular, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, RowMajor, Version >::run(), internal::packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >::run(), Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, false >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, Dynamic >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >::run(), Eigen::internal::triangular_solver_unroller< Lhs, Rhs, Mode, LoopIndex, Size, false >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, OnTheLeft, Mode, CompleteUnrolling, 1 >::run(), Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, OnTheRight, Mode, CompleteUnrolling, 1 >::run(), Eigen::internal::triangular_product_impl< Mode, true, Lhs, false, Rhs, true >::run(), Eigen::internal::gemv_dense_selector< OnTheLeft, StorageOrder, BlasCompatible >::run(), Eigen::internal::triangular_product_impl< Mode, false, Lhs, true, Rhs, false >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, true >::run(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, true >::run(), Eigen::internal::trmv_selector< Mode, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::run(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >::run(), Eigen::internal::ArrayApplyAndReduce< Reducer, Op, A, 1 >::run(), Eigen::internal::redux_impl< Func, Derived, SliceVectorizedTraversal, Unrolling >::run(), Eigen::internal::trmv_selector< Mode, RowMajor >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, LhsSelfAdjoint, ConjugateLhs, RhsStorageOrder, RhsSelfAdjoint, ConjugateRhs, RowMajor >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run(), Eigen::internal::ArrayZipAndReduce< Reducer, Op, A, B, 1 >::run(), Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run(), Eigen::internal::triangular_product_impl< Mode, LhsIsTriangular, Lhs, false, Rhs, false >::run(), Eigen::internal::random_default_impl< half, false, false >::run(), Eigen::internal::sparse_vector_assign_selector< Dest, Src, SVA_RuntimeSwitch >::run(), Eigen::internal::dense_assignment_loop< Kernel, InnerVectorizedTraversal, InnerUnrolling >::run(), Eigen::internal::selfadjoint_product_impl< Lhs, LhsMode, false, Rhs, RhsMode, false >::run(), Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, GemvProduct >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, TriangularShape, DenseShape, ProductTag >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, TriangularShape, ProductTag >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, SelfAdjointShape, DenseShape, ProductTag >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, SelfAdjointShape, ProductTag >::scaleAndAddTo(), Eigen::internal::smart_copy(), Eigen::internal::smart_memmove(), Eigen::internal::sparse_time_dense_product(), symm(), symv(), syr2k(), syrk(), testMatrixSqrt(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), Eigen::DenseBase< Derived >::transposeInPlace(), trmm(), trmv(), trsm(), trsv(), Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::unary_evaluator(), Eigen::viewAsCholmod(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().