pairinteraction: internal Namespace Reference
internal Namespace Reference
Data Structures
struct band_solve_triangular_selector
struct band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ColMajor >
struct band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, RowMajor >
struct colamd_col
struct Colamd_Row
struct general_rank1_update
struct general_rank1_update< Scalar, Index, ColMajor, ConjLhs, ConjRhs >
struct general_rank1_update< Scalar, Index, RowMajor, ConjLhs, ConjRhs >
struct packed_rank2_update_selector
struct packed_triangular_matrix_vector_product
struct packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor >
struct packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor >
struct packed_triangular_solve_vector
struct packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >
struct packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >
struct packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >
struct rank2_update_selector
struct selfadjoint_packed_rank1_update
struct selfadjoint_packed_rank1_update< Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs >
struct selfadjoint_packed_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >
Functions
template<typename IndexType >
IndexType colamd_c (IndexType n_col)
template<typename IndexType >
IndexType colamd_r (IndexType n_row)
template<typename IndexType >
IndexType colamd_recommended (IndexType nnz, IndexType n_row, IndexType n_col)
Returns the recommended value of Alen.
Function Documentation
colamd_c()
template<typename IndexType > IndexType internal::colamd_c (IndexType n_col) inline
Definition at line 202 of file Eigen_Colamd.h.
Referenced by colamd_recommended().
colamd_r()
template<typename IndexType > IndexType internal::colamd_r (IndexType n_row) inline
Definition at line 206 of file Eigen_Colamd.h.
References col(), COLAMD_KNOBS, COLAMD_STATS, head(), and p.
Referenced by colamd_recommended().
colamd_recommended()
template<typename IndexType > IndexType internal::colamd_recommended (IndexType nnz, IndexType n_row, IndexType n_col) inline
Returns the recommended value of Alen.
Returns recommended value of Alen for use by colamd. Returns -1 if any input argument is negative. The use of this routine or macro is optional. Note that the macro uses its arguments more than once, so be careful for side effects, if you pass expressions as arguments to COLAMD_RECOMMENDED.
Parameters
nnz nonzeros in A
n_row number of rows in A
n_col number of columns in A
Returns
recommended value of Alen for use by colamd
Definition at line 257 of file Eigen_Colamd.h.
References c, col(), COL_IS_ALIVE, COL_IS_DEAD, COL_IS_DEAD_PRINCIPAL, COLAMD_ASSERT, colamd_c(), COLAMD_DEBUG0, COLAMD_DEBUG1, COLAMD_DEBUG2, COLAMD_DEBUG3, COLAMD_DEBUG4, COLAMD_DEFRAG_COUNT, COLAMD_DENSE_COL, COLAMD_DENSE_ROW, COLAMD_EMPTY, COLAMD_ERROR_A_not_present, COLAMD_ERROR_A_too_small, COLAMD_ERROR_col_length_negative, COLAMD_ERROR_ncol_negative, COLAMD_ERROR_nnz_negative, COLAMD_ERROR_nrow_negative, COLAMD_ERROR_p0_nonzero, COLAMD_ERROR_p_not_present, COLAMD_ERROR_row_index_out_of_bounds, COLAMD_INFO1, COLAMD_INFO2, COLAMD_INFO3, COLAMD_KNOBS, COLAMD_OK, COLAMD_OK_BUT_JUMBLED, colamd_r(), COLAMD_STATS, COLAMD_STATUS, internal::Colamd_Row< IndexType >::degree, internal::colamd_col< IndexType >::degree_next, internal::colamd_col< IndexType >::hash, internal::colamd_col< IndexType >::hash_next, internal::colamd_col< IndexType >::headhash, i, j, KILL_NON_PRINCIPAL_COL, KILL_PRINCIPAL_COL, KILL_ROW, internal::colamd_col< IndexType >::length, ONES_COMPLEMENT, internal::colamd_col< IndexType >::order, internal::colamd_col< IndexType >::parent, internal::colamd_col< IndexType >::prev, return, row(), ROW_IS_ALIVE, ROW_IS_DEAD, ROW_IS_MARKED_DEAD, internal::colamd_col< IndexType >::score, internal::colamd_col< IndexType >::shared1, internal::Colamd_Row< IndexType >::shared1, internal::colamd_col< IndexType >::shared2, internal::colamd_col< IndexType >::shared3, internal::colamd_col< IndexType >::shared4, and internal::colamd_col< IndexType >::start.