pairinteraction: utils Namespace Reference
utils Namespace Reference
Data Structures
struct is_complex
struct is_complex< std::complex< T > >
Functions
std::default_random_engine & randint_engine ()
Thread-local static random engine.
template<typename T >
T randint (T a, T b)
Generate a random integer.
uint64_t FNV64 (uint8_t *s, size_t sz)
Function Documentation
FNV64()
uint64_t utils::FNV64 (uint8_t * s, size_t sz) inline
Definition at line 71 of file utils.h.
References i.
Referenced by Hamiltonianmatrix::hashBasis(), and Hamiltonianmatrix::hashEntries().
randint()
template<typename T > T utils::randint (T a, T b) inline
Generate a random integer.
This is very similar to the implementation of randint in the GCC standard library Fundamentals TS v2. It is specified by the standard per clause 13.2.2.1, Function template randint.
The function generates a random integer in the closed interval [a,b].
Parameters
a lower bound
b upper bound
Returns
random integer between a and b.
Definition at line 63 of file utils.h.
References a, b, and randint_engine().
randint_engine()
std::default_random_engine& utils::randint_engine () inline
Thread-local static random engine.
To save some effort this function initializes a static thread-local random engine to avoid race conditions and broken random sampling. It is seeded once using std::random_device for good entropy.
Returns
Reference to static thread-local random engine
Definition at line 43 of file utils.h.
Referenced by randint().