pairinteraction: model_potential Namespace Reference
model_potential Namespace Reference
Functions
double V (QuantumDefect const &qd, double x)
Calculate the model potentials.
double g (QuantumDefect const &qd, double x)
Helper function for Numerov's method.s.
Function Documentation
g()
double model_potential::g (QuantumDefect const & qd, double x)
Helper function for Numerov's method.s.
Numerov's method solves \(y''(x) + g(x) y(x) = 0\). This function implements \(g(x) \).
\[ g(x) = \frac{(2 l + 1/2)^2}{x} + 8 x (V_{\mathrm{mod}}(x) - E) \]
Parameters
[in] qd Quantum defect data (parameters for the potentials)
[in] x Radial position
Returns
Scaling coefficient evaluted at position x with parameters qd
Definition at line 44 of file Wavefunction.cpp.
References au2GHz, QuantumDefect::energy, QuantumDefect::l, and V().
Referenced by Eigen::DynamicSGroup::add(), BOOST_FIXTURE_TEST_CASE_TEMPLATE(), Eigen::DGMRES< _MatrixType, _Preconditioner >::dgmresCycle(), Numerov::integrate(), Eigen::internal::operator-(), and solve_with_guess().
V()
double model_potential::V (QuantumDefect const & qd, double x)
Calculate the model potentials.
This function calculates the model potentials and returns \(V_{\mathrm{mod}}(r) = V_{\mathrm{C}}(r) + V_{\mathrm{P}}(r) + V_{\mathrm{s.o.}}(r) \)
\[ \begin{aligned} V_{\mathrm{C}}(r) &= - \frac{e^2}{4\pi\varepsilon_0} \frac{1 + (Z-1)\mathrm{e}^{-\alpha_1 r} - r(\alpha_3+\alpha_4 r)\mathrm{e}^{-\alpha_2 r}}{r} \\ V_{\mathrm{P}}(r) &= -\frac{e^2}{(4\pi\varepsilon_0)^2} \frac{\alpha_d}{2 r^4} \left[ 1 - \mathrm{e}^{-(r/r_c)^6} \right] \\ V_{\mathrm{s.o.}}(r) &= \frac{1}{2} \left(\frac{e^2}{4\pi\varepsilon_0} \right) \left(\frac{g_s}{2 m_e^2 c^2} \right) \frac{\boldsymbol{l}\cdot\boldsymbol{s}}{r^3} \end{aligned} \]
Parameters
[in] qd Quantum defect data (parameters for the potentials)
[in] x Radial position
Returns
Model potentials evaluted at position x with parameters qd
Definition at line 30 of file Wavefunction.cpp.
References QuantumDefect::a1, QuantumDefect::a2, QuantumDefect::a3, QuantumDefect::a4, QuantumDefect::ac, alpha, exp(), QuantumDefect::j, QuantumDefect::l, Eigen::half_impl::pow(), QuantumDefect::rc, x, and QuantumDefect::Z.
Referenced by BOOST_FIXTURE_TEST_CASE_TEMPLATE(), and g().