pairinteraction: /travis/libpairinteraction/eigen/test/nullary.cpp File Reference
nullary.cpp File Reference
#include "main.h"
Functions
template<typename MatrixType >
bool equalsIdentity (const MatrixType &A)
template<typename VectorType >
void check_extremity_accuracy (const VectorType &v, const typename VectorType::Scalar &low, const typename VectorType::Scalar &high)
template<typename VectorType >
void testVectorType (const VectorType &base)
template<typename MatrixType >
void testMatrixType (const MatrixType &m)
void test_nullary ()
Function Documentation
check_extremity_accuracy()
template<typename VectorType > void check_extremity_accuracy (const VectorType & v, const typename VectorType::Scalar & low, const typename VectorType::Scalar & high)
Definition at line 37 of file nullary.cpp.
References abs(), i, size, v, and VERIFY.
equalsIdentity()
template<typename MatrixType > bool equalsIdentity (const MatrixType & A)
Definition at line 14 of file nullary.cpp.
References i, j, min, and zero().
Referenced by testMatrixType().
test_nullary()
void test_nullary ()
Definition at line 224 of file nullary.cpp.
References i, and testMatrixType().
testMatrixType()
template<typename MatrixType > void testMatrixType (const MatrixType & m)
Definition at line 197 of file nullary.cpp.
References abs(), cols, e(), equalsIdentity(), i, j, rows, VERIFY, and VERIFY_IS_APPROX.
Referenced by test_nullary().
testVectorType()
template<typename VectorType > void testVectorType (const VectorType & base)
Definition at line 64 of file nullary.cpp.
References size, and std::swap().