pairinteraction: /travis/libpairinteraction/eigen/test/packetmath.cpp File Reference
packetmath.cpp File Reference
#include "main.h"
#include "unsupported/Eigen/SpecialFunctions"
Data Structures
struct packet_helper< Cond, Packet >
struct packet_helper< false, Packet >
Namespaces
Eigen
Namespace containing all symbols from the Eigen library.
Eigen::internal
Macros
#define CHECK_CWISE1(REFOP, POP)
#define CHECK_CWISE1_IF(COND, REFOP, POP)
#define CHECK_CWISE2_IF(COND, REFOP, POP)
#define REF_ADD(a, b) ((a)+(b))
#define REF_SUB(a, b) ((a)-(b))
#define REF_MUL(a, b) ((a)*(b))
#define REF_DIV(a, b) ((a)/(b))
Functions
template<typename T >
T Eigen::internal::negate (const T &x)
template<typename Scalar >
EIGEN_DONT_INLINE bool isApproxAbs (const Scalar &a, const Scalar &b, const typename NumTraits< Scalar >::Real &refvalue)
template<typename Scalar >
bool areApproxAbs (const Scalar *a, const Scalar *b, int size, const typename NumTraits< Scalar >::Real &refvalue)
template<typename Scalar >
bool areApprox (const Scalar *a, const Scalar *b, int size)
template<typename Scalar >
void packetmath ()
template<typename Scalar >
void packetmath_real ()
template<typename Scalar >
void packetmath_notcomplex ()
template<typename Scalar , bool ConjLhs, bool ConjRhs>
void test_conj_helper (Scalar *data1, Scalar *data2, Scalar *ref, Scalar *pval)
template<typename Scalar >
void packetmath_complex ()
template<typename Scalar >
void packetmath_scatter_gather ()
void test_packetmath ()
Variables
const bool g_vectorize_sse = false
Macro Definition Documentation
CHECK_CWISE1
#define CHECK_CWISE1 (REFOP, POP)
Value:
{ \
  for (int i=0; i<PacketSize; ++i) \
    ref[i] = REFOP(data1[i]); \
  internal::pstore(data2, POP(internal::pload<Packet>(data1))); \
  VERIFY(areApprox(ref, data2, PacketSize) && #POP); \
}
Definition at line 64 of file packetmath.cpp.
Referenced by packetmath(), and packetmath_notcomplex().
CHECK_CWISE1_IF
#define CHECK_CWISE1_IF (COND, REFOP, POP)
Value:
if(COND) { \
  packet_helper<COND,Packet> h; \
  for (int i=0; i<PacketSize; ++i) \
    ref[i] = REFOP(data1[i]); \
  h.store(data2, POP(h.load(data1))); \
  VERIFY(areApprox(ref, data2, PacketSize) && #POP); \
}
Definition at line 91 of file packetmath.cpp.
Referenced by packetmath_real().
CHECK_CWISE2_IF
#define CHECK_CWISE2_IF (COND, REFOP, POP)
Value:
if(COND) { \
  packet_helper<COND,Packet> h; \
  for (int i=0; i<PacketSize; ++i) \
    ref[i] = REFOP(data1[i], data1[i+PacketSize]); \
  h.store(data2, POP(h.load(data1),h.load(data1+PacketSize))); \
  VERIFY(areApprox(ref, data2, PacketSize) && #POP); \
}
Definition at line 99 of file packetmath.cpp.
Referenced by packetmath(), and packetmath_notcomplex().
REF_ADD
#define REF_ADD (a, b) ((a)+(b))
Definition at line 107 of file packetmath.cpp.
Referenced by packetmath().
REF_DIV
#define REF_DIV (a, b) ((a)/(b))
Definition at line 110 of file packetmath.cpp.
Referenced by packetmath().
REF_MUL
#define REF_MUL (a, b) ((a)*(b))
Definition at line 109 of file packetmath.cpp.
Referenced by packetmath().
REF_SUB
#define REF_SUB (a, b) ((a)-(b))
Definition at line 108 of file packetmath.cpp.
Referenced by packetmath().
Function Documentation
areApprox()
template<typename Scalar > bool areApprox (const Scalar * a, const Scalar * b, int size)
Definition at line 51 of file packetmath.cpp.
References a, i, and size.
Referenced by packetmath(), packetmath_complex(), packetmath_notcomplex(), and test_conj_helper().
areApproxAbs()
template<typename Scalar > bool areApproxAbs (const Scalar * a, const Scalar * b, int size, const typename NumTraits< Scalar >::Real & refvalue)
Definition at line 38 of file packetmath.cpp.
References a, i, isApproxAbs(), and size.
Referenced by packetmath().
isApproxAbs()
template<typename Scalar > EIGEN_DONT_INLINE bool isApproxAbs (const Scalar & a, const Scalar & b, const typename NumTraits< Scalar >::Real & refvalue)
Definition at line 33 of file packetmath.cpp.
Referenced by areApproxAbs(), packetmath(), and packetmath_scatter_gather().
packetmath()
template<typename Scalar > void packetmath ()
Definition at line 112 of file packetmath.cpp.
References abs(), areApprox(), areApproxAbs(), CHECK_CWISE1, CHECK_CWISE2_IF, conj(), EIGEN_ALIGN_MAX, i, isApproxAbs(), j, max, Eigen::internal::negate(), offset, Eigen::internal::padd(), Eigen::internal::pblend(), Eigen::internal::pconj(), Eigen::internal::pdiv(), Eigen::internal::pfirst(), Eigen::internal::pinsertfirst(), Eigen::internal::pinsertlast(), Eigen::internal::pmul(), Eigen::internal::pnegate(), Eigen::internal::predux(), Eigen::internal::predux_downto4(), Eigen::internal::predux_mul(), Eigen::internal::preduxp(), Eigen::internal::preverse(), Eigen::internal::pstore(), Eigen::internal::pstoreu(), Eigen::internal::psub(), Eigen::internal::ptranspose(), REF_ADD, REF_DIV, REF_MUL, REF_SUB, s, size, Eigen::internal::is_same< T, U >::value, and VERIFY.
Referenced by test_packetmath().
packetmath_complex()
template<typename Scalar > void packetmath_complex ()
Definition at line 548 of file packetmath.cpp.
References areApprox(), EIGEN_ALIGN_MAX, i, imag(), Eigen::internal::pcplxflip(), Eigen::internal::pstore(), size, and VERIFY.
Referenced by test_packetmath().
packetmath_notcomplex()
template<typename Scalar > void packetmath_notcomplex ()
Definition at line 483 of file packetmath.cpp.
References abs(), areApprox(), CHECK_CWISE1, CHECK_CWISE2_IF, EIGEN_ALIGN_MAX, i, Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map(), max, min, Eigen::internal::pabs(), Eigen::internal::pmax(), Eigen::internal::pmin(), Eigen::internal::predux_max(), Eigen::internal::predux_min(), Eigen::internal::pstore(), size, and VERIFY.
packetmath_real()
template<typename Scalar > void packetmath_real ()
Definition at line 328 of file packetmath.cpp.
References abs(), acos(), asin(), ceil(), CHECK_CWISE1_IF, cos(), EIGEN_ALIGN_MAX, exp(), floor(), i, isnan, packet_helper< Cond, Packet >::load(), min, Eigen::internal::pacos(), Eigen::internal::pasin(), Eigen::internal::pceil(), Eigen::internal::pcos(), Eigen::internal::perf(), Eigen::internal::perfc(), Eigen::internal::pexp(), Eigen::internal::pfloor(), Eigen::internal::plgamma(), Eigen::half_impl::pow(), Eigen::internal::pround(), Eigen::internal::psin(), Eigen::internal::ptan(), Eigen::internal::ptanh(), round(), sin(), size, packet_helper< Cond, Packet >::store(), tan(), tanh(), VERIFY, and VERIFY_IS_EQUAL.
packetmath_scatter_gather()
template<typename Scalar > void packetmath_scatter_gather ()
Definition at line 579 of file packetmath.cpp.
References EIGEN_ALIGN_MAX, i, isApproxAbs(), Eigen::internal::pstore(), size, and VERIFY.
Referenced by test_packetmath().
test_conj_helper()
template<typename Scalar , bool ConjLhs, bool ConjRhs> void test_conj_helper (Scalar * data1, Scalar * data2, Scalar * ref, Scalar * pval)
Definition at line 519 of file packetmath.cpp.
References areApprox(), i, Eigen::internal::pstore(), size, and VERIFY.
test_packetmath()
void test_packetmath ()
Definition at line 616 of file packetmath.cpp.
References i, packetmath(), packetmath_complex(), and packetmath_scatter_gather().
Variable Documentation
g_vectorize_sse
const bool g_vectorize_sse = false
Definition at line 22 of file packetmath.cpp.