pairinteraction: /travis/libpairinteraction/eigen/test/product_small.cpp File Reference
product_small.cpp File Reference
#include "product.h"
#include <Eigen/LU>
Macros
#define EIGEN_NO_STATIC_ASSERT
Functions
template<int >
void product1x1 ()
template<typename TC , typename TA , typename TB >
const TC & ref_prod (TC &C, const TA &A, const TB &B)
template<typename T , int Rows, int Cols, int Depth, int OC, int OA, int OB>
internal::enable_if<!((Rows==1 &&Depth!=1 &&OA==ColMajor)||(Depth==1 &&Rows !=1 &&OA==RowMajor)||(Cols==1 &&Depth!=1 &&OB==RowMajor)||(Depth==1 &&Cols !=1 &&OB==ColMajor)||(Rows==1 &&Cols !=1 &&OC==ColMajor)||(Cols==1 &&Rows !=1 &&OC==RowMajor)), void >::type test_lazy_single (int rows, int cols, int depth)
template<typename T , int Rows, int Cols, int Depth, int OC, int OA, int OB>
internal::enable_if<((Rows==1 &&Depth!=1 &&OA==ColMajor)||(Depth==1 &&Rows !=1 &&OA==RowMajor)||(Cols==1 &&Depth!=1 &&OB==RowMajor)||(Depth==1 &&Cols !=1 &&OB==ColMajor)||(Rows==1 &&Cols !=1 &&OC==ColMajor)||(Cols==1 &&Rows !=1 &&OC==RowMajor)), void >::type test_lazy_single (int, int, int)
template<typename T , int Rows, int Cols, int Depth>
void test_lazy_all_layout (int rows=Rows, int cols=Cols, int depth=Depth)
template<typename T >
void test_lazy_l1 ()
template<typename T >
void test_lazy_l2 ()
template<typename T >
void test_lazy_l3 ()
template<typename T , int N, int M, int K>
void test_linear_but_not_vectorizable ()
template<int Rows>
void bug_1311 ()
void test_product_small ()
Macro Definition Documentation
EIGEN_NO_STATIC_ASSERT
#define EIGEN_NO_STATIC_ASSERT
Definition at line 10 of file product_small.cpp.
Function Documentation
bug_1311()
template<int Rows> void bug_1311 ()
Definition at line 214 of file product_small.cpp.
References b, res, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom(), and VERIFY_IS_APPROX.
product1x1()
template<int > void product1x1 ()
Definition at line 16 of file product_small.cpp.
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom(), mpfr::sum(), and VERIFY_IS_APPROX.
ref_prod()
template<typename TC , typename TA , typename TB > const TC& ref_prod (TC & C, const TA & A, const TB & B)
Definition at line 34 of file product_small.cpp.
References Eigen::ColMajor, i, j, and Eigen::RowMajor.
Referenced by test_lazy_single().
test_lazy_all_layout()
template<typename T , int Rows, int Cols, int Depth> void test_lazy_all_layout (int rows = Rows, int cols = Cols, int depth = Depth)
Definition at line 71 of file product_small.cpp.
References CALL_SUBTEST.
test_lazy_l1()
template<typename T > void test_lazy_l1 ()
Definition at line 84 of file product_small.cpp.
References CALL_SUBTEST.
test_lazy_l2()
template<typename T > void test_lazy_l2 ()
Definition at line 113 of file product_small.cpp.
References CALL_SUBTEST.
test_lazy_l3()
template<typename T > void test_lazy_l3 ()
Definition at line 149 of file product_small.cpp.
References CALL_SUBTEST.
test_lazy_single() [1/2]
template<typename T , int Rows, int Cols, int Depth, int OC, int OA, int OB> internal::enable_if<! ((Rows ==1&&Depth!=1&&OA==ColMajor) || (Depth==1&&Rows !=1&&OA==RowMajor) || (Cols ==1&&Depth!=1&&OB==RowMajor) || (Depth==1&&Cols !=1&&OB==ColMajor) || (Rows ==1&&Cols !=1&&OC==ColMajor) || (Cols ==1&&Rows !=1&&OC==RowMajor)),void>::type test_lazy_single (int rows, int cols, int depth)
Definition at line 50 of file product_small.cpp.
References Eigen::ColMajor, D, ref_prod(), Eigen::RowMajor, Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom(), and VERIFY_IS_APPROX.
test_lazy_single() [2/2]
template<typename T , int Rows, int Cols, int Depth, int OC, int OA, int OB> internal::enable_if< ((Rows ==1&&Depth!=1&&OA==ColMajor) || (Depth==1&&Rows !=1&&OA==RowMajor) || (Cols ==1&&Depth!=1&&OB==RowMajor) || (Depth==1&&Cols !=1&&OB==ColMajor) || (Rows ==1&&Cols !=1&&OC==ColMajor) || (Cols ==1&&Rows !=1&&OC==RowMajor)),void>::type test_lazy_single (int , int , int)
Definition at line 66 of file product_small.cpp.
test_linear_but_not_vectorizable()
template<typename T , int N, int M, int K> void test_linear_but_not_vectorizable ()
Definition at line 182 of file product_small.cpp.
References n.
test_product_small()
void test_product_small ()
Definition at line 231 of file product_small.cpp.
References i.