pairinteraction: /travis/libpairinteraction/eigen/test/product.h File Reference
product.h File Reference
#include "main.h"
#include <Eigen/QR>
Functions
template<typename Derived1 , typename Derived2 >
bool areNotApprox (const MatrixBase< Derived1 > &m1, const MatrixBase< Derived2 > &m2, typename Derived1::RealScalar epsilon=NumTraits< typename Derived1::RealScalar >::dummy_precision())
template<typename MatrixType >
void product (const MatrixType &m)
Function Documentation
areNotApprox()
template<typename Derived1 , typename Derived2 > bool areNotApprox (const MatrixBase< Derived1 > & m1, const MatrixBase< Derived2 > & m2, typename Derived1::RealScalar epsilon = NumTraits<typename Derived1::RealScalar>::dummy_precision())
Definition at line 14 of file product.h.
References cwiseAbs2(), Eigen::MatrixBase< Derived >::cwiseAbs2(), m2(), and max.
Referenced by product().
product()
template<typename MatrixType > void product (const MatrixType & m)
Definition at line 20 of file product.h.
References areNotApprox(), c, Eigen::ColMajor, cols, conjugate(), eval(), i, m1, m2(), min, res, Eigen::RowMajor, Eigen::RowMajorBit, rows, square(), mpfr::sum(), v1(), VERIFY, VERIFY_IS_APPROX, VERIFY_RAISES_ASSERT, x, and y.
Referenced by binaryExpr(), EIGEN_CWISE_BINARY_RETURN_TYPE(), SystemBase< StateTwo >::getOverlap(), Eigen::UniformScaling< _Scalar >::isApprox(), Eigen::AutoDiffScalar< _DerType >::operator/(), and Eigen::SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::operator=().