pairinteraction: /travis/libpairinteraction/eigen/test/qr_colpivoting.cpp File Reference
qr_colpivoting.cpp File Reference
#include "main.h"
#include <Eigen/QR>
#include <Eigen/SVD>
Functions
template<typename MatrixType >
void cod ()
template<typename MatrixType , int Cols2>
void cod_fixedsize ()
template<typename MatrixType >
void qr ()
template<typename MatrixType , int Cols2>
void qr_fixedsize ()
template<typename MatrixType >
void qr_kahan_matrix ()
template<typename MatrixType >
void qr_invertible ()
template<typename MatrixType >
void qr_verify_assert ()
void test_qr_colpivoting ()
Function Documentation
cod()
template<typename MatrixType > void cod ()
Definition at line 16 of file qr_colpivoting.cpp.
References c, cols, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::colsPermutation(), Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::createRandomPIMatrixOfRank(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::dimensionOfKernel(), EIGEN_TEST_MAX_SIZE, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::householderQ(), Eigen::PermutationBase< Derived >::inverse(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInjective(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInvertible(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isSurjective(), matrix(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixT(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixZ(), min, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::pseudoInverse(), Eigen::numext::q, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rank(), rows, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::solve(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::solve(), svd(), VERIFY, VERIFY_IS_APPROX, and VERIFY_IS_UNITARY.
Referenced by bench(), and cod_fixedsize().
cod_fixedsize()
template<typename MatrixType , int Cols2> void cod_fixedsize ()
Definition at line 66 of file qr_colpivoting.cpp.
References cod(), Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::createRandomPIMatrixOfRank(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::dimensionOfKernel(), int(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInjective(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInvertible(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isSurjective(), matrix(), min, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rank(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::solve(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::solve(), svd(), VERIFY, and VERIFY_IS_APPROX.
qr()
template<typename MatrixType > void qr ()
Definition at line 94 of file qr_colpivoting.cpp.
References abs(), c, cols, Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::ColPivHouseholderQR< _MatrixType >::compute(), Eigen::createRandomPIMatrixOfRank(), Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), EIGEN_TEST_MAX_SIZE, Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), i, Eigen::PermutationBase< Derived >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), j, m1, m2(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), min, Eigen::numext::q, Eigen::ColPivHouseholderQR< _MatrixType >::rank(), rows, size, Eigen::ColPivHouseholderQR< _MatrixType >::solve(), sqrt(), boost::multiprecision::test_isApproxOrLessThan(), VERIFY, VERIFY_IS_APPROX, VERIFY_IS_APPROX_OR_LESS_THAN, VERIFY_IS_EQUAL, VERIFY_IS_UNITARY, x, and y.
Referenced by qr_fixedsize(), qr_invertible(), qr_kahan_matrix(), and qr_verify_assert().
qr_fixedsize()
template<typename MatrixType , int Cols2> void qr_fixedsize ()
Definition at line 158 of file qr_colpivoting.cpp.
References abs(), c, Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::createRandomPIMatrixOfRank(), Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), i, int(), Eigen::PermutationBase< Derived >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), j, m1, m2(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), min, qr(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), Eigen::ColPivHouseholderQR< _MatrixType >::solve(), sqrt(), boost::multiprecision::test_isApproxOrLessThan(), VERIFY_IS_APPROX, VERIFY_IS_APPROX_OR_LESS_THAN, VERIFY_IS_EQUAL, x, and y.
qr_invertible()
template<typename MatrixType > void qr_invertible ()
Definition at line 251 of file qr_colpivoting.cpp.
References a, abs(), Eigen::ColPivHouseholderQR< _MatrixType >::absDeterminant(), Eigen::ColPivHouseholderQR< _MatrixType >::compute(), Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), i, log(), Eigen::ColPivHouseholderQR< _MatrixType >::logAbsDeterminant(), m1, m2(), qr(), size, Eigen::ColPivHouseholderQR< _MatrixType >::solve(), and VERIFY_IS_APPROX.
qr_kahan_matrix()
template<typename MatrixType > void qr_kahan_matrix ()
Definition at line 210 of file qr_colpivoting.cpp.
References abs(), c, cols, eval(), i, j, m1, Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), min, Eigen::half_impl::pow(), qr(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), rows, s, sqrt(), boost::multiprecision::test_isApproxOrLessThan(), VERIFY_IS_APPROX_OR_LESS_THAN, x, and y.
qr_verify_assert()
template<typename MatrixType > void qr_verify_assert ()
Definition at line 286 of file qr_colpivoting.cpp.
References Eigen::ColPivHouseholderQR< _MatrixType >::absDeterminant(), Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), Eigen::ColPivHouseholderQR< _MatrixType >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), Eigen::ColPivHouseholderQR< _MatrixType >::logAbsDeterminant(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), qr(), Eigen::ColPivHouseholderQR< _MatrixType >::solve(), and VERIFY_RAISES_ASSERT.
test_qr_colpivoting()
void test_qr_colpivoting ()
Definition at line 303 of file qr_colpivoting.cpp.
References i.