pairinteraction: /travis/libpairinteraction/eigen/test/qtvector.cpp File Reference
qtvector.cpp File Reference
#include "main.h"
#include <QtCore/QVector>
#include <Eigen/Geometry>
#include <Eigen/QtAlignedMalloc>
Macros
#define EIGEN_WORK_AROUND_QT_BUG_CALLING_WRONG_OPERATOR_NEW_FIXED_IN_QT_4_5
Functions
template<typename MatrixType >
void check_qtvector_matrix (const MatrixType &m)
template<typename TransformType >
void check_qtvector_transform (const TransformType &)
template<typename QuaternionType >
void check_qtvector_quaternion (const QuaternionType &)
void test_qtvector ()
Macro Definition Documentation
EIGEN_WORK_AROUND_QT_BUG_CALLING_WRONG_OPERATOR_NEW_FIXED_IN_QT_4_5
#define EIGEN_WORK_AROUND_QT_BUG_CALLING_WRONG_OPERATOR_NEW_FIXED_IN_QT_4_5
Definition at line 11 of file qtvector.cpp.
Function Documentation
check_qtvector_matrix()
template<typename MatrixType > void check_qtvector_matrix (const MatrixType & m)
Definition at line 19 of file qtvector.cpp.
References cols, i, rows, v, VERIFY, VERIFY_IS_APPROX, w, x, and y.
Referenced by test_qtvector().
check_qtvector_quaternion()
template<typename QuaternionType > void check_qtvector_quaternion (const QuaternionType &)
Definition at line 96 of file qtvector.cpp.
References i, int(), v, VERIFY, VERIFY_IS_APPROX, w, x, and y.
Referenced by test_qtvector().
check_qtvector_transform()
template<typename TransformType > void check_qtvector_transform (const TransformType &)
Definition at line 61 of file qtvector.cpp.
References i, int(), matrix(), v, VERIFY, VERIFY_IS_APPROX, w, x, and y.
Referenced by test_qtvector().
test_qtvector()
void test_qtvector ()
Definition at line 130 of file qtvector.cpp.
References CALL_SUBTEST, check_qtvector_matrix(), check_qtvector_quaternion(), and check_qtvector_transform().