pairinteraction: /travis/libpairinteraction/eigen/test/real_qz.cpp File Reference
real_qz.cpp File Reference
#include "main.h"
#include <limits>
#include <Eigen/Eigenvalues>
Macros
#define EIGEN_RUNTIME_NO_MALLOC
Functions
template<typename MatrixType >
void real_qz (const MatrixType &m)
void test_real_qz ()
Macro Definition Documentation
EIGEN_RUNTIME_NO_MALLOC
#define EIGEN_RUNTIME_NO_MALLOC
Definition at line 10 of file real_qz.cpp.
Function Documentation
real_qz()
template<typename MatrixType > void real_qz (const MatrixType & m)
Definition at line 15 of file real_qz.cpp.
References abs(), Eigen::RealQZ< _MatrixType >::compute(), mpfr::dim(), i, Eigen::RealQZ< _MatrixType >::info(), j, Eigen::RealQZ< _MatrixType >::matrixQ(), Eigen::RealQZ< _MatrixType >::matrixS(), Eigen::RealQZ< _MatrixType >::matrixT(), Eigen::RealQZ< _MatrixType >::matrixZ(), qz(), Eigen::PlainObjectBase< Derived >::setZero(), Eigen::Success, VERIFY_IS_APPROX, and VERIFY_IS_EQUAL.
test_real_qz()
void test_real_qz ()
Definition at line 79 of file real_qz.cpp.
References i, and s.