pairinteraction: /travis/libpairinteraction/eigen/test/ref.cpp File Reference
ref.cpp File Reference
#include "main.h"
Macros
#define TEST_ENABLE_TEMPORARY_TRACKING
Typedefs
typedef Matrix< double, Dynamic, Dynamic, RowMajor > RowMatrixXd
Functions
template<typename MatrixType >
void ref_matrix (const MatrixType &m)
template<typename VectorType >
void ref_vector (const VectorType &m)
template<typename PlainObjectType >
void check_const_correctness (const PlainObjectType &)
template<typename B >
EIGEN_DONT_INLINE void call_ref_1 (Ref< VectorXf > a, const B &b)
template<typename B >
EIGEN_DONT_INLINE void call_ref_2 (const Ref< const VectorXf > &a, const B &b)
template<typename B >
EIGEN_DONT_INLINE void call_ref_3 (Ref< VectorXf, 0, InnerStride<> > a, const B &b)
template<typename B >
EIGEN_DONT_INLINE void call_ref_4 (const Ref< const VectorXf, 0, InnerStride<> > &a, const B &b)
template<typename B >
EIGEN_DONT_INLINE void call_ref_5 (Ref< MatrixXf, 0, OuterStride<> > a, const B &b)
template<typename B >
EIGEN_DONT_INLINE void call_ref_6 (const Ref< const MatrixXf, 0, OuterStride<> > &a, const B &b)
template<typename B >
EIGEN_DONT_INLINE void call_ref_7 (Ref< Matrix< float, Dynamic, 3 > > a, const B &b)
void call_ref ()
int test_ref_overload_fun1 (Ref< MatrixXd >)
int test_ref_overload_fun1 (Ref< RowMatrixXd >)
int test_ref_overload_fun1 (Ref< MatrixXf >)
int test_ref_overload_fun2 (Ref< const MatrixXd >)
int test_ref_overload_fun2 (Ref< const MatrixXf >)
void test_ref_ambiguous (const Ref< const ArrayXd > &A, Ref< ArrayXd > B)
void test_ref_overloads ()
void test_ref ()
Macro Definition Documentation
TEST_ENABLE_TEMPORARY_TRACKING
#define TEST_ENABLE_TEMPORARY_TRACKING
Definition at line 15 of file ref.cpp.
Typedef Documentation
RowMatrixXd
typedef Matrix<double,Dynamic,Dynamic,RowMajor> RowMatrixXd
Definition at line 227 of file ref.cpp.
Function Documentation
call_ref()
void call_ref ()
Definition at line 167 of file ref.cpp.
References a, b, c, call_ref_1(), call_ref_2(), call_ref_3(), call_ref_4(), call_ref_5(), call_ref_6(), call_ref_7(), and VERIFY_EVALUATION_COUNT.
call_ref_1()
template<typename B > EIGEN_DONT_INLINE void call_ref_1 (Ref< VectorXf > a, const B & b)
Definition at line 153 of file ref.cpp.
References VERIFY_IS_EQUAL.
Referenced by call_ref().
call_ref_2()
template<typename B > EIGEN_DONT_INLINE void call_ref_2 (const Ref< const VectorXf > & a, const B & b)
Definition at line 155 of file ref.cpp.
References VERIFY_IS_EQUAL.
Referenced by call_ref().
call_ref_3()
template<typename B > EIGEN_DONT_INLINE void call_ref_3 (Ref< VectorXf, 0, InnerStride<> > a, const B & b)
Definition at line 157 of file ref.cpp.
References a, and VERIFY_IS_EQUAL.
Referenced by call_ref().
call_ref_4()
template<typename B > EIGEN_DONT_INLINE void call_ref_4 (const Ref< const VectorXf, 0, InnerStride<> > & a, const B & b)
Definition at line 159 of file ref.cpp.
References a, and VERIFY_IS_EQUAL.
Referenced by call_ref().
call_ref_5()
template<typename B > EIGEN_DONT_INLINE void call_ref_5 (Ref< MatrixXf, 0, OuterStride<> > a, const B & b)
Definition at line 161 of file ref.cpp.
References a, and VERIFY_IS_EQUAL.
Referenced by call_ref().
call_ref_6()
template<typename B > EIGEN_DONT_INLINE void call_ref_6 (const Ref< const MatrixXf, 0, OuterStride<> > & a, const B & b)
Definition at line 163 of file ref.cpp.
References a, and VERIFY_IS_EQUAL.
Referenced by call_ref().
call_ref_7()
template<typename B > EIGEN_DONT_INLINE void call_ref_7 (Ref< Matrix< float, Dynamic, 3 > > a, const B & b)
Definition at line 165 of file ref.cpp.
References a, and VERIFY_IS_EQUAL.
Referenced by call_ref().
check_const_correctness()
template<typename PlainObjectType > void check_const_correctness (const PlainObjectType &)
Definition at line 142 of file ref.cpp.
References Eigen::LvalueBit, and VERIFY.
ref_matrix()
template<typename MatrixType > void ref_matrix (const MatrixType & m)
Definition at line 33 of file ref.cpp.
References cols, i, j, m1, m2(), rows, and VERIFY_IS_EQUAL.
ref_vector()
template<typename VectorType > void ref_vector (const VectorType & m)
Definition at line 81 of file ref.cpp.
References i, mat1(), size, v1(), v2(), VERIFY_IS_APPROX, and VERIFY_IS_EQUAL.
test_ref()
void test_ref ()
Definition at line 258 of file ref.cpp.
References i.
test_ref_ambiguous()
void test_ref_ambiguous (const Ref< const ArrayXd > & A, Ref< ArrayXd > B)
Definition at line 235 of file ref.cpp.
Referenced by test_ref_overloads().
test_ref_overload_fun1() [1/3]
int test_ref_overload_fun1 (Ref< MatrixXd >)
Definition at line 228 of file ref.cpp.
Referenced by test_ref_overloads().
test_ref_overload_fun1() [2/3]
int test_ref_overload_fun1 (Ref< RowMatrixXd >)
Definition at line 229 of file ref.cpp.
test_ref_overload_fun1() [3/3]
int test_ref_overload_fun1 (Ref< MatrixXf >)
Definition at line 230 of file ref.cpp.
test_ref_overload_fun2() [1/2]
int test_ref_overload_fun2 (Ref< const MatrixXd >)
Definition at line 232 of file ref.cpp.
Referenced by test_ref_overloads().
test_ref_overload_fun2() [2/2]
int test_ref_overload_fun2 (Ref< const MatrixXf >)
Definition at line 233 of file ref.cpp.
test_ref_overloads()
void test_ref_overloads ()
Definition at line 242 of file ref.cpp.
References test_ref_ambiguous(), test_ref_overload_fun1(), test_ref_overload_fun2(), and VERIFY.