pairinteraction: /travis/libpairinteraction/eigen/blas/testing/sblat2.f File Reference
sblat2.f File Reference
Functions/Subroutines
program sblat2
SBLAT2
subroutine schk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine schk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine schk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, XT, G, Z)
subroutine schk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine schk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine schk6 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine schke (ISNUM, SRNAMT, NOUT)
subroutine smake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, KL, KU, RESET, TRANSL)
subroutine smvch (TRANS, M, N, ALPHA, A, NMAX, X, INCX, BETA, Y, INCY, YT, G, YY, EPS, ERR, FATAL, NOUT, MV)
logical function lse (RI, RJ, LR)
logical function lseres (TYPE, UPLO, M, N, AA, AS, LDA)
real function sbeg (RESET)
real function sdiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 3096 of file sblat2.f.
lse()
logical function lse (real, dimension(*) RI, real, dimension(*) RJ, integer LR)
Definition at line 2945 of file sblat2.f.
Referenced by lse().
lseres()
logical function lseres (character*2 TYPE, character*1 UPLO, integer M, integer N, real, dimension(lda, *) AA, real, dimension(lda, *) AS, integer LDA)
Definition at line 2975 of file sblat2.f.
Referenced by lseres().
sbeg()
real function sbeg (logical RESET)
Definition at line 3034 of file sblat2.f.
Referenced by sbeg().
sblat2()
program sblat2 ()
SBLAT2
Purpose:
 Test program for the REAL Level 2 Blas.
 The program must be driven by a short data file. The first 18 records
 of the file are read using list-directed input, the last 16 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 34 lines:
 'sblat2.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'SBLAT2.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 4                 NUMBER OF VALUES OF K
 0 1 2 4           VALUES OF K
 4                 NUMBER OF VALUES OF INCX AND INCY
 1 2 -1 -2         VALUES OF INCX AND INCY
 3                 NUMBER OF VALUES OF ALPHA
 0.0 1.0 0.7       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 0.0 1.0 0.9       VALUES OF BETA
 SGEMV  T PUT F FOR NO TEST. SAME COLUMNS.
 SGBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 SSYMV  T PUT F FOR NO TEST. SAME COLUMNS.
 SSBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 SSPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 STRMV  T PUT F FOR NO TEST. SAME COLUMNS.
 STBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 STPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 STRSV  T PUT F FOR NO TEST. SAME COLUMNS.
 STBSV  T PUT F FOR NO TEST. SAME COLUMNS.
 STPSV  T PUT F FOR NO TEST. SAME COLUMNS.
 SGER   T PUT F FOR NO TEST. SAME COLUMNS.
 SSYR   T PUT F FOR NO TEST. SAME COLUMNS.
 SSPR   T PUT F FOR NO TEST. SAME COLUMNS.
 SSYR2  T PUT F FOR NO TEST. SAME COLUMNS.
 SSPR2  T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
    See:
       Dongarra J. J., Du Croz J. J., Hammarling S.  and Hanson R. J..
       An  extended  set of Fortran  Basic Linear Algebra Subprograms.
       Technical  Memoranda  Nos. 41 (revision 3) and 81,  Mathematics
       and  Computer Science  Division,  Argonne  National Laboratory,
       9700 South Cass Avenue, Argonne, Illinois 60439, US.
       Or
       NAG  Technical Reports TR3/87 and TR4/87,  Numerical Algorithms
       Group  Ltd.,  NAG  Central  Office,  256  Banbury  Road, Oxford
       OX2 7DE, UK,  and  Numerical Algorithms Group Inc.,  1101  31st
       Street,  Suite 100,  Downers Grove,  Illinois 60515-1263,  USA.
 -- Written on 10-August-1987.
    Richard Hanson, Sandia National Labs.
    Jeremy Du Croz, NAG Central Office.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 103 of file sblat2.f.
References abs, max, min, p, schk1(), schk2(), schk3(), schk4(), schk5(), schk6(), schke(), smvch(), x, and y.
schk1()
subroutine schk1 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, real, dimension(nalf) ALF, integer NBET, real, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax) X, real, dimension(nmax*incmax) XX, real, dimension(nmax*incmax) XS, real, dimension(nmax) Y, real, dimension(nmax*incmax) YY, real, dimension(nmax*incmax) YS, real, dimension(nmax) YT, real, dimension(nmax) G)
Definition at line 434 of file sblat2.f.
References abs, lda, m, max, min, n, sgbmv(), sgemv(), smake(), smvch(), x, and y.
Referenced by sblat2(), and sblat3().
schk2()
subroutine schk2 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, real, dimension(nalf) ALF, integer NBET, real, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax) X, real, dimension(nmax*incmax) XX, real, dimension(nmax*incmax) XS, real, dimension(nmax) Y, real, dimension(nmax*incmax) YY, real, dimension(nmax*incmax) YS, real, dimension(nmax) YT, real, dimension(nmax) G)
Definition at line 775 of file sblat2.f.
References abs, lda, max, n, smake(), smvch(), ssbmv(), sspmv(), ssymv(), x, and y.
Referenced by sblat2(), and sblat3().
schk3()
subroutine schk3 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax) X, real, dimension(nmax*incmax) XX, real, dimension(nmax*incmax) XS, real, dimension(nmax) XT, real, dimension(nmax) G, real, dimension(nmax) Z)
Definition at line 1117 of file sblat2.f.
References abs, lda, max, n, smake(), smvch(), stbmv(), stbsv(), stpmv(), stpsv(), strmv(), strsv(), and x.
Referenced by sblat2(), and sblat3().
schk4()
subroutine schk4 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax) X, real, dimension(nmax*incmax) XX, real, dimension(nmax*incmax) XS, real, dimension(nmax) Y, real, dimension(nmax*incmax) YY, real, dimension(nmax*incmax) YS, real, dimension(nmax) YT, real, dimension(nmax) G, real, dimension(nmax) Z)
Definition at line 1475 of file sblat2.f.
References abs, j, lda, m, max, min, n, sger(), smake(), smvch(), x, and y.
Referenced by sblat2(), and sblat3().
schk5()
subroutine schk5 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax) X, real, dimension(nmax*incmax) XX, real, dimension(nmax*incmax) XS, real, dimension(nmax) Y, real, dimension(nmax*incmax) YY, real, dimension(nmax*incmax) YS, real, dimension(nmax) YT, real, dimension(nmax) G, real, dimension(nmax) Z)
Definition at line 1736 of file sblat2.f.
References abs, lda, max, n, smake(), smvch(), sspr(), ssyr(), x, and y.
Referenced by sblat2(), and sblat3().
schk6()
subroutine schk6 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax) X, real, dimension(nmax*incmax) XX, real, dimension(nmax*incmax) XS, real, dimension(nmax) Y, real, dimension(nmax*incmax) YY, real, dimension(nmax*incmax) YS, real, dimension(nmax) YT, real, dimension(nmax) G, real, dimension(nmax, 2) Z)
Definition at line 2014 of file sblat2.f.
References abs, j, lda, max, n, smake(), smvch(), sspr2(), ssyr2(), x, and y.
Referenced by sblat2().
schke()
subroutine schke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 2326 of file sblat2.f.
References chkxer(), sgbmv(), sgemv(), sger(), ssbmv(), sspmv(), sspr(), sspr2(), ssymv(), ssyr(), ssyr2(), stbmv(), stbsv(), stpmv(), stpsv(), strmv(), and strsv().
Referenced by sblat2(), and sblat3().
sdiff()
real function sdiff (real X, real Y)
Definition at line 3080 of file sblat2.f.
References sdiff().
smake()
subroutine smake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, real, dimension(nmax, *) A, integer NMAX, real, dimension(*) AA, integer LDA, integer KL, integer KU, logical RESET, real TRANSL)
Definition at line 2653 of file sblat2.f.
References max, and min.
Referenced by schk1(), schk2(), schk3(), schk4(), schk5(), and schk6().
smvch()
subroutine smvch (character*1 TRANS, integer M, integer N, real ALPHA, real, dimension(nmax, *) A, integer NMAX, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY, real, dimension(*) YT, real, dimension(*) G, real, dimension(*) YY, real EPS, real ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 2829 of file sblat2.f.
References abs, max, and sqrt().
Referenced by sblat2(), schk1(), schk2(), schk3(), schk4(), schk5(), and schk6().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 3124 of file sblat2.f.