pairinteraction: /travis/libpairinteraction/eigen/blas/testing/sblat1.f File Reference
sblat1.f File Reference
Functions/Subroutines
program sblat1
SBLAT1
subroutine header
subroutine check0 (SFAC)
subroutine check1 (SFAC)
subroutine check2 (SFAC)
subroutine check3 (SFAC)
subroutine stest (LEN, SCOMP, STRUE, SSIZE, SFAC)
subroutine stest1 (SCOMP1, STRUE1, SSIZE, SFAC)
real function sdiff (SA, SB)
subroutine itest1 (ICOMP, ITRUE)
Function/Subroutine Documentation
check0()
subroutine check0 (real SFAC)
Definition at line 127 of file sblat1.f.
References a, b, c, e(), j, srotg(), srotmg(), stest(), and stest1().
check1()
subroutine check1 (real SFAC)
Definition at line 243 of file sblat1.f.
References itest1(), max, sscal(), stest(), and stest1().
check2()
subroutine check2 (real SFAC)
Definition at line 337 of file sblat1.f.
References a, abs, b, c, e(), m, min, saxpy(), scopy(), srotm(), sswap(), stest(), and stest1().
check3()
subroutine check3 (real SFAC)
Definition at line 685 of file sblat1.f.
References abs, min, srot(), and stest().
header()
subroutine header ()
Definition at line 96 of file sblat1.f.
References x.
itest1()
subroutine itest1 (integer ICOMP, integer ITRUE)
Definition at line 982 of file sblat1.f.
References x.
sblat1()
program sblat1 ()
SBLAT1
Purpose:
    Test program for the REAL Level 1 BLAS.
    Based upon the original BLAS test routine together with:
    F06EAF Example Program Text
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 38 of file sblat1.f.
References check0(), check1(), check2(), check3(), e(), header(), and x.
sdiff()
real function sdiff (real SA, real SB)
Definition at line 972 of file sblat1.f.
References sdiff().
stest()
subroutine stest (integer LEN, real, dimension(len) SCOMP, real, dimension(len) STRUE, real, dimension(len) SSIZE, real SFAC)
Definition at line 891 of file sblat1.f.
References abs, and x.
stest1()
subroutine stest1 (real SCOMP1, real STRUE1, real, dimension(*) SSIZE, real SFAC)
Definition at line 947 of file sblat1.f.
References stest().