pairinteraction: /travis/libpairinteraction/eigen/blas/testing/sblat3.f File Reference
sblat3.f File Reference
Functions/Subroutines
program sblat3
SBLAT3
subroutine schk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine schk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine schk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NMAX, A, AA, AS, B, BB, BS, CT, G, C)
subroutine schk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine schk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, AB, AA, AS, BB, BS, C, CC, CS, CT, G, W)
subroutine schke (ISNUM, SRNAMT, NOUT)
subroutine smake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, RESET, TRANSL)
subroutine smmch (TRANSA, TRANSB, M, N, KK, ALPHA, A, LDA, B, LDB, BETA, C, LDC, CT, G, CC, LDCC, EPS, ERR, FATAL, NOUT, MV)
logical function lse (RI, RJ, LR)
logical function lseres (TYPE, UPLO, M, N, AA, AS, LDA)
real function sbeg (RESET)
real function sdiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 2789 of file sblat3.f.
lse()
logical function lse (real, dimension(*) RI, real, dimension(*) RJ, integer LR)
Definition at line 2631 of file sblat3.f.
References lse().
lseres()
logical function lseres (character*2 TYPE, character*1 UPLO, integer M, integer N, real, dimension(lda, *) AA, real, dimension(lda, *) AS, integer LDA)
Definition at line 2663 of file sblat3.f.
References lseres().
sbeg()
real function sbeg (logical RESET)
Definition at line 2724 of file sblat3.f.
References sbeg().
sblat3()
program sblat3 ()
SBLAT3
Purpose:
 Test program for the REAL             Level 3 Blas.
 The program must be driven by a short data file. The first 14 records
 of the file are read using list-directed input, the last 6 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 20 lines:
 'sblat3.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'SBLAT3.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 3                 NUMBER OF VALUES OF ALPHA
 0.0 1.0 0.7       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 0.0 1.0 1.3       VALUES OF BETA
 SGEMM  T PUT F FOR NO TEST. SAME COLUMNS.
 SSYMM  T PUT F FOR NO TEST. SAME COLUMNS.
 STRMM  T PUT F FOR NO TEST. SAME COLUMNS.
 STRSM  T PUT F FOR NO TEST. SAME COLUMNS.
 SSYRK  T PUT F FOR NO TEST. SAME COLUMNS.
 SSYR2K T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
 See:
    Dongarra J. J., Du Croz J. J., Duff I. S. and Hammarling S.
    A Set of Level 3 Basic Linear Algebra Subprograms.
    Technical Memorandum No.88 (Revision 1), Mathematics and
    Computer Science Division, Argonne National Laboratory, 9700
    South Cass Avenue, Argonne, Illinois 60439, US.
 -- Written on 8-February-1989.
    Jack Dongarra, Argonne National Laboratory.
    Iain Duff, AERE Harwell.
    Jeremy Du Croz, Numerical Algorithms Group Ltd.
    Sven Hammarling, Numerical Algorithms Group Ltd.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 83 of file sblat3.f.
References a, c, max, min, p, schk1(), schk2(), schk3(), schk4(), schk5(), schke(), smmch(), w, and x.
schk1()
subroutine schk1 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NBET, real, dimension(nbet) BET, integer NMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax, nmax) B, real, dimension(nmax*nmax) BB, real, dimension(nmax*nmax) BS, real, dimension(nmax, nmax) C, real, dimension(nmax*nmax) CC, real, dimension(nmax*nmax) CS, real, dimension(nmax) CT, real, dimension(nmax) G)
Definition at line 398 of file sblat3.f.
References b, c, lda, m, max, n, sgemm(), smake(), smmch(), and x.
schk2()
subroutine schk2 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NBET, real, dimension(nbet) BET, integer NMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax, nmax) B, real, dimension(nmax*nmax) BB, real, dimension(nmax*nmax) BS, real, dimension(nmax, nmax) C, real, dimension(nmax*nmax) CC, real, dimension(nmax*nmax) CS, real, dimension(nmax) CT, real, dimension(nmax) G)
Definition at line 679 of file sblat3.f.
References b, c, lda, m, max, n, smake(), smmch(), ssymm(), and x.
schk3()
subroutine schk3 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax, nmax) B, real, dimension(nmax*nmax) BB, real, dimension(nmax*nmax) BS, real, dimension(nmax) CT, real, dimension(nmax) G, real, dimension(nmax, nmax) C)
Definition at line 949 of file sblat3.f.
References b, c, lda, m, max, n, smake(), smmch(), strmm(), strsm(), and x.
schk4()
subroutine schk4 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NBET, real, dimension(nbet) BET, integer NMAX, real, dimension(nmax, nmax) A, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax, nmax) B, real, dimension(nmax*nmax) BB, real, dimension(nmax*nmax) BS, real, dimension(nmax, nmax) C, real, dimension(nmax*nmax) CC, real, dimension(nmax*nmax) CS, real, dimension(nmax) CT, real, dimension(nmax) G)
Definition at line 1254 of file sblat3.f.
References b, c, lda, max, n, smake(), smmch(), ssyrk(), and x.
schk5()
subroutine schk5 (character*6 SNAME, real EPS, real THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, real, dimension(nalf) ALF, integer NBET, real, dimension(nbet) BET, integer NMAX, real, dimension(2*nmax*nmax) AB, real, dimension(nmax*nmax) AA, real, dimension(nmax*nmax) AS, real, dimension(nmax*nmax) BB, real, dimension(nmax*nmax) BS, real, dimension(nmax, nmax) C, real, dimension(nmax*nmax) CC, real, dimension(nmax*nmax) CS, real, dimension(nmax) CT, real, dimension(nmax) G, real, dimension(2*nmax) W)
Definition at line 1529 of file sblat3.f.
References c, lda, max, n, smake(), smmch(), ssyr2k(), w, and x.
schke()
subroutine schke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 1841 of file sblat3.f.
References chkxer(), sgemm(), ssymm(), ssyr2k(), ssyrk(), strmm(), and strsm().
sdiff()
real function sdiff (real X, real Y)
Definition at line 2770 of file sblat3.f.
References sdiff().
smake()
subroutine smake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, real, dimension(nmax, *) A, integer NMAX, real, dimension(*) AA, integer LDA, logical RESET, real TRANSL)
Definition at line 2397 of file sblat3.f.
smmch()
subroutine smmch (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer KK, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC, real, dimension(*) CT, real, dimension(*) G, real, dimension(ldcc, *) CC, integer LDCC, real EPS, real ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 2511 of file sblat3.f.
References abs, max, sqrt(), and x.
Referenced by sblat3(), schk1(), schk2(), schk3(), schk4(), and schk5().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 2819 of file sblat3.f.