pairinteraction: /travis/libpairinteraction/eigen/lapack/second_NONE.f File Reference
second_NONE.f File Reference
Functions/Subroutines
real function second ()
SECOND returns nothing
Function/Subroutine Documentation
second()
real function second ()
SECOND returns nothing
Purpose:
  SECOND returns nothing instead of returning the user time for a process in seconds.
  If you are using that routine, it means that neither EXTERNAL ETIME,
  EXTERNAL ETIME_, INTERNAL ETIME, INTERNAL CPU_TIME is available  on
  your machine.
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
November 2011
Definition at line 39 of file second_NONE.f.
References e().
Referenced by Eigen::choose(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::data(), Eigen::internal::pblend(), Eigen::internal::predux_max< Packet2d >(), Eigen::IndexPair< Idx >::set(), and Eigen::TensorContractionEvaluatorBase< TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType >, Device > >::TensorContractionEvaluatorBase().