pairinteraction: /travis/libpairinteraction/eigen/lapack/slarf.f File Reference
slarf.f File Reference
Functions/Subroutines
subroutine slarf (SIDE, M, N, V, INCV, TAU, C, LDC, WORK)
SLARF
Function/Subroutine Documentation
slarf()
subroutine slarf (character SIDE, integer M, integer N, real, dimension(*) V, integer INCV, real TAU, real, dimension(ldc, *) C, integer LDC, real, dimension(*) WORK)
SLARF
Download SLARF + dependencies [TGZ] [ZIP] [TXT]
Purpose:
 SLARF applies a real elementary reflector H to a real m by n matrix
 C, from either the left or the right. H is represented in the form
       H = I - tau * v * v**T
 where tau is a real scalar and v is a real vector.
 If tau = 0, then H is taken to be the unit matrix.
Parameters
[in] SIDE
          SIDE is CHARACTER*1
          = 'L': form  H * C
          = 'R': form  C * H
[in] M
          M is INTEGER
          The number of rows of the matrix C.
[in] N
          N is INTEGER
          The number of columns of the matrix C.
[in] V
          V is REAL array, dimension
                     (1 + (M-1)*abs(INCV)) if SIDE = 'L'
                  or (1 + (N-1)*abs(INCV)) if SIDE = 'R'
          The vector v in the representation of H. V is not used if
          TAU = 0.
[in] INCV
          INCV is INTEGER
          The increment between elements of v. INCV <> 0.
[in] TAU
          TAU is REAL
          The value tau in the representation of H.
[in,out] C
          C is REAL array, dimension (LDC,N)
          On entry, the m by n matrix C.
          On exit, C is overwritten by the matrix H * C if SIDE = 'L',
          or C * H if SIDE = 'R'.
[in] LDC
          LDC is INTEGER
          The leading dimension of the array C. LDC >= max(1,M).
[out] WORK
          WORK is REAL array, dimension
                         (N) if SIDE = 'L'
                      or (M) if SIDE = 'R'
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
November 2011
Definition at line 126 of file slarf.f.
References e(), sgemv(), and sger().