pairinteraction: /travis/libpairinteraction/eigen/bench/btl/data/smooth.cxx File Reference
smooth.cxx File Reference
#include "utilities.h"
#include <vector>
#include <deque>
#include <string>
#include <iostream>
#include <fstream>
#include "bench_parameter.hh"
#include <set>
Functions
void read_xy_file (const string &filename, vector< int > &tab_sizes, vector< double > &tab_mflops)
void write_xy_file (const string &filename, vector< int > &tab_sizes, vector< double > &tab_mflops)
void smooth_curve (const vector< double > &tab_mflops, vector< double > &smooth_tab_mflops, int window_half_width)
void centered_smooth_curve (const vector< double > &tab_mflops, vector< double > &smooth_tab_mflops, int window_half_width)
int main (int argc, char *argv[])
template<class VECTOR >
double weighted_mean (const VECTOR &data)
Function Documentation
centered_smooth_curve()
void centered_smooth_curve (const vector< double > & tab_mflops, vector< double > & smooth_tab_mflops, int window_half_width)
Definition at line 125 of file smooth.cxx.
References i, j, size, and weighted_mean().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 38 of file smooth.cxx.
References centered_smooth_curve(), relicense::filename, INFOS, read_xy_file(), and write_xy_file().
read_xy_file()
void read_xy_file (const string & filename, vector< int > & tab_sizes, vector< double > & tab_mflops)
Definition at line 176 of file smooth.cxx.
References INFOS, SCRUTE, and size.
Referenced by main().
smooth_curve()
void smooth_curve (const vector< double > & tab_mflops, vector< double > & smooth_tab_mflops, int window_half_width)
Definition at line 100 of file smooth.cxx.
References i, j, size, and weighted_mean().
weighted_mean()
template<class VECTOR > double weighted_mean (const VECTOR & data)
Definition at line 79 of file smooth.cxx.
References i.
Referenced by centered_smooth_curve(), and smooth_curve().
write_xy_file()
void write_xy_file (const string & filename, vector< int > & tab_sizes, vector< double > & tab_mflops)
Definition at line 160 of file smooth.cxx.
References i.
Referenced by main().