pairinteraction: /travis/libpairinteraction/eigen/test/sparse_solvers.cpp File Reference
sparse_solvers.cpp File Reference
#include "sparse.h"
Functions
template<typename Scalar >
void initSPD (double density, Matrix< Scalar, Dynamic, Dynamic > &refMat, SparseMatrix< Scalar > &sparseMat)
template<typename Scalar >
void sparse_solvers (int rows, int cols)
void test_sparse_solvers ()
Function Documentation
initSPD()
template<typename Scalar > void initSPD (double density, Matrix< Scalar, Dynamic, Dynamic > & refMat, SparseMatrix< Scalar > & sparseMat)
Definition at line 13 of file sparse_solvers.cpp.
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::PlainObjectBase< Derived >::cols(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), ForceNonZeroDiag, i, initSparse(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), j, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero().
sparse_solvers()
template<typename Scalar > void sparse_solvers (int rows, int cols)
Definition at line 33 of file sparse_solvers.cpp.
References ForceNonZeroDiag, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), m2(), MakeLowerTriangular, MakeUpperTriangular, matB(), max, Eigen::SparseCompressedBase< Derived >::nonZeros(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), triangularView< Lower >(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr(), vec1(), and VERIFY_IS_APPROX.
test_sparse_solvers()
void test_sparse_solvers ()
Definition at line 104 of file sparse_solvers.cpp.
References i.