pairinteraction: /travis/libpairinteraction/eigen/test/sparse_vector.cpp File Reference
sparse_vector.cpp File Reference
#include "sparse.h"
Functions
template<typename Scalar , typename StorageIndex >
void sparse_vector (int rows, int cols)
void test_sparse_vector ()
Function Documentation
sparse_vector()
template<typename Scalar , typename StorageIndex > void sparse_vector (int rows, int cols)
Definition at line 12 of file sparse_vector.cpp.
References Eigen::PlainObjectBase< Derived >::coeffRef(), e(), i, j, m1, max, rows, v, v1(), v2(), vec1(), VERIFY, VERIFY_IS_APPROX, and VERIFY_IS_MUCH_SMALLER_THAN.
test_sparse_vector()
void test_sparse_vector ()
Definition at line 148 of file sparse_vector.cpp.
References i.