pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/sparse_extra.cpp File Reference
sparse_extra.cpp File Reference
#include "sparse_basic.cpp"
#include "sparse_product.cpp"
#include <Eigen/SparseExtra>
Macros
#define EIGEN_NO_DEPRECATED_WARNING
Functions
template<typename SetterType , typename DenseType , typename Scalar , int Options>
bool test_random_setter (SparseMatrix< Scalar, Options > &sm, const DenseType &ref, const std::vector< Vector2i > &nonzeroCoords)
template<typename SetterType , typename DenseType , typename T >
bool test_random_setter (DynamicSparseMatrix< T > &sm, const DenseType &ref, const std::vector< Vector2i > &nonzeroCoords)
template<typename SparseMatrixType >
void sparse_extra (const SparseMatrixType &ref)
void test_sparse_extra ()
Macro Definition Documentation
EIGEN_NO_DEPRECATED_WARNING
#define EIGEN_NO_DEPRECATED_WARNING
Definition at line 12 of file sparse_extra.cpp.
Function Documentation
sparse_extra()
template<typename SparseMatrixType > void sparse_extra (const SparseMatrixType & ref)
Definition at line 50 of file sparse_extra.cpp.
References cols, e(), i, int(), m, max, rows, test_random_setter(), vec1(), VERIFY, VERIFY_IS_APPROX, VERIFY_IS_MUCH_SMALLER_THAN, VERIFY_RAISES_ASSERT, x, and y.
test_random_setter() [1/2]
template<typename SetterType , typename DenseType , typename Scalar , int Options> bool test_random_setter (SparseMatrix< Scalar, Options > & sm, const DenseType & ref, const std::vector< Vector2i > & nonzeroCoords)
Definition at line 18 of file sparse_extra.cpp.
References i, Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::isApprox(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), w, x, and y.
Referenced by sparse_extra().
test_random_setter() [2/2]
template<typename SetterType , typename DenseType , typename T > bool test_random_setter (DynamicSparseMatrix< T > & sm, const DenseType & ref, const std::vector< Vector2i > & nonzeroCoords)
Definition at line 36 of file sparse_extra.cpp.
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), i, Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::isApprox(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), x, and y.
test_sparse_extra()
void test_sparse_extra ()
Definition at line 132 of file sparse_extra.cpp.
References i.