pairinteraction: /travis/libpairinteraction/eigen/test/sparseqr.cpp File Reference
sparseqr.cpp File Reference
#include "sparse.h"
#include <Eigen/SparseQR>
Functions
template<typename MatrixType , typename DenseMat >
int generate_sparse_rectangular_problem (MatrixType &A, DenseMat &dA, int maxRows=300, int maxCols=150)
template<typename Scalar >
void test_sparseqr_scalar ()
void test_sparseqr ()
Function Documentation
generate_sparse_rectangular_problem()
template<typename MatrixType , typename DenseMat > int generate_sparse_rectangular_problem (MatrixType & A, DenseMat & dA, int maxRows = 300, int maxCols = 150)
Definition at line 13 of file sparseqr.cpp.
References cols, eigen_assert, ForceNonZeroDiag, max, rows, and s.
Referenced by test_sparseqr_scalar().
test_sparseqr()
void test_sparseqr ()
Definition at line 98 of file sparseqr.cpp.
References i.
test_sparseqr_scalar()
template<typename Scalar > void test_sparseqr_scalar ()
Definition at line 44 of file sparseqr.cpp.
References b, Eigen::SparseQR< _MatrixType, _OrderingType >::compute(), generate_sparse_rectangular_problem(), solver, and x.