pairinteraction: /travis/libpairinteraction/eigen/test/sparse_basic.cpp File Reference
sparse_basic.cpp File Reference
#include "sparse.h"
Macros
#define EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN g_realloc_count++;
Functions
template<typename SparseMatrixType >
void sparse_basic (const SparseMatrixType &ref)
template<typename SparseMatrixType >
void big_sparse_triplet (Index rows, Index cols, double density)
void test_sparse_basic ()
Macro Definition Documentation
EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN
#define EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN g_realloc_count++;
Definition at line 13 of file sparse_basic.cpp.
Referenced by Eigen::internal::CompressedStorage< Scalar, StorageIndex >::reallocate().
Function Documentation
big_sparse_triplet()
template<typename SparseMatrixType > void big_sparse_triplet (Index rows, Index cols, double density)
Definition at line 619 of file sparse_basic.cpp.
References c, cols, i, m, mpfr::sum(), v, VERIFY, and VERIFY_IS_APPROX.
sparse_basic()
template<typename SparseMatrixType > void sparse_basic (const SparseMatrixType & ref)
Definition at line 17 of file sparse_basic.cpp.
References cols, e(), i, int(), m, m1, m2(), max, rows, Eigen::PlainObjectBase< Derived >::setZero(), vec1(), VERIFY_IS_APPROX, VERIFY_IS_MUCH_SMALLER_THAN, VERIFY_RAISES_ASSERT, x, and y.
test_sparse_basic()
void test_sparse_basic ()
Definition at line 644 of file sparse_basic.cpp.
References i.