pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/SparseMatrix_coeffs.cpp File Reference
SparseMatrix_coeffs.cpp File Reference
Functions
SparseMatrix< double > A (3, 3)
A insert (1, 2)=0
A insert (0, 1)
A insert (2, 0)
A makeCompressed ()
Function Documentation
A()
SparseMatrix<double> A (3 , 3)
insert() [1/3]
A insert (1 , 2) pure virtual
Referenced by Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex >::blockPtr(), Eigen::SparseMatrix< scalar_t >::coeffRef(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fillrand(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::fillrand(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), and Eigen::SparseMatrix< scalar_t >::insertByOuterInner().
insert() [2/3]
A insert (0 , 1)
insert() [3/3]
A insert (2 , 0)
makeCompressed()
A makeCompressed ()
Referenced by Eigen::SparseMatrix< scalar_t >::prune().