pairinteraction: /travis/libpairinteraction/eigen/test/stable_norm.cpp File Reference
stable_norm.cpp File Reference
#include "main.h"
Functions
template<typename T >
EIGEN_DONT_INLINE T copy (const T &x)
template<typename MatrixType >
void stable_norm (const MatrixType &m)
void test_stable_norm ()
Function Documentation
copy()
template<typename T > EIGEN_DONT_INLINE T copy (const T & x)
Definition at line 12 of file stable_norm.cpp.
References x.
Referenced by stable_norm().
stable_norm()
template<typename MatrixType > void stable_norm (const MatrixType & m)
Definition at line 17 of file stable_norm.cpp.
References abs(), abs2(), cols, copy(), e(), eval(), i, isfinite, isnan, Eigen::isPlusInf(), j, max, min, Eigen::internal::radix(), rows, size, sqrt(), v, VERIFY, VERIFY_IS_APPROX, VERIFY_IS_MUCH_SMALLER_THAN, and VERIFY_IS_NOT_APPROX.
test_stable_norm()
void test_stable_norm ()
Definition at line 183 of file stable_norm.cpp.
References i.