pairinteraction: /travis/libpairinteraction/eigen/test/stdlist.cpp File Reference
stdlist.cpp File Reference
#include "main.h"
#include <Eigen/StdList>
#include <Eigen/Geometry>
Functions
template<typename MatrixType >
void check_stdlist_matrix (const MatrixType &m)
template<typename TransformType >
void check_stdlist_transform (const TransformType &)
template<typename QuaternionType >
void check_stdlist_quaternion (const QuaternionType &)
void test_stdlist ()
Function Documentation
check_stdlist_matrix()
template<typename MatrixType > void check_stdlist_matrix (const MatrixType & m)
Definition at line 16 of file stdlist.cpp.
References cols, i, rows, v, VERIFY_IS_APPROX, w, x, and y.
Referenced by test_stdlist().
check_stdlist_quaternion()
template<typename QuaternionType > void check_stdlist_quaternion (const QuaternionType &)
Definition at line 77 of file stdlist.cpp.
References i, v, VERIFY_IS_APPROX, w, x, and y.
Referenced by test_stdlist().
check_stdlist_transform()
template<typename TransformType > void check_stdlist_transform (const TransformType &)
Definition at line 48 of file stdlist.cpp.
References i, v, VERIFY_IS_APPROX, w, x, and y.
Referenced by test_stdlist().
test_stdlist()
void test_stdlist ()
Definition at line 105 of file stdlist.cpp.
References check_stdlist_matrix(), check_stdlist_quaternion(), and check_stdlist_transform().