pairinteraction: Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape > Struct Template Reference
Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
enum { StorageOrder = int(Lhs::Flags) & RowMajorBit ? RowMajor : ColMajor }
typedef diagonal_product_evaluator_base< Lhs, typename Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight > Base
typedef Base::Scalar Scalar
typedef Product< Lhs, Rhs, ProductKind > XprType
typedef XprType::PlainObject PlainObject
Public Types inherited from Eigen::internal::diagonal_product_evaluator_base< Lhs, Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight >
enum
typedef ScalarBinaryOpTraits< typename Lhs ::Scalar, typename Rhs::DiagonalVectorType ::Scalar >::ReturnType Scalar
Public Types inherited from Eigen::internal::evaluator_base< Product< Lhs, Rhs, LazyProduct > >
enum
typedef traits< Product< Lhs, Rhs, LazyProduct > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC product_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index idx) const
Public Member Functions inherited from Eigen::internal::diagonal_product_evaluator_base< Lhs, Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight >
diagonal_product_evaluator_base (const Lhs &mat, const Rhs::DiagonalVectorType &diag)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index idx) const
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::diagonal_product_evaluator_base< Lhs, Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight >
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::true_type) const
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::false_type) const
Protected Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Protected Attributes inherited from Eigen::internal::diagonal_product_evaluator_base< Lhs, Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight >
evaluator< Rhs::DiagonalVectorType > m_diagImpl
evaluator< Lhs > m_matImpl
Detailed Description
template<typename Lhs, typename Rhs, int ProductKind, int ProductTag>
struct Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >
Definition at line 874 of file ProductEvaluators.h.
Member Typedef Documentation
Base
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef diagonal_product_evaluator_base<Lhs, typename Rhs::DiagonalVectorType, Product<Lhs, Rhs, LazyProduct>, OnTheRight> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::Base
Definition at line 877 of file ProductEvaluators.h.
PlainObject
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef XprType::PlainObject Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::PlainObject
Definition at line 884 of file ProductEvaluators.h.
Scalar
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Base::Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::Scalar
Definition at line 881 of file ProductEvaluators.h.
XprType
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Product<Lhs, Rhs, ProductKind> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::XprType
Definition at line 883 of file ProductEvaluators.h.
Member Enumeration Documentation
anonymous enum
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> anonymous enum
Enumerator
StorageOrder
Definition at line 886 of file ProductEvaluators.h.
Constructor & Destructor Documentation
product_evaluator()
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::product_evaluator (const XprType & xpr) inline explicit
Definition at line 888 of file ProductEvaluators.h.
Member Function Documentation
coeff()
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::coeff (Index row, Index col) const inline
Definition at line 893 of file ProductEvaluators.h.
packet() [1/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet (Index row, Index col) const inline
Definition at line 900 of file ProductEvaluators.h.
References col(), and row().
packet() [2/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet (Index idx) const inline
Definition at line 907 of file ProductEvaluators.h.
References Eigen::ColMajor, and int().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ProductEvaluators.h