pairinteraction: TestFunc1< _Scalar, NX, NY > Struct Template Reference
TestFunc1< _Scalar, NX, NY > Struct Template Reference
Public Types
enum { InputsAtCompileTime = NX, ValuesAtCompileTime = NY }
enum { InputsAtCompileTime = NX, ValuesAtCompileTime = NY }
typedef _Scalar Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef _Scalar Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Member Functions
TestFunc1 ()
TestFunc1 (int inputs, int values)
int inputs () const
int values () const
template<typename T >
void operator() (const Matrix< T, InputsAtCompileTime, 1 > &x, Matrix< T, ValuesAtCompileTime, 1 > *_v) const
void operator() (const InputType &x, ValueType *v, JacobianType *_j) const
TestFunc1 ()
TestFunc1 (int inputs, int values)
int inputs () const
int values () const
template<typename T >
void operator() (const Matrix< T, InputsAtCompileTime, 1 > &x, Matrix< T, ValuesAtCompileTime, 1 > *_v) const
void operator() (const InputType &x, ValueType *v, JacobianType *_j) const
Data Fields
int m_inputs
int m_values
Detailed Description
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic>
struct TestFunc1< _Scalar, NX, NY >
Definition at line 33 of file autodiff.cpp.
Member Typedef Documentation
InputType [1/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,InputsAtCompileTime,1> TestFunc1< _Scalar, NX, NY >::InputType
Definition at line 31 of file forward_adolc.cpp.
InputType [2/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,InputsAtCompileTime,1> TestFunc1< _Scalar, NX, NY >::InputType
Definition at line 40 of file autodiff.cpp.
JacobianType [1/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,InputsAtCompileTime> TestFunc1< _Scalar, NX, NY >::JacobianType
Definition at line 33 of file forward_adolc.cpp.
JacobianType [2/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,InputsAtCompileTime> TestFunc1< _Scalar, NX, NY >::JacobianType
Definition at line 42 of file autodiff.cpp.
Scalar [1/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef _Scalar TestFunc1< _Scalar, NX, NY >::Scalar
Definition at line 26 of file forward_adolc.cpp.
Scalar [2/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef _Scalar TestFunc1< _Scalar, NX, NY >::Scalar
Definition at line 35 of file autodiff.cpp.
ValueType [1/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,1> TestFunc1< _Scalar, NX, NY >::ValueType
Definition at line 32 of file forward_adolc.cpp.
ValueType [2/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,1> TestFunc1< _Scalar, NX, NY >::ValueType
Definition at line 41 of file autodiff.cpp.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> anonymous enum
Enumerator
InputsAtCompileTime
ValuesAtCompileTime
Definition at line 36 of file autodiff.cpp.
anonymous enum
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> anonymous enum
Enumerator
InputsAtCompileTime
ValuesAtCompileTime
Definition at line 27 of file forward_adolc.cpp.
Constructor & Destructor Documentation
TestFunc1() [1/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> TestFunc1< _Scalar, NX, NY >::TestFunc1 () inline
Definition at line 46 of file autodiff.cpp.
TestFunc1() [2/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> TestFunc1< _Scalar, NX, NY >::TestFunc1 (int inputs, int values) inline
Definition at line 47 of file autodiff.cpp.
TestFunc1() [3/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> TestFunc1< _Scalar, NX, NY >::TestFunc1 () inline
Definition at line 37 of file forward_adolc.cpp.
TestFunc1() [4/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> TestFunc1< _Scalar, NX, NY >::TestFunc1 (int inputs, int values) inline
Definition at line 38 of file forward_adolc.cpp.
Member Function Documentation
inputs() [1/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> int TestFunc1< _Scalar, NX, NY >::inputs () const inline
Definition at line 40 of file forward_adolc.cpp.
References TestFunc1< _Scalar, NX, NY >::m_inputs.
inputs() [2/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> int TestFunc1< _Scalar, NX, NY >::inputs () const inline
Definition at line 49 of file autodiff.cpp.
Referenced by TestFunc1< _Scalar, NX, NY >::operator()().
operator()() [1/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> template<typename T > void TestFunc1< _Scalar, NX, NY >::operator() (const Matrix< T, InputsAtCompileTime, 1 > & x, Matrix< T, ValuesAtCompileTime, 1 > * _v) const inline
Definition at line 44 of file forward_adolc.cpp.
References TestFunc1< _Scalar, NX, NY >::inputs(), v, and TestFunc1< _Scalar, NX, NY >::values().
operator()() [2/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> template<typename T > void TestFunc1< _Scalar, NX, NY >::operator() (const Matrix< T, InputsAtCompileTime, 1 > & x, Matrix< T, ValuesAtCompileTime, 1 > * _v) const inline
Definition at line 53 of file autodiff.cpp.
References v.
operator()() [3/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> void TestFunc1< _Scalar, NX, NY >::operator() (const InputType & x, ValueType * v, JacobianType * _j) const inline
Definition at line 63 of file forward_adolc.cpp.
References TestFunc1< _Scalar, NX, NY >::inputs(), j, v, TestFunc1< _Scalar, NX, NY >::values(), and x.
operator()() [4/4]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> void TestFunc1< _Scalar, NX, NY >::operator() (const InputType & x, ValueType * v, JacobianType * _j) const inline
Definition at line 72 of file autodiff.cpp.
References j, v, and x.
values() [1/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> int TestFunc1< _Scalar, NX, NY >::values () const inline
Definition at line 41 of file forward_adolc.cpp.
References TestFunc1< _Scalar, NX, NY >::m_values.
values() [2/2]
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> int TestFunc1< _Scalar, NX, NY >::values () const inline
Definition at line 50 of file autodiff.cpp.
Referenced by TestFunc1< _Scalar, NX, NY >::operator()().
Field Documentation
m_inputs
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> int TestFunc1< _Scalar, NX, NY >::m_inputs
Definition at line 44 of file autodiff.cpp.
Referenced by TestFunc1< _Scalar, NX, NY >::inputs().
m_values
template<typename _Scalar , int NX = Dynamic, int NY = Dynamic> int TestFunc1< _Scalar, NX, NY >::m_values
Definition at line 44 of file autodiff.cpp.
Referenced by TestFunc1< _Scalar, NX, NY >::values().
The documentation for this struct was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/test/autodiff.cpp
/travis/libpairinteraction/eigen/unsupported/test/forward_adolc.cpp