pairinteraction: Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device > Struct Template Reference
#include <TensorCustomOp.h>
Public Types
enum {
IsAligned = false, PacketAccess = (internal::packet_traits<Scalar>::size > 1), BlockAccess = false, Layout = TensorEvaluator<LhsXprType, Device>::Layout,
CoordAccess = false, RawAccess = false
}
typedef TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType > XprType
typedef internal::traits< XprType >::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef internal::remove_const< typename XprType::CoeffReturnType >::type CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (CoeffReturnType *data)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC CoeffReturnType * data () const
Static Public Attributes
static const int NumDims = internal::traits<XprType>::NumDimensions
static const int PacketSize = internal::unpacket_traits<PacketReturnType>::size
Protected Member Functions
EIGEN_DEVICE_FUNC void evalTo (Scalar *data)
Protected Attributes
Dimensions m_dimensions
const XprType m_op
const Device & m_device
CoeffReturnType * m_result
Detailed Description
template<typename CustomBinaryFunc, typename LhsXprType, typename RhsXprType, typename Device>
struct Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >
Definition at line 236 of file TensorCustomOp.h.
Member Typedef Documentation
CoeffReturnType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef internal::remove_const<typename XprType::CoeffReturnType>::type Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::CoeffReturnType
Definition at line 243 of file TensorCustomOp.h.
Dimensions
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Dimensions
Definition at line 241 of file TensorCustomOp.h.
Index
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef internal::traits<XprType>::Index Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Index
Definition at line 239 of file TensorCustomOp.h.
PacketReturnType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::PacketReturnType
Definition at line 244 of file TensorCustomOp.h.
Scalar
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Scalar
Definition at line 242 of file TensorCustomOp.h.
XprType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef TensorCustomBinaryOp<CustomBinaryFunc, LhsXprType, RhsXprType> Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::XprType
Definition at line 238 of file TensorCustomOp.h.
Member Enumeration Documentation
anonymous enum
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
Layout
CoordAccess
RawAccess
Definition at line 247 of file TensorCustomOp.h.
Constructor & Destructor Documentation
TensorEvaluator()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
Definition at line 256 of file TensorCustomOp.h.
References Eigen::TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >::func(), Eigen::TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >::lhsExpression(), and Eigen::TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >::rhsExpression().
Member Function Documentation
cleanup()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::cleanup () inline
Definition at line 275 of file TensorCustomOp.h.
coeff()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::coeff (Index index) const inline
Definition at line 282 of file TensorCustomOp.h.
costPerCoeff()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::costPerCoeff (bool vectorized) const inline
Definition at line 291 of file TensorCustomOp.h.
data()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType* Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::data () const inline
Definition at line 296 of file TensorCustomOp.h.
dimensions()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::dimensions () const inline
Definition at line 262 of file TensorCustomOp.h.
evalSubExprsIfNeeded()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalSubExprsIfNeeded (CoeffReturnType * data) inline
Definition at line 264 of file TensorCustomOp.h.
evalTo()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC void Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalTo (Scalar * data) inline protected
Definition at line 299 of file TensorCustomOp.h.
packet()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::packet (Index index) const inline
Definition at line 287 of file TensorCustomOp.h.
Field Documentation
m_device
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > const Device& Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_device protected
Definition at line 306 of file TensorCustomOp.h.
m_dimensions
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_dimensions protected
Definition at line 304 of file TensorCustomOp.h.
m_op
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > const XprType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_op protected
Definition at line 305 of file TensorCustomOp.h.
m_result
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > CoeffReturnType* Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_result protected
Definition at line 307 of file TensorCustomOp.h.
NumDims
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > const int Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::NumDims = internal::traits<XprType>::NumDimensions static
Definition at line 240 of file TensorCustomOp.h.
PacketSize
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > const int Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::PacketSize = internal::unpacket_traits<PacketReturnType>::size static
Definition at line 245 of file TensorCustomOp.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorCustomOp.h