pairinteraction: Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape > Struct Template Reference
Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef nested_eval< ExpressionType, 1 >::type MatrixType
typedef remove_all< MatrixType >::type MatrixTypeCleaned
Static Public Member Functions
template<typename Dest , typename TranspositionType >
static void run (Dest &dst, const TranspositionType &tr, const ExpressionType &xpr)
Detailed Description
template<typename ExpressionType, int Side, bool Transposed, typename ExpressionShape>
struct Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >
Definition at line 1035 of file ProductEvaluators.h.
Member Typedef Documentation
MatrixType
template<typename ExpressionType , int Side, bool Transposed, typename ExpressionShape > typedef nested_eval<ExpressionType, 1>::type Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::MatrixType
Definition at line 1037 of file ProductEvaluators.h.
MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed, typename ExpressionShape > typedef remove_all<MatrixType>::type Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::MatrixTypeCleaned
Definition at line 1038 of file ProductEvaluators.h.
Member Function Documentation
run()
template<typename ExpressionType , int Side, bool Transposed, typename ExpressionShape > template<typename Dest , typename TranspositionType > static void Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::run (Dest & dst, const TranspositionType & tr, const ExpressionType & xpr) inline static
Definition at line 1041 of file ProductEvaluators.h.
References Eigen::internal::is_same_dense(), j, mat, Eigen::OnTheLeft, Eigen::OnTheRight, and size.
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, TranspositionsShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, MatrixShape, TranspositionsShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Transpose< Lhs >, Rhs, TranspositionsShape, MatrixShape, ProductTag >::evalTo(), and Eigen::internal::generic_product_impl< Lhs, Transpose< Rhs >, MatrixShape, TranspositionsShape, ProductTag >::evalTo().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ProductEvaluators.h