pairinteraction: Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version > Struct Template Reference
Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version > Struct Template Reference
#include <TriangularMatrixMatrix.h>
Public Types
enum { SmallPanelWidth = EIGEN_PLAIN_ENUM_MAX(Traits::mr,Traits::nr), IsLower = (Mode&Lower) == Lower, SetDiag = (Mode&(ZeroDiag|UnitDiag)) ? 0 : 1 }
typedef gebp_traits< Scalar, Scalar > Traits
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index _rows, Index _cols, Index _depth, const Scalar *_lhs, Index lhsStride, const Scalar *_rhs, Index rhsStride, Scalar *res, Index resStride, const Scalar &alpha, level3_blocking< Scalar, Scalar > &blocking)
Detailed Description
template<typename Scalar, typename Index, int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version>
struct Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >
Definition at line 233 of file TriangularMatrixMatrix.h.
Member Typedef Documentation
Traits
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> typedef gebp_traits<Scalar,Scalar> Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::Traits
Definition at line 237 of file TriangularMatrixMatrix.h.
Member Enumeration Documentation
anonymous enum
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> anonymous enum
Enumerator
SmallPanelWidth
IsLower
SetDiag
Definition at line 238 of file TriangularMatrixMatrix.h.
Member Function Documentation
run()
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> EIGEN_DONT_INLINE void Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run (Index _rows, Index _cols, Index _depth, const Scalar * _lhs, Index lhsStride, const Scalar * _rhs, Index rhsStride, Scalar * res, Index resStride, const Scalar & alpha, level3_blocking< Scalar, Scalar > & blocking) static
Definition at line 257 of file TriangularMatrixMatrix.h.
References alpha, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), cols, ei_declare_aligned_stack_constructed_variable, EIGEN_MAX_ALIGN_BYTES, j, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), min, res, rows, and Eigen::ZeroDiag.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h