pairinteraction: Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false > Struct Template Reference
Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false > Struct Template Reference
#include <Transform.h>
Public Types
enum { ResultMode = transform_product_result<LhsMode,RhsMode>::Mode }
typedef Transform< Scalar, Dim, LhsMode, LhsOptions > Lhs
typedef Transform< Scalar, Dim, RhsMode, RhsOptions > Rhs
typedef Transform< Scalar, Dim, ResultMode, LhsOptions > ResultType
Static Public Member Functions
static ResultType run (const Lhs &lhs, const Rhs &rhs)
Detailed Description
template<typename Scalar, int Dim, int LhsMode, int LhsOptions, int RhsMode, int RhsOptions>
struct Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >
Definition at line 1481 of file Transform.h.
Member Typedef Documentation
Lhs
template<typename Scalar , int Dim, int LhsMode, int LhsOptions, int RhsMode, int RhsOptions> typedef Transform<Scalar,Dim,LhsMode,LhsOptions> Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::Lhs
Definition at line 1484 of file Transform.h.
ResultType
template<typename Scalar , int Dim, int LhsMode, int LhsOptions, int RhsMode, int RhsOptions> typedef Transform<Scalar,Dim,ResultMode,LhsOptions> Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::ResultType
Definition at line 1486 of file Transform.h.
Rhs
template<typename Scalar , int Dim, int LhsMode, int LhsOptions, int RhsMode, int RhsOptions> typedef Transform<Scalar,Dim,RhsMode,RhsOptions> Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::Rhs
Definition at line 1485 of file Transform.h.
Member Enumeration Documentation
anonymous enum
template<typename Scalar , int Dim, int LhsMode, int LhsOptions, int RhsMode, int RhsOptions> anonymous enum
Enumerator
ResultMode
Definition at line 1483 of file Transform.h.
Member Function Documentation
run()
template<typename Scalar , int Dim, int LhsMode, int LhsOptions, int RhsMode, int RhsOptions> static ResultType Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run (const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 1487 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::makeAffine(), res, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Geometry/Transform.h