pairinteraction: Functor< _Scalar, NX, NY > Struct Template Reference
Functor< _Scalar, NX, NY > Struct Template Reference
Public Types
enum { InputsAtCompileTime = NX, ValuesAtCompileTime = NY }
enum { InputsAtCompileTime = NX, ValuesAtCompileTime = NY }
typedef _Scalar Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef _Scalar Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Member Functions
Functor ()
Functor (int inputs, int values)
int inputs () const
int values () const
Functor ()
Functor (int inputs, int values)
int inputs () const
int values () const
Data Fields
const int m_inputs
const int m_values
int m_inputs
int m_values
Detailed Description
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic>
struct Functor< _Scalar, NX, NY >
Definition at line 108 of file NonLinearOptimization.cpp.
Member Typedef Documentation
InputType [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,InputsAtCompileTime,1> Functor< _Scalar, NX, NY >::InputType
Definition at line 20 of file NumericalDiff.cpp.
InputType [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,InputsAtCompileTime,1> Functor< _Scalar, NX, NY >::InputType
Definition at line 115 of file NonLinearOptimization.cpp.
JacobianType [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,InputsAtCompileTime> Functor< _Scalar, NX, NY >::JacobianType
Definition at line 22 of file NumericalDiff.cpp.
JacobianType [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,InputsAtCompileTime> Functor< _Scalar, NX, NY >::JacobianType
Definition at line 117 of file NonLinearOptimization.cpp.
Scalar [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef _Scalar Functor< _Scalar, NX, NY >::Scalar
Definition at line 15 of file NumericalDiff.cpp.
Scalar [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef _Scalar Functor< _Scalar, NX, NY >::Scalar
Definition at line 110 of file NonLinearOptimization.cpp.
ValueType [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,1> Functor< _Scalar, NX, NY >::ValueType
Definition at line 21 of file NumericalDiff.cpp.
ValueType [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar,ValuesAtCompileTime,1> Functor< _Scalar, NX, NY >::ValueType
Definition at line 116 of file NonLinearOptimization.cpp.
Member Enumeration Documentation
anonymous enum
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> anonymous enum
Enumerator
InputsAtCompileTime
ValuesAtCompileTime
Definition at line 111 of file NonLinearOptimization.cpp.
anonymous enum
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> anonymous enum
Enumerator
InputsAtCompileTime
ValuesAtCompileTime
Definition at line 16 of file NumericalDiff.cpp.
Constructor & Destructor Documentation
Functor() [1/4]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> Functor< _Scalar, NX, NY >::Functor () inline
Definition at line 121 of file NonLinearOptimization.cpp.
Functor() [2/4]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> Functor< _Scalar, NX, NY >::Functor (int inputs, int values) inline
Definition at line 122 of file NonLinearOptimization.cpp.
Functor() [3/4]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> Functor< _Scalar, NX, NY >::Functor () inline
Definition at line 26 of file NumericalDiff.cpp.
Functor() [4/4]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> Functor< _Scalar, NX, NY >::Functor (int inputs, int values) inline
Definition at line 27 of file NumericalDiff.cpp.
Member Function Documentation
inputs() [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> int Functor< _Scalar, NX, NY >::inputs () const inline
Definition at line 29 of file NumericalDiff.cpp.
inputs() [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> int Functor< _Scalar, NX, NY >::inputs () const inline
Definition at line 124 of file NonLinearOptimization.cpp.
values() [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> int Functor< _Scalar, NX, NY >::values () const inline
Definition at line 30 of file NumericalDiff.cpp.
values() [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> int Functor< _Scalar, NX, NY >::values () const inline
Definition at line 125 of file NonLinearOptimization.cpp.
Referenced by my_functor::actual_df(), Eigen::NumericalDiff< _Functor, mode >::df(), lmder_functor::df(), my_functor::operator()(), and lmder_functor::operator()().
Field Documentation
m_inputs [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> int Functor< _Scalar, NX, NY >::m_inputs
Definition at line 24 of file NumericalDiff.cpp.
m_inputs [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> const int Functor< _Scalar, NX, NY >::m_inputs
Definition at line 119 of file NonLinearOptimization.cpp.
Referenced by Functor< double >::inputs().
m_values [1/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> int Functor< _Scalar, NX, NY >::m_values
Definition at line 24 of file NumericalDiff.cpp.
m_values [2/2]
template<typename _Scalar, int NX = Dynamic, int NY = Dynamic> const int Functor< _Scalar, NX, NY >::m_values
Definition at line 119 of file NonLinearOptimization.cpp.
Referenced by Functor< double >::values().
The documentation for this struct was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/test/NonLinearOptimization.cpp
/travis/libpairinteraction/eigen/unsupported/test/NumericalDiff.cpp