pairinteraction: Eigen::internal::scalar_sigmoid_op< T > Struct Template Reference
Eigen::internal::scalar_sigmoid_op< T > Struct Template Reference
#include <TensorFunctors.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T operator() (const T &x) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packetOp (const Packet &x) const
Detailed Description
template<typename T>
struct Eigen::internal::scalar_sigmoid_op< T >
Definition at line 63 of file TensorFunctors.h.
Member Function Documentation
operator()()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::scalar_sigmoid_op< T >::operator() (const T & x) const inline
Definition at line 65 of file TensorFunctors.h.
References EIGEN_STRONG_INLINE, and exp().
packetOp()
template<typename T > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_sigmoid_op< T >::packetOp (const Packet & x) const inline
Definition at line 71 of file TensorFunctors.h.
References Eigen::internal::padd(), Eigen::internal::pdiv(), Eigen::internal::pexp(), and Eigen::internal::pnegate().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorFunctors.h