pairinteraction: Eigen::Sizes< Indices > Struct Template Reference
Eigen::Sizes< Indices > Struct Template Reference
#include <TensorDimensions.h>
Public Types
typedef internal::numeric_list< std::ptrdiff_t, Indices... > Base
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::ptrdiff_t rank () const
EIGEN_DEVICE_FUNC Sizes ()
template<typename DenseIndex >
EIGEN_DEVICE_FUNC Sizes (const array< DenseIndex, Base::count > &)
template<typename T >
Sizes & operator= (const T &)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::ptrdiff_t operator[] (const std::size_t index) const
template<typename DenseIndex >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t IndexOfColMajor (const array< DenseIndex, Base::count > &indices) const
template<typename DenseIndex >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t IndexOfRowMajor (const array< DenseIndex, Base::count > &indices) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::ptrdiff_t TotalSize ()
Static Public Attributes
static const std::ptrdiff_t total_size = internal::arg_prod(Indices...)
Detailed Description
template<typename std::ptrdiff_t... Indices>
struct Eigen::Sizes< Indices >
Definition at line 93 of file TensorDimensions.h.
Member Typedef Documentation
Base
template<typename std::ptrdiff_t... Indices> typedef internal::numeric_list<std::ptrdiff_t, Indices...> Eigen::Sizes< Indices >::Base
Definition at line 94 of file TensorDimensions.h.
Constructor & Destructor Documentation
Sizes() [1/2]
template<typename std::ptrdiff_t... Indices> EIGEN_DEVICE_FUNC Eigen::Sizes< Indices >::Sizes () inline
Definition at line 105 of file TensorDimensions.h.
Sizes() [2/2]
template<typename std::ptrdiff_t... Indices> template<typename DenseIndex > EIGEN_DEVICE_FUNC Eigen::Sizes< Indices >::Sizes (const array< DenseIndex, Base::count > &) inline explicit
Definition at line 107 of file TensorDimensions.h.
Member Function Documentation
IndexOfColMajor()
template<typename std::ptrdiff_t... Indices> template<typename DenseIndex > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::Sizes< Indices >::IndexOfColMajor (const array< DenseIndex, Base::count > & indices) const inline
Definition at line 127 of file TensorDimensions.h.
References EIGEN_STRONG_INLINE, and Eigen::internal::fixed_size_tensor_index_linearization_helper< Index, NumIndices, n, RowMajor >::run().
IndexOfRowMajor()
template<typename std::ptrdiff_t... Indices> template<typename DenseIndex > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::Sizes< Indices >::IndexOfRowMajor (const array< DenseIndex, Base::count > & indices) const inline
Definition at line 131 of file TensorDimensions.h.
References Eigen::internal::fixed_size_tensor_index_linearization_helper< Index, NumIndices, n, RowMajor >::run().
operator=()
template<typename std::ptrdiff_t... Indices> template<typename T > Sizes& Eigen::Sizes< Indices >::operator= (const T &) inline
Definition at line 117 of file TensorDimensions.h.
operator[]()
template<typename std::ptrdiff_t... Indices> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::ptrdiff_t Eigen::Sizes< Indices >::operator[] (const std::size_t index) const inline
Definition at line 122 of file TensorDimensions.h.
References EIGEN_STRONG_INLINE, and Eigen::internal::fixed_size_tensor_index_extraction_helper< Index, n >::run().
rank()
template<typename std::ptrdiff_t... Indices> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::ptrdiff_t Eigen::Sizes< Indices >::rank () const inline
Definition at line 97 of file TensorDimensions.h.
TotalSize()
template<typename std::ptrdiff_t... Indices> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::ptrdiff_t Eigen::Sizes< Indices >::TotalSize () inline static
Definition at line 101 of file TensorDimensions.h.
Field Documentation
total_size
template<typename std::ptrdiff_t... Indices> const std::ptrdiff_t Eigen::Sizes< Indices >::total_size = internal::arg_prod(Indices...) static
Definition at line 95 of file TensorDimensions.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDimensions.h