pairinteraction: Eigen::TensorSycl::internal::AccessorConstructor Struct Reference
Eigen::TensorSycl::internal::AccessorConstructor Struct Reference
#include <TensorSyclExtractAccessor.h>
Static Public Member Functions
template<typename Arg >
static auto getTuple (cl::sycl::handler &cgh, Arg eval) -> decltype(ExtractAccessor< Arg >::getTuple(cgh, eval))
template<typename Arg1 , typename Arg2 >
static auto getTuple (cl::sycl::handler &cgh, Arg1 eval1, Arg2 eval2) -> decltype(utility::tuple::append(ExtractAccessor< Arg1 >::getTuple(cgh, eval1), ExtractAccessor< Arg2 >::getTuple(cgh, eval2)))
template<typename Arg1 , typename Arg2 , typename Arg3 >
static auto getTuple (cl::sycl::handler &cgh, Arg1 eval1, Arg2 eval2, Arg3 eval3) -> decltype(utility::tuple::append(ExtractAccessor< Arg1 >::getTuple(cgh, eval1), utility::tuple::append(ExtractAccessor< Arg2 >::getTuple(cgh, eval2), ExtractAccessor< Arg3 >::getTuple(cgh, eval3))))
template<cl::sycl::access::mode AcM, typename Arg >
static auto getAccessor (cl::sycl::handler &cgh, Arg eval) -> decltype(utility::tuple::make_tuple(eval.device().template get_sycl_accessor< AcM, typename Eigen::internal::remove_all< typename Arg::CoeffReturnType >::type >(eval.dimensions().TotalSize(), cgh, eval.data())))
Detailed Description
Definition at line 45 of file TensorSyclExtractAccessor.h.
Member Function Documentation
getAccessor()
template<cl::sycl::access::mode AcM, typename Arg > static auto Eigen::TensorSycl::internal::AccessorConstructor::getAccessor (cl::sycl::handler & cgh, Arg eval) -> decltype(utility::tuple::make_tuple(eval.device().template get_sycl_accessor<AcM, typename Eigen::internal::remove_all<typename Arg::CoeffReturnType>::type>(eval.dimensions().TotalSize(), cgh,eval.data()))) inline static
Definition at line 59 of file TensorSyclExtractAccessor.h.
References eval(), utility::tuple::make_tuple(), and OP.
getTuple() [1/3]
template<typename Arg > static auto Eigen::TensorSycl::internal::AccessorConstructor::getTuple (cl::sycl::handler & cgh, Arg eval) -> decltype(ExtractAccessor<Arg>::getTuple(cgh, eval)) inline static
Definition at line 46 of file TensorSyclExtractAccessor.h.
References eval().
Referenced by Eigen::TensorSycl::internal::ExtractAccessor< TensorEvaluator< const UnaryCategory< OP, RHSExpr >, Dev > >::getTuple(), Eigen::TensorSycl::internal::ExtractAccessor< TensorEvaluator< const BinaryCategory< OP, LHSExpr, RHSExpr >, Dev > >::getTuple(), Eigen::TensorSycl::internal::ExtractAccessor< TensorEvaluator< const TernaryCategory< OP, Arg1Expr, Arg2Expr, Arg3Expr >, Dev > >::getTuple(), Eigen::TensorSycl::internal::ExtractAccessor< TensorEvaluator< const TensorSelectOp< IfExpr, ThenExpr, ElseExpr >, Dev > >::getTuple(), Eigen::TensorSycl::internal::ExtractAccessor< TensorEvaluator< const TensorAssignOp< LHSExpr, RHSExpr >, Dev > >::getTuple(), and Eigen::TensorSycl::internal::ExtractAccessor< TensorEvaluator< const TensorEvalToOp< Expr >, Dev > >::getTuple().
getTuple() [2/3]
template<typename Arg1 , typename Arg2 > static auto Eigen::TensorSycl::internal::AccessorConstructor::getTuple (cl::sycl::handler & cgh, Arg1 eval1, Arg2 eval2) -> decltype(utility::tuple::append(ExtractAccessor<Arg1>::getTuple(cgh, eval1), ExtractAccessor<Arg2>::getTuple(cgh, eval2))) inline static
Definition at line 51 of file TensorSyclExtractAccessor.h.
References utility::tuple::append().
getTuple() [3/3]
template<typename Arg1 , typename Arg2 , typename Arg3 > static auto Eigen::TensorSycl::internal::AccessorConstructor::getTuple (cl::sycl::handler & cgh, Arg1 eval1, Arg2 eval2, Arg3 eval3) -> decltype(utility::tuple::append(ExtractAccessor<Arg1>::getTuple(cgh, eval1),utility::tuple::append(ExtractAccessor<Arg2>::getTuple(cgh, eval2), ExtractAccessor<Arg3>::getTuple(cgh, eval3)))) inline static
Definition at line 55 of file TensorSyclExtractAccessor.h.
References utility::tuple::append().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorSyclExtractAccessor.h