pairinteraction: Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape > Struct Template Reference
Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef nested_eval< ExpressionType, 1 >::type MatrixType
typedef remove_all< MatrixType >::type MatrixTypeCleaned
Static Public Member Functions
template<typename Dest , typename PermutationType >
static void run (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
Detailed Description
template<typename ExpressionType, int Side, bool Transposed>
struct Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >
Definition at line 927 of file ProductEvaluators.h.
Member Typedef Documentation
MatrixType
template<typename ExpressionType , int Side, bool Transposed> typedef nested_eval<ExpressionType, 1>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::MatrixType
Definition at line 929 of file ProductEvaluators.h.
MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed> typedef remove_all<MatrixType>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::MatrixTypeCleaned
Definition at line 930 of file ProductEvaluators.h.
Member Function Documentation
run()
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType > static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::run (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
Definition at line 933 of file ProductEvaluators.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), i, Eigen::internal::is_same_dense(), mat, n, Eigen::OnTheLeft, Eigen::OnTheRight, and Eigen::internal::swap().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ProductEvaluators.h