pairinteraction: Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false > Struct Template Reference
Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false > Struct Template Reference
#include <ComplexSchur.h>
Static Public Member Functions
static void run (ComplexSchur< MatrixType > &_this, const MatrixType &matrix, bool computeU)
Detailed Description
template<typename MatrixType>
struct Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >
Definition at line 365 of file ComplexSchur.h.
Member Function Documentation
run()
template<typename MatrixType > static void Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run (ComplexSchur< MatrixType > & _this, const MatrixType & matrix, bool computeU) inline static
Definition at line 367 of file ComplexSchur.h.
References Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), i, Eigen::ComplexSchur< _MatrixType >::m_hess, Eigen::ComplexSchur< _MatrixType >::m_matT, Eigen::ComplexSchur< _MatrixType >::m_matU, Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::HessenbergDecomposition< _MatrixType >::matrixH(), Eigen::HessenbergDecomposition< _MatrixType >::matrixQ(), min, Eigen::NoConvergence, Q, rot(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::Success.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Eigenvalues/ComplexSchur.h