pairinteraction: Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode > Struct Template Reference
Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef Product< Lhs, Rhs >::Scalar Scalar
Static Public Member Functions
template<typename Dst >
static EIGEN_STRONG_INLINE void evalTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void addTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void subTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
Detailed Description
template<typename Lhs, typename Rhs>
struct Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >
Definition at line 388 of file ProductEvaluators.h.
Member Typedef Documentation
Scalar
template<typename Lhs , typename Rhs > typedef Product<Lhs,Rhs>::Scalar Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::Scalar
Definition at line 390 of file ProductEvaluators.h.
Member Function Documentation
addTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::addTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 401 of file ProductEvaluators.h.
References Eigen::internal::call_assignment_no_alias().
evalTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::evalTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 393 of file ProductEvaluators.h.
References Eigen::internal::call_assignment_no_alias().
subTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::subTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 408 of file ProductEvaluators.h.
References Eigen::internal::call_assignment_no_alias().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ProductEvaluators.h