pairinteraction: Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double > Struct Template Reference
Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double > Struct Template Reference
#include <Geometry_SSE.h>
Public Types
enum { BAlignment = traits<OtherDerived>::Alignment, ResAlignment = traits<Quaternion<double> >::Alignment }
Static Public Member Functions
static Quaternion< double > run (const QuaternionBase< Derived > &_a, const QuaternionBase< OtherDerived > &_b)
Detailed Description
template<class Derived, class OtherDerived>
struct Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >
Definition at line 84 of file Geometry_SSE.h.
Member Enumeration Documentation
anonymous enum
template<class Derived , class OtherDerived > anonymous enum
Enumerator
BAlignment
ResAlignment
Definition at line 86 of file Geometry_SSE.h.
Member Function Documentation
run()
template<class Derived , class OtherDerived > static Quaternion<double> Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run (const QuaternionBase< Derived > & _a, const QuaternionBase< OtherDerived > & _b) inline static
Definition at line 91 of file Geometry_SSE.h.
References a, Eigen::QuaternionBase< Derived >::coeffs(), EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmul(), Eigen::internal::preverse(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::psub(), Eigen::internal::pxor(), res, Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::x(), and Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::z().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Geometry/arch/Geometry_SSE.h