pairinteraction: Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true > Struct Template Reference
Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
Detailed Description
template<>
struct Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >
Definition at line 216 of file Complex.h.
Member Function Documentation
pmadd() [1/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 216 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [2/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 218 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [3/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 259 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [4/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 330 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmul() [1/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 219 of file Complex.h.
References Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::pconj(), Eigen::internal::pmul(), and vec4f_swizzle1.
pmul() [2/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 221 of file Complex.h.
References Eigen::internal::pconj(), and Eigen::internal::pmul().
pmul() [3/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 262 of file Complex.h.
References a, Eigen::Aligned16, b, c, EIGEN_ALIGN16, EIGEN_ARM_PREFETCH, EIGEN_DEBUG_ALIGNED_LOAD, EIGEN_DEBUG_ALIGNED_STORE, EIGEN_DEBUG_UNALIGNED_LOAD, EIGEN_DEBUG_UNALIGNED_STORE, EIGEN_STRONG_INLINE, imag(), Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::padd(), Eigen::internal::padd< Packet1cd >(), Eigen::internal::padd< Packet2d >(), Eigen::internal::pand< Packet1cd >(), Eigen::internal::pandnot< Packet1cd >(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pdiv(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pfirst(), Eigen::internal::pfirst< Packet1cd >(), Eigen::internal::pload< Packet1cd >(), Eigen::internal::pload< Packet2d >(), Eigen::internal::ploaddup< Packet1cd >(), Eigen::internal::ploadu< Packet1cd >(), Eigen::internal::ploadu< Packet2d >(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::pmul< Packet1cd >(), Eigen::internal::pmul< Packet2d >(), Eigen::internal::pnegate(), Eigen::internal::por< Packet1cd >(), Eigen::internal::predux< Packet1cd >(), Eigen::internal::predux_mul< Packet1cd >(), Eigen::internal::preduxp< Packet1cd >(), Eigen::internal::preverse(), Eigen::internal::pset1< Packet1cd >(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::pstore(), Eigen::internal::pstoreu(), Eigen::internal::psub< Packet1cd >(), Eigen::internal::psub< Packet2d >(), Eigen::internal::ptranspose(), Eigen::internal::pxor< Packet1cd >(), res, Eigen::TensorSycl::run(), s, size, Eigen::internal::Packet2cf::v, Eigen::internal::Packet1cd::v, v1(), v2(), x, and Eigen::y.
pmul() [4/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 333 of file Complex.h.
References a, b, Eigen::internal::Packet2cf::cd, EIGEN_STRONG_INLINE, Eigen::internal::Packet1cd::Packet1cd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pdiv(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pmul(), Eigen::internal::preverse(), res, s, and x.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/arch/AltiVec/Complex.h