pairinteraction: Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version > Struct Template Reference
Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version > Struct Template Reference
#include <TriangularMatrixVector.h>
Public Types
enum { IsLower = ((Mode&Lower)==Lower), HasUnitDiag = (Mode & UnitDiag)==UnitDiag, HasZeroDiag = (Mode & ZeroDiag)==ZeroDiag }
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index _rows, Index _cols, const LhsScalar *_lhs, Index lhsStride, const RhsScalar *_rhs, Index rhsIncr, ResScalar *_res, Index resIncr, const RhsScalar &alpha)
Detailed Description
template<typename Index, int Mode, typename LhsScalar, bool ConjLhs, typename RhsScalar, bool ConjRhs, int Version>
struct Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >
Definition at line 21 of file TriangularMatrixVector.h.
Member Typedef Documentation
ResScalar
template<typename Index , int Mode, typename LhsScalar , bool ConjLhs, typename RhsScalar , bool ConjRhs, int Version> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::ResScalar
Definition at line 23 of file TriangularMatrixVector.h.
Member Enumeration Documentation
anonymous enum
template<typename Index , int Mode, typename LhsScalar , bool ConjLhs, typename RhsScalar , bool ConjRhs, int Version> anonymous enum
Enumerator
IsLower
HasUnitDiag
HasZeroDiag
Definition at line 24 of file TriangularMatrixVector.h.
Member Function Documentation
run()
template<typename Index , int Mode, typename LhsScalar , bool ConjLhs, typename RhsScalar , bool ConjRhs, int Version> EIGEN_DONT_INLINE void Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run (Index _rows, Index _cols, const LhsScalar * _lhs, Index lhsStride, const RhsScalar * _rhs, Index rhsIncr, ResScalar * _res, Index resIncr, const RhsScalar & alpha) static
Definition at line 35 of file TriangularMatrixVector.h.
References alpha, Eigen::Triplet< Scalar, StorageIndex >::col(), cols, EIGEN_TUNE_TRIANGULAR_PANEL_WIDTH, i, min, res, rows, Eigen::TensorSycl::run(), s, Eigen::SparseMatrixBase< Derived >::segment(), and size.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/products/TriangularMatrixVector.h