pairinteraction: Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true > Struct Template Reference
Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true > Struct Template Reference
#include <SparseDenseProduct.h>
Public Types
typedef internal::remove_all< SparseLhsType >::type Lhs
typedef internal::remove_all< DenseRhsType >::type Rhs
typedef internal::remove_all< DenseResType >::type Res
typedef evaluator< Lhs >::InnerIterator LhsInnerIterator
typedef evaluator< Lhs > LhsEval
Static Public Member Functions
static void run (const SparseLhsType &lhs, const DenseRhsType &rhs, DenseResType &res, const typename Res::Scalar &alpha)
static void processRow (const LhsEval &lhsEval, const DenseRhsType &rhs, DenseResType &res, const typename Res::Scalar &alpha, Index i, Index col)
Detailed Description
template<typename SparseLhsType, typename DenseRhsType, typename DenseResType>
struct Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >
Definition at line 27 of file SparseDenseProduct.h.
Member Typedef Documentation
Lhs
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef internal::remove_all<SparseLhsType>::type Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::Lhs
Definition at line 29 of file SparseDenseProduct.h.
LhsEval
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef evaluator<Lhs> Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::LhsEval
Definition at line 33 of file SparseDenseProduct.h.
LhsInnerIterator
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef evaluator<Lhs>::InnerIterator Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::LhsInnerIterator
Definition at line 32 of file SparseDenseProduct.h.
Res
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef internal::remove_all<DenseResType>::type Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::Res
Definition at line 31 of file SparseDenseProduct.h.
Rhs
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef internal::remove_all<DenseRhsType>::type Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::Rhs
Definition at line 30 of file SparseDenseProduct.h.
Member Function Documentation
processRow()
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > static void Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::processRow (const LhsEval & lhsEval, const DenseRhsType & rhs, DenseResType & res, const typename Res::Scalar & alpha, Index i, Index col) inline static
Definition at line 64 of file SparseDenseProduct.h.
References col().
run()
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > static void Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::run (const SparseLhsType & lhs, const DenseRhsType & rhs, DenseResType & res, const typename Res::Scalar & alpha) inline static
Definition at line 34 of file SparseDenseProduct.h.
References c, i, Eigen::initParallel(), n, and Eigen::nbThreads().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/SparseCore/SparseDenseProduct.h