pairinteraction: Eigen::internal::conj_helper< Packet4d, Packet2cd, false, false > Struct Template Reference
Eigen::internal::conj_helper< Packet4d, Packet2cd, false, false > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cd pmadd (const Packet4d &x, const Packet2cd &y, const Packet2cd &c) const
EIGEN_STRONG_INLINE Packet2cd pmul (const Packet4d &x, const Packet2cd &y) const
Detailed Description
template<>
struct Eigen::internal::conj_helper< Packet4d, Packet2cd, false, false >
Definition at line 403 of file Complex.h.
Member Function Documentation
pmadd()
EIGEN_STRONG_INLINE Packet2cd Eigen::internal::conj_helper< Packet4d, Packet2cd, false, false >::pmadd (const Packet4d & x, const Packet2cd & y, const Packet2cd & c) const inline
Definition at line 405 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmul()
EIGEN_STRONG_INLINE Packet2cd Eigen::internal::conj_helper< Packet4d, Packet2cd, false, false >::pmul (const Packet4d & x, const Packet2cd & y) const inline
Definition at line 408 of file Complex.h.
References Eigen::internal::pmul(), and Eigen::internal::Packet2cd::v.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/arch/AVX/Complex.h