pairinteraction: Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > Struct Template Reference
Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > Struct Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Expression type for return value of FullPivHouseholderQR::matrixQ()
#include <FullPivHouseholderQR.h>
Public Types
typedef FullPivHouseholderQR< MatrixType >::IntDiagSizeVectorType IntDiagSizeVectorType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime > WorkVectorType
Public Types inherited from Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >
typedef internal::traits< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
FullPivHouseholderQRMatrixQReturnType (const MatrixType &qr, const HCoeffsType &hCoeffs, const IntDiagSizeVectorType &rowsTranspositions)
template<typename ResultType >
void evalTo (ResultType &result) const
template<typename ResultType >
void evalTo (ResultType &result, WorkVectorType &workspace) const
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
MatrixType::Nested m_qr
HCoeffsType::Nested m_hCoeffs
IntDiagSizeVectorType::Nested m_rowsTranspositions
Detailed Description
template<typename MatrixType>
struct Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >
Expression type for return value of FullPivHouseholderQR::matrixQ()
Template Parameters
MatrixType type of underlying dense matrix
Definition at line 24 of file FullPivHouseholderQR.h.
Member Typedef Documentation
HCoeffsType
template<typename MatrixType > typedef internal::plain_diag_type<MatrixType>::type Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::HCoeffsType
Definition at line 600 of file FullPivHouseholderQR.h.
IntDiagSizeVectorType
template<typename MatrixType > typedef FullPivHouseholderQR<MatrixType>::IntDiagSizeVectorType Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::IntDiagSizeVectorType
Definition at line 599 of file FullPivHouseholderQR.h.
WorkVectorType
template<typename MatrixType > typedef Matrix<typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime> Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::WorkVectorType
Definition at line 602 of file FullPivHouseholderQR.h.
Constructor & Destructor Documentation
FullPivHouseholderQRMatrixQReturnType()
template<typename MatrixType > Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::FullPivHouseholderQRMatrixQReturnType (const MatrixType & qr, const HCoeffsType & hCoeffs, const IntDiagSizeVectorType & rowsTranspositions) inline
Definition at line 604 of file FullPivHouseholderQR.h.
Member Function Documentation
cols()
template<typename MatrixType > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::cols (void) const inline
Definition at line 641 of file FullPivHouseholderQR.h.
evalTo() [1/2]
template<typename MatrixType > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo (ResultType & result) const inline
Definition at line 613 of file FullPivHouseholderQR.h.
References rows.
evalTo() [2/2]
template<typename MatrixType > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo (ResultType & result, WorkVectorType & workspace) const inline
Definition at line 621 of file FullPivHouseholderQR.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), cols, conj(), Eigen::conj(), min, Eigen::PlainObjectBase< Derived >::resize(), rows, and size.
rows()
template<typename MatrixType > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::rows (void) const inline
Definition at line 640 of file FullPivHouseholderQR.h.
Field Documentation
m_hCoeffs
template<typename MatrixType > HCoeffsType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_hCoeffs protected
Definition at line 645 of file FullPivHouseholderQR.h.
m_qr
template<typename MatrixType > MatrixType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr protected
Definition at line 644 of file FullPivHouseholderQR.h.
m_rowsTranspositions
template<typename MatrixType > IntDiagSizeVectorType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_rowsTranspositions protected
Definition at line 646 of file FullPivHouseholderQR.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/QR/FullPivHouseholderQR.h