pairinteraction: Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > > Struct Template Reference
Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > > Struct Template Reference
#include <BlasUtil.h>
Public Types
typedef blas_traits< NestedXpr > Base
typedef CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > XprType
typedef Base::ExtractType ExtractType
Public Types inherited from Eigen::internal::blas_traits< NestedXpr >
enum
typedef traits< NestedXpr >::Scalar Scalar
typedef const NestedXpr & ExtractType
typedef NestedXpr _ExtractType
typedef conditional< bool(HasUsableDirectAccess), ExtractType, typename _ExtractType::PlainObject >::type DirectLinearAccessType
Static Public Member Functions
static ExtractType extract (const XprType &x)
static Scalar extractScalarFactor (const XprType &x)
Static Public Member Functions inherited from Eigen::internal::blas_traits< NestedXpr >
static ExtractType extract (const NestedXpr &x)
static const Scalar extractScalarFactor (const NestedXpr &)
Detailed Description
template<typename Scalar, typename NestedXpr, typename Plain>
struct Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >
Definition at line 321 of file BlasUtil.h.
Member Typedef Documentation
Base
template<typename Scalar , typename NestedXpr , typename Plain > typedef blas_traits<NestedXpr> Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::Base
Definition at line 324 of file BlasUtil.h.
ExtractType
template<typename Scalar , typename NestedXpr , typename Plain > typedef Base::ExtractType Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::ExtractType
Definition at line 326 of file BlasUtil.h.
XprType
template<typename Scalar , typename NestedXpr , typename Plain > typedef CwiseBinaryOp<scalar_product_op<Scalar>, NestedXpr, const CwiseNullaryOp<scalar_constant_op<Scalar>,Plain> > Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::XprType
Definition at line 325 of file BlasUtil.h.
Member Function Documentation
extract()
template<typename Scalar , typename NestedXpr , typename Plain > static ExtractType Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::extract (const XprType & x) inline static
Definition at line 327 of file BlasUtil.h.
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs().
extractScalarFactor()
template<typename Scalar , typename NestedXpr , typename Plain > static Scalar Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >::extractScalarFactor (const XprType & x) inline static
Definition at line 328 of file BlasUtil.h.
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs(), and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/BlasUtil.h