pairinteraction: Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device > Struct Template Reference
#include <TensorEvaluator.h>
Public Types
enum {
IsAligned = TensorEvaluator<ThenArgType, Device>::IsAligned & TensorEvaluator<ElseArgType, Device>::IsAligned, PacketAccess, Layout = TensorEvaluator<IfArgType, Device>::Layout, CoordAccess = false,
RawAccess = false
}
typedef TensorSelectOp< IfArgType, ThenArgType, ElseArgType > XprType
typedef XprType::Scalar Scalar
typedef XprType::Index Index
typedef internal::traits< XprType >::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< IfArgType, Device >::Dimensions Dimensions
Public Member Functions
EIGEN_DEVICE_FUNC TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (CoeffReturnType *)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType * data () const
const TensorEvaluator< IfArgType, Device > & cond_impl () const
required by sycl in order to extract the accessor
const TensorEvaluator< ThenArgType, Device > & then_impl () const
required by sycl in order to extract the accessor
const TensorEvaluator< ElseArgType, Device > & else_impl () const
required by sycl in order to extract the accessor
Static Public Attributes
static const int PacketSize = internal::unpacket_traits<PacketReturnType>::size
Detailed Description
template<typename IfArgType, typename ThenArgType, typename ElseArgType, typename Device>
struct Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >
Definition at line 544 of file TensorEvaluator.h.
Member Typedef Documentation
CoeffReturnType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef internal::traits<XprType>::Scalar Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::CoeffReturnType
Definition at line 570 of file TensorEvaluator.h.
Dimensions
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorEvaluator<IfArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Dimensions
Definition at line 573 of file TensorEvaluator.h.
Index
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Index
Definition at line 569 of file TensorEvaluator.h.
PacketReturnType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::PacketReturnType
Definition at line 571 of file TensorEvaluator.h.
Scalar
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Scalar
Definition at line 547 of file TensorEvaluator.h.
XprType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorSelectOp<IfArgType, ThenArgType, ElseArgType> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::XprType
Definition at line 546 of file TensorEvaluator.h.
Member Enumeration Documentation
anonymous enum
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
Layout
CoordAccess
RawAccess
Definition at line 549 of file TensorEvaluator.h.
Constructor & Destructor Documentation
TensorEvaluator()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
Definition at line 558 of file TensorEvaluator.h.
References Eigen::dimensions_match(), eigen_assert, and EIGEN_STATIC_ASSERT.
Member Function Documentation
cleanup()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::cleanup () inline
Definition at line 587 of file TensorEvaluator.h.
coeff()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::coeff (Index index) const inline
Definition at line 593 of file TensorEvaluator.h.
cond_impl()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > const TensorEvaluator<IfArgType, Device>& Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::cond_impl () const inline
required by sycl in order to extract the accessor
Definition at line 618 of file TensorEvaluator.h.
costPerCoeff()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::costPerCoeff (bool vectorized) const inline
Definition at line 610 of file TensorEvaluator.h.
References Eigen::TensorOpCost::cwiseMax().
data()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType* Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::data () const inline
Definition at line 616 of file TensorEvaluator.h.
dimensions()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::dimensions () const inline
Definition at line 575 of file TensorEvaluator.h.
else_impl()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > const TensorEvaluator<ElseArgType, Device>& Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::else_impl () const inline
required by sycl in order to extract the accessor
Definition at line 622 of file TensorEvaluator.h.
evalSubExprsIfNeeded()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::evalSubExprsIfNeeded (CoeffReturnType *) inline
Definition at line 581 of file TensorEvaluator.h.
packet()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::packet (Index index) const inline
Definition at line 598 of file TensorEvaluator.h.
References EIGEN_STRONG_INLINE, i, Eigen::internal::pblend(), and Eigen::internal::Selector< N >::select.
then_impl()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > const TensorEvaluator<ThenArgType, Device>& Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::then_impl () const inline
required by sycl in order to extract the accessor
Definition at line 620 of file TensorEvaluator.h.
Field Documentation
PacketSize
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > const int Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::PacketSize = internal::unpacket_traits<PacketReturnType>::size static
Definition at line 572 of file TensorEvaluator.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h