pairinteraction: Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > > Struct Template Reference
Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > > Struct Template Reference
#include <BlasUtil.h>
Public Types
typedef blas_traits< NestedXpr > Base
typedef CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > XprType
typedef Base::ExtractType ExtractType
Public Types inherited from Eigen::internal::blas_traits< NestedXpr >
enum
typedef traits< NestedXpr >::Scalar Scalar
typedef const NestedXpr & ExtractType
typedef NestedXpr _ExtractType
typedef conditional< bool(HasUsableDirectAccess), ExtractType, typename _ExtractType::PlainObject >::type DirectLinearAccessType
Static Public Member Functions
static ExtractType extract (const XprType &x)
static Scalar extractScalarFactor (const XprType &x)
Static Public Member Functions inherited from Eigen::internal::blas_traits< NestedXpr >
static ExtractType extract (const NestedXpr &x)
static const Scalar extractScalarFactor (const NestedXpr &)
Detailed Description
template<typename Scalar, typename NestedXpr, typename Plain>
struct Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >
Definition at line 310 of file BlasUtil.h.
Member Typedef Documentation
Base
template<typename Scalar , typename NestedXpr , typename Plain > typedef blas_traits<NestedXpr> Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::Base
Definition at line 313 of file BlasUtil.h.
ExtractType
template<typename Scalar , typename NestedXpr , typename Plain > typedef Base::ExtractType Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::ExtractType
Definition at line 315 of file BlasUtil.h.
XprType
template<typename Scalar , typename NestedXpr , typename Plain > typedef CwiseBinaryOp<scalar_product_op<Scalar>, const CwiseNullaryOp<scalar_constant_op<Scalar>,Plain>, NestedXpr> Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::XprType
Definition at line 314 of file BlasUtil.h.
Member Function Documentation
extract()
template<typename Scalar , typename NestedXpr , typename Plain > static ExtractType Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::extract (const XprType & x) inline static
Definition at line 316 of file BlasUtil.h.
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs().
extractScalarFactor()
template<typename Scalar , typename NestedXpr , typename Plain > static Scalar Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >::extractScalarFactor (const XprType & x) inline static
Definition at line 317 of file BlasUtil.h.
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs(), and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/BlasUtil.h