pairinteraction: Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape > Struct Template Reference
Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
enum { StorageOrder = int(Rhs::Flags) & RowMajorBit ? RowMajor : ColMajor }
typedef diagonal_product_evaluator_base< Rhs, typename Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft > Base
typedef Base::Scalar Scalar
typedef Product< Lhs, Rhs, ProductKind > XprType
typedef XprType::PlainObject PlainObject
Public Types inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
enum
typedef ScalarBinaryOpTraits< typename Rhs ::Scalar, typename Lhs::DiagonalVectorType ::Scalar >::ReturnType Scalar
Public Types inherited from Eigen::internal::evaluator_base< Product< Lhs, Rhs, LazyProduct > >
enum
typedef traits< Product< Lhs, Rhs, LazyProduct > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC product_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index idx) const
Public Member Functions inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
diagonal_product_evaluator_base (const Rhs &mat, const Lhs::DiagonalVectorType &diag)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index idx) const
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::true_type) const
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::false_type) const
Protected Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Protected Attributes inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
evaluator< Lhs::DiagonalVectorType > m_diagImpl
evaluator< Rhs > m_matImpl
Detailed Description
template<typename Lhs, typename Rhs, int ProductKind, int ProductTag>
struct Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >
Definition at line 828 of file ProductEvaluators.h.
Member Typedef Documentation
Base
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef diagonal_product_evaluator_base<Rhs, typename Lhs::DiagonalVectorType, Product<Lhs, Rhs, LazyProduct>, OnTheLeft> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::Base
Definition at line 831 of file ProductEvaluators.h.
PlainObject
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef XprType::PlainObject Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::PlainObject
Definition at line 838 of file ProductEvaluators.h.
Scalar
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Base::Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::Scalar
Definition at line 835 of file ProductEvaluators.h.
XprType
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Product<Lhs, Rhs, ProductKind> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::XprType
Definition at line 837 of file ProductEvaluators.h.
Member Enumeration Documentation
anonymous enum
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> anonymous enum
Enumerator
StorageOrder
Definition at line 840 of file ProductEvaluators.h.
Constructor & Destructor Documentation
product_evaluator()
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::product_evaluator (const XprType & xpr) inline explicit
Definition at line 844 of file ProductEvaluators.h.
Member Function Documentation
coeff()
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::coeff (Index row, Index col) const inline
Definition at line 849 of file ProductEvaluators.h.
packet() [1/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet (Index row, Index col) const inline
Definition at line 856 of file ProductEvaluators.h.
References col(), and row().
packet() [2/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet (Index idx) const inline
Definition at line 865 of file ProductEvaluators.h.
References Eigen::ColMajor, and int().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ProductEvaluators.h