pairinteraction: GlMatrixHelper< false, _Flags > Struct Template Reference
GlMatrixHelper< false, _Flags > Struct Template Reference
#include <gpuhelper.h>
Static Public Member Functions
static void loadMatrix (const Matrix< float, 4, 4, _Flags, 4, 4 > &mat)
static void loadMatrix (const Matrix< double, 4, 4, _Flags, 4, 4 > &mat)
static void multMatrix (const Matrix< float, 4, 4, _Flags, 4, 4 > &mat)
static void multMatrix (const Matrix< double, 4, 4, _Flags, 4, 4 > &mat)
Detailed Description
template<int _Flags>
struct GlMatrixHelper< false, _Flags >
Definition at line 118 of file gpuhelper.h.
Member Function Documentation
loadMatrix() [1/2]
template<int _Flags> static void GlMatrixHelper< false, _Flags >::loadMatrix (const Matrix< float, 4, 4, _Flags, 4, 4 > & mat) inline static
Definition at line 120 of file gpuhelper.h.
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data().
loadMatrix() [2/2]
template<int _Flags> static void GlMatrixHelper< false, _Flags >::loadMatrix (const Matrix< double, 4, 4, _Flags, 4, 4 > & mat) inline static
Definition at line 121 of file gpuhelper.h.
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data().
multMatrix() [1/2]
template<int _Flags> static void GlMatrixHelper< false, _Flags >::multMatrix (const Matrix< float, 4, 4, _Flags, 4, 4 > & mat) inline static
Definition at line 122 of file gpuhelper.h.
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data().
multMatrix() [2/2]
template<int _Flags> static void GlMatrixHelper< false, _Flags >::multMatrix (const Matrix< double, 4, 4, _Flags, 4, 4 > & mat) inline static
Definition at line 123 of file gpuhelper.h.
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/demos/opengl/gpuhelper.h