pairinteraction: Eigen::internal::scalar_zeta_op< Scalar > Struct Template Reference
Eigen::internal::scalar_zeta_op< Scalar > Struct Template Reference
#include <ForwardDeclarations.h>
Public Types
typedef packet_traits< Scalar >::type Packet
Public Member Functions
EIGEN_DEVICE_FUNC const Scalar operator() (const Scalar &x, const Scalar &q) const
EIGEN_DEVICE_FUNC Packet packetOp (const Packet &x, const Packet &q) const
Detailed Description
template<typename Scalar>
struct Eigen::internal::scalar_zeta_op< Scalar >
Definition at line 218 of file ForwardDeclarations.h.
Member Typedef Documentation
Packet
template<typename Scalar > typedef packet_traits<Scalar>::type Eigen::internal::scalar_zeta_op< Scalar >::Packet
Definition at line 151 of file SpecialFunctionsFunctors.h.
Member Function Documentation
operator()()
template<typename Scalar > EIGEN_DEVICE_FUNC const Scalar Eigen::internal::scalar_zeta_op< Scalar >::operator() (const Scalar & x, const Scalar & q) const inline
Definition at line 148 of file SpecialFunctionsFunctors.h.
References Eigen::zeta(), and zeta().
packetOp()
template<typename Scalar > EIGEN_DEVICE_FUNC Packet Eigen::internal::scalar_zeta_op< Scalar >::packetOp (const Packet & x, const Packet & q) const inline
Definition at line 152 of file SpecialFunctionsFunctors.h.
References Eigen::internal::pzeta().
The documentation for this struct was generated from the following files:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/ForwardDeclarations.h
/travis/libpairinteraction/eigen/unsupported/Eigen/src/SpecialFunctions/SpecialFunctionsFunctors.h