pairinteraction: Eigen::internal::TensorPrinter< Tensor, Rank > Struct Template Reference
Eigen::internal::TensorPrinter< Tensor, Rank > Struct Template Reference
#include <TensorIO.h>
Static Public Member Functions
static void run (std::ostream &os, const Tensor &tensor)
Detailed Description
template<typename Tensor, int Rank>
struct Eigen::internal::TensorPrinter< Tensor, Rank >
Definition at line 19 of file TensorIO.h.
Member Function Documentation
run()
template<typename Tensor , int Rank> static void Eigen::internal::TensorPrinter< Tensor, Rank >::run (std::ostream & os, const Tensor & tensor) inline static
Definition at line 20 of file TensorIO.h.
References Eigen::internal::array_prod(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimensions(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::Layout, and matrix().
Referenced by Eigen::operator<<().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorIO.h