pairinteraction: Eigen::internal::Packet4cf Struct Reference
Eigen::internal::Packet4cf Struct Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet4cf ()
EIGEN_STRONG_INLINE Packet4cf (const __m256 &a)
Data Fields
__m256 v
Detailed Description
Definition at line 18 of file Complex.h.
Constructor & Destructor Documentation
Packet4cf() [1/2]
EIGEN_STRONG_INLINE Eigen::internal::Packet4cf::Packet4cf () inline
Definition at line 20 of file Complex.h.
Referenced by Eigen::internal::padd< Packet4cf >(), Eigen::internal::pand< Packet4cf >(), Eigen::internal::pandnot< Packet4cf >(), Eigen::internal::pconj(), Eigen::internal::pcplxflip< Packet4cf >(), Eigen::internal::pdiv< Packet4cf >(), Eigen::internal::pgather< std::complex< float >, Packet4cf >(), Eigen::internal::pinsertfirst(), Eigen::internal::pinsertlast(), Eigen::internal::pload< Packet4cf >(), Eigen::internal::ploaddup< Packet4cf >(), Eigen::internal::ploadu< Packet4cf >(), Eigen::internal::conj_helper< Packet8f, Packet4cf, false, false >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet8f, false, false >::pmul(), Eigen::internal::pmul< Packet4cf >(), Eigen::internal::pnegate(), Eigen::internal::por< Packet4cf >(), Eigen::internal::preduxp< Packet4cf >(), Eigen::internal::preverse(), Eigen::internal::pset1< Packet4cf >(), Eigen::internal::psub< Packet4cf >(), and Eigen::internal::pxor< Packet4cf >().
Packet4cf() [2/2]
EIGEN_STRONG_INLINE Eigen::internal::Packet4cf::Packet4cf (const __m256 & a) inline explicit
Definition at line 21 of file Complex.h.
Field Documentation
v
__m256 Eigen::internal::Packet4cf::v
Definition at line 22 of file Complex.h.
Referenced by Eigen::internal::pconj(), Eigen::internal::pdiv< Packet4cf >(), Eigen::internal::pinsertfirst(), Eigen::internal::pinsertlast(), Eigen::internal::conj_helper< Packet8f, Packet4cf, false, false >::pmul(), Eigen::internal::conj_helper< Packet4cf, Packet8f, false, false >::pmul(), Eigen::internal::pnegate(), Eigen::internal::preduxp< Packet2cd >(), Eigen::internal::preduxp< Packet4cf >(), Eigen::internal::preverse(), and Eigen::internal::palign_impl< Offset, Packet4cf >::run().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/arch/AVX/Complex.h