pairinteraction: chwirut2_functor Struct Reference
chwirut2_functor Struct Reference
Public Member Functions
chwirut2_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
chwirut2_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
Public Member Functions inherited from Functor< double >
Functor ()
Functor (int inputs, int values)
Functor ()
Functor (int inputs, int values)
int inputs () const
int inputs () const
int values () const
int values () const
Public Member Functions inherited from Eigen::DenseFunctor< double >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Static Public Attributes
static const double m_x [54] = { 0.500E0, 1.000E0, 1.750E0, 3.750E0, 5.750E0, 0.875E0, 2.250E0, 3.250E0, 5.250E0, 0.750E0, 1.750E0, 2.750E0, 4.750E0, 0.625E0, 1.250E0, 2.250E0, 4.250E0, .500E0, 3.000E0, .750E0, 3.000E0, 1.500E0, 6.000E0, 3.000E0, 6.000E0, 1.500E0, 3.000E0, .500E0, 2.000E0, 4.000E0, .750E0, 2.000E0, 5.000E0, .750E0, 2.250E0, 3.750E0, 5.750E0, 3.000E0, .750E0, 2.500E0, 4.000E0, .750E0, 2.500E0, 4.000E0, .750E0, 2.500E0, 4.000E0, .500E0, 6.000E0, 3.000E0, .500E0, 2.750E0, .500E0, 1.750E0}
static const double m_y [54] = { 92.9000E0 ,57.1000E0 ,31.0500E0 ,11.5875E0 ,8.0250E0 ,63.6000E0 ,21.4000E0 ,14.2500E0 ,8.4750E0 ,63.8000E0 ,26.8000E0 ,16.4625E0 ,7.1250E0 ,67.3000E0 ,41.0000E0 ,21.1500E0 ,8.1750E0 ,81.5000E0 ,13.1200E0 ,59.9000E0 ,14.6200E0 ,32.9000E0 ,5.4400E0 ,12.5600E0 ,5.4400E0 ,32.0000E0 ,13.9500E0 ,75.8000E0 ,20.0000E0 ,10.4200E0 ,59.5000E0 ,21.6700E0 ,8.5500E0 ,62.0000E0 ,20.2000E0 ,7.7600E0 ,3.7500E0 ,11.8100E0 ,54.7000E0 ,23.7000E0 ,11.5500E0 ,61.3000E0 ,17.7000E0 ,8.7400E0 ,59.2000E0 ,16.3000E0 ,8.6200E0 ,81.0000E0 ,4.8700E0 ,14.6200E0 ,81.7000E0 ,17.1700E0 ,81.3000E0 ,28.9000E0 }
Additional Inherited Members
Public Types inherited from Functor< double >
enum
enum
typedef double Scalar
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Types inherited from Eigen::DenseFunctor< double >
enum
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Data Fields inherited from Functor< double >
const int m_inputs
int m_inputs
const int m_values
int m_values
Data Fields inherited from Eigen::DenseFunctor< double >
const int m_inputs
const int m_values
Detailed Description
Definition at line 244 of file levenberg_marquardt.cpp.
Constructor & Destructor Documentation
chwirut2_functor() [1/2]
chwirut2_functor::chwirut2_functor (void) inline
Definition at line 246 of file levenberg_marquardt.cpp.
chwirut2_functor() [2/2]
chwirut2_functor::chwirut2_functor (void) inline
Definition at line 636 of file NonLinearOptimization.cpp.
Member Function Documentation
df() [1/2]
int chwirut2_functor::df (const VectorXd & b, MatrixXd & fjac) inline
Definition at line 261 of file levenberg_marquardt.cpp.
References e(), exp(), i, m_x, m_y, and x.
df() [2/2]
int chwirut2_functor::df (const VectorXd & b, MatrixXd & fjac) inline
Definition at line 651 of file NonLinearOptimization.cpp.
References e(), exp(), i, m_x, m_y, and x.
operator()() [1/2]
int chwirut2_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
Definition at line 249 of file levenberg_marquardt.cpp.
References exp(), i, and x.
operator()() [2/2]
int chwirut2_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
Definition at line 639 of file NonLinearOptimization.cpp.
References exp(), i, and x.
Field Documentation
m_x
const double chwirut2_functor::m_x = { 0.500E0, 1.000E0, 1.750E0, 3.750E0, 5.750E0, 0.875E0, 2.250E0, 3.250E0, 5.250E0, 0.750E0, 1.750E0, 2.750E0, 4.750E0, 0.625E0, 1.250E0, 2.250E0, 4.250E0, .500E0, 3.000E0, .750E0, 3.000E0, 1.500E0, 6.000E0, 3.000E0, 6.000E0, 1.500E0, 3.000E0, .500E0, 2.000E0, 4.000E0, .750E0, 2.000E0, 5.000E0, .750E0, 2.250E0, 3.750E0, 5.750E0, 3.000E0, .750E0, 2.500E0, 4.000E0, .750E0, 2.500E0, 4.000E0, .750E0, 2.500E0, 4.000E0, .500E0, 6.000E0, 3.000E0, .500E0, 2.750E0, .500E0, 1.750E0} static
Definition at line 247 of file levenberg_marquardt.cpp.
Referenced by df().
m_y
const double chwirut2_functor::m_y = { 92.9000E0 ,57.1000E0 ,31.0500E0 ,11.5875E0 ,8.0250E0 ,63.6000E0 ,21.4000E0 ,14.2500E0 ,8.4750E0 ,63.8000E0 ,26.8000E0 ,16.4625E0 ,7.1250E0 ,67.3000E0 ,41.0000E0 ,21.1500E0 ,8.1750E0 ,81.5000E0 ,13.1200E0 ,59.9000E0 ,14.6200E0 ,32.9000E0 ,5.4400E0 ,12.5600E0 ,5.4400E0 ,32.0000E0 ,13.9500E0 ,75.8000E0 ,20.0000E0 ,10.4200E0 ,59.5000E0 ,21.6700E0 ,8.5500E0 ,62.0000E0 ,20.2000E0 ,7.7600E0 ,3.7500E0 ,11.8100E0 ,54.7000E0 ,23.7000E0 ,11.5500E0 ,61.3000E0 ,17.7000E0 ,8.7400E0 ,59.2000E0 ,16.3000E0 ,8.6200E0 ,81.0000E0 ,4.8700E0 ,14.6200E0 ,81.7000E0 ,17.1700E0 ,81.3000E0 ,28.9000E0 } static
Definition at line 248 of file levenberg_marquardt.cpp.
Referenced by df().
The documentation for this struct was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/test/levenberg_marquardt.cpp
/travis/libpairinteraction/eigen/unsupported/test/NonLinearOptimization.cpp