pairinteraction: Eigen::internal::tensor_index_linearization_helper< Index, NumIndices, n, RowMajor > Struct Template Reference
Eigen::internal::tensor_index_linearization_helper< Index, NumIndices, n, RowMajor > Struct Template Reference
#include <TensorDimensions.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index run (array< Index, NumIndices > const &indices, array< Index, NumIndices > const &dimensions)
Detailed Description
template<typename Index, std::size_t NumIndices, std::size_t n, bool RowMajor>
struct Eigen::internal::tensor_index_linearization_helper< Index, NumIndices, n, RowMajor >
Definition at line 235 of file TensorDimensions.h.
Member Function Documentation
run()
template<typename Index , std::size_t NumIndices, std::size_t n, bool RowMajor> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::tensor_index_linearization_helper< Index, NumIndices, n, RowMajor >::run (array< Index, NumIndices > const & indices, array< Index, NumIndices > const & dimensions) inline static
Definition at line 238 of file TensorDimensions.h.
References Eigen::internal::array_get(), n, and Eigen::RowMajor.
Referenced by Eigen::DSizes< Index, NumDims >::IndexOfColMajor(), and Eigen::DSizes< Index, NumDims >::IndexOfRowMajor().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDimensions.h