pairinteraction: Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true > Struct Template Reference
Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true > Struct Template Reference
#include <JacobiSVD.h>
Public Types
typedef JacobiSVD< MatrixType, QRPreconditioner > SVD
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
Static Public Member Functions
static bool run (typename SVD::WorkMatrixType &work_matrix, SVD &svd, Index p, Index q, RealScalar &maxDiagEntry)
Detailed Description
template<typename MatrixType, int QRPreconditioner>
struct Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >
Definition at line 362 of file JacobiSVD.h.
Member Typedef Documentation
RealScalar
template<typename MatrixType , int QRPreconditioner> typedef MatrixType::RealScalar Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::RealScalar
Definition at line 366 of file JacobiSVD.h.
Scalar
template<typename MatrixType , int QRPreconditioner> typedef MatrixType::Scalar Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::Scalar
Definition at line 365 of file JacobiSVD.h.
SVD
template<typename MatrixType , int QRPreconditioner> typedef JacobiSVD<MatrixType, QRPreconditioner> Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::SVD
Definition at line 364 of file JacobiSVD.h.
Member Function Documentation
run()
template<typename MatrixType , int QRPreconditioner> static bool Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run (typename SVD::WorkMatrixType & work_matrix, SVD & svd, Index p, Index q, RealScalar & maxDiagEntry) inline static
Definition at line 367 of file JacobiSVD.h.
References abs(), abs2(), Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::c(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::SVDBase< Derived >::computeU(), Eigen::SVDBase< Derived >::computeV(), Eigen::conj(), imag(), Eigen::SVDBase< Derived >::m_matrixU, Eigen::SVDBase< Derived >::m_matrixV, min, n, rot(), Eigen::JacobiRotation< Scalar >::s(), and sqrt().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/SVD/JacobiSVD.h