pairinteraction: lanczos1_functor Struct Reference
lanczos1_functor Struct Reference
Public Member Functions
lanczos1_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
lanczos1_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
Public Member Functions inherited from Functor< double >
Functor ()
Functor (int inputs, int values)
Functor ()
Functor (int inputs, int values)
int inputs () const
int inputs () const
int values () const
int values () const
Public Member Functions inherited from Eigen::DenseFunctor< double >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Static Public Attributes
static const double x [24] = { 0.000000000000E+00, 5.000000000000E-02, 1.000000000000E-01, 1.500000000000E-01, 2.000000000000E-01, 2.500000000000E-01, 3.000000000000E-01, 3.500000000000E-01, 4.000000000000E-01, 4.500000000000E-01, 5.000000000000E-01, 5.500000000000E-01, 6.000000000000E-01, 6.500000000000E-01, 7.000000000000E-01, 7.500000000000E-01, 8.000000000000E-01, 8.500000000000E-01, 9.000000000000E-01, 9.500000000000E-01, 1.000000000000E+00, 1.050000000000E+00, 1.100000000000E+00, 1.150000000000E+00 }
static const double y [24] = { 2.513400000000E+00 ,2.044333373291E+00 ,1.668404436564E+00 ,1.366418021208E+00 ,1.123232487372E+00 ,9.268897180037E-01 ,7.679338563728E-01 ,6.388775523106E-01 ,5.337835317402E-01 ,4.479363617347E-01 ,3.775847884350E-01 ,3.197393199326E-01 ,2.720130773746E-01 ,2.324965529032E-01 ,1.996589546065E-01 ,1.722704126914E-01 ,1.493405660168E-01 ,1.300700206922E-01 ,1.138119324644E-01 ,1.000415587559E-01 ,8.833209084540E-02 ,7.833544019350E-02 ,6.976693743449E-02 ,6.239312536719E-02 }
Additional Inherited Members
Public Types inherited from Functor< double >
enum
enum
typedef double Scalar
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Types inherited from Eigen::DenseFunctor< double >
enum
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Data Fields inherited from Functor< double >
const int m_inputs
int m_inputs
const int m_values
int m_values
Data Fields inherited from Eigen::DenseFunctor< double >
const int m_inputs
const int m_values
Detailed Description
Definition at line 583 of file levenberg_marquardt.cpp.
Constructor & Destructor Documentation
lanczos1_functor() [1/2]
lanczos1_functor::lanczos1_functor (void) inline
Definition at line 585 of file levenberg_marquardt.cpp.
lanczos1_functor() [2/2]
lanczos1_functor::lanczos1_functor (void) inline
Definition at line 974 of file NonLinearOptimization.cpp.
References x, and y.
Member Function Documentation
df() [1/2]
int lanczos1_functor::df (const VectorXd & b, MatrixXd & fjac) inline
Definition at line 596 of file levenberg_marquardt.cpp.
References exp(), i, x, and y.
df() [2/2]
int lanczos1_functor::df (const VectorXd & b, MatrixXd & fjac) inline
Definition at line 985 of file NonLinearOptimization.cpp.
References exp(), i, x, and y.
operator()() [1/2]
int lanczos1_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
Definition at line 588 of file levenberg_marquardt.cpp.
References exp(), and i.
operator()() [2/2]
int lanczos1_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
Definition at line 977 of file NonLinearOptimization.cpp.
References exp(), and i.
Field Documentation
x
const double lanczos1_functor::x = { 0.000000000000E+00, 5.000000000000E-02, 1.000000000000E-01, 1.500000000000E-01, 2.000000000000E-01, 2.500000000000E-01, 3.000000000000E-01, 3.500000000000E-01, 4.000000000000E-01, 4.500000000000E-01, 5.000000000000E-01, 5.500000000000E-01, 6.000000000000E-01, 6.500000000000E-01, 7.000000000000E-01, 7.500000000000E-01, 8.000000000000E-01, 8.500000000000E-01, 9.000000000000E-01, 9.500000000000E-01, 1.000000000000E+00, 1.050000000000E+00, 1.100000000000E+00, 1.150000000000E+00 } static
Definition at line 586 of file levenberg_marquardt.cpp.
Referenced by df().
y
const double lanczos1_functor::y = { 2.513400000000E+00 ,2.044333373291E+00 ,1.668404436564E+00 ,1.366418021208E+00 ,1.123232487372E+00 ,9.268897180037E-01 ,7.679338563728E-01 ,6.388775523106E-01 ,5.337835317402E-01 ,4.479363617347E-01 ,3.775847884350E-01 ,3.197393199326E-01 ,2.720130773746E-01 ,2.324965529032E-01 ,1.996589546065E-01 ,1.722704126914E-01 ,1.493405660168E-01 ,1.300700206922E-01 ,1.138119324644E-01 ,1.000415587559E-01 ,8.833209084540E-02 ,7.833544019350E-02 ,6.976693743449E-02 ,6.239312536719E-02 } static
Definition at line 587 of file levenberg_marquardt.cpp.
Referenced by df().
The documentation for this struct was generated from the following files:
/travis/libpairinteraction/eigen/unsupported/test/levenberg_marquardt.cpp
/travis/libpairinteraction/eigen/unsupported/test/NonLinearOptimization.cpp