pairinteraction: packet_helper< Cond, Packet > Struct Template Reference
packet_helper< Cond, Packet > Struct Template Reference
Public Member Functions
template<typename T >
Packet load (const T *from) const
template<typename T >
void store (T *to, const Packet &x) const
Detailed Description
template<bool Cond, typename Packet>
struct packet_helper< Cond, Packet >
Definition at line 72 of file packetmath.cpp.
Member Function Documentation
load()
template<bool Cond, typename Packet> template<typename T > Packet packet_helper< Cond, Packet >::load (const T * from) const inline
Definition at line 75 of file packetmath.cpp.
Referenced by packetmath_real().
store()
template<bool Cond, typename Packet> template<typename T > void packet_helper< Cond, Packet >::store (T * to, const Packet & x) const inline
Definition at line 78 of file packetmath.cpp.
References Eigen::internal::pstore().
Referenced by packetmath_real().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/test/packetmath.cpp