pairinteraction: Eigen::internal::plain_array< T, Size, MatrixOrArrayOptions, Alignment > Struct Template Reference
Eigen::internal::plain_array< T, Size, MatrixOrArrayOptions, Alignment > Struct Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC plain_array ()
EIGEN_DEVICE_FUNC plain_array (constructor_without_unaligned_array_assert)
Data Fields
T array [Size]
Detailed Description
template<typename T, int Size, int MatrixOrArrayOptions, int Alignment = (MatrixOrArrayOptions&DontAlign) ? 0 : compute_default_alignment<T,Size>::value>
struct Eigen::internal::plain_array< T, Size, MatrixOrArrayOptions, Alignment >
Definition at line 44 of file DenseStorage.h.
Constructor & Destructor Documentation
plain_array() [1/2]
template<typename T, int Size, int MatrixOrArrayOptions, int Alignment = (MatrixOrArrayOptions&DontAlign) ? 0 : compute_default_alignment<T,Size>::value> EIGEN_DEVICE_FUNC Eigen::internal::plain_array< T, Size, MatrixOrArrayOptions, Alignment >::plain_array () inline
Definition at line 49 of file DenseStorage.h.
plain_array() [2/2]
template<typename T, int Size, int MatrixOrArrayOptions, int Alignment = (MatrixOrArrayOptions&DontAlign) ? 0 : compute_default_alignment<T,Size>::value> EIGEN_DEVICE_FUNC Eigen::internal::plain_array< T, Size, MatrixOrArrayOptions, Alignment >::plain_array (constructor_without_unaligned_array_assert) inline
Definition at line 55 of file DenseStorage.h.
Field Documentation
array
template<typename T, int Size, int MatrixOrArrayOptions, int Alignment = (MatrixOrArrayOptions&DontAlign) ? 0 : compute_default_alignment<T,Size>::value> T Eigen::internal::plain_array< T, Size, MatrixOrArrayOptions, Alignment >::array[Size]
Definition at line 46 of file DenseStorage.h.
Referenced by Eigen::internal::gemv_static_vector_if< Scalar, Size, MaxSize, true >::data(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::data(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::data(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::data(), and Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::data().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/DenseStorage.h