pairinteraction: PointPointMinimizer Struct Reference
PointPointMinimizer Struct Reference
Public Types
typedef double Scalar
Public Member Functions
PointPointMinimizer ()
double minimumOnVolumeVolume (const Box2d &r1, const Box2d &r2)
double minimumOnVolumeObject (const Box2d &r, const Vector2d &v)
double minimumOnObjectVolume (const Vector2d &v, const Box2d &r)
double minimumOnObjectObject (const Vector2d &v1, const Vector2d &v2)
Data Fields
int calls
Detailed Description
Definition at line 12 of file BVH_Example.cpp.
Member Typedef Documentation
Scalar
typedef double PointPointMinimizer::Scalar
Definition at line 15 of file BVH_Example.cpp.
Constructor & Destructor Documentation
PointPointMinimizer()
PointPointMinimizer::PointPointMinimizer () inline
Definition at line 14 of file BVH_Example.cpp.
Member Function Documentation
minimumOnObjectObject()
double PointPointMinimizer::minimumOnObjectObject (const Vector2d & v1, const Vector2d & v2) inline
Definition at line 20 of file BVH_Example.cpp.
Referenced by main().
minimumOnObjectVolume()
double PointPointMinimizer::minimumOnObjectVolume (const Vector2d & v, const Box2d & r) inline
Definition at line 19 of file BVH_Example.cpp.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::squaredExteriorDistance().
minimumOnVolumeObject()
double PointPointMinimizer::minimumOnVolumeObject (const Box2d & r, const Vector2d & v) inline
Definition at line 18 of file BVH_Example.cpp.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::squaredExteriorDistance().
minimumOnVolumeVolume()
double PointPointMinimizer::minimumOnVolumeVolume (const Box2d & r1, const Box2d & r2) inline
Definition at line 17 of file BVH_Example.cpp.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::squaredExteriorDistance().
Field Documentation
calls
int PointPointMinimizer::calls
Definition at line 22 of file BVH_Example.cpp.
Referenced by main().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/doc/examples/BVH_Example.cpp