pairinteraction: Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > > Struct Template Reference
Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum {
IsRowMajor = XprType::IsRowMajor, IsColMajor = !IsRowMajor, ReverseRow = (Direction == Vertical) || (Direction == BothDirections), ReverseCol = (Direction == Horizontal) || (Direction == BothDirections),
ReversePacket, CoeffReadCost = evaluator<ArgType>::CoeffReadCost, Flags0 = evaluator<ArgType>::Flags, LinearAccess,
Flags = int(Flags0) & (HereditaryBits | PacketAccessBit | LinearAccess), Alignment = 0
}
typedef Reverse< ArgType, Direction > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Reverse< ArgType, Direction > >
enum
typedef traits< Reverse< ArgType, Direction > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &reverse)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Protected Attributes
evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index, ReverseRow ? ArgType::RowsAtCompileTime :1 > m_rows
const variable_if_dynamic< Index, ReverseCol ? ArgType::ColsAtCompileTime :1 > m_cols
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Detailed Description
template<typename ArgType, int Direction>
struct Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >
Definition at line 1416 of file CoreEvaluators.h.
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , int Direction> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::CoeffReturnType
Definition at line 1421 of file CoreEvaluators.h.
Scalar
template<typename ArgType , int Direction> typedef XprType::Scalar Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::Scalar
Definition at line 1420 of file CoreEvaluators.h.
XprType
template<typename ArgType , int Direction> typedef Reverse<ArgType, Direction> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::XprType
Definition at line 1419 of file CoreEvaluators.h.
Member Enumeration Documentation
anonymous enum
template<typename ArgType , int Direction> anonymous enum
Enumerator
IsRowMajor
IsColMajor
ReverseRow
ReverseCol
ReversePacket
CoeffReadCost
Flags0
LinearAccess
Flags
Alignment
Definition at line 1423 of file CoreEvaluators.h.
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::unary_evaluator (const XprType & reverse) inline explicit
Definition at line 1446 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff (Index row, Index col) const inline
Definition at line 1453 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, and row().
coeff() [2/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff (Index index) const inline
Definition at line 1460 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
coeffRef() [1/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef (Index row, Index col) inline
Definition at line 1466 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, and row().
coeffRef() [2/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef (Index index) inline
Definition at line 1473 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
packet() [1/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet (Index row, Index col) const inline
Definition at line 1480 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, row(), and Eigen::TensorSycl::run().
packet() [2/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet (Index index) const inline
Definition at line 1495 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE, and Eigen::internal::preverse().
writePacket() [1/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket (Index row, Index col, const PacketType & x) inline
Definition at line 1503 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, row(), and Eigen::TensorSycl::run().
writePacket() [2/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket (Index index, const PacketType & x) inline
Definition at line 1520 of file CoreEvaluators.h.
References Eigen::internal::preverse().
Field Documentation
m_argImpl
template<typename ArgType , int Direction> evaluator<ArgType> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_argImpl protected
Definition at line 1528 of file CoreEvaluators.h.
m_cols
template<typename ArgType , int Direction> const variable_if_dynamic<Index, ReverseCol ? ArgType::ColsAtCompileTime : 1> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_cols protected
Definition at line 1533 of file CoreEvaluators.h.
m_rows
template<typename ArgType , int Direction> const variable_if_dynamic<Index, ReverseRow ? ArgType::RowsAtCompileTime : 1> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_rows protected
Definition at line 1532 of file CoreEvaluators.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/CoreEvaluators.h