pairinteraction: Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { RowsAtCompileTime = XprType::RowsAtCompileTime }
typedef Block< ArgType, BlockRows, BlockCols, InnerPanel > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
enum
typedef traits< Block< ArgType, BlockRows, BlockCols, InnerPanel > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &block)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Protected Attributes
evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index,(ArgType::RowsAtCompileTime==1 &&BlockRows==1) ? 0 :Dynamic > m_startRow
const variable_if_dynamic< Index,(ArgType::ColsAtCompileTime==1 &&BlockCols==1) ? 0 :Dynamic > m_startCol
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Detailed Description
template<typename ArgType, int BlockRows, int BlockCols, bool InnerPanel>
struct Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >
Definition at line 1013 of file CoreEvaluators.h.
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::CoeffReturnType
Definition at line 1025 of file CoreEvaluators.h.
Scalar
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::Scalar Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::Scalar
Definition at line 1024 of file CoreEvaluators.h.
XprType
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef Block<ArgType, BlockRows, BlockCols, InnerPanel> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::XprType
Definition at line 1016 of file CoreEvaluators.h.
Member Enumeration Documentation
anonymous enum
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> anonymous enum
Enumerator
RowsAtCompileTime
Definition at line 1027 of file CoreEvaluators.h.
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::unary_evaluator (const XprType & block) inline explicit
Definition at line 1018 of file CoreEvaluators.h.
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff (Index row, Index col) const inline
Definition at line 1032 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, and row().
coeff() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff (Index index) const inline
Definition at line 1038 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
coeffRef() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef (Index row, Index col) inline
Definition at line 1044 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, and row().
coeffRef() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef (Index index) inline
Definition at line 1050 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
packet() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet (Index row, Index col) const inline
Definition at line 1057 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, and row().
packet() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet (Index index) const inline
Definition at line 1064 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
writePacket() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket (Index row, Index col, const PacketType & x) inline
Definition at line 1072 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, row(), and x.
writePacket() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket (Index index, const PacketType & x) inline
Definition at line 1079 of file CoreEvaluators.h.
References x.
Field Documentation
m_argImpl
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> evaluator<ArgType> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_argImpl protected
Definition at line 1087 of file CoreEvaluators.h.
m_startCol
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, (ArgType::ColsAtCompileTime == 1 && BlockCols==1) ? 0 : Dynamic> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_startCol protected
Definition at line 1089 of file CoreEvaluators.h.
m_startRow
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, (ArgType::RowsAtCompileTime == 1 && BlockRows==1) ? 0 : Dynamic> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_startRow protected
Definition at line 1088 of file CoreEvaluators.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/CoreEvaluators.h