pairinteraction: Eigen::internal::matrix_function_compute< MatrixType, IsComplex > Struct Template Reference
Eigen::internal::matrix_function_compute< MatrixType, IsComplex > Struct Template Reference
Class for computing matrix functions.
#include <MatrixFunction.h>
Static Public Member Functions
template<typename AtomicType , typename ResultType >
static void run (const MatrixType &A, AtomicType &atomic, ResultType &result)
Compute the matrix function.
Detailed Description
template<typename MatrixType, int IsComplex = NumTraits<typename internal::traits<MatrixType>::Scalar>::IsComplex>
struct Eigen::internal::matrix_function_compute< MatrixType, IsComplex >
Class for computing matrix functions.
Template Parameters
MatrixType type of the argument of the matrix function, expected to be an instantiation of the Matrix class template.
AtomicType type for computing matrix function of atomic blocks.
IsComplex used internally to select correct specialization.
This class implements the Schur-Parlett algorithm for computing matrix functions. The spectrum of the matrix is divided in clustered of eigenvalues that lies close together. This class delegates the computation of the matrix function on every block corresponding to these clusters to an object of type AtomicType and uses these results to compute the matrix function of the whole matrix. The class AtomicType should have a compute() member function for computing the matrix function of a block.
See also
class MatrixFunctionAtomic, class MatrixLogarithmAtomic
Definition at line 376 of file MatrixFunction.h.
Member Function Documentation
run()
template<typename MatrixType , int IsComplex = NumTraits<typename internal::traits<MatrixType>::Scalar>::IsComplex> template<typename AtomicType , typename ResultType > static void Eigen::internal::matrix_function_compute< MatrixType, IsComplex >::run (const MatrixType & A, AtomicType & atomic, ResultType & result) static
Compute the matrix function.
Parameters
[in] A argument of matrix function, should be a square matrix.
[in] atomic class for computing matrix function of atomic blocks.
[out] result the function f applied to A, as specified in the constructor.
See MatrixBase::matrixFunction() for details on how this computation is implemented.
Referenced by Eigen::MatrixLogarithmReturnValue< Derived >::evalTo(), Eigen::MatrixFunctionReturnValue< Derived >::evalTo(), and Eigen::internal::matrix_function_compute< MatrixType, 0 >::run().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/MatrixFunctions/MatrixFunction.h