pairinteraction: Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false > Struct Template Reference
Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet4f &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &x, const Packet4f &y) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet4f &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &x, const Packet4f &y) const
Detailed Description
template<>
struct Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >
Definition at line 236 of file Complex.h.
Member Function Documentation
pmadd() [1/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmadd (const Packet2cf & x, const Packet4f & y, const Packet2cf & c) const inline
Definition at line 238 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [2/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmadd (const Packet2cf & x, const Packet4f & y, const Packet2cf & c) const inline
Definition at line 243 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmul() [1/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmul (const Packet2cf & x, const Packet4f & y) const inline
Definition at line 241 of file Complex.h.
References Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::pmul< Packet4f >(), and Eigen::internal::Packet2cf::v.
pmul() [2/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmul (const Packet2cf & x, const Packet4f & y) const inline
Definition at line 246 of file Complex.h.
References a, b, EIGEN_STRONG_INLINE, Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pmul(), Eigen::internal::pmul< Packet4f >(), res, and s.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/arch/AltiVec/Complex.h