pairinteraction: Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false > Struct Template Reference
Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf pmadd (const Packet2cf &x, const Packet2cf &y, const Packet2cf &c) const
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b) const
Detailed Description
template<>
struct Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >
Definition at line 205 of file Complex.h.
Member Function Documentation
pmadd() [1/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 198 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [2/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 207 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [3/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 248 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmadd() [4/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd (const Packet2cf & x, const Packet2cf & y, const Packet2cf & c) const inline
Definition at line 319 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
pmul() [1/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 201 of file Complex.h.
References Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::pconj(), Eigen::internal::pmul(), and vec4f_swizzle1.
pmul() [2/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 210 of file Complex.h.
References Eigen::internal::pconj(), and Eigen::internal::pmul().
pmul() [3/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 251 of file Complex.h.
References Eigen::internal::pconj(), and Eigen::internal::pmul().
pmul() [4/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul (const Packet2cf & a, const Packet2cf & b) const inline
Definition at line 322 of file Complex.h.
References Eigen::internal::pconj(), and Eigen::internal::pmul().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/arch/AltiVec/Complex.h