pairinteraction: Eigen::internal::kiss_cpx_fft< _Scalar > Struct Template Reference
Eigen::internal::kiss_cpx_fft< _Scalar > Struct Template Reference
#include <ei_kissfft_impl.h>
Public Types
typedef _Scalar Scalar
typedef std::complex< Scalar > Complex
Public Member Functions
void make_twiddles (int nfft, bool inverse)
void factorize (int nfft)
template<typename _Src >
void work (int stage, Complex *xout, const _Src *xin, size_t fstride, size_t in_stride)
void bfly2 (Complex *Fout, const size_t fstride, int m)
void bfly4 (Complex *Fout, const size_t fstride, const size_t m)
void bfly3 (Complex *Fout, const size_t fstride, const size_t m)
void bfly5 (Complex *Fout, const size_t fstride, const size_t m)
void bfly_generic (Complex *Fout, const size_t fstride, int m, int p)
Data Fields
std::vector< Complex > m_twiddles
std::vector< int > m_stageRadix
std::vector< int > m_stageRemainder
std::vector< Complex > m_scratchBuf
bool m_inverse
Detailed Description
template<typename _Scalar>
struct Eigen::internal::kiss_cpx_fft< _Scalar >
Definition at line 18 of file ei_kissfft_impl.h.
Member Typedef Documentation
Complex
template<typename _Scalar > typedef std::complex<Scalar> Eigen::internal::kiss_cpx_fft< _Scalar >::Complex
Definition at line 21 of file ei_kissfft_impl.h.
Scalar
template<typename _Scalar > typedef _Scalar Eigen::internal::kiss_cpx_fft< _Scalar >::Scalar
Definition at line 20 of file ei_kissfft_impl.h.
Member Function Documentation
bfly2()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::bfly2 (Complex * Fout, const size_t fstride, int m) inline
Definition at line 99 of file ei_kissfft_impl.h.
References m.
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::work().
bfly3()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::bfly3 (Complex * Fout, const size_t fstride, const size_t m) inline
Definition at line 132 of file ei_kissfft_impl.h.
References Eigen::imag(), m, m2(), and Eigen::real().
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::work().
bfly4()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::bfly4 (Complex * Fout, const size_t fstride, const size_t m) inline
Definition at line 109 of file ei_kissfft_impl.h.
References Eigen::imag(), m, and Eigen::real().
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::work().
bfly5()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::bfly5 (Complex * Fout, const size_t fstride, const size_t m) inline
Definition at line 161 of file ei_kissfft_impl.h.
References Eigen::imag(), m, and Eigen::real().
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::work().
bfly_generic()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::bfly_generic (Complex * Fout, const size_t fstride, int m, int p) inline
Definition at line 228 of file ei_kissfft_impl.h.
References m, p, and Eigen::numext::q.
Referenced by Eigen::internal::kiss_cpx_fft< _Scalar >::work().
factorize()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::factorize (int nfft) inline
Definition at line 39 of file ei_kissfft_impl.h.
References n, and p.
Referenced by Eigen::internal::kissfft_impl< _Scalar >::get_plan().
make_twiddles()
template<typename _Scalar > void Eigen::internal::kiss_cpx_fft< _Scalar >::make_twiddles (int nfft, bool inverse) inline
Definition at line 29 of file ei_kissfft_impl.h.
References acos(), exp(), i, and inverse().
Referenced by Eigen::internal::kissfft_impl< _Scalar >::get_plan().
work()
template<typename _Scalar > template<typename _Src > void Eigen::internal::kiss_cpx_fft< _Scalar >::work (int stage, Complex * xout, const _Src * xin, size_t fstride, size_t in_stride) inline
Definition at line 64 of file ei_kissfft_impl.h.
References Eigen::internal::kiss_cpx_fft< _Scalar >::bfly2(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly3(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly4(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly5(), Eigen::internal::kiss_cpx_fft< _Scalar >::bfly_generic(), m, and p.
Field Documentation
m_inverse
template<typename _Scalar > bool Eigen::internal::kiss_cpx_fft< _Scalar >::m_inverse
Definition at line 26 of file ei_kissfft_impl.h.
m_scratchBuf
template<typename _Scalar > std::vector<Complex> Eigen::internal::kiss_cpx_fft< _Scalar >::m_scratchBuf
Definition at line 25 of file ei_kissfft_impl.h.
m_stageRadix
template<typename _Scalar > std::vector<int> Eigen::internal::kiss_cpx_fft< _Scalar >::m_stageRadix
Definition at line 23 of file ei_kissfft_impl.h.
m_stageRemainder
template<typename _Scalar > std::vector<int> Eigen::internal::kiss_cpx_fft< _Scalar >::m_stageRemainder
Definition at line 24 of file ei_kissfft_impl.h.
m_twiddles
template<typename _Scalar > std::vector<Complex> Eigen::internal::kiss_cpx_fft< _Scalar >::m_twiddles
Definition at line 22 of file ei_kissfft_impl.h.
Referenced by Eigen::internal::kissfft_impl< _Scalar >::get_plan().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/src/FFT/ei_kissfft_impl.h