pairinteraction: Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > > Struct Template Reference
Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > > Struct Template Reference
#include <SuperLUSupport.h>
Public Types
typedef Matrix< Scalar, Rows, Cols, Options, MRows, MCols > MatrixType
Static Public Member Functions
static void run (MatrixType &mat, SluMatrix &res)
Detailed Description
template<typename Scalar, int Rows, int Cols, int Options, int MRows, int MCols>
struct Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >
Definition at line 232 of file SuperLUSupport.h.
Member Typedef Documentation
MatrixType
template<typename Scalar , int Rows, int Cols, int Options, int MRows, int MCols> typedef Matrix<Scalar,Rows,Cols,Options,MRows,MCols> Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::MatrixType
Definition at line 234 of file SuperLUSupport.h.
Member Function Documentation
run()
template<typename Scalar , int Rows, int Cols, int Options, int MRows, int MCols> static void Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run (MatrixType & mat, SluMatrix & res) inline static
Definition at line 235 of file SuperLUSupport.h.
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), eigen_assert, Eigen::SluMatrix::lda, Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride(), Eigen::RowMajor, Eigen::PlainObjectBase< Derived >::rows(), Eigen::SluMatrix::setScalarType(), Eigen::SluMatrix::setStorageType(), Eigen::SluMatrix::storage, and Eigen::SluMatrix::values.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h