pairinteraction: Eigen::internal::Packet2cf Struct Reference
Eigen::internal::Packet2cf Struct Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const __m128 &a)
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
Data Fields
Packet4f v
__m128 v
union {
Packet4f v
Packet1cd cd [2]
};
Detailed Description
Definition at line 30 of file Complex.h.
Constructor & Destructor Documentation
Packet2cf() [1/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline explicit
Definition at line 32 of file Complex.h.
Referenced by Eigen::internal::padd< Packet2cf >(), Eigen::internal::pand< Packet2cf >(), Eigen::internal::pandnot< Packet2cf >(), Eigen::internal::pblend(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pcplxflip< Packet2cf >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pinsertfirst(), Eigen::internal::pinsertlast(), Eigen::internal::pload< Packet2cf >(), Eigen::internal::ploadu< Packet2cf >(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet4f, Packet2cf, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pmul< Packet2cf >(), Eigen::internal::pnegate(), Eigen::internal::por< Packet2cf >(), Eigen::internal::predux< Packet2cf >(), Eigen::internal::predux_mul< Packet2cf >(), Eigen::internal::preduxp< Packet2cf >(), Eigen::internal::preverse(), Eigen::internal::psub< Packet2cf >(), and Eigen::internal::pxor< Packet2cf >().
Packet2cf() [2/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
Definition at line 33 of file Complex.h.
Packet2cf() [3/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
Definition at line 37 of file Complex.h.
Packet2cf() [4/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
Definition at line 38 of file Complex.h.
References v.
Packet2cf() [5/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
Definition at line 20 of file Complex.h.
Packet2cf() [6/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const __m128 & a) inline explicit
Definition at line 21 of file Complex.h.
Packet2cf() [7/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
Definition at line 30 of file Complex.h.
Packet2cf() [8/8]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
Definition at line 31 of file Complex.h.
References Eigen::internal::Packet1cd::v.
Field Documentation
@99
union { ... }
cd
Packet1cd Eigen::internal::Packet2cf::cd[2]
Definition at line 34 of file Complex.h.
Referenced by Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pscatter< std::complex< double >, Packet1cd >(), and Eigen::internal::palign_impl< Offset, Packet2cf >::run().
v [1/2]
__m128 Eigen::internal::Packet2cf::v
Definition at line 22 of file Complex.h.
v [2/2]
Packet4f Eigen::internal::Packet2cf::v
Definition at line 34 of file Complex.h.
Referenced by Packet2cf(), Eigen::internal::pconj(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::ploaddup< Packet4cf >(), Eigen::internal::conj_helper< Packet4f, Packet2cf, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pnegate(), Eigen::internal::preduxp< Packet2cf >(), Eigen::internal::preverse(), Eigen::internal::pscatter< std::complex< double >, Packet1cd >(), Eigen::internal::pset1< Packet2cf >(), Eigen::internal::ptranspose(), and Eigen::internal::palign_impl< Offset, Packet2cf >::run().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/arch/AltiVec/Complex.h