pairinteraction: Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > > Struct Template Reference
Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > > Struct Template Reference
#include <BlasUtil.h>
Public Types
enum { IsComplex = NumTraits<Scalar>::IsComplex, NeedToConjugate = Base::NeedToConjugate ? 0 : IsComplex }
typedef blas_traits< NestedXpr > Base
typedef CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > XprType
typedef Base::ExtractType ExtractType
Public Types inherited from Eigen::internal::blas_traits< NestedXpr >
enum
typedef traits< NestedXpr >::Scalar Scalar
typedef const NestedXpr & ExtractType
typedef NestedXpr _ExtractType
typedef conditional< bool(HasUsableDirectAccess), ExtractType, typename _ExtractType::PlainObject >::type DirectLinearAccessType
Static Public Member Functions
static ExtractType extract (const XprType &x)
static Scalar extractScalarFactor (const XprType &x)
Static Public Member Functions inherited from Eigen::internal::blas_traits< NestedXpr >
static ExtractType extract (const NestedXpr &x)
static const Scalar extractScalarFactor (const NestedXpr &)
Detailed Description
template<typename Scalar, typename NestedXpr>
struct Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >
Definition at line 293 of file BlasUtil.h.
Member Typedef Documentation
Base
template<typename Scalar , typename NestedXpr > typedef blas_traits<NestedXpr> Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::Base
Definition at line 296 of file BlasUtil.h.
ExtractType
template<typename Scalar , typename NestedXpr > typedef Base::ExtractType Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::ExtractType
Definition at line 298 of file BlasUtil.h.
XprType
template<typename Scalar , typename NestedXpr > typedef CwiseUnaryOp<scalar_conjugate_op<Scalar>, NestedXpr> Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::XprType
Definition at line 297 of file BlasUtil.h.
Member Enumeration Documentation
anonymous enum
template<typename Scalar , typename NestedXpr > anonymous enum
Enumerator
IsComplex
NeedToConjugate
Definition at line 300 of file BlasUtil.h.
Member Function Documentation
extract()
template<typename Scalar , typename NestedXpr > static ExtractType Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::extract (const XprType & x) inline static
Definition at line 304 of file BlasUtil.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression().
extractScalarFactor()
template<typename Scalar , typename NestedXpr > static Scalar Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::extractScalarFactor (const XprType & x) inline static
Definition at line 305 of file BlasUtil.h.
References Eigen::conj(), and Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/util/BlasUtil.h