pairinteraction: sparseGaussianTest< Scalar > Struct Template Reference
sparseGaussianTest< Scalar > Struct Template Reference
Public Types
typedef Matrix< Scalar, Dynamic, 1 > VectorType
typedef SparseFunctor< Scalar, int > Base
typedef Base::JacobianType JacobianType
Public Types inherited from Eigen::SparseFunctor< Scalar, int >
enum
typedef Scalar Scalar
typedef int Index
typedef Matrix< Scalar, Dynamic, 1 > InputType
typedef Matrix< Scalar, Dynamic, 1 > ValueType
typedef SparseMatrix< Scalar, ColMajor, Index > JacobianType
typedef SparseQR< JacobianType, COLAMDOrdering< int > > QRSolver
Public Member Functions
sparseGaussianTest (int inputs, int values)
VectorType model (const VectorType &uv, VectorType &x)
void initPoints (VectorType &uv_ref, VectorType &x)
int operator() (const VectorType &uv, VectorType &fvec)
int df (const VectorType &uv, JacobianType &fjac)
Public Member Functions inherited from Eigen::SparseFunctor< Scalar, int >
SparseFunctor (int inputs, int values)
int inputs () const
int values () const
Data Fields
VectorType m_x
VectorType m_y
Data Fields inherited from Eigen::SparseFunctor< Scalar, int >
const int m_inputs
const int m_values
Detailed Description
template<typename Scalar>
struct sparseGaussianTest< Scalar >
Definition at line 21 of file sparseLM.cpp.
Member Typedef Documentation
Base
template<typename Scalar> typedef SparseFunctor<Scalar,int> sparseGaussianTest< Scalar >::Base
Definition at line 24 of file sparseLM.cpp.
JacobianType
template<typename Scalar> typedef Base::JacobianType sparseGaussianTest< Scalar >::JacobianType
Definition at line 25 of file sparseLM.cpp.
VectorType
template<typename Scalar> typedef Matrix<Scalar,Dynamic,1> sparseGaussianTest< Scalar >::VectorType
Definition at line 23 of file sparseLM.cpp.
Constructor & Destructor Documentation
sparseGaussianTest()
template<typename Scalar> sparseGaussianTest< Scalar >::sparseGaussianTest (int inputs, int values) inline
Definition at line 26 of file sparseLM.cpp.
Member Function Documentation
df()
template<typename Scalar> int sparseGaussianTest< Scalar >::df (const VectorType & uv, JacobianType & fjac) inline
Definition at line 83 of file sparseLM.cpp.
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), col(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), eigen_assert, m, n, row(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and v.
initPoints()
template<typename Scalar> void sparseGaussianTest< Scalar >::initPoints (VectorType & uv_ref, VectorType & x) inline
Definition at line 54 of file sparseLM.cpp.
References x.
Referenced by test_sparseLM_T().
model()
template<typename Scalar> VectorType sparseGaussianTest< Scalar >::model (const VectorType & uv, VectorType & x) inline
Definition at line 29 of file sparseLM.cpp.
References eigen_assert, i, j, m, n, Eigen::half_impl::pow(), Eigen::PlainObjectBase< Derived >::setZero(), v, x, and y.
operator()()
template<typename Scalar> int sparseGaussianTest< Scalar >::operator() (const VectorType & uv, VectorType & fvec) inline
Definition at line 59 of file sparseLM.cpp.
References eigen_assert, i, j, m, n, Eigen::half_impl::pow(), and v.
Field Documentation
m_x
template<typename Scalar> VectorType sparseGaussianTest< Scalar >::m_x
Definition at line 124 of file sparseLM.cpp.
m_y
template<typename Scalar> VectorType sparseGaussianTest< Scalar >::m_y
Definition at line 124 of file sparseLM.cpp.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/test/sparseLM.cpp