pairinteraction: Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version > Struct Template Reference
Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version > Struct Template Reference
#include <GeneralMatrixMatrixTriangular.h>
Public Types
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (Index size, Index depth, const LhsScalar *_lhs, Index lhsStride, const RhsScalar *_rhs, Index rhsStride, ResScalar *_res, Index resStride, const ResScalar &alpha, level3_blocking< LhsScalar, RhsScalar > &blocking)
Detailed Description
template<typename Index, typename LhsScalar, int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar, int RhsStorageOrder, bool ConjugateRhs, int UpLo, int Version>
struct Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >
Definition at line 58 of file GeneralMatrixMatrixTriangular.h.
Member Typedef Documentation
ResScalar
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs, int UpLo, int Version> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::ResScalar
Definition at line 60 of file GeneralMatrixMatrixTriangular.h.
Member Function Documentation
run()
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs, int UpLo, int Version> static EIGEN_STRONG_INLINE void Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run (Index size, Index depth, const LhsScalar * _lhs, Index lhsStride, const RhsScalar * _rhs, Index rhsStride, ResScalar * _res, Index resStride, const ResScalar & alpha, level3_blocking< LhsScalar, RhsScalar > & blocking) inline static
Definition at line 61 of file GeneralMatrixMatrixTriangular.h.
References alpha, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), ei_declare_aligned_stack_constructed_variable, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::Lower, max, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), min, res, size, and Eigen::Upper.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h