pairinteraction: Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device > Struct Template Reference
#include <TensorConvolution.h>
Public Types
enum {
IsAligned = TensorEvaluator<InputArgType, Device>::IsAligned & TensorEvaluator<KernelArgType, Device>::IsAligned, PacketAccess = TensorEvaluator<InputArgType, Device>::PacketAccess & TensorEvaluator<KernelArgType, Device>::PacketAccess, Layout = TensorEvaluator<InputArgType, Device>::Layout, CoordAccess = false,
RawAccess = false
}
typedef TensorConvolutionOp< Indices, InputArgType, KernelArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (Scalar *)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void cleanup ()
void evalTo (typename XprType::Scalar *buffer)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (const Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Scalar * data () const
Static Public Attributes
static const int NumDims = internal::array_size<typename TensorEvaluator<InputArgType, Device>::Dimensions>::value
static const int NumKernelDims = internal::array_size<Indices>::value
static const int PacketSize = internal::unpacket_traits<PacketReturnType>::size
Detailed Description
template<typename Indices, typename InputArgType, typename KernelArgType, typename Device>
struct Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >
Definition at line 291 of file TensorConvolution.h.
Member Typedef Documentation
CoeffReturnType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::CoeffReturnType
Definition at line 301 of file TensorConvolution.h.
Dimensions
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Dimensions
Definition at line 298 of file TensorConvolution.h.
Index
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Index
Definition at line 297 of file TensorConvolution.h.
PacketReturnType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::PacketReturnType
Definition at line 302 of file TensorConvolution.h.
Scalar
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Scalar
Definition at line 300 of file TensorConvolution.h.
XprType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef TensorConvolutionOp<Indices, InputArgType, KernelArgType> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::XprType
Definition at line 293 of file TensorConvolution.h.
Member Enumeration Documentation
anonymous enum
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
Layout
CoordAccess
RawAccess
Definition at line 305 of file TensorConvolution.h.
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
Definition at line 313 of file TensorConvolution.h.
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_STATIC_ASSERT, i, and Eigen::TensorConvolutionOp< Indices, InputXprType, KernelXprType >::indices().
Member Function Documentation
cleanup()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::cleanup () inline
Definition at line 382 of file TensorConvolution.h.
coeff()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::coeff (Index index) const inline
Definition at line 399 of file TensorConvolution.h.
costPerCoeff()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::costPerCoeff (bool vectorized) const inline
Definition at line 452 of file TensorConvolution.h.
data()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC Scalar* Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data () const inline
Definition at line 468 of file TensorConvolution.h.
References blockDim, blockIdx, ceil(), Eigen::ColMajor, data, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STRONG_INLINE, eval(), i, Eigen::TensorConvolutionOp< Indices, InputXprType, KernelXprType >::indices(), Eigen::TensorConvolutionOp< Indices, InputXprType, KernelXprType >::inputExpression(), j, Eigen::TensorConvolutionOp< Indices, InputXprType, KernelXprType >::kernelExpression(), m, Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputKernelToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaInputPlaneToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputKernelToTensorOutputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapCudaOutputPlaneToTensorOutputOffset(), n, p, Eigen::internal::TensorExecutor< Expression, Device, Vectorizable >::run(), s, and threadIdx.
dimensions()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::dimensions () const inline
Definition at line 375 of file TensorConvolution.h.
evalSubExprsIfNeeded()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalSubExprsIfNeeded (Scalar *) inline
Definition at line 377 of file TensorConvolution.h.
evalTo()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalTo (typename XprType::Scalar * buffer) inline
Definition at line 391 of file TensorConvolution.h.
References i.
packet()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::packet (const Index index) const inline
Definition at line 407 of file TensorConvolution.h.
References Eigen::ColMajor, data, EIGEN_ALIGN_MAX, EIGEN_STRONG_INLINE, and i.
Field Documentation
NumDims
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > const int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<InputArgType, Device>::Dimensions>::value static
Definition at line 295 of file TensorConvolution.h.
NumKernelDims
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > const int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::NumKernelDims = internal::array_size<Indices>::value static
Definition at line 296 of file TensorConvolution.h.
PacketSize
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > const int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::PacketSize = internal::unpacket_traits<PacketReturnType>::size static
Definition at line 303 of file TensorConvolution.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorConvolution.h