pairinteraction: Eigen::internal::FullReducer< Self, Op, Device, Vectorizable > Struct Template Reference
Eigen::internal::FullReducer< Self, Op, Device, Vectorizable > Struct Template Reference
#include <TensorReduction.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (const Self &self, Op &reducer, const Device &, typename Self::CoeffReturnType *output)
Static Public Attributes
static const bool HasOptimizedImplementation = false
Detailed Description
template<typename Self, typename Op, typename Device, bool Vectorizable = (Self::InputPacketAccess & Op::PacketAccess)>
struct Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >
Definition at line 219 of file TensorReduction.h.
Member Function Documentation
run()
template<typename Self , typename Op , typename Device , bool Vectorizable = (Self::InputPacketAccess & Op::PacketAccess)> static EIGEN_DEVICE_FUNC void Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::run (const Self & self, Op & reducer, const Device & , typename Self::CoeffReturnType * output) inline static
Definition at line 222 of file TensorReduction.h.
References Eigen::internal::array_prod(), eigen_assert, EIGEN_STRONG_INLINE, i, Eigen::TensorCostModel< Device >::numThreads(), Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable >::reduce(), and Eigen::TensorSycl::run().
Referenced by Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::evalSubExprsIfNeeded().
Field Documentation
HasOptimizedImplementation
template<typename Self , typename Op , typename Device , bool Vectorizable = (Self::InputPacketAccess & Op::PacketAccess)> const bool Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::HasOptimizedImplementation = false static
Definition at line 220 of file TensorReduction.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h