pairinteraction: Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum {
IsRowMajor = PlainObjectType::IsRowMajor, IsVectorAtCompileTime = PlainObjectType::IsVectorAtCompileTime, RowsAtCompileTime = PlainObjectType::RowsAtCompileTime, ColsAtCompileTime = PlainObjectType::ColsAtCompileTime,
CoeffReadCost = NumTraits<Scalar>::ReadCost, Flags = traits<Derived>::EvaluatorFlags, Alignment = traits<Derived>::Alignment
}
typedef PlainObjectBase< Derived > PlainObjectType
typedef PlainObjectType::Scalar Scalar
typedef PlainObjectType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Derived >
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC evaluator ()
EIGEN_DEVICE_FUNC evaluator (const PlainObjectType &m)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Protected Attributes
const Scalar * m_data
variable_if_dynamic< Index, IsVectorAtCompileTime ? 0 :int(IsRowMajor) ? ColsAtCompileTime :RowsAtCompileTime > m_outerStride
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Detailed Description
template<typename Derived>
struct Eigen::internal::evaluator< PlainObjectBase< Derived > >
Definition at line 127 of file CoreEvaluators.h.
Member Typedef Documentation
CoeffReturnType
template<typename Derived > typedef PlainObjectType::CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::CoeffReturnType
Definition at line 132 of file CoreEvaluators.h.
PlainObjectType
template<typename Derived > typedef PlainObjectBase<Derived> Eigen::internal::evaluator< PlainObjectBase< Derived > >::PlainObjectType
Definition at line 130 of file CoreEvaluators.h.
Scalar
template<typename Derived > typedef PlainObjectType::Scalar Eigen::internal::evaluator< PlainObjectBase< Derived > >::Scalar
Definition at line 131 of file CoreEvaluators.h.
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
IsRowMajor
IsVectorAtCompileTime
RowsAtCompileTime
ColsAtCompileTime
CoeffReadCost
Flags
Alignment
Definition at line 134 of file CoreEvaluators.h.
Constructor & Destructor Documentation
evaluator() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator () inline
Definition at line 145 of file CoreEvaluators.h.
References EIGEN_INTERNAL_CHECK_COST_VALUE.
evaluator() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator (const PlainObjectType & m) inline explicit
Definition at line 154 of file CoreEvaluators.h.
References EIGEN_INTERNAL_CHECK_COST_VALUE, and EIGEN_STRONG_INLINE.
Member Function Documentation
coeff() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index row, Index col) const inline
Definition at line 161 of file CoreEvaluators.h.
References col(), and EIGEN_STRONG_INLINE.
coeff() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index index) const inline
Definition at line 170 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
coeffRef() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index row, Index col) inline
Definition at line 176 of file CoreEvaluators.h.
References col(), and EIGEN_STRONG_INLINE.
coeffRef() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index index) inline
Definition at line 185 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
packet() [1/2]
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index row, Index col) const inline
Definition at line 192 of file CoreEvaluators.h.
References col(), and EIGEN_STRONG_INLINE.
packet() [2/2]
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index index) const inline
Definition at line 202 of file CoreEvaluators.h.
References EIGEN_STRONG_INLINE.
writePacket() [1/2]
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index row, Index col, const PacketType & x) inline
Definition at line 209 of file CoreEvaluators.h.
References col(), EIGEN_STRONG_INLINE, and x.
writePacket() [2/2]
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index index, const PacketType & x) inline
Definition at line 221 of file CoreEvaluators.h.
Field Documentation
m_data
template<typename Derived > const Scalar* Eigen::internal::evaluator< PlainObjectBase< Derived > >::m_data protected
Definition at line 227 of file CoreEvaluators.h.
m_outerStride
template<typename Derived > variable_if_dynamic<Index, IsVectorAtCompileTime ? 0 : int(IsRowMajor) ? ColsAtCompileTime : RowsAtCompileTime> Eigen::internal::evaluator< PlainObjectBase< Derived > >::m_outerStride protected
Definition at line 232 of file CoreEvaluators.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/CoreEvaluators.h