pairinteraction: Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > Struct Template Reference
#include <TensorReduction.h>
Public Types
enum {
IsAligned = false, PacketAccess = Self::InputPacketAccess && Op::PacketAccess, Layout = TensorEvaluator<ArgType, Device>::Layout, CoordAccess = false,
RawAccess = false
}
typedef TensorReductionOp< Op, Dims, ArgType, MakePointer_ > XprType
typedef XprType::Index Index
typedef ArgType ChildType
typedef TensorEvaluator< ArgType, Device >::Dimensions InputDimensions
typedef internal::conditional< NumOutputDims==0, Sizes<>, DSizes< Index, NumOutputDims > >::type Dimensions
typedef XprType::Scalar Scalar
typedef TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device > Self
typedef internal::remove_const< typename XprType::CoeffReturnType >::type CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool evalSubExprsIfNeeded (typename MakePointer_< CoeffReturnType >::Type data)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC MakePointer_< Scalar >::Type data () const
const TensorEvaluator< ArgType, Device > & impl () const
required by sycl in order to extract the accessor
const Device & device () const
added for sycl in order to construct the buffer from the sycl device
const Dims & xprDims () const
added for sycl in order to re-construct the reduction eval on the device for the sub-kernel
Static Public Attributes
static const int NumInputDims = internal::array_size<InputDimensions>::value
static const int NumReducedDims = internal::array_size<Dims>::value
static const int NumOutputDims = NumInputDims - NumReducedDims
static const bool InputPacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess
static const int PacketSize = internal::unpacket_traits<PacketReturnType>::size
static const bool ReducingInnerMostDims = internal::are_inner_most_dims<Dims, NumInputDims, Layout>::value
static const bool PreservingInnerMostDims = internal::preserve_inner_most_dims<Dims, NumInputDims, Layout>::value
static const bool RunningFullReduction = (NumOutputDims==0)
Friends
template<int , typename , typename >
struct internal::GenericDimReducer
template<typename , typename , bool >
struct internal::InnerMostDimReducer
template<int , typename , typename , bool >
struct internal::InnerMostDimPreserver
template<typename S , typename O , typename D , bool V>
struct internal::FullReducer
template<typename S , typename O , typename D >
struct internal::InnerReducer
Detailed Description
template<typename Op, typename Dims, typename ArgType, template< class > class MakePointer_, typename Device>
struct Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >
Definition at line 382 of file TensorReduction.h.
Member Typedef Documentation
ChildType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef ArgType Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ChildType
Definition at line 386 of file TensorReduction.h.
CoeffReturnType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef internal::remove_const<typename XprType::CoeffReturnType>::type Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::CoeffReturnType
Definition at line 395 of file TensorReduction.h.
Dimensions
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef internal::conditional<NumOutputDims==0, Sizes<>, DSizes<Index, NumOutputDims> >::type Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Dimensions
Definition at line 391 of file TensorReduction.h.
Index
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Index
Definition at line 385 of file TensorReduction.h.
InputDimensions
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::InputDimensions
Definition at line 387 of file TensorReduction.h.
PacketReturnType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::PacketReturnType
Definition at line 396 of file TensorReduction.h.
Scalar
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Scalar
Definition at line 392 of file TensorReduction.h.
Self
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef TensorEvaluator<const TensorReductionOp<Op, Dims, ArgType, MakePointer_>, Device> Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::Self
Definition at line 393 of file TensorReduction.h.
XprType
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > typedef TensorReductionOp<Op, Dims, ArgType, MakePointer_> Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::XprType
Definition at line 384 of file TensorReduction.h.
Member Enumeration Documentation
anonymous enum
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
Layout
CoordAccess
RawAccess
Definition at line 399 of file TensorReduction.h.
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
Definition at line 411 of file TensorReduction.h.
References Eigen::internal::array_prod(), Eigen::array< T, n >::back(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), Eigen::TensorReductionOp< Op, Dims, XprType, MakePointer_ >::dims(), eigen_assert, EIGEN_STATIC_ASSERT, i, and Eigen::internal::DimInitializer< OutputDims >::run().
Member Function Documentation
cleanup()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::cleanup () inline
Definition at line 583 of file TensorReduction.h.
coeff()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::coeff (Index index) const inline
Definition at line 591 of file TensorReduction.h.
References Eigen::ColMajor, Eigen::internal::GenericDimReducer< DimIndex, Self, Op >::reduce(), and Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable >::reduce().
costPerCoeff()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::costPerCoeff (bool vectorized) const inline
Definition at line 654 of file TensorReduction.h.
References Eigen::internal::array_prod().
data()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC MakePointer_<Scalar>::Type Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::data () const inline
Definition at line 665 of file TensorReduction.h.
device()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const Device& Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::device () const inline
added for sycl in order to construct the buffer from the sycl device
Definition at line 669 of file TensorReduction.h.
dimensions()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::dimensions () const inline
Definition at line 480 of file TensorReduction.h.
evalSubExprsIfNeeded()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::evalSubExprsIfNeeded (typename MakePointer_< CoeffReturnType >::Type data) inline
Definition at line 482 of file TensorReduction.h.
References Eigen::internal::array_prod(), Eigen::ColMajor, data, i, Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::run(), and Eigen::internal::InnerReducer< Self, Op, Device >::run().
impl()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const TensorEvaluator<ArgType, Device>& Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::impl () const inline
required by sycl in order to extract the accessor
Definition at line 667 of file TensorReduction.h.
packet()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::packet (Index index) const inline
Definition at line 611 of file TensorReduction.h.
References Eigen::internal::array_prod(), Eigen::ColMajor, EIGEN_ALIGN_MAX, eigen_assert, EIGEN_STATIC_ASSERT, i, Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable >::reduce(), and Eigen::internal::InnerMostDimPreserver< DimIndex, Self, Op, vectorizable >::reduce().
xprDims()
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const Dims& Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::xprDims () const inline
added for sycl in order to re-construct the reduction eval on the device for the sub-kernel
Definition at line 671 of file TensorReduction.h.
Friends And Related Function Documentation
internal::FullReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<typename S , typename O , typename D , bool V> friend struct internal::FullReducer friend
Definition at line 678 of file TensorReduction.h.
internal::GenericDimReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<int , typename , typename > friend struct internal::GenericDimReducer friend
Definition at line 675 of file TensorReduction.h.
internal::InnerMostDimPreserver
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<int , typename , typename , bool > friend struct internal::InnerMostDimPreserver friend
Definition at line 677 of file TensorReduction.h.
internal::InnerMostDimReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<typename , typename , bool > friend struct internal::InnerMostDimReducer friend
Definition at line 676 of file TensorReduction.h.
internal::InnerReducer
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > template<typename S , typename O , typename D > friend struct internal::InnerReducer friend
Definition at line 694 of file TensorReduction.h.
Field Documentation
InputPacketAccess
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const bool Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::InputPacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess static
Definition at line 394 of file TensorReduction.h.
NumInputDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const int Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumInputDims = internal::array_size<InputDimensions>::value static
Definition at line 388 of file TensorReduction.h.
NumOutputDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const int Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumOutputDims = NumInputDims - NumReducedDims static
Definition at line 390 of file TensorReduction.h.
NumReducedDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const int Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::NumReducedDims = internal::array_size<Dims>::value static
Definition at line 389 of file TensorReduction.h.
PacketSize
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const int Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::PacketSize = internal::unpacket_traits<PacketReturnType>::size static
Definition at line 397 of file TensorReduction.h.
PreservingInnerMostDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const bool Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::PreservingInnerMostDims = internal::preserve_inner_most_dims<Dims, NumInputDims, Layout>::value static
Definition at line 408 of file TensorReduction.h.
ReducingInnerMostDims
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const bool Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::ReducingInnerMostDims = internal::are_inner_most_dims<Dims, NumInputDims, Layout>::value static
Definition at line 407 of file TensorReduction.h.
RunningFullReduction
template<typename Op , typename Dims , typename ArgType , template< class > class MakePointer_, typename Device > const bool Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::RunningFullReduction = (NumOutputDims==0) static
Definition at line 409 of file TensorReduction.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h