pairinteraction: Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct > Struct Template Reference
Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct > Struct Template Reference
#include <ProductEvaluators.h>
Data Structures
struct add
struct adds
struct is_row_major
struct set
struct sub
Public Types
typedef Product< Lhs, Rhs >::Scalar Scalar
Static Public Member Functions
template<typename Dst >
static void evalTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static void addTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static void subTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static void scaleAndAddTo (Dst &dst, const Lhs &lhs, const Rhs &rhs, const Scalar &alpha)
Detailed Description
template<typename Lhs, typename Rhs>
struct Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >
Definition at line 297 of file ProductEvaluators.h.
Member Typedef Documentation
Scalar
template<typename Lhs , typename Rhs > typedef Product<Lhs,Rhs>::Scalar Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::Scalar
Definition at line 300 of file ProductEvaluators.h.
Member Function Documentation
addTo()
template<typename Lhs , typename Rhs > template<typename Dst > static void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::addTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 321 of file ProductEvaluators.h.
References Eigen::internal::outer_product_selector_run().
evalTo()
template<typename Lhs , typename Rhs > template<typename Dst > static void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::evalTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 315 of file ProductEvaluators.h.
References Eigen::internal::outer_product_selector_run().
scaleAndAddTo()
template<typename Lhs , typename Rhs > template<typename Dst > static void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::scaleAndAddTo (Dst & dst, const Lhs & lhs, const Rhs & rhs, const Scalar & alpha) inline static
Definition at line 333 of file ProductEvaluators.h.
References Eigen::internal::outer_product_selector_run().
subTo()
template<typename Lhs , typename Rhs > template<typename Dst > static void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::subTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
Definition at line 327 of file ProductEvaluators.h.
References Eigen::internal::outer_product_selector_run(), and sub().
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/ProductEvaluators.h