pairinteraction: Eigen::EigenBase< Derived > Class Template Reference
Eigen::EigenBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
#include <EigenBase.h>
Public Types
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Detailed Description
template<typename Derived>
class Eigen::EigenBase< Derived >
Common base class for all classes T such that MatrixBase has an operator=(T) and a constructor MatrixBase(T).
In other words, an EigenBase object is an object that can be copied into a MatrixBase.
Besides MatrixBase-derived classes, this also includes special matrix classes such as diagonal matrices, etc.
Notice that this class is trivial, it is only used to disambiguate overloaded functions.
See also
The class hierarchy
Definition at line 29 of file EigenBase.h.
Member Typedef Documentation
Index
template<typename Derived> typedef Eigen::Index Eigen::EigenBase< Derived >::Index
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
Deprecated:
Since Eigen 3.3, its usage is deprecated. Use Eigen::Index instead.
See also
StorageIndex, Preprocessor directives.
Definition at line 38 of file EigenBase.h.
StorageKind
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind
Definition at line 41 of file EigenBase.h.
Member Function Documentation
addTo()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline
Definition at line 77 of file EigenBase.h.
applyThisOnTheLeft()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline
Definition at line 109 of file EigenBase.h.
applyThisOnTheRight()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline
Definition at line 100 of file EigenBase.h.
cols()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::cols (void) const inline
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
Definition at line 62 of file EigenBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::EigenBase< MatrixReplacement >::addTo(), Eigen::internal::BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options >::BandMatrixWrapper(), Eigen::RealSchur< MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< MatrixType >::compute(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), print_size(), Eigen::EigenBase< MatrixReplacement >::size(), Eigen::EigenBase< MatrixReplacement >::subTo(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
const_cast_derived()
template<typename Derived> EIGEN_DEVICE_FUNC Derived& Eigen::EigenBase< Derived >::const_cast_derived () const inline
Definition at line 51 of file EigenBase.h.
Referenced by Eigen::copy_using_evaluator(), and Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived> EIGEN_DEVICE_FUNC const Derived& Eigen::EigenBase< Derived >::const_derived () const inline
Definition at line 54 of file EigenBase.h.
derived() [1/2]
template<typename Derived> EIGEN_DEVICE_FUNC Derived& Eigen::EigenBase< Derived >::derived () inline
Returns
a reference to the derived object
Definition at line 45 of file EigenBase.h.
Referenced by Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::analyzePattern(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheLeft(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::applyOnTheRight(), Eigen::EigenBase< MatrixReplacement >::applyThisOnTheLeft(), Eigen::EigenBase< MatrixReplacement >::applyThisOnTheRight(), Eigen::internal::blueNorm_impl(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::coeffs(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::ColPivHouseholderQR(), Eigen::EigenBase< MatrixReplacement >::cols(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition(), Eigen::ComplexEigenSolver< _MatrixType >::ComplexEigenSolver(), Eigen::ComplexSchur< MatrixType >::ComplexSchur(), Eigen::FullPivLU< _MatrixType >::compute(), Eigen::PartialPivLU< Matrix< Scalar, Dynamic, Dynamic > >::compute(), Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::compute(), Eigen::RealSchur< MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< MatrixType >::compute(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), Eigen::ColPivHouseholderQR< TransposeTypeWithSameStorageOrder >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::EigenSolver< CompanionMatrixType >::EigenSolver(), Eigen::EigenBase< MatrixReplacement >::evalTo(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::factorize(), Eigen::FullPivHouseholderQR< TransposeTypeWithSameStorageOrder >::FullPivHouseholderQR(), Eigen::FullPivLU< _MatrixType >::FullPivLU(), Eigen::internal::generic_matrix_wrapper< MatrixType, false >::grab(), Eigen::UmfPackLU< _MatrixType >::grab(), Eigen::HouseholderQR< TransposeTypeWithSameStorageOrder >::HouseholderQR(), Eigen::kroneckerProduct(), Eigen::LDLT< _MatrixType, _UpLo >::LDLT(), Eigen::LLT< _MatrixType, _UpLo >::LLT(), Eigen::RotationBase< Derived, 3 >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex > >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Eigen::operator*(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator*=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator+=(), Eigen::DenseBase< Derived >::operator+=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator-=(), Eigen::DenseBase< Derived >::operator-=(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), Eigen::MatrixBase< Solve< Decomposition, RhsType > >::operator=(), Eigen::DenseBase< Derived >::operator=(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), Eigen::Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, _PacketAccess >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), Eigen::SparseMatrix< scalar_t >::operator=(), Eigen::PartialPivLU< Matrix< Scalar, Dynamic, Dynamic > >::PartialPivLU(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::RealSchur< MatrixType >::RealSchur(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), Eigen::EigenBase< MatrixReplacement >::rows(), Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::subs(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::supers(), Eigen::test_relative_error(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
derived() [2/2]
template<typename Derived> EIGEN_DEVICE_FUNC const Derived& Eigen::EigenBase< Derived >::derived () const inline
Returns
a const reference to the derived object
Definition at line 48 of file EigenBase.h.
evalTo()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline
Definition at line 71 of file EigenBase.h.
Referenced by Eigen::EigenBase< MatrixReplacement >::addTo(), and Eigen::EigenBase< MatrixReplacement >::subTo().
rows()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::rows (void) const inline
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
Definition at line 59 of file EigenBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::EigenBase< MatrixReplacement >::addTo(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::RealSchur< MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< MatrixType >::compute(), Eigen::EigenSolver< CompanionMatrixType >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), print_size(), Eigen::EigenBase< MatrixReplacement >::size(), Eigen::EigenBase< MatrixReplacement >::subTo(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
size()
template<typename Derived> EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
Definition at line 66 of file EigenBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::FullPivLU< _MatrixType >::computeInPlace(), and print_size().
subTo()
template<typename Derived> template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline
Definition at line 89 of file EigenBase.h.
The documentation for this class was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/Core/EigenBase.h