pairinteraction: Eigen::DefaultDevice Struct Reference
Eigen::DefaultDevice Struct Reference
#include <TensorDeviceDefault.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void * allocate (size_t num_bytes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void deallocate (void *buffer) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void memcpy (void *dst, const void *src, size_t n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void memcpyHostToDevice (void *dst, const void *src, size_t n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void memcpyDeviceToHost (void *dst, const void *src, size_t n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void memset (void *buffer, int c, size_t n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t numThreads () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t firstLevelCacheSize () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t lastLevelCacheSize () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int majorDeviceVersion () const
Detailed Description
Definition at line 17 of file TensorDeviceDefault.h.
Member Function Documentation
allocate()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void* Eigen::DefaultDevice::allocate (size_t num_bytes) const inline
Definition at line 18 of file TensorDeviceDefault.h.
References Eigen::internal::aligned_malloc().
deallocate()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DefaultDevice::deallocate (void * buffer) const inline
Definition at line 21 of file TensorDeviceDefault.h.
References Eigen::internal::aligned_free().
firstLevelCacheSize()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::DefaultDevice::firstLevelCacheSize () const inline
Definition at line 47 of file TensorDeviceDefault.h.
References Eigen::l1CacheSize().
Referenced by lastLevelCacheSize().
lastLevelCacheSize()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::DefaultDevice::lastLevelCacheSize () const inline
Definition at line 57 of file TensorDeviceDefault.h.
References firstLevelCacheSize(), and Eigen::l3CacheSize().
majorDeviceVersion()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE int Eigen::DefaultDevice::majorDeviceVersion () const inline
Definition at line 67 of file TensorDeviceDefault.h.
memcpy()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DefaultDevice::memcpy (void * dst, const void * src, size_t n) const inline
Definition at line 24 of file TensorDeviceDefault.h.
Referenced by memcpyDeviceToHost(), and memcpyHostToDevice().
memcpyDeviceToHost()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DefaultDevice::memcpyDeviceToHost (void * dst, const void * src, size_t n) const inline
Definition at line 30 of file TensorDeviceDefault.h.
References memcpy().
memcpyHostToDevice()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DefaultDevice::memcpyHostToDevice (void * dst, const void * src, size_t n) const inline
Definition at line 27 of file TensorDeviceDefault.h.
References memcpy().
memset()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DefaultDevice::memset (void * buffer, int c, size_t n) const inline
Definition at line 33 of file TensorDeviceDefault.h.
numThreads()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::DefaultDevice::numThreads () const inline
Definition at line 37 of file TensorDeviceDefault.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceDefault.h