pairinteraction: Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > > Struct Template Reference
Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > > Struct Template Reference
#include <SolveWithGuess.h>
Public Types
typedef SolveWithGuess< Decomposition, RhsType, GuessType > SolveType
typedef SolveType::PlainObject PlainObject
typedef evaluator< PlainObject > Base
Public Types inherited from Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType >::PlainObject >
typedef unary_evaluator< SolveWithGuess< Decomposition, RhsType, GuessType >::PlainObject > Base
Public Member Functions
evaluator (const SolveType &solve)
Public Member Functions inherited from Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType >::PlainObject >
EIGEN_DEVICE_FUNC evaluator (const SolveWithGuess< Decomposition, RhsType, GuessType >::PlainObject &xpr)
Protected Attributes
PlainObject m_result
Detailed Description
template<typename Decomposition, typename RhsType, typename GuessType>
struct Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >
Definition at line 74 of file SolveWithGuess.h.
Member Typedef Documentation
Base
template<typename Decomposition , typename RhsType , typename GuessType > typedef evaluator<PlainObject> Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >::Base
Definition at line 79 of file SolveWithGuess.h.
PlainObject
template<typename Decomposition , typename RhsType , typename GuessType > typedef SolveType::PlainObject Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >::PlainObject
Definition at line 78 of file SolveWithGuess.h.
SolveType
template<typename Decomposition , typename RhsType , typename GuessType > typedef SolveWithGuess<Decomposition,RhsType,GuessType> Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >::SolveType
Definition at line 77 of file SolveWithGuess.h.
Constructor & Destructor Documentation
evaluator()
template<typename Decomposition , typename RhsType , typename GuessType > Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >::evaluator (const SolveType & solve) inline
Definition at line 81 of file SolveWithGuess.h.
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::dec(), Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::guess(), and Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rhs().
Field Documentation
m_result
template<typename Decomposition , typename RhsType , typename GuessType > PlainObject Eigen::internal::evaluator< SolveWithGuess< Decomposition, RhsType, GuessType > >::m_result protected
Definition at line 90 of file SolveWithGuess.h.
The documentation for this struct was generated from the following file:
/travis/libpairinteraction/eigen/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h