pairinteraction: /travis/libpairinteraction/eigen/test/svd_common.h File Reference
svd_common.h File Reference
#include "svd_fill.h"
Functions
template<typename SvdType , typename MatrixType >
void svd_check_full (const MatrixType &m, const SvdType &svd)
template<typename SvdType , typename MatrixType >
void svd_compare_to_full (const MatrixType &m, unsigned int computationOptions, const SvdType &referenceSvd)
template<typename SvdType , typename MatrixType >
void svd_least_square (const MatrixType &m, unsigned int computationOptions)
template<typename MatrixType >
void svd_min_norm (const MatrixType &m, unsigned int computationOptions)
template<typename SvdType , typename MatrixType >
void svd_test_all_computation_options (const MatrixType &m, bool full_only)
template<typename Scalar >
EIGEN_DONT_INLINE Scalar zero ()
template<typename T >
EIGEN_DONT_INLINE T sub (T a, T b)
template<typename SvdType , typename MatrixType >
void svd_inf_nan ()
template<typename >
void svd_underoverflow ()
template<typename MatrixType >
void svd_all_trivial_2x2 (void(*cb)(const MatrixType &, bool))
template<typename >
void svd_preallocate ()
template<typename SvdType , typename MatrixType >
void svd_verify_assert (const MatrixType &m)
Function Documentation
sub()
template<typename T > EIGEN_DONT_INLINE T sub (T a, T b)
Definition at line 278 of file svd_common.h.
References b.
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::subTo(), and svd_inf_nan().
svd_all_trivial_2x2()
template<typename MatrixType > void svd_all_trivial_2x2 (void(*)(const MatrixType &, bool) cb)
Definition at line 373 of file svd_common.h.
Referenced by test_bdcsvd(), and test_jacobisvd().
svd_check_full()
template<typename SvdType , typename MatrixType > void svd_check_full (const MatrixType & m, const SvdType & svd)
Definition at line 24 of file svd_common.h.
References cols, min, rows, v, VERIFY, VERIFY_IS_APPROX, and VERIFY_IS_UNITARY.
Referenced by svd_test_all_computation_options(), and svd_underoverflow().
svd_compare_to_full()
template<typename SvdType , typename MatrixType > void svd_compare_to_full (const MatrixType & m, unsigned int computationOptions, const SvdType & referenceSvd)
Definition at line 59 of file svd_common.h.
References cols, Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, min, rows, svd(), VERIFY, and VERIFY_IS_APPROX.
Referenced by svd_test_all_computation_options().
svd_inf_nan()
template<typename SvdType , typename MatrixType > void svd_inf_nan ()
Definition at line 282 of file svd_common.h.
References Eigen::ComputeFullU, Eigen::ComputeFullV, e(), m, sub(), svd(), and VERIFY.
svd_least_square()
template<typename SvdType , typename MatrixType > void svd_least_square (const MatrixType & m, unsigned int computationOptions)
Definition at line 100 of file svd_common.h.
References cols, e(), rows, sqrt(), svd(), boost::multiprecision::test_isMuchSmallerThan(), and x.
svd_min_norm()
template<typename MatrixType > void svd_min_norm (const MatrixType & m, unsigned int computationOptions)
Definition at line 168 of file svd_common.h.
References adjoint(), cols, Eigen::Dynamic, m2(), qr(), SVD_FOR_MIN_NORM, VERIFY, and VERIFY_IS_APPROX.
Referenced by svd_test_all_computation_options().
svd_preallocate()
template<typename > void svd_preallocate ()
Definition at line 398 of file svd_common.h.
References v.
svd_test_all_computation_options()
template<typename SvdType , typename MatrixType > void svd_test_all_computation_options (const MatrixType & m, bool full_only)
Definition at line 227 of file svd_common.h.
References CALL_SUBTEST, Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::Dynamic, min, svd(), svd_check_full(), svd_compare_to_full(), svd_min_norm(), and VERIFY_IS_APPROX.
Referenced by bdcsvd(), and jacobisvd().
svd_underoverflow()
template<typename > void svd_underoverflow ()
Definition at line 320 of file svd_common.h.
References CALL_SUBTEST, Eigen::ComputeFullU, Eigen::ComputeFullV, M3(), svd(), svd_check_full(), and SVD_DEFAULT.
svd_verify_assert()
template<typename SvdType , typename MatrixType > void svd_verify_assert (const MatrixType & m)
Definition at line 437 of file svd_common.h.
References a, cols, Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::Dynamic, rows, svd(), SVD_DEFAULT, SVD_FOR_MIN_NORM, and VERIFY_RAISES_ASSERT.
Referenced by test_bdcsvd().
zero()
template<typename Scalar > EIGEN_DONT_INLINE Scalar zero ()
Definition at line 275 of file svd_common.h.
Referenced by array_complex(), array_special_functions(), drotm_(), drotmg_(), equalsIdentity(), Eigen::internal::pblend(), Eigen::internal::ptranspose(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::igammac_impl< Scalar >::run(), Eigen::internal::igamma_impl< Scalar >::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::internal::polygamma_impl< Scalar >::run(), Eigen::internal::betainc_impl< Scalar >::run(), srotm_(), and srotmg_().