pairinteraction: /travis/libpairinteraction/eigen/lapack/svd.cpp File Reference
svd.cpp File Reference
#include "lapack_common.h"
#include <Eigen/SVD>
Functions
EIGEN_LAPACK_FUNC (gesdd,(char *jobz, int *m, int *n, Scalar *a, int *lda, RealScalar *s, Scalar *u, int *ldu, Scalar *vt, int *ldvt, Scalar *, int *lwork, EIGEN_LAPACK_ARG_IF_COMPLEX(RealScalar *) int *, int *info))
EIGEN_LAPACK_FUNC (gesvd,(char *jobu, char *jobv, int *m, int *n, Scalar *a, int *lda, RealScalar *s, Scalar *u, int *ldu, Scalar *vt, int *ldvt, Scalar *, int *lwork, EIGEN_LAPACK_ARG_IF_COMPLEX(RealScalar *) int *info))
Function Documentation
EIGEN_LAPACK_FUNC() [1/2]
EIGEN_LAPACK_FUNC (gesdd , (char *jobz, int *m, int *n, Scalar *a, int *lda, RealScalar *s, Scalar *u, int *ldu, Scalar *vt, int *ldvt, Scalar *, int *lwork, EIGEN_LAPACK_ARG_IF_COMPLEX(RealScalar *) int *, int *info))
Definition at line 14 of file svd.cpp.
References Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, e(), info, m, make_vector(), mat, matrix(), Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixU(), Eigen::SVDBase< BDCSVD< _MatrixType > >::matrixV(), max, min, SCALAR_SUFFIX_UP, Eigen::SVDBase< BDCSVD< _MatrixType > >::singularValues(), svd(), and xerbla_().
EIGEN_LAPACK_FUNC() [2/2]
EIGEN_LAPACK_FUNC (gesvd , (char *jobu, char *jobv, int *m, int *n, Scalar *a, int *lda, RealScalar *s, Scalar *u, int *ldu, Scalar *vt, int *ldvt, Scalar *, int *lwork, EIGEN_LAPACK_ARG_IF_COMPLEX(RealScalar *) int *info))
Definition at line 85 of file svd.cpp.
References Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, e(), info, m, make_vector(), mat, matrix(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixU(), Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV(), max, min, SCALAR_SUFFIX_UP, Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::singularValues(), svd(), and xerbla_().