pairinteraction: /travis/libpairinteraction/eigen/unsupported/test/EulerAngles.cpp File Reference
EulerAngles.cpp File Reference
#include "main.h"
#include <unsupported/Eigen/EulerAngles>
Functions
template<typename EulerSystem , typename Scalar >
void verify_euler_ranged (const Matrix< Scalar, 3, 1 > &ea, bool positiveRangeAlpha, bool positiveRangeBeta, bool positiveRangeGamma)
template<typename EulerSystem , typename Scalar >
void verify_euler (const Matrix< Scalar, 3, 1 > &ea)
template<typename Scalar >
void check_all_var (const Matrix< Scalar, 3, 1 > &ea)
template<typename Scalar >
void eulerangles ()
void test_EulerAngles ()
Function Documentation
check_all_var()
template<typename Scalar > void check_all_var (const Matrix< Scalar, 3, 1 > & ea)
Definition at line 137 of file EulerAngles.cpp.
Referenced by eulerangles().
eulerangles()
template<typename Scalar > void eulerangles ()
Definition at line 155 of file EulerAngles.cpp.
References a, check_all_var(), EIGEN_PI, and m.
test_EulerAngles()
void test_EulerAngles ()
Definition at line 202 of file EulerAngles.cpp.
References i.
verify_euler()
template<typename EulerSystem , typename Scalar > void verify_euler (const Matrix< Scalar, 3, 1 > & ea)
Definition at line 125 of file EulerAngles.cpp.
verify_euler_ranged()
template<typename EulerSystem , typename Scalar > void verify_euler_ranged (const Matrix< Scalar, 3, 1 > & ea, bool positiveRangeAlpha, bool positiveRangeBeta, bool positiveRangeGamma)
Definition at line 17 of file EulerAngles.cpp.
References abs(), Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::AlphaAxisAbs, Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::BetaAxisAbs, e(), EIGEN_PI, Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::GammaAxisAbs, i, Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::IsAlphaOpposite, Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::IsBetaOpposite, Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::IsGammaOpposite, j, J, m, Eigen::numext::q, Eigen::test_isMuchSmallerThan(), VERIFY, and VERIFY_IS_APPROX.