pairinteraction: /travis/libpairinteraction/eigen/test/sparse_product.cpp File Reference
sparse_product.cpp File Reference
#include "sparse.h"
Macros
#define EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN { on_temporary_creation(); }
#define VERIFY_EVALUATION_COUNT(XPR, N)
Functions
void on_temporary_creation ()
template<typename SparseMatrixType >
void sparse_product ()
template<typename SparseMatrixType , typename DenseMatrixType >
void sparse_product_regression_test ()
template<typename Scalar >
void bug_942 ()
void test_sparse_product ()
Macro Definition Documentation
EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
#define EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN { on_temporary_creation(); }
Definition at line 17 of file sparse_product.cpp.
Referenced by Eigen::SparseMatrix< scalar_t >::operator=(), Eigen::SparseMatrix< scalar_t >::SparseMatrix(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector().
VERIFY_EVALUATION_COUNT
#define VERIFY_EVALUATION_COUNT (XPR, N)
Value:
{\
    nb_temporaries = 0; \
    CALL_SUBTEST( XPR ); \
    if(nb_temporaries!=N) std::cerr << "nb_temporaries == " << nb_temporaries << "\n"; \
    VERIFY( (#XPR) && nb_temporaries==N ); \
  }
Definition at line 21 of file sparse_product.cpp.
Referenced by call_ref(), cholesky(), ctor_init1(), matrixRedux(), permutationmatrices(), product_notemporary(), run_nesting_ops_2(), sparse_product(), and vectorwiseop_matrix().
Function Documentation
bug_942()
template<typename Scalar > void bug_942 ()
Definition at line 352 of file sparse_product.cpp.
References eval(), res, and VERIFY_IS_APPROX.
on_temporary_creation()
void on_temporary_creation () inline
Definition at line 12 of file sparse_product.cpp.
sparse_product()
template<typename SparseMatrixType > void sparse_product ()
Definition at line 30 of file sparse_product.cpp.
References b, c, cols, e(), eval(), ForceRealDiag, initSparse(), leftCols(), m2(), MakeUpperTriangular, max, n, rows, triangularView< Lower >(), v1(), v2(), VERIFY_EVALUATION_COUNT, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, and x.
sparse_product_regression_test()
template<typename SparseMatrixType , typename DenseMatrixType > void sparse_product_regression_test ()
Definition at line 330 of file sparse_product.cpp.
References m2(), and VERIFY_IS_APPROX.
test_sparse_product()
void test_sparse_product ()
Definition at line 374 of file sparse_product.cpp.
References i.