pairinteraction: /travis/libpairinteraction/eigen/test/cholesky.cpp File Reference
cholesky.cpp File Reference
#include "main.h"
#include <Eigen/Cholesky>
#include <Eigen/QR>
Macros
#define EIGEN_NO_ASSERTION_CHECKING
#define TEST_ENABLE_TEMPORARY_TRACKING
Functions
template<typename MatrixType , int UpLo>
MatrixType::RealScalar matrix_l1_norm (const MatrixType &m)
template<typename MatrixType , template< typename, int > class CholType>
void test_chol_update (const MatrixType &symm)
template<typename MatrixType >
void cholesky (const MatrixType &m)
template<typename MatrixType >
void cholesky_cplx (const MatrixType &m)
template<typename MatrixType >
void cholesky_bug241 (const MatrixType &m)
template<typename MatrixType >
void cholesky_definiteness (const MatrixType &m)
template<typename >
void cholesky_faillure_cases ()
template<typename MatrixType >
void cholesky_verify_assert ()
void test_cholesky ()
Macro Definition Documentation
EIGEN_NO_ASSERTION_CHECKING
#define EIGEN_NO_ASSERTION_CHECKING
Definition at line 11 of file cholesky.cpp.
TEST_ENABLE_TEMPORARY_TRACKING
#define TEST_ENABLE_TEMPORARY_TRACKING
Definition at line 14 of file cholesky.cpp.
Function Documentation
cholesky()
template<typename MatrixType > void cholesky (const MatrixType & m)
Definition at line 58 of file cholesky.cpp.
References a, c, cols, Eigen::Dynamic, Eigen::LDLT< _MatrixType, _UpLo >::info(), m1, m2(), matB(), Eigen::LLT< _MatrixType, _UpLo >::matrixL(), Eigen::LDLT< _MatrixType, _UpLo >::matrixL(), Eigen::LLT< _MatrixType, _UpLo >::matrixU(), Eigen::LDLT< _MatrixType, _UpLo >::matrixU(), min, Eigen::NumericalIssue, Eigen::ArrayBase< Derived >::pow(), Eigen::half_impl::pow(), Eigen::LLT< _MatrixType, _UpLo >::rcond(), Eigen::LDLT< _MatrixType, _UpLo >::rcond(), Eigen::LLT< _MatrixType, _UpLo >::reconstructedMatrix(), Eigen::LDLT< _MatrixType, _UpLo >::reconstructedMatrix(), rows, s, Eigen::PlainObjectBase< Derived >::setRandom(), Eigen::PlainObjectBase< Derived >::setZero(), sign(), Eigen::LLT< _MatrixType, _UpLo >::solve(), Eigen::LDLT< _MatrixType, _UpLo >::solve(), sqrt(), Eigen::Success, symm(), triangularView< Lower >(), VERIFY, VERIFY_EVALUATION_COUNT, and VERIFY_IS_APPROX.
Referenced by Action_cholesky< Interface >::calculate(), cholesky_cplx(), and test_boostmultiprec().
cholesky_bug241()
template<typename MatrixType > void cholesky_bug241 (const MatrixType & m)
Definition at line 346 of file cholesky.cpp.
References eigen_assert, matA(), and VERIFY_IS_APPROX.
cholesky_cplx()
template<typename MatrixType > void cholesky_cplx (const MatrixType & m)
Definition at line 285 of file cholesky.cpp.
References cholesky(), cols, matB(), rows, sign(), Eigen::Success, symm(), triangularView< Lower >(), VERIFY, and VERIFY_IS_APPROX.
cholesky_definiteness()
template<typename MatrixType > void cholesky_definiteness (const MatrixType & m)
Definition at line 364 of file cholesky.cpp.
References Eigen::LDLT< _MatrixType, _UpLo >::compute(), eigen_assert, Eigen::LDLT< _MatrixType, _UpLo >::info(), Eigen::LDLT< _MatrixType, _UpLo >::isNegative(), Eigen::LDLT< _MatrixType, _UpLo >::isPositive(), mat, Eigen::Success, and VERIFY.
cholesky_faillure_cases()
template<typename > void cholesky_faillure_cases ()
Definition at line 408 of file cholesky.cpp.
References Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::info(), mat, Eigen::NumericalIssue, Eigen::LDLT< _MatrixType, _UpLo >::reconstructedMatrix(), VERIFY, and VERIFY_IS_NOT_APPROX.
cholesky_verify_assert()
template<typename MatrixType > void cholesky_verify_assert ()
Definition at line 457 of file cholesky.cpp.
References Eigen::LLT< _MatrixType, _UpLo >::matrixL(), Eigen::LLT< _MatrixType, _UpLo >::matrixU(), Eigen::LLT< _MatrixType, _UpLo >::solve(), Eigen::LLT< _MatrixType, _UpLo >::solveInPlace(), and VERIFY_RAISES_ASSERT.
matrix_l1_norm()
template<typename MatrixType , int UpLo> MatrixType::RealScalar matrix_l1_norm (const MatrixType & m)
Definition at line 21 of file cholesky.cpp.
References symm().
test_chol_update()
template<typename MatrixType , template< typename, int > class CholType> void test_chol_update (const MatrixType & symm)
Definition at line 26 of file cholesky.cpp.
References Eigen::Success, symm(), triangularView< Lower >(), and VERIFY_IS_APPROX.
test_cholesky()
void test_cholesky ()
Definition at line 477 of file cholesky.cpp.
References i, and s.