pairinteraction: /travis/libpairinteraction/eigen/test/triangular.cpp File Reference
triangular.cpp File Reference
#include "main.h"
Functions
template<typename MatrixType >
void triangular_square (const MatrixType &m)
template<typename MatrixType >
void triangular_rect (const MatrixType &m)
void bug_159 ()
void test_triangular ()
Function Documentation
bug_159()
void bug_159 ()
Definition at line 218 of file triangular.cpp.
References EIGEN_UNUSED_VARIABLE, Eigen::Lower, and m.
test_triangular()
void test_triangular ()
Definition at line 224 of file triangular.cpp.
References EIGEN_TEST_MAX_SIZE, i, maxsize, and min.
triangular_rect()
template<typename MatrixType > void triangular_rect (const MatrixType & m)
Definition at line 135 of file triangular.cpp.
References cols, m1, m2(), rows, setOnes(), swap(), triangularView< Lower >(), VERIFY, and VERIFY_IS_APPROX.
triangular_square()
template<typename MatrixType > void triangular_square (const MatrixType & m)
Definition at line 14 of file triangular.cpp.
References abs2(), cols, e(), i, m1, m2(), rows, setOnes(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom(), swap(), triangularView< Lower >(), v2(), VERIFY, and VERIFY_IS_APPROX.