pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/Tutorial_ReshapeMat2Vec.cpp File Reference
Tutorial_ReshapeMat2Vec.cpp File Reference
Functions
MatrixXf M1 (3, 3)
M1<< 1, 2, 3, 4, 5, 6, 7, 8, 9;Map< RowVectorXf > v1 (M1.data(), M1.size())
cout<< "v1:"<< endl<< v1<< endl;Matrix< float, Dynamic, Dynamic, RowMajor > M2 (M1)
Map< RowVectorXf > v2 (M2.data(), M2.size())
Function Documentation
M1()
MatrixXf M1 (3 , 3)
M2()
cout<< "v1:" << endl << v1 << endl;Matrix<float,Dynamic,Dynamic,RowMajor> M2 (M1)
v1()
M1<< 1, 2, 3, 4, 5, 6, 7, 8, 9;Map<RowVectorXf> v1 (M1. data(), M1. size())
Referenced by adjoint(), Eigen::array< Index, ContractDims >::array(), basicStuff(), block(), bug890(), bug_1264(), diagonalmatrices(), mpfr::mpreal::get_default_prec(), Eigen::KdBVH< _Scalar, _Dim, _Object >::getVolume(), householder(), integer_type_tests(), main(), mapQuaternion(), memoryleak(), miscMatrices(), non_projective_only(), orthomethods_3(), planes(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pmul< Packet2cf >(), product(), product_extra(), product_selfadjoint(), Eigen::internal::pscatter< std::complex< double >, Packet1cd >(), Eigen::internal::ptranspose(), quaternion(), ref_vector(), replicate(), reverse(), adjoint_specific< true >::run(), adjoint_specific< false >::run(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::setFromTwoVectors(), sparse_block(), sparse_product(), sparse_vector(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Through(), transform_associativity(), transformations(), trmv(), unaligned_objects(), and vectorVisitor().
v2()
Map<RowVectorXf> v2 (M2. data(), M2. size())
Referenced by adjoint(), Eigen::array< Index, ContractDims >::array(), bug890(), bug_1264(), diagonalmatrices(), mpfr::mpreal::get_default_prec(), Eigen::KdBVH< _Scalar, _Dim, _Object >::getVolume(), householder(), integer_type_tests(), main(), orthomethods_3(), planes(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::pmul< Packet2cf >(), product_selfadjoint(), Eigen::internal::pscatter< std::complex< double >, Packet1cd >(), Eigen::internal::ptranspose(), quaternion(), ref_vector(), adjoint_specific< false >::run(), smallVectors(), sparse_product(), sparse_vector(), test_evaluators(), transform_associativity(), triangular_square(), unaligned_objects(), and vectorVisitor().