pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/Tutorial_AdvancedInitialization_CommaTemporary.cpp File Reference
Tutorial_AdvancedInitialization_CommaTemporary.cpp File Reference
Variables
MatrixXf mat = MatrixXf::Random(2, 3)
Variable Documentation
mat
MatrixXf mat = MatrixXf::Random(2, 3)
Definition at line 1 of file Tutorial_AdvancedInitialization_CommaTemporary.cpp.
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), Eigen::internal::apply_block_householder_on_the_left(), MatrixReplacement::attachMyMatrix(), benchBasic_loop(), HamiltonianOne::build(), cholesky_definiteness(), cholesky_faillure_cases(), combine(), Eigen::IncompleteLU< _Scalar >::compute(), Eigen::IterScaling< _MatrixType >::compute(), Eigen::SPQR< _MatrixType >::compute(), Eigen::SparseQR< _MatrixType, _OrderingType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), eigen33(), EIGEN_LAPACK_FUNC(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::internal::generic_matrix_wrapper< MatrixType, false >::grab(), Eigen::internal::generic_matrix_wrapper< MatrixType, true >::grab(), Eigen::PastixBase< PastixLU< _MatrixType > >::info(), initMatrix_random(), inverse_general_4x4(), GpuHelper::loadMatrix(), main(), Eigen::SluMatrix::Map(), Eigen::Matrix< Scalar, Deg, 1 >::operator=(), internal::selfadjoint_packed_rank1_update< Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 1, IsComplex >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::run(), Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::run(), setinnerrand_eigen(), Eigen::DGMRES< _MatrixType, _Preconditioner >::setMaxEigenv(), setrand_eigen_compact(), setrand_eigen_dynamic(), setrand_eigen_gnu_hash(), setrand_eigen_google_dense(), setrand_eigen_google_sparse(), setrand_eigen_sumeq(), setrand_scipy(), setrand_ublas_genvec(), setrand_ublas_mapped(), numpy::internal::sparse_impl(), sparse_permutations(), test_evaluators(), trmm(), use_n_times(), and Eigen::viewAsCholmod().