pairinteraction: /travis/libpairinteraction/eigen/doc/special_examples/Tutorial_sparse_example_details.cpp File Reference
Tutorial_sparse_example_details.cpp File Reference
#include <Eigen/Sparse>
#include <vector>
#include <QImage>
Typedefs
typedef Eigen::SparseMatrix< double > SpMat
typedef Eigen::Triplet< double > T
Functions
void insertCoefficient (int id, int i, int j, double w, std::vector< T > &coeffs, Eigen::VectorXd &b, const Eigen::VectorXd &boundary)
void buildProblem (std::vector< T > &coefficients, Eigen::VectorXd &b, int n)
void saveAsBitmap (const Eigen::VectorXd &x, int n, const char *filename)
Typedef Documentation
SpMat
typedef Eigen::SparseMatrix<double> SpMat
Definition at line 5 of file Tutorial_sparse_example_details.cpp.
T
typedef Eigen::Triplet<double> T
Definition at line 6 of file Tutorial_sparse_example_details.cpp.
Function Documentation
buildProblem()
void buildProblem (std::vector< T > & coefficients, Eigen::VectorXd & b, int n)
Definition at line 19 of file Tutorial_sparse_example_details.cpp.
References i, insertCoefficient(), j, M_PI, and n.
Referenced by main().
insertCoefficient()
void insertCoefficient (int id, int i, int j, double w, std::vector< T > & coeffs, Eigen::VectorXd & b, const Eigen::VectorXd & boundary)
Definition at line 8 of file Tutorial_sparse_example_details.cpp.
References b, int(), and n.
Referenced by buildProblem().
saveAsBitmap()
void saveAsBitmap (const Eigen::VectorXd & x, int n, const char * filename)
Definition at line 37 of file Tutorial_sparse_example_details.cpp.
References Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), i, and n.
Referenced by main().