pairinteraction: /travis/libpairinteraction/eigen/doc/snippets/Tutorial_SlicingCol.cpp File Reference
Tutorial_SlicingCol.cpp File Reference
Functions
cout<< "Column major input:"<< endl<< M1<< "\";Map< MatrixXf, 0, OuterStride<> > M2 (M1.data(), M1.rows(),(M1.cols()+2)/3, OuterStride<>(M1.outerStride() *3))
RowMajorMatrixXf M3 (M1)
cout<< "Row major input:"<< endl<< M3<< "\";Map< RowMajorMatrixXf, 0, Stride< Dynamic, 3 > > M4 (M3.data(), M3.rows(),(M3.cols()+2)/3, Stride< Dynamic, 3 >(M3.outerStride(), 3))
Variables
cout<< "1 column over 3:"<< endl<< M2<< "\";typedef Matrix< float, Dynamic, Dynamic, RowMajor > RowMajorMatrixXf
MatrixXf M1 = MatrixXf::Random(3,8)
Function Documentation
M2()
cout<< "Column major input:" << endl << M1 << "\n";Map<MatrixXf,0,OuterStride<> > M2 (M1. data(), M1. rows(), (M1.cols()+2)/ 3, OuterStride<> M1.outerStride() *3)
M3()
RowMajorMatrixXf M3 (M1)
Referenced by svd_underoverflow().
M4()
cout<< "Row major input:" << endl << M3 << "\n";Map<RowMajorMatrixXf,0,Stride<Dynamic,3> > M4 (M3. data(), M3. rows(), (M3.cols()+2)/ 3, Stride< Dynamic, 3 > M3.outerStride(), 3)
Variable Documentation
M1
MatrixXf M1 = MatrixXf::Random(3,8)
Definition at line 1 of file Tutorial_SlicingCol.cpp.
Referenced by test_blocks(), and test_nomalloc().
RowMajorMatrixXf
cout<< "1 column over 3:" << endl << M2 << "\n";typedef Matrix<float,Dynamic,Dynamic,RowMajor> RowMajorMatrixXf
Definition at line 6 of file Tutorial_SlicingCol.cpp.