pairinteraction: /travis/libpairinteraction/eigen/test/umeyama.cpp File Reference
umeyama.cpp File Reference
#include "main.h"
#include <Eigen/Core>
#include <Eigen/Geometry>
#include <Eigen/LU>
#include <Eigen/SVD>
Functions
template<typename T >
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > randMatrixUnitary (int size)
template<typename T >
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > randMatrixSpecialUnitary (int size)
template<typename MatrixType >
void run_test (int dim, int num_elements)
template<typename Scalar , int Dimension>
void run_fixed_size_test (int num_elements)
void test_umeyama ()
Function Documentation
randMatrixSpecialUnitary()
template<typename T > Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> randMatrixSpecialUnitary (int size)
Definition at line 75 of file umeyama.cpp.
References conj(), Q, and size.
randMatrixUnitary()
template<typename T > Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> randMatrixUnitary (int size)
Definition at line 22 of file umeyama.cpp.
References col(), eigen_assert, Q, row(), and size.
run_fixed_size_test()
template<typename Scalar , int Dimension> void run_fixed_size_test (int num_elements)
Definition at line 121 of file umeyama.cpp.
References abs(), c, mpfr::dim(), Eigen::umeyama(), and VERIFY.
run_test()
template<typename MatrixType > void run_test (int dim, int num_elements)
Definition at line 91 of file umeyama.cpp.
References abs(), c, mpfr::dim(), Eigen::umeyama(), and VERIFY.
test_umeyama()
void test_umeyama ()
Definition at line 158 of file umeyama.cpp.
References mpfr::dim(), and i.