pairinteraction: /travis/libpairinteraction/eigen/test/vectorization_logic.cpp File Reference
vectorization_logic.cpp File Reference
#include "main.h"
#include <typeinfo>
Data Structures
struct vectorization_logic< Scalar, Enable >
struct vectorization_logic< Scalar, false >
struct vectorization_logic_half< Scalar, Enable >
struct vectorization_logic_half< Scalar, false >
Macros
#define EIGEN_DEBUG_ASSIGN
Functions
template<typename Dst , typename Src >
bool test_assign (const Dst &, const Src &, int traversal, int unrolling)
template<typename Dst , typename Src >
bool test_assign (int traversal, int unrolling)
template<typename Xpr >
bool test_redux (const Xpr &, int traversal, int unrolling)
void test_vectorization_logic ()
Macro Definition Documentation
EIGEN_DEBUG_ASSIGN
#define EIGEN_DEBUG_ASSIGN
Definition at line 21 of file vectorization_logic.cpp.
Function Documentation
test_assign() [1/2]
template<typename Dst , typename Src > bool test_assign (const Dst & , const Src & , int traversal, int unrolling)
Definition at line 30 of file vectorization_logic.cpp.
References Eigen::CompleteUnrolling, Eigen::InnerUnrolling, int(), and res.
Referenced by vectorization_logic< Scalar, Enable >::run(), vectorization_logic_half< Scalar, Enable >::run(), and test_vectorization_logic().
test_assign() [2/2]
template<typename Dst , typename Src > bool test_assign (int traversal, int unrolling)
Definition at line 54 of file vectorization_logic.cpp.
References res.
test_redux()
template<typename Xpr > bool test_redux (const Xpr & , int traversal, int unrolling)
Definition at line 74 of file vectorization_logic.cpp.
References res.
Referenced by vectorization_logic< Scalar, Enable >::run(), vectorization_logic_half< Scalar, Enable >::run(), and test_vectorization_logic().
test_vectorization_logic()
void test_vectorization_logic ()
Definition at line 383 of file vectorization_logic.cpp.
References CALL_SUBTEST, Eigen::CompleteUnrolling, Eigen::DefaultTraversal, EIGEN_UNALIGNED_VECTORIZE, Eigen::LinearTraversal, Eigen::LinearVectorizedTraversal, vectorization_logic< Scalar, Enable >::run(), test_assign(), test_redux(), and VERIFY.