pairinteraction: /travis/libpairinteraction/eigen/test/visitor.cpp File Reference
visitor.cpp File Reference
#include "main.h"
Functions
template<typename MatrixType >
void matrixVisitor (const MatrixType &p)
template<typename VectorType >
void vectorVisitor (const VectorType &w)
void test_visitor ()
Function Documentation
matrixVisitor()
template<typename MatrixType > void matrixVisitor (const MatrixType & p)
Definition at line 12 of file visitor.cpp.
References cols, eval(), i, j, m, rows, VERIFY, and VERIFY_IS_APPROX.
test_visitor()
void test_visitor ()
Definition at line 118 of file visitor.cpp.
References i.
vectorVisitor()
template<typename VectorType > void vectorVisitor (const VectorType & w)
Definition at line 65 of file visitor.cpp.
References i, min, size, v, v1(), v2(), VERIFY, and VERIFY_IS_APPROX.