pairinteraction: /travis/libpairinteraction/Wavefunction.h File Reference
Wavefunction.h File Reference
#include <string>
#include <vector>
#include "dtypes.h"
#include "QuantumDefect.h"
Data Structures
class Numerov
Numerov's method
class Whittaker
Namespaces
model_potential
whittaker_functions
Functions
double model_potential::V (QuantumDefect const &qd, double x)
Calculate the model potentials.
double model_potential::g (QuantumDefect const &qd, double x)
Helper function for Numerov's method.s.
double whittaker_functions::HypergeometricU (double a, double b, double z)
Compute the confluent hypergeometric function.
double whittaker_functions::WhittakerW (double k, double m, double z)
Compute the Whittaker function.
double whittaker_functions::RadialWFWhittaker (double r, double nu, int l)
Radial wavefunctions from Whittaker's function.
template<typename T >
int findidx (T const &x, typename T::Scalar const &d)
Find and return index.
template<typename T >
double IntegrateRadialElement (QuantumDefect const &qd1, int power, QuantumDefect const &qd2)
Compute radial matrix elements.
Function Documentation
findidx()
template<typename T > int findidx (T const & x, typename T::Scalar const & d)
Find and return index.
Find a value in an Eigen matrix and return its index in the container to the caller. This is intended to work with Eigen::Vector or columns of Eigen::Matrix.
Parameters
[in] x An Eigen matrix type
[in] d value to find
Returns
index of d
Exceptions
std::runtime_error if the value can't be found
Definition at line 228 of file Wavefunction.h.
References L, m, and x.
Referenced by IntegrateRadialElement().
IntegrateRadialElement()
template<typename T > double IntegrateRadialElement (QuantumDefect const & qd1, int power, QuantumDefect const & qd2)
Compute radial matrix elements.
The radial matrix element can be calculated from the integral
\[ \langle nlj| \hat{p}^{\mathrm{rad}}_\kappa |n'l'j' \rangle = \int \Psi^{\text{rad}}_{nlj}(r) \Psi^{\text{rad}}_{n'l'j'}(r) r^{2+\kappa} \; dr \]
The part \(r^{2+\kappa} \) varies with rescaling the domain and is this given by the power_kernel function.
Template Parameters
T Method for calculating the wavefunction
Parameters
[in] qd1 Quantum defect data for first atom
[in] power Exponent kappa
[in] qd2 Quantum defect data for second atom
Returns
Radial matrix element
Definition at line 258 of file Wavefunction.h.
References au2GHz, au2um, au2Vcm, findidx(), and Eigen::half_impl::pow().