pairinteraction: /travis/libpairinteraction/eigen/blas/xerbla.cpp File Reference
xerbla.cpp File Reference
#include <stdio.h>
Macros
#define EIGEN_WEAK_LINKING
Functions
EIGEN_WEAK_LINKING int xerbla_ (const char *msg, int *info, int)
Macro Definition Documentation
EIGEN_WEAK_LINKING
#define EIGEN_WEAK_LINKING
Definition at line 7 of file xerbla.cpp.
Function Documentation
xerbla_()
EIGEN_WEAK_LINKING int xerbla_ (const char * msg, int * info, int)
Definition at line 15 of file xerbla.cpp.
Referenced by chbmv_(), chpmv_(), dsbmv_(), dspmv_(), EIGEN_LAPACK_FUNC(), gemm(), gemv(), ger(), gerc(), geru(), hemv(), her(), her2(), hpr(), hpr2(), lda(), spr(), spr2(), ssbmv_(), sspmv_(), symm(), symv(), syr(), syr2(), syr2k(), syrk(), tbsv(), tpmv(), tpsv(), trmm(), trmv(), trsm(), trsv(), zhbmv_(), and zhpmv_().