pairinteraction: /travis/libpairinteraction/eigen/blas/testing/zblat2.f File Reference
zblat2.f File Reference
Functions/Subroutines
program zblat2
ZBLAT2
subroutine zchk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine zchk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NALF, ALF, NBET, BET, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G)
subroutine zchk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NKB, KB, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, XT, G, Z)
subroutine zchk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine zchk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine zchk6 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NINC, INC, NMAX, INCMAX, A, AA, AS, X, XX, XS, Y, YY, YS, YT, G, Z)
subroutine zchke (ISNUM, SRNAMT, NOUT)
subroutine zmake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, KL, KU, RESET, TRANSL)
subroutine zmvch (TRANS, M, N, ALPHA, A, NMAX, X, INCX, BETA, Y, INCY, YT, G, YY, EPS, ERR, FATAL, NOUT, MV)
logical function lze (RI, RJ, LR)
logical function lzeres (TYPE, UPLO, M, N, AA, AS, LDA)
complex *16 function zbeg (RESET)
double precision function ddiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 3207 of file zblat2.f.
ddiff()
double precision function ddiff (double precision X, double precision Y)
Definition at line 3191 of file zblat2.f.
References ddiff().
lze()
logical function lze (complex*16, dimension(*) RI, complex*16, dimension(*) RJ, integer LR)
Definition at line 3050 of file zblat2.f.
Referenced by lze().
lzeres()
logical function lzeres (character*2 TYPE, character*1 UPLO, integer M, integer N, complex*16, dimension(lda, *) AA, complex*16, dimension(lda, *) AS, integer LDA)
Definition at line 3080 of file zblat2.f.
Referenced by lzeres().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 3235 of file zblat2.f.
zbeg()
complex*16 function zbeg (logical RESET)
Definition at line 3139 of file zblat2.f.
Referenced by zbeg().
zblat2()
program zblat2 ()
ZBLAT2
Purpose:
 Test program for the COMPLEX*16       Level 2 Blas.
 The program must be driven by a short data file. The first 18 records
 of the file are read using list-directed input, the last 17 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 35 lines:
 'zblat2.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'CBLA2T.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 4                 NUMBER OF VALUES OF K
 0 1 2 4           VALUES OF K
 4                 NUMBER OF VALUES OF INCX AND INCY
 1 2 -1 -2         VALUES OF INCX AND INCY
 3                 NUMBER OF VALUES OF ALPHA
 (0.0,0.0) (1.0,0.0) (0.7,-0.9)       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 (0.0,0.0) (1.0,0.0) (1.3,-1.1)       VALUES OF BETA
 ZGEMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZGBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHEMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTRMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTBMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTPMV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTRSV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTBSV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTPSV  T PUT F FOR NO TEST. SAME COLUMNS.
 ZGERC  T PUT F FOR NO TEST. SAME COLUMNS.
 ZGERU  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHER   T PUT F FOR NO TEST. SAME COLUMNS.
 ZHPR   T PUT F FOR NO TEST. SAME COLUMNS.
 ZHER2  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHPR2  T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
    See:
       Dongarra J. J., Du Croz J. J., Hammarling S.  and Hanson R. J..
       An  extended  set of Fortran  Basic Linear Algebra Subprograms.
       Technical  Memoranda  Nos. 41 (revision 3) and 81,  Mathematics
       and  Computer Science  Division,  Argonne  National Laboratory,
       9700 South Cass Avenue, Argonne, Illinois 60439, US.
       Or
       NAG  Technical Reports TR3/87 and TR4/87,  Numerical Algorithms
       Group  Ltd.,  NAG  Central  Office,  256  Banbury  Road, Oxford
       OX2 7DE, UK,  and  Numerical Algorithms Group Inc.,  1101  31st
       Street,  Suite 100,  Downers Grove,  Illinois 60515-1263,  USA.
 -- Written on 10-August-1987.
    Richard Hanson, Sandia National Labs.
    Jeremy Du Croz, NAG Central Office.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 104 of file zblat2.f.
References abs, max, min, p, x, y, zchk1(), zchk2(), zchk3(), zchk4(), zchk5(), zchk6(), zchke(), and zmvch().
zchk1()
subroutine zchk1 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, complex*16, dimension(nalf) ALF, integer NBET, complex*16, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax) X, complex*16, dimension(nmax*incmax) XX, complex*16, dimension(nmax*incmax) XS, complex*16, dimension(nmax) Y, complex*16, dimension(nmax*incmax) YY, complex*16, dimension(nmax*incmax) YS, complex*16, dimension(nmax) YT, double precision, dimension(nmax) G)
Definition at line 442 of file zblat2.f.
References abs, lda, m, max, min, n, x, y, zgbmv(), zgemv(), zmake(), and zmvch().
Referenced by zblat2(), and zblat3().
zchk2()
subroutine zchk2 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NALF, complex*16, dimension(nalf) ALF, integer NBET, complex*16, dimension(nbet) BET, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax) X, complex*16, dimension(nmax*incmax) XX, complex*16, dimension(nmax*incmax) XS, complex*16, dimension(nmax) Y, complex*16, dimension(nmax*incmax) YY, complex*16, dimension(nmax*incmax) YS, complex*16, dimension(nmax) YT, double precision, dimension(nmax) G)
Definition at line 788 of file zblat2.f.
References abs, lda, max, n, x, y, zhbmv(), zhemv(), zhpmv(), zmake(), and zmvch().
Referenced by zblat2(), and zblat3().
zchk3()
subroutine zchk3 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NKB, integer, dimension(nkb) KB, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax) X, complex*16, dimension(nmax*incmax) XX, complex*16, dimension(nmax*incmax) XS, complex*16, dimension(nmax) XT, double precision, dimension(nmax) G, complex*16, dimension(nmax) Z)
Definition at line 1136 of file zblat2.f.
References abs, lda, max, n, x, zmake(), zmvch(), ztbmv(), ztbsv(), ztpmv(), ztpsv(), ztrmv(), and ztrsv().
Referenced by zblat2(), and zblat3().
zchk4()
subroutine zchk4 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax) X, complex*16, dimension(nmax*incmax) XX, complex*16, dimension(nmax*incmax) XS, complex*16, dimension(nmax) Y, complex*16, dimension(nmax*incmax) YY, complex*16, dimension(nmax*incmax) YS, complex*16, dimension(nmax) YT, double precision, dimension(nmax) G, complex*16, dimension(nmax) Z)
Definition at line 1499 of file zblat2.f.
References abs, j, lda, m, max, min, n, x, y, zgerc(), zgeru(), zmake(), and zmvch().
Referenced by zblat2(), and zblat3().
zchk5()
subroutine zchk5 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax) X, complex*16, dimension(nmax*incmax) XX, complex*16, dimension(nmax*incmax) XS, complex*16, dimension(nmax) Y, complex*16, dimension(nmax*incmax) YY, complex*16, dimension(nmax*incmax) YS, complex*16, dimension(nmax) YT, double precision, dimension(nmax) G, complex*16, dimension(nmax) Z)
Definition at line 1777 of file zblat2.f.
References abs, lda, max, n, x, y, zher(), zhpr(), zmake(), and zmvch().
Referenced by zblat2(), and zblat3().
zchk6()
subroutine zchk6 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NINC, integer, dimension(ninc) INC, integer NMAX, integer INCMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax) X, complex*16, dimension(nmax*incmax) XX, complex*16, dimension(nmax*incmax) XS, complex*16, dimension(nmax) Y, complex*16, dimension(nmax*incmax) YY, complex*16, dimension(nmax*incmax) YS, complex*16, dimension(nmax) YT, double precision, dimension(nmax) G, complex*16, dimension(nmax, 2) Z)
Definition at line 2062 of file zblat2.f.
References abs, j, lda, max, n, x, y, zher2(), zhpr2(), zmake(), and zmvch().
Referenced by zblat2().
zchke()
subroutine zchke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 2382 of file zblat2.f.
References chkxer(), zgbmv(), zgemv(), zgerc(), zgeru(), zhbmv(), zhemv(), zher(), zher2(), zhpmv(), zhpr(), zhpr2(), ztbmv(), ztbsv(), ztpmv(), ztpsv(), ztrmv(), and ztrsv().
Referenced by zblat2(), and zblat3().
zmake()
subroutine zmake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, complex*16, dimension(nmax, *) A, integer NMAX, complex*16, dimension(*) AA, integer LDA, integer KL, integer KU, logical RESET, complex*16 TRANSL)
Definition at line 2726 of file zblat2.f.
References max, and min.
Referenced by zchk1(), zchk2(), zchk3(), zchk4(), zchk5(), and zchk6().
zmvch()
subroutine zmvch (character*1 TRANS, integer M, integer N, complex*16 ALPHA, complex*16, dimension(nmax, *) A, integer NMAX, complex*16, dimension(*) X, integer INCX, complex*16 BETA, complex*16, dimension(*) Y, integer INCY, complex*16, dimension(*) YT, double precision, dimension(*) G, complex*16, dimension(*) YY, double precision EPS, double precision ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 2919 of file zblat2.f.
References abs, max, and sqrt().
Referenced by zblat2(), zchk1(), zchk2(), zchk3(), zchk4(), zchk5(), and zchk6().