pairinteraction: /travis/libpairinteraction/eigen/blas/testing/zblat1.f File Reference
zblat1.f File Reference
Functions/Subroutines
program zblat1
ZBLAT1
subroutine header
subroutine check1 (SFAC)
subroutine check2 (SFAC)
subroutine stest (LEN, SCOMP, STRUE, SSIZE, SFAC)
subroutine stest1 (SCOMP1, STRUE1, SSIZE, SFAC)
double precision function sdiff (SA, SB)
subroutine ctest (LEN, CCOMP, CTRUE, CSIZE, SFAC)
subroutine itest1 (ICOMP, ITRUE)
Function/Subroutine Documentation
check1()
subroutine check1 (double precision SFAC)
Definition at line 119 of file zblat1.f.
References ctest(), itest1(), max, stest1(), zdscal(), and zscal().
check2()
subroutine check2 (double precision SFAC)
Definition at line 320 of file zblat1.f.
References abs, ctest(), min, zaxpy(), zcopy(), and zswap().
ctest()
subroutine ctest (integer LEN, complex*16, dimension(len) CCOMP, complex*16, dimension(len) CTRUE, complex*16, dimension(len) CSIZE, double precision SFAC)
Definition at line 655 of file zblat1.f.
References stest().
header()
subroutine header ()
Definition at line 91 of file zblat1.f.
References x.
itest1()
subroutine itest1 (integer ICOMP, integer ITRUE)
Definition at line 686 of file zblat1.f.
References x.
sdiff()
double precision function sdiff (double precision SA, double precision SB)
Definition at line 645 of file zblat1.f.
References sdiff().
stest()
subroutine stest (integer LEN, double precision, dimension(len) SCOMP, double precision, dimension(len) STRUE, double precision, dimension(len) SSIZE, double precision SFAC)
Definition at line 564 of file zblat1.f.
References abs, and x.
stest1()
subroutine stest1 (double precision SCOMP1, double precision STRUE1, double precision, dimension(*) SSIZE, double precision SFAC)
Definition at line 620 of file zblat1.f.
References stest().
zblat1()
program zblat1 ()
ZBLAT1
Purpose:
    Test program for the COMPLEX*16 Level 1 BLAS.
    Based upon the original BLAS test routine together with:
    F06GAF Example Program Text
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 38 of file zblat1.f.
References check1(), check2(), header(), and x.