pairinteraction: /travis/libpairinteraction/eigen/blas/testing/zblat3.f File Reference
zblat3.f File Reference
Functions/Subroutines
program zblat3
ZBLAT3
subroutine zchk1 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine zchk2 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine zchk3 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NMAX, A, AA, AS, B, BB, BS, CT, G, C)
subroutine zchk4 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, A, AA, AS, B, BB, BS, C, CC, CS, CT, G)
subroutine zchk5 (SNAME, EPS, THRESH, NOUT, NTRA, TRACE, REWI, FATAL, NIDIM, IDIM, NALF, ALF, NBET, BET, NMAX, AB, AA, AS, BB, BS, C, CC, CS, CT, G, W)
subroutine zchke (ISNUM, SRNAMT, NOUT)
subroutine zmake (TYPE, UPLO, DIAG, M, N, A, NMAX, AA, LDA, RESET, TRANSL)
subroutine zmmch (TRANSA, TRANSB, M, N, KK, ALPHA, A, LDA, B, LDB, BETA, C, LDC, CT, G, CC, LDCC, EPS, ERR, FATAL, NOUT, MV)
logical function lze (RI, RJ, LR)
logical function lzeres (TYPE, UPLO, M, N, AA, AS, LDA)
complex *16 function zbeg (RESET)
double precision function ddiff (X, Y)
subroutine chkxer (SRNAMT, INFOT, NOUT, LERR, OK)
subroutine xerbla (SRNAME, INFO)
Function/Subroutine Documentation
chkxer()
subroutine chkxer (character*6 SRNAMT, integer INFOT, integer NOUT, logical LERR, logical OK)
Definition at line 3418 of file zblat3.f.
ddiff()
double precision function ddiff (double precision X, double precision Y)
Definition at line 3399 of file zblat3.f.
References ddiff().
lze()
logical function lze (complex*16, dimension(*) RI, complex*16, dimension(*) RJ, integer LR)
Definition at line 3252 of file zblat3.f.
References lze().
lzeres()
logical function lzeres (character*2 TYPE, character*1 UPLO, integer M, integer N, complex*16, dimension(lda, *) AA, complex*16, dimension(lda, *) AS, integer LDA)
Definition at line 3284 of file zblat3.f.
References lzeres().
xerbla()
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 3448 of file zblat3.f.
zbeg()
complex*16 function zbeg (logical RESET)
Definition at line 3345 of file zblat3.f.
References zbeg().
zblat3()
program zblat3 ()
ZBLAT3
Purpose:
 Test program for the COMPLEX*16       Level 3 Blas.
 The program must be driven by a short data file. The first 14 records
 of the file are read using list-directed input, the last 9 records
 are read using the format ( A6, L2 ). An annotated example of a data
 file can be obtained by deleting the first 3 characters from the
 following 23 lines:
 'zblat3.out'      NAME OF SUMMARY OUTPUT FILE
 6                 UNIT NUMBER OF SUMMARY FILE
 'ZBLAT3.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
 -1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
 F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
 F        LOGICAL FLAG, T TO STOP ON FAILURES.
 T        LOGICAL FLAG, T TO TEST ERROR EXITS.
 16.0     THRESHOLD VALUE OF TEST RATIO
 6                 NUMBER OF VALUES OF N
 0 1 2 3 5 9       VALUES OF N
 3                 NUMBER OF VALUES OF ALPHA
 (0.0,0.0) (1.0,0.0) (0.7,-0.9)       VALUES OF ALPHA
 3                 NUMBER OF VALUES OF BETA
 (0.0,0.0) (1.0,0.0) (1.3,-1.1)       VALUES OF BETA
 ZGEMM  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHEMM  T PUT F FOR NO TEST. SAME COLUMNS.
 ZSYMM  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTRMM  T PUT F FOR NO TEST. SAME COLUMNS.
 ZTRSM  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHERK  T PUT F FOR NO TEST. SAME COLUMNS.
 ZSYRK  T PUT F FOR NO TEST. SAME COLUMNS.
 ZHER2K T PUT F FOR NO TEST. SAME COLUMNS.
 ZSYR2K T PUT F FOR NO TEST. SAME COLUMNS.
 Further Details
 ===============
 See:
    Dongarra J. J., Du Croz J. J., Duff I. S. and Hammarling S.
    A Set of Level 3 Basic Linear Algebra Subprograms.
    Technical Memorandum No.88 (Revision 1), Mathematics and
    Computer Science Division, Argonne National Laboratory, 9700
    South Cass Avenue, Argonne, Illinois 60439, US.
 -- Written on 8-February-1989.
    Jack Dongarra, Argonne National Laboratory.
    Iain Duff, AERE Harwell.
    Jeremy Du Croz, Numerical Algorithms Group Ltd.
    Sven Hammarling, Numerical Algorithms Group Ltd.
    10-9-00:  Change STATUS='NEW' to 'UNKNOWN' so that the testers
              can be run multiple times without deleting generated
              output files (susan)
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
April 2012
Definition at line 87 of file zblat3.f.
References a, c, max, min, p, w, x, zchk1(), zchk2(), zchk3(), zchk4(), zchk5(), zchke(), and zmmch().
zchk1()
subroutine zchk1 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NBET, complex*16, dimension(nbet) BET, integer NMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax, nmax) B, complex*16, dimension(nmax*nmax) BB, complex*16, dimension(nmax*nmax) BS, complex*16, dimension(nmax, nmax) C, complex*16, dimension(nmax*nmax) CC, complex*16, dimension(nmax*nmax) CS, complex*16, dimension(nmax) CT, double precision, dimension(nmax) G)
Definition at line 410 of file zblat3.f.
References b, c, lda, m, max, n, x, zgemm(), zmake(), and zmmch().
zchk2()
subroutine zchk2 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NBET, complex*16, dimension(nbet) BET, integer NMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax, nmax) B, complex*16, dimension(nmax*nmax) BB, complex*16, dimension(nmax*nmax) BS, complex*16, dimension(nmax, nmax) C, complex*16, dimension(nmax*nmax) CC, complex*16, dimension(nmax*nmax) CS, complex*16, dimension(nmax) CT, double precision, dimension(nmax) G)
Definition at line 695 of file zblat3.f.
References b, c, lda, m, max, n, x, zhemm(), zmake(), zmmch(), and zsymm().
zchk3()
subroutine zchk3 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax, nmax) B, complex*16, dimension(nmax*nmax) BB, complex*16, dimension(nmax*nmax) BS, complex*16, dimension(nmax) CT, double precision, dimension(nmax) G, complex*16, dimension(nmax, nmax) C)
Definition at line 974 of file zblat3.f.
References b, c, lda, m, max, n, x, zmake(), zmmch(), ztrmm(), and ztrsm().
zchk4()
subroutine zchk4 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NBET, complex*16, dimension(nbet) BET, integer NMAX, complex*16, dimension(nmax, nmax) A, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax, nmax) B, complex*16, dimension(nmax*nmax) BB, complex*16, dimension(nmax*nmax) BS, complex*16, dimension(nmax, nmax) C, complex*16, dimension(nmax*nmax) CC, complex*16, dimension(nmax*nmax) CS, complex*16, dimension(nmax) CT, double precision, dimension(nmax) G)
Definition at line 1285 of file zblat3.f.
References b, c, lda, max, n, x, zherk(), zmake(), zmmch(), and zsyrk().
zchk5()
subroutine zchk5 (character*6 SNAME, double precision EPS, double precision THRESH, integer NOUT, integer NTRA, logical TRACE, logical REWI, logical FATAL, integer NIDIM, integer, dimension(nidim) IDIM, integer NALF, complex*16, dimension(nalf) ALF, integer NBET, complex*16, dimension(nbet) BET, integer NMAX, complex*16, dimension(2*nmax*nmax) AB, complex*16, dimension(nmax*nmax) AA, complex*16, dimension(nmax*nmax) AS, complex*16, dimension(nmax*nmax) BB, complex*16, dimension(nmax*nmax) BS, complex*16, dimension(nmax, nmax) C, complex*16, dimension(nmax*nmax) CC, complex*16, dimension(nmax*nmax) CS, complex*16, dimension(nmax) CT, double precision, dimension(nmax) G, complex*16, dimension(2*nmax) W)
Definition at line 1617 of file zblat3.f.
References c, lda, max, n, w, x, zher2k(), zmake(), zmmch(), and zsyr2k().
zchke()
subroutine zchke (integer ISNUM, character*6 SRNAMT, integer NOUT)
Definition at line 1989 of file zblat3.f.
References chkxer(), zgemm(), zhemm(), zher2k(), zherk(), zsymm(), zsyr2k(), zsyrk(), ztrmm(), and ztrsm().
zmake()
subroutine zmake (character*2 TYPE, character*1 UPLO, character*1 DIAG, integer M, integer N, complex*16, dimension(nmax, *) A, integer NMAX, complex*16, dimension(*) AA, integer LDA, logical RESET, complex*16 TRANSL)
Definition at line 2934 of file zblat3.f.
zmmch()
subroutine zmmch (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer KK, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB, complex*16 BETA, complex*16, dimension(ldc, *) C, integer LDC, complex*16, dimension(*) CT, double precision, dimension(*) G, complex*16, dimension(ldcc, *) CC, integer LDCC, double precision EPS, double precision ERR, logical FATAL, integer NOUT, logical MV)
Definition at line 3064 of file zblat3.f.
References abs, max, sqrt(), and x.
Referenced by zblat3(), zchk1(), zchk2(), zchk3(), zchk4(), and zchk5().