pairinteraction: /travis/libpairinteraction/eigen/test/zerosized.cpp File Reference
zerosized.cpp File Reference
#include "main.h"
Functions
template<typename MatrixType >
void zeroReduction (const MatrixType &m)
template<typename MatrixType >
void zeroSizedMatrix ()
template<typename VectorType >
void zeroSizedVector ()
void test_zerosized ()
Function Documentation
test_zerosized()
void test_zerosized ()
Definition at line 84 of file zerosized.cpp.
zeroReduction()
template<typename MatrixType > void zeroReduction (const MatrixType & m)
Definition at line 13 of file zerosized.cpp.
References VERIFY.
Referenced by zeroSizedMatrix(), and zeroSizedVector().
zeroSizedMatrix()
template<typename MatrixType > void zeroSizedMatrix ()
Definition at line 25 of file zerosized.cpp.
References cols, Eigen::PlainObjectBase< Derived >::cols(), Eigen::Dynamic, m, prod(), rows, Eigen::PlainObjectBase< Derived >::rows(), VERIFY, and zeroReduction().
zeroSizedVector()
template<typename VectorType > void zeroSizedVector ()
Definition at line 68 of file zerosized.cpp.
References Eigen::Dynamic, VERIFY, and zeroReduction().