pairinteraction: /travis/libpairinteraction/eigen/blas/f2c/zhbmv.c File Reference
zhbmv.c File Reference
#include "datatypes.h"
Functions
int zhbmv_ (char *uplo, integer *n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, doublecomplex *x, integer *incx, doublecomplex *beta, doublecomplex *y, integer *incy, ftnlen uplo_len)
Function Documentation
zhbmv_()
int zhbmv_ (char * uplo, integer * n, integer * k, doublecomplex * alpha, doublecomplex * a, integer * lda, doublecomplex * x, integer * incx, doublecomplex * beta, doublecomplex * y, integer * incy, ftnlen uplo_len)
Definition at line 15 of file zhbmv.c.
References d_cnjg(), doublecomplex::i, incx, incy, info, j, lda, lsame_(), max, min, n, doublecomplex::r, x, xerbla_(), and y.