var searchData=
[
  ['scalar_5fabs2_5fop',['scalar_abs2_op',['../structEigen_1_1internal_1_1scalar__abs2__op.html',1,'Eigen::internal']]],
  ['scalar_5fabs_5fop',['scalar_abs_op',['../structEigen_1_1internal_1_1scalar__abs__op.html',1,'Eigen::internal']]],
  ['scalar_5facos_5fop',['scalar_acos_op',['../structEigen_1_1internal_1_1scalar__acos__op.html',1,'Eigen::internal']]],
  ['scalar_5farg_5fop',['scalar_arg_op',['../structEigen_1_1internal_1_1scalar__arg__op.html',1,'Eigen::internal']]],
  ['scalar_5fasin_5fop',['scalar_asin_op',['../structEigen_1_1internal_1_1scalar__asin__op.html',1,'Eigen::internal']]],
  ['scalar_5fatan_5fop',['scalar_atan_op',['../structEigen_1_1internal_1_1scalar__atan__op.html',1,'Eigen::internal']]],
  ['scalar_5fbetainc_5fop',['scalar_betainc_op',['../structEigen_1_1internal_1_1scalar__betainc__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fand_5fop',['scalar_boolean_and_op',['../structEigen_1_1internal_1_1scalar__boolean__and__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fnot_5fop',['scalar_boolean_not_op',['../structEigen_1_1internal_1_1scalar__boolean__not__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5for_5fop',['scalar_boolean_or_op',['../structEigen_1_1internal_1_1scalar__boolean__or__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fxor_5fop',['scalar_boolean_xor_op',['../structEigen_1_1internal_1_1scalar__boolean__xor__op.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop',['scalar_cast_op',['../structEigen_1_1internal_1_1scalar__cast__op.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop_3c_20eigen_3a_3ahalf_2c_20float_20_3e',['scalar_cast_op&lt; Eigen::half, float &gt;',['../structEigen_1_1internal_1_1scalar__cast__op_3_01Eigen_1_1half_00_01float_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop_3c_20float_2c_20eigen_3a_3ahalf_20_3e',['scalar_cast_op&lt; float, Eigen::half &gt;',['../structEigen_1_1internal_1_1scalar__cast__op_3_01float_00_01Eigen_1_1half_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop_3c_20int_2c_20eigen_3a_3ahalf_20_3e',['scalar_cast_op&lt; int, Eigen::half &gt;',['../structEigen_1_1internal_1_1scalar__cast__op_3_01int_00_01Eigen_1_1half_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fceil_5fop',['scalar_ceil_op',['../structEigen_1_1internal_1_1scalar__ceil__op.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop',['scalar_cmp_op',['../structEigen_1_1internal_1_1scalar__cmp__op.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5feq_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_EQ &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__EQ_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fge_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_GE &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__GE_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fgt_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_GT &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__GT_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fle_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_LE &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__LE_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5flt_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_LT &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__LT_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fneq_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_NEQ &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__NEQ_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5funord_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_UNORD &gt;',['../structEigen_1_1internal_1_1scalar__cmp__op_3_01LhsScalar_00_01RhsScalar_00_01cmp__UNORD_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fconj_5fproduct_5fop',['scalar_conj_product_op',['../structEigen_1_1internal_1_1scalar__conj__product__op.html',1,'Eigen::internal']]],
  ['scalar_5fconjugate_5fop',['scalar_conjugate_op',['../structEigen_1_1internal_1_1scalar__conjugate__op.html',1,'Eigen::internal']]],
  ['scalar_5fconstant_5fop',['scalar_constant_op',['../structEigen_1_1internal_1_1scalar__constant__op.html',1,'Eigen::internal']]],
  ['scalar_5fcos_5fop',['scalar_cos_op',['../structEigen_1_1internal_1_1scalar__cos__op.html',1,'Eigen::internal']]],
  ['scalar_5fcosh_5fop',['scalar_cosh_op',['../structEigen_1_1internal_1_1scalar__cosh__op.html',1,'Eigen::internal']]],
  ['scalar_5fcube_5fop',['scalar_cube_op',['../structEigen_1_1internal_1_1scalar__cube__op.html',1,'Eigen::internal']]],
  ['scalar_5fdifference_5fop',['scalar_difference_op',['../structEigen_1_1internal_1_1scalar__difference__op.html',1,'Eigen::internal']]],
  ['scalar_5fdigamma_5fop',['scalar_digamma_op',['../structEigen_1_1internal_1_1scalar__digamma__op.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost',['scalar_div_cost',['../structEigen_1_1internal_1_1scalar__div__cost.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20double_2c_20true_20_3e',['scalar_div_cost&lt; double, true &gt;',['../structEigen_1_1internal_1_1scalar__div__cost_3_01double_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20float_2c_20true_20_3e',['scalar_div_cost&lt; float, true &gt;',['../structEigen_1_1internal_1_1scalar__div__cost_3_01float_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20signed_20long_2c_20vectorized_2c_20typename_20conditional_3c_20sizeof_28long_29_3d_3d8_2c_20void_2c_20false_5ftype_20_3e_3a_3atype_20_3e',['scalar_div_cost&lt; signed long, Vectorized, typename conditional&lt; sizeof(long)==8, void, false_type &gt;::type &gt;',['../structEigen_1_1internal_1_1scalar__div__cost_3_01signed_01long_00_01Vectorized_00_01typename_01cde50979a4ebe3034d1acf31cd785c359.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20std_3a_3acomplex_3c_20t_20_3e_2c_20vectorized_20_3e',['scalar_div_cost&lt; std::complex&lt; T &gt;, Vectorized &gt;',['../structEigen_1_1internal_1_1scalar__div__cost_3_01std_1_1complex_3_01T_01_4_00_01Vectorized_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20unsigned_20long_2c_20vectorized_2c_20typename_20conditional_3c_20sizeof_28long_29_3d_3d8_2c_20void_2c_20false_5ftype_20_3e_3a_3atype_20_3e',['scalar_div_cost&lt; unsigned long, Vectorized, typename conditional&lt; sizeof(long)==8, void, false_type &gt;::type &gt;',['../structEigen_1_1internal_1_1scalar__div__cost_3_01unsigned_01long_00_01Vectorized_00_01typename_0ebb4014c32cae2c5e62f12f43133a050.html',1,'Eigen::internal']]],
  ['scalar_5ferf_5fop',['scalar_erf_op',['../structEigen_1_1internal_1_1scalar__erf__op.html',1,'Eigen::internal']]],
  ['scalar_5ferfc_5fop',['scalar_erfc_op',['../structEigen_1_1internal_1_1scalar__erfc__op.html',1,'Eigen::internal']]],
  ['scalar_5fexp_5fop',['scalar_exp_op',['../structEigen_1_1internal_1_1scalar__exp__op.html',1,'Eigen::internal']]],
  ['scalar_5ffloor_5fop',['scalar_floor_op',['../structEigen_1_1internal_1_1scalar__floor__op.html',1,'Eigen::internal']]],
  ['scalar_5ffmod_5fop',['scalar_fmod_op',['../structEigen_1_1internal_1_1scalar__fmod__op.html',1,'Eigen::internal']]],
  ['scalar_5fhypot_5fop',['scalar_hypot_op',['../structEigen_1_1internal_1_1scalar__hypot__op.html',1,'Eigen::internal']]],
  ['scalar_5fhypot_5fop_3c_20scalar_2c_20scalar_20_3e',['scalar_hypot_op&lt; Scalar, Scalar &gt;',['../structEigen_1_1internal_1_1scalar__hypot__op_3_01Scalar_00_01Scalar_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fidentity_5fop',['scalar_identity_op',['../structEigen_1_1internal_1_1scalar__identity__op.html',1,'Eigen::internal']]],
  ['scalar_5figamma_5fop',['scalar_igamma_op',['../structEigen_1_1internal_1_1scalar__igamma__op.html',1,'Eigen::internal']]],
  ['scalar_5figammac_5fop',['scalar_igammac_op',['../structEigen_1_1internal_1_1scalar__igammac__op.html',1,'Eigen::internal']]],
  ['scalar_5fimag_5fop',['scalar_imag_op',['../structEigen_1_1internal_1_1scalar__imag__op.html',1,'Eigen::internal']]],
  ['scalar_5fimag_5fref_5fop',['scalar_imag_ref_op',['../structEigen_1_1internal_1_1scalar__imag__ref__op.html',1,'Eigen::internal']]],
  ['scalar_5finverse_5fop',['scalar_inverse_op',['../structEigen_1_1internal_1_1scalar__inverse__op.html',1,'Eigen::internal']]],
  ['scalar_5fisfinite_5fop',['scalar_isfinite_op',['../structEigen_1_1internal_1_1scalar__isfinite__op.html',1,'Eigen::internal']]],
  ['scalar_5fisinf_5fop',['scalar_isinf_op',['../structEigen_1_1internal_1_1scalar__isinf__op.html',1,'Eigen::internal']]],
  ['scalar_5fisnan_5fop',['scalar_isnan_op',['../structEigen_1_1internal_1_1scalar__isnan__op.html',1,'Eigen::internal']]],
  ['scalar_5flgamma_5fop',['scalar_lgamma_op',['../structEigen_1_1internal_1_1scalar__lgamma__op.html',1,'Eigen::internal']]],
  ['scalar_5flog10_5fop',['scalar_log10_op',['../structEigen_1_1internal_1_1scalar__log10__op.html',1,'Eigen::internal']]],
  ['scalar_5flog1p_5fop',['scalar_log1p_op',['../structEigen_1_1internal_1_1scalar__log1p__op.html',1,'Eigen::internal']]],
  ['scalar_5flog_5fop',['scalar_log_op',['../structEigen_1_1internal_1_1scalar__log__op.html',1,'Eigen::internal']]],
  ['scalar_5fmax_5fop',['scalar_max_op',['../structEigen_1_1internal_1_1scalar__max__op.html',1,'Eigen::internal']]],
  ['scalar_5fmin_5fop',['scalar_min_op',['../structEigen_1_1internal_1_1scalar__min__op.html',1,'Eigen::internal']]],
  ['scalar_5fmod2_5fop',['scalar_mod2_op',['../structEigen_1_1internal_1_1scalar__mod2__op.html',1,'Eigen::internal']]],
  ['scalar_5fmod_5fop',['scalar_mod_op',['../structEigen_1_1internal_1_1scalar__mod__op.html',1,'Eigen::internal']]],
  ['scalar_5fnorm1_5fop',['scalar_norm1_op',['../structscalar__norm1__op.html',1,'']]],
  ['scalar_5fopposite_5fop',['scalar_opposite_op',['../structEigen_1_1internal_1_1scalar__opposite__op.html',1,'Eigen::internal']]],
  ['scalar_5fpolygamma_5fop',['scalar_polygamma_op',['../structEigen_1_1internal_1_1scalar__polygamma__op.html',1,'Eigen::internal']]],
  ['scalar_5fpow_5fop',['scalar_pow_op',['../structEigen_1_1internal_1_1scalar__pow__op.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5fop',['scalar_product_op',['../structEigen_1_1internal_1_1scalar__product__op.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits',['scalar_product_traits',['../structEigen_1_1internal_1_1scalar__product__traits.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits_3c_20scalara_2c_20scalarb_20_3e',['scalar_product_traits&lt; ScalarA, ScalarB &gt;',['../structEigen_1_1internal_1_1scalar__product__traits.html',1,'Eigen::internal']]],
  ['scalar_5fquotient_5fop',['scalar_quotient_op',['../structEigen_1_1internal_1_1scalar__quotient__op.html',1,'Eigen::internal']]],
  ['scalar_5frandom_5fop',['scalar_random_op',['../structEigen_1_1internal_1_1scalar__random__op.html',1,'Eigen::internal']]],
  ['scalar_5freal_5fop',['scalar_real_op',['../structEigen_1_1internal_1_1scalar__real__op.html',1,'Eigen::internal']]],
  ['scalar_5freal_5fref_5fop',['scalar_real_ref_op',['../structEigen_1_1internal_1_1scalar__real__ref__op.html',1,'Eigen::internal']]],
  ['scalar_5fround_5fop',['scalar_round_op',['../structEigen_1_1internal_1_1scalar__round__op.html',1,'Eigen::internal']]],
  ['scalar_5frsqrt_5fop',['scalar_rsqrt_op',['../structEigen_1_1internal_1_1scalar__rsqrt__op.html',1,'Eigen::internal']]],
  ['scalar_5fscore_5fcoeff_5fop',['scalar_score_coeff_op',['../structEigen_1_1internal_1_1scalar__score__coeff__op.html',1,'Eigen::internal']]],
  ['scalar_5fsigmoid_5fop',['scalar_sigmoid_op',['../structEigen_1_1internal_1_1scalar__sigmoid__op.html',1,'Eigen::internal']]],
  ['scalar_5fsign_5fop',['scalar_sign_op',['../structEigen_1_1internal_1_1scalar__sign__op.html',1,'Eigen::internal']]],
  ['scalar_5fsign_5fop_3c_20scalar_2c_20false_20_3e',['scalar_sign_op&lt; Scalar, false &gt;',['../structEigen_1_1internal_1_1scalar__sign__op_3_01Scalar_00_01false_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsign_5fop_3c_20scalar_2c_20true_20_3e',['scalar_sign_op&lt; Scalar, true &gt;',['../structEigen_1_1internal_1_1scalar__sign__op_3_01Scalar_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsin_5fop',['scalar_sin_op',['../structEigen_1_1internal_1_1scalar__sin__op.html',1,'Eigen::internal']]],
  ['scalar_5fsinh_5fop',['scalar_sinh_op',['../structEigen_1_1internal_1_1scalar__sinh__op.html',1,'Eigen::internal']]],
  ['scalar_5fsqrt_5fop',['scalar_sqrt_op',['../structEigen_1_1internal_1_1scalar__sqrt__op.html',1,'Eigen::internal']]],
  ['scalar_5fsquare_5fop',['scalar_square_op',['../structEigen_1_1internal_1_1scalar__square__op.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop',['scalar_sum_op',['../structEigen_1_1internal_1_1scalar__sum__op.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop_3c_20bool_2c_20bool_20_3e',['scalar_sum_op&lt; bool, bool &gt;',['../structEigen_1_1internal_1_1scalar__sum__op_3_01bool_00_01bool_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop_3c_20int_2c_20int_20_3e',['scalar_sum_op&lt; int, int &gt;',['../structEigen_1_1internal_1_1scalar__sum__op.html',1,'Eigen::internal']]],
  ['scalar_5ftan_5fop',['scalar_tan_op',['../structEigen_1_1internal_1_1scalar__tan__op.html',1,'Eigen::internal']]],
  ['scalar_5ftanh_5fop',['scalar_tanh_op',['../structEigen_1_1internal_1_1scalar__tanh__op.html',1,'Eigen::internal']]],
  ['scalar_5fzeta_5fop',['scalar_zeta_op',['../structEigen_1_1internal_1_1scalar__zeta__op.html',1,'Eigen::internal']]],
  ['scalarbinaryoptraits',['ScalarBinaryOpTraits',['../structEigen_1_1ScalarBinaryOpTraits.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20autodiffscalar_3c_20dertype_20_3e_2c_20typename_20dertype_3a_3ascalar_2c_20binop_20_3e',['ScalarBinaryOpTraits&lt; AutoDiffScalar&lt; DerType &gt;, typename DerType::Scalar, BinOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01AutoDiffScalar_3_01DerType_01_4_00_01typename_01DerType_1_1Scalar_00_01BinOp_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20t_2c_20t_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; T, T, BinaryOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01T_00_01T_00_01BinaryOp_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20t_2c_20typename_20numtraits_3c_20typename_20internal_3a_3aenable_5fif_3c_20numtraits_3c_20t_20_3e_3a_3aiscomplex_2c_20t_20_3e_3a_3atype_20_3e_3a_3areal_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; T, typename NumTraits&lt; typename internal::enable_if&lt; NumTraits&lt; T &gt;::IsComplex, T &gt;::type &gt;::Real, BinaryOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01T_00_01typename_01NumTraits_3_01typename_01internal_1_1e56d7471d15e084cfef57c181a609e17b.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20t_2c_20void_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; T, void, BinaryOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01T_00_01void_00_01BinaryOp_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20typename_20dertype_3a_3ascalar_2c_20autodiffscalar_3c_20dertype_20_3e_2c_20binop_20_3e',['ScalarBinaryOpTraits&lt; typename DerType::Scalar, AutoDiffScalar&lt; DerType &gt;, BinOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01typename_01DerType_1_1Scalar_00_01AutoDiffScalar_3_01DerType_01_4_00_01BinOp_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20typename_20numtraits_3c_20typename_20internal_3a_3aenable_5fif_3c_20numtraits_3c_20t_20_3e_3a_3aiscomplex_2c_20t_20_3e_3a_3atype_20_3e_3a_3areal_2c_20t_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; typename NumTraits&lt; typename internal::enable_if&lt; NumTraits&lt; T &gt;::IsComplex, T &gt;::type &gt;::Real, T, BinaryOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01typename_01NumTraits_3_01typename_01internal_1_1enable__cb0e31770c68ef6e6bb9fa3dde8a23d7.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20void_2c_20t_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; void, T, BinaryOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01void_00_01T_00_01BinaryOp_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20void_2c_20void_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; void, void, BinaryOp &gt;',['../structEigen_1_1ScalarBinaryOpTraits_3_01void_00_01void_00_01BinaryOp_01_4.html',1,'Eigen']]],
  ['scalarwithexceptions',['ScalarWithExceptions',['../classScalarWithExceptions.html',1,'']]],
  ['scaling',['Scaling',['../classScaling.html',1,'']]],
  ['scanlauncher',['ScanLauncher',['../structEigen_1_1ScanLauncher.html',1,'Eigen']]],
  ['scoped_5farray',['scoped_array',['../classEigen_1_1internal_1_1scoped__array.html',1,'Eigen::internal']]],
  ['select',['Select',['../classEigen_1_1Select.html',1,'Eigen']]],
  ['selector',['Selector',['../structEigen_1_1internal_1_1Selector.html',1,'Eigen::internal']]],
  ['selfadjoint_5fmatrix_5fvector_5fproduct',['selfadjoint_matrix_vector_product',['../structEigen_1_1internal_1_1selfadjoint__matrix__vector__product.html',1,'Eigen::internal']]],
  ['selfadjoint_5fmatrix_5fvector_5fproduct_3c_20scalar_2c_20index_2c_20storageorder_2c_20uplo_2c_20conjugatelhs_2c_20conjugaterhs_2c_20builtin_20_3e',['selfadjoint_matrix_vector_product&lt; Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn &gt;',['../structEigen_1_1internal_1_1selfadjoint__matrix__vector__product.html',1,'Eigen::internal']]],
  ['selfadjoint_5fmatrix_5fvector_5fproduct_5fsymv',['selfadjoint_matrix_vector_product_symv',['../structEigen_1_1internal_1_1selfadjoint__matrix__vector__product__symv.html',1,'Eigen::internal']]],
  ['selfadjoint_5fpacked_5frank1_5fupdate',['selfadjoint_packed_rank1_update',['../structinternal_1_1selfadjoint__packed__rank1__update.html',1,'internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, StorageOrder, UpLo, ConjLhs, ConjRhs &gt;'],['../structEigen_1_1internal_1_1selfadjoint__packed__rank1__update.html',1,'Eigen::internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, StorageOrder, UpLo, ConjLhs, ConjRhs &gt;']]],
  ['selfadjoint_5fpacked_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20colmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_packed_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;',['../structEigen_1_1internal_1_1selfadjoint__packed__rank1__update_3_01Scalar_00_01Index_00_01ColMajo6096ab9a623b7ce6a0eb3603f0b08dc4.html',1,'Eigen::internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;'],['../structinternal_1_1selfadjoint__packed__rank1__update_3_01Scalar_00_01Index_00_01ColMajor_00_01Upa5eff2e1f5aa5eec42f78aee7799a3d0.html',1,'internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;']]],
  ['selfadjoint_5fpacked_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20rowmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_packed_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;',['../structinternal_1_1selfadjoint__packed__rank1__update_3_01Scalar_00_01Index_00_01RowMajor_00_01Upce29a2a0af6015f96ab0bd9a4a2b36da.html',1,'internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;'],['../structEigen_1_1internal_1_1selfadjoint__packed__rank1__update_3_01Scalar_00_01Index_00_01RowMajo0b5023b8dc0bec403bd301b3942bb7bc.html',1,'Eigen::internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;']]],
  ['selfadjoint_5fproduct_5fimpl',['selfadjoint_product_impl',['../structEigen_1_1internal_1_1selfadjoint__product__impl.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl_3c_20lhs_2c_200_2c_20true_2c_20rhs_2c_20rhsmode_2c_20false_20_3e',['selfadjoint_product_impl&lt; Lhs, 0, true, Rhs, RhsMode, false &gt;',['../structEigen_1_1internal_1_1selfadjoint__product__impl_3_01Lhs_00_010_00_01true_00_01Rhs_00_01RhsMode_00_01false_01_4.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl_3c_20lhs_2c_20lhsmode_2c_20false_2c_20rhs_2c_200_2c_20true_20_3e',['selfadjoint_product_impl&lt; Lhs, LhsMode, false, Rhs, 0, true &gt;',['../structEigen_1_1internal_1_1selfadjoint__product__impl_3_01Lhs_00_01LhsMode_00_01false_00_01Rhs_00_010_00_01true_01_4.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl_3c_20lhs_2c_20lhsmode_2c_20false_2c_20rhs_2c_20rhsmode_2c_20false_20_3e',['selfadjoint_product_impl&lt; Lhs, LhsMode, false, Rhs, RhsMode, false &gt;',['../structEigen_1_1internal_1_1selfadjoint__product__impl_3_01Lhs_00_01LhsMode_00_01false_00_01Rhs_00_01RhsMode_00_01false_01_4.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fselector',['selfadjoint_product_selector',['../structEigen_1_1selfadjoint__product__selector.html',1,'Eigen']]],
  ['selfadjoint_5fproduct_5fselector_3c_20matrixtype_2c_20othertype_2c_20uplo_2c_20false_20_3e',['selfadjoint_product_selector&lt; MatrixType, OtherType, UpLo, false &gt;',['../structEigen_1_1selfadjoint__product__selector_3_01MatrixType_00_01OtherType_00_01UpLo_00_01false_01_4.html',1,'Eigen']]],
  ['selfadjoint_5fproduct_5fselector_3c_20matrixtype_2c_20othertype_2c_20uplo_2c_20true_20_3e',['selfadjoint_product_selector&lt; MatrixType, OtherType, UpLo, true &gt;',['../structEigen_1_1selfadjoint__product__selector_3_01MatrixType_00_01OtherType_00_01UpLo_00_01true_01_4.html',1,'Eigen']]],
  ['selfadjoint_5frank1_5fupdate',['selfadjoint_rank1_update',['../structEigen_1_1selfadjoint__rank1__update.html',1,'Eigen']]],
  ['selfadjoint_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20colmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;',['../structEigen_1_1selfadjoint__rank1__update_3_01Scalar_00_01Index_00_01ColMajor_00_01UpLo_00_01ConjLhs_00_01ConjRhs_01_4.html',1,'Eigen']]],
  ['selfadjoint_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20rowmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;',['../structEigen_1_1selfadjoint__rank1__update_3_01Scalar_00_01Index_00_01RowMajor_00_01UpLo_00_01ConjLhs_00_01ConjRhs_01_4.html',1,'Eigen']]],
  ['selfadjoint_5frank2_5fupdate_5fselector',['selfadjoint_rank2_update_selector',['../structEigen_1_1internal_1_1selfadjoint__rank2__update__selector.html',1,'Eigen::internal']]],
  ['selfadjoint_5frank2_5fupdate_5fselector_3c_20scalar_2c_20index_2c_20utype_2c_20vtype_2c_20lower_20_3e',['selfadjoint_rank2_update_selector&lt; Scalar, Index, UType, VType, Lower &gt;',['../structEigen_1_1internal_1_1selfadjoint__rank2__update__selector_3_01Scalar_00_01Index_00_01UType_00_01VType_00_01Lower_01_4.html',1,'Eigen::internal']]],
  ['selfadjoint_5frank2_5fupdate_5fselector_3c_20scalar_2c_20index_2c_20utype_2c_20vtype_2c_20upper_20_3e',['selfadjoint_rank2_update_selector&lt; Scalar, Index, UType, VType, Upper &gt;',['../structEigen_1_1internal_1_1selfadjoint__rank2__update__selector_3_01Scalar_00_01Index_00_01UType_00_01VType_00_01Upper_01_4.html',1,'Eigen::internal']]],
  ['selfadjointeigensolver',['SelfAdjointEigenSolver',['../classEigen_1_1SelfAdjointEigenSolver.html',1,'Eigen']]],
  ['selfadjointshape',['SelfAdjointShape',['../structEigen_1_1SelfAdjointShape.html',1,'Eigen']]],
  ['selfadjointview',['SelfAdjointView',['../classEigen_1_1SelfAdjointView.html',1,'Eigen']]],
  ['selfadjointviewreturntype',['SelfAdjointViewReturnType',['../structEigen_1_1MatrixBase_1_1SelfAdjointViewReturnType.html',1,'Eigen::MatrixBase&lt; Derived &gt;::SelfAdjointViewReturnType&lt; UpLo &gt;'],['../structEigen_1_1SparseMatrixBase_1_1SelfAdjointViewReturnType.html',1,'Eigen::SparseMatrixBase&lt; Derived &gt;::SelfAdjointViewReturnType&lt; UpLo &gt;']]],
  ['serializable',['Serializable',['../classSerializable.html',1,'']]],
  ['serializer',['Serializer',['../classSerializer.html',1,'']]],
  ['set',['set',['../structEigen_1_1internal_1_1generic__product__impl_3_01Lhs_00_01Rhs_00_01DenseShape_00_01DenseShaa243cd8836786c40b5d44485b15eb561.html',1,'Eigen::internal::generic_product_impl&lt; Lhs, Rhs, DenseShape, DenseShape, OuterProduct &gt;']]],
  ['setidentity_5fimpl',['setIdentity_impl',['../structEigen_1_1internal_1_1setIdentity__impl.html',1,'Eigen::internal']]],
  ['setidentity_5fimpl_3c_20derived_2c_20true_20_3e',['setIdentity_impl&lt; Derived, true &gt;',['../structEigen_1_1internal_1_1setIdentity__impl_3_01Derived_00_01true_01_4.html',1,'Eigen::internal']]],
  ['sgroup',['SGroup',['../classEigen_1_1SGroup.html',1,'Eigen']]],
  ['significant_5fdecimals_5fimpl',['significant_decimals_impl',['../structEigen_1_1internal_1_1significant__decimals__impl.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper',['SimpleTensorContractionMapper',['../classEigen_1_1internal_1_1SimpleTensorContractionMapper.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper_3c_20scalar_2c_20index_2c_20side_2c_20tensor_2c_20nocontract_5ft_2c_20contract_5ft_2c_201_2c_20inner_5fdim_5fcontiguous_2c_20alignment_20_3e',['SimpleTensorContractionMapper&lt; Scalar, Index, side, Tensor, nocontract_t, contract_t, 1, inner_dim_contiguous, Alignment &gt;',['../classEigen_1_1internal_1_1SimpleTensorContractionMapper.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper_3c_20scalar_5f_2c_20index_2c_20side_2c_20tensor_2c_20nocontract_5ft_2c_20contract_5ft_2c_20packet_5fsize_2c_20inner_5fdim_5fcontiguous_2c_20alignment_20_3e',['SimpleTensorContractionMapper&lt; Scalar_, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment &gt;',['../classEigen_1_1internal_1_1SimpleTensorContractionMapper.html',1,'Eigen::internal']]],
  ['simplethreadpooltempl',['SimpleThreadPoolTempl',['../classEigen_1_1SimpleThreadPoolTempl.html',1,'Eigen']]],
  ['simplicial_5fcholesky_5fgrab_5finput',['simplicial_cholesky_grab_input',['../structEigen_1_1internal_1_1simplicial__cholesky__grab__input.html',1,'Eigen::internal']]],
  ['simplicial_5fcholesky_5fgrab_5finput_3c_20matrixtype_2c_20matrixtype_20_3e',['simplicial_cholesky_grab_input&lt; MatrixType, MatrixType &gt;',['../structEigen_1_1internal_1_1simplicial__cholesky__grab__input_3_01MatrixType_00_01MatrixType_01_4.html',1,'Eigen::internal']]],
  ['simplicialcholesky',['SimplicialCholesky',['../classEigen_1_1SimplicialCholesky.html',1,'Eigen']]],
  ['simplicialcholeskybase',['SimplicialCholeskyBase',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialldlt',['SimplicialLDLT',['../classEigen_1_1SimplicialLDLT.html',1,'Eigen']]],
  ['simplicialllt',['SimplicialLLT',['../classEigen_1_1SimplicialLLT.html',1,'Eigen']]],
  ['singletonvector',['SingletonVector',['../classEigen_1_1SparseMatrix_1_1SingletonVector.html',1,'Eigen::SparseMatrix']]],
  ['size_5fat_5fcompile_5ftime',['size_at_compile_time',['../structEigen_1_1internal_1_1size__at__compile__time.html',1,'Eigen::internal']]],
  ['size_5fof_5fxpr_5fat_5fcompile_5ftime',['size_of_xpr_at_compile_time',['../structEigen_1_1internal_1_1size__of__xpr__at__compile__time.html',1,'Eigen::internal']]],
  ['size_5ftriple_5ft',['size_triple_t',['../structsize__triple__t.html',1,'']]],
  ['sizes',['Sizes',['../structEigen_1_1Sizes.html',1,'Eigen']]],
  ['sizes_5fmatch_5fbelow_5fdim',['sizes_match_below_dim',['../structEigen_1_1internal_1_1sizes__match__below__dim.html',1,'Eigen::internal']]],
  ['sizes_5fmatch_5fbelow_5fdim_3c_20dims1_2c_20dims2_2c_200_2c_200_20_3e',['sizes_match_below_dim&lt; Dims1, Dims2, 0, 0 &gt;',['../structEigen_1_1internal_1_1sizes__match__below__dim_3_01Dims1_00_01Dims2_00_010_00_010_01_4.html',1,'Eigen::internal']]],
  ['sizes_5fmatch_5fbelow_5fdim_3c_20dims1_2c_20dims2_2c_20n_2c_20n_20_3e',['sizes_match_below_dim&lt; Dims1, Dims2, n, n &gt;',['../structEigen_1_1internal_1_1sizes__match__below__dim_3_01Dims1_00_01Dims2_00_01n_00_01n_01_4.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fmode',['skyline_product_mode',['../structEigen_1_1internal_1_1skyline__product__mode.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fselector',['skyline_product_selector',['../structEigen_1_1internal_1_1skyline__product__selector.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_20_3e',['skyline_product_selector&lt; Lhs, Rhs, ResultType, ColMajor &gt;',['../structEigen_1_1internal_1_1skyline__product__selector_3_01Lhs_00_01Rhs_00_01ResultType_00_01ColMajor_01_4.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_20_3e',['skyline_product_selector&lt; Lhs, Rhs, ResultType, RowMajor &gt;',['../structEigen_1_1internal_1_1skyline__product__selector_3_01Lhs_00_01Rhs_00_01ResultType_00_01RowMajor_01_4.html',1,'Eigen::internal']]],
  ['skylineinplacelu',['SkylineInplaceLU',['../classEigen_1_1SkylineInplaceLU.html',1,'Eigen']]],
  ['skylinematrix',['SkylineMatrix',['../classEigen_1_1SkylineMatrix.html',1,'Eigen']]],
  ['skylinematrixbase',['SkylineMatrixBase',['../classEigen_1_1SkylineMatrixBase.html',1,'Eigen']]],
  ['skylinematrixbase_3c_20skylinematrix_3c_20_5fscalar_2c_20_5foptions_20_3e_20_3e',['SkylineMatrixBase&lt; SkylineMatrix&lt; _Scalar, _Options &gt; &gt;',['../classEigen_1_1SkylineMatrixBase.html',1,'Eigen']]],
  ['skylineproduct',['SkylineProduct',['../classEigen_1_1SkylineProduct.html',1,'Eigen::SkylineProduct&lt; Lhs, Rhs, ProductMode &gt;'],['../classEigen_1_1internal_1_1SkylineProduct.html',1,'Eigen::internal::SkylineProduct&lt; LhsNested, RhsNested, ProductMode &gt;']]],
  ['skylineproductreturntype',['SkylineProductReturnType',['../structEigen_1_1internal_1_1SkylineProductReturnType.html',1,'Eigen::internal::SkylineProductReturnType&lt; Lhs, Rhs, ProductMode &gt;'],['../structEigen_1_1SkylineProductReturnType.html',1,'Eigen::SkylineProductReturnType&lt; Lhs, Rhs, ProductMode &gt;']]],
  ['skylinestorage',['SkylineStorage',['../classEigen_1_1SkylineStorage.html',1,'Eigen']]],
  ['skylinevector',['SkylineVector',['../classEigen_1_1SkylineVector.html',1,'Eigen']]],
  ['slumatrix',['SluMatrix',['../structEigen_1_1SluMatrix.html',1,'Eigen']]],
  ['slumatrixmaphelper',['SluMatrixMapHelper',['../structEigen_1_1SluMatrixMapHelper.html',1,'Eigen']]],
  ['slumatrixmaphelper_3c_20matrix_3c_20scalar_2c_20rows_2c_20cols_2c_20options_2c_20mrows_2c_20mcols_20_3e_20_3e',['SluMatrixMapHelper&lt; Matrix&lt; Scalar, Rows, Cols, Options, MRows, MCols &gt; &gt;',['../structEigen_1_1SluMatrixMapHelper_3_01Matrix_3_01Scalar_00_01Rows_00_01Cols_00_01Options_00_01MRows_00_01MCols_01_4_01_4.html',1,'Eigen']]],
  ['slumatrixmaphelper_3c_20sparsematrixbase_3c_20derived_20_3e_20_3e',['SluMatrixMapHelper&lt; SparseMatrixBase&lt; Derived &gt; &gt;',['../structEigen_1_1SluMatrixMapHelper_3_01SparseMatrixBase_3_01Derived_01_4_01_4.html',1,'Eigen']]],
  ['smart_5fcopy_5fhelper',['smart_copy_helper',['../structEigen_1_1internal_1_1smart__copy__helper.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper_3c_20t_2c_20false_20_3e',['smart_copy_helper&lt; T, false &gt;',['../structEigen_1_1internal_1_1smart__copy__helper_3_01T_00_01false_01_4.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper_3c_20t_2c_20true_20_3e',['smart_copy_helper&lt; T, true &gt;',['../structEigen_1_1internal_1_1smart__copy__helper_3_01T_00_01true_01_4.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper',['smart_memmove_helper',['../structEigen_1_1internal_1_1smart__memmove__helper.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper_3c_20t_2c_20false_20_3e',['smart_memmove_helper&lt; T, false &gt;',['../structEigen_1_1internal_1_1smart__memmove__helper_3_01T_00_01false_01_4.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper_3c_20t_2c_20true_20_3e',['smart_memmove_helper&lt; T, true &gt;',['../structEigen_1_1internal_1_1smart__memmove__helper_3_01T_00_01true_01_4.html',1,'Eigen::internal']]],
  ['socket',['socket',['../classzmq_1_1socket.html',1,'zmq']]],
  ['solve',['Solve',['../classEigen_1_1Solve.html',1,'Eigen']]],
  ['solve_5ftraits',['solve_traits',['../structEigen_1_1internal_1_1solve__traits.html',1,'Eigen::internal']]],
  ['solve_5ftraits_3c_20decomposition_2c_20rhstype_2c_20dense_20_3e',['solve_traits&lt; Decomposition, RhsType, Dense &gt;',['../structEigen_1_1internal_1_1solve__traits_3_01Decomposition_00_01RhsType_00_01Dense_01_4.html',1,'Eigen::internal']]],
  ['solve_5ftraits_3c_20decomposition_2c_20rhstype_2c_20sparse_20_3e',['solve_traits&lt; Decomposition, RhsType, Sparse &gt;',['../structEigen_1_1internal_1_1solve__traits_3_01Decomposition_00_01RhsType_00_01Sparse_01_4.html',1,'Eigen::internal']]],
  ['solveimpl',['SolveImpl',['../classEigen_1_1SolveImpl.html',1,'Eigen']]],
  ['solveimpl_3c_20decomposition_2c_20rhstype_2c_20dense_20_3e',['SolveImpl&lt; Decomposition, RhsType, Dense &gt;',['../classEigen_1_1SolveImpl_3_01Decomposition_00_01RhsType_00_01Dense_01_4.html',1,'Eigen']]],
  ['solveimpl_3c_20decomposition_2c_20rhstype_2c_20internal_3a_3atraits_3c_20rhstype_20_3e_3a_3astoragekind_20_3e',['SolveImpl&lt; Decomposition, RhsType, internal::traits&lt; RhsType &gt;::StorageKind &gt;',['../classEigen_1_1SolveImpl.html',1,'Eigen']]],
  ['solverbase',['SolverBase',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e',['SolverBase&lt; FullPivLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20partialpivlu_3c_20_5fmatrixtype_20_3e_20_3e',['SolverBase&lt; PartialPivLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20partialpivlu_3c_20matrix_3c_20scalar_2c_20dynamic_2c_20dynamic_20_3e_20_3e_20_3e',['SolverBase&lt; PartialPivLU&lt; Matrix&lt; Scalar, Dynamic, Dynamic &gt; &gt; &gt;',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solvershape',['SolverShape',['../structEigen_1_1SolverShape.html',1,'Eigen']]],
  ['solverstorage',['SolverStorage',['../structEigen_1_1SolverStorage.html',1,'Eigen']]],
  ['solvewithguess',['SolveWithGuess',['../classEigen_1_1SolveWithGuess.html',1,'Eigen']]],
  ['some_5fnon_5fvectorizable_5ftype',['some_non_vectorizable_type',['../structsome__non__vectorizable__type.html',1,'']]],
  ['sparse',['Sparse',['../structEigen_1_1Sparse.html',1,'Eigen']]],
  ['sparse2dense',['Sparse2Dense',['../structEigen_1_1internal_1_1Sparse2Dense.html',1,'Eigen::internal']]],
  ['sparse2sparse',['Sparse2Sparse',['../structEigen_1_1internal_1_1Sparse2Sparse.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator',['sparse_conjunction_evaluator',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20cwisebinaryop_3c_20scalar_5fboolean_5fand_5fop_2c_20lhs_2c_20rhs_20_3e_20_3e',['sparse_conjunction_evaluator&lt; CwiseBinaryOp&lt; scalar_boolean_and_op, Lhs, Rhs &gt; &gt;',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20cwisebinaryop_3c_20scalar_5fproduct_5fop_3c_20t1_2c_20t2_20_3e_2c_20lhs_2c_20rhs_20_3e_20_3e',['sparse_conjunction_evaluator&lt; CwiseBinaryOp&lt; scalar_product_op&lt; T1, T2 &gt;, Lhs, Rhs &gt; &gt;',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20cwisebinaryop_3c_20scalar_5fquotient_5fop_3c_20t1_2c_20t2_20_3e_2c_20lhs_2c_20rhs_20_3e_20_3e',['sparse_conjunction_evaluator&lt; CwiseBinaryOp&lt; scalar_quotient_op&lt; T1, T2 &gt;, Lhs, Rhs &gt; &gt;',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20xprtype_2c_20indexbased_2c_20iteratorbased_20_3e',['sparse_conjunction_evaluator&lt; XprType, IndexBased, IteratorBased &gt;',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator_3_01XprType_00_01IndexBased_00_01IteratorBased_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20xprtype_2c_20iteratorbased_2c_20indexbased_20_3e',['sparse_conjunction_evaluator&lt; XprType, IteratorBased, IndexBased &gt;',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator_3_01XprType_00_01IteratorBased_00_01IndexBased_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20xprtype_2c_20iteratorbased_2c_20iteratorbased_20_3e',['sparse_conjunction_evaluator&lt; XprType, IteratorBased, IteratorBased &gt;',['../structEigen_1_1internal_1_1sparse__conjunction__evaluator_3_01XprType_00_01IteratorBased_00_01IteratorBased_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fdense_5fouter_5fproduct_5fevaluator',['sparse_dense_outer_product_evaluator',['../structEigen_1_1internal_1_1sparse__dense__outer__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdense_5fouter_5fproduct_5fevaluator_3c_20lhs_2c_20rhs_2c_20lhs_3a_3aisrowmajor_20_3e',['sparse_dense_outer_product_evaluator&lt; Lhs, Rhs, Lhs::IsRowMajor &gt;',['../structEigen_1_1internal_1_1sparse__dense__outer__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdense_5fouter_5fproduct_5fevaluator_3c_20lhs_2c_20rhs_2c_20rhs_3a_3aisrowmajor_20_3e',['sparse_dense_outer_product_evaluator&lt; Lhs, Rhs, Rhs::IsRowMajor &gt;',['../structEigen_1_1internal_1_1sparse__dense__outer__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator',['sparse_diagonal_product_evaluator',['../structEigen_1_1internal_1_1sparse__diagonal__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20lhs_2c_20transpose_3c_20const_20rhs_3a_3adiagonalvectortype_20_3e_2c_20lhs_3a_3aflags_20_26rowmajorbit_3fsdp_5fascwiseproduct_3asdp_5fasscalarproduct_20_3e',['sparse_diagonal_product_evaluator&lt; Lhs, Transpose&lt; const Rhs::DiagonalVectorType &gt;, Lhs::Flags &amp;RowMajorBit?SDP_AsCwiseProduct:SDP_AsScalarProduct &gt;',['../structEigen_1_1internal_1_1sparse__diagonal__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20rhs_2c_20lhs_3a_3adiagonalvectortype_2c_20rhs_3a_3aflags_20_26rowmajorbit_3fsdp_5fasscalarproduct_3asdp_5fascwiseproduct_20_3e',['sparse_diagonal_product_evaluator&lt; Rhs, Lhs::DiagonalVectorType, Rhs::Flags &amp;RowMajorBit?SDP_AsScalarProduct:SDP_AsCwiseProduct &gt;',['../structEigen_1_1internal_1_1sparse__diagonal__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20sparsexprtype_2c_20diagcoefftype_2c_20sdp_5fascwiseproduct_20_3e',['sparse_diagonal_product_evaluator&lt; SparseXprType, DiagCoeffType, SDP_AsCwiseProduct &gt;',['../structEigen_1_1internal_1_1sparse__diagonal__product__evaluator_3_01SparseXprType_00_01DiagCoeff737b889b2304dfe901d72808cd5ba820.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20sparsexprtype_2c_20diagonalcoefftype_2c_20sdp_5fasscalarproduct_20_3e',['sparse_diagonal_product_evaluator&lt; SparseXprType, DiagonalCoeffType, SDP_AsScalarProduct &gt;',['../structEigen_1_1internal_1_1sparse__diagonal__product__evaluator_3_01SparseXprType_00_01DiagonalC739580d6209ee88097dc375f8d79a908.html',1,'Eigen::internal']]],
  ['sparse_5feval',['sparse_eval',['../structEigen_1_1internal_1_1sparse__eval.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_201_2c_201_2c_20flags_20_3e',['sparse_eval&lt; T, 1, 1, Flags &gt;',['../structEigen_1_1internal_1_1sparse__eval_3_01T_00_011_00_011_00_01Flags_01_4.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_201_2c_20cols_2c_20flags_20_3e',['sparse_eval&lt; T, 1, Cols, Flags &gt;',['../structEigen_1_1internal_1_1sparse__eval_3_01T_00_011_00_01Cols_00_01Flags_01_4.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_20rows_2c_201_2c_20flags_20_3e',['sparse_eval&lt; T, Rows, 1, Flags &gt;',['../structEigen_1_1internal_1_1sparse__eval_3_01T_00_01Rows_00_011_00_01Flags_01_4.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_20traits_3c_20t_20_3e_3a_3arowsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3acolsatcompiletime_2c_20evaluator_3c_20t_20_3e_3a_3aflags_20_3e',['sparse_eval&lt; T, traits&lt; T &gt;::RowsAtCompileTime, traits&lt; T &gt;::ColsAtCompileTime, evaluator&lt; T &gt;::Flags &gt;',['../structEigen_1_1internal_1_1sparse__eval.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_20traits_3c_20t_20_3e_3a_3arowsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3acolsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3aflags_20_3e',['sparse_eval&lt; T, traits&lt; T &gt;::RowsAtCompileTime, traits&lt; T &gt;::ColsAtCompileTime, traits&lt; T &gt;::Flags &gt;',['../structEigen_1_1internal_1_1sparse__eval.html',1,'Eigen::internal']]],
  ['sparse_5fmatrix_5fblock_5fimpl',['sparse_matrix_block_impl',['../classEigen_1_1internal_1_1sparse__matrix__block__impl.html',1,'Eigen::internal']]],
  ['sparse_5fmatrix_5fblock_5fimpl_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_20_3e',['sparse_matrix_block_impl&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols &gt;',['../classEigen_1_1internal_1_1sparse__matrix__block__impl.html',1,'Eigen::internal']]],
  ['sparse_5fmatrix_5fblock_5fimpl_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_20_3e',['sparse_matrix_block_impl&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols &gt;',['../classEigen_1_1internal_1_1sparse__matrix__block__impl.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector',['sparse_solve_triangular_selector',['../structEigen_1_1internal_1_1sparse__solve__triangular__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20lower_2c_20colmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Lower, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__solve__triangular__selector_3_01Lhs_00_01Rhs_00_01Mode_00_01Lower_00_01ColMajor_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20lower_2c_20rowmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Lower, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__solve__triangular__selector_3_01Lhs_00_01Rhs_00_01Mode_00_01Lower_00_01RowMajor_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20upper_2c_20colmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Upper, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__solve__triangular__selector_3_01Lhs_00_01Rhs_00_01Mode_00_01Upper_00_01ColMajor_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20upper_2c_20rowmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Upper, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__solve__triangular__selector_3_01Lhs_00_01Rhs_00_01Mode_00_01Upper_00_01RowMajor_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fsparse_5fselector',['sparse_solve_triangular_sparse_selector',['../structEigen_1_1internal_1_1sparse__solve__triangular__sparse__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fsparse_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20uplo_2c_20colmajor_20_3e',['sparse_solve_triangular_sparse_selector&lt; Lhs, Rhs, Mode, UpLo, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__solve__triangular__sparse__selector_3_01Lhs_00_01Rhs_00_01Mode_00_01UpLo_00_01ColMajor_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector',['sparse_sparse_product_with_pruning_selector',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20colmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_8fb9624b29ea478e133eb11c5f2cb9ae.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20colmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_285779f9870b7e339778d8c9d612d218.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20rowmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_818eb816416cb2ce1ae788aac29309be.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20rowmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_86b29bb9fc94a68f2c04a02141ac2d07.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20colmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_f352f8dd4fd84fbb7a4be5e84a7f5675.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20colmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_f96a1f31d7c531bcb062e19aed640a1a.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20rowmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_6d58fe4584107c73c02d251725236025.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20rowmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01Lhs_00_01Rhs_00_2e7be101e70412a2a2f736105bc3336a.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector',['sparse_sparse_to_dense_product_selector',['../structEigen_1_1internal_1_1sparse__sparse__to__dense__product__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20colmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, ColMajor, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01Lhs_00_01Rhs_00_01Re112fb0c3dbb404b95a8257b328114456.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20rowmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, ColMajor, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01Lhs_00_01Rhs_00_01Re0a7dda063d3add40671beb7e17ea9f62.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20colmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, RowMajor, ColMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01Lhs_00_01Rhs_00_01Re6669d184b74bd8598337c71e7155b382.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20rowmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, RowMajor, RowMajor &gt;',['../structEigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01Lhs_00_01Rhs_00_01Re67da0718ab589ea8a33fdd42170d877a.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl',['sparse_time_dense_product_impl',['../structEigen_1_1internal_1_1sparse__time__dense__product__impl.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20alphatype_2c_20colmajor_2c_20true_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, AlphaType, ColMajor, true &gt;',['../structEigen_1_1internal_1_1sparse__time__dense__product__impl_3_01SparseLhsType_00_01DenseRhsTyp0d3415422a64c8e08f4d34e09086a85a.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20typename_20denserestype_3a_3ascalar_2c_20colmajor_2c_20false_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, ColMajor, false &gt;',['../structEigen_1_1internal_1_1sparse__time__dense__product__impl_3_01SparseLhsType_00_01DenseRhsTyp173fa659c7e29b3400f6df61969f50d2.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20typename_20denserestype_3a_3ascalar_2c_20rowmajor_2c_20false_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, false &gt;',['../structEigen_1_1internal_1_1sparse__time__dense__product__impl_3_01SparseLhsType_00_01DenseRhsType1fae7a24848354b6b913a1d08f4e3c4.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20typename_20denserestype_3a_3ascalar_2c_20rowmajor_2c_20true_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true &gt;',['../structEigen_1_1internal_1_1sparse__time__dense__product__impl_3_01SparseLhsType_00_01DenseRhsTyp9a792d4ee9c75d9914d6c7ad20d0617b.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector',['sparse_vector_assign_selector',['../structEigen_1_1internal_1_1sparse__vector__assign__selector.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector_3c_20dest_2c_20src_2c_20sva_5finner_20_3e',['sparse_vector_assign_selector&lt; Dest, Src, SVA_Inner &gt;',['../structEigen_1_1internal_1_1sparse__vector__assign__selector_3_01Dest_00_01Src_00_01SVA__Inner_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector_3c_20dest_2c_20src_2c_20sva_5fouter_20_3e',['sparse_vector_assign_selector&lt; Dest, Src, SVA_Outer &gt;',['../structEigen_1_1internal_1_1sparse__vector__assign__selector_3_01Dest_00_01Src_00_01SVA__Outer_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector_3c_20dest_2c_20src_2c_20sva_5fruntimeswitch_20_3e',['sparse_vector_assign_selector&lt; Dest, Src, SVA_RuntimeSwitch &gt;',['../structEigen_1_1internal_1_1sparse__vector__assign__selector_3_01Dest_00_01Src_00_01SVA__RuntimeSwitch_01_4.html',1,'Eigen::internal']]],
  ['sparsecompressedbase',['SparseCompressedBase',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseCompressedBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseCompressedBase&lt; SparseVector&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e',['SparseCompressedBase&lt; Transpose&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsedenseouterproduct',['SparseDenseOuterProduct',['../classEigen_1_1SparseDenseOuterProduct.html',1,'Eigen']]],
  ['sparsedenseproductreturntype',['SparseDenseProductReturnType',['../structEigen_1_1SparseDenseProductReturnType.html',1,'Eigen']]],
  ['sparsediagonalproduct',['SparseDiagonalProduct',['../classEigen_1_1SparseDiagonalProduct.html',1,'Eigen']]],
  ['sparsefunctor',['SparseFunctor',['../structEigen_1_1SparseFunctor.html',1,'Eigen']]],
  ['sparsefunctor_3c_20scalar_2c_20int_20_3e',['SparseFunctor&lt; Scalar, int &gt;',['../structEigen_1_1SparseFunctor.html',1,'Eigen']]],
  ['sparsegaussiantest',['sparseGaussianTest',['../structsparseGaussianTest.html',1,'']]],
  ['sparselu',['SparseLU',['../classEigen_1_1SparseLU.html',1,'Eigen']]],
  ['sparseluimpl',['SparseLUImpl',['../classSparseLUImpl.html',1,'SparseLUImpl&lt; Scalar, StorageIndex &gt;'],['../classEigen_1_1internal_1_1SparseLUImpl.html',1,'Eigen::internal::SparseLUImpl&lt; Scalar, StorageIndex &gt;']]],
  ['sparseluimpl_3c_20_5fmatrixtype_3a_3ascalar_2c_20_5fmatrixtype_3a_3astorageindex_20_3e',['SparseLUImpl&lt; _MatrixType::Scalar, _MatrixType::StorageIndex &gt;',['../classEigen_1_1internal_1_1SparseLUImpl.html',1,'Eigen::internal']]],
  ['sparselumatrixlreturntype',['SparseLUMatrixLReturnType',['../structEigen_1_1SparseLUMatrixLReturnType.html',1,'Eigen']]],
  ['sparselumatrixureturntype',['SparseLUMatrixUReturnType',['../structEigen_1_1SparseLUMatrixUReturnType.html',1,'Eigen']]],
  ['sparsemapbase',['SparseMapBase',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_20_3e',['SparseMapBase&lt; Derived &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20readonlyaccessors_20_3e',['SparseMapBase&lt; Derived, ReadOnlyAccessors &gt;',['../classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20writeaccessors_20_3e',['SparseMapBase&lt; Derived, WriteAccessors &gt;',['../classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20map_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Map&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20map_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Map&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20const_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; const SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1SparseMapBase.html',1,'Eigen']]],
  ['sparsematrix',['SparseMatrix',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20double_20_3e',['SparseMatrix&lt; double &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_20_3e',['SparseMatrix&lt; Scalar &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_20_3e',['SparseMatrix&lt; Scalar, ColMajor &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20int_20_3e',['SparseMatrix&lt; Scalar, ColMajor, int &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20storageindex_20_3e',['SparseMatrix&lt; Scalar, ColMajor, StorageIndex &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_20_3e',['SparseMatrix&lt; Scalar, RowMajor &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_2c_20storageindex_20_3e',['SparseMatrix&lt; Scalar, RowMajor, StorageIndex &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_5ft_20_3e',['SparseMatrix&lt; scalar_t &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrixbase',['SparseMatrixBase',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrix_3c_20_5fscalar_2c_20_5fblockatcompiletime_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; BlockSparseMatrix&lt; _Scalar, _BlockAtCompileTime, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrix_3c_20_5fscalar_2c_20_5fblockatcompiletime_2c_20_5foptions_2c_20storageindex_20_3e_20_3e',['SparseMatrixBase&lt; BlockSparseMatrix&lt; _Scalar, _BlockAtCompileTime, _Options, StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrixt_20_3e',['SparseMatrixBase&lt; BlockSparseMatrixT &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20cwisebinaryop_3c_20binaryop_2c_20lhs_2c_20rhs_20_3e_20_3e',['SparseMatrixBase&lt; CwiseBinaryOp&lt; BinaryOp, Lhs, Rhs &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20dynamicsparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; DynamicSparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; SparseVector&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparseview_3c_20matrixtype_20_3e_20_3e',['SparseMatrixBase&lt; SparseView&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e',['SparseMatrixBase&lt; Transpose&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20triangularview_3c_20matrixtype_2c_20mode_20_3e_20_3e',['SparseMatrixBase&lt; TriangularView&lt; MatrixType, Mode &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparseqr',['SparseQR',['../classEigen_1_1SparseQR.html',1,'Eigen']]],
  ['sparseqr_5fqproduct',['SparseQR_QProduct',['../structEigen_1_1SparseQR__QProduct.html',1,'Eigen']]],
  ['sparseqrmatrixqreturntype',['SparseQRMatrixQReturnType',['../structEigen_1_1SparseQRMatrixQReturnType.html',1,'Eigen']]],
  ['sparseqrmatrixqtransposereturntype',['SparseQRMatrixQTransposeReturnType',['../structEigen_1_1SparseQRMatrixQTransposeReturnType.html',1,'Eigen']]],
  ['sparserefbase',['SparseRefBase',['../classEigen_1_1internal_1_1SparseRefBase.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1internal_1_1SparseRefBase.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20const_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; const SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1internal_1_1SparseRefBase.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1internal_1_1SparseRefBase.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../classEigen_1_1internal_1_1SparseRefBase.html',1,'Eigen::internal']]],
  ['sparseselfadjoint2sparse',['SparseSelfAdjoint2Sparse',['../structEigen_1_1internal_1_1SparseSelfAdjoint2Sparse.html',1,'Eigen::internal']]],
  ['sparseselfadjointshape',['SparseSelfAdjointShape',['../structEigen_1_1internal_1_1SparseSelfAdjointShape.html',1,'Eigen::internal']]],
  ['sparseselfadjointview',['SparseSelfAdjointView',['../classEigen_1_1SparseSelfAdjointView.html',1,'Eigen']]],
  ['sparseshape',['SparseShape',['../structEigen_1_1SparseShape.html',1,'Eigen']]],
  ['sparsesolverbase',['SparseSolverBase',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20bicgstab_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; BiCGSTAB&lt; _MatrixType, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmoddecomposition_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodDecomposition&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsimplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSimplicialLDLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsimplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSimplicialLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsupernodalllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSupernodalLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20conjugategradient_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; ConjugateGradient&lt; _MatrixType, _UpLo, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20dgmres_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; DGMRES&lt; _MatrixType, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20gmres_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; GMRES&lt; _MatrixType, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletecholesky_3c_20scalar_2c_20_5fuplo_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; IncompleteCholesky&lt; Scalar, _UpLo, _OrderingType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletelu_3c_20_5fscalar_20_3e_20_3e',['SparseSolverBase&lt; IncompleteLU&lt; _Scalar &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletelut_3c_20_5fscalar_2c_20_5fstorageindex_20_3e_20_3e',['SparseSolverBase&lt; IncompleteLUT&lt; _Scalar, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20leastsquaresconjugategradient_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; LeastSquaresConjugateGradient&lt; _MatrixType, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20minres_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; MINRES&lt; _MatrixType, _UpLo, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisoldlt_3c_20matrixtype_2c_20options_20_3e_20_3e',['SparseSolverBase&lt; PardisoLDLT&lt; MatrixType, Options &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisollt_3c_20matrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PardisoLLT&lt; MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisolu_3c_20matrixtype_20_3e_20_3e',['SparseSolverBase&lt; PardisoLU&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PastixLDLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PastixLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixlu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; PastixLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparselu_3c_20_5fmatrixtype_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; SparseLU&lt; _MatrixType, _OrderingType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparseqr_3c_20_5fmatrixtype_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; SparseQR&lt; _MatrixType, _OrderingType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20spqr_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SPQR&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SuperLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20umfpacklu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; UmfPackLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesparseproduct',['SparseSparseProduct',['../classEigen_1_1SparseSparseProduct.html',1,'Eigen']]],
  ['sparsesparseproductreturntype',['SparseSparseProductReturnType',['../structEigen_1_1SparseSparseProductReturnType.html',1,'Eigen']]],
  ['sparsesymmetricpermutationproduct',['SparseSymmetricPermutationProduct',['../classEigen_1_1SparseSymmetricPermutationProduct.html',1,'Eigen']]],
  ['sparsetimedenseproduct',['SparseTimeDenseProduct',['../classEigen_1_1SparseTimeDenseProduct.html',1,'Eigen']]],
  ['sparsetransposeimpl',['SparseTransposeImpl',['../classEigen_1_1internal_1_1SparseTransposeImpl.html',1,'Eigen::internal']]],
  ['sparsetransposeimpl_3c_20matrixtype_20_3e',['SparseTransposeImpl&lt; MatrixType &gt;',['../classEigen_1_1internal_1_1SparseTransposeImpl.html',1,'Eigen::internal']]],
  ['sparsetransposeimpl_3c_20matrixtype_2c_20compressedaccessbit_20_3e',['SparseTransposeImpl&lt; MatrixType, CompressedAccessBit &gt;',['../classEigen_1_1internal_1_1SparseTransposeImpl_3_01MatrixType_00_01CompressedAccessBit_01_4.html',1,'Eigen::internal']]],
  ['sparsetriangularshape',['SparseTriangularShape',['../structEigen_1_1internal_1_1SparseTriangularShape.html',1,'Eigen::internal']]],
  ['sparsevector',['SparseVector',['../classEigen_1_1SparseVector.html',1,'Eigen']]],
  ['sparseview',['SparseView',['../classEigen_1_1SparseView.html',1,'Eigen']]],
  ['sparsexprinneriterator',['SparseXprInnerIterator',['../classSparseXprInnerIterator.html',1,'']]],
  ['spline',['Spline',['../classEigen_1_1Spline.html',1,'Eigen']]],
  ['splinefitting',['SplineFitting',['../structEigen_1_1SplineFitting.html',1,'Eigen']]],
  ['splinetraits',['SplineTraits',['../structEigen_1_1SplineTraits.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_20_3e',['SplineTraits&lt; Spline &gt;',['../structEigen_1_1SplineTraits.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20_5fscalar_2c_20_5fdim_2c_20_5fdegree_20_3e_20_3e',['SplineTraits&lt; Spline&lt; _Scalar, _Dim, _Degree &gt; &gt;',['../structEigen_1_1SplineTraits.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20_5fscalar_2c_20_5fdim_2c_20_5fdegree_20_3e_2c_20_5fderivativeorder_20_3e',['SplineTraits&lt; Spline&lt; _Scalar, _Dim, _Degree &gt;, _DerivativeOrder &gt;',['../structEigen_1_1SplineTraits_3_01Spline_3_01__Scalar_00_01__Dim_00_01__Degree_01_4_00_01__DerivativeOrder_01_4.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20_5fscalar_2c_20_5fdim_2c_20_5fdegree_20_3e_2c_20dynamic_20_3e',['SplineTraits&lt; Spline&lt; _Scalar, _Dim, _Degree &gt;, Dynamic &gt;',['../structEigen_1_1SplineTraits_3_01Spline_3_01__Scalar_00_01__Dim_00_01__Degree_01_4_00_01Dynamic_01_4.html',1,'Eigen']]],
  ['spqr',['SPQR',['../classEigen_1_1SPQR.html',1,'Eigen']]],
  ['spqr_5fqproduct',['SPQR_QProduct',['../structEigen_1_1SPQR__QProduct.html',1,'Eigen']]],
  ['spqrmatrixqreturntype',['SPQRMatrixQReturnType',['../structEigen_1_1SPQRMatrixQReturnType.html',1,'Eigen']]],
  ['spqrmatrixqtransposereturntype',['SPQRMatrixQTransposeReturnType',['../structEigen_1_1SPQRMatrixQTransposeReturnType.html',1,'Eigen']]],
  ['state',['State',['../classState.html',1,'']]],
  ['statement',['statement',['../classsqlite_1_1statement.html',1,'sqlite']]],
  ['stateone',['StateOne',['../classStateOne.html',1,'']]],
  ['states_5fset',['states_set',['../structstates__set.html',1,'']]],
  ['states_5fset_3c_20stateone_20_3e',['states_set&lt; StateOne &gt;',['../structstates__set.html',1,'']]],
  ['states_5fset_3c_20statetwo_20_3e',['states_set&lt; StateTwo &gt;',['../structstates__set.html',1,'']]],
  ['statetwo',['StateTwo',['../classStateTwo.html',1,'']]],
  ['static_5fassertion',['static_assertion',['../structEigen_1_1internal_1_1static__assertion.html',1,'Eigen::internal']]],
  ['static_5fassertion_3c_20true_20_3e',['static_assertion&lt; true &gt;',['../structEigen_1_1internal_1_1static__assertion_3_01true_01_4.html',1,'Eigen::internal']]],
  ['static_5fsize_5fgenerator',['static_size_generator',['../structstatic__size__generator.html',1,'']]],
  ['static_5fsize_5fgenerator_3c_201_2c_20perf_5fanalyzer_2c_20action_2c_20interface_20_3e',['static_size_generator&lt; 1, Perf_Analyzer, Action, Interface &gt;',['../structstatic__size__generator_3_011_00_01Perf__Analyzer_00_01Action_00_01Interface_01_4.html',1,'']]],
  ['static_5fval',['static_val',['../structEigen_1_1internal_1_1static__val.html',1,'Eigen::internal']]],
  ['staticif',['StaticIf',['../structutility_1_1tuple_1_1StaticIf.html',1,'utility::tuple']]],
  ['staticif_3c_20true_2c_20t_20_3e',['StaticIf&lt; true, T &gt;',['../structutility_1_1tuple_1_1StaticIf_3_01true_00_01T_01_4.html',1,'utility::tuple']]],
  ['staticsgroup',['StaticSGroup',['../classEigen_1_1StaticSGroup.html',1,'Eigen']]],
  ['stdmaptraits',['StdMapTraits',['../structEigen_1_1StdMapTraits.html',1,'Eigen']]],
  ['stem_5ffunction',['stem_function',['../structEigen_1_1internal_1_1stem__function.html',1,'Eigen::internal']]],
  ['stl_5finterface',['STL_interface',['../classSTL__interface.html',1,'']]],
  ['stl_5fperf_5fanalyzer',['STL_Perf_Analyzer',['../classSTL__Perf__Analyzer.html',1,'']]],
  ['stl_5ftimer',['STL_Timer',['../classSTL__Timer.html',1,'']]],
  ['stlthreadenvironment',['StlThreadEnvironment',['../structEigen_1_1StlThreadEnvironment.html',1,'Eigen']]],
  ['storage_5fkind_5fto_5fevaluator_5fkind',['storage_kind_to_evaluator_kind',['../structEigen_1_1internal_1_1storage__kind__to__evaluator__kind.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fevaluator_5fkind_3c_20sparse_20_3e',['storage_kind_to_evaluator_kind&lt; Sparse &gt;',['../structEigen_1_1internal_1_1storage__kind__to__evaluator__kind_3_01Sparse_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape',['storage_kind_to_shape',['../structEigen_1_1internal_1_1storage__kind__to__shape.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20dense_20_3e',['storage_kind_to_shape&lt; Dense &gt;',['../structEigen_1_1internal_1_1storage__kind__to__shape_3_01Dense_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20diagonalshape_20_3e',['storage_kind_to_shape&lt; DiagonalShape &gt;',['../structEigen_1_1internal_1_1storage__kind__to__shape_3_01DiagonalShape_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20permutationstorage_20_3e',['storage_kind_to_shape&lt; PermutationStorage &gt;',['../structEigen_1_1internal_1_1storage__kind__to__shape_3_01PermutationStorage_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20solverstorage_20_3e',['storage_kind_to_shape&lt; SolverStorage &gt;',['../structEigen_1_1internal_1_1storage__kind__to__shape_3_01SolverStorage_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20sparse_20_3e',['storage_kind_to_shape&lt; Sparse &gt;',['../structEigen_1_1internal_1_1storage__kind__to__shape_3_01Sparse_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20transpositionsstorage_20_3e',['storage_kind_to_shape&lt; TranspositionsStorage &gt;',['../structEigen_1_1internal_1_1storage__kind__to__shape_3_01TranspositionsStorage_01_4.html',1,'Eigen::internal']]],
  ['stride',['Stride',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e',['Stride&lt; 0, Value &gt;',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_20stridetype_3a_3aouterstrideatcompiletime_2c_20stridetype_3a_3ainnerstrideatcompiletime_20_3e',['Stride&lt; StrideType::OuterStrideAtCompileTime, StrideType::InnerStrideAtCompileTime &gt;',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_20value_2c_200_20_3e',['Stride&lt; Value, 0 &gt;',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stridedalignedmaptype',['StridedAlignedMapType',['../structEigen_1_1PlainObjectBase_1_1StridedAlignedMapType.html',1,'Eigen::PlainObjectBase']]],
  ['stridedconstalignedmaptype',['StridedConstAlignedMapType',['../structEigen_1_1PlainObjectBase_1_1StridedConstAlignedMapType.html',1,'Eigen::PlainObjectBase']]],
  ['stridedconstmaptype',['StridedConstMapType',['../structEigen_1_1PlainObjectBase_1_1StridedConstMapType.html',1,'Eigen::PlainObjectBase']]],
  ['stridedmaptype',['StridedMapType',['../structEigen_1_1PlainObjectBase_1_1StridedMapType.html',1,'Eigen::PlainObjectBase']]],
  ['strip_5fidentities',['strip_identities',['../structEigen_1_1internal_1_1group__theory_1_1strip__identities.html',1,'Eigen::internal::group_theory']]],
  ['strip_5fidentities_3c_20equality_2c_20id_2c_20type_5flist_3c_20eigen_5ftpl_5fpp_5fspec_5fhack_5fuse_28ts_29_3e_20_3e',['strip_identities&lt; Equality, id, type_list&lt; EIGEN_TPL_PP_SPEC_HACK_USE(ts)&gt; &gt;',['../structEigen_1_1internal_1_1group__theory_1_1strip__identities_3_01Equality_00_01id_00_01type__li0f75648c980077c83280d356a1140bae.html',1,'Eigen::internal::group_theory']]],
  ['strip_5fidentities_3c_20equality_2c_20id_2c_20type_5flist_3c_20t_2c_20ts_2e_2e_2e_20_3e_20_3e',['strip_identities&lt; Equality, id, type_list&lt; t, ts... &gt; &gt;',['../structEigen_1_1internal_1_1group__theory_1_1strip__identities_3_01Equality_00_01id_00_01type__li49140c6a9028b86805968b1d3f5e598f.html',1,'Eigen::internal::group_theory']]],
  ['sub',['sub',['../structEigen_1_1internal_1_1generic__product__impl_3_01Lhs_00_01Rhs_00_01DenseShape_00_01DenseSha6c6b8971a8be3974a451e3d7d26ac07a.html',1,'Eigen::internal::generic_product_impl&lt; Lhs, Rhs, DenseShape, DenseShape, OuterProduct &gt;']]],
  ['sub_5fassign_5fop',['sub_assign_op',['../structEigen_1_1internal_1_1sub__assign__op.html',1,'Eigen::internal']]],
  ['sum_5fop',['sum_op',['../structEigen_1_1internal_1_1sum__op.html',1,'Eigen::internal']]],
  ['sumreducer',['SumReducer',['../structEigen_1_1internal_1_1SumReducer.html',1,'Eigen::internal']]],
  ['superlu',['SuperLU',['../classEigen_1_1SuperLU.html',1,'Eigen']]],
  ['superlubase',['SuperLUBase',['../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SuperLUBase&lt; _MatrixType, SuperLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['svd_5fprecondition_5f2x2_5fblock_5fto_5fbe_5freal',['svd_precondition_2x2_block_to_be_real',['../structEigen_1_1internal_1_1svd__precondition__2x2__block__to__be__real.html',1,'Eigen::internal']]],
  ['svd_5fprecondition_5f2x2_5fblock_5fto_5fbe_5freal_3c_20matrixtype_2c_20qrpreconditioner_2c_20false_20_3e',['svd_precondition_2x2_block_to_be_real&lt; MatrixType, QRPreconditioner, false &gt;',['../structEigen_1_1internal_1_1svd__precondition__2x2__block__to__be__real_3_01MatrixType_00_01QRPreconditioner_00_01false_01_4.html',1,'Eigen::internal']]],
  ['svd_5fprecondition_5f2x2_5fblock_5fto_5fbe_5freal_3c_20matrixtype_2c_20qrpreconditioner_2c_20true_20_3e',['svd_precondition_2x2_block_to_be_real&lt; MatrixType, QRPreconditioner, true &gt;',['../structEigen_1_1internal_1_1svd__precondition__2x2__block__to__be__real_3_01MatrixType_00_01QRPreconditioner_00_01true_01_4.html',1,'Eigen::internal']]],
  ['svdbase',['SVDBase',['../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20bdcsvd_3c_20_5fmatrixtype_20_3e_20_3e',['SVDBase&lt; BDCSVD&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20jacobisvd_3c_20_5fmatrixtype_2c_20qrpreconditioner_20_3e_20_3e',['SVDBase&lt; JacobiSVD&lt; _MatrixType, QRPreconditioner &gt; &gt;',['../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['swap_5fassign_5fop',['swap_assign_op',['../structEigen_1_1internal_1_1swap__assign__op.html',1,'Eigen::internal']]],
  ['swap_5fassign_5fop_3c_20dstevaluatortypet_3a_3ascalar_20_3e',['swap_assign_op&lt; DstEvaluatorTypeT::Scalar &gt;',['../structEigen_1_1internal_1_1swap__assign__op.html',1,'Eigen::internal']]],
  ['swapwrapper',['SwapWrapper',['../classEigen_1_1SwapWrapper.html',1,'Eigen']]],
  ['syclgenericbufferreducer',['syclGenericBufferReducer',['../structEigen_1_1internal_1_1syclGenericBufferReducer.html',1,'Eigen::internal']]],
  ['symm_5fpack_5flhs',['symm_pack_lhs',['../structEigen_1_1internal_1_1symm__pack__lhs.html',1,'Eigen::internal']]],
  ['symm_5fpack_5frhs',['symm_pack_rhs',['../structEigen_1_1internal_1_1symm__pack__rhs.html',1,'Eigen::internal']]],
  ['symmetry',['Symmetry',['../structSymmetry.html',1,'Symmetry'],['../structEigen_1_1Symmetry.html',1,'Eigen::Symmetry&lt; One_, Two_ &gt;']]],
  ['systembase',['SystemBase',['../classSystemBase.html',1,'']]],
  ['systembase_3c_20stateone_20_3e',['SystemBase&lt; StateOne &gt;',['../classSystemBase.html',1,'']]],
  ['systembase_3c_20statetwo_20_3e',['SystemBase&lt; StateTwo &gt;',['../classSystemBase.html',1,'']]],
  ['systemone',['SystemOne',['../classSystemOne.html',1,'']]],
  ['systemtwo',['SystemTwo',['../classSystemTwo.html',1,'']]]
];
